### PR TITLE
httpie: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
@sjackman testbot still hasn't created a release for this PR and hasn't uploaded the bottle to bintray

**Comment by sjackman** [comment]
`bot.linuxbrew.sh` failed with this intermittent error:
```
To git@github.com:LinuxbrewTestBot/homebrew-core.git
! [remote rejected] master -> master (cannot lock ref 'refs/heads/master': ref refs/heads/master is at 87754413ca4a2e98c8faeea292ad914bbdd9b5ba but expected 3e2fee862e6d0fde203a21fa8be4ff0f5e3331cb)
! [remote rejected] pr-2390 (failed)
error: failed to push some refs to 'git@github.com:LinuxbrewTestBot/homebrew-core.git'
Error: Failure while executing: git push --force git@github.com:LinuxbrewTestBot/homebrew-core.git master:master :refs/tags/pr-2390
```

I'm not sure what causes it. You can trigger a new bottle push using:
```
http://bot.linuxbrew.sh/ci-upload/github.com/Linuxbrew/homebrew-core/pull/2390?keep-old=1
```

**Comment by maxim-belkin** [comment]
> `bot.linuxbrew.sh` failed with this intermittent error:

well, it was not intermittent :) but thanks for the solution :)

**Comment by sjackman** [comment]
I wouldn't call it a solution, but it's a workaround. If it's not intermittent, and the PR is behind master by more than 50 commits, try rebasing onto `origin/master`.

**Pull request closed without merging**
