### PR TITLE
gcc@4.9: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by iMichka** [comment]
You may want to align the content of the formula with the changes made for the other `gcc` formulae?

**Comment by sjackman** [comment]
CircleCI
```
/tmp/gcc@4.9-20180604-3531-1rbtq97/gcc-4.9.4/build/./gcc/xgcc -B/tmp/gcc@4.9-20180604-3531-1rbtq97/gcc-4.9.4/build/./gcc/ -B/home/linuxbrew/.linuxbrew/Cellar/gcc@4.9/4.9.4_1/x86_64-unknown-linux-gnu/bin/ -B/home/linuxbrew/.linuxbrew/Cellar/gcc@4.9/4.9.4_1/x86_64-unknown-linux-gnu/lib/ -isystem /home/linuxbrew/.linuxbrew/Cellar/gcc@4.9/4.9.4_1/x86_64-unknown-linux-gnu/include -isystem /home/linuxbrew/.linuxbrew/Cellar/gcc@4.9/4.9.4_1/x86_64-unknown-linux-gnu/sys-include    -g -O2 -O2  -g -O2 -DIN_GCC    -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wno-format -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include   -fpic -mlong-double-80 -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector   -fpic -mlong-double-80 -I. -I. -I../.././gcc -I../../../libgcc -I../../../libgcc/. -I../../../libgcc/../gcc -I../../../libgcc/../include -I../../../libgcc/config/libbid -DENABLE_DECIMAL_BID_FORMAT -DHAVE_CC_TLS  -DUSE_TLS -o _fixunssfdi.o -MT _fixunssfdi.o -MD -MP -MF _fixunssfdi.dep -DL_fixunssfdi -c ../../../libgcc/libgcc2.c -fvisibility=hidden -DHIDE_EXPORTS
In file included from /usr/include/stdio.h:27:0,
                 from ../../../../libgcc/../gcc/tsystem.h:87,
                 from ../../../../libgcc/libgcc2.c:27:
/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
compilation terminated.
Makefile:463: recipe for target '_negdi2.o' failed
```

**Comment by sjackman** [comment]
`/usr/include/x86_64-linux-gnu/sys/cdefs.h` is provided by `libc6-dev`
`/usr/include/sys/cdefs.h` is provided by `libc6-dev-i386`

**Comment by sjackman** [comment]
> You may want to align the content of the formula with the changes made for the other gcc formulae?

👍 Done.

**Comment by iMichka** [comment]
```
== /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gcc@4.9.rb ==
C:124:  9: Put a comma after the last item of a multiline array.
```

**Comment by iMichka** [comment]
```
checking for x86_64-unknown-linux-gnu-gcc... /tmp/gcc@4.9-20180604-3505-by0kmt/gcc-4.9.4/build/./gcc/xgcc -B/tmp/gcc@4.9-20180604-3505-by0kmt/gcc-4.9.4/build/./gcc/ -B/home/linuxbrew/.linuxbrew/Cellar/gcc@4.9/4.9.4_1/x86_64-unknown-linux-gnu/bin/ -B/home/linuxbrew/.linuxbrew/Cellar/gcc@4.9/4.9.4_1/x86_64-unknown-linux-gnu/lib/ -isystem /home/linuxbrew/.linuxbrew/Cellar/gcc@4.9/4.9.4_1/x86_64-unknown-linux-gnu/include -isystem /home/linuxbrew/.linuxbrew/Cellar/gcc@4.9/4.9.4_1/x86_64-unknown-linux-gnu/sys-include   
checking for suffix of object files... configure: error: in `/tmp/gcc@4.9-20180604-3505-by0kmt/gcc-4.9.4/build/x86_64-unknown-linux-gnu/libgcc':
configure: error: cannot compute suffix of object files: cannot compile
See `config.log' for more details.
```

**Comment by sjackman** [comment]
CircleCI
```
configure:3353: checking for C compiler version
configure:3362: /tmp/gcc@4.9-20180604-2041-14ti8kb/gcc-4.9.4/build/./gcc/xgcc -B/tmp/gcc@4.9-20180604-2041-14ti8kb/gcc-4.9.4/build/./gcc/ -B/home/linuxbrew/.linuxbrew/Cellar/gcc@4.9/4.9.4_1/x86_64-unknown-linux-gnu/bin/ -B/home/linuxbrew/.linuxbrew/Cellar/gcc@4.9/4.9.4_1/x86_64-unknown-linux-gnu/lib/ -isystem /home/linuxbrew/.linuxbrew/Cellar/gcc@4.9/4.9.4_1/x86_64-unknown-linux-gnu/include -isystem /home/linuxbrew/.linuxbrew/Cellar/gcc@4.9/4.9.4_1/x86_64-unknown-linux-gnu/sys-include    --version >&5
/tmp/gcc@4.9-20180604-2041-14ti8kb/gcc-4.9.4/libgcc/configure: line 3364:   772 Segmentation fault      (core dumped) $CC --version 1>&5
configure:3373: $? = 139
```
So the compiled GCC (`xgcc`) is segfaulting, but I can't say why. There's no brewed GLIBC or brewed GCC installed. It also segfaults when I run `xgcc --version`.
```
/tmp/gcc@4.9-20180604-2041-14ti8kb/gcc-4.9.4/build/./gcc/xgcc --version
Segmentation fault (core dumped)
```

**Comment by sjackman** [comment]
```
❯❯❯ /home/linuxbrew/.linuxbrew/bin/patchelf --print-interpreter /tmp/gcc@4.9-20180604-2041-14ti8kb/gcc-4.9.4/build/./gcc/xgcc
/home/linuxbrew/.linuxbrew/lib/ld.so
❯❯❯ /home/linuxbrew/.linuxbrew/bin/patchelf --print-rpath /tmp/gcc@4.9-20180604-2041-14ti8kb/gcc-4.9.4/build/./gcc/xgcc
/home/linuxbrew/.linuxbrew/Cellar/gcc@4.9/4.9.4_1/lib:/home/linuxbrew/.linuxbrew/lib:/home/linuxbrew/.linuxbrew/opt/zlib/lib:/home/linuxbrew/.linuxbrew/opt/binutils/lib
```

**Comment by sjackman** [comment]
I get the same segfault with `brew install --env=std gcc@4.9`.
There was a built built for `gcc@4.9` 4.9.4 last year, so this regression is somewhat recent.
https://bintray.com/linuxbrew/bottles/gcc%3A4.9/4.9.4#files

**Comment by sjackman** [comment]
@xu-cheng Any thoughts on this issue with GCC 4.9.4 segfaulting while it's being compiled? It's reproducible in Docker with `linuxbrew/linuxbrew`.

**Comment by sjackman** [comment]
Here's the GDB backtrace. It's segfaulting in `set_multilib_dir`. Interesting since `multilib` is disabled.
```
(gdb) bt
#0  0x00007f59289d2532 in __GI___libc_free (mem=0x49060a) at malloc.c:2967
#1  0x00000000004133e1 in set_multilib_dir () at ../../gcc/gcc.c:7821
#2  0x00000000004105e4 in main (argc=2, argv=0x7ffc4fcca308)
    at ../../gcc/gcc.c:6682
```

**Comment by sjackman** [comment]
It looks as though the segfault is fixed by adding a dot here:
```diff
-inreplace "gcc/config/i386/t-linux64", "m64=../lib64", "m64="
+inreplace "gcc/config/i386/t-linux64", "m64=../lib64", "m64=."
```

**Comment by sjackman** [comment]
Thanks for merging, Michka!

**Comment by xu-cheng** [comment]
Sorry for the late response. Glad that you figure it out.

I spot a small mistake in the formula.
`libdir = HOMEBREW_PREFIX/"lib/gcc/6"` should be `libdir = HOMEBREW_PREFIX/"lib/gcc/4.9"`

**Comment by iMichka** [comment]
Nice catch. Fixed by 1069013e0c9897c9c70d7aa2641f8f727780563a

**Pull request closed without merging**
