### PR TITLE
ghc: Build a bottle for Linuxbrew: ghc-pwd: Syntax error: Unterminated quoted string

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
checking for path to top of build tree... utils/ghc-pwd/dist-install/build/tmp/ghc-pwd: 12: utils/ghc-pwd/dist-install/build/tmp/ghc-pwd: Syntax error: Unterminated quoted string
configure: error: cannot determine current directory
```

**Comment by rwhogg** [comment]
Looks like an issue came up regarding this: #851

**Comment by sjackman** [comment]
```
ghc-pkg: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/182449508#L1605

**Comment by sjackman** [comment]
Circle timed out: `took more than 120 minutes to run`

**Comment by sjackman** [comment]
It timed out (>120 min) on Circle, but on my Mac Pro it built in under an hour in Docker.
```
real	55m22.990s
user	111m24.170s
sys	10m57.500s
```

**Pull request closed without merging**
