### PR TITLE
wine: Build a bottle for Linuxbrew: checking whether the C compiler works... no

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
Blocked by gnutls #84

**Comment by sjackman** [comment]
Triggered a rebuild of Circle and Travis

**Comment by sjackman** [comment]
Sigh.

**Comment by Luthaf** [comment]
Same error locally, I fixed this one by putting linuxbrew gcc before the system gcc in the path. I still have issues about libpam not found locally, but if I can get a bottle I'll be happy!

**Comment by sjackman** [comment]
Perhaps it `fails_with :gcc => 4.8`
@Luthaf Could you please `brew gist-logs wine` with the failed build so that we can see `config.log`?

**Comment by Luthaf** [comment]
It is not actually wine itself who fails, but dependencies. The first one was `util-linux` (here is the log: https://gist.github.com/anonymous/2cfbc08b0e35db8a7d8dfb27829754b6), I patched the formula to remove the binaries needing libpam, and then another dependency was failling.

Here is the linker error: https://gist.github.com/anonymous/2cfbc08b0e35db8a7d8dfb27829754b6#file-02-make-L901-L902

I do have libpam and libpam_misc installed on my system, but not by linuxbrew:

```
$ locate libpam
/usr/lib/libpam.so.0
/usr/lib/libpam.so.0.83.1
/usr/lib/libpam_misc.so.0
/usr/lib/libpam_misc.so.0.82.0
/usr/lib/libpamc.so.0
/usr/lib/libpamc.so.0.82.1
/usr/lib64/libpam.so
/usr/lib64/libpam.so.0
/usr/lib64/libpam.so.0.83.1
/usr/lib64/libpam_misc.so
/usr/lib64/libpam_misc.so.0
/usr/lib64/libpam_misc.so.0.82.0
/usr/lib64/libpamc.so
/usr/lib64/libpamc.so.0
/usr/lib64/libpamc.so.0.82.1
/usr/share/doc/pam-devel-1.1.8/html/adg-libpam-functions.html
/usr/share/doc/pam-devel-1.1.8/html/adg-libpam_misc.html
```

Do you prefer that I open a separated issue about this?

**Comment by sjackman** [comment]
Yes, please open a new issue that `util-linux` depends on `pam`. Somewhere there's an issue discussing this dependency, but I can't seem to find it at the moment. The user also include the list of programs that must be disabled at the `configure` stage to remove the dependency on `pam`.
There are related issues at
https://github.com/Linuxbrew/homebrew-core/pull/1186
https://github.com/Linuxbrew/homebrew-core/pull/1524

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `util-linux`.
Another possible workaround for you is `brew install --force-bottle util-linux`, but no promises.

**Comment by sjackman** [comment]
Superseded by https://github.com/Linuxbrew/homebrew-core/pull/2397

**Pull request closed without merging**
