### PR TITLE
guile: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
from local attempt to build using `test-bot-docker`:

```
./autogen.sh: 30: ./autogen.sh: flex: not found
```

**Comment by sjackman** [comment]
Both TravisCI and CircleCI timed out.
```
==> make install
...
command umask 022; PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"; eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"; brew install patchelf && brew tap homebrew/dupes && brew tap linuxbrew/xorg && brew test-bot --tap=homebrew/core --keep-old took more than 10 minutes since last output
```

**Comment by rwhogg** [comment]
I'm retrying this with a local `test-bot-docker`. With any luck, it'll work this time and we'll finally be able to bottle this.

**Comment by rwhogg** [comment]
After merging #1939, I now get this:

```
/tmp/guile-20170304-1886-y9c7os/build-aux/missing: line 81: makeinfo: command not found
```

Texinfo isn't listed as a dependency at http://git.savannah.gnu.org/gitweb/?p=guile.git;a=blob;f=HACKING;h=f3011d93228a148704f9c52db496a0edfbdc16a2;hb=HEAD . 

Not sure what the deal is here.

**Comment by sjackman** [comment]
```ruby
depends-on "texinfo" => :build unless OS.mac?
```
?

**Comment by maxim-belkin** [comment]
This currently blocks #2056

**Comment by maxim-belkin** [comment]
no output in 10 minutes. building locally

**Pull request closed without merging**
