### PR TITLE
gsettings-desktop-schemas: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
checking for XML::Parser... configure: error: XML::Parser perl module is required for intltool

==> Formula
Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gsettings-desktop-schemas.rb
```

**Comment by iMichka** [comment]
Actually that error pops up for multiple other formulae, see for example #4191.

@rwhogg @sjackman do you think the xml::parser should be vendored in `intltool`, or does it need to be vendored for each formula that depends on `intltool`?

**Comment by rwhogg** [comment]
My gut feeling is that we should vendor it in for `intltool`, but this definitely needs some thought.

**Comment by iMichka** [comment]
`intltool` does already vendor xml parser. But seems that the other formulae do not pick that up, which would make sense.

Also:
```
failed: brew linkage --test gsettings-desktop-schemas

        System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libexpat.so.1
No broken dylib links
Unwanted system libraries:
  libexpat.so.1
```

**Comment by sjackman** [comment]
> do you think the xml::parser should be vendored in intltool, or does it need to be vendored for each formula that depends on intltool?

That's the way that it looks right now, but I'd rather avoid that solution if possible. It'd be better if a formula depends on `intltool`, it is also able to detect that `XML::Parser` is installed. One possible solution would be creating a formula for XML::Parser and link it into the top-level.

**Comment by iMichka** [comment]
Yes, that is the long term solution I think. I merged this change because we have tens of formulae that were depending on `gsettings-desktop-schemas`, and that were now failing. I think we need to find a more general solution for `XML::Parser` as it is being used by a lot of formulae right now.

**Comment by sjackman** [comment]
I need to look into it a bit further. If a formula depends on `intltool` and does not itself directly depend on `XML::Parser` (only indirectly through `intltool`), then it *shouldn't* itself need to know anything about `XML::Parser`. That idealized view and reality may conflict.

**Comment by iMichka** [comment]
Actually I started vendoring `XML::Parser` in some formulae that complained about that lately. But this  feels wrong ... there are 78 formulae that depend on `intltool` ...

**Comment by sjackman** [comment]
Let's avoid doing it for every formula that depends on `intltool`. We need a better solution.

**Pull request closed without merging**
