### PR TITLE
CI: also test changes with Homebrew/brew

### PR DESCRIPTION
**Pull request by jonchang**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Since we are preparing for a migration to Homebrew/brew it's probably
best that we also test all changes in this repository against it.

### CODE REVIEW

**Comment by iMichka** [comment]
You know that I never opened the Travis build since at least one year? 😅

**Comment by jonchang** [comment]
Let's make the change to Circle then so you'll be forced to 🙂

**Comment by iMichka** [comment]
Does this mean that the build and everything runs twice? I would like to avoid that. Some builds may time out, and I also prefer shorter build times to be more efficient.

**Comment by jonchang** [comment]
What if we passed `--fast` to circle? It wouldn't run install but would still run e.g. audit.

**Comment by iMichka** [comment]
Yes this could be ok. We can revert it if I feel it is too annoying.

**Comment by sjackman** [comment]
I'm hesitant to make the CircleCI builds any longer than they currently are. If we did do this, I'd be inclined to either use just TravisCI for this purpose. I don't really feel that it's necessary for this check to be part of our standard CI though.

**Comment by iMichka** [comment]
Yes, maybe we should not do that. As the diff between both repositories shrinks, the testing is still done by Linuxbrew/brew.

**Comment by sjackman** [comment]
Thanks, Jon, but I'll pass on this PR.

**Pull request closed without merging**
