### PR TITLE
bc: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by rwhogg** [comment]
Travis failed because of `brew linkage --test` (https://travis-ci.org/Linuxbrew/homebrew-core/builds/221367975#L2927):

```
Missing libraries:
  libfl.so.2
```

**Comment by sjackman** [comment]
I think that library is provided by `flex`.

**Comment by maxim-belkin** [comment]
circle installs a bunch of stuff:
```
=> brew fetch --retry bison flex gettext gpatch help2man libxml2 m4 ncurses pkg-config texinfo xz zlib
```

**Comment by maxim-belkin** [comment]
going to try adding here `depends_on "flex" unless OS.mac?`

**Comment by maxim-belkin** [comment]
nice PR number: 2345 :D

**Pull request closed without merging**
