### PR TITLE
grafana: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
==> node_modules/grunt-cli/bin/grunt build
�[31m16 09 2017 17:06:12.921:ERROR [launcher]: �[39mCannot start PhantomJS
	
�[32m16 09 2017 17:06:12.924:INFO [launcher]: �[39mTrying to start PhantomJS again (1/2).
�[31m16 09 2017 17:06:12.936:ERROR [phantomjs.launcher]: �[39m/tmp/grafana-20170916-4351-1k3360e/grafana-4.5.1/src/github.com/grafana/grafana/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory
```

**Comment by iMichka** [comment]
Annoying. `fontconfig` is installed. And grafana had a bottle before. I have no clue how to pass the library path to grunt.

**Comment by iMichka** [comment]
Rebased

**Comment by JuPlutonic** [comment]
```
brew unlink freetype
 (fontconfig) 
brew reinstall phantomjs
(2.1.1)
brew link freetype
```
Didn't help?

**Comment by iMichka** [comment]
I see, I need a working phantomjs bottle first. Let's rebuild that first: #5022

**Comment by iMichka** [comment]
Needs to be rebased: #5198

**Pull request closed without merging**
