### PR TITLE
llvm: Build a bottle for Linuxbrew: took more than 120 minutes to run

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
Travis `The job exceeded the maximum time limit for jobs, and has been terminated.`

**Comment by sjackman** [comment]
Circle `took more than 120 minutes to run`

**Comment by sjackman** [comment]
@Linuxbrew/core It'd be fantastic to bottle `llvm` and `clang` for Linuxbrew. Any thoughts on how to get this build to complete in two hours? Bottle it manually?

**Comment by timotheecour** [comment]
ping: any update?

**Comment by sjackman** [comment]
@maxim-belkin has bottled `llvm` in PR #1202. Nice work, Maxim!

**Pull request closed without merging**
