### PR TITLE
Merge 2017-08-19 c437f35

### PR DESCRIPTION
**Pull request by rwhogg**
No conflicts, since all of the formulae here are homebrew/science imports.

### CODE REVIEW

**Comment by iMichka** [comment]
If I remember well got, gmt@4 and hypre had Linux bottles. We may need to add some tweaks here and there to make them work.

**Comment by rwhogg** [comment]
> If I remember well got, gmt@4 and hypre had Linux bottles. We may need to add some tweaks here and there to make them work.

If you look at my final commit, I changed `hypre` substantially to restore some of the stuff that was stripped out from homebrew/core.

The only other pertinent change (relative to when the imports happened) was to `ampl-mp`, where I only had to do a minor tweak.

`gmt`, `gmt@4`, and `libmatio` required no changes at all.

**Comment by iMichka** [comment]
If I use `linuxbrew pull`, the merge commit is lost. I think you can't put commits like that on top of a merge for our workflow.
I made a new merge PR here: #3903

Closing this one without merging. I'll cherry-pick your changes to separate PRs.

**Comment by iMichka** [comment]
#3904 
#3905
#3906
#3907
#3908

**Comment by rwhogg** [comment]
> I think you can't put commits like that on top of a merge for our workflow.

Hmm, I seem to recall something similar happening before. That would explain a lot, thanks!

**Pull request closed without merging**
