### PR TITLE
genometools: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
CircleCI on Linux
```
[compile canvas_cairo.o]
[compile canvas_cairo_context.o]
[compile canvas_cairo_file.o]
…
In file included from src/annotationsketch/canvas_cairo_context.c:30:0:
/tmp/genometools-20180416-15546-1njkmy2/genometools-1.5.10/src/annotationsketch/canvas_cairo_context.h:21:19: fatal error: cairo.h: No such file or directory
compilation terminated.
Makefile:821: recipe for target 'obj/src/annotationsketch/canvas_cairo_context.o' failed
```
https://circleci.com/gh/Linuxbrew/homebrew-core/15500
https://circleci.com/api/v1.1/project/github/Linuxbrew/homebrew-core/15500/output/111/0?file=true

**Comment by sjackman** [comment]
Very strange. The formula depends on `cairo`. It works locally for me. I haven't yet tried it in a Docker container.

**Comment by sjackman** [comment]
One hack fix is to disable `cairo` on Linux.
See https://github.com/ilovezfs/homebrew-science/blob/10b21695981ceccd760ee96d445e265da0ddc7da/genometools.rb#L33
I'd want to do more troubleshooting before resorting to that.

**Comment by sjackman** [comment]
`cairo.h` is in a subdirectory `include/cairo/cairo.h`. Perhaps that's related.
```
/home/linuxbrew/.linuxbrew/Cellar/cairo/1.14.12_2/include/cairo/cairo.h
```

**Comment by sbfnk** [comment]
It doesn't work locally for me because pkg-config fails for cairo, similar to https://github.com/Linuxbrew/homebrew-core/issues/6931. Adding `depends_on "linuxbrew/xorg/libpthread-stubs" unless OS.mac?` has fixed it for me.

**Comment by iMichka** [comment]
A pr would be welcome.

@sjackman it took me months to migrate from `:x11` to plain formula dependencies: the migration is not completely done but I made good progress. We can go back the old way, but I still would prefer to keep plain dependencies.

Also, `libpthread-stubs` is not installed by `xorg` anymore. We have also a bunch of `proto` formula that sometimes need to be added; they are marked as necessary for pkgconfig. We had a discussion with @maxim-belkin about that, and sort of decided to use `"linuxbrew/xorg/libpthread-stubs" unless OS.mac?` when needed.

**Comment by sjackman** [comment]
> it took me months to migrate from :x11 to plain formula dependencies: the migration is not completely done but I made good progress. We can go back the old way, but I still would prefer to keep plain dependencies.

Ah, okay. I didn't realize that. Whichever you prefer is fine by me.

Is `linuxbrew/xorg/libpthread-stubs` a build-time or run-time dependency? If it's a run-time dependency, I feel it should probably be a dependency of `linuxbrew/xorg/xorg`. If it's a build-time dependency, then perhaps there should be a `linuxbrew/xorg/xorg-dev` package that provides the common build time dependencies.

**Comment by maxim-belkin** [comment]
There is literally nothing useful in `libpthread-stubs` (just the `.pc` file) so unless we're talking about some sadists, it shouldn't be a run-time dependency.
Not sure about `xorg-dev`. It's a good idea but what to include in it?

**Comment by iMichka** [comment]
Superseded by #7234. But we can continue the discussion to see if we can come up with a better solution.

**Comment by sjackman** [comment]
> There is literally nothing useful in libpthread-stubs (just the .pc file) so unless we're talking about some sadists, it shouldn't be a run-time dependency.

If it's only a single `pc` file, I think it's simpler then to make `libpthread-stubs` a normal dependency of `linuxbrew/xorg/xorg` to prevent these sorts of build failures. I know it's not truly a run-time dependency, but it seems the easier solution.

**Comment by iMichka** [comment]
I am fine with that solution too. I thought it was just needed in 2 or 3 formulae at the beginning, but it turns out it is needed almost everywhere.

I'll add it to xorg (with a comment why this is needed), and remove the dependency from all the formulae where it was added manually.

**Comment by iMichka** [comment]
See https://github.com/Linuxbrew/homebrew-xorg/pull/373

**Comment by sjackman** [comment]
Thanks, Michka!

**Pull request closed without merging**
