### PR TITLE
arpack: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by dpo** [comment]
It works for me locally if I explicitly link with `-lopenblas` in `build` and in `test`. The error may be coming from the fact that the CI installs `libblas_dev` but I'm not sure what BLAS `arpack` picks up.
```diff
diff --git a/Formula/arpack.rb b/Formula/arpack.rb
index e4846db302..a62799e912 100644
--- a/Formula/arpack.rb
+++ b/Formula/arpack.rb
@@ -16,13 +16,13 @@ class Arpack < Formula
   depends_on "libtool" => :build
 
   depends_on :fortran
-  depends_on "veclibfort"
+  depends_on "openblas"
   depends_on :mpi => [:optional, :f77]
 
   def install
     args = %W[ --disable-dependency-tracking
                --prefix=#{libexec}
-               --with-blas=-L#{Formula["veclibfort"].opt_lib}\ -lvecLibFort ]
+               --with-blas=-L#{Formula["openblas"].opt_lib}\ -lopenblas ]
 
     if build.with? "mpi"
       args << "F77=#{ENV["MPIF77"]}" << "--enable-mpi"
@@ -46,7 +46,7 @@ class Arpack < Formula
   test do
     ENV.fortran
     system ENV.fc, "-o", "test", pkgshare/"dnsimp.f", pkgshare/"mmio.f",
-                   "-L#{lib}", "-larpack", "-lvecLibFort"
+                   "-L#{lib}", "-larpack", "-lopenblas"
     cp_r pkgshare/"testA.mtx", testpath
     assert_match "reached", shell_output("./test")
```

**Comment by dpo** [comment]
A construct we've used in several formulae, e.g., `mumps.rb`, is the following:
```ruby
  depends_on "openblas" => OS.mac? ? :optional : :recommended
  depends_on "veclibfort" if build.without?("openblas") && OS.mac?
  # ...
  def install
  # ...
  if build.with? "openblas"
    make_args << "LIBBLAS=-L#{Formula["openblas"].opt_lib} -lopenblas"
  elsif build.with? "veclibfort"
    make_args << "LIBBLAS=-L#{Formula["veclibfort"].opt_lib} -lvecLibFort"
  else
    make_args << "LIBBLAS=-lblas -llapack"
  end
  # ...
  end
```

**Comment by sjackman** [comment]
@dpo A PR to replace this one is plenty welcome if you have the interest. If not I'll get to it later this week.

**Comment by dpo** [comment]
Closed by #3457.

**Pull request closed without merging**
