### PR TITLE
Merge 2017-08-03 29b6cd5fa6

### PR DESCRIPTION
**Pull request by iMichka**
+ [ ] expat
+ [ ] numpy
+ [ ] scipy

### CODE REVIEW

**Comment by iMichka** [comment]
Interesting. For `numpy`, as the revisions drifted apart, I wrote something like this:
```
revision 1 if OS.mac?
revision 2 unless OS.mac?
```
That mostly worked. The bottle got build with the right revision, but `linuxbrew pull` tried to pull the bottle with revision 1 instead of 2.

I deleted the already uploaded bottles for `expat` and `scipy` for this commit. I am abandoning this PR, I'll open a new one.

**Comment by sjackman** [comment]
> The bottle got build with the right revision, but linuxbrew pull tried to pull the bottle with revision 1 instead of 2.

Are you running `linuxbrew pull` on a Mac or on Linux?

**Comment by iMichka** [comment]
On a mac ... Didn't think about that :)

I'll open a bigger PR with more bottles, it will timeout in 2 hours, so you'll have more stuff to pull.

**Comment by iMichka** [comment]
Superseded by #3579

**Pull request closed without merging**
