### PR TITLE
mycli: Depends on libffi for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**
Fix the error: ffi.h: No such file or directory

### CODE REVIEW

**Comment by maxim-belkin** [comment]
I think you need to do the same thing as in `buku`: you need `pkg-config` to find `libffi`

**Comment by sjackman** [comment]
Odd that it passes on TravisCI but not on CircleCI. I'll try your suggestion. Thanks.

**Comment by sjackman** [comment]
```
    creating build/temp.linux-x86_64-2.7/c
    gcc-4.8 -fno-strict-aliasing -g -O2 -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/home/linuxbrew/.linuxbrew/bin/../Cellar/python/2.7.13/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    error: command 'gcc-4.8' failed with exit status 1
    Running setup.py install for cffi: finished with status 'error'
```
https://circleci.com/gh/Linuxbrew/homebrew-core/6831

**Comment by sjackman** [comment]
Success! Thanks for the tip, Maxim.

**Pull request closed without merging**
