### PR TITLE
infer: [ERROR] The compilation of conf-ncurses failed at "pkg-config ncurses".

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by rwhogg** [comment]
From https://travis-ci.org/Linuxbrew/homebrew-core/builds/129569621#L1746-L1763

```
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[conf-m4: sh echo | m4] Command started
[conf-pkg-config: pkg-config] Command started
∗  installed conf-pkg-config.1.0
[conf-ncurses: pkg-config ncurses] Command started
∗  installed conf-m4.1
[ERROR] The compilation of conf-ncurses failed at "pkg-config ncurses".
#=== ERROR while installing conf-ncurses.1 ====================================#
# opam-version         1.2.2
# os                   linux
# command              pkg-config ncurses
# path                /tmp/infer-20160512-22193-1thxylc/infer-linux64-v0.8.1/build/system/build/conf-ncurses.1
# compiler             system (4.03.0)
# exit-code            1
# env-file             /tmp/infer-20160512-22193-1thxylc/infer-linux64-v0.8.1/build/system/build/conf-ncurses.1/conf-ncurses-22622-ffb3fd.env
# stdout-file          /tmp/infer-20160512-22193-1thxylc/infer-linux64-v0.8.1/build/system/build/conf-ncurses.1/conf-ncurses-22622-ffb3fd.out
# stderr-file          /tmp/infer-20160512-22193-1thxylc/infer-linux64-v0.8.1/build/system/build/conf-ncurses.1/conf-ncurses-22622-ffb3fd.err
```

It did the same thing to me back when I first fixed this formula on https://github.com/Linuxbrew/linuxbrew/pull/950

**Comment by sjackman** [comment]
`ncurses` does not install a `pkg-config` file.

**Comment by sjackman** [comment]
```
$ ls `brew --prefix ncurses`/lib/pkgconfig
formw.pc  menuw.pc  ncurses++w.pc  ncursesw.pc  panelw.pc
$ pkg-config --cflags ncursesw
-D_GNU_SOURCE -I/home/sjackman/.linuxbrew/Cellar/ncurses/6.0_1/include -I/home/sjackman/.linuxbrew/Cellar/ncurses/6.0_1/include/ncursesw
$ pkg-config --cflags ncurses
Package ncurses was not found in the pkg-config search path.
Perhaps you should add the directory containing `ncurses.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ncurses' found
```

Looks as though `ncurses` install `ncursesw.pc` but not `ncurses.pc`.

**Comment by rwhogg** [comment]
Superceded by #952

**Pull request closed without merging**
