### PR TITLE
davix: fix dependencies

### PR DESCRIPTION
**Pull request by tueda**
This patch fixes build errors that I encountered when I did `brew install davix` on CentOS 6.10 w/o sudo:
```
/tmp/davix-20180824-31990-1tlk76h/deps/libneon/src/ne_utils.c:47:31: fatal error: libxml/xmlversion.h: No such file or directory
/tmp/davix-20180824-31990-1tlk76h/deps/libneon/src/ne_xml.c:60:31: fatal error: libxml/xmlversion.h: No such file or directory
```
and
```
/tmp/davix-20180824-17284-1p08r3g/src/fileops/AzureIO.cpp:23:23: fatal error: uuid/uuid.h: No such file or directory
```
-----
- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Here is a log of my successful build with the `libxml2` change but without the `util-linux`
https://gist.github.com/79c747b9c1900b8482f3c9a1709d9b37

**Comment by tueda** [comment]
I'm totally not sure about the g++-5 internal compiler errors in your build.
For `uuid/uuid.h`, you would have it somewhere in the include path, maybe. Actually `libuuid` has also `uuid/uuid.h`, which I tried at first, but then I found many formulae use `util-linux` instead; this is why I switched to `util-linux`.

**Comment by sjackman** [comment]
To resolve the GCC compiler error, add right after `def install`
```ruby
    # Reduce memory usage below for Circle CI.
    ENV["MAKEFLAGS"] = "-j8" if ENV["CIRCLECI"]
```

**Comment by tueda** [comment]
Thank you for reviewing. Now it works on Circle CI.

**Comment by sjackman** [comment]
Merged. Thank you for your contribution to Linuxbrew, Takahiro! 🏅

**Pull request closed without merging**
