### PR TITLE
pandoc-citeproc: Build a bottle for Linuxbrew (blocked by #1940)

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by rwhogg** [comment]
Failed with `zlib`-related issues, just like #1913.

Might make sense to work on #1909 before attempting to solve this.

**Comment by sjackman** [comment]
I've merge the `zlib` PR. Strange error that is.

**Comment by sjackman** [comment]
Perhaps `depends_on "zlib" unless OS.mac?` would resolve this issue.

**Comment by rwhogg** [comment]
> Perhaps depends_on "zlib" unless OS.mac? would resolve this issue.

I'm more inclined to add that to `pandoc` itself rather than to here.

**Comment by sjackman** [comment]
```
$ brew linkage pandoc
Homebrew libraries:
  /gsc/btl/linuxbrew/lib/libc.so.6 (glibc)
  /gsc/btl/linuxbrew/lib/libdl.so.2 (glibc)
  /gsc/btl/linuxbrew/lib/libm.so.6 (glibc)
  /gsc/btl/linuxbrew/lib/libpthread.so.0 (glibc)
  /gsc/btl/linuxbrew/lib/librt.so.1 (glibc)
  /gsc/btl/linuxbrew/lib/libutil.so.1 (glibc)
  /gsc/btl/linuxbrew/lib/libz.so.1 (zlib)
Possible undeclared dependencies:
  zlib
```

**Pull request closed without merging**
