### PR TITLE
geos: Build a bottle for Linuxbrew: Error: No such file or directory - python-config

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
Error: No such file or directory - python-config
==> FAILED
```
Depends on `python`?

**Comment by sjackman** [comment]
```
checking for python... /home/linuxbrew/.linuxbrew/opt/python/libexec/bin/python
checking for python version... 2.7
checking for python platform... linux2
checking for python script directory... ${prefix}/lib/python2.7/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python2.7/site-packages
checking for Python include path... 
configure: error: cannot find Python include path
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/261217435#L2252

**Comment by sjackman** [comment]
Merging without updating the bottle.

**Comment by rwhogg** [comment]
This one's been puzzling me for a few days now 😦

**Pull request merged**
