### PR TITLE
e2fsprogs - enable shared libs too

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
No idea what this means.

```
./e2fsprogs-1.44.1_1.x86_64_linux.bottle.tar.gz
  bottle do
    sha256 "25612605014a7de43ce85b2c644b9f4b18f03775738c12edf567d8ca2fe95121" => :x86_64_linux
  end
==> brew bottle --merge --write --no-commit ./e2fsprogs-1.44.1_1.x86_64_linux.bottle.json --keep-old
Error: --keep-old was passed but there are changes in:
sha256 => x86_64_linux
Error: Kernel.exit
==> e2fsprogs
==> FAILED
```

**Comment by tseemann** [comment]
@iMichka it worked!

**Comment by iMichka** [comment]
Thanks @tseemann

**Comment by tseemann** [comment]
Now i have to remember what I was trying to build that *needed* those shared libs!

**Pull request closed without merging**
