### PR TITLE
avra: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
```
make
install
 cd . && /bin/bash /tmp/avra-20170425-23691-efvsj5/avra-1.3.0/src/missing automake-1.15 --gnu 
automake-1.15: warning: autoconf input should be named 'configure.ac', not 'configure.in'
configure.in:3: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.in:3: http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
Makefile.am: error: required file './NEWS' not found
Makefile.am: error: required file './README' not found
Makefile.am: error: required file './AUTHORS' not found
Makefile.am: error: required file './ChangeLog' not found
automake-1.15: warning: autoconf input should be named 'configure.ac', not 'configure.in'
make: *** [Makefile.in] Error 1
```

**Comment by maxim-belkin** [comment]
`--add-missing` didn't help

```
automake
--add-missing

automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
configure.in:3: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.in:3: http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
Makefile.am: error: required file './NEWS' not found
Makefile.am: error: required file './README' not found
Makefile.am: error: required file './AUTHORS' not found
Makefile.am: error: required file './ChangeLog' not found
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
```

**Comment by maxim-belkin** [comment]
Ok, the problem is that mac's `/bin/sh` that is used in `boostrap` script is different from `/bin/sh` on Linux  in that it understands bracket expansion. So, we need to either `inreplace` `/bin/sh` to `/bin/bash` in the bootstrap script or ...

**Comment by sjackman** [comment]
> So, we need to either inreplace /bin/sh to /bin/bash in the bootstrap script

That sounds good to me.

**Comment by maxim-belkin** [comment]
By the way, on ubuntu the default shell is `dash` ⚠️

**Comment by maxim-belkin** [comment]
waiting for #2609 to finish

**Pull request closed without merging**
