### PR TITLE
systemd: disable building with acl

### PR DESCRIPTION
**Pull request by iMichka**
We do not have an acl formula.
If somebody needs this it can be added back later.

### CODE REVIEW

**Comment by iMichka** [comment]
```
./systemd-234_1.x86_64_linux.bottle.tar.gz
  bottle do
    sha256 "7ab34653105a7df03694d48ed9132e901353b09c1532883cc0f6e763dd765676" => :x86_64_linux
  end
==> brew bottle --merge --write --no-commit ./systemd-234_1.x86_64_linux.bottle.json --keep-old
Error: --keep-old was passed but there are changes in:
sha256 => x86_64_linux
Error: Kernel.exit
==> systemd
==> FAILED
```

**Comment by iMichka** [comment]
Got the same error with #4770. Need to double-check the brew code, I think we have a bug here.

**Comment by sjackman** [comment]
Remove `--keep-old` from `.circleci/config.yml`

**Comment by iMichka** [comment]
Thanks that worked. Forgot about that trick.

**Pull request closed without merging**
