### PR TITLE
php: Fix build for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
==> brew install --verbose --build-bottle php
==> Downloading https://php.net/get/php-7.2.11.tar.xz/from/this/mirror
Already downloaded: /home/linuxbrew/.cache/Homebrew/downloads/5d0ee9fb096b97464d061a454967a5577a077b4c48d88d284ea8f0b390e1ebf8--php-7.2.11.tar.xz
==> Verifying 5d0ee9fb096b97464d061a454967a5577a077b4c48d88d284ea8f0b390e1ebf8--php-7.2.11.tar.xz checksum
env PATH=/home/linuxbrew/.linuxbrew/opt/xz/bin:/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super:/home/linuxbrew/.linuxbrew/opt/httpd/bin:/home/linuxbrew/.linuxbrew/opt/pkg-config/bin:/home/linuxbrew/.linuxbrew/opt/ncurses/bin:/home/linuxbrew/.linuxbrew/opt/gdbm/bin:/home/linuxbrew/.linuxbrew/opt/openssl/bin:/home/linuxbrew/.linuxbrew/opt/sqlite/bin:/home/linuxbrew/.linuxbrew/opt/bzip2/bin:/home/linuxbrew/.linuxbrew/opt/python@2/bin:/home/linuxbrew/.linuxbrew/opt/util-linux/bin:/home/linuxbrew/.linuxbrew/opt/apr/bin:/home/linuxbrew/.linuxbrew/opt/expat/bin:/home/linuxbrew/.linuxbrew/opt/apr-util/bin:/home/linuxbrew/.linuxbrew/opt/argon2/bin:/home/linuxbrew/.linuxbrew/opt/aspell/bin:/home/linuxbrew/.linuxbrew/opt/m4/bin:/home/linuxbrew/.linuxbrew/opt/autoconf/bin:/home/linuxbrew/.linuxbrew/opt/curl/bin:/home/linuxbrew/.linuxbrew/opt/libtool/bin:/home/linuxbrew/.linuxbrew/opt/unixodbc/bin:/home/linuxbrew/.linuxbrew/opt/freetds/bin:/home/linuxbrew/.linuxbrew/opt/libpng/bin:/home/linuxbrew/.linuxbrew/opt/freetype/bin:/home/linuxbrew/.linuxbrew/opt/gettext/bin:/home/linuxbrew/.linuxbrew/opt/pcre/bin:/home/linuxbrew/.linuxbrew/opt/glib/bin:/home/linuxbrew/.linuxbrew/opt/icu4c/bin:/home/linuxbrew/.linuxbrew/opt/jpeg/bin:/home/linuxbrew/.linuxbrew/opt/libpq/bin:/home/linuxbrew/.linuxbrew/opt/libzip/bin:/home/linuxbrew/.linuxbrew/opt/libtiff/bin:/home/linuxbrew/.linuxbrew/opt/webp/bin:/usr/bin:/bin:/usr/sbin:/sbin unxz -T0 -- /tmp/d20181031-28354-1j5ocym/5d0ee9fb096b97464d061a454967a5577a077b4c48d88d284ea8f0b390e1ebf8--php-7.2.11.tar.xz
env: ‘unxz’: No such file or directory
Error: undefined method `shelljoin' for nil:NilClass
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/exceptions.rb:545:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/fork.rb:7:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/fork.rb:7:in `rewrite_child_error'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/fork.rb:84:in `block (3 levels) in safe_fork'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:402:in `ignore_interrupts'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/fork.rb:60:in `block (2 levels) in safe_fork'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/fork.rb:29:in `open'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/fork.rb:29:in `block in safe_fork'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/fork.rb:28:in `safe_fork'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:751:in `build'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:318:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:325:in `install_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:256:in `block in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:254:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:254:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

**Comment by sjackman** [comment]
```
env: ‘unxz’: No such file or directory
```
```ruby
depends_on "xz" => :build unless OS.mac?
```
with any luck

**Comment by iMichka** [comment]
```
configure: error: Cannot find sys/sdt.h which is required for DTrace support

==> Formula
Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/php.rb
```

**Comment by iMichka** [comment]
Will need this first: #10261

**Comment by iMichka** [comment]
```
==> SKIPPING: php
is not needed on Linux, where iconv.h is provided by glibc
```

**Pull request closed without merging**
