### PR TITLE
gcc: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
g++-5 -c   -g -DIN_GCC    -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wno-format -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings -fno-common  -DHAVE_CONFIG_H -I. -I. -I../../gcc -I../../gcc/. -I../../gcc/../include -I../../gcc/../libcpp/include -I/home/linuxbrew/.linuxbrew/opt/gmp/include -I/home/linuxbrew/.linuxbrew/opt/mpfr/include -I/home/linuxbrew/.linuxbrew/opt/libmpc/include  -I../../gcc/../libdecnumber -I../../gcc/../libdecnumber/bid -I../libdecnumber -I../../gcc/../libbacktrace -I/home/linuxbrew/.linuxbrew/opt/isl/include  -o graphite-optimize-isl.o -MT graphite-optimize-isl.o -MMD -MP -MF ./.deps/graphite-optimize-isl.TPo ../../gcc/graphite-optimize-isl.c
../../gcc/graphite-optimize-isl.c:30:22: fatal error: isl/band.h: No such file or directory
```

**Comment by sjackman** [comment]
The isl 0.18 bottle contains the file `include/isl/band.h`
The isl 0.19 bottles does not contain this file.
```
$ diff isl-0.18 isl-0.19
7d6
< band.h
10d8
< deprecated
```

**Comment by sjackman** [comment]
No other formulae other than `gcc` and `mingw-w64` use `isl`. I'm going to revert `isl` to 0.18 and revert `gcc` back to the previous working bottle.

**Comment by sjackman** [comment]
Superseded by https://github.com/Linuxbrew/homebrew-core/pull/6632, revert isl to 0.18

**Comment by iMichka** [comment]
Yes, but mingw was revision bumped due to isl.

I reverted your revert, and building `isl@18` right now: #6636, which I will use for gcc

**Comment by iMichka** [comment]
Superseded by #6637

**Pull request closed without merging**
