### PR TITLE
Merge 2017-08-29 2d73bf6b34

### PR DESCRIPTION
**Pull request by iMichka**
+ [ ] azure-cli

### CODE REVIEW

**Comment by sjackman** [comment]
```
==> Downloading https://www.erlang.org/download/otp_doc_man_17.5.tar.gz
/usr/bin/curl --remote-time --location --user-agent Linuxbrew/1.3.0 (Linux; x86_64 4.4.0-83-generic) curl/7.47.0 --fail --silent https://www.erlang.org/download/otp_doc_man_17.5.tar.gz -C 0 -o /home/linuxbrew/.cache/Homebrew/erlang@17--man-17.5.tar.gz.incomplete
Error: Failed to download resource "erlang@17--man"
Download failed: https://www.erlang.org/download/otp_doc_man_17.5.tar.gz
==> FAILED
```

**Comment by iMichka** [comment]
Actually:
```
erlang@17:
  * The URL https://www.erlang.org/ is not reachable
  * Stable resource "man": The URL https://www.erlang.org/download/otp_doc_man_17.5.tar.gz is not reachable
  * Stable resource "html": The URL https://www.erlang.org/download/otp_doc_html_17.5.tar.gz is not reachable
  * New formulae should not require patches to build. Patches should be submitted and accepted upstream first.
  * HEAD resource "man": The URL https://www.erlang.org/download/otp_doc_man_17.5.tar.gz is not reachable
  * HEAD resource "html": The URL https://www.erlang.org/download/otp_doc_html_17.5.tar.gz is not reachable
  * New formulae should not require patches to build. Patches should be submitted and accepted upstream first.
```

**Comment by sjackman** [comment]
https://www.erlang.org/ works fine and is reachable using macOS and their SSL implementation. It's not reachable from Linuxbrew using OpenSSL due to a misconfigured certificate.

**Comment by iMichka** [comment]
It is a new formula, will probably need to get adapted to Linuxbrew later. Somebody can pick that up, I'll merge this PR once travis is back

**Comment by sjackman** [comment]
```
/tmp/fibjs-20170829-49739-mw2iuo/vender/v8/src/heap/heap-inl.h:547:42:   required from here
/usr/include/c++/5/bits/hashtable_policy.h:101:30: error: no matching function for call to ‘get(const std::pair<v8::internal::AllocationSite* const, long unsigned int>&)’
       -> decltype(std::get<0>(std::forward<_Tp>(__x)))
…
Error: fibjs 0.12.0 did not build
```

**Comment by sjackman** [comment]
That's it. Only those two errors. :+1:

**Comment by iMichka** [comment]
Yeah for fibjs you can see that in the formula:
> depends_on :macos => :sierra # fibjs requires >= Xcode 8.3 (or equivalent CLT)

Will probably need more work, so not my priority at the moment

**Comment by sjackman** [comment]
TravisCI is still running on Trusty. We can leave it that way for a bit, until the C++ rebottling effort is under way. I suggest that we start the C++ rebottling after the first CI failure related to the C++ ABI.

**Pull request merged**
