### PR TITLE
Merge 2017-08-13 543d8e9b27

### PR DESCRIPTION
**Pull request by iMichka**
+ [ ] filebeat

### CODE REVIEW

**Comment by iMichka** [comment]
```
Testing inetutils
==> /home/linuxbrew/.linuxbrew/Cellar/inetutils/1.9.4/libexec/gnubin/ftp -v
Error: inetutils: failed
```

```
ice

i686-linux-gnu-g++-4.8  -MT src/Slice/build/i386-linux-gnu/static/Grammar.o -MMD -MP -MF  src/Slice/build/i386-linux-gnu/static/Grammar.Td -Wall -Wdeprecated -Werror -pthread -DNDEBUG -Isrc -Isrc/Slice/generated -Iinclude -Iinclude/generated -DICE_BUILDING_SRC -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -I/home/linuxbrew/.linuxbrew/opt/mcpp/include -DICE_STATIC_LIBS  -c src/Slice/Grammar.cpp -o src/Slice/build/i386-linux-gnu/static/Grammar.o
make[1]: i686-linux-gnu-g++-4.8: Command not found
```

```
swiftgen
public_suffix-2.0.5 requires ruby version >= 2.0, which is incompatible with the
current version, ruby 1.9.3p484
```

**Comment by sjackman** [comment]
`i686-linux-gnu-g++-4.8: Command not found`
That's a 32-bit compiler. Weird.

**Comment by sjackman** [comment]
`ruby 1.9.3p484`
I thought CI use Ruby 2.0. Also weird.

**Comment by iMichka** [comment]
BTW the next swiftgen update (#3935) did have a different issue. In fact it needs Xcode. Disabling it for Linuxbrew here:  #3936

**Pull request merged**
