### PR TITLE
ghc@8.0: Fix for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by iMichka** [comment]
@sjackman you hit the 4Gb memory limit

**Comment by sjackman** [comment]
```
Your build has exceeded the memory limit of 4G on 1 container.
```
https://circleci.com/gh/Linuxbrew/homebrew-core/7279
https://7279-56942570-gh.circle-artifacts.com/0/tmp/memory-usage.txt

**Comment by sjackman** [comment]
| Jobs | Status |
| 32 | ❌ |
| 8 | |

**Comment by sjackman** [comment]
Merge this PR without updating the bottle.

**Pull request closed without merging**
