### PR TITLE
phantomjs: Depends on libxml2 zlib for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**
See https://github.com/Linuxbrew/homebrew-core/issues/1571

### CODE REVIEW

**Comment by sjackman** [comment]
```
QtCore: created fwd-include header(s) for <srcbase>/src/corelib/xml/ { qxmlstream.h (1), qxmlstream_p.h (1), qxmlutils_p.h (1) }
Creating qmake...
Done.
Running configuration tests...
The ICU library support cannot be enabled.
 Turn on verbose messaging (-v) to /tmp/phantomjs-20170111-36263-edafco/src/qt/qtbase/configure to see the final report.
 If you believe this message is in error you may use the continue
 switch (-continue) to /tmp/phantomjs-20170111-36263-edafco/src/qt/qtbase/configure to continue.

ERROR: Failed to build PhantomJS! Configuration of Qt Base failed.
Executing in /tmp/phantomjs-20170111-36263-edafco: git submodule init
Executing in /tmp/phantomjs-20170111-36263-edafco: git submodule update --init
configuring Qt Base, please wait...
Executing in /tmp/phantomjs-20170111-36263-edafco/src/qt/qtbase: /tmp/phantomjs-20170111-36263-edafco/src/qt/qtbase/configure -static -opensource -confirm-license -prefix /tmp/phantomjs-20170111-36263-edafco/src/qt/qtbase -qt-zlib -qt-libpng -qt-libjpeg -qt-pcre -nomake examples -nomake tools -nomake tests -no-qml-debug -no-dbus -no-opengl -no-audio-backend -D QT_NO_GRAPHICSVIEW -D QT_NO_GRAPHICSEFFECT -D QT_NO_STYLESHEET -D QT_NO_STYLE_CDE -D QT_NO_STYLE_CLEANLOOKS -D QT_NO_STYLE_MOTIF -D QT_NO_STYLE_PLASTIQUE -D QT_NO_PRINTPREVIEWDIALOG -qpa phantom -openssl -openssl-linked -no-openvg -no-eglfs -no-egl -no-glib -no-gtkstyle -no-cups -no-sm -no-xinerama -no-xkb -no-xcb -no-kms -no-linuxfb -no-directfb -no-mtdev -no-libudev -no-evdev -no-pulseaudio -no-alsa -no-feature-PRINTPREVIEWWIDGET -fontconfig -icu -release
```

Oh good grief. Why is `phantomjs` building `qt` from source, and can we disable that feature? @rwhogg

**Comment by sjackman** [comment]
`phantomjs` does not depend on `icu4c` on Mac OS. Is it possible to disable that dependency? I'd prefer to avoid dependencies not present upstream. When upstream bumps `icu4c` it breaks the `phantomjs` bottle because upstream doesn't need to rebuild the bottle but Linuxbrew does.

**Comment by rwhogg** [comment]
From http://phantomjs.org/build.html :

```
Linux requirements

First, install the development packages of the following tools and libraries: GNU C++ compiler, bison, flex, gperf, Perl, Ruby, SQLite, FreeType, Fontconfig, OpenSSL, and ICU. The actual package names may vary from one distribution to another.

...

OS X requirements

Xcode and the necessary SDK for development (gcc, various tools, libraries, etc)
OpenSSL via Homebrew or via MacPorts

```

`brew linkage phantomjs` confirms this:

```
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libdl.so.2
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /lib/x86_64-linux-gnu/librt.so.1
  /lib64/ld-linux-x86-64.so.2
Homebrew libraries:
  /home/linuxbrew/.linuxbrew/lib/libfontconfig.so.1 (fontconfig)
  /home/linuxbrew/.linuxbrew/lib/libfreetype.so.6 (freetype)
  /home/linuxbrew/.linuxbrew/lib/libgcc_s.so.1 (gcc)
  /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6 (gcc)
  /home/linuxbrew/.linuxbrew/lib/libxml2.so.2 (libxml2)
  /home/linuxbrew/.linuxbrew/lib/libcrypto.so.1.0.0 (openssl)
  /home/linuxbrew/.linuxbrew/lib/libssl.so.1.0.0 (openssl)
  /home/linuxbrew/.linuxbrew/lib/libz.so.1 (zlib)
Missing libraries:
  libicui18n.so.57
  libicuuc.so.57
Possible undeclared dependencies:
  fontconfig
  freetype
  libxml2
  zlib
```

Unless we want to switch to a [binary distribution](http://phantomjs.org/download.html) I don't have an easy answer here.

**Comment by sjackman** [comment]
Yep, I think it'll just have to depend on `icu4c` on Linuxbrew.

**Comment by sjackman** [comment]
Circle
```
==> brew uninstall --force phantomjs
Uninstalling phantomjs... (50 files, 55.3M)
==> brew uninstall --force icu4c libxml2 openssl zlib
Warning: /home/linuxbrew/.linuxbrew/Cellar/zlib/1.2.8, /home/linuxbrew/.linuxbrew/Cellar/openssl/1.0.2j_1 are required by curl, which is currently installed.
…
/home/linuxbrew/.linuxbrew/opt/curl/bin/curl: symbol lookup error: /home/linuxbrew/.linuxbrew/lib/libcurl.so.4: undefined symbol: SSL_CTX_set_alpn_protos
```

**Comment by sjackman** [comment]
TravisCI
```
The job exceeded the maximum time limit for jobs, and has been terminated.
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/200485615#L2412

**Pull request closed without merging**
