### PR TITLE
openssl: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
brew pull --clean https://github.com/Linuxbrew/homebrew-core/pull/204
Error: /home/linuxbrew/.linuxbrew/Cellar/ruby/2.3.1/lib/ruby/2.3.0/x86_64-linux/openssl.so: undefined symbol: SSLv2_method - /home/linuxbrew/.linuxbrew/Cellar/ruby/2.3.1/lib/ruby/2.3.0/x86_64-linux/openssl.so
Please report this bug:
    https://github.com/Linuxbrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/linuxbrew/.linuxbrew/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/linuxbrew/.linuxbrew/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/linuxbrew/.linuxbrew/Cellar/ruby/2.3.1/lib/ruby/2.3.0/openssl.rb:13:in `<top (required)>'
```

**Comment by DoomHammer** [comment]
`brew fetch $(brew uses --installed $FORMULA)` before `brew test-bot --keep-old --verbose` and `brew reinstall $(brew uses --installed $FORMULA)` afterwards?

A bit of an overkill, perhaps. We may reduce the list just to the essentials (though I believe only such are installed at the point). Any other ideas? `openssl` bottle would be _really_ nice to have.

**Comment by sjackman** [comment]
I had put together https://github.com/Linuxbrew/linuxbrew/pull/1024 to address this issue, but I'm not happy with the solution.

**Comment by sjackman** [comment]
This failure is a bit unique. It's failing not during the normal `brew test-bot` but during `brew test-bot --ci-upload`, which Travis doesn't run and is why Travis succeeds.

`test-bot` installs `ruby` because `brew uses`, then removes `openssl` and its deps `zlib`, to test that it uninstalls cleanly, but it does *not* remove the formula that it installed for `brew uses`, leaving the system in a broken state. The solution for this particular issue is to remove all the formula that were installed either after `brew test-bot` or before `brew test-bot --ci-upload`. Of course with a broken `ruby`, not much of anything will happen, so the first one then.

`brew install ruby` https://travis-ci.org/Linuxbrew/homebrew-core/builds/128184990#L3181
`brew remove openssl` https://travis-ci.org/Linuxbrew/homebrew-core/builds/128184990#L3271

**Comment by sjackman** [comment]
Instead of `ruby` shared library error, now we have a `curl` shared library error:
```
curl -I --silent --fail --output /dev/null https://linuxbrew.bintray.com/bottles/openssl-1.0.2h.x86_64_linux.bottle.tar.gz
curl: symbol lookup error: /home/linuxbrew/.linuxbrew/lib/libcurl.so.4: undefined symbol: SSL_CTX_set_alpn_protos
```

`curl` is installed as a dependency of `git`, and then not removed.

**Comment by sjackman** [comment]
Fixed by https://github.com/Linuxbrew/brew/commit/3297e46203fcf33b157ca7b57a05389c43578ea4!

**Pull request closed without merging**
