### PR TITLE
jdk 1.8.0-144

### PR DESCRIPTION
**Pull request by VonUniGE**
Update to jdk 1.8.0-144

- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by rwhogg** [comment]
Thanks a bunch for helping us keep `jdk` up to date!

When you update this formula in the future (or any other formula marked with "# tag linuxbrew"), please apply those same changes to circle.yml that I just pushed to this branch.

"# tag linuxbrew" denotes a formula that exists in linuxbrew/core but not homebrew/core, and our continuous integration system has to handle them differently.

**Comment by sjackman** [comment]
@rwhogg We could modify `brew bump-formula-pr` to do this automatically for Linuxbrew. (I've actually never used `brew bump-formula-pr` myself.)

**Comment by sjackman** [comment]
I'd love for `test-bot` to be smarter though and determine when `--keep-old` is and isn't needed.

**Comment by sjackman** [comment]
Merged. Thanks for your contribution to Linuxbrew, @VonUniGE! :tada:

**Comment by sjackman** [comment]
Resolved by
043fb1f50a jdk: update 1.8.0-144 bottle for Linuxbrew.
843ca3e238 jdk 1.8.0-144

**Pull request closed without merging**
