### PR TITLE
grafana: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by iMichka** [comment]
> Your build has exceeded the memory limit of 4G on 1 container

**Comment by sjackman** [comment]
| Jobs | Status |
| 32 | ❌ |
| 16 | |

**Comment by sjackman** [comment]
```
1.00s==> brew linkage --test grafana
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libdl.so.2
  /lib/x86_64-linux-gnu/libgcc_s.so.1
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /lib/x86_64-linux-gnu/librt.so.1
  /lib/x86_64-linux-gnu/libz.so.1
  /lib64/ld-linux-x86-64.so.2
  /usr/lib/x86_64-linux-gnu/libfontconfig.so.1
  /usr/lib/x86_64-linux-gnu/libfreetype.so.6
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No broken dylib links
Unwanted system libraries:
  libfontconfig.so.1
  libfreetype.so.6
  libz.so.1
==> FAILED
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/251312054#L1596

**Comment by sjackman** [comment]
Thanks for merging, Michka.

**Pull request closed without merging**
