### PR TITLE
glibc: Bump revision to 1 for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
False positive `brew audit glibc` failure
```
  * stable: sha256 changed without the version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/263570945#L1527

**Comment by rwhogg** [comment]
FYI @sjackman this needs to be rebased after I merged #3791

**Comment by sjackman** [comment]
This PR built a bottle successfully. Pouring that bottle fails for some reason I'm not sure yet. I'll have to sort that issue out before merging this PR.

**Comment by sjackman** [comment]
CircleCI
```
==> SKIPPING: glibc
gawk is required to build glibc.
Install gawk with your host package manager if you have sudo access.
  sudo apt-get install gawk
```
https://circleci.com/gh/Linuxbrew/homebrew-core/8349
Working around by temporarily installing the host's `gawk` on CircleCI.

**Comment by sjackman** [comment]
Merged!

**Pull request closed without merging**
