### PR TITLE
libsoup: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
> checking for XML::Parser... configure: error: XML::Parser perl module is required for intltool

**Comment by iMichka** [comment]
> checking for XML::Parser... configure: error: XML::Parser perl module is required for intltool

**Comment by iMichka** [comment]
@half2me this should be fixed now.

**Comment by half2me** [comment]
thanks @iMichka
Other than these, I've having many problems on my clean install of Ubuntu 17.04 Server.
A lot of formulas don't work. Should I report these all separately?

**Comment by iMichka** [comment]
Yes please. Always fill out the issue template, just in case. We are aware that there a still a lot a formulae that are not working on Linux. If you have specific ones that need a fix we can look at these in priority, it's always better for us to focus on formulae that people really have an usage for.

**Comment by half2me** [comment]
@iMichka thanks for all this btw, brew is completely changing the way I now install apps and dependencies on linux. I always hated how the apt repos would have outdated versions, and installing from source was always such a pain. I'm glad brew is not just for osx anymore :)

**Pull request closed without merging**
