### PR TITLE
freetds: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by sjackman** [comment]
TravisCI only
```
Unwanted system libraries:
  libodbc.so.1
  libodbcinst.so.1
==> FAILED
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/227724894#L2905

**Comment by maxim-belkin** [comment]
I guess the list of libraries to remove from Travis has to be expanded 😈

**Comment by maxim-belkin** [comment]
`libodbc1` and `odbcinst1debian2`

**Comment by sjackman** [comment]
We've been removing only the `-dev` packages so far. I'd stick with that for now.

**Pull request closed without merging**
