### PR TITLE
automake: Set environment variable PERL

### PR DESCRIPTION
**Pull request by Char-Aznable**
Set environment variable PERL to brewed perl so that the installed scripts shebang the brewed perl.

### CODE REVIEW

**Comment by iMichka** [comment]
Hi. In principle we prefer to use system perl. I am not a perl specialist, but if I understand well, setting the ENV path will set the perl shebangs to brewed perl. If we do not do this, and you install these formulae with bottles, the shebangs will be the ones coming from the perl installed on circle.ci, which may be wrong for other platforms.

So if my understanding is right (please correct me if I am wrong), then we should use brewed perl.

Would it be possible to split this in two separate pull requests (one for each formula)?

Also, you have superfluous `if OS.mac?` and `if OS.linux?` stances in you changes.

**Comment by sjackman** [comment]
Currently, the shebang line of `automake` is set to `#!/usr/bin/perl -w`. What do you we want it to be set to? I feel like I'd prefer to avoid a hard dependency on brewed perl if possible. The host's Perl is likely sufficient (with PR #6352) if the host has `/usr/bin/perl`.
I'd suggest perhaps…
```ruby
depends_on "perl" unless which "perl"
```
and setting the shebang line to
```sh
#!/usr/bin/env perl
```
Thoughts?

**Comment by iMichka** [comment]
@Char-Aznable what shebang were you expecting. And also what error did you hit?

@sjackman I am fine with your version.

**Comment by Char-Aznable** [comment]
The error I hit was that both librsvg and systemd's makefile have hard-coded commands running either the scripts in autoconf/automake and they failed because the ancient system perl was used. I'm fine with what @sjackman proposed. I'll try to split these two in separate PRs.

**Comment by sjackman** [comment]
To resolve your issue, Char, I suspect you want PR #6352 rather than this particular PR.

**Comment by Char-Aznable** [comment]
No, the error I got was missing the Cwd perl module or something it depends on. 

It seems setting shebang to "#!/usr/bin/env perl" can't be done by setting PERL to that line during installation. I'm rolling back to my original proposal. Let me know if you have better solution.

**Comment by sjackman** [comment]
It would be helpful to us to report the exact error message that you are seeing.

You can use `inreplace` to change the shebang line after installation to `#!/usr/bin/env perl`.

Please separate this PR into two, one for each formula.

**Comment by Char-Aznable** [comment]
The dependency problem was more complicated than I thought. I tried to track down what scripts was called during make but then gave up after I found 3 of them. I'll try to split the PR later.

**Comment by Char-Aznable** [comment]
PR #6517 and #6518 submitted.

**Comment by sjackman** [comment]
Superseded by PRs #6517 and #6518

**Pull request closed without merging**
