### PR TITLE
rust: Build a bottle for Linuxbrew: Timed out

### PR DESCRIPTION
**Pull request by DoomHammer**

### CODE REVIEW

**Comment by DoomHammer** [comment]
Timeout during build.

**Comment by DoomHammer** [comment]
@sjackman shall we close this one?

**Comment by sjackman** [comment]
Better to leave it open for the record, so that if someone else tries `brew build-bottle-pr rust`, they'll be pointed to this existing PR.

You can try adding
```ruby
ENV["MAKEFLAGS"] = "-j32" if ENV["CIRCLECI"]
```

The default value is limited to 8, to prevent an excess number of compiler processes from exceeding the 4 GB memory limit of CircleCI.

**Comment by DoomHammer** [comment]
Both `-j32` and `-j16` result in `[...] died unexpectedly`

[']

**Comment by sjackman** [comment]
> Your build has exceeded the memory limit of 4G on 1 container. The results of this build are likely invalid. We have taken a snapshot of the memory usage at the time, which you can find in a build artifact named `memory-usage.txt`. The RSS column in this file shows the amount of memory used by each process, measured in kilobytes.

**Comment by sjackman** [comment]
```
   PID   RSS %CPU COMMAND
 66632 209476 8.0 /usr/lib/gcc/x86_64-linux-gnu/4.8/cc1plus
```

Each `cc1` process uses ~209 MB of RAM, so you should be able to use ~19 threads. Try `-j16` and if it fails for memory usage check the Artifacts tab to check the memory usage of `cc1` and adjust the number of threads accordingly.

**Comment by DoomHammer** [comment]
X, Postgres, Mongo? What are they doing there? :confused:

**Comment by DoomHammer** [comment]
Words cannot describe my happiness. After failures with `-j8`, `-j32` and `-j16` it was `-j12` that saved the day! :tada: :balloon: :wine_glass:

**Comment by sjackman** [comment]
Yeah! Good work, Piotr. I've been through this optimizing-the-number-of-threads process with Circle too. It's, erm, interesting.

**Comment by DoomHammer** [comment]
Should I leave the CircleCI `if` for future generations?

**Comment by sjackman** [comment]
Yes, absolutely. Please add a comment whenever you include a hack like this in the formula, to explain to future generations why it was needed.
```ruby
    # Reduce memory usage below 4 GB for Circle CI.
```

**Pull request closed without merging**
