### PR TITLE
whois: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
> /usr/bin/ld: cannot find -liconv

**Comment by iMichka** [comment]
> libiconv: is not needed on Linux, where iconv.h is provided by glibc

**Comment by bmhatfield** [comment]
This PR is very welcomed - `whois` is currently failing for me for this exact reason.

**Comment by iMichka** [comment]
@bmhatfield should be fixed now, please update.

**Pull request closed without merging**
