### PR TITLE
percona-server: Build a bottle for Linuxbrew.

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
-- EDITLINE_INCLUDE_DIR 
-- EDITLINE_LIBRARY EDITLINE_LIBRARY-NOTFOUND
CMake Error at cmake/readline.cmake:280 (MESSAGE):
  Cannot find system editline libraries.
Call Stack (most recent call first):
  CMakeLists.txt:524 (MYSQL_CHECK_EDITLINE)
```

**Comment by iMichka** [comment]
This is failing:
> ./mysql-test-run.pl status --vardir=/tmp/d20180105-11780-1p2xkuo

```
 - the logfile can be found in '/tmp/d20180105-11780-1p2xkuo/log/main.status/status.log'
--------------------------------------------------------------------------
The servers were restarted 0 times
Spent 0.000 of 9 seconds executing testcases
mysql-test-run: WARNING: Got errors/warnings while running tests, please examine '/tmp/d20180105-11780-1p2xkuo/log/warnings' for details.

Completed: Failed 1/1 tests, 0.00% were successful.

Failing test(s): main.status

The log files in var/log may give you some hint of what went wrong.
```

**Comment by iMichka** [comment]
Will need to be rebased after #5432 is merged

**Comment by unixfox** [comment]
Any updates on this?

**Comment by iMichka** [comment]
I rebased this. If it does not build, somebody will need to build this locally and have a look at the log file ...

**Comment by iMichka** [comment]
This is the actual error

```
[ 48%] Building CXX object plugin/keyring_vault/CMakeFiles/keyring_vault.dir/vault_io.cc.o
cd /tmp/percona-server-20180206-17293-1dqtrmy/percona-server-5.7.20-19/plugin/keyring_vault && /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++-5  -DHAVE_CONFIG_H -DHAVE_LIBEVENT1 -DHAVE_MEMSET_S=1 -DMYSQL_DYNAMIC_PLUGIN -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -Dkeyring_vault_EXPORTS -I/tmp/percona-server-20180206-17293-1dqtrmy/percona-server-5.7.20-19/include -I/tmp/percona-server-20180206-17293-1dqtrmy/percona-server-5.7.20-19/extra/rapidjson/include -I/tmp/percona-server-20180206-17293-1dqtrmy/percona-server-5.7.20-19/libbinlogevents/include -I/tmp/percona-server-20180206-17293-1dqtrmy/percona-server-5.7.20-19/libbinlogevents/export -I/tmp/percona-server-20180206-17293-1dqtrmy/percona-server-5.7.20-19/include/boost_1_59_0/patches -isystem /tmp/percona-server-20180206-17293-1dqtrmy/percona-server-5.7.20-19/boost -isystem /home/linuxbrew/.linuxbrew/include -I/tmp/percona-server-20180206-17293-1dqtrmy/percona-server-5.7.20-19/plugin/keyring/common -I/tmp/percona-server-20180206-17293-1dqtrmy/percona-server-5.7.20-19/sql -I/tmp/percona-server-20180206-17293-1dqtrmy/percona-server-5.7.20-19/sql/auth -I/tmp/percona-server-20180206-17293-1dqtrmy/percona-server-5.7.20-19/regex  -Wall -Wextra -Wformat-security -Wvla -Woverloaded-virtual -Wno-unused-parameter -DNDEBUG -DDBUG_OFF -DNDEBUG -fPIC   -o CMakeFiles/keyring_vault.dir/vault_io.cc.o -c /tmp/percona-server-20180206-17293-1dqtrmy/percona-server-5.7.20-19/plugin/keyring_vault/vault_io.cc
In file included from /tmp/percona-server-20180206-17293-1dqtrmy/percona-server-5.7.20-19/plugin/keyring_vault/i_vault_parser.h:8:0,
                 from /tmp/percona-server-20180206-17293-1dqtrmy/percona-server-5.7.20-19/plugin/keyring_vault/vault_parser.h:5,
                 from /tmp/percona-server-20180206-17293-1dqtrmy/percona-server-5.7.20-19/plugin/keyring_vault/vault_io.h:8,
                 from /tmp/percona-server-20180206-17293-1dqtrmy/percona-server-5.7.20-19/plugin/keyring_vault/vault_io.cc:2:
/tmp/percona-server-20180206-17293-1dqtrmy/percona-server-5.7.20-19/plugin/keyring_vault/vault_memory.h: In instantiation of ‘void keyring::Secure_allocator<T>::deallocate(T*, size_t) [with T = char; size_t = long unsigned int]’:
/usr/include/c++/5/ext/alloc_traits.h:185:7:   required from ‘static void __gnu_cxx::__alloc_traits<_Alloc>::deallocate(_Alloc&, __gnu_cxx::__alloc_traits<_Alloc>::pointer, __gnu_cxx::__alloc_traits<_Alloc>::size_type) [with _Alloc = keyring::Secure_allocator<char>; __gnu_cxx::__alloc_traits<_Alloc>::pointer = char*; __gnu_cxx::__alloc_traits<_Alloc>::size_type = long unsigned int]’
/usr/include/c++/5/bits/basic_string.h:185:34:   required from ‘void std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_M_destroy(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = keyring::Secure_allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
/usr/include/c++/5/bits/basic_string.h:180:14:   required from ‘void std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_M_dispose() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = keyring::Secure_allocator<char>]’
/usr/include/c++/5/bits/basic_string.h:543:19:   required from ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::~basic_string() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = keyring::Secure_allocator<char>]’
/tmp/percona-server-20180206-17293-1dqtrmy/percona-server-5.7.20-19/plugin/keyring_vault/vault_curl.h:24:16:   required from here
/tmp/percona-server-20180206-17293-1dqtrmy/percona-server-5.7.20-19/plugin/keyring_vault/vault_memory.h:30:15: error: ‘memset_s’ was not declared in this scope
       memset_s(p, n, 0, n);
               ^
plugin/keyring_vault/CMakeFiles/keyring_vault.dir/build.make:137: recipe for target 'plugin/keyring_vault/CMakeFiles/keyring_vault.dir/vault_io.cc.o' failed
```

**Comment by iMichka** [comment]
Maybe this bug: https://bugs.launchpad.net/percona-server/+bug/1741647
Let's try to apply the patch ...

**Comment by iMichka** [comment]
Fixed and merged

**Comment by unixfox** [comment]
Can confirm it's working now:
```
==> Summary
🍺  /media/sdah1/unixfox/.linuxbrew/Cellar/percona-server/5.7.21-20: 332 files, 423.2MB, built in 2 minutes 46 seconds
```

**Pull request closed without merging**
