### PR TITLE
swig: Fix test for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
See also #192

**Comment by sjackman** [comment]
No idea what this means:
```
==> brew test swig --verbose
Testing swig
==> /home/linuxbrew/.linuxbrew/Cellar/swig/3.0.8/bin/swig -ruby test.i
==> /home/linuxbrew/.linuxbrew/bin/gcc-5 -c -fPIC test.c
==> /home/linuxbrew/.linuxbrew/bin/gcc-5 -c -fPIC test_wrap.c -I/home/travis/.rvm/rubies/ruby-2.0.0-p647-clang/include/ruby-2.0.0 -I/home/travis/.rvm/rubies/ruby-2.0.0-p647-clang/include/ruby-2.0.0/x86_64-linux
==> /home/linuxbrew/.linuxbrew/bin/gcc-5 -shared test.o test_wrap.o -o test.so -lruby
…
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -lruby
collect2: error: ld returned 1 exit status
Error: swig: failed
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/139632311#L1392

`brew test` depends on `libruby-dev`

**Comment by rwhogg** [comment]
> brew test swig depends on libruby-dev

I've been wondering for a while if Homebrew (upstream included) would benefit from having a DSL method for `depends_on "something" => :test`.

The only precedent I can find in the current code is

```
openvdb.rb:34:  depends_on "cppunit" if build.with? "test"
cereal.rb:21:  depends_on "cmake" => :build if build.with? "tests"
```

I don't really like the idea of depending on `ruby` (or `python`), even just `:recommended`, for the purpose of a test. I regularly experience problems with apt-installed gems not working with Homebrew Ruby for bizarre reasons.

As for a crude fix, ```depends_on "ruby" if ENV["CIRCLECI"]``` would be ok in my opinion (assuming it works). I'd prefer to have as few system-installed development packages on Circle as possible so that we expose more missing dependencies.

**Comment by sjackman** [comment]
> `depends_on "ruby" if ENV["CIRCLECI"]`

Yep, I'd be okay with that, with a comment explaining why it's necessary.

The hack I went with in this case was to modify the CircleCI build script:
`sudo ln -sf /usr/lib/x86_64-linux-gnu/libruby-2.0.so /usr/lib/x86_64-linux-gnu/libruby.so`
because brewed `ruby` provides `libruby.so` but `ruby2.0-dev` from Ubuntu instead provides `libruby-2.0.so`, so I hack up Ubuntu to make it look more like Linuxbrew.

**Pull request closed without merging**
