### PR TITLE
mkvtoolnix: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
> configure: error: xsltproc wasn't found

**Comment by iMichka** [comment]
```
==> ./configure --disable-debug --prefix=/home/linuxbrew/.linuxbrew/Cellar/mkvtoolnix/17.0.0 --with-boost=/home/linuxbrew/.linuxbrew/opt/boost --with-docbook-xsl-root=/home/linuxbrew/.linuxbrew/opt/docbook-xsl/docbook-xsl --with-extra-includes=/home/linuxbrew/.linuxbrew/opt/libogg/include;/home/linuxbrew/.linuxbrew/opt/libvorbis/include;/home/linuxbrew/.linuxbrew/opt/libebml/include;/home/linuxbrew/.linuxbrew/opt/libmatroska/include;/home/linuxbrew/.linuxbrew/opt/flac/include;/home/linuxbrew/.linuxbrew/opt/libmagic/include --with-extra-libs=/home/linuxbrew/.linuxbrew/opt/libogg/lib;/home/linuxbrew/.linuxbrew/opt/libvorbis/lib;/home/linuxbrew/.linuxbrew/opt/libebml/lib;/home/linuxbrew/.linuxbrew/opt/libmatroska/lib;/home/linuxbrew/.linuxbrew/opt/flac/lib;/home/linuxbrew/.linuxbrew/opt/libmagic/lib --disable-qt
.
==> rake -j32
.....Too long with no output (exceeded 10m0s)
```

**Comment by iMichka** [comment]
> g++-5: internal compiler error: Killed (program cc1plus)

**Comment by iMichka** [comment]
```
ebml_chapters_converter.cpp:(.text+0x263f): undefined reference to `libebml::EbmlString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&[abi:cxx11]() const'
```

I need to rebuild the `libeml` bottle for gcc5.

**Comment by iMichka** [comment]
Needs #5547 first.

@retokromer I am making some progress, lets see if this helps.

**Comment by iMichka** [comment]
```
src/common/libmtxcommon.a(mm_io.o): In function `__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > boost::re_detail_106600::re_is_set_member<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char, boost::regex_traits<char, boost::cpp_regex_traits<char> >, unsigned int>(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::re_detail_106600::re_set_long<unsigned int> const*, boost::re_detail_106600::regex_data<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, bool)':
mm_io.cpp:(.text._ZN5boost16re_detail_10660016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb[_ZN5boost16re_detail_10660016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb]+0x1d1): undefined reference to `boost::re_detail_106600::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
mm_io.cpp:(.text._ZN5boost16re_detail_10660016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb[_ZN5boost16re_detail_10660016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb]+0x4ae): undefined reference to `boost::re_detail_106600::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
collect2: error: ld returned 1 exit status
src/common/libmtxcommon.a(mm_io.o): In function `__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > boost::re_detail_106600::re_is_set_member<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char, boost::regex_traits<char, boost::cpp_regex_traits<char> >, unsigned int>(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::re_detail_106600::re_set_long<unsigned int> const*, boost::re_detail_106600::regex_data<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, bool)':
mm_io.cpp:(.text._ZN5boost16re_detail_10660016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb[_ZN5boost16re_detail_10660016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb]+0x1d1): undefined reference to `boost::re_detail_106600::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
mm_io.cpp:(.text._ZN5boost16re_detail_10660016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb[_ZN5boost16re_detail_10660016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb]+0x4ae): undefined reference to `boost::re_detail_106600::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
src/common/libmtxcommon.a(ebml_chapters_converter.o): In function `mtx::xml::ebml_chapters_converter_c::fix_display(libmatroska::KaxChapterDisplay&) const':
ebml_chapters_converter.cpp:(.text+0x3035): undefined reference to `libebml::EbmlString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&() const'
ebml_chapters_converter.cpp:(.text+0x323b): undefined reference to `libebml::EbmlString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&() const'
src/info/mkvinfo.o: In function `handle_ebml_head(libebml::EbmlElement*, std::shared_ptr<mm_io_c>, libebml::EbmlStream*)':
mkvinfo.cpp:(.text+0xe924): undefined reference to `libebml::EbmlString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&() const'
collect2: error: ld returned 1 exit status
src/propedit/libmtxpropedit.a(propedit_cli_parser.o): In function `__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > boost::re_detail_106600::re_is_set_member<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char, boost::regex_traits<char, boost::cpp_regex_traits<char> >, unsigned int>(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::re_detail_106600::re_set_long<unsigned int> const*, boost::re_detail_106600::regex_data<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, bool)':
propedit_cli_parser.cpp:(.text._ZN5boost16re_detail_10660016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb[_ZN5boost16re_detail_10660016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb]+0x1d1): undefined reference to `boost::re_detail_106600::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
propedit_cli_parser.cpp:(.text._ZN5boost16re_detail_10660016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb[_ZN5boost16re_detail_10660016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb]+0x49e): undefined reference to `boost::re_detail_106600::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
src/propedit/libmtxpropedit.a(attachment_target.o): In function `attachment_target_c::matches_by_uid_name_or_mime_type(libmatroska::KaxAttached&)':
attachment_target.cpp:(.text+0x2c7e): undefined reference to `libebml::EbmlString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&() const'
src/common/libmtxcommon.a(ebml_chapters_converter.o): In function `mtx::xml::ebml_chapters_converter_c::fix_display(libmatroska::KaxChapterDisplay&) const':
ebml_chapters_converter.cpp:(.text+0x3035): undefined reference to `libebml::EbmlString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&() const'
ebml_chapters_converter.cpp:(.text+0x323b): undefined reference to `libebml::EbmlString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&() const'
collect2: error: ld returned 1 exit status
src/extract/libmtxextract.a(extract_cli_parser.o): In function `__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > boost::re_detail_106600::re_is_set_member<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char, boost::regex_traits<char, boost::cpp_regex_traits<char> >, unsigned int>(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::re_detail_106600::re_set_long<unsigned int> const*, boost::re_detail_106600::regex_data<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, bool)':
extract_cli_parser.cpp:(.text._ZN5boost16re_detail_10660016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb[_ZN5boost16re_detail_10660016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb]+0x1d1): undefined reference to `boost::re_detail_106600::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
extract_cli_parser.cpp:(.text._ZN5boost16re_detail_10660016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb[_ZN5boost16re_detail_10660016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb]+0x49e): undefined reference to `boost::re_detail_106600::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
src/extract/libmtxextract.a(xtr_textsubs.o): In function `xtr_usf_c::create_file(xtr_base_c*, libmatroska::KaxTrackEntry&)':
xtr_textsubs.cpp:(.text+0x1129): undefined reference to `libebml::EbmlString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&() const'
src/common/libmtxcommon.a(ebml_chapters_converter.o): In function `mtx::xml::ebml_chapters_converter_c::fix_display(libmatroska::KaxChapterDisplay&) const':
ebml_chapters_converter.cpp:(.text+0x3035): undefined reference to `libebml::EbmlString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&() const'
ebml_chapters_converter.cpp:(.text+0x323b): undefined reference to `libebml::EbmlString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&() const'
collect2: error: ld returned 1 exit status
src/merge/mkvmerge.o: In function `__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > boost::re_detail_106600::re_is_set_member<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char, boost::regex_traits<char, boost::cpp_regex_traits<char> >, unsigned int>(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::re_detail_106600::re_set_long<unsigned int> const*, boost::re_detail_106600::regex_data<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, bool)':
mkvmerge.cpp:(.text._ZN5boost16re_detail_10660016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb[_ZN5boost16re_detail_10660016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb]+0x1d1): undefined reference to `boost::re_detail_106600::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
mkvmerge.cpp:(.text._ZN5boost16re_detail_10660016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb[_ZN5boost16re_detail_10660016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb]+0x4ae): undefined reference to `boost::re_detail_106600::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
src/common/libmtxcommon.a(ebml_chapters_converter.o): In function `mtx::xml::ebml_chapters_converter_c::fix_display(libmatroska::KaxChapterDisplay&) const':
ebml_chapters_converter.cpp:(.text+0x3035): undefined reference to `libebml::EbmlString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&() const'
ebml_chapters_converter.cpp:(.text+0x323b): undefined reference to `libebml::EbmlString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&() const'
collect2: error: ld returned 1 exit status
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/xorg.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
```

**Comment by retokromer** [comment]
Travis is happy, but I’m afraid I couldn’t understand that hurts Circle.

**Comment by retokromer** [comment]
@iMichka MKVToolNix v20.0.0 has just be released, therefore I guess we should wait until the formula is updated in Brew and consider this one for Linuxbrew as well.

**Comment by mbunkus** [comment]
Just as a heads-up, even though this is probably not the right place for it:

```
==> rake -j32
.....Too long with no output (exceeded 10m0s)
```

rake has serious issues with parallel builds, especially the version coming with macOS. It seems to spawn way more tasks than one sets with `-j…` leading to huge memory usage, swapping and hence compiler processes being killed due to OOM or taking too long. I highly advice to install and use the `drake` gem instead.

**Comment by iMichka** [comment]
@mbunkus Thanks for the heads up. I found a workaround for the `Too long with no output` problem on circle-ci, by using the `--trace` flag, which outputs regularly.

This fails to build in a docker container on my local computer, so I do not believe this is due to a memory problem. I still need to look more closely at the log file.

**Comment by iMichka** [comment]
I tried with -j1, and launched a new build. I am a little bit annoyed because this fails without error message:

```
** Execute manpages
** Invoke translations:programs (first_time)
** Invoke po/ca.mo (first_time)
** Invoke po/ca.po (first_time, not_needed)
** Execute po/ca.mo
      MSGFMT po/ca.po
```

Is there a way to get a more detailed output?

**Comment by mbunkus** [comment]
Sure, add `V=1` which will output the commands executed. However, the output of said program is only passed through; if there's no output, then nothing was produced…

**Comment by iMichka** [comment]
```
** Execute doc/man/mkvmerge.1
/home/linuxbrew/.linuxbrew/opt/libxslt/bin/xsltproc --nonet -o doc/man/mkvmerge.1 /home/linuxbrew/.linuxbrew/opt/docbook-xsl/docbook-xsl/manpages/docbook.xsl doc/man/mkvmerge.xml
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
doc/man/mkvmerge.xml:19: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
]>
  ^
Note: Writing mkvmerge.1
** Invoke doc/man/mkvinfo.1 (first_time)
** Invoke doc/man/mkvinfo.xml (first_time, not_needed)
** Execute doc/man/mkvinfo.1
/home/linuxbrew/.linuxbrew/opt/libxslt/bin/xsltproc --nonet -o doc/man/mkvinfo.1 /home/linuxbrew/.linuxbrew/opt/docbook-xsl/docbook-xsl/manpages/docbook.xsl doc/man/mkvinfo.xml
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
doc/man/mkvinfo.xml:19: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
]>
  ^
Note: Writing mkvinfo.1
** Invoke doc/man/mkvextract.1 (first_time)
** Invoke doc/man/mkvextract.xml (first_time, not_needed)
** Execute doc/man/mkvextract.1
/home/linuxbrew/.linuxbrew/opt/libxslt/bin/xsltproc --nonet -o doc/man/mkvextract.1 /home/linuxbrew/.linuxbrew/opt/docbook-xsl/docbook-xsl/manpages/docbook.xsl doc/man/mkvextract.xml
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
doc/man/mkvextract.xml:19: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
]>
  ^
Note: Writing mkvextract.1
** Invoke doc/man/mkvpropedit.1 (first_time)
** Invoke doc/man/mkvpropedit.xml (first_time, not_needed)
** Execute doc/man/mkvpropedit.1
/home/linuxbrew/.linuxbrew/opt/libxslt/bin/xsltproc --nonet -o doc/man/mkvpropedit.1 /home/linuxbrew/.linuxbrew/opt/docbook-xsl/docbook-xsl/manpages/docbook.xsl doc/man/mkvpropedit.xml
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
doc/man/mkvpropedit.xml:19: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
]>
  ^
Note: Writing mkvpropedit.1
```


Got that error. Let's try to add the `dockbook` dependency.

**Comment by iMichka** [comment]
Actually `docbook` is installed. There was this bug back then: https://github.com/Linuxbrew/homebrew-xorg/issues/11

Setting `ENV["XML_CATALOG_FILES"] = "#{etc}/xml/catalog"` should fix this.

**Comment by retokromer** [comment]
As made in Homebrew, by adding
```
depends_on "cmark" if build.with? "qt"
```
it works fine on my side on Linuxbrew as well.

**Comment by iMichka** [comment]
Rebased, this is now building version `20.0.0` as I merged that just before to homebrew-core. I made even more changes in the hope to get this to build.

**Comment by iMichka** [comment]
```
** Invoke doc/man/mkvextract.1 (first_time)
** Invoke doc/man/mkvextract.xml (first_time, not_needed)
** Execute doc/man/mkvextract.1
    XSLTPROC doc/man/mkvextract.xml
/home/linuxbrew/.linuxbrew/opt/libxslt/bin/xsltproc --nonet -o doc/man/mkvextract.1 /home/linuxbrew/.linuxbrew/opt/docbook-xsl/docbook-xsl/manpages/docbook.xsl doc/man/mkvextract.xml
Note: Writing mkvextract.1
** Invoke doc/man/mkvpropedit.1 (first_time)
** Invoke doc/man/mkvpropedit.xml (first_time, not_needed)
** Execute doc/man/mkvpropedit.1
    XSLTPROC doc/man/mkvpropedit.xml
/home/linuxbrew/.linuxbrew/opt/libxslt/bin/xsltproc --nonet -o doc/man/mkvpropedit.1 /home/linuxbrew/.linuxbrew/opt/docbook-xsl/docbook-xsl/manpages/docbook.xsl doc/man/mkvpropedit.xml
Note: Writing mkvpropedit.1
** Execute manpages
** Invoke translations:programs (first_time)
** Invoke po/ca.mo (first_time)
** Invoke po/ca.po (first_time, not_needed)
** Execute po/ca.mo
      MSGFMT po/ca.po
msgfmt -c -o po/ca.mo po/ca.po
** Invoke apps:tools:ebml_validator (first_time)
** Invoke src/tools/ebml_validator (first_time)
** Invoke src/tools/ebml_validator.o (first_time)
** Invoke src/tools/ebml_validator.cpp (first_time, not_needed)
```

I like how this fails without error message ...

**Comment by mbunkus** [comment]
Adding a dependency on `libxslt` let `configure` find `xsltproc` and proceed to the compilation stage. It fails there for some reason. I'll try to figure out why.

**Comment by iMichka** [comment]
Yes, this is what I did. You can look at the diff of this pull request. If you are using linuxbrew you should be able to `brew pull https://github.com/Linuxbrew/homebrew-core/pull/4963` to test this.

**Comment by mbunkus** [comment]
Huh, I don't understand what happens:

1. using the same arguments to `configure` that `01.configure` lists and compiling with `rake -j4` works; all binaries are built; exit code of `rake -j4` is 0 = success.
2. Using `brew install mkvtoolnix` still fails for some reason? It runs `rake -j4`, `rake` does build everything according to `02.rake`, but `brew install` still says that it failed.
3. However, normally the line `Done. Enjoy :)` is printed after `rake` has done everything. That line is present in 1., but not in `02.rake` in step 2.

I don't think that I can really help here.

**Comment by mbunkus** [comment]
Starting with v20 there's a new option the `Rakefile` knows about, `RUN_SHOW_START_STOP=1`. This causes the output to look something like this:

```
[start          ]          CXX src/common/common_pch.h
[done  00:02.826]          CXX src/common/common_pch.h
[start          ]          CXX src/info/console_ui.cpp
[start          ]          CXX src/merge/mkvmerge.cpp
[start          ]          CXX src/extract/mkvextract.cpp
[start          ]          CXX src/propedit/propedit.cpp
[done  00:00.350]          CXX src/info/console_ui.cpp
[start          ]          CXX src/info/info_cli_parser.cpp
[done  00:00.855]          CXX src/info/info_cli_parser.cpp
[start          ]          CXX src/info/mkvinfo.cpp
[done  00:02.037]          CXX src/extract/mkvextract.cpp
```

which makes it easier to follow which command actually outputs errors. This output leads us to the following:

```
[start          ]       MSGFMT po/cs.po
[fail  00:00.000]       MSGFMT po/cs.po
[start          ]       MSGFMT po/de.po
[fail  00:00.000]       MSGFMT po/de.po
…
```

So all calls to `msgfmt` fail. What's actually executed is this (verified by adding `V=1` to the `rake` call):

```
msgfmt -c -o po/de.mo po/de.po
```

There's no output because `Rakefile` doesn't deal with `command not found` properly (I'll fix that later). And this it the crux of the story: even though `msgfmt` does exist and can be used just fine from a normal shell, it isn't found when run from `brew install…` — meaning `brew install…` messes with `PATH` somehow, probably for the optional stuff, I guess.

So the takeaway is:

1. `configure` doesn't actually check the presence of the `msgfmt` binary. It only checks the existence and usability of the `gettext` C function & library. I'll fix `configure` to run `AC_PATH_PROG` for all relevant binaries regarding `gettext`, and if any of them isn't found, MKVToolNix will simply be built without support for translations.
2. `Rakefile` doesn't deal with binaries not existing well and doesn't output an error message in that case. I'll fix that, too.
3. If you want to make `gettext` truly optional, then you need to actually force `configure` not to check for it if it isn't installed. Otherwise the compiled MKVToolNix will depend on it due to auto-detection, even though the user did not request that optional feature.

None of those two things have changed in ages. My guess is that you made `gettext` optional at some point, and that it started building since then.

Note that you cannot combine `RUN_SHOW_START_STOP=1` and `V=1`; `V=1` takes precedence.

**Comment by mbunkus** [comment]
Done. If you want to build v20, you have two options:

1. Make `gettext` a required dependency until v21.
2. Leave `gettext` an optional dependency, apply [this commit](https://gitlab.com/mbunkus/mkvtoolnix/commit/a26be1f6004e0861df482469831326709ec64f2a) on top of the v20 sources and run `autogen.sh` in order to re-build `configure`.

[This change](https://gitlab.com/mbunkus/mkvtoolnix/commit/de37cf341805cfa7efaba295da67d73776cc8637) is the one making `rake` output proper error messages if the command to execute isn't found. It isn't required for the fix for detecting `msgfmt`, but it can make debugging easier.

Both changes will be part of the next release, of course.

**Comment by retokromer** [comment]
Thank you, @mbunkus, very useful!

@iMichka : I would suggest:
>Make `gettext` a required dependency until v21.

(`gettext` was already installed on my system, therefore I could install with the change mentioned above some days ago.)

**Comment by iMichka** [comment]
Okay so this is what happened:

- `gettext` has been optional since 2014, so nothing has changed on that side
- on mac, `gettext` is provided by the system, and the `gettext` formula is `keg only`, which means it is rarely installed by brew (this is why it was optional).
- previously, we had a ubuntu docker image that had many things pre-installed: this probably allowed to build mkvtoolnix the first time
- another explanation is that brew has now a really strict env filtering: if `gettext` is not defined as a dependency, the system `gettext` will be ignored (the PATHs are being magically cleaned up). This is a good thing because we can not guarantee that a user has `gettext` installed on his system and we need to define the dependency in the dependency list.

I added `gettext` as a dependency for Linux. Let's see if this builds.

@mbunkus thank you to have found this out, this is really helpful. I think that with a better error message from the build process I would have found out what was missing, but the rake output was sort of confusing :)

**Comment by iMichka** [comment]
Ok this is now merged and binaries were built and uploaded. Thanks to all for your help!

**Comment by mbunkus** [comment]
Note that adding `--without-gettext` if the `gettext` feature isn't requested should have fixed this, too, as the auto-detection for the header & library isn't run in that case. I haven't tried it, though.

**Pull request closed without merging**
