### PR TITLE
re2: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
Test fails
>/tmp/ccNtCBBm.o: In function `main':
test.cpp:(.text+0x1c): undefined reference to `re2::RE2::RE2(char const*)'

```
/usr/bin/g++-4.8
-std=c++11
-I/home/linuxbrew/.linuxbrew/Cellar/re2/20170701/include
-L/home/linuxbrew/.linuxbrew/Cellar/re2/20170701/lib
-lre2
test.cpp
-o
test
```

Maybe `-lre2` needs to be put at the end.

**Comment by iMichka** [comment]
Also a follow up from #832

And bang! Fixed!

@sjackman @rwhogg it was not `-lphtread` but `-pthread` ... does this make any sense to you?

**Comment by rwhogg** [comment]
Yes, it does. Here's a line from `gcc --help`:

```
-pthread                Support POSIX threads in generated code
```

I swear that I tried that months ago and it didn't work though.

**Comment by iMichka** [comment]
Weird. It took me some time to find ou what was going on.

Anyway, I'll merge this as soon as core is unfrozen. Thanks for the explanation, I did not know that this was a gcc flag, I just found this by randomly looking at some stackoverflow issues ...

**Comment by sjackman** [comment]
If my reading of this SO question is accurate, `-pthread` is equivalent to
```
cc -D_REENTRANT -D__USE_REENTRANT -lpthread
```

**Comment by iMichka** [comment]
There is also:
> -lpthread comes in existence while linking there will be no influence while preprocessing.

So if you use c++ preprocessor macros, `-lpthread` may not work.

**Comment by sjackman** [comment]
I believe the purpose of `-D_REENTRANT -D__USE_REENTRANT` is to make the standard C library functions (like `malloc` maybe?) reentrant by default.

**Pull request closed without merging**
