### PR TITLE
folly: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
> checking whether the Boost::Context library is available... yes
configure: error: Could not find a version of the library!

**Comment by iMichka** [comment]
Let's try by setting `--with-boost-libdir`

**Comment by iMichka** [comment]
https://github.com/facebook/folly/issues/599
> Folly requires GCC >= 4.9

**Comment by iMichka** [comment]
>  stable version should not decrease (from 2017.07.31.00 to 2017.07.24.00)

**Comment by iMichka** [comment]
Rebasing on master to get the new version

**Comment by iMichka** [comment]
This hit the 4Gb limit now. Let's try with less cores.

**Comment by iMichka** [comment]
> logging.h:695: undefined reference to `google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()

**Comment by sjackman** [comment]
Adding `fails_with :gcc => "5" if OS.linux?` may workaround this failure. Please comment that it's a hack workaround.

**Comment by iMichka** [comment]
Nah this needs c++11, so no gcc4.8:
> error: parameter declared ‘auto’

**Comment by iMichka** [comment]
> Cannot allocate memory
-j20 fails now, but we changed to circle 2 and we changed the compiler.

**Comment by iMichka** [comment]
-j16 fails

**Comment by iMichka** [comment]
Okay this builds now but fails with:
```
./.libs/libfollybase.a(Format.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<int, int>(int const&, int const&, char const*)':
/home/linuxbrew/.linuxbrew/include/glog/logging.h:695: undefined reference to `google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()'
```

We are probably hitting our first ABI compatibly problem post-gcc5 migration. I will merge as-is, without bottle, as there is an update for folly in the next core merge.

**Pull request closed without merging**
