### PR TITLE
muparser: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Circle
```
==> ./configure --disable-debug --disable-dependency-tracking --prefix=/home/linuxbrew/.linuxbrew/Cellar/muparser/2.2.5
.
==> make install
.
Error: patchelf must be installed: brew install patchelf
```

**Comment by maxim-belkin** [comment]
@sjackman thoughts?

**Comment by sjackman** [comment]
It's a bug in `brew` (that I introduced 😳) that affects formula that have no bottled dependencies (which would install `patchelf`).
There's two possible fixes.
1. Have `brew` install `patchelf`
2. Modify `os/linux/elf.rb` to use `binutils readelf` when `patchelf` is not available for reading ELF files.

**Comment by sjackman** [comment]
I've implemented option 2 in PR https://github.com/Linuxbrew/brew/pull/365

**Comment by maxim-belkin** [comment]
Circle:
```
==> brew test muparser --verbose
Testing muparser
==> /usr/bin/g++-4.8 -I/home/linuxbrew/.linuxbrew/Cellar/muparser/2.2.5/include -L/home/linuxbrew/.linuxbrew/Cellar/muparser/2.2.5/lib -lmuparser /tmp/muparser-test-20170501-39758-191058d/test.cpp -o /tmp/muparser-test-20170501-39758-191058d/test
.
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/muparser/test.01.g++-4.8:
2017-05-01 20:50:31 +0000

/usr/bin/g++-4.8
-I/home/linuxbrew/.linuxbrew/Cellar/muparser/2.2.5/include
-L/home/linuxbrew/.linuxbrew/Cellar/muparser/2.2.5/lib
-lmuparser
/tmp/muparser-test-20170501-39758-191058d/test.cpp
-o
/tmp/muparser-test-20170501-39758-191058d/test

/tmp/ccNSrvAH.o: In function `main':
test.cpp:(.text+0x5e): undefined reference to `mu::Parser::Parser()'
test.cpp:(.text+0xa8): undefined reference to `mu::ParserBase::DefineVar(std::string const&, double*)'
test.cpp:(.text+0x171): undefined reference to `mu::ParserBase::SetExpr(std::string const&)'
test.cpp:(.text+0x1db): undefined reference to `mu::ParserBase::Eval() const'
test.cpp:(.text+0x325): undefined reference to `mu::ParserError::GetMsg() const'
/tmp/ccNSrvAH.o: In function `void mu::ParserBase::DefineFun<double (*)(double)>(std::string const&, double (*)(double), bool)':
test.cpp:(.text._ZN2mu10ParserBase9DefineFunIPFddEEEvRKSsT_b[_ZN2mu10ParserBase9DefineFunIPFddEEEvRKSsT_b]+0x24): undefined reference to `mu::ParserBase::ValidNameChars() const'
test.cpp:(.text._ZN2mu10ParserBase9DefineFunIPFddEEEvRKSsT_b[_ZN2mu10ParserBase9DefineFunIPFddEEEvRKSsT_b]+0x51): undefined reference to `mu::ParserCallback::ParserCallback(double (*)(double), bool, int, mu::ECmdCode)'
test.cpp:(.text._ZN2mu10ParserBase9DefineFunIPFddEEEvRKSsT_b[_ZN2mu10ParserBase9DefineFunIPFddEEEvRKSsT_b]+0x6b): undefined reference to `mu::ParserBase::AddCallback(std::string const&, mu::ParserCallback const&, std::map<std::string, mu::ParserCallback, std::less<std::string>, std::allocator<std::pair<std::string const, mu::ParserCallback> > >&, char const*)'
/tmp/ccNSrvAH.o: In function `mu::Parser::~Parser()':
test.cpp:(.text._ZN2mu6ParserD2Ev[_ZN2mu6ParserD5Ev]+0x13): undefined reference to `vtable for mu::Parser'
test.cpp:(.text._ZN2mu6ParserD2Ev[_ZN2mu6ParserD5Ev]+0x1f): undefined reference to `mu::ParserBase::~ParserBase()'
collect2: error: ld returned 1 exit status
Error: muparser: failed
Failed executing: /usr/bin/g++-4.8 -I/home/linuxbrew/.linuxbrew/Cellar/muparser/2.2.5/include -L/home/linuxbrew/.linuxbrew/Cellar/muparser/2.2.5/lib -lmuparser /tmp/muparser-test-20170501-39758-191058d/test.cpp -o /tmp/muparser-test-20170501-39758-191058d/test
```

**Comment by sjackman** [comment]
Swap the order of these two lines
```
-lmuparser
/tmp/muparser-test-20170501-39758-191058d/test.cpp
```

**Comment by maxim-belkin** [comment]
reordered, rebased, and force-pushed

**Comment by sjackman** [comment]
:tada:

**Comment by maxim-belkin** [comment]
Well... this is what I get upon testing the bottle in linuxbrew/linuxbrew docker container:
```
$ brew test muparser
Testing muparser
==> /home/linuxbrew/.linuxbrew/bin/g++-5 -I/home/linuxbrew/.linuxbrew/Cellar/muparser/2.2.5/include -L/home/linuxbrew/.linuxbrew/Cellar/muparser/2.2.5/lib /tmp/muparser-test-20170503-28031-fn
Last 15 lines from /home/linuxbrew/.cache/Homebrew/Logs/muparser/test.01.g++-5:
/home/linuxbrew/.linuxbrew/bin/g++-5
-I/home/linuxbrew/.linuxbrew/Cellar/muparser/2.2.5/include
-L/home/linuxbrew/.linuxbrew/Cellar/muparser/2.2.5/lib
/tmp/muparser-test-20170503-28031-fn7hjt/test.cpp
-lmuparser
-o
/tmp/muparser-test-20170503-28031-fn7hjt/test

/tmp/ccDuIIot.o: In function `main':
test.cpp:(.text+0x95): undefined reference to `mu::ParserBase::DefineVar(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, double*)'
test.cpp:(.text+0x140): undefined reference to `mu::ParserBase::SetExpr(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
test.cpp:(.text+0x2a3): undefined reference to `mu::ParserError::GetMsg[abi:cxx11]() const'
/tmp/ccDuIIot.o: In function `void mu::ParserBase::DefineFun<double (*)(double)>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, double (*)(double), bool)':
test.cpp:(.text._ZN2mu10ParserBase9DefineFunIPFddEEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_b[_ZN2mu10ParserBase9DefineFunIPFddEEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_b]+0x6b): undefined reference to `mu::ParserBase::AddCallback(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, mu::ParserCallback const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, mu::ParserCallback, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, mu::ParserCallback> > >&, char const*)'
collect2: error: ld returned 1 exit status
Error: muparser: failed
Failed executing: /home/linuxbrew/.linuxbrew/bin/g++-5 -I/home/linuxbrew/.linuxbrew/Cellar/muparser/2.2.5/include -L/home/linuxbrew/.linuxbrew/Cellar/muparser/2.2.5/lib /tmp/muparser-test-20170503-28031-fn7hjt/test.cpp -lmuparser -o /tmp/muparser-test-20170503-28031-fn7hjt/test
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1836:in `block in system'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1774:in `open'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1774:in `system'
/home/linuxbrew/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/muparser.rb:59:in `block in <class:Muparser>'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1673:in `block (2 levels) in run_test'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:884:in `with_logging'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1672:in `block in run_test'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1666:in `run_test'
/home/linuxbrew/.linuxbrew/Library/Homebrew/test.rb:33:in `block in <main>'
/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/home/linuxbrew/.linuxbrew/Library/Homebrew/test.rb:32:in `<main>'
```

**Comment by sjackman** [comment]
The bottle was built with GCC 4.8 and the old C++ ABI, so testing it with GCC 5 and the new C++ ABI won't work. 😭
That's the current status quo for Linuxbrew, so you can merge this PR if you like.
I think we should migrate Linuxbrew as quickly as we can to the new C++ ABI.

**Comment by maxim-belkin** [comment]
So... before  we pour a bottle, we should check user's GCC version is ABI-compatible with GCC used to build a bottle. I can merge this PR but it would be nice to at least create an issue or start working on that.

**Comment by sjackman** [comment]
That check is already in there! :tada: The `libstdc++` dependency and compiler version is recorded in `INSTALL_RECEIPT.json`. Unfortunately that support was added only recently, so old bottles don't have it. Meaning, the test only works with newly built bottles.

**Comment by maxim-belkin** [comment]
> That check is already in there! :tada:

Then why did it allow me to pour the bottle?

**Comment by sjackman** [comment]
> Then why did it allow me to pour the bottle?

It'll complain if you attempt to build a formula from source using GCC-5 that depends on `muparser`

**Comment by maxim-belkin** [comment]
ok, but what I meant was that if someone tries to pour a bottle, Linuxbrew should check that system's compiler is ABI-compatible with the one used to create the bottle

**Comment by sjackman** [comment]
`brew test` shouldn't try to use a compiler that's expected to fail.

**Comment by maxim-belkin** [comment]
I'm not following :)

What I'm saying that Linuxbrew should not pour a bottle that was built (on Circle) with GCC that is ABI incompatible with GCC installed on user's system. In such a case it should build it from source. Similar to the way Linuxbrew & Homebrew check for cellar

**Comment by sjackman** [comment]
Linuxbrew should work regardless of the host compiler. If the host compiler is not appropriate, Linuxbrew should install an appropriate compiler. The problem here is that the bottles are built with GCC 4.8, but the Linuxbrew `gcc` formula is GCC 5.3, and the two are not ABI compatible.

**Comment by maxim-belkin** [comment]
> Linuxbrew should work regardless of the host compiler. If the host compiler is not appropriate, Linuxbrew should install an appropriate compiler. The problem here is that the bottles are built with GCC 4.8, but the Linuxbrew `gcc` formula is GCC 5.3, and the two are not ABI compatible.

If Linuxbrew's compiler is installed, it will be used in user's PATH. Hence, if the compiler that is used in the standard environment is not ABI-compatible with the compiler used to build a bottle, the bottle will not be usable. I'm suggesting we build a formula from source if compiler in the standard environment is not ABI-compatible with Circle's compiler.

**Comment by sjackman** [comment]
I suggest that we change the compiler used to build bottles to be ABI compatible with the compiler provided by the formula `gcc`, and keep the two in sync form now on.

**Comment by maxim-belkin** [comment]
Merged!

`gcc` formula should definitely be ABI compatible with bottles. However, if someone is using his/her own system's compiler which is not ABI compatible with Linuxbrew bottles, Linuxbrew should detect this and not pour bottles that are not going to work anyways.

**Pull request closed without merging**
