### PR TITLE
sshfs: Only depends on osxfuse on OSX

### PR DESCRIPTION
**Pull request by dholm**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Thanks for the patch. Could you please post gist-logs of before and after this patch is applied? (yes, we're lazy)

**Comment by sjackman** [comment]
I believe @rwhogg had worked on `:osxfuse`.

**Comment by sjackman** [comment]
TravisCI
```
configure: error: Package requirements (fuse >= 2.3 glib-2.0 gthread-2.0) were not met:
No package 'fuse' found
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/232326755#L2116

The correct fix here is that `:osxfuse` should depend on `libfuse` on Linuxbrew. I believe that's what @rwhogg was working on.

**Comment by rwhogg** [comment]
https://github.com/Homebrew/brew/pull/2274 was my PR to do that, but we elected not to add a dependency on `libfuse` upstream.

I don't disagree with that decision, but do feel that on a temporary basis we should add a `default_formula libfuse` for Linuxbrew. Yeah, divergence is unfortunate, but user experience is more important.

**Comment by sjackman** [comment]
Seems it's already in there: https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/requirements/osxfuse_requirement.rb#L27

@dholm What error were you trying to fix with this PR?

**Comment by dholm** [comment]
@sjackman 

`$ brew upgrade -v sshfs
==> Upgrading 1 outdated package, with result:
sshfs 2.9
Error: wrong number of arguments (0 for 1..3)
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/eholmda/.linuxbrew/Library/Homebrew/requirement.rb:58:in `instance_eval'
/home/eholmda/.linuxbrew/Library/Homebrew/requirement.rb:58:in `block in satisfied?'
/home/eholmda/.linuxbrew/Library/Homebrew/requirement.rb:200:in `block in yielder'
/home/eholmda/.linuxbrew/Library/Homebrew/extend/ENV.rb:25:in `with_build_environment'
/home/eholmda/.linuxbrew/Library/Homebrew/requirement.rb:200:in `yielder'
/home/eholmda/.linuxbrew/Library/Homebrew/requirement.rb:58:in `satisfied?'
/home/eholmda/.linuxbrew/Library/Homebrew/formula_installer.rb:441:in `block in expand_requirements'
/home/eholmda/.linuxbrew/Library/Homebrew/requirement.rb:232:in `block in prune?'
/home/eholmda/.linuxbrew/Library/Homebrew/requirement.rb:230:in `catch'
/home/eholmda/.linuxbrew/Library/Homebrew/requirement.rb:230:in `prune?'
/home/eholmda/.linuxbrew/Library/Homebrew/requirement.rb:221:in `block (2 levels) in expand'
/home/eholmda/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/lib/ruby/2.0.0/set.rb:232:in `each_key'
/home/eholmda/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/lib/ruby/2.0.0/set.rb:232:in `each'
/home/eholmda/.linuxbrew/Library/Homebrew/dependencies.rb:68:in `each'
/home/eholmda/.linuxbrew/Library/Homebrew/requirement.rb:220:in `block in expand'
/home/eholmda/.linuxbrew/Library/Homebrew/requirement.rb:219:in `each'
/home/eholmda/.linuxbrew/Library/Homebrew/requirement.rb:219:in `expand'
/home/eholmda/.linuxbrew/Library/Homebrew/formula.rb:1525:in `recursive_requirements'
/home/eholmda/.linuxbrew/Library/Homebrew/formula_installer.rb:429:in `expand_requirements'
/home/eholmda/.linuxbrew/Library/Homebrew/formula_installer.rb:371:in `compute_dependencies'
/home/eholmda/.linuxbrew/Library/Homebrew/formula_installer.rb:135:in `verify_deps_exist'
/home/eholmda/.linuxbrew/Library/Homebrew/formula_installer.rb:128:in `prelude'
/home/eholmda/.linuxbrew/Library/Homebrew/cmd/upgrade.rb:128:in `upgrade_formula'
/home/eholmda/.linuxbrew/Library/Homebrew/cmd/upgrade.rb:92:in `block in upgrade'
/home/eholmda/.linuxbrew/Library/Homebrew/cmd/upgrade.rb:90:in `each'
/home/eholmda/.linuxbrew/Library/Homebrew/cmd/upgrade.rb:90:in `upgrade'
/home/eholmda/.linuxbrew/Library/Homebrew/brew.rb:91:in `<main>'
`

**Comment by rwhogg** [comment]
> Seems it's already in there: https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/requirements/osxfuse_requirement.rb#L27

Sorry, I meant after brew 1.2.0 is merged. https://github.com/Homebrew/brew/blob/master/Library/Homebrew/extend/os/linux/requirements/osxfuse_requirement.rb

**Comment by sjackman** [comment]
Here's a PR to merge `brew` 1.2.0, if you'd like to test it out before it's merged:
https://github.com/Linuxbrew/brew/pull/385

**Comment by sjackman** [comment]
I've merged `brew` 1.2.0, obviating this PR. Thanks for reporting this bug, David.

**Pull request closed without merging**
