### PR TITLE
dmd: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by rwhogg** [comment]
Linkage failure on Circle seems to be coming from /lib64/ld-linux-x86-64.so.2. IMO, this should be whitelisted.

**Comment by sjackman** [comment]
`dmd` does in fact include the dynamic linker in its `DT_NEEDED` list. That's weird. I wonder why it does that.
```
$ patchelf --print-needed $(which dmd)
libstdc++.so.6
libpthread.so.0
librt.so.1
libm.so.6
libgcc_s.so.1
libc.so.6
ld-linux-x86-64.so.2
```

**Comment by maxim-belkin** [comment]
rebased on top of the latest Linuxbrew

**Comment by rwhogg** [comment]
Rebased after merging https://github.com/Linuxbrew/brew/issues/342. It should pass on Circle now.

**Comment by maxim-belkin** [comment]
passed! yay!

**Pull request closed without merging**
