### PR TITLE
pypy3: fixes for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Successful build: https://gist.github.com/3f8272430c48d3dc6f774b6312aebe8b

### CODE REVIEW

**Comment by maxim-belkin** [comment]
@iMichka, I think we have to do the same thing as before: merge this "as is" and build it locally.

**Comment by sjackman** [comment]
Thanks for this work, Maxim!

**Comment by iMichka** [comment]
Thanks. I'll build the bottle myself :)

**Comment by iMichka** [comment]
```
Missing libraries:
  libtcl8.6.so
  libtk8.6.so
Unwanted system libraries:
  libbz2.so.1.0
  libexpat.so.1
  libffi.so.6
  libz.so.1
```

Did you forget to add the dependencies?

**Comment by maxim-belkin** [comment]
Ah, dang it! yes!

**Comment by sjackman** [comment]
🎉 ❤️ Thanks, Maxim!

**Pull request closed without merging**
