### PR TITLE
ruby: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 1.16.1
Fetching gemoji 3.0.0
Bundler::GemspecError: Could not read gem at
/tmp/ruby-test-20180219-29794-dy2o12/cache/gemoji-3.0.0.gem. It may be
corrupted.
An error occurred while installing gemoji (3.0.0), and Bundler cannot continue.
Make sure that `gem install gemoji -v '3.0.0'` succeeds before bundling.

In Gemfile:
  gemoji
Error: ruby: failed
```

**Comment by sjackman** [comment]
I was hoping that it was a transient error, but it occurred twice on CircleCI.
https://circleci.com/gh/Linuxbrew/homebrew-core/13295
https://circleci.com/gh/Linuxbrew/homebrew-core/13333

**Comment by iMichka** [comment]
That's annoying, I can't reproduce this locally in a docker container, and a third build on circle failed.

Guess I will need to connect to the running container with ssh ...

**Comment by iMichka** [comment]
Actually going back to the previous version we shipped is broken too.

Maybe my local build is not to be considered, as it may contain some cached gems ...

I'll continue to investigate this later. Maybe there is a real problem with that `gemoji` gem ...

**Comment by iMichka** [comment]
Looks really like https://discuss.circleci.com/t/bundler-error-in-rails-app-same-revision-passes-locally-and-on-other-branch/591

I already tried to build without cache. I'll login with ssh and see what gems are already installed.

**Comment by iMichka** [comment]
Ok actually this is the test which is failing ... my bad ... bottle is fine :)

I do not have much time to spend fixing this so I'll just pull the bottle for the moment.

**Pull request closed without merging**
