### PR TITLE
pulseaudio: fix source build with default options

### PR DESCRIPTION
**Pull request by jpauwels**
- [x] Have you followed the [guidelines for contributing]([](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md))?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jpauwels** [comment]
Reading the upstream bug report, I realised that the compilation failure (#1174) only occurs when building with X11. Normally, the default option for the formula should be to disable X11 support, but the correct flag wasn't passed on until this commit. For a source build with default options, the compilation error should now be bypassed, but it still can be recalled by `brew install pulseaudio --with-x11`.

**Comment by rwhogg** [comment]
Thanks a bunch @jpauwels! :smile_cat: 

@MikeMcQuaid would you accept this patch upstream? The issue affects macOS (i.e. if XQuartz is installed then `pulseaudio` will try to use it by default) and thus anyone in that scenario building from source will hit https://github.com/Homebrew/homebrew-core/issues/2408.

**Comment by MikeMcQuaid** [comment]
@rwhogg Works for me but it sounds like removing the X11 option would be a better upstream fix, maybe?

**Comment by rwhogg** [comment]
> it sounds like removing the X11 option would be a better upstream fix, maybe?

Good point. Supporting a broken build option isn't helping anyone.

@jpauwels, would you like to do the following?

* Remove the optional dependency on X11 altogether
* Put the `--disable-x11` into the args array, and don't make it conditional
* Send the patch in a PR to Homebrew/homebrew-core?

If you don't have a Mac to test the patch on, no worries as I can do that for you.

Thanks again!

**Comment by jpauwels** [comment]
Patch changed, but I'm struggling to find the most efficient way to submit to Homebrew/homebrew-core. The best option I can think of:
- Create a new branch at the point where Homebrew/homebrew-core and Linuxbrew/homebrew-core diverge
- Cherry-pick my commit onto that branch
- Create a PR from that branch

However, I can't seem to quickly find the divergence point. Is there a better way? Anything else I can come up with fails because Github remembers I forked from Linuxbrew, not Homebrew and I can't have two forks.

**Comment by rwhogg** [comment]
@jpauwels:

> However, I can't seem to quickly find the divergence point. Is there a better way? Anything else I can come up with fails because Github remembers I forked from Linuxbrew, not Homebrew and I can't have two forks.

Yes, there's a better way. On your local machine, run commands like these:

```bash
% git remote add homebrew https://github.com/homebrew/homebrew-core
% git fetch homebrew
% git checkout --track homebrew/master -b homebrew-master
% git checkout -b pulseaudio-remove-x11
```

From there, you can cherry-pick, verify that it still works, and push to GitHub. The easiest way to make a PR to Homebrew rather than Linuxbrew (given that you forked from Linuxbrew) is to go to https://github.com/homebrew/homebrew-core and hit the new PR button.

If you have any further questions, feel free to message again. We're always happy to have new contributors :smile_cat:

**Comment by jpauwels** [comment]
@rwhogg got it, thanks, see https://github.com/Homebrew/homebrew-core/pull/7779

**Comment by sjackman** [comment]
Superseded by Homebrew#7779.
Thanks for the patch, Johan!

**Pull request closed without merging**
