### PR TITLE
bazel: limit resources for building

### PR DESCRIPTION
**Pull request by carlorosati**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Addresses issue #1497

### CODE REVIEW

**Comment by sjackman** [comment]
Do you know whether this issue also affects macOS?

**Comment by sjackman** [comment]
TravisCI
```
ERROR: /tmp/bazel-20170316-23166-1y4vp9/src/main/java/com/google/devtools/build/lib/BUILD:985:1: Java compilation in rule '//src/main/java/com/google/devtools/build/lib:runtime' failed: Worker process sent response with exit code: 1..
java.io.IOException: Cannot write dependencies to bazel-out/host/bin/src/main/java/com/google/devtools/build/lib/libruntime.jdeps
	at com.google.devtools.build.buildjar.javac.plugins.dependency.DependencyModule.emitDependencyInformation(DependencyModule.java:137)
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/211725354#L1949

**Comment by sjackman** [comment]
CircleCI: `Your build has exceeded the memory limit of 4G on 1 container.`
See https://4386-56942570-gh.circle-artifacts.com/0/tmp/memory-usage.txt
It's currently using ~36 threads. The number of threads configured by Homebrew is found in the variable `ENV.make_jobs`. Pass that argument (somehow) to the `bazel` build system. On Linuxbrew CircleCI it's set to 8 by default.

**Comment by carlorosati** [comment]
I just tried building this on a Mac from source. No issue. I'm not sure what the Linux kernel or the shell does differently than on macOS/Darwin to allow such an absurd number of threads be spawned and lag the system to a halt.

**Comment by sjackman** [comment]
It appears to use as many threads as there are CPUs provided by the host. CircleCI provides 32 CPUs. You'll have to tell the `bazel` build system explicitly to use fewer threads. For an example in `boost` see https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/boost.rb#L70

**Comment by carlorosati** [comment]
Closing as upstream ```--jobs``` does not limit threads.

**Pull request closed without merging**
