### PR TITLE
amqp-cpp: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
```
==> brew test amqp-cpp --verbose
Testing amqp-cpp
==> /usr/bin/g++-4.8 test.cpp -std=c++11 -L/home/linuxbrew/.linuxbrew/Cellar/amqp-cpp/2.6.2/lib -o test -lc++ -lamqp-cpp
.
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/amqp-cpp/test.01.g++-4.8:
2017-04-25 20:20:11 +0000

/usr/bin/g++-4.8
test.cpp
-std=c++11
-L/home/linuxbrew/.linuxbrew/Cellar/amqp-cpp/2.6.2/lib
-o
test
-lc++
-lamqp-cpp

/usr/bin/ld: cannot find -lc++
collect2: error: ld returned 1 exit status
```

**Comment by maxim-belkin** [comment]
@sjackman ?
```
$ git diff
diff --git a/Formula/amqp-cpp.rb b/Formula/amqp-cpp.rb
index 8e799b7..d8bb795 100644
--- a/Formula/amqp-cpp.rb
+++ b/Formula/amqp-cpp.rb
@@ -31,8 +31,8 @@ class AmqpCpp < Formula
         return 0;
       }
       EOS
-    system ENV.cxx, "test.cpp", "-std=c++11", "-L#{lib}", "-o",
-                    "test", "-lc++", "-lamqp-cpp"
+    system ENV.cxx, "test.cpp", "-std=c++11", *("-pthread" if ENV.compiler == :gcc), "-L#{lib}", "-o",
+                    "test", *("-lc++" if ENV.compiler == :clang), "-lamqp-cpp"
     system "./test"
   end
 end
```

**Comment by maxim-belkin** [comment]
I'm not sure about `-lc++" if ENV.compiler == :clang` bit

**Comment by sjackman** [comment]
`-lc++` looks super weird to me. I'd go with
```ruby
*("-lc++" if OS.mac?)
```

**Comment by maxim-belkin** [comment]
Travis:
```
home/linuxbrew/.linuxbrew/bin/g++-5
test.cpp
-std=c++11
-L/home/linuxbrew/.linuxbrew/Cellar/amqp-cpp/2.6.2/lib
-o
test
-lamqp-cpp
/home/linuxbrew/.linuxbrew/Cellar/amqp-cpp/2.6.2/lib/libamqp-cpp.so: undefined reference to `pthread_create'
```

**Comment by sjackman** [comment]
Odd (to me) that the error occurs on TravisCI (GCC 5.3) but not on CircleCI (GCC 4.8).

**Comment by maxim-belkin** [comment]
`-pthread` was not added on Travis as if `ENV.compiler == :gcc` is not true there

**Comment by maxim-belkin** [comment]
this is what I got in a linuxbrew/linuxbrew container:
```ruby
ohai ENV.compiler.to_s # gcc-5
ohai :gcc.to_s # gcc
ohai ENV.compiler == :gcc # false
```

**Comment by sjackman** [comment]
It's a historical anachronism, but `:gcc` is an alias for specifically GCC 4.2.

**Comment by maxim-belkin** [comment]
Circle:
```
==> brew test amqp-cpp --verbose
Testing amqp-cpp
==> /usr/bin/g++-4.8 test.cpp -std=c++11 -L/home/linuxbrew/.linuxbrew/Cellar/amqp-cpp/2.6.2/lib -o test -lamqp-cpp

==> ./test
```

so, `-pthread` was not added either but it worked

**Pull request closed without merging**
