### PR TITLE
go: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
==> go build

Error: Failure while executing: /home/linuxbrew/.linuxbrew/opt/glibc/bin/ldd /home/linuxbrew/.linuxbrew/Cellar/go/1.9/libexec/src/debug/dwarf/testdata/line-clang.elf
/home/linuxbrew/.linuxbrew/opt/glibc/bin/ldd: line 117: /home/linuxbrew/.linuxbrew/Cellar/go/1.9/libexec/src/debug/dwarf/testdata/line-clang.elf: Permission denied 
==> FAILED
```

**Comment by sjackman** [comment]
```
/home/linuxbrew/.linuxbrew/Cellar/go/1.9/libexec/src/debug/dwarf/testdata/line-clang.elf: Permission denied 
```
My best guess is that `line-clang.elf` does not have its executable permission bit set.
Torsten @tseemann has also reported this error message.

**Comment by tseemann** [comment]
Yes, it's still  here: https://github.com/Linuxbrew/homebrew-core/issues/2798

**Comment by tseemann** [comment]
@sjackman @iMichka I have untarred `go-1.9.tar.gz` and had a look:
```
ls ./src/debug/dwarf/testdata/ -l
total 248
-rw-r--r--. 1 linuxbrew linuxbrew    103 Aug 25 07:50 cycle.c
-rw-r--r--. 1 linuxbrew linuxbrew   2624 Aug 25 07:50 cycle.elf
-rw-r--r--. 1 linuxbrew linuxbrew  10271 Aug 25 07:50 line-clang.elf
-rw-r--r--. 1 linuxbrew linuxbrew 133202 Aug 25 07:50 line-gcc-win.bin
-rw-r--r--. 1 linuxbrew linuxbrew  10113 Aug 25 07:50 line-gcc.elf
-rw-r--r--. 1 linuxbrew linuxbrew     61 Aug 25 07:50 line1.c
-rw-r--r--. 1 linuxbrew linuxbrew     83 Aug 25 07:50 line1.h
-rw-r--r--. 1 linuxbrew linuxbrew     54 Aug 25 07:50 line2.c
-rw-r--r--. 1 linuxbrew linuxbrew    415 Aug 25 07:50 ranges.c
-rwxr-xr-x. 1 linuxbrew linuxbrew  10348 Aug 25 07:50 ranges.elf
-rw-r--r--. 1 linuxbrew linuxbrew     59 Aug 25 07:50 split.c
-rw-r--r--. 1 linuxbrew linuxbrew   9509 Aug 25 07:50 split.elf
-rw-r--r--. 1 linuxbrew linuxbrew   2083 Aug 25 07:50 typedef.c
-rwxr-xr-x. 1 linuxbrew linuxbrew  12448 Aug 25 07:50 typedef.elf
-rw-r--r--. 1 linuxbrew linuxbrew   9496 Aug 25 07:50 typedef.elf4
-rw-r--r--. 1 linuxbrew linuxbrew   5024 Aug 25 07:50 typedef.macho
```

The `line-clang.elf` and `line-gcc.elf` etc are NOT executable, where some of the others are.

Does this help?

PS. Also, if we are building with `gcc` i'm not sure why it is touching `clang` related stuff anyway?

**Comment by iMichka** [comment]
I tested locally on my Ubuntu 17.04, and I had not trouble building go from source. Don't know why it is different on the buildbot. Anyway, I changed to code to set the executable bit for these files. Let's see if it helps.

**Comment by iMichka** [comment]
```
/home/linuxbrew/.linuxbrew/opt/glibc/bin/ldd: line 117: /home/linuxbrew/.linuxbrew/Cellar/go/1.9/libexec/src/debug/elf/testdata/gcc-amd64-linux-exec: Permission denied
```

Another file now ..

**Comment by iMichka** [comment]
Ok bottles built. I need to remove the devel block too, which is gone upstream but I probably missed while doing the merge. Let's rebuild this one last time.

**Comment by iMichka** [comment]
@tseemann @sjackman go bottles built and uploaded!

**Comment by tseemann** [comment]
ALL SYSTEMS ARE "Go"  !

**Pull request closed without merging**
