### PR TITLE
mobile-shell: Depends on openssl for Linuxbrew

### PR DESCRIPTION
**Pull request by timotheecour**
- [x ] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x ] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fix https://github.com/Linuxbrew/homebrew-core/issues/1562

### CODE REVIEW

**Comment by sjackman** [comment]
http://stackoverflow.com/a/30175210/423153
> If libprotobuf was built with GCC 4.x or prior, but your app is built with GCC 5, then you will see problems, because libprotobuf uses std::string in its interface. You have two options:
1. Rebuild libprotobuf with GCC 5 (but now any apps built with GCC 4 won't work with the new version of libprotobuf).
2. Build you app with -D_GLIBCXX_USE_CXX11_ABI=0 as described at the above link. This will force GCC to use the old ABI version.

Thanks for this reference. For your `gist` it looks as though you're using your host system's `gcc` 4.8 can you confirm that's the case? The `mobile-shell` bottle built fine on Circle with Ubuntu 14, so I'm surprised by this error.

**Comment by timotheecour** [comment]
PTAL

this worked for me on a fresh brew install after reverted the last commit (in https://github.com/Linuxbrew/homebrew-core/pull/1577/commits/6600d61ef01adf6ccf77d6a0fd06aced13dd52f0) 

> For your gist it looks as though you're using your host system's gcc 4.8 can you confirm that's the case?

Yes, here's the relevant line from https://gist.github.com/timotheecour/143e39752eb60827c954b298f905c2ae :
```
CC: /usr/bin/gcc-4.8
CXX: /usr/bin/g++-4.8
```
if that's insufficient we should `fix the gist` :)

Also:
```
which -a gcc
/home/timothee/.linuxbrew//bin/gcc
/usr/bin/gcc
/usr/bin/gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
```


Not exactly sure what had happened in https://github.com/Linuxbrew/homebrew-core/issues/1562#issuecomment-271792013 but probably something related to trying to install another library, I think it was grpc/grpc; I will file a separate bug for that.

```
# add `depends_on "openssl" unless OS.mac?` to mobile-shell.rb from a fresh brew install
$brew install mosh
#works

$which -a protoc
/home/timothee/.linuxbrew//bin/protoc

$protoc --version
libprotoc 3.1.0

$brew tap grpc/grpc
$brew install --with-plugins grpc
==> Installing grpc from grpc/grpc
==> Installing dependencies for grpc/grpc/grpc: google-protobuf
==> Installing grpc/grpc/grpc dependency: google-protobuf
Error: Cannot install grpc/grpc/google-protobuf because conflicting formulae are installed.

  protobuf: because this formula is a customized version of protobuf formula

Please `brew unlink protobuf` before continuing.

$brew unlink protobuf
$brew install --with-plugins grpc #ok

$brew reinstall mosh
Error: You must `brew link protobuf` before mobile-shell can be installed
$brew link protobuf
Linking /home/timothee/ubuntu1404/temp/brew/Cellar/protobuf/3.1.0...
Error: Could not symlink bin/protoc
Target /home/timothee/ubuntu1404/temp/brew/bin/protoc
is a symlink belonging to google-protobuf. You can unlink it:
  brew unlink google-protobuf

To force the link and overwrite all conflicting files:
  brew link --overwrite protobuf

To list all files that would be deleted:
  brew link --overwrite --dry-run protobuf

$brew unlink google-protobuf
$brew link protobuf
$brew reinstall mosh #works
```

**Comment by sjackman** [comment]
Travis
```
671.40s$ travis_wait brew test-bot
Still running (12 of 20): brew test-bot
The command brew test-bot exited with 1.
Log:
cat: travis_wait_1673.log: No such file or directory
/home/travis/build.sh: line 151: 11573 Terminated              travis_jigger $! $timeout $cmd
The command "travis_wait brew test-bot" exited with 1.
Done. Your build exited with 1.
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/192652898
I'm unsure what this error means. Perhaps we need to remove `travis_wait`.

**Comment by sjackman** [comment]
Merged. Thanks for your contribution to Linuxbrew, Timothee.

**Pull request closed without merging**
