### PR TITLE
ghc: Fix for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**
Fix the error:
```
checking version of ghc... 7.8.4
configure: error: GHC version 7.10 or later is required to compile GHC.
```

### CODE REVIEW

**Comment by maxim-belkin** [comment]
```
Your build has exceeded the memory limit of 4G on 1 container
```

**Comment by sjackman** [comment]
| Jobs | Status |
|---|---|
| 16 | |
| 29 | ❌ |

**Comment by iMichka** [comment]
Does this use `ghc@8` to be compiled? Because for `ghc@8` there is no bottle, because that build also timed out/hit the memory limit.

**Comment by sjackman** [comment]
`ghc@8.0` does have a bottle. I built it locally using `brew test-bot-docker ghc@8.0`. I'll do the same for this formula if it's not possible to build on CI.

`ghc` bootstraps itself not with `ghc@8.0` but with a binary distribution of GHC.

**Comment by CristianCantoro** [comment]
Sorry if this is not the right place to ask, I bumped into the same bug and I was wondering why there are two formulae for `ghc` one is `v. 8.0.2` and the other is `v. 8.2.1` from the [GHC homepage](https://www.haskell.org/ghc/) I see one is the latest stable version and the former is the old-stable, but why are we keeping two?

**Comment by sjackman** [comment]
I'm afraid I don't have the answer to that question. That decision is made by the upstream Homebrew developers. I presume it's because some GHC formulae fail to build with GHC 8.2.1.
@ilovezfs Do you know the answer?

**Comment by ilovezfs** [comment]
>I presume it's because some GHC formulae fail to build with GHC 8.2.1.

Correct. You can track the progress here: https://github.com/Homebrew/homebrew-core/pull/15934#issuecomment-317268668

**Pull request closed without merging**
