### PR TITLE
geos: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
configure: error: cannot find Python library path

==> Formula
Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/geos.rb
```

**Comment by iMichka** [comment]
I found a ugly hack. The build script is quite ... surprising. This is now fixed.

**Comment by iMichka** [comment]
And I will not upstream that change, as https://trac.osgeo.org/geos/ticket/771 was already opened to ask better support a long time ago.

**Comment by jonchang** [comment]
Thanks @iMichka! This was causing issues for me. I should probably email the developers to see if they can't fix their build script to be less surprising.

**Pull request closed without merging**
