### PR TITLE
crystal-lang: Build a bottle for Linuxbrew: No output has been received in the last 10m0s

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
Both CircleCI and TravisCI
```
==> make crystal release=true
.
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/230445391#L2868
It's supposed to output a dot every minute. It went ten minutes without outputting a dot. I can't say why.

**Comment by develop7** [comment]
OK, it's [just `make`](https://crystal-lang.org/docs/installation/from_source_repository.html) now; could you try again?

**Comment by sjackman** [comment]
I've retried this PR, and increased the CircleCI `timeout` to 2 hours.

> OK, it's just `make` now; could you try again?

Could you please elaborate? If the formula needs to change, please open a PR.

**Comment by sjackman** [comment]
> Your build has exceeded the memory limit of 4G on 1 container.

https://circleci.com/gh/Linuxbrew/homebrew-core/5951

**Comment by sjackman** [comment]
Uh oh. One single process of `crystal build` is consuming over 4 GB of RAM and being killed by CircleCI.
@develop7 Do you know of a fix/workaround for that, Andrei?

**Comment by develop7** [comment]
@sjackman no idea. My rig got 32G, so I didn't care of RAM at the moment. Do you think the issue belongs to [crystal-lang/crystal](/crystal-lang/crystal)?

**Comment by sjackman** [comment]
You can report the issue, and it'll be up to them whether they consider reducing the memory usage below 4 GB an important goal. You can mention that CircleCI has a 4 GB memory limit as the use case. Perhaps they'll have some tips on command line options to reduce the memory usage.

**Comment by develop7** [comment]
They actually do use CircleCI too, see https://github.com/crystal-lang/crystal/blob/master/circle.yml. Wonder how they're not affected by memory limit.

**Comment by sjackman** [comment]
That's good news.
@matiasgarciaisaia @mverzilli Linuxbrew is unable to build `crystal-lang` on CircleCI, because it exceeds the 4 GB memory limit.
See https://circleci.com/gh/Linuxbrew/homebrew-core/5951
and https://5951-56942570-gh.circle-artifacts.com/0/tmp/memory-usage.txt
Do you have tips for building `crystal-lang` on CircleCI?

**Comment by matiasgarciaisaia** [comment]
@sjackman we're only building OSX on CircleCI, so there may be some differences that make it not hit the 4GB limit.

Anyway, for the omnibus setup we've hit this very same issue, which was worked around by adding `--no-debug` to the compiling options. You can see [this commit](https://github.com/crystal-lang/omnibus-crystal/pull/18/commits/565c81c068e6463edf6e3a69d970fe07a5a220de) for reference.

Sorry I can't jump into this repo right now :/ - but feel free to ping as needed 👍

**Comment by sjackman** [comment]
@develop7 Would you be interested in submitting a PR to Linuxbrew/core that implements the suggestion of @matiasgarciaisaia ?

**Comment by develop7** [comment]
@sjackman can do!

**Comment by sjackman** [comment]
Thanks!

**Pull request closed without merging**
