### PR TITLE
vim: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
==> brew install --build-bottle --verbose vim
Error: undefined method `dirname' for nil:NilClass
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/linuxbrew/.linuxbrew/Library/Homebrew/requirements/ruby_requirement.rb:14:in `block in <class:RubyRequirement>'
/home/linuxbrew/.linuxbrew/Library/Homebrew/requirement.rb:90:in `instance_eval'
/home/linuxbrew/.linuxbrew/Library/Homebrew/requirement.rb:90:in `modify_build_environment'
/home/linuxbrew/.linuxbrew/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/set.rb:324:in `each_key'
/home/linuxbrew/.linuxbrew/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/set.rb:324:in `each'
/home/linuxbrew/.linuxbrew/Library/Homebrew/dependencies.rb:68:in `each'
/home/linuxbrew/.linuxbrew/Library/Homebrew/build.rb:93:in `install'
/home/linuxbrew/.linuxbrew/Library/Homebrew/build.rb:201:in `<main>'
==> FAILED
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/215807708#L2644

This build error is likely related to https://github.com/Linuxbrew/brew/pull/269

**Comment by carlorosati** [comment]
ahh okay that should be easy to fix

**Comment by sjackman** [comment]
Yep, I did. Does the fix look right to you?

**Comment by carlorosati** [comment]
@sjackman Yeah. That looks good

**Pull request closed without merging**
