### PR TITLE
calc: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
forming calc.usage from calc.1
/bin/sh: 5: col: not found
Makefile:2329: recipe for target 'calc.usage' failed
make: *** [calc.usage] Error 127
```

**Comment by sjackman** [comment]
`col` is included in `bsdmainutils`.

**Comment by sjackman** [comment]
Thanks, Michka! I use `calc` a fair bit in fact.

**Comment by iMichka** [comment]
I must say that env filtering and our minimal Ubuntu docker setup really help find these « hidden » dependencies. That’s really nice :)

**Pull request closed without merging**
