### PR TITLE
fontconfig: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by arkanoid87** [comment]
[jack@geo1 ~]$ brew install linuxbrew/xorg/xorg
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Installing xorg from linuxbrew/xorg
==> Installing dependencies for linuxbrew/xorg/xorg: fontconfig, linuxbrew/xorg/libxft, linuxbrew/xorg/libxi, linuxbrew/xorg/libxinerama, linuxbrew/xorg/libxrandr, linuxbrew/xorg/libxres, linuxbrew/xorg/libxtst, linuxbrew/xorg/libxv, linuxbrew/xorg/videoproto, linuxbrew/xorg/libxvmc, linuxbrew/xorg/libxxf86dga, linuxbrew/xorg/libxxf86vm, linuxbrew/xorg/libdmx, linuxbrew/xorg/libpciaccess, linuxbrew/xorg/libxkbfile, linuxbrew/xorg/libxshmfence, linuxbrew/xorg/xdpyinfo
==> Installing linuxbrew/xorg/xorg dependency: fontconfig
==> Downloading https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.13.0.tar.bz2
Already downloaded: /home/nfs/jack/.cache/Homebrew/fontconfig-2.13.0.tar.bz2
==> autoreconf -iv
Last 15 lines from /home/nfs/jack/.cache/Homebrew/Logs/fontconfig/01.autoreconf:
2018-05-04 22:33:21 +0200

autoreconf
-iv

autoreconf: Entering directory `.'
autoreconf: running: autopoint
Can't exec "autopoint": No such file or directory at /home/nfs/jack/.linuxbrew/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 345.
autoreconf: failed to run autopoint: No such file or directory
autoreconf: autopoint is needed because this package uses Gettext

READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.

These open issues may also help:
fontconfig: Build a bottle for Linuxbrew https://github.com/Linuxbrew/homebrew-core/pull/7514
[jack@geo1 ~]$

**Comment by iMichka** [comment]
```
==> autoreconf -iv
.
Last 150 lines from /home/linuxbrew/.cache/Homebrew/Logs/fontconfig/01.autoreconf:
2018-05-04 19:23:16 +0000

autoreconf
-iv

autoreconf: Entering directory `.'
autoreconf: running: autopoint
Can't exec "autopoint": No such file or directory at /home/linuxbrew/.linuxbrew/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 345.
autoreconf: failed to run autopoint: No such file or directory
autoreconf: autopoint is needed because this package uses Gettext
```

**Comment by arkanoid87** [comment]
[jack@geo1 ~]$ brew install fontconfig
Updating Homebrew...
==> Downloading https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.13.0.tar.bz2
Already downloaded: /home/nfs/jack/.cache/Homebrew/fontconfig-2.13.0.tar.bz2
==> autoreconf -iv
Last 15 lines from /home/nfs/jack/.cache/Homebrew/Logs/fontconfig/01.autoreconf:
Copying file m4/threadlib.m4
Copying file m4/uintmax_t.m4
Copying file m4/visibility.m4
Copying file m4/wchar_t.m4
Copying file m4/wint_t.m4
Copying file m4/xsize.m4
Copying file po/Makevars.template
Copying file po-conf/Makevars.template
autoreconf: running: aclocal -I m4
Can't locate Data/Dumper.pm in @INC (@INC contains: /home/nfs/jack/.linuxbrew/Cellar/autoconf/2.69/share/autoconf /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/nfs/jack/.linuxbrew/Cellar/autoconf/2.69/share/autoconf/Autom4te/C4che.pm line 33.
BEGIN failed--compilation aborted at /home/nfs/jack/.linuxbrew/Cellar/autoconf/2.69/share/autoconf/Autom4te/C4che.pm line 33.
Compilation failed in require at /home/nfs/jack/.linuxbrew/Cellar/autoconf/2.69/bin/autom4te line 37.
BEGIN failed--compilation aborted at /home/nfs/jack/.linuxbrew/Cellar/autoconf/2.69/bin/autom4te line 37.
aclocal: error: echo failed with exit status: 2
autoreconf: aclocal failed with exit status: 2

READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.

These open issues may also help:
fontconfig: Build a bottle for Linuxbrew https://github.com/Linuxbrew/homebrew-core/pull/7514
[jack@geo1 ~]$

**Comment by iMichka** [comment]
Another error:
```
make[1]: Entering directory '/tmp/fontconfig-20180504-7629-1geeitq/fontconfig-2.13.0/fc-cache'
gcc-5 -DHAVE_CONFIG_H -I. -I..  -I.. -I../src -Wall -Wpointer-arith -Wstrict-prototypes 	-Wmissing-prototypes -Wmissing-declarations 	-Wnested-externs -fno-strict-aliasing   -g -O2 -pthread -c -o fc-cache.o fc-cache.c
/bin/bash ../libtool  --tag=CC   --mode=link gcc-5  -g -O2 -pthread   -o fc-cache fc-cache.o ../src/libfontconfig.la 
libtool: link: gcc-5 -g -O2 -pthread -o .libs/fc-cache fc-cache.o  ../src/.libs/libfontconfig.so -L/home/linuxbrew/.linuxbrew/opt/freetype/lib -L/home/linuxbrew/.linuxbrew/Cellar/expat/2.2.5/lib -lfreetype -lexpat -pthread -Wl,-rpath -Wl,/home/linuxbrew/.linuxbrew/Cellar/fontconfig/2.13.0/lib
../src/.libs/libfontconfig.so: undefined reference to `uuid_unparse'
../src/.libs/libfontconfig.so: undefined reference to `uuid_copy'
../src/.libs/libfontconfig.so: undefined reference to `uuid_generate_random'
../src/.libs/libfontconfig.so: undefined reference to `uuid_parse'
```

**Comment by iMichka** [comment]
From my point of view this is fixed and a bottle was built. If you still encounter problems with this, please open a new issue and fill out the issue template. Thanks!

**Pull request closed without merging**
