### PR TITLE
gcc@6: various linux specific improvement

### PR DESCRIPTION
**Pull request by xu-cheng**
- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Backport changes from #6649.

### CODE REVIEW

**Comment by xu-cheng** [comment]
```
==> brew bottle --merge --write --no-commit ./gcc@6-6.4.0_3.x86_64_linux.bottle.json --keep-old
Error: --keep-old was passed but there are changes in:
sha256 => x86_64_linux
Error: Kernel.exit
==> gcc@6
==> FAILED
```

**Comment by iMichka** [comment]
@xu-cheng you need to remove the `ha256 "a67dc68ae96f9dde2811edb68506607bd636bded74db69528c4c37ae8f7cea87" => :x86_64_linux` line; our build bot is not really clever :)

**Comment by xu-cheng** [comment]
Thanks for the tip. I have removed it.

**Comment by iMichka** [comment]
@xu-cheng Thanks for all the fixes!

**Pull request closed without merging**
