### PR TITLE
kibana: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
`make test` failed on CircleCI but passed on TravisCI. May be intermittent.
```
/usr/bin/python tools/test.py --mode=release -J \
		addons doctool inspector known_issues message pseudo-tty parallel sequential


=== release test-net-can-reset-timeout ===
Path: parallel/test-net-can-reset-timeout
timeout
timeout
server side end
client side end
Mismatched <anonymous> function calls. Expected 1, actual 2.
    at Server.<anonymous> (/tmp/kibana--node-20170706-40159-gcm44j/node-v6.10.2/test/parallel/test-net-can-reset-timeout.js:10:31)
    at Server.<anonymous> (/tmp/kibana--node-20170706-40159-gcm44j/node-v6.10.2/test/common.js:441:15)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at TCP.onconnection (net.js:1468:8)
Command: out/Release/node /tmp/kibana--node-20170706-40159-gcm44j/node-v6.10.2/test/parallel/test-net-can-reset-timeout.js

=== release test-tls-fast-writing ===
Path: parallel/test-tls-fast-writing
not ok - timed out
Command: out/Release/node /tmp/kibana--node-20170706-40159-gcm44j/node-v6.10.2/test/parallel/test-tls-fast-writing.js

[02:58|% 100|+ 1318|-   2]: Done
make: *** [test] Error 1
```
https://circleci.com/gh/Linuxbrew/homebrew-core/6528

**Comment by sjackman** [comment]
TravisCI passed again. CircleCI gave a different error this time. Perhaps `make test` should be deparallelized.
```
/usr/bin/python tools/test.py --mode=release -J \
		addons doctool inspector known_issues message pseudo-tty parallel sequential


=== release test-async-wrap-check-providers ===
Path: parallel/test-async-wrap-check-providers
fs.js:1445
    throw error;
    ^

Error: watch /tmp/kibana--node-20170706-40130-fxu6ch/node-v6.10.2/test/parallel/test-async-wrap-check-providers.js ENOSPC
    at exports._errnoException (util.js:1018:11)
    at FSWatcher.start (fs.js:1443:19)
    at Object.fs.watch (fs.js:1470:11)
    at Object.<anonymous> (/tmp/kibana--node-20170706-40130-fxu6ch/node-v6.10.2/test/parallel/test-async-wrap-check-providers.js:54:6)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
Command: out/Release/node /tmp/kibana--node-20170706-40130-fxu6ch/node-v6.10.2/test/parallel/test-async-wrap-check-providers.js
```
https://circleci.com/gh/Linuxbrew/homebrew-core/6532

**Comment by iMichka** [comment]
@sjackman with #3491, `kibana` was updated. Could you rebase and try again?

**Comment by sjackman** [comment]
@iMichka Feel free to close this PR and `linuxbrew build-bottle-pr kibana` if you'd like to adopt it.

**Pull request closed without merging**
