### PR TITLE
rust: fix for linuxbrew: couldn't find required command: ar

### PR DESCRIPTION
**Pull request by timotheecour**
- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

attempt at fixing https://github.com/Linuxbrew/homebrew-core/issues/1733

### CODE REVIEW

**Comment by timotheecour** [comment]
this helps a bit but now `brew install rust` fails with:

```
cat /home/timothee/.cache/Homebrew/Logs/rust/06.make
2017-02-07 23:40:17 -0800

make

brew/Cellar/rust/1.15.0/bin/rustc -V
rustc 1.15.0
/tmp/rust-20170207-28902-1jwvcsf/rustc-1.15.0-src/cargobootstrap/bin/cargo --version
/tmp/rust-20170207-28902-1jwvcsf/rustc-1.15.0-src/cargobootstrap/bin/cargo: 1: /tmp/rust-20170207-28902-1jwvcsf/rustc-1.15.0-src/cargobootstrap/bin/cargo: 8: not found
/tmp/rust-20170207-28902-1jwvcsf/rustc-1.15.0-src/cargobootstrap/bin/cargo: 2: /tmp/rust-20170207-28902-1jwvcsf/rustc-1.15.0-src/cargobootstrap/bin/cargo: H__PAGEZERO__TEX__text__TEXT1__stubs__TEXT@K: not found
/tmp/rust-20170207-28902-1jwvcsf/rustc-1.15.0-src/cargobootstrap/bin/cargo: 2: /tmp/rust-20170207-28902-1jwvcsf/rustc-1.15.0-src/cargobootstrap/bin/cargo: @__stub_helper__TEXTEK4: not found
/tmp/rust-20170207-28902-1jwvcsf/rustc-1.15.0-src/cargobootstrap/bin/cargo: 1: /tmp/rust-20170207-28902-1jwvcsf/rustc-1.15.0-src/cargobootstrap/bin/cargo: ,8__DATA: not found
/tmp/rust-20170207-28902-1jwvcsf/rustc-1.15.0-src/cargobootstrap/bin/cargo: 3: /tmp/rust-20170207-28902-1jwvcsf/rustc-1.15.0-src/cargobootstrap/bin/cargo: =X__unwind_info__TEXTZP}Z__eh_frame__TEXT8: not found
/tmp/rust-20170207-28902-1jwvcsf/rustc-1.15.0-src/cargobootstrap/bin/cargo: 1: /tmp/rust-20170207-28902-1jwvcsf/rustc-1.15.0-src/cargobootstrap/bin/cargo: Syntax error: end of file unexpected (expecting ")")
Makefile:109: recipe for target 'cargo-x86_64-unknown-linux-gnu' failed
make: *** [cargo-x86_64-unknown-linux-gnu] Error 2

HOMEBREW_VERSION: 1.1.8-1-gfb44951
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: fb449510d05511c6ac2c58c7e30d6c27bcd75d81
Last commit: 31 hours ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 820c40e0a9736c398389e7e1ff4a782ead5565c1
Core tap last commit: 13 hours ago
HOMEBREW_PREFIX: brew
HOMEBREW_REPOSITORY: brew
HOMEBREW_CELLAR: brew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: 32-core 64-bit haswell
Homebrew Ruby: 2.3.1 => /usr/bin/ruby2.3
Clang: N/A
Git: 2.7.4 => /usr/bin/git
Perl: /usr/bin/perl
Python: /home/timothee/m/katrina/brew/bin/python => /home/timothee/m/katrina/brew/Cellar/python/2.7.13/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby2.3
Java: 1.8.0_121
Kernel: Linux 4.4.0-59-generic x86_64 GNU/Linux
OS: Ubuntu 16.04.1 LTS
Codename: xenial
OS glibc: 2.23
OS gcc: 5.4.0
Linuxbrew glibc: N/A
Linuxbrew gcc: N/A
Linuxbrew xorg: N/A

CC: /usr/bin/gcc-5
CXX: /usr/bin/g++-5
OBJC: /usr/bin/gcc-5
OBJCXX: /usr/bin/g++-5
CFLAGS: -Os -w -pipe -march=native
CXXFLAGS: -Os -w -pipe -march=native
CPPFLAGS: -isystembrew/include
LDFLAGS: -Lbrew/lib -Wl,--dynamic-linker=brew/lib/ld.so -Wl,-rpath,brew/lib
MAKEFLAGS: -j32
CMAKE_PREFIX_PATH: brew
PKG_CONFIG_LIBDIR: brew/lib/pkgconfig
PATH: /tmp/rust-20170207-28902-1jwvcsf/rustc-1.15.0-src/cargobootstrap/bin:brew/bin:/home/timothee/perl5/bin:/home/timothee/usr/local/bin:/home/timothee/m/katrina//brew//bin:/home/timothee/m/katrina//brew//sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:brew/Library/Homebrew/cask/cmd:brew/Library/Homebrew/shims/scm
CPATH: brew/include
LD_LIBRARY_PATH: brew/Cellar/rust/1.15.0/lib:brew/Cellar/rust/1.15.0
LD_RUN_PATH: brew/lib
LIBRARY_PATH: brew/lib
```

**Comment by sjackman** [comment]
What does `file /tmp/rust-20170207-28902-1jwvcsf/rustc-1.15.0-src/cargobootstrap/bin/cargo` report?

**Comment by timotheecour** [comment]
```
file /tmp/rust-20170210-24874-19s5u3x/rustc-1.15.1-src/cargobootstrap/bin/cargo
/tmp/rust-20170210-24874-19s5u3x/rustc-1.15.1-src/cargobootstrap/bin/cargo: Mach-O 64-bit x86_64 executable
```

indeed, that's suspicious

**Comment by ilovezfs** [comment]
resource "cargobootstrap" do
    url "https://s3.amazonaws.com/rust-lang-ci/cargo-builds/fbeea902d2c9a5be6d99cc35681565d8f7832592/cargo-nightly-x86_64-apple-darwin.tar.gz"
    version "2016-12-15"
    sha256 "ad6c31b41fef1d68e4523eb7d090fe8103848f30eb5ac8cba5128b7c11ed23fc"
  end

You need to use the Linux one.

**Comment by timotheecour** [comment]
@ilovezfs thanks, PTAL it works now, but:

I didn't know where to find the corresponding link for linux:
* not sure how to find the versioned link under https://s3.amazonaws.com/rust-lang-ci/cargo-builds as for mac
* not sure about version, nor which command to get `sha256`

**Comment by ilovezfs** [comment]
I believe the link should be https://s3.amazonaws.com/rust-lang-ci/cargo-builds/fbeea902d2c9a5be6d99cc35681565d8f7832592/cargo-nightly-x86_64-unknown-linux-gnu.tar.gz

The commit should be the one specified in https://github.com/rust-lang/rust/blob/1.15.1/src/stage0.txt for the tag you're building.

**Comment by ilovezfs** [comment]
For getting sha256 I usually do this:
```
openssl dgst -sha256 <(curl -sL https://s3.amazonaws.com/rust-lang-ci/cargo-builds/fbeea902d2c9a5be6d99cc35681565d8f7832592/cargo-nightly-x86_64-unknown-linux-gnu.tar.gz)
```

**Comment by alexcrichton** [comment]
@timotheecour sorry I may be missing context, I'm not sure what's going on here :(

**Comment by ilovezfs** [comment]
@alexcrichton I think the problem was just that bootstrapping cargo on Linux amazingly does not work if you try to use your macOS binary to do the bootstrapping.

**Comment by maxim-belkin** [comment]
>@alexcrichton I think the problem was just that bootstrapping cargo on Linux amazingly does not work if you try to use your macOS binary to do the bootstrapping.

yeah, that's weird!

**Comment by sjackman** [comment]
I use `gsha256sum` to calculate the SHA-256. `brew install coreutils`

**Comment by timotheecour** [comment]
PTAL, all comments addressed. 

@ilovezfs 
> The commit should be the one specified in https://github.com/rust-lang/rust/blob/1.15.1/src/stage0.txt for the tag you're building.

actually i think that should be 1.15.0, but it doesn't change the link.

**Comment by ilovezfs** [comment]
>actually i think that should be 1.15.0

Nope, it's actually 1.15.1 now: https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/rust.rb#L6

(See https://github.com/Homebrew/homebrew-core/pull/9812)

LGTM.

**Comment by timotheecour** [comment]
@ilovezfs ok i rebased and updated the comment to use 1.15.1 instead of 1.15.0; let me know if there's anything else before this can merge

**Comment by rwhogg** [comment]
Merged, but the bottle was not updated. I'll build it myself to avoid Circle timeouts.

Thanks again @timotheecour :smile_cat:

**Comment by rwhogg** [comment]
Tried building the bottle on Docker; it failed. Looks like it also depends on Python:

```
configure: CFG_PYTHON           :=  
configure: error: CFG_PYTHON needed, but unable to find any of: python2.7 python2 python

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
```

**Comment by timotheecour** [comment]
@ilovezfs  on a fresh brew install on same machine as where i had previously attempted a `brew install rust` prior to this PR, it now gives:

```
==> Downloading https://static.rust-lang.org/dist/rustc-1.15.1-src.tar.gz
Already downloaded: /home/timothee/.cache/Homebrew/rust-1.15.1.tar.gz
==> ./configure --prefix=/katrina/home/timothee/m/face1/temp/brew/Cellar/rust/1.15.1 --release-channel=stable
==> make
==> make install
==> Downloading https://s3.amazonaws.com/rust-lang-ci/cargo-builds/fbeea902d2c9a5be6d99cc35681565d8f7832592/cargo-nightly-x86_64-unknown-linux-gnu.tar.gz
Already downloaded: /home/timothee/.cache/Homebrew/rust--cargobootstrap-2016-12-15.tar.gz
Error: SHA256 mismatch
Expected: 0e052514ee88f236153a0d6c6f38f66d691eb4cf1ac09e6040d96e5101d57800
Actual: ad6c31b41fef1d68e4523eb7d090fe8103848f30eb5ac8cba5128b7c11ed23fc
Archive: /home/timothee/.cache/Homebrew/rust--cargobootstrap-2016-12-15.tar.gz
```

so it's using the old file `/home/timothee/.cache/Homebrew/rust--cargobootstrap-2016-12-15.tar.gz` that was pointing to (when untarred) cargo-nightly-x86_64-apple-darwin/ , which has the old sha:

```
gsha256sum /home/timothee/.cache/Homebrew/rust--cargobootstrap-2016-12-15.tar.gz
ad6c31b41fef1d68e4523eb7d090fe8103848f30eb5ac8cba5128b7c11ed23fc 

wget https://s3.amazonaws.com/rust-lang-ci/cargo-builds/fbeea902d2c9a5be6d99cc35681565d8f7832592/cargo-nightly-x86_64-unknown-linux-gnu.tar.gz
gsha256sum cargo-nightly-x86_64-unknown-linux-gnu.tar.gz
0e052514ee88f236153a0d6c6f38f66d691eb4cf1ac09e6040d96e5101d57800  
```

To fix this, I believe all i have to do is update version (say from `2016-12-15` to `2016-12-15b`): would a PR with this be ok?

```
diff --git a/Formula/rust.rb b/Formula/rust.rb
index 5fd6877..80e2be3 100644
--- a/Formula/rust.rb
+++ b/Formula/rust.rb
@@ -64,7 +64,7 @@ class Rust < Formula
       url "https://s3.amazonaws.com/rust-lang-ci/cargo-builds/fbeea902d2c9a5be6d99cc35681565d8f7832592/cargo-nightly-x86_64-unknown-linux-gnu.tar.gz"
       # From:
       # name=cargo-nightly-x86_64-unknown-linux-gnu && tar -zxvf $name.tar.gz $name/version && cat $name/version
-      version "2016-12-15"
+      version "2016-12-15b"
       sha256 "0e052514ee88f236153a0d6c6f38f66d691eb4cf1ac09e6040d96e5101d57800"
     end
   end
```

**Comment by ilovezfs** [comment]
I think you can do brew fetch --force, no?

**Comment by timotheecour** [comment]
just sent out the PR: https://github.com/Linuxbrew/homebrew-core/pull/1780

> I think you can do brew fetch --force, no?

but I wanna make sure `brew install rust` will work for anyone who has previously tried to install it. i don't see any downside to modifying the version.

**Comment by ilovezfs** [comment]
That seems reasonable to me.

**Comment by sjackman** [comment]
Pretty minor thing, but I prefer to keep alpha characters out of version numbers, so perhaps `2016-12-15.2`

**Comment by timotheecour** [comment]
@sjackman well it was merged; feel free to make another PR to change it to `2016-12-15.2` if you want

**Pull request merged**
