### PR TITLE
config: do not unshallow

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by sjackman** [comment]
Here's the challenge…
`brew --version` needs to work because the Homebrew/brew version used to build the bottle is stored in `INSTALL_RECEIPT.json`.
`brew --version` needs all the commits between the most recent stable tag and `master` for it to work.
Getting just those commits is possible but a little tricky.
The simplest fix that doesn't require unshallowing the entire repo is
```sh
brew fetch --shallow-since=2019-01-01 --tags
```

**Comment by sjackman** [comment]
Line 22 also conditionally runs `--unshallow`, so we're fine.
https://github.com/Linuxbrew/homebrew-core/blob/910363c87ef84348982113fdae6a7fc890a63977/.circleci/config.yml#L22

**Comment by maxim-belkin** [comment]
Line 22 is for `homebrew-core`...

**Comment by maxim-belkin** [comment]
One can get the latest tag with this simple one-liner:
```sh
latest_tag=$(git ls-remote -t --refs https://github.com/Homebrew/brew.git | sed -n '$s|.*/||gp')
```

**Comment by iMichka** [comment]
On the other hand `brew --version` did not complain since I made this change.

**Comment by sjackman** [comment]
> On the other hand `brew --version` did not complain since I made this change.

Yep, it seems alright. It must not be shallow then.

```
==> brew config
HOMEBREW_VERSION: 2.0.1-41-gff898bc
```
https://circleci.com/gh/Linuxbrew/homebrew-core/25542

**Pull request merged**
