### PR TITLE
qt5: Depends on glib pulseaudio sqlite systemd x11

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
sqlite2.cpp:34:20: fatal error: sqlite.h: No such file or directory
tds.cpp:34:22: fatal error: sybfront.h: No such file or directory
cups.cpp:34:23: fatal error: cups/cups.h: No such file or directory
libproxy.cpp:36:19: fatal error: proxy.h: No such file or directory
glib.cpp:36:18: fatal error: glib.h: No such file or directory
icu.cpp:34:28: fatal error: unicode/utypes.h: No such file or directory
pulseaudio.cpp:34:30: fatal error: pulse/pulseaudio.h: No such file or directory
libudev.cpp:34:21: fatal error: libudev.h: No such file or directory
tslib.cpp:34:19: fatal error: tslib.h: No such file or directory
xkbcommon.cpp:34:33: fatal error: xkbcommon/xkbcommon.h: No such file or directory
xcb.cpp:38:27: fatal error: xcb/xcb_icccm.h: No such file or directory
```
Ugh. So many missing dependencies.

**Comment by sjackman** [comment]
```ruby
unless OS.mac?
  depends_on :x11
  depends_on "glib"
  depends_on "pulseaudio"
  depends_on "sqlite"
  depends_on "systemd"
end
```

**Comment by rwhogg** [comment]
We might also need/want `homebrew/x11/libxkbcommon`.

**Comment by rwhogg** [comment]
From https://travis-ci.org/Linuxbrew/homebrew-core/builds/147800223#L4357

```
configure: error: *** sys/capability.h not found.  Use --without-caps to disable capabilities support.
```

Pulseaudio failed to build.

**Comment by rwhogg** [comment]
There are a number of problems with PulseAudio, so I'm going to split that out into its own PR.

**Comment by sjackman** [comment]
```
pulseaudio: failed to build --with-x11 https://github.com/Homebrew/homebrew-core/issues/2408
```
Blocked by pulseaudio

**Comment by rwhogg** [comment]
I've made a PR (685) for PulseAudio. It now builds on the Linuxbrew Docker image, but not on my local, since I'm also running into https://github.com/Homebrew/homebrew-core/issues/2408

We'll see how that goes.

**Comment by sjackman** [comment]
@rwhogg Would you like to take over this PR? Feel free to close it and open your own if so.

**Comment by rwhogg** [comment]
Replaced by #686

**Pull request closed without merging**
