### PR TITLE
cabal-install: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Circle:
```
checking version of ghc... 7.8.4
configure: error: GHC version 7.10 or later is required to compile GHC.
```

**Comment by sjackman** [comment]
Blocked by ghc #3738.

**Comment by sjackman** [comment]
I've bottled `ghc`. Can you retry this?

**Comment by iMichka** [comment]
Rebased

**Pull request closed without merging**
