### PR TITLE
open-mpi: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
make[2]: Entering directory '/tmp/open-mpi-20180514-4620-zqafbb/openmpi-3.1.0/opal/tools/wrappers'
  CC       opal_wrapper.o
  GENERATE opal_wrapper.1
  CCLD     opal_wrapper
../../../opal/.libs/libopen-pal.so: undefined reference to `__atomic_compare_exchange_16'
collect2: error: ld returned 1 exit status
```

**Comment by tseemann** [comment]
I am getting the same error, if that makes you feel better :)
```
make[2]: Leaving directory '/tmp/open-mpi-20180526-45573-oiiegy/openmpi-3.1.0/opal/tools/wrappers'
make[1]: *** [Makefile:2375: all-recursive] Error 1
make[1]: Leaving directory '/tmp/open-mpi-20180526-45573-oiiegy/openmpi-3.1.0/opal'
make: *** [Makefile:1897: all-recursive] Error 1
```

**Comment by sjackman** [comment]
Here's a gist of the build logs of a successful build of Open MPI 3.1.0: https://gist.github.com/sjackman/b0e95821db1cce774263a7451ee2626f

**Comment by sjackman** [comment]
It was built with brewed gcc-5, and these dependencies:
```json
"runtime_dependencies":[{"full_name":"zlib","version":"1.2.11"},{"full_name":"gmp","version":"6.1.2"},{"full_name":"mpfr","version":"4.0.1"},{"full_name":"libmpc","version":"1.1.0"},{"full_name":"isl@0.18","version":"0.18"},{"full_name":"gcc","version":"5.5.0"},{"full_name":"openssl","version":"1.0.2o"},{"full_name":"libevent","version":"2.1.8"},{"full_name":"linuxbrew/xorg/libpciaccess","version":"0.13.5"}]
```

**Comment by sjackman** [comment]
Very curious. I'm not able to reproduce this issue myself in the `linuxbrew/linuxbrew` Docker image.

```
❯❯❯ brew install open-mpi
…
🍺  /home/linuxbrew/.linuxbrew/Cellar/libevent/2.1.8: 856 files, 2.6MB
==> Installing open-mpi
==> Downloading https://www.open-mpi.org/software/ompi/v3.1/downloads/openmpi-3.
==> Downloading from https://download.open-mpi.org/release/open-mpi/v3.1/openmpi
######################################################################## 100.0%
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/open-mpi/3.1.0 --disa
==> make all
==> make check
==> make install
🍺  /home/linuxbrew/.linuxbrew/Cellar/open-mpi/3.1.0: 1,034 files, 13MB, built in 23 minutes 4 seconds
```

**Comment by sjackman** [comment]
The only differences between CircleCI and my Docker test should be the CPU, the Linux kernel version, and the number of threads. I wonder if it's a just a race due to the default 32 jobs.

**Comment by tseemann** [comment]
@sjackman how can i force a source build to use a single CPU on my system?
is `MAKEFLAGS` honoured?

**Comment by sjackman** [comment]
I'm trying another build over at PR https://github.com/Linuxbrew/homebrew-core/pull/8112
and then I'll try modifying the number of make jobs.

**Comment by iMichka** [comment]
Superseded by #8112

**Pull request closed without merging**
