### PR TITLE
libxml2: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by sjackman** [comment]
Hmm. `libxml2` seems broken. Multiple failures that all look like:
```
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -lxml2
Missing libraries: libxml2.so.2
undefined reference to `xmlDocSetRootElement@LIBXML2_2.4.30'
error while loading shared libraries: libxml2.so.2: cannot open shared object file: No such file or directory
```
https://circleci.com/gh/Linuxbrew/homebrew-core/8388?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by sjackman** [comment]
The built bottle contains `libxml2.so.2`, so I'm not sure what's gone wrong.
```
libxml2/2.9.4_4/lib/libxml2.so
libxml2/2.9.4_4/lib/libxml2.so.2
libxml2/2.9.4_4/lib/libxml2.so.2.9.4
```
https://8388-56942570-gh.circle-artifacts.com/0/home/linuxbrew/bottles/libxml2-2.9.4_4.x86_64_linux.bottle.tar.gz

**Comment by sjackman** [comment]
This formula used
```ruby
keg_only :provided_by_macos
```
rather than
```ruby
keg_only :provided_by_osx
```
and `:provided_by_macos` was not implemented by `brew`. I've merged PR https://github.com/Linuxbrew/brew/pull/474 to resolve this issue, and tagged and released `brew` 1.2.8.

**Comment by iMichka** [comment]
@maxim-belkin could this be rebased, I think this should work now, and we will need `libxml2` :)

**Comment by iMichka** [comment]
```
==> /home/linuxbrew/.linuxbrew/Cellar/casperjs/1.1.4-1/bin/casperjs /tmp/casperjs-test-20170829-62198-1x0oykn/fetch.js
.
Last 150 lines from /home/linuxbrew/.cache/Homebrew/Logs/casperjs/test.01.casperjs:
2017-08-29 22:05:39 +0000

/home/linuxbrew/.linuxbrew/Cellar/casperjs/1.1.4-1/bin/casperjs
/tmp/casperjs-test-20170829-62198-1x0oykn/fetch.js

phantomjs: error while loading shared libraries: libicui18n.so.58: cannot open shared object file: No such file or directory
Error: casperjs: failed
Failed executing: /home/linuxbrew/.linuxbrew/Cellar/casperjs/1.1.4-1/bin/casperjs /tmp/casperjs-test-20170829-62198-1x0oykn/fetch.js
```

```
==> /home/linuxbrew/.linuxbrew/Cellar/git-flow-avh/1.11.0_1/bin/git-flow init -d
.
Last 150 lines from /home/linuxbrew/.cache/Homebrew/Logs/git-flow-avh/test.02.git-flow:
2017-08-29 22:27:11 +0000

/home/linuxbrew/.linuxbrew/Cellar/git-flow-avh/1.11.0_1/bin/git-flow
init
-d

Using default branch names.
No branches exist yet. Base branches must be created now.
Branch name for production releases: [master] 
Branch name for "next release" development: [develop] 

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <linuxbrew@c96753ac45bb.(none)>) not allowed
```

```
==> /home/linuxbrew/.linuxbrew/Cellar/docbook2x/0.8.8_1/bin/docbook2man /tmp/docbook2x-test-20170829-91815-1hvcrk6/brew.1.xml
.
Last 150 lines from /home/linuxbrew/.cache/Homebrew/Logs/docbook2x/test.01.docbook2man:
2017-08-29 22:27:56 +0000

/home/linuxbrew/.linuxbrew/Cellar/docbook2x/0.8.8_1/bin/docbook2man
/tmp/docbook2x-test-20170829-91815-1hvcrk6/brew.1.xml

Can't locate XML/SAX/ParserFactory.pm in @INC (you may need to install the XML::SAX::ParserFactory module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /home/linuxbrew/.linuxbrew/Cellar/docbook2x/0.8.8_1/bin/db2x_manxml line 2413.
BEGIN failed--compilation aborted at /home/linuxbrew/.linuxbrew/Cellar/docbook2x/0.8.8_1/bin/db2x_manxml line 2413.
Error: docbook2x: failed
```


```
==> brew linkage --test gl2ps
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
No broken dylib links
No unwanted system libraries
==> brew test --verbose gl2ps
Testing gl2ps
==> /home/linuxbrew/.linuxbrew/bin/gcc-5 test.c -o test -L/home/linuxbrew/.linuxbrew/Cellar/gl2ps/1.3.9_2/lib -lgl2ps -lglut -lGL

==> ./test
.
Last 150 lines from /home/linuxbrew/.cache/Homebrew/Logs/gl2ps/test.02.test:
2017-08-29 22:54:19 +0000

./test

freeglut (./test): failed to open display ''
Error: gl2ps: failed
```


And so on ... basically a huge list of reverse deps that fail, but not due to libxml2 itself. Merged.

**Pull request closed without merging**
