### PR TITLE
intltool: Depends on perl 5.8[.1]

### PR DESCRIPTION
**Pull request by dholm**

### CODE REVIEW

**Comment by dholm** [comment]
https://gist.github.com/7586802511c9d705a07d953b8cd85cc5

```
BuildError: Failed executing: ./configure --prefix=/home/eholmda/.linuxbrew/Cellar/intltool/0.51.0 --disable-silent-rules
1. raise                                                                                                   
2. ignore           
3. backtrace
4. irb
5. shell
Choose an action: 5
When you exit this shell, you will return to the menu.
$ which perl
/usr/bin/perl
$ which perldoc
/usr/bin/perldoc
$ perldoc -l XML::Parser
/home/eholmda/.local/lib/perl5/x86_64-linux-thread-multi/XML/Parser.pm
```

**Comment by sjackman** [comment]
This issue suffers from the same bug as #2655. Lots of formula have a `:build` dep on `intltool` which depends on `:perl`. Because of that bug, lots of formula (anything that depends on `"intltool" => :build`) will have an unnecessary dependency on `perl`. So unfortunately I won't merge it until we find a resolution for that issue.

**Comment by sjackman** [comment]
As a workaround, I suggest installing the host package for `XML::Parser` or installing the brewed perl.
```sh
sudo apt-get install -y libxml-parser-perl
```
or
```sh
brew install perl cpanm
cpanm XML::Parser
```

**Comment by dholm** [comment]
@sjackman I don't have root access so I'll just apply my workarounds locally. Do you want me to close the pull request?

**Comment by sjackman** [comment]
Leave it open for now, incase someone else picks it up. I'll be enabling the auto-stale bot for this repo soon, which will close stale issues after a week of inactivity.

**Pull request closed without merging**
