### PR TITLE
quilt: bad sed version

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by rwhogg** [comment]
Ok, what gives? https://travis-ci.org/Linuxbrew/homebrew-core/builds/160498172#L1415-L1422

```
checking for sed... /home/linuxbrew/.linuxbrew/bin/gsed
configure: WARNING: /home/linuxbrew/.linuxbrew/bin/gsed does not exist
checking whether /home/linuxbrew/.linuxbrew/bin/gsed understands (foo|bar)... no

configure: error: 

Sorry, you have a version of sed which doesn't understand constructs
of the form (foo|bar).  quilt needs it.  If you have access to
a version of sed which does understand such constructs, you can supply
its path with the '--with-sed=' option.
```

**Comment by sjackman** [comment]
Weird. Does Circle work?

**Comment by rwhogg** [comment]
> Weird. Does Circle work?

No, fails the exact same way :confounded:

**Comment by sjackman** [comment]
`(foo|bar)` is extended regex and requires `sed -r,--regexp-extended`. I wonder if their `configure` script is including that flag? It would be quite broken if not.

**Comment by rwhogg** [comment]
Works now!

**Comment by sjackman** [comment]
We should create a `gsed` symlink in`gnu-sed` for compatibility with Homebrew.

**Comment by rwhogg** [comment]
> We should create a gsed symlink ingnu-sed for compatibility with Homebrew.

The `gnu-sed` formula is kind of weird. At least on Linux, the `--with-default-names` and `--without-default-names` don't appear to change what gets installed into `bin`. By contrast, `coreutils` does install working versions of `gls` and such.

**Comment by sjackman** [comment]
`--with-default-names` and `--without-default-names` are ignored on Linuxbrew. It's always treated as though `--with-default-names` is specified.

**Pull request closed without merging**
