### PR TITLE
perl-modules: new formula for Linuxbrew

### PR DESCRIPTION
**Pull request by DoomHammer**
This is the first hackish approach to dealing with `perl` [modules problem](https://github.com/Linuxbrew/brew/issues/6). Ideally it should be incorporated into `perl` formula, but let us talk about it first.

### CODE REVIEW

**Comment by sjackman** [comment]
Cool. Thanks, Piotr. Could you take my gist of Mac OS formula and remove the blacklist elements and hardcode the result in the formula? Does this formula conflict with `cpanm`, and should it instead `depends_on "cpanm"`?

**Comment by DoomHammer** [comment]
Never would have thought it has its own formula. It would be better to depend on it, but if we want to make it a part of `perl` formula as suggested such dependency would be circular.

**Comment by sjackman** [comment]
I'm thinking that a separate formula is better, but we'll see. The `:perl` requirement could install `perl-modules` on Linux.

**Comment by DoomHammer** [comment]
Good idea! I will apply your suggestions.

**Comment by iMichka** [comment]
IMHO most of the perl dependencies are vendored by upstream. Often only "xml::parser" is missing, but we have a solution for that, see: #4499

I would be in favour of closing this pull request. I am worried by the maintenance burden to keep all these perl modules up to date.

**Pull request closed without merging**
