### PR TITLE
glibmm: Test fails because of missing -lintl

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by rwhogg** [comment]
Both this one and #290 failed because of a missing `libintl`. This is supposedly part of `gettext`, but it's not installed by it on my machine.

**Comment by sjackman** [comment]
> Both this one and #290 failed because of a missing libintl. This is supposedly part of gettext, but it's not installed by it on my machine.

The `gettext.h` included with `glibc` on Linux is a headers-only library and does not require any library. If you remove `-lintl`, which is only needed on Mac, it should work.

**Comment by sjackman** [comment]
The comment above probably wasn't entirely accurate. The `libintl` functions are I believe implemented by `libc`.

**Comment by rwhogg** [comment]
Fair point, no worries though. I had already seen somewhere on GNU's website that `libintl` doesn't need `-lintl` on Linux, it was just at 2:00 in the morning so I didn't get a chance to test it myself.

**Pull request closed without merging**
