### PR TITLE
netcdf: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by sjackman** [comment]
Do these `libnetcdf.settings` files exist anywhere on macOS or are they specific to Linux?
https://travis-ci.org/Linuxbrew/homebrew-core/builds/261600659#L2387

**Comment by sjackman** [comment]
```
Unwanted system libraries:
  libcurl.so.4
```
Depends on `curl`.

**Comment by sjackman** [comment]
`brew test radx` fails. `radx` needs to be rebuilt for `hdf5`.
https://travis-ci.org/Linuxbrew/homebrew-core/builds/261600659#L8075

**Comment by iMichka** [comment]
> Do these libnetcdf.settings files exist anywhere on macOS or are they specific to Linux?
They exist also on mac. It is a known problem. Upstream decided to ignore that error. This will also only be flagged as an error for new formulae from now on, so this should be green/ignored next time we build netcdf.

**Comment by iMichka** [comment]
radx is broken since forever: https://github.com/Homebrew/homebrew-science/pull/5646

**Comment by iMichka** [comment]
> Depends on curl.

Added; I force pushed the change, so this will rebuild again. See you in 2 hours :)

**Comment by iMichka** [comment]
Merged. Don't worry about the errors in `vtk`: it is being migrated from science to core so we will have time to tackle them later. And `statismo` fails to build too, but has a PR open for that in science.

**Pull request closed without merging**
