### PR TITLE
arx: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by sjackman** [comment]
I believe the `bin` directories of direct dependencies (not recursive) are added to `PATH`.
```ruby
depends_on "sphinx-doc" => :build unless OS.mac?
```

**Comment by maxim-belkin** [comment]
Circle
```
System/Posix/ARX/TMPXTools.hs:14:1: error:
    Failed to load interface for ‘Blaze.ByteString.Builder’
    Perhaps you meant
      Data.ByteString.Builder (from bytestring-0.10.8.1)
    Use -v to see a list of the files searched for.

System/Posix/ARX/TMPXTools.hs:15:1: error:
    Failed to load interface for ‘Data.FileEmbed’
    Use -v to see a list of the files searched for.
```

**Comment by solidsnack** [comment]
You might have to do `cabal install --only-dependencies` first.

**Comment by maxim-belkin** [comment]
we do it [here](https://github.com/Linuxbrew/homebrew-core/pull/2526/files#diff-0d37bfaa5d6c2453d3b93dee3f179b43R26)

**Comment by maxim-belkin** [comment]
https://travis-ci.org/Linuxbrew/homebrew-core/builds/228732337#L1539

**Comment by solidsnack** [comment]
Well, I just built this the other day and it worked... I built it on Mac but those dependencies are pure Haskell. Try building master?

**Pull request closed without merging**
