### PR TITLE
libepoxy: depends on mesa for Linuxbrew

### PR DESCRIPTION
**Pull request by DoomHammer**
- [X] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by rwhogg** [comment]
Looks like everything passed except the test:

```
/home/linuxbrew/.linuxbrew/bin/gcc-5
test.c
-lepoxy
-framework
OpenGL
-o
test
gcc-5: error: OpenGL: No such file or directory
gcc-5: error: unrecognized command line option '-framework'
Error: libepoxy: failed
Failed executing: /home/linuxbrew/.linuxbrew/bin/gcc-5 test.c -lepoxy -framework OpenGL -o test
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1802:in `block in system'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1740:in `open'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1740:in `system'
/home/linuxbrew/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/libepoxy.rb:66:in `block in <class:Libepoxy>'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1640:in `block (2 levels) in run_test'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:870:in `with_logging'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1639:in `block in run_test'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1633:in `run_test'
/home/linuxbrew/.linuxbrew/Library/Homebrew/test.rb:33:in `block in <main>'
/home/travis/.rvm/rubies/ruby-2.0.0-p648-clang/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/home/linuxbrew/.linuxbrew/Library/Homebrew/test.rb:32:in `<main>'
```

BTW, thanks a bunch @DoomHammer. I'm really excited to see us making more progress on the GTK+ front.

**Comment by DoomHammer** [comment]
Fixed the test in a hackish way. Open for suggestions :)

**Comment by DoomHammer** [comment]
Supersedes #276 @sjackman

**Comment by DoomHammer** [comment]
General idea is to split tests and dependency into separate commits. Waiting for comments on my approach to tests, though.

**Comment by maxim-belkin** [comment]
is there a way to improve
```c
#ifdef something
...
#endif

<single command>

#ifdef something
...
#endif
```

**Comment by DoomHammer** [comment]
@maxim-belkin I wish I knew :)

**Comment by DoomHammer** [comment]
This year? 8O

**Pull request closed without merging**
