### PR TITLE
neko: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
--   No package 'gtk+-2.0' found
CMake Error at /home/linuxbrew/.linuxbrew/Cellar/cmake/3.9.5/share/cmake/Modules/FindPkgConfig.cmake:412 (message):
  A required package was not found
Call Stack (most recent call first):
  /home/linuxbrew/.linuxbrew/Cellar/cmake/3.9.5/share/cmake/Modules/FindPkgConfig.cmake:588 (_pkg_check_modules_internal)
  CMakeLists.txt:703 (pkg_check_modules)
```

**Comment by iMichka** [comment]
https://github.com/HaxeFoundation/neko/blob/77d1ec9cc00bb90de2b5c66364641d954defab5f/libs/ui/ui.c#L46-L54

Let's add gtk2 as it is a dependency on Linux.

**Comment by iMichka** [comment]
> No package 'sqlite3' found

**Comment by TiZ-EX1** [comment]
I tried to tackle this myself from another angle, by making gtk+ and httpd optional dependencies, but the current stable version of neko has a cmake define that basically doesn't work. It was fixed in master across multiple commits by changing the single `WITH_NDLLS` define to multiple `WITH_WHATEVER` defines that are all ON by default.

If you opt to make a bottle out of this build, I'm fairly certain that gtk+ and httpd are mainly build dependencies. They are used to create dynamic libraries that neko loads up for certain functionality. I must respectfully and strongly assert that hard dependencies on gtk+ and httpd have no place in a programming language's formula.

**Comment by iMichka** [comment]
I would like to keep the formula as similar as the mac version. If they decided that the GUI and http would be default, it should be same on Linux. On mac the dependencies do not need to be installed as the GUI framework and httpd are already there.

> gtk+ and httpd have no place in a programming language's formula.

Then why are these values on ON by default? That is the choice of upstream, not our choice. We could decide to turn these off, but as said above, I would like to follow the decisions made in the mac formula.

I think we can make a bottle with the current version, we are just hitting the 4Gb memory limit of the build bot (g++-5: internal compiler error: Killed (program cc1plus)). I tried to set a `-j4` flag but that does not seem to be passed down during the compilation, which is utterly annoying.

And if upstream has fixed some important bugs in their cmake files, it would be great if they could tag a new stable release :)

**Comment by TiZ-EX1** [comment]
You're right, it is upstream's choice. I think gtk+ and httpd can be optional deps when it comes to installing the pre-made bottle since the library files they're used to build don't have to be loaded, and mandatory deps when it comes to building it since we can't currently disable making either of those modules.

**Comment by iMichka** [comment]
Needs #4962 first. I'll try to set the dependencies as build dependencies only here later.

**Comment by iMichka** [comment]
```
--   Package 'pango', required by 'gdk-x11-2.0', not found
CMake Error at /home/linuxbrew/.linuxbrew/Cellar/cmake/3.9.6/share/cmake/Modules/FindPkgConfig.cmake:412 (message):
  A required package was not found
Call Stack (most recent call first):
  /home/linuxbrew/.linuxbrew/Cellar/cmake/3.9.6/share/cmake/Modules/FindPkgConfig.cmake:588 (_pkg_check_modules_internal)
  CMakeLists.txt:703 (pkg_check_modules)
```

**Comment by iMichka** [comment]
```
-- Found APACHE: /home/linuxbrew/.linuxbrew/include/httpd  
CMake Error at cmake/FindAPR.cmake:56 (MESSAGE):
  Could not find APR library
Call Stack (most recent call first):
  CMakeLists.txt:882 (find_package)
```

**Comment by iMichka** [comment]
```
--   Found gtk+-2.0, version 2.24.31
-- Found APACHE: /home/linuxbrew/.linuxbrew/include/httpd  
-- Found APR: /home/linuxbrew/.linuxbrew/opt/apr/lib
-- Found MBEDTLS_LIBRARIES: /home/linuxbrew/.linuxbrew/lib/libmbedtls.so;/home/linuxbrew/.linuxbrew/lib/libmbedcrypto.so;/home/linuxbrew/.linuxbrew/lib/libmbedx509.so
-- Found MBEDTLS_STATIC_LIBRARIES: /home/linuxbrew/.linuxbrew/lib/libmbedtls.a;/home/linuxbrew/.linuxbrew/lib/libmbedx509.a;/home/linuxbrew/.linuxbrew/lib/libmbedcrypto.a
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/tmp/neko-20171125-48082-1195s5s/neko-2.1.0-src/APRUTIL_INCLUDE_DIR
   used as include directory in directory /tmp/neko-20171125-48082-1195s5s/neko-2.1.0-src
   used as include directory in directory /tmp/neko-20171125-48082-1195s5s/neko-2.1.0-src

-- Configuring incomplete, errors occurred!
See also "/tmp/neko-20171125-48082-1195s5s/neko-2.1.0-src/CMakeFiles/CMakeOutput.log".
See also "/tmp/neko-20171125-48082-1195s5s/neko-2.1.0-src/CMakeFiles/CMakeError.log".
```

**Comment by iMichka** [comment]
```
[ 55%] Building C object CMakeFiles/mod_neko2.ndll.dir/libs/mod_neko/mod_neko.c.o
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/gcc-5 -DABI_ELF -D_GNU_SOURCE -Dmod_neko2_ndll_EXPORTS -I/tmp/neko-20171203-48005-wz3q3z/neko-2.1.0-src -I/tmp/neko-20171203-48005-wz3q3z/neko-2.1.0-src/vm -I/tmp/neko-20171203-48005-wz3q3z/neko-2.1.0-src/libs/common -I/home/linuxbrew/.linuxbrew/include/httpd -I/home/linuxbrew/.linuxbrew/opt/apr/include -I/home/linuxbrew/.linuxbrew/opt/apr-util/include  -DNDEBUG -fPIC   -fno-omit-frame-pointer -o CMakeFiles/mod_neko2.ndll.dir/libs/mod_neko/mod_neko.c.o   -c /tmp/neko-20171203-48005-wz3q3z/neko-2.1.0-src/libs/mod_neko/mod_neko.c
In file included from /home/linuxbrew/.linuxbrew/include/httpd/ap_config.h:25:0,
                 from /home/linuxbrew/.linuxbrew/include/httpd/httpd.h:44,
                 from /tmp/neko-20171203-48005-wz3q3z/neko-2.1.0-src/libs/mod_neko/mod_neko.h:25,
                 from /tmp/neko-20171203-48005-wz3q3z/neko-2.1.0-src/libs/mod_neko/mod_neko.c:22:
/home/linuxbrew/.linuxbrew/include/httpd/ap_hooks.h:39:17: fatal error: apr.h: No such file or directory
compilation terminated.
```

**Comment by iMichka** [comment]
@TiZ-EX1 There is a bottle for this now. This was a pain to package, but got it to work. There are a lot of dependencies, but all these are the same ones as on mac, so we just follow the same build options as the homebrew repo.

**Comment by TiZ-EX1** [comment]
What a mess building neko. Thanks for going through all of that business. Neko still doesn't install on my system, though; it fails to build httpd. I'll open a separate issue for that.

**Pull request closed without merging**
