### PR TITLE
nload: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
> configure: error: ncurses library or development files not found. ncurses is required for nload.

**Comment by tundratim** [comment]
@iMichka I happen to be working on this right now.  I assume I can just reclone linuxbrew to test?

Summary Of Findings So Far:

- autoconf/automake within brew are hardwired to use system perl even if brew has its own perl installation
- for nload to build (in CentOS) you have to have perl-data-dumper pkg installed

**Comment by iMichka** [comment]
You can just `brew update`.

The perl part of Linuxbrew is not really my speciality, but I think we should vendor the dependency like we do for other formulae. You can have a look at the `vit` formula on how to vendor a perl package. It may be that this package is installed by default on mac, and they did not add it. We can add it for Linux though.

**Comment by tundratim** [comment]
It seems that building nload works only if I have the CentOS Development Tools.  I've spent hours trying to chase this down as to what a bootstrapped environment with its own gcc and perl might need and simply cannot find the magic sauce.

**Pull request closed without merging**
