### PR TITLE
opencv: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by hotkidfamily** [comment]
can compile opencv 3.3.0 with 3 on unbuntu

**Comment by iMichka** [comment]
I need to debug this. The log output is cut by the bot, so I do not see what is broken. I hope I can do that today.

**Comment by iMichka** [comment]
```
In file included from /home/linuxbrew/.linuxbrew/include/lapacke.h:73:0,
                 from /tmp/opencv-20170828-15479-bcnhtr/opencv-3.3.0/build/opencv_lapack.h:2,
                 from /tmp/opencv-20170828-15479-bcnhtr/opencv-3.3.0/modules/core/src/hal_internal.cpp:49:
/tmp/opencv-20170828-15479-bcnhtr/opencv-3.3.0/modules/core/src/hal_internal.cpp: In function 'int lapack_gemm_c(const fptype*, size_t, const fptype*, size_t, fptype, const fptype*, size_t, fptype, fptype*, size_t, int, int, int, int)':
/tmp/opencv-20170828-15479-bcnhtr/opencv-3.3.0/modules/core/src/hal_internal.cpp:437:48: error: expected unqualified-id before '_Complex'
     int ldsrc1 = (int)(src1_step / sizeof(std::complex<fptype>));
                                                ^
/tmp/opencv-20170828-15479-bcnhtr/opencv-3.3.0/modules/core/src/hal_internal.cpp:437:48: error: expected ')' before '_Complex'
/tmp/opencv-20170828-15479-bcnhtr/opencv-3.3.0/modules/core/src/hal_internal.cpp:437:65: error: expected ')' before ';' token
     int ldsrc1 = (int)(src1_step / sizeof(std::complex<fptype>));
                                                                 ^
In file included from /home/linuxbrew/.linuxbrew/include/lapacke.h:73:0,
                 from /tmp/opencv-20170828-15479-bcnhtr/opencv-3.3.0/build/opencv_lapack.h:2,
                 from /tmp/opencv-20170828-15479-bcnhtr/opencv-3.3.0/modules/core/src/hal_internal.cpp:49:
/tmp/opencv-20170828-15479-bcnhtr/opencv-3.3.0/modules/core/src/hal_internal.cpp:438:48: error: expected unqualified-id before '_Complex'
     int ldsrc2 = (int)(src2_step / sizeof(std::complex<fptype>));
                                                ^
```

**Comment by iMichka** [comment]
> can't write PCH file: Cannot allocate memory

I need to reduce the number of cores too ...

**Pull request closed without merging**
