### PR TITLE
gv: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
CircleCI
```
checking for XawInitializeWidgetSet in -lXaw3d... no
configure: error: Unable to find a valid Xaw3d library. Please install it and rerun configure.
```
Looks like `libXaw3d` doesn't yet have a formula for Xorg.
https://ftp.x.org/archive//individual/lib/libXaw3d-1.6.2.tar.bz2

**Comment by maxim-belkin** [comment]
sure. Should be easy enough :)

**Comment by sjackman** [comment]
Thanks, Maxim!

**Comment by sjackman** [comment]
The CircleCI failure is…
```
brew audit gv
Dependency ghostscript should not use option with-x11
```
@iMichka Can you please merge this PR when core is 🌞 ?

**Comment by iMichka** [comment]
I'll do that.

**Comment by sjackman** [comment]
Thanks!

**Comment by sjackman** [comment]
Reminder to merge when you get a chance.

**Comment by iMichka** [comment]
Woups forgot about that one. I'll merge it after the next core merge.

**Comment by iMichka** [comment]
Done :)

**Comment by sjackman** [comment]
Thanks, Michka!

**Pull request closed without merging**
