### PR TITLE
rubberband: Depends on fftw ladspa vamp-plugin-sdk

### PR DESCRIPTION
**Pull request by sjackman**
Fix error: Accelerate/Accelerate.h: No such file or directory

Fixes Linuxbrew/homebrew-core#1037.

### CODE REVIEW

**Comment by sjackman** [comment]
Circle CI
```
g++  -DNDEBUG -ffast-math -mfpmath=sse -msse -msse2 -O3 -ftree-vectorize -I/usr/local/include -DUSE_PTHREADS -DMALLOC_IS_ALIGNED -DHAVE_VDSP -DUSE_SPEEX -DNO_THREAD_CHECKS -DNO_TIMING -Irubberband -I. -Isrc -isystem/home/linuxbrew/.linuxbrew/include  -c -o src/audiocurves/SpectralDifferenceAudioCurve.o src/audiocurves/SpectralDifferenceAudioCurve.cpp
In file included from src/system/Allocators.h:27:0,
                 from src/dsp/MovingMedian.h:29,
                 from src/audiocurves/CompoundAudioCurve.cpp:26:
src/system/VectorOps.h:36:25: fatal error: vecLib/vDSP.h: No such file or directory
```

**Comment by sjackman** [comment]
Travis
```
configure: error: Package requirements (fftw3) were not met:
No package 'fftw3' found
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/167196613#L1379

**Comment by sjackman** [comment]
Travis
```
checking for Vamp... no
configure: error: Package requirements (vamp-sdk) were not met:
No package 'vamp-sdk' found
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/167198513#L1441

**Comment by sjackman** [comment]
Travis
```
In file included from ladspa/RubberBandPitchShifter.cpp:24:0:
ladspa/RubberBandPitchShifter.h:27:20: fatal error: ladspa.h: No such file or directory
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/167201333#L1555

**Comment by sjackman** [comment]
LADSPA is not packaged for Linuxbrew.

**Comment by maxim-belkin** [comment]
Check out PR #1111. If approved, we could then use `depends_on "ladspa-header"` here.
Otherwise (which would be fine by me), we could use a resource.

Currently, I don't know any other formula that uses `ladspa.h`, so the second option might be a more reasonable one.

**Comment by sjackman** [comment]
> Currently, I don't know any other formula that uses ladspa.h, so the second option might be a more reasonable one.

:+1: for a LADSPA resource

**Comment by maxim-belkin** [comment]
@sjackman: do you plan to update this branch with a `ladspa-header` resource?
Just for reference
```ruby
resource "ladspa-header" do
   url "https://gist.githubusercontent.com/maxim-belkin/721fafe404e78e52cf3bf29a259ea9d2/raw/c50f363ec478e23e0bd5b28ea705b5ae52523abb/ladspa.h"
   sha256 "0c73624df742727076c65a9fec4c2806d37bcb7245f62e973d070048b6d333af"
end

include.install resource("ladspa-header")
```

**Comment by sjackman** [comment]
We don't (I think) want to install `ladspa.h` in `include`, just make it available to the formula while it's being built. Feel free to take over this PR if you want, @maxim-belkin

**Comment by sjackman** [comment]
Merging without updating the bottle, because the LADSPA issue is not resolved.

**Pull request merged**
