### PR TITLE
gmp: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
==> brew audit gmp --online
Error: 1 problem in 1 formula
gmp:
  * macOS has been 64-bit only since 10.6 so 32-bit options are deprecated.
==> FAILED
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/190768178#L1161

**Comment by sjackman** [comment]
Circle
`brew test ginac` failed
```
==> brew test --verbose ginac
Testing ginac
==> /home/linuxbrew/.linuxbrew/bin/g++-5 test.cpp -L/home/linuxbrew/.linuxbrew/Cellar/ginac/1.6.7_1/lib -L/home/linuxbrew/.linuxbrew/Cellar/cln/1.3.4/lib -lcln -lginac -o test
.
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/ginac/test.01.g++-5:
2017-01-10 22:26:04 +0000

/home/linuxbrew/.linuxbrew/bin/g++-5
test.cpp
-L/home/linuxbrew/.linuxbrew/Cellar/ginac/1.6.7_1/lib
-L/home/linuxbrew/.linuxbrew/Cellar/cln/1.3.4/lib
-lcln
-lginac
-o
test

/tmp/cc77AwS5.o: In function `main':
test.cpp:(.text+0x4b): undefined reference to `GiNaC::symbol::symbol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
test.cpp:(.text+0xac): undefined reference to `GiNaC::symbol::symbol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/cc77AwS5.o: In function `GiNaC::container<std::vector>::archive(GiNaC::archive_node&) const':
test.cpp:(.text._ZNK5GiNaC9containerISt6vectorE7archiveERNS_12archive_nodeE[_ZNK5GiNaC9containerISt6vectorE7archiveERNS_12archive_nodeE]+0xa9): undefined reference to `GiNaC::archive_node::add_ex(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, GiNaC::ex const&)'
/tmp/cc77AwS5.o: In function `GiNaC::container<std::vector>::read_archive(GiNaC::archive_node const&, GiNaC::container<std::__cxx11::list>&)':
test.cpp:(.text._ZN5GiNaC9containerISt6vectorE12read_archiveERKNS_12archive_nodeERNS0_INSt7__cxx114listEEE[_ZN5GiNaC9containerISt6vectorE12read_archiveERKNS_12archive_nodeERNS0_INSt7__cxx114listEEE]+0x3d): undefined reference to `GiNaC::basic::read_archive(GiNaC::archive_node const&, GiNaC::container<std::__cxx11::list>&)'
test.cpp:(.text._ZN5GiNaC9containerISt6vectorE12read_archiveERKNS_12archive_nodeERNS0_INSt7__cxx114listEEE[_ZN5GiNaC9containerISt6vectorE12read_archiveERKNS_12archive_nodeERNS0_INSt7__cxx114listEEE]+0x8c): undefined reference to `GiNaC::archive_node::find_first(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
test.cpp:(.text._ZN5GiNaC9containerISt6vectorE12read_archiveERKNS_12archive_nodeERNS0_INSt7__cxx114listEEE[_ZN5GiNaC9containerISt6vectorE12read_archiveERKNS_12archive_nodeERNS0_INSt7__cxx114listEEE]+0xdf): undefined reference to `GiNaC::archive_node::find_last(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
test.cpp:(.text._ZN5GiNaC9containerISt6vectorE12read_archiveERKNS_12archive_nodeERNS0_INSt7__cxx114listEEE[_ZN5GiNaC9containerISt6vectorE12read_archiveERKNS_12archive_nodeERNS0_INSt7__cxx114listEEE]+0x19b): undefined reference to `GiNaC::archive_node::find_ex_by_loc(__gnu_cxx::__normal_iterator<GiNaC::archive_node::property const*, std::vector<GiNaC::archive_node::property, std::allocator<GiNaC::archive_node::property> > >, GiNaC::ex&, GiNaC::container<std::__cxx11::list>&) const'
collect2: error: ld returned 1 exit status
Error: ginac: failed
Failed executing: /home/linuxbrew/.linuxbrew/bin/g++-5 test.cpp -L/home/linuxbrew/.linuxbrew/Cellar/ginac/1.6.7_1/lib -L/home/linuxbrew/.linuxbrew/Cellar/cln/1.3.4/lib -lcln -lginac -o test
```

**Comment by maxim-belkin** [comment]
`ENV.cxx11`?

**Comment by maxim-belkin** [comment]
but how can we do that with an old compiler?

**Comment by sjackman** [comment]
Circle timed out
```
==> Installing libepoxy dependency: linuxbrew/xorg/mesa
==> Downloading ftp://ftp.freedesktop.org/pub/mesa/12.0.1/mesa-12.0.1.tar.xz

command umask 022; PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"; brew install patchelf && brew tap homebrew/dupes && brew tap linuxbrew/xorg && brew test-bot --tap=homebrew/core --keep-old --verbose took more than 10 minutes since last output
```

**Comment by sjackman** [comment]
`brew test gmp` fails on Travis.
```
2.00s==> brew test gmp --verbose
Testing gmp
==> /usr/bin/gcc-4.6 test.c -L/home/linuxbrew/.linuxbrew/Cellar/gmp/6.1.1/lib -lgmp -o test
.
==> ./test
.
Last 150 lines from /home/linuxbrew/.cache/Homebrew/Logs/gmp/test.02.test:
2017-01-10 22:55:57 +0000
./test
Inconsistency detected by ld.so: dl-close.c: 759: _dl_close: Assertion `map->l_init_called' failed!
Error: gmp: failed
Failed executing: ./test 
==> FAILED
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/190784196#L1114

**Pull request closed without merging**
