### PR TITLE
fix #852

### LINKED ISSUE #852: ldc: ld: unrecognized option -Wl,--dynamic-linker
```
/usr/bin/ld: unrecognized option '-Wl,--dynamic-linker=/home/timothee/.linuxbrew/lib/ld.so'
/usr/bin/ld: use the --help option for usage information
collect2: error: ld returned 1 exit status
Error: /usr/bin/g++-4.8 failed with status: 1
```

Also relevant:
https://github.com/Linuxbrew/homebrew-core/pull/509
https://github.com/ldc-developers/ldc/issues/1729#issuecomment-243919298
QUOTE from there: In any case, this is a duplicate of #1594, and has already been fixed quite a while ago (including the latest beta for 1.1.0).

### PR DESCRIPTION
**Pull request by timotheecour**
- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by timotheecour** [comment]
```
brew audit --strict ldc
ldc:
  * devel version 1.1.0-beta3 is older than stable version 1.1.0
```
but this'll be fixed eventually in homebrew

**Comment by maxim-belkin** [comment]
@timotheecour, Thanks for the PR. But since this is an upstream issiue for us, you have to submit this fix to Homebrew itself. We regularly merge Homebrew into Linuxbrew but not vice a versa.

**Comment by timotheecour** [comment]
@maxim-belkin happy to do that but I would like to understand: I read the guidelines but that left me thinking i should still do this PR here since the bug is only affecting linux, not osx?

**Comment by rwhogg** [comment]
> @maxim-belkin happy to do that but I would like to understand: I read the guidelines but that left me thinking i should still do this PR here since the bug is only affecting linux, not osx?

Well, since you're contributing a new version of a formula that exists in Homebrew, the PR should go to Homebrew. That you're fixing an issue on Linux as a result of doing so is just a nice side effect.

As a side note, while it's perfectly reasonable to link to a Linuxbrew issue or PR to provide context about why you're making a Homebrew PR, the PR title and description should explain what you're trying to accomplish in Homebrew's terms. For example, in this situation you're contributing a new version of the `ldc` formula, so your PR title should be something like "ldc 1.1.0" or similar.

I know this is confusing, so my apologies.

**Comment by timotheecour** [comment]
@rwhogg this pull was moved to https://github.com/Homebrew/homebrew-core/pull/8617

However, what do I do with https://github.com/Homebrew/homebrew-core/pull/8615 ? @MikeMcQuaid  said "Homebrew only supports macOS, please don't support Linux PRs here." and you're saying to do the change in homebrew not linuxbrew... what do I do ???

**Comment by rwhogg** [comment]
> @rwhogg this pull was moved to Homebrew#8617

Yeah, I know, was just hoping you read this before they saw the PR so you could fix the title.

> However, what do I do with Homebrew#8615 ? @MikeMcQuaid said "Homebrew only supports macOS, please don't support Linux PRs here." and you're saying to do the change in homebrew not linuxbrew... what do I do ???

### In this specific case:

I would avoid arguing with upstream about this; if they don't want the PR, they don't want it. (Were I in Mike's position I would have rejected the PR too.) At most, you could post an apologetic comment.

I'm personally hesitant to take on a patch that isn't strictly necessary for proper/good functionality on Linux and has been rejected upstream. @sjackman, do you agree/disagree?

If we don't take this PR, you obviously have the option of maintaining this option in your own fork.

I apologize for us recommending you send this PR upstream. I don't think any of us realized at the time that shared libraries weren't supported on macOS.

### More generally:

Shaun or Mike might have a better guideline, but here's my process for deciding what goes upstream and what doesn't:

1. For a bug fix or build error, if it affects Homebrew's current version of the formula **when building and running on macOS**, then send it upstream. This can of course be hard to tell in some cases, so if you don't have a Mac to confirm on feel free to ask us maintainers to test it for you. Otherwise, send the PR to Linuxbrew.
2. For a new version, send it upstream. The only exception would be if the new version dropped support for macOS or had really degraded functionality on it, but that's pretty rare.
3. For enabling new functionality (as was the case with Homebrew#8615), the new functionality should a) be supported on macOS and b) actually be reasonably useful there.

**Comment by timotheecour** [comment]
could you update https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md with these instructions?

**Comment by timotheecour** [comment]
@rwhogg  ok moved (once again..) to https://github.com/Linuxbrew/homebrew-core/pull/1528

**Comment by maxim-belkin** [comment]
Let's not confuse two different things:
1. PRs (like this one) that fix issues related to Homebrew AND Linuxbrew. These should be submitted to Homebrew
2. PRs (like #1528) that fix issues related to Linuxbrew only. Such PRs should be submitted here.
Hence, this PR was closed and the other one is legit. No changes to CONTRIBUTING.md is necessary.

**Pull request closed without merging**
