### PR TITLE
Berkeley-DB: with-dbm option

### PR DESCRIPTION
**Pull request by Horta**
Option to enable DBM interface support.

### CODE REVIEW

**Comment by sjackman** [comment]
Do you have access to a Mac? If so, please test on a Mac and send this PR upstream to https://github.com/Homebrew/homebrew-core
What's your motivation for this PR?
Please add a real test, ideally, or remove the dummy test block.

**Comment by sjackman** [comment]
I'm generally disinclined to merge options into Linuxbrew that aren't merged into Homebrew, unless there's a strong use for Linux that does not apply to Mac.

**Comment by Horta** [comment]
I see. I work on a mac but I log into linux machines for cluster stuff.

What I still don't get it is how Linuxbrew and Homebrew are related. Is there an "official" way to make sure we do pull request to both at the same time? Or the procedure is "start with Mac and then go do Linux?"

Thank you @sjackman!

**Comment by Horta** [comment]
To give you a better example. I just forked homebrew-science and added a formula: https://github.com/Horta/homebrew-science

Should I do first Mac homebrew-science and then Linux?

**Comment by sjackman** [comment]
Mac Homebrew is merged into Linuxbrew roughly weekly. If you have a PR merged into Mac Homebrew, it'll appear in Linuxbrew automatically soon after. Homebrew/brew has some support for Linux, and it's improving. Homebrew/homebrew-core does not support Linux.

Homebrew-Science supports Linux, and I have commit rights to Homebrew/Homebrew-Science, so Linux PR may be sent directly to Homebrew/Homebrew-Science. Linuxbrew/Homebrew-Science is a testing ground for building binary bottles and tracking issues.

**Comment by sjackman** [comment]
Please send this PR upstream to Homebrew/homebrew-core. You will need to provide the motivation for your fix and improve the `test do` block.

**Comment by Horta** [comment]
I changed my mind about that option because the only reason I had for that was pam library compilation, which didn't work at the end.

**Pull request closed without merging**
