### PR TITLE
qt: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
pulseaudio: Unsatisfied dependency: XML::Parser
Homebrew does not provide special Perl dependencies; install with:
  `cpan -i XML::Parser`
Error: An unsatisfied requirement failed this build.
==> FAILED
brew.install.9
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/256318796#L1663

**Comment by sjackman** [comment]
```
Note: Dropped compiler flags '-pthread' when detecting library 'glib'.

Note: Disabling Linux Accessibility Bridge: D-Bus is missing.

Note: No wayland-egl support detected. Cross-toolkit compatibility disabled.

ERROR: The OpenGL functionality tests failed!
You might need to modify the include and library search paths by editing QMAKE_INCDIR_OPENGL[_ES2],
QMAKE_LIBDIR_OPENGL[_ES2] and QMAKE_LIBS_OPENGL[_ES2] in the mkspec for your platform.
```
https://circleci.com/api/v1.1/project/github/Linuxbrew/homebrew-core/6908/output/31/0?file=true

**Comment by sjackman** [comment]
```
Your build has exceeded the memory limit of 4G on 1 container.
```
https://6909-56942570-gh.circle-artifacts.com/0/tmp/memory-usage.txt

**Comment by rwhogg** [comment]
Memory limit exhausted again ☹️

**Comment by sjackman** [comment]
| Jobs | Status |
|---|---|
| 32 | ❌ |
| 24 | ❌ |
| 20 | ❌ |
| 12 | |

**Comment by sjackman** [comment]
```
==> make
.............................................................................................
command umask 022; PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"; eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"; brew install patchelf && brew tap homebrew/science && brew tap linuxbrew/xorg && brew test-bot --tap=homebrew/core --keep-old took more than 120 minutes to run
```
Grr 😠

**Comment by sjackman** [comment]
17 jobs uses too much memory, and 16 jobs times out. No luck.

**Comment by rwhogg** [comment]
That's a shame 😦. At least we won't waste time trying in vain to build it on CI any more.

**Pull request closed without merging**
