### PR TITLE
git: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
I'll close this one because the next merge PR updates git to 2.13 and this PR can't be merged before that one

**Comment by sjackman** [comment]
This PR failed to produce any bottles, sadly.
```
gcc-4.8 -o http-walker.o -c -MF ./.depend/http-walker.o.d -MQ http-walker.o -MMD -MP   -I. -DHAVE_ALLOCA_H -DNO_OPENSSL -DNO_GETTEXT -DSHA1_MAX_BLOCK_SIZE="1024L*1024L*1024L"  -DHAVE_PATHS_H -DHAVE_DEV_TTY -DHAVE_CLOCK_GETTIME -DHAVE_CLOCK_MONOTONIC -DHAVE_GETDELIM -DSHA1_HEADER='"block-sha1/sha1.h"'  -DNO_STRLCPY -DSHELL_PATH='"/bin/sh"' -DPAGER_ENV='"LESS=FRX LV=-c"'  http-walker.c
In file included from http.c:2:0:
http.h:6:23: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/231659027#L1230

**Comment by maxim-belkin** [comment]
That's my oversight, I think: https://github.com/Linuxbrew/homebrew-core/pull/2638/files#diff-3e84bae646d908b93e043833873d316dR35 should be recommended for Linux

**Comment by maxim-belkin** [comment]
Just like https://github.com/Linuxbrew/homebrew-core/pull/2638/files#diff-3e84bae646d908b93e043833873d316dR34

**Comment by sjackman** [comment]
I'm glad that we're doing much stricter dependency checking in `test-bot` now.

**Pull request closed without merging**
