### PR TITLE
systemd: Fix for gperf 3.1 for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**
Fix the error: conflicting types for 'lookup_arphrd'

### CODE REVIEW

**Comment by sjackman** [comment]
No luck. The patch doesn't apply cleanly to systemd 221:
https://github.com/systemd/systemd-stable/commit/79a5d862a7abe903f456a75d6d1ca3c11adfa379.patch
https://travis-ci.org/Linuxbrew/homebrew-core/builds/208304411#L2816

Our options are to either backport the patch to 221 or update systemd to 232. See PR https://github.com/Linuxbrew/homebrew-core/pull/1893

**Comment by sjackman** [comment]
There's a good chance that Debian also encountered this issue, and we can borrow their patches.
https://packages.debian.org/sid/systemd

**Comment by KihongHeo** [comment]
Hi, 
How is it going? I am stuck in ```brew install systems```. Is there any other workaround?

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `systemd`.
Another possible workaround for you is `brew install --force-bottle systemd`, but no promises.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by sjackman** [comment]
@KihongHeo Which formula are you trying to install?

**Comment by sjackman** [comment]
I'm trying to update `systemd` to version 233 with PR https://github.com/Linuxbrew/homebrew-core/pull/2795

**Comment by sjackman** [comment]
Superseded by #2795.

**Pull request closed without merging**
