### PR TITLE
imagemagick: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
libtool: link: /bin/grep -E -e ".*" "filters/.libs/analyze.exp" > "filters/.libs/analyze.expT"
libtool: link: mv -f "filters/.libs/analyze.expT" "filters/.libs/analyze.exp"
libtool: link: echo "{ global:" > filters/.libs/analyze.ver
libtool: link:  cat filters/.libs/analyze.exp | sed -e "s/\(.*\)/\1;/" >> filters/.libs/analyze.ver
libtool: link:  echo "local: *; };" >> filters/.libs/analyze.ver
libtool: link:  gcc-5 -shared  -fPIC -DPIC  filters/.libs/filters_analyze_la-analyze.o   -Wl,-rpath -Wl,/tmp/imagemagick-20171217-3718-104kquk/ImageMagick-7.0.7-15/MagickCore/.libs -Wl,-rpath -Wl,/home/linuxbrew/.linuxbrew/Cellar/imagemagick/7.0.7-15/lib MagickCore/.libs/libMagickCore-7.Q16HDRI.so -L/home/linuxbrew/.linuxbrew/opt/freetype/lib -L/home/linuxbrew/.linuxbrew/Cellar/xz/5.2.3/lib -L/home/linuxbrew/.linuxbrew/Cellar/zlib/1.2.11/lib -lfreetype -llzma -lbz2 -lz -lltdl -lm  -g -O2 -mtune=ivybridge -pthread   -pthread -Wl,-soname -Wl,analyze.so -Wl,-version-script -Wl,filters/.libs/analyze.ver -o filters/.libs/analyze.so
libtool: link: ( cd "coders/.libs" && rm -f "jpeg.la" && ln -s "../jpeg.la" "jpeg.la" )
/usr/bin/ld: /home/linuxbrew/.linuxbrew/lib/libtiff.a(tif_aux.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/home/linuxbrew/.linuxbrew/lib/libtiff.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:6662: recipe for target 'coders/tiff.la' failed
```

**Comment by iMichka** [comment]
@sjackman is -fPic being filtered out too?

**Comment by sjackman** [comment]
No, `-fPIC` should not be filtered out. I'm not sure what's going on here.

**Comment by iMichka** [comment]
Actually the libtiff bottle does not contain a .so file, only .a libraries ...

```
==> Verifying libtiff-4.0.9.tar.gz checksum
tar xzf /home/linuxbrew/.cache/Homebrew/libtiff-4.0.9.tar.gz
==> ./configure --disable-dependency-tracking --prefix=/home/linuxbrew/.linuxbrew/Cellar/libtiff/4.0.9 --without-x --with-jpeg-include-dir=/home/linuxbrew/.linuxbrew/opt/jpeg/include --with-jpeg-lib-dir=/home/linuxbrew/.linuxbrew/opt/jpeg/lib --disable-lzma
.
==> make install
.
==> Cleaning
rm /home/linuxbrew/.linuxbrew/Cellar/libtiff/4.0.9/lib/libtiff.la
rm /home/linuxbrew/.linuxbrew/Cellar/libtiff/4.0.9/lib/libtiffxx.la
==> Finishing up
ln -s ../Cellar/libtiff/4.0.9/bin/fax2ps fax2ps
ln -s ../Cellar/libtiff/4.0.9/bin/fax2tiff fax2tiff
ln -s ../Cellar/libtiff/4.0.9/bin/pal2rgb pal2rgb
ln -s ../Cellar/libtiff/4.0.9/bin/ppm2tiff ppm2tiff
ln -s ../Cellar/libtiff/4.0.9/bin/raw2tiff raw2tiff
ln -s ../Cellar/libtiff/4.0.9/bin/tiff2bw tiff2bw
ln -s ../Cellar/libtiff/4.0.9/bin/tiff2pdf tiff2pdf
ln -s ../Cellar/libtiff/4.0.9/bin/tiff2ps tiff2ps
ln -s ../Cellar/libtiff/4.0.9/bin/tiff2rgba tiff2rgba
ln -s ../Cellar/libtiff/4.0.9/bin/tiffcmp tiffcmp
ln -s ../Cellar/libtiff/4.0.9/bin/tiffcp tiffcp
ln -s ../Cellar/libtiff/4.0.9/bin/tiffcrop tiffcrop
ln -s ../Cellar/libtiff/4.0.9/bin/tiffdither tiffdither
ln -s ../Cellar/libtiff/4.0.9/bin/tiffdump tiffdump
ln -s ../Cellar/libtiff/4.0.9/bin/tiffinfo tiffinfo
ln -s ../Cellar/libtiff/4.0.9/bin/tiffmedian tiffmedian
ln -s ../Cellar/libtiff/4.0.9/bin/tiffset tiffset
ln -s ../Cellar/libtiff/4.0.9/bin/tiffsplit tiffsplit
ln -s ../Cellar/libtiff/4.0.9/include/tiff.h tiff.h
ln -s ../Cellar/libtiff/4.0.9/include/tiffconf.h tiffconf.h
ln -s ../Cellar/libtiff/4.0.9/include/tiffio.h tiffio.h
ln -s ../Cellar/libtiff/4.0.9/include/tiffio.hxx tiffio.hxx
ln -s ../Cellar/libtiff/4.0.9/include/tiffvers.h tiffvers.h
ln -s ../../Cellar/libtiff/4.0.9/share/doc/tiff-4.0.9 tiff-4.0.9
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man1/fax2ps.1 fax2ps.1
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man1/fax2tiff.1 fax2tiff.1
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man1/pal2rgb.1 pal2rgb.1
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man1/ppm2tiff.1 ppm2tiff.1
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man1/raw2tiff.1 raw2tiff.1
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man1/tiff2bw.1 tiff2bw.1
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man1/tiff2pdf.1 tiff2pdf.1
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man1/tiff2ps.1 tiff2ps.1
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man1/tiff2rgba.1 tiff2rgba.1
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man1/tiffcmp.1 tiffcmp.1
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man1/tiffcp.1 tiffcp.1
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man1/tiffcrop.1 tiffcrop.1
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man1/tiffdither.1 tiffdither.1
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man1/tiffdump.1 tiffdump.1
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man1/tiffgt.1 tiffgt.1
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man1/tiffinfo.1 tiffinfo.1
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man1/tiffmedian.1 tiffmedian.1
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man1/tiffset.1 tiffset.1
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man1/tiffsplit.1 tiffsplit.1
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFClose.3tiff TIFFClose.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFDataWidth.3tiff TIFFDataWidth.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFError.3tiff TIFFError.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFFieldDataType.3tiff TIFFFieldDataType.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFFieldName.3tiff TIFFFieldName.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFFieldPassCount.3tiff TIFFFieldPassCount.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFFieldReadCount.3tiff TIFFFieldReadCount.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFFieldTag.3tiff TIFFFieldTag.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFFieldWriteCount.3tiff TIFFFieldWriteCount.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFFlush.3tiff TIFFFlush.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFGetField.3tiff TIFFGetField.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFOpen.3tiff TIFFOpen.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFPrintDirectory.3tiff TIFFPrintDirectory.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFRGBAImage.3tiff TIFFRGBAImage.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFReadDirectory.3tiff TIFFReadDirectory.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFReadEncodedStrip.3tiff TIFFReadEncodedStrip.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFReadEncodedTile.3tiff TIFFReadEncodedTile.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFReadRGBAImage.3tiff TIFFReadRGBAImage.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFReadRGBAStrip.3tiff TIFFReadRGBAStrip.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFReadRGBATile.3tiff TIFFReadRGBATile.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFReadRawStrip.3tiff TIFFReadRawStrip.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFReadRawTile.3tiff TIFFReadRawTile.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFReadScanline.3tiff TIFFReadScanline.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFReadTile.3tiff TIFFReadTile.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFSetDirectory.3tiff TIFFSetDirectory.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFSetField.3tiff TIFFSetField.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFWarning.3tiff TIFFWarning.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFWriteDirectory.3tiff TIFFWriteDirectory.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFWriteEncodedStrip.3tiff TIFFWriteEncodedStrip.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFWriteEncodedTile.3tiff TIFFWriteEncodedTile.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFWriteRawStrip.3tiff TIFFWriteRawStrip.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFWriteRawTile.3tiff TIFFWriteRawTile.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFWriteScanline.3tiff TIFFWriteScanline.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFWriteTile.3tiff TIFFWriteTile.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFbuffer.3tiff TIFFbuffer.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFcodec.3tiff TIFFcodec.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFcolor.3tiff TIFFcolor.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFmemory.3tiff TIFFmemory.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFquery.3tiff TIFFquery.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFsize.3tiff TIFFsize.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFstrip.3tiff TIFFstrip.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFswab.3tiff TIFFswab.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/TIFFtile.3tiff TIFFtile.3tiff
ln -s ../../../Cellar/libtiff/4.0.9/share/man/man3/libtiff.3tiff libtiff.3tiff
ln -s ../Cellar/libtiff/4.0.9/lib/libtiff.a libtiff.a
ln -s ../Cellar/libtiff/4.0.9/lib/libtiffxx.a libtiffxx.a
ln -s ../../Cellar/libtiff/4.0.9/lib/pkgconfig/libtiff-4.pc libtiff-4.pc
```

https://circleci.com/api/v1.1/project/github/Linuxbrew/homebrew-core/10934/output/111/0?file=true

Let's try to rebuild it.

**Comment by iMichka** [comment]
We can see what gets produced in this PR: #5247

**Comment by iMichka** [comment]
The new `libtiff` bottles had .so files. Not sure what happened here. @sjackman one of your latest commits to brew probably fixed it (as `libtiff` was bumped a few days ago).

This is fixed :)

**Comment by sjackman** [comment]
Thanks, Michka!

**Pull request closed without merging**
