### PR TITLE
strace 4.15

### PR DESCRIPTION
**Pull request by rwhogg**
- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by maxim-belkin** [comment]
ping :)

**Comment by sjackman** [comment]
It's a Linux-only formula, and we're bumping the version, but building with `--keep-old`, and so it fails. A hack workaround to try is to delete the `x86_64_linux` bottle in the PR in a separate commit, and when merging the PR, remove that commit before pushing. Not ideal, I realize, but we don't have many Linux-only formula in `core`. If no formula in `core` depend on `strace`, perhaps it could be moved to the proposed `Linuxbrew/extra`.

**Comment by rwhogg** [comment]
> If no formula in core depend on strace, perhaps it could be moved to the proposed Linuxbrew/extra.

Nothing in core depends on it.

**Comment by rwhogg** [comment]
I've created https://github.com/rwhogg/homebrew-extra with just `strace` 4.15. If @Linuxbrew/core is okay with it, I'll transfer ownership to the Linuxbrew organization and we can work on migrating both the core `strace` formula and anything else that should go there into the new tap.

**Comment by sjackman** [comment]
Sounds good to me!

**Comment by DoomHammer** [comment]
Coll, now what would be the exact criteria for a formula to not end up in `-core`?

**Comment by sjackman** [comment]
A new formula that works on Mac or Linux should go to Homebrew/core.
A new formula that is Linux-only, and a formula in Linuxbrew/core depends on it, it should go in Linuxbrew/core.
A new formula that is Linux-only, and no formula in Linuxbrew/core depends on it, it should go in Linuxbrew/extra.

**Comment by rwhogg** [comment]
I've transferred the organization, so I'm closing this PR.

`strace` is already available, but I have not yet configured Circle, so IMO we should not add the tap migrations until we have a bottle for 4.15.

**Pull request closed without merging**
