### PR TITLE
aescrypt-packetizer: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Travis:
```
gcc -Wall -Wextra -pedantic -std=c99 -D_FILE_OFFSET_BITS=64 -liconv -o aescrypt_keygen aescrypt_keygen.o password.o
/usr/bin/ld: cannot find -liconv
```

**Comment by sjackman** [comment]
`-liconv` is not needed on Linux, where iconv.h is provided by glibc

**Comment by sjackman** [comment]
Was the error in `brew install` or `brew test`?
If `brew install` fix it in superenv. See https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/shims/linux/super/cc#L153-L154
If `brew test` fix it in the formula.

**Comment by maxim-belkin** [comment]
The formula has an `inreplace` patch that adds `-liconv`. I've commented out this patch in [here](https://github.com/Linuxbrew/homebrew-core/pull/2465/files#diff-4429175bc110a3d96eee7c4e80df4912R38)

**Comment by sjackman** [comment]
That'll fix this one formula. A more general solution is to fix `superenv` to ignore `-liconv`.

**Comment by sjackman** [comment]
It affects only 28 formulae in `Homebrew/core`, but I still think it's worth doing so that Homebrew/core formulae can be used unmodified on Linuxbrew.

**Pull request closed without merging**
