### PR TITLE
gcc 5.4.0 and isl 0.18

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
CI fails because of `brew audit`.
```
==> brew audit gcc
Error: 3 problems in 1 formula
gcc:
  * Don't need 'FileUtils.' before mv.
  * Use the `mv` Ruby method instead of `system "mv `
  * Non-libraries were installed to "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.4.0/lib"
    Installing non-libraries to "lib" is discouraged.
    The offending files are:
      /home/linuxbrew/.linuxbrew/Cellar/gcc/5.4.0/lib/libcilkrts.spec
      /home/linuxbrew/.linuxbrew/Cellar/gcc/5.4.0/lib/libgfortran.spec
      /home/linuxbrew/.linuxbrew/Cellar/gcc/5.4.0/lib/libgomp.spec
      /home/linuxbrew/.linuxbrew/Cellar/gcc/5.4.0/lib/libitm.spec
      /home/linuxbrew/.linuxbrew/Cellar/gcc/5.4.0/lib/libsanitizer.spec
==> FAILED
```

**Comment by sjackman** [comment]
```
  * Don't need 'FileUtils.' before mv.
  * Use the `mv` Ruby method instead of `system "mv `
```
The use of `system "mv"` was for compatibility with Ruby 1.8 which has a buggy `FileUtils.mv` for symlinks. Now that we bundle Ruby 2.0 we can fix it.

```
Installing non-libraries to "lib" is discouraged.
```
Should we add an exception for GCC's `.spec` files for Linuxbrew?
In the short term we can ignore this audit failure.

**Comment by sjackman** [comment]
TravisCI
```
Inconsistency detected by ld.so: dl-close.c: 759: _dl_close: Assertion `map->l_init_called' failed!
Error: isl: failed
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/205036576#L1775

**Comment by sjackman** [comment]
CircleCI
```
/tmp/gcc-20170502-9844-1z01z83/gcc-5.4.0/build/./prev-gcc/xg++ -B/tmp/gcc-20170502-9844-1z01z83/gcc-5.4.0/build/./prev-gcc/ -B/home/linuxbrew/.linuxbrew/Cellar/gcc/5.4.0/x86_64-unknown-linux-gnu/bin/ -nostdinc++ -B/tmp/gcc-20170502-9844-1z01z83/gcc-5.4.0/build/prev-x86_64-unknown-linux-gnu/libstdc++-v3/src/.libs -B/tmp/gcc-20170502-9844-1z01z83/gcc-5.4.0/build/prev-x86_64-unknown-linux-gnu/libstdc++-v3/libsupc++/.libs  -I/tmp/gcc-20170502-9844-1z01z83/gcc-5.4.0/build/prev-x86_64-unknown-linux-gnu/libstdc++-v3/include/x86_64-unknown-linux-gnu  -I/tmp/gcc-20170502-9844-1z01z83/gcc-5.4.0/build/prev-x86_64-unknown-linux-gnu/libstdc++-v3/include  -I/tmp/gcc-20170502-9844-1z01z83/gcc-5.4.0/libstdc++-v3/libsupc++ -L/tmp/gcc-20170502-9844-1z01z83/gcc-5.4.0/build/prev-x86_64-unknown-linux-gnu/libstdc++-v3/src/.libs -L/tmp/gcc-20170502-9844-1z01z83/gcc-5.4.0/build/prev-x86_64-unknown-linux-gnu/libstdc++-v3/libsupc++/.libs -c   -g -O2 -gtoggle -DIN_GCC    -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -I. -I. -I../../gcc -I../../gcc/. -I../../gcc/../include -I../../gcc/../libcpp/include -I/home/linuxbrew/.linuxbrew/opt/gmp/include -I/home/linuxbrew/.linuxbrew/opt/mpfr/include -I/home/linuxbrew/.linuxbrew/opt/libmpc/include  -I../../gcc/../libdecnumber -I../../gcc/../libdecnumber/bid -I../libdecnumber -I../../gcc/../libbacktrace -I/home/linuxbrew/.linuxbrew/opt/isl/include  -o lto-compress.o -MT lto-compress.o -MMD -MP -MF ./.deps/lto-compress.TPo ../../gcc/lto-compress.c
../../gcc/lto-compress.c:28:18: fatal error: zlib.h: No such file or directory
compilation terminated.
```
https://circleci.com/api/v1.1/project/github/Linuxbrew/homebrew-core/5523/output/30/0?file=true

**Comment by sjackman** [comment]
```
==> make bootstrap
.............................................................................................
==> make install
.
Error: No such file or directory - /home/linuxbrew/.linuxbrew/Cellar/gcc/5.4.0/lib64/libssp.so.0
==> FAILED
```
https://circleci.com/gh/Linuxbrew/homebrew-core/5524

**Comment by maxim-belkin** [comment]
This is what I got in docker container:
```
==> Summary
/home/linuxbrew/.linuxbrew/Cellar/ctags/5.8_1: 8 files, 384.4KB
==> Installing abi-compliance-checker dependency: gcc
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-5.4.0/gcc-5.4.0.tar.bz2
Already downloaded: /home/linuxbrew/.cache/Homebrew/gcc-5.4.0.tar.bz2
==> ../configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/gcc/5.4.0  --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-5 --with-gmp=/home/linuxbrew/.linuxbrew/opt/gmp --with-mpfr=/home/linuxbrew/.linuxbrew/opt/mpfr --with-mpc=/home/linuxbrew/.linuxbrew/opt/libmpc --with-isl=/home/linuxbrew/.linuxbrew/opt/isl  --enable-stage1-checking --enable-checking=release --enable-lto --with-build-config=bootstrap-debug --disable-werror --with-pkgversion=Homebrew gcc 5.4.0 --with-bugurl=https://github.com/Homebrew/homebrew/issues --with-boot-ldflags=-static-libstdc++ -static-libgcc  --disable-nls --disable-multilib
==> make bootstrap
==> make install
Error: No such file or directory - /home/linuxbrew/.linuxbrew/Cellar/gcc/5.4.0/lib64/libstdc++.so.6
==> FAILED
```

**Comment by sjackman** [comment]
Was that error with `env :super` or with `env :std`?

**Comment by maxim-belkin** [comment]
I assume `:super`

**Comment by sjackman** [comment]
Okay. I'm trying `env :std` now.

**Comment by sjackman** [comment]
I get the same error with `env :std` as I did with superenv.
```
==> make install
.
Error: No such file or directory - /home/linuxbrew/.linuxbrew/Cellar/gcc/5.4.0/lib64/libssp.so.0
==> FAILED
```
https://circleci.com/gh/Linuxbrew/homebrew-core/5526

**Comment by sjackman** [comment]
Superseded by https://github.com/Linuxbrew/homebrew-core/pull/4390

**Pull request closed without merging**
