### PR TITLE
sphinx-doc: Requires Python on Linux

### PR DESCRIPTION
**Pull request by dholm**

### CODE REVIEW

**Comment by sjackman** [comment]
This issue has a long history. When the user's host system already has Python installed, we want to avoid requiring that the user install the brewed Python to install `sphinx-doc`, because a lot of formulae depend on `sphinx-doc`. That was the decision the last time that we visited this issue. I'm inclined toward adding the dependency now.
@Linuxbrew/core Your thoughts?

My preferred style would be:
```ruby
depends_on :python if !OS.mac? || (OS.mac? && MacOS.version <= :snow_leopard)
```

**Comment by rwhogg** [comment]
Now that brew does not auto-install the `default_formula` if a requirement is satisfied, I agree with adding a `:python` dependency (but not a hard `python` dependency).

I agree with Shaun's comment about the preferred style.

**Comment by maxim-belkin** [comment]
let me just quickly ask:
Should we abuse the fact that MacOS.version on Linux == 0?

**Comment by sjackman** [comment]
No, let's not. I'd prefer and hope to eventually change `MacOS.version` to `nil`.

**Comment by DoomHammer** [comment]
Actually I am from the camp that thinks brewed software is better because it is in our control. So I would suggest using brewed software over system software anytime.

**Comment by dholm** [comment]
@sjackman Fixed the dependency.

**Comment by sjackman** [comment]
I remember the reason that `sphinx-doc` does not depend on `:python`. There's a bug in `brew` that we inherit from upstream.

`cmake` has `depends_on "sphinx-doc" => :build`
`sphinx-doc` has `depends_on :python` (with this PR)
`brew install cmake` pours `cmake` from a bottle, and it's a relocatable bottle (`cellar :any`).
Because it's poured from a bottle, it should need any of its build deps, so it shouldn't need `sphinx-doc` or `python`. The bug is that with this PR `brew install cmake` does not install `sphinx-doc` but bizarrely does install `python`. Because `cmake` is a dependency of so many things, and `python` is not relocatable and so built from source, this was causing a lot of issues.

So, to no fault of this PR, I can't merge it until we fix the above bug or find a workaround for it.

**Comment by maxim-belkin** [comment]
there is difference between `brew deps cmake` and `brew deps --tree cmake`

**Comment by maxim-belkin** [comment]
this differences comes from `!ARGV.one?` that appears in `deps.rb` in the following line:
```ruby
all_deps = deps_for_formulae(ARGV.formulae, !ARGV.one?, &(mode.union? ? :| : :&))
```
Effectively, `!ARGV.one? == true` for `brew deps cmake`

**Comment by sjackman** [comment]
`brew deps --include-build cmake` and `brew deps --tree cmake` agree for me. It looks as though `--tree` implies `--include-build`, which is probably a bug.

**Comment by maxim-belkin** [comment]
`--tree` should not be equal to `--include-build`
absence of arguments to `deps` command currently implies `recursive = !ARGV.one?`, which is questionable

**Pull request closed without merging**
