### PR TITLE
docbook2x: bottle fails to upload to Bintray

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by rwhogg** [comment]
From https://travis-ci.org/Linuxbrew/homebrew-core/builds/155726674#L1241

```
Can't locate XML/SAX/ParserFactory.pm in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at db2x_manxml line 2413.
```

**Comment by rwhogg** [comment]
Marking as blocked by #945

**Comment by rwhogg** [comment]
After everything we've gone through, now it seems the bottle won't upload to Bintray :crying_cat_face:

**Comment by sjackman** [comment]
Rebuilding…

**Comment by sjackman** [comment]
Merged!

**Pull request closed without merging**
