### PR TITLE
wxmac: Depends on mesa and glu for Linuxbrew

### PR DESCRIPTION
**Pull request by rwhogg**
- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

See https://github.com/Linuxbrew/homebrew-core/pull/1558#issuecomment-271926468

### CODE REVIEW

**Comment by rwhogg** [comment]
From Travis (https://travis-ci.org/Linuxbrew/homebrew-core/builds/206652353#L7779-L7782)
```
checking for OpenGL headers... not found
checking for GL/gl.h... yes
checking for GL/glu.h... no
configure: error: OpenGL libraries not available
```

**Comment by rwhogg** [comment]
From Travis (https://travis-ci.org/Linuxbrew/homebrew-core/builds/206675967#L7830):

```
Error: Formula not installed or up-to-date: wxmac
```

Huh?

**Comment by sjackman** [comment]
```
depends_on "linuxbrew/xorg/mesa"
depends_on "linuxbrew/xorg/glu"
```
I think the cross-tap dependencies is making `brew` confused, because `linuxbrew/xorg/glu` depends on `mesa` (without `linuxbrew/xorg/`), and it ends up depending on both `mesa` and `linuxbrew/xorg/mesa` and gets confused. It's a bug in `brew` if I'm right.

**Comment by rwhogg** [comment]
Closing and recommending we merge #1920

**Pull request closed without merging**
