### PR TITLE
libtiff: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
[Travis log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/222504009/log.txt)

**Comment by maxim-belkin** [comment]
```
Package xrender was not found in the pkg-config search path.
Perhaps you should add the directory containing `xrender.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xrender', required by 'cairo', not found
```

**Comment by sjackman** [comment]
CircleCI succeeded except for this odd test failure.
```
==> brew test --verbose epstool
Testing epstool
Error: epstool: failed
epstool cannot be built with any available compilers.
Install Clang or brew install gcc
/home/linuxbrew/.linuxbrew/Library/Homebrew/compilers.rb:127:in `compiler'
/home/linuxbrew/.linuxbrew/Library/Homebrew/compilers.rb:109:in `select_for'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/ENV/shared.rb:171:in `compiler'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/ENV/std.rb:74:in `setup_build_environment'
/home/linuxbrew/.linuxbrew/Library/Homebrew/test.rb:20:in `<main>'
==> FAILED
```
https://circleci.com/gh/Linuxbrew/homebrew-core/5013

TravisCI
```
==> brew install gtk+
…
Package xrender was not found in the pkg-config search path.
Perhaps you should add the directory containing `xrender.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xrender', required by 'cairo', not found
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/222504008#L9777

**Comment by sjackman** [comment]
Merging despite these failures.

**Pull request closed without merging**
