### PR TITLE
coq: Reduce CircleCI memory usage for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
Whatever happens this will need to be rebased on top of #3189

**Comment by iMichka** [comment]
`-j24` worked. Testing with `-j28` to try to speed this a little bit up. If this is green it can be merged.

**Comment by iMichka** [comment]
`-j28` fails. Going back to `-j24`

**Comment by iMichka** [comment]
Weird. `-j24` worked the first time, but fails now. Trying with `-j16`.

**Comment by sjackman** [comment]
As an overly pessimistic estimate, I use four million kilobytes divided by the memory usage of the hungriest process. So for example at https://6617-56942570-gh.circle-artifacts.com/0/tmp/memory-usage.txt
4e6 / 400624 = 10 processes

**Comment by iMichka** [comment]
10 failed too. Let me test something more drastic: 4

**Comment by sjackman** [comment]
The last log suggests that 8 would work:
https://6638-56942570-gh.circle-artifacts.com/0/tmp/memory-usage.txt
```
   PID   RSS %CPU COMMAND
 64234 514332 20.6 bin/coqtop -boot -native-compiler -compile theories/FSets/FMapAVL.v
 65024 437028 17.6 bin/coqtop -boot -native-compiler -compile theories/Numbers/Cyclic/DoubleCyclic/DoubleMul.v
…
```

**Comment by iMichka** [comment]
Okay, `-j4` worked. Trying your 8 out :)

**Pull request closed without merging**
