### PR TITLE
mame: Build a bottle for Linuxbrew: Depends on alsalib

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
CircleCI and TravisCI
```
error: alsa/asoundlib.h: No such file or directory
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/228381484#L2093

**Comment by sjackman** [comment]
Same error even after adding `depends_on "alsa-lib"`

**Comment by maxim-belkin** [comment]
weird because:

```
$ brew list -v alsa-lib | grep "asoundlib.h"
/home/linuxbrew/.linuxbrew/Cellar/alsa-lib/1.1.2/include/alsa/asoundlib.h
/home/linuxbrew/.linuxbrew/Cellar/alsa-lib/1.1.2/include/sys/asoundlib.h
```

**Comment by sjackman** [comment]
Might have to add a `--with-alsa` option to tell it where to find the headers.

**Pull request closed without merging**
