### PR TITLE
util-linux 2.30.1

### PR DESCRIPTION
**Pull request by rwhogg**
Signed-off-by: Bob W. Hogg <rwhogg@linux.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by rwhogg** [comment]
Hmm, does `r` need a revision for `jpeg`? https://travis-ci.org/Linuxbrew/homebrew-core/builds/262519320#L9678

```
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libdl.so.2
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /lib/x86_64-linux-gnu/librt.so.1
  /usr/lib/x86_64-linux-gnu/libjpeg.so.8
No broken dylib links
Unwanted system libraries:
  libjpeg.so.8
```

**Comment by sjackman** [comment]
That's curious.  The `r` formula depends on `jpeg`. On macOS, the current `r` 3.4.1_1 bottle has no linkage to libjpeg. The `r` 3.4.0_1  bottle however does have linkage to `libjpeg`.
```
brew linkage r | grep jpeg
/usr/local/opt/jpeg/lib/libjpeg.8.dylib (jpeg)
```

**Comment by rwhogg** [comment]
The current version is now 2.30.2, and 2.31-rc1 was released just today. After we get this merged, upgrading again is probably a good idea.

**Comment by sjackman** [comment]
Merged.

**Pull request closed without merging**
