### PR TITLE
osc: Build a bottle for Linuxbrew: error: Python.h: No such file or directory

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
    creating build/temp.linux-x86_64-2.7/src
    gcc-4.8 -fno-strict-aliasing -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPYCURL_VERSION="7.43.0" -DHAVE_CURL_OPENSSL=1 -DHAVE_CURL_SSL=1 -I/home/linuxbrew/.linuxbrew/Cellar/curl/7.54.1/include -I/opt/python/2.7.13/include/python2.7 -c src/docstrings.c -o build/temp.linux-x86_64-2.7/src/docstrings.o
    In file included from src/docstrings.c:4:0:
    src/pycurl.h:4:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'gcc-4.8' failed with exit status 1
    Running setup.py install for pycurl: finished with status 'error'
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/258880106#L2310

**Comment by sjackman** [comment]
Even with `depends_on :python` we see `error: Python.h: No such file or directory`.
I wonder whether it's using the correct `python` executable.

**Comment by rwhogg** [comment]
> I wonder whether it's using the correct python executable.

https://github.com/Homebrew/brew/pull/2917 (part of `brew 1.2.5`) might be relevant.

**Comment by sjackman** [comment]
Wasn't the brewed `python` executable renamed to `python2` recently? That may be quite relevant.

**Comment by rwhogg** [comment]
> Wasn't the brewed python executable renamed to python2 recently? That may be quite relevant.

Yep, that was part of the `python` merge from this morning. https://github.com/Homebrew/homebrew-core/pull/14408

I've added `python`'s `libexec/bin` to my PATH on both Linux and macOS for this reason.

**Comment by sjackman** [comment]
Hmm. So I suspect what's going on then is that the host `python` executable is being used on macOS, and it's succeeding in the build. On Linuxbrew the host `python` executable is being used, but it's failing, because the development headers and libraries are not installed. The `:python` requirement should probably add the `python`'s `libexec/bin` to the `PATH`, which is exactly what https://github.com/Homebrew/brew/pull/2917/files#diff-3f67535859dc12a0877cde01e12a40dfR25 does. Mystery solved.

**Comment by sjackman** [comment]
Blocked by `brew` 1.2.5

**Comment by sjackman** [comment]
I've pushed Jon's merge of `brew` 1.2.5.

**Pull request closed without merging**
