### PR TITLE
gcc@7: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
The `brew audit` failure is because `gcc@7` was initially merged with `revision 1`, though it never got a bottle with that revision.
https://github.com/Linuxbrew/homebrew-core/blob/450307d834ccf10b9c02554803f0f54722ead71a/Formula/gcc%407.rb#L1-L4
Upstream Homebrew is at revision 0.

**Comment by sjackman** [comment]
`ENV.refurbish_args` is now enabled by default and removes `-g`. Stripping should hopefully no longer be necessary.

**Comment by sjackman** [comment]
The bottle ballooned from 64 MB to 418 MB!
See https://bintray.com/linuxbrew/bottles/gcc:7#files

Name | Creator | Updated | Size |
-- | -- | -- | -- |
gcc@7-7.3.0.x86_64_linux.bottle.1.tar.gz | linuxbrewtestbot | 22 minutes ago | 418.67 MB |
gcc@7-7.3.0.x86_64_linux.bottle.tar.gz | linuxbrewtestbot | 5 months ago | 64.31 MB |

**Comment by sjackman** [comment]
```
superenv removed:  -g
```
`ENV.refurbish_args` seems to be doing its job.

**Comment by sjackman** [comment]
Superenv is probably used to build the bootstrap compiler. When the bootstrap compiler is used to build the final compiler, it most likely evades superenv. So, the ELF binaries must be stripped by other means.

**Comment by iMichka** [comment]
@sjackman we changed the stripping part of the code in the gcc formula a few weeks ago. You may want to align the code here with that new version.

**Comment by sjackman** [comment]
I went with `make install-strip` in the end, and it worked! I had forgotten about that automake target.

**Pull request closed without merging**
