### PR TITLE
Merge 2017-04-27

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
```
==> brew linkage imagemagick
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libgcc_s.so.1
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6
Homebrew libraries:
  /home/linuxbrew/.linuxbrew/lib/libbz2.so.1.0 (bzip2)
  /home/linuxbrew/.linuxbrew/lib/libfreetype.so.6 (freetype)
  /home/linuxbrew/.linuxbrew/Cellar/imagemagick/7.0.5-5/lib/libMagickCore-7.Q16HDRI.so.2 (imagemagick)
  /home/linuxbrew/.linuxbrew/Cellar/imagemagick/7.0.5-5/lib/libMagickWand-7.Q16HDRI.so.0 (imagemagick)
  /home/linuxbrew/.linuxbrew/lib/libjpeg.so.8 (jpeg)
  /home/linuxbrew/.linuxbrew/lib/libpng16.so.16 (libpng)
  /home/linuxbrew/.linuxbrew/lib/libtiff.so.5 (libtiff)
  /home/linuxbrew/.linuxbrew/lib/libltdl.so.7 (libtool)
  /home/linuxbrew/.linuxbrew/lib/liblzma.so.5 (xz)
  /home/linuxbrew/.linuxbrew/lib/libz.so.1 (zlib)
Possible undeclared dependencies:
  zlib
```

**Comment by maxim-belkin** [comment]
`glbinding` package:
```
==> brew install --build-bottle --verbose glbinding
==> Downloading https://github.com/cginternals/glbinding/archive/v2.1.2.tar.gz
Already downloaded: /home/ubuntu/.cache/Homebrew/glbinding-2.1.2.tar.gz
==> Verifying glbinding-2.1.2.tar.gz checksum
tar xzf /home/ubuntu/.cache/Homebrew/glbinding-2.1.2.tar.gz
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/home/linuxbrew/.linuxbrew/Cellar/glbinding/2.1.2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DGLFW_LIBRARY_RELEASE=
.
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/glbinding/01.cmake:
2017-04-27 13:22:40 +0000

cmake
.
-DCMAKE_C_FLAGS_RELEASE=-DNDEBUG
-DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
-DCMAKE_INSTALL_PREFIX=/home/linuxbrew/.linuxbrew/Cellar/glbinding/2.1.2
-DCMAKE_BUILD_TYPE=Release
-DCMAKE_FIND_FRAMEWORK=LAST
-DCMAKE_VERBOSE_MAKEFILE=ON
-Wno-dev
-DGLFW_LIBRARY_RELEASE=

-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /home/linuxbrew/.linuxbrew/Library/Homebrew/shims/linux/super/gcc-4.8
-- Check for working C compiler: /home/linuxbrew/.linuxbrew/Library/Homebrew/shims/linux/super/gcc-4.8 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/linuxbrew/.linuxbrew/Library/Homebrew/shims/linux/super/g++-4.8
-- Check for working CXX compiler: /home/linuxbrew/.linuxbrew/Library/Homebrew/shims/linux/super/g++-4.8 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find cppcheck (missing:  cppcheck_EXECUTABLE) 
-- Check cppcheck skipped: cppcheck not found
-- Could NOT find clang_tidy (missing:  clang_tidy_EXECUTABLE) 
-- Check clang-tidy skipped: clang-tidy not found
-- Command update
-- Command generate
CMake Error at /home/linuxbrew/.linuxbrew/Cellar/cmake/3.8.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenGL (missing: OPENGL_gl_LIBRARY OPENGL_INCLUDE_DIR)
Call Stack (most recent call first):
  /home/linuxbrew/.linuxbrew/Cellar/cmake/3.8.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /home/linuxbrew/.linuxbrew/Cellar/cmake/3.8.0/share/cmake/Modules/FindOpenGL.cmake:170 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  source/glbinding/CMakeLists.txt:6 (find_package)
```

**Comment by maxim-belkin** [comment]
```
==> Pouring go-1.8.1.x86_64_linux.bottle.tar.gz
tar xzf /home/ubuntu/.cache/Homebrew/go-1.8.1.x86_64_linux.bottle.tar.gz
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/lib --set-interpreter /home/linuxbrew/.linuxbrew/lib/ld.so /home/linuxbrew/.linuxbrew/Cellar/go/1.8.1/libexec/bin/go
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/lib --set-interpreter /home/linuxbrew/.linuxbrew/lib/ld.so /home/linuxbrew/.linuxbrew/Cellar/go/1.8.1/libexec/bin/godoc
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/lib --set-interpreter /home/linuxbrew/.linuxbrew/lib/ld.so /home/linuxbrew/.linuxbrew/Cellar/go/1.8.1/libexec/pkg/tool/linux_amd64/pprof
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/lib --set-interpreter /home/linuxbrew/.linuxbrew/lib/ld.so /home/linuxbrew/.linuxbrew/Cellar/go/1.8.1/libexec/pkg/tool/linux_amd64/trace
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/lib --set-interpreter /home/linuxbrew/.linuxbrew/lib/ld.so /home/linuxbrew/.linuxbrew/Cellar/go/1.8.1/libexec/src/debug/dwarf/testdata/line-clang.elf
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/lib --set-interpreter /home/linuxbrew/.linuxbrew/lib/ld.so /home/linuxbrew/.linuxbrew/Cellar/go/1.8.1/libexec/src/debug/dwarf/testdata/line-gcc.elf
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/lib --set-interpreter /home/linuxbrew/.linuxbrew/lib/ld.so /home/linuxbrew/.linuxbrew/Cellar/go/1.8.1/libexec/src/debug/dwarf/testdata/ranges.elf
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/lib --set-interpreter /home/linuxbrew/.linuxbrew/lib/ld.so /home/linuxbrew/.linuxbrew/Cellar/go/1.8.1/libexec/src/debug/dwarf/testdata/split.elf
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/lib --set-interpreter /home/linuxbrew/.linuxbrew/lib/ld.so /home/linuxbrew/.linuxbrew/Cellar/go/1.8.1/libexec/src/debug/dwarf/testdata/typedef.elf
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/lib --set-interpreter /home/linuxbrew/.linuxbrew/lib/ld.so /home/linuxbrew/.linuxbrew/Cellar/go/1.8.1/libexec/src/debug/elf/testdata/gcc-386-freebsd-exec
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/lib --set-interpreter /home/linuxbrew/.linuxbrew/lib/ld.so /home/linuxbrew/.linuxbrew/Cellar/go/1.8.1/libexec/src/debug/elf/testdata/gcc-amd64-linux-exec
Error: Failure while executing: ["ldd", "/home/linuxbrew/.linuxbrew/Cellar/go/1.8.1/libexec/src/debug/elf/testdata/gcc-386-freebsd-exec"] 
Warning: Bottle installation failed: building from source.
```

**Comment by maxim-belkin** [comment]
```
Only the first 100 operations were output.
==> /home/linuxbrew/.linuxbrew/Cellar/perl/5.24.1/bin/cpan -i XML::Parser
...
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/perl/post_install.01.cpan:

/home/linuxbrew/.linuxbrew/Cellar/perl/5.24.1/bin/cpan
-i
XML::Parser

Loading internal null logger. Install Log::Log4perl for logging messages
Reading '/home/ubuntu/.cpan/Metadata'
  Database was generated on Thu, 27 Apr 2017 12:53:49 GMT
Running install for module 'XML::Parser'
Fetching with HTTP::Tiny:
http://mirrors.vinahost.vn/CPAN/authors/id/T/TO/TODDR/XML-Parser-2.44.tar.gz
HTTP::Tiny failed with an internal error: Could not read from socket: 'Connection reset by peer'


Trying with
    /usr/bin/wget -O "/home/ubuntu/.cpan/sources/authors/id/T/TO/TODDR/XML-Parser-2.44.tar.gz.tmp106185"
to get
    http://mirrors.vinahost.vn/CPAN/authors/id/T/TO/TODDR/XML-Parser-2.44.tar.gz
--2017-04-27 14:24:53--  http://mirrors.vinahost.vn/CPAN/authors/id/T/TO/TODDR/XML-Parser-2.44.tar.gz
Resolving mirrors.vinahost.vn (mirrors.vinahost.vn)... 123.30.129.186
Connecting to mirrors.vinahost.vn (mirrors.vinahost.vn)|123.30.129.186|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.
```

**Comment by sjackman** [comment]
` Error: Failure while executing: ["ldd", "/home/linuxbrew/.linuxbrew/Cellar/go/1.8.1/libexec/src/debug/elf/testdata/gcc-386-freebsd-exec"] `

Uh oh. I introduced that bug in https://github.com/Linuxbrew/brew/pull/334. I'll take a look at it.

**Comment by maxim-belkin** [comment]
thank you!

**Comment by sjackman** [comment]
The `guile` formula has a similar issue, but it's problem is with `patchelf` rather than `ldd`.

**Comment by maxim-belkin** [comment]
Closed in d1c5f078ea9fc2f1aa607b7934e8b92c2b766ed8

**Pull request closed without merging**
