### PR TITLE
git-flow: test fails

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by rwhogg** [comment]
From https://travis-ci.org/Linuxbrew/homebrew-core/builds/132158404#L1648-L1654

```
==> git rev-parse --abbrev-ref HEAD
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Error: git-flow: failed
<0> expected but was
<128>.
```

**Comment by maxim-belkin** [comment]
So, the problem is that in the test environment we don't have git user.email nor user.name.

`brew test -vd git-flow` shows the problem. We have to tweak it somewhere in the Linuxbrew environment. @sjackman ?


```
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
```

**Comment by sjackman** [comment]
In `circle.yml`
```yml
    - git config user.name LinuxbrewTestBot
    - git config user.email testbot@linuxbrew.sh
```
Changing that to `--global` should resolve the issue.

**Comment by maxim-belkin** [comment]
#2367

**Comment by maxim-belkin** [comment]
#2369

**Pull request closed without merging**
