### PR TITLE
python: Bump revision for readline

### PR DESCRIPTION
**Pull request by rwhogg**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

Note to self: Make sure the bottle is actually different!

### CODE REVIEW

**Comment by rwhogg** [comment]
Circle failed because a Python bottle for 2.7.12_1 was already published. That was part of #673, which enabled `select.poll` by default on Linux.

Will bump the revision to redo this.

**Comment by rwhogg** [comment]
Circle's failure was just `--keep-old`, so will merge assuming Travis passes.

**Comment by sjackman** [comment]
The revision bump and rebuild is do to `readline` changing its SONAME, is that correct?

**Comment by rwhogg** [comment]
> The revision bump and rebuild is do to readline changing its SONAME, is that correct?

Yes, it is. My bad, should have put that in the issue title.

**Comment by sjackman** [comment]
No worries. Thanks for the fix.

**Pull request closed without merging**
