### PR TITLE
mariadb: Reduce CircleCI memory usage: Depends on ncurses bzip2

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
28 and 20 failed.

**Comment by sjackman** [comment]
Try 12
4e6 / 355772 = 11.2
https://6696-56942570-gh.circle-artifacts.com/0/tmp/memory-usage.txt

**Comment by iMichka** [comment]
I'm at 8. Should work. I think we should not try to optimise too much. On some formulae I saw just 1 min out of 30 min build time gain for 4 threads more. Not worth my time :) So if 8 work I'll leave it like this.

**Comment by sjackman** [comment]
Agreed!

**Comment by sjackman** [comment]
It's also possible that the need for this optimization could be moot with CircleCI 2.0.

**Comment by iMichka** [comment]
> Unwanted system libraries:
  libbz2.so.1.0

**Comment by sjackman** [comment]
Depends on `ncurses zlib`

**Comment by sjackman** [comment]
So close! Thanks, Mischa!

**Comment by iMichka** [comment]
> ./mariadb-10.2.6.x86_64_linux.bottle.tar.gz
  bottle do
    sha256 "b8d092ccf620ecdcc6e11da8f71931b862c5896921e96832e321764b5a32c1e9" => :x86_64_linux
  end
==> brew bottle --merge --write --no-commit ./mariadb-10.2.6.x86_64_linux.bottle.json --keep-old
Error: --keep-old was passed but there are changes in:
sha256 => x86_64_linux
Error: Kernel.exit
==> mariadb
==> FAILED

I guess that this bug is preventing the bottle upload?

**Comment by iMichka** [comment]
Merged as is, without the bottle. I hope the next PR will upload the bottles: #3242

**Comment by sjackman** [comment]
In this case it's not a bug but intended behaviour, because `mariadb` already has a bottle for `x86_64_linux`. The error message could be more helpful though.

**Pull request closed without merging**
