### PR TITLE
.travis.yml: fast finish and allow failures

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by sjackman** [comment]
Perhaps something like…
```
matrix:
  fast_finish: true
  allow_failures:
    - os: linux
…
script:
   - brew test-bot
```

**Comment by iMichka** [comment]
```
==> Verifying hello-2.10.tar.gz checksum
tar xzf /home/linuxbrew/.cache/Homebrew/hello-2.10.tar.gz
Error: remove this line before pushing
travis_time:end:362b7bb9,start=1504729409000000000,finish=1504729410000000000,duration=1000000000
travis_fold:end:brew.install.7
==> [1m[31mFAILED[0m[0m
travis_fold:start:brew.audit.8
travis_time:start:a8fcef61
[34m==>[0m [1mbrew audit hello --online[0m
==> Installing or updating 'rubocop' gem
Building native extensions.  This could take a while...
Successfully installed rainbow-2.2.2
Successfully installed ast-2.3.0
Successfully installed parser-2.4.0.0
Successfully installed powerpack-0.1.1
Successfully installed ruby-progressbar-1.8.1
Successfully installed unicode-display_width-1.3.0
Successfully installed parallel-1.12.0
Successfully installed rubocop-0.49.1
8 gems installed
==> [1m[32mPASSED[0m[0m
```

Travis does fail; but is green. This is fine. I am wondering why it does not really fast fail ... it is probably because `brew test-bot` is just one command, so it waits until it is done.

Circle does not fail, which is more annoying

**Comment by sjackman** [comment]
Are you expecting CircleCI to fail because there's already a published bottle for this formula and version? Here's the somewhat unexpected reason:
```
    sha256 "f81d7c0a3eee9fd62ebdecf685fbc5284e40d4a61c372d554fd45719e52a43cc" => :x86_64_linux # glibc 2.19
    sha256 "c198bf75ffae00bba9f371e0f22af37c6ebdec66a22276bba047b78db116328b" => :x86_64_linux
```
These two aren't seen as the same by that logic.

**Comment by iMichka** [comment]
No, I am expecting it to fail because I put a `raise` in the formula.

**Comment by iMichka** [comment]
Got it. As I didn't remove the sha256, it only did a brew test and brew linkage. Everything is fine.
Removing the raise line from the hello file, and this is good to go.

**Pull request closed without merging**
