### PR TITLE
Merge 2017-09-05 2ad14a63d4

### PR DESCRIPTION
**Pull request by iMichka**
+ [ ] dmtx-utils
+ [ ] faas-cli
+ [ ] glibmm
+ [ ] gtk+3

### CODE REVIEW

**Comment by sjackman** [comment]
```
curl -L https://linuxbrew.bintray.com/bottles/imagemagick-7.0.7-0.x86_64_linux.bottle.tar.gz
The requested path was not found.
```
Uh oh.

**Comment by sjackman** [comment]
```
==> Bottling faas-cli-0.4.12.x86_64_linux.bottle.tar.gz...
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath @@HOMEBREW_PREFIX@@/lib --set-interpreter /lib64/ld-linux-x86-64.so.2 /home/linuxbrew/.linuxbrew/Cellar/faas-cli/0.4.12/bin/faas-cli
cannot find section .tbss
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/lib /home/linuxbrew/.linuxbrew/Cellar/faas-cli/0.4.12/bin/faas-cli
cannot find section .tbss
Error: Failure while executing: /home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/lib /home/linuxbrew/.linuxbrew/Cellar/faas-cli/0.4.12/bin/faas-cli
==> FAILED
```

**Comment by sjackman** [comment]
```
/home/linuxbrew/.linuxbrew/Cellar/libxml++3/3.0.1/lib/libxml++-3.0.so: undefined reference to `Glib::ustring::rbegin()'
/home/linuxbrew/.linuxbrew/Cellar/libxml++3/3.0.1/lib/libxml++-3.0.so: undefined reference to `Glib::get_unichar_from_std_iterator(__gnu_cxx::__normal_iterator<char const*, std::string>)'
/home/linuxbrew/.linuxbrew/Cellar/libxml++3/3.0.1/lib/libxml++-3.0.so: undefined reference to `Glib::ustring::ustring(std::string const&)'
collect2: error: ld returned 1 exit status
Error: libxml++3: failed
Failed executing: /usr/bin/g++-5 -std=c++11 test.cpp -o test -I/home/linuxbrew/.linuxbrew/opt/gettext/include -I/home/linuxbrew/.linuxbrew/opt/glib/include/glib-2.0 -I/home/linuxbrew/.linuxbrew/opt/glib/lib/glib-2.0/include -I/home/linuxbrew/.linuxbrew/opt/glibmm/include/glibmm-2.4 -I/home/linuxbrew/.linuxbrew/opt/glibmm/lib/glibmm-2.4/include -I/home/linuxbrew/.linuxbrew/Cellar/libxml++3/3.0.1/include/libxml++-3.0 -I/home/linuxbrew/.linuxbrew/opt/libsigc++/include/sigc++-2.0 -I/home/linuxbrew/.linuxbrew/opt/libsigc++/lib/sigc++-2.0/include -I/home/linuxbrew/.linuxbrew/Cellar/libxml++3/3.0.1/lib/libxml++-3.0/include -L/home/linuxbrew/.linuxbrew/opt/gettext/lib -L/home/linuxbrew/.linuxbrew/opt/glib/lib -L/home/linuxbrew/.linuxbrew/opt/glibmm/lib -L/home/linuxbrew/.linuxbrew/opt/libsigc++/lib -L/home/linuxbrew/.linuxbrew/Cellar/libxml++3/3.0.1/lib -lglib-2.0 -lglibmm-2.4 -lgobject-2.0 -lsigc-2.0 -lxml++-3.0 -lxml2
```

**Comment by sjackman** [comment]
```
/home/linuxbrew/.linuxbrew/Cellar/libxml++/2.40.1/lib/libxml++-2.6.so: undefined reference to `Glib::ustring::rbegin()'
/home/linuxbrew/.linuxbrew/Cellar/libxml++/2.40.1/lib/libxml++-2.6.so: undefined reference to `Glib::get_unichar_from_std_iterator(__gnu_cxx::__normal_iterator<char const*, std::string>)'
collect2: error: ld returned 1 exit status
Error: libxml++: failed
Failed executing: /usr/bin/g++-5 -std=c++11 test.cpp -o test -I/home/linuxbrew/.linuxbrew/opt/gettext/include -I/home/linuxbrew/.linuxbrew/opt/glib/include/glib-2.0 -I/home/linuxbrew/.linuxbrew/opt/glib/lib/glib-2.0/include -I/home/linuxbrew/.linuxbrew/opt/glibmm/include/glibmm-2.4 -I/home/linuxbrew/.linuxbrew/opt/glibmm/lib/glibmm-2.4/include -I/home/linuxbrew/.linuxbrew/Cellar/libxml++/2.40.1/include/libxml++-2.6 -I/home/linuxbrew/.linuxbrew/opt/libsigc++/include/sigc++-2.0 -I/home/linuxbrew/.linuxbrew/opt/libsigc++/lib/sigc++-2.0/include -I/home/linuxbrew/.linuxbrew/Cellar/libxml++/2.40.1/lib/libxml++-2.6/include -L/home/linuxbrew/.linuxbrew/opt/gettext/lib -L/home/linuxbrew/.linuxbrew/opt/glib/lib -L/home/linuxbrew/.linuxbrew/opt/glibmm/lib -L/home/linuxbrew/.linuxbrew/opt/libsigc++/lib -L/home/linuxbrew/.linuxbrew/Cellar/libxml++/2.40.1/lib -lglib-2.0 -lglibmm-2.4 -lgobject-2.0 -lsigc-2.0 -lxml++-2.6 -lxml2
```

**Comment by sjackman** [comment]
```
❯❯❯ grep "'failed'" ~/Downloads/brew-test-bot.xml
    <testcase name='fetch autoconf automake bzip2 freetype gpatch imagemagick jpeg libdmtx libpng libtiff libtool m4 pkg-config xz zlib' status='failed' time='7.025541819'>
    <testcase name='bottle faas-cli --keep-old' status='failed' time='0.476361923'>
    <testcase name='test libxml++3' status='failed' time='1.541621969'>
    <testcase name='test libxml++' status='failed' time='1.590181092'>
    <testcase name='test gtkmm' status='failed' time='4.149444967'>
    <testcase name='test gcsfuse' status='failed' time='0.878948555'>
    <testcase name='bottle faas-cli --keep-old' status='failed' time='0.320475487'>
    <testcase name='install gource' status='failed' time='558.034218122'>
    <testcase name='audit gource --online' status='failed' time='16.636259427'>
```

**Comment by iMichka** [comment]
Could not pull:
```
Verifying bottle: gcsfuse-0.23.0.x86_64_linux.bottle.tar.gz
Error: Failed to find published gcsfuse bottle at https://linuxbrew.bintray.com/bottles/gcsfuse-0.23.0.x86_64_linux.bottle.tar.gz (302 )!
```

Opening related pull requests separately.

**Pull request closed without merging**
