### PR TITLE
expat: Depends on xmlto

### PR DESCRIPTION
**Pull request by dholm**

### CODE REVIEW

**Comment by sjackman** [comment]
Either remove the host package `docbook-utils` which provides `docbook2man` or install the host package `docbook2x` which provides `docbook2x-man`.

**Comment by sjackman** [comment]
Is there a particular reason that you're attempting to compile `expat` from source rather than use the relocatable precompiled binary bottle?

**Comment by sjackman** [comment]
Closing without merging.

**Comment by dholm** [comment]
@sjackman The glibc in Linuxbrew is incompatible with our host systems (both bottle and built from source) so I have to compile every package from source.

**Comment by sjackman** [comment]
The only dependency that the `glibc` bottle is supposed to have is on the Linux kernel version ≥ 2.6.32. What's your Linux kernel version?

**Comment by dholm** [comment]
@sjackman It is a heavily patched 2.6.18 if I remember correctly.  The people who administrate these machines are not happy with it but sadly we are stuck with it.

**Comment by sjackman** [comment]
Linux 2.6.18 was released in 2006, so is twelve years old now. We have limited time, and so at some point have to draw a line of which distributions we do and don't support. CentOS 6 was released in 2011, and that's roughly where we're drawing the line, so for Ubuntu that's Ubuntu 12.04 (Precise Pangolin) and later.

`xmlto` pulls in a lot of dependencies:
```
brew deps --include-build xmlto | wc -l
16
```
which is why I hesitate to pull it in unnecessarily.

Does installing the deps without modifying the formula work for you?
```
brew install xmlto expat
HOMEBREW_ENV_NO_FILTERING=1 brew install xmlto expat
```

**Comment by dholm** [comment]
@sjackman It doesn't sadly, it requires manually overriding the environment variable too.  But I'm ok with you not merging this change as I understand your concerns.

I noticed that several of the systems have a newer kernel now, only one of them is still stuck on `2.6.32-<insert-vendor-patchlevel-here>` so perhaps we can start using the Linuxbrew glibc soon.

**Comment by sjackman** [comment]
Thanks for your understanding. You could consider keeping your install-from-source installation of Linuxbrew for this one older system, and start a new installation of Linuxbrew for your newer systems. While you're at it, you could ask your system administrator to create `linuxbrew` role account for you so that you can install in `/home/linuxbrew/.linuxbrew`, after which you'll be able to use all the precompiled binary bottles, not just the relocatable ones. You'll feel like you're driving a race car after compiling everything from source. 🏎️

**Comment by dholm** [comment]
@sjackman Annoyingly (in this case) our home directories are shared across all hosts. :)

**Comment by sjackman** [comment]
Yes, that's desirable in fact. You'll be able to share the same installation of Linuxbrew across all your hosts. Even across users if that interests you.

**Pull request closed without merging**
