### PR TITLE
llvm@5: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
Fails to build locally with:
```
make[2]: Leaving directory '/tmp/llvm@5-20180622-8094-14ak7uo'
[ 97%] Built target llvm-cxxdump
make -f tools/llvm-dwp/CMakeFiles/llvm-dwp.dir/build.make tools/llvm-dwp/CMakeFiles/llvm-dwp.dir/depend
make[2]: Entering directory '/tmp/llvm@5-20180622-8094-14ak7uo'
cd /tmp/llvm@5-20180622-8094-14ak7uo && /home/linuxbrew/.linuxbrew/Cellar/cmake/3.11.4/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/llvm@5-20180622-8094-mchukb/llvm-5.0.2.src /tmp/llvm@5-20180622-8094-mchukb/llvm-5.0.2.src/tools/llvm-dwp /tmp/llvm@5-20180622-8094-14ak7uo /tmp/llvm@5-20180622-8094-14ak7uo/tools/llvm-dwp /tmp/llvm@5-20180622-8094-14ak7uo/tools/llvm-dwp/CMakeFiles/llvm-dwp.dir/DependInfo.cmake --color=
Scanning dependencies of target llvm-dwp
make[2]: Leaving directory '/tmp/llvm@5-20180622-8094-14ak7uo'
make -f tools/llvm-dwp/CMakeFiles/llvm-dwp.dir/build.make tools/llvm-dwp/CMakeFiles/llvm-dwp.dir/build
make[2]: Entering directory '/tmp/llvm@5-20180622-8094-14ak7uo'
[ 97%] Building CXX object tools/llvm-dwp/CMakeFiles/llvm-dwp.dir/llvm-dwp.cpp.o
cd /tmp/llvm@5-20180622-8094-14ak7uo/tools/llvm-dwp && /home/linuxbrew/.linuxbrew/opt/gcc/bin/g++  -DLLVM_BUILD_GLOBAL_ISEL -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/llvm@5-20180622-8094-14ak7uo/tools/llvm-dwp -I/tmp/llvm@5-20180622-8094-mchukb/llvm-5.0.2.src/tools/llvm-dwp -I/tmp/llvm@5-20180622-8094-14ak7uo/include -I/tmp/llvm@5-20180622-8094-mchukb/llvm-5.0.2.src/include  -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -ffunction-sections -fdata-sections -DNDEBUG     -o CMakeFiles/llvm-dwp.dir/llvm-dwp.cpp.o -c /tmp/llvm@5-20180622-8094-mchukb/llvm-5.0.2.src/tools/llvm-dwp/llvm-dwp.cpp
collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.
tools/clang/tools/libclang/CMakeFiles/libclang.dir/build.make:567: recipe for target 'lib/libclang.so.5.0' failed
make[2]: *** [lib/libclang.so.5.0] Error 1
make[2]: *** Deleting file 'lib/libclang.so.5.0'
make[2]: Leaving directory '/tmp/llvm@5-20180622-8094-14ak7uo'
CMakeFiles/Makefile2:28095: recipe for target 'tools/clang/tools/libclang/CMakeFiles/libclang.dir/all' failed
make[1]: *** [tools/clang/tools/libclang/CMakeFiles/libclang.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 97%] Building CXX object tools/llvm-dwp/CMakeFiles/llvm-dwp.dir/DWPError.cpp.o
```

**Comment by maxim-belkin** [comment]
```
collect2: fatal error: ld terminated with signal 9 [Killed
```
out of memory?

**Comment by iMichka** [comment]
Yeah, but I have 16 Gb. But I reformatted my hard drive lately, and maybe my swap is a little bit small. I was able to build llvm@5 back then with the same computer ...

**Comment by iMichka** [comment]
For the small story: I have 16Gb of Ram, and I had 2Gb of Swap. Increasing the swap to 20Gb fixed it :)

**Comment by maxim-belkin** [comment]
Interesting... I wonder if brew should monitor swap file / memory / etc usage during the installation in a docker container locally so that we could adjust parallelism for CI

**Comment by iMichka** [comment]
I know that you can play with swap setting when starting a docker container. I never tried though. But I bet these values are set by circle.ci to prevent somebody to hijack too much disk space (and slow down disk access for others maybe?)

**Pull request closed without merging**
