### PR TITLE
libarchive: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
rebased

**Comment by maxim-belkin** [comment]
Errored while trying to tar up the bottle :)
```
tar cf /home/ubuntu/homebrew-core/libarchive-3.3.1.x86_64_linux.bottle.tar libarchive/3.3.1
tar: /lib/x86_64-linux-gnu/liblzma.so.5: version `XZ_5.2' not found (required by tar)
```

**Comment by sjackman** [comment]
Ugh. That's weird. At first I thought it was because it was using `gnu-tar`, but that doesn't seem to be the case. I can't think of why the host `tar` would have unsatisfied shared libraries. This will require some interactive debugging on CircleCI.

Unrelated, but I noticed that `gnu-tar` has no dependencies on `zlib` and `bzip2`, and it probably should, possibly `xz` too.

**Comment by sjackman** [comment]
```ruby
    ln_s bin/"bsdtar", bin/"tar"
    ln_s bin/"bsdcpio", bin/"cpio"
    ln_s man1/"bsdtar.1", man1/"tar.1"
    ln_s man1/"bsdcpio.1", man1/"cpio.1"
```
Well that partly explains it. Let's not create these symlinks on Linux.

```
Possible undeclared dependencies:
  zlib
```
Let's add a dependency on `zlib`.
I suspect it may also need a dependency on `bzip2`.

**Comment by rwhogg** [comment]
Related to https://github.com/Linuxbrew/homebrew-core/issues/1447

**Comment by sjackman** [comment]
Ah, I figured it out.
```sh
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath @@HOMEBREW_PREFIX@@/lib:@@HOMEBREW_PREFIX@@/opt/xz/lib 
tar cf /home/linuxbrew/.linuxbrew/libarchive-3.3.1.x86_64_linux.bottle.1.tar libarchive/3.3.1
tar: /usr/lib/x86_64-linux-gnu/liblzma.so.5: version `XZ_5.2' not found (required by tar)
```
`brew bottle` breaks the `RPATH` of `tar`, and then tries to use it to create the bottle.
Not creating the symlinks will fix this issue.

Please add the `zlib` dependency.

On your own machine, can you try
```sh
brew install --env=std zlib bzip2 libarchive
brew linkage libarchive
```
If it has a dependency `bzip2`, can you add it?

**Comment by maxim-belkin** [comment]
```
Possible undeclared dependencies:
  bzip2
  expat
  zlib
```

**Comment by maxim-belkin** [comment]
@sjackman I was not sure whom you directed your messages so I committed directly to the branch here

**Comment by sjackman** [comment]
Thanks, Maxim. Looks great to me! :shipit:

**Pull request closed without merging**
