### PR TITLE
gnu-time: Install gtime symlink and fix test [Linux]

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
@iMichka Can you please merge this PR after the next core merge, assuming that CI succeeds?

**Comment by iMichka** [comment]
Can this be safeguarded by `if OS.mac?` conditions? Just to prevent confusion when merging and stuff has changed.

**Comment by sjackman** [comment]
Done.

**Comment by sjackman** [comment]
Thanks, Michka!

**Pull request closed without merging**
