### PR TITLE
glib: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by sjackman** [comment]
On both CircleCI and TravisCI.
```
==> brew install libcroco
intltool: Unsatisfied dependency: XML::Parser
Homebrew does not provide special Perl dependencies; install with:
  `cpan -i XML::Parser`
Error: An unsatisfied requirement failed this build.
==> FAILED
```
That's weird. I thought this issue was resolved on CircleCI (though not yet on TravisCI). Grumble.

**Comment by maxim-belkin** [comment]
That's because bottled `intltool` uses system's perl and installation of `XML::Parser` fails sporadically due to some missing packages.

**Comment by rwhogg** [comment]
I tried installing `perl` on the Travis Docker image; the postinstall step fails with

```
Use of uninitialized value $_[0] in substitution (s///) at /home/linuxbrew/.linuxbrew/Cellar/perl/5.24.0_3/lib/perl5/5.24.0/File/Basename.pm line 341.
fileparse(): need a valid pathname at /home/linuxbrew/.linuxbrew/Cellar/perl/5.24.0_3/lib/perl5/5.24.0/CPAN/FirstTime.pm line 1403.
Warning: The post-install step did not complete successfully
```

But a subsequent `cpan -i XML::Parser` succeeds, which suggests that it's the "FirstTime.pm" module which is blowing up.

> And what's the relationship to intltool; does installing the brewed intltool break XML::Parser?

I'm not sure what the sporadic failures on Circle due to missing packages are unfortunately :frowning: However, I can shed some light on the relationship between XML::Parser and `intltool`.

The relationship to `intltool` is from https://github.com/Linuxbrew/homebrew-core/pull/1440 and https://github.com/Linuxbrew/homebrew-core/pull/1443. Since #1440, `intltool` depends on XML::Parser from brew's standpoint (although it's always unofficially required it).

#1443 is the really interesting one. By default `intltool` hardcodes whichever Perl it was built with into itself, so on 1443 Maxim forced it to instead use /usr/bin/env to find Perl. This actually brings the formula more in line with brew itself, since `LanguageModuleRequirement` also uses /usr/bin/env to find Perl.

**Comment by rwhogg** [comment]
Ah, this may be interesting. Comes up in the first part of the postinstall on Travis:

```
Warning: You do not have write permission for Perl library directories.
```

**Comment by rwhogg** [comment]
Also note that https://github.com/Homebrew/homebrew-core/issues/10133 was filed upstream. I'm now quite looking forward to upstream's response to that; hopefully it will introduce new information that we can take advantage of.

**Comment by sjackman** [comment]
Upstream's solution is to unset all user environment variables in https://github.com/Homebrew/brew/pull/1753
It's merged! Is that in Linuxbrew yet, I wonder?

**Comment by sjackman** [comment]
`glib` is a pretty core dependency of much stuff, so I'm merging this PR for the bottle despite the CI failures related to `XML::Parser`.

**Pull request closed without merging**
