### PR TITLE
freeglut: Build a bottle for Linuxbrew: error: GL/glu.h: No such file or directory

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
CircleCI
```
-- Detecting CXX compile features - done
CMake Error at /home/linuxbrew/.linuxbrew/Cellar/cmake/3.7.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find OpenGL (missing: OPENGL_gl_LIBRARY)
Call Stack (most recent call first):
  /home/linuxbrew/.linuxbrew/Cellar/cmake/3.7.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /home/linuxbrew/.linuxbrew/Cellar/cmake/3.7.2/share/cmake/Modules/FindOpenGL.cmake:162 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:234 (FIND_PACKAGE)
```
https://circleci.com/gh/Linuxbrew/homebrew-core/3673

**Comment by sjackman** [comment]
CircleCI
```
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
configure.ac:234: error: Could not locate the pkg-config autoconf macros.
  These are usually located in /usr/share/aclocal/pkg.m4. If your macros
  are in a different location, try setting the environment variable
  ACLOCAL="aclocal -I/other/macro/dir" before running autoreconf.
configure.ac:234: the top level
autom4te: /home/linuxbrew/.linuxbrew/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1

==> Formula
Tap: linuxbrew/xorg
Path: /home/linuxbrew/.linuxbrew/Library/Taps/linuxbrew/homebrew-xorg/mesa.rb
```
https://circleci.com/api/v1.1/project/github/Linuxbrew/homebrew-core/3676/output/30/0?file=true

**Comment by sjackman** [comment]
CircleCI
```
[  9%] Building C object CMakeFiles/freeglut_static.dir/src/fg_ext.c.o
In file included from /tmp/freeglut-20170212-54272-13f6p1c/freeglut-3.0.0/include/GL/freeglut.h:17:0,
                 from /tmp/freeglut-20170212-54272-13f6p1c/freeglut-3.0.0/src/fg_callbacks.c:28:
/tmp/freeglut-20170212-54272-13f6p1c/freeglut-3.0.0/include/GL/freeglut_std.h:144:23: fatal error: GL/glu.h: No such file or directory
compilation terminated.
make[2]: *** [CMakeFiles/freeglut_static.dir/src/fg_callbacks.c.o] Error 1
```
https://circleci.com/api/v1.1/project/github/Linuxbrew/homebrew-core/3684/output/30/0?file=true

**Comment by sjackman** [comment]
Depends on GLU, which does not yet have a formula. See https://mesa.freedesktop.org/archive/glu/

**Comment by maxim-belkin** [comment]
`depends_on "linuxbrew/xorg/glu" if OS.linux?`

**Comment by maxim-belkin** [comment]
```ruby
unless OS.mac?
  depends_on "linuxbrew/xorg/mesa"
  depends_on "linuxbrew/xorg/glu"
end
```

**Comment by sjackman** [comment]
Thanks, Maxim!

**Pull request closed without merging**
