### PR TITLE
libass: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
configure: error: Either DirectWrite (on Windows), CoreText (on OSX), or Fontconfig (Linux, other) is required. If you really want to compile without a system font provider, add --disable-require-system-font-provider
```

**Comment by iMichka** [comment]
Needs a rebase because of #5095

**Comment by nick-dimitrov** [comment]
Hello, this is from today:

nick1710@nick17:~$ brew install libass
==> Downloading https://github.com/libass/libass/releases/download/0.14.0/libass
Already downloaded: /home/nick1710/.cache/Homebrew/libass-0.14.0.tar.xz
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/libass/0.14.0_1 --dis
Last 15 lines from /home/nick1710/.cache/Homebrew/Logs/libass/01.configure:
checking for strdup... yes
checking for strndup... yes
checking for library containing libiconv_open... no
checking for library containing iconv_open... none required
checking for fabs in -lm... yes
checking for nasm... yes
checking if nasm supports vpmovzxwd... yes
checking for pkg-config... /home/linuxbrew/.linuxbrew/opt/pkg-config/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for freetype2 >= 9.10.3... yes
checking for fribidi >= 0.19.0... yes
checking for CORETEXT... no
checking for DIRECTWRITE... no
checking for harfbuzz >= 0.9.5... yes
configure: error: Either DirectWrite (on Windows), CoreText (on OSX), or Fontconfig (Linux, other) is required. If you really want to compile without a system font provider, add --disable-require-system-font-provider

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.

These open issues may also help:
libass: Build a bottle for Linuxbrew https://github.com/Linuxbrew/homebrew-core/pull/4873

**Comment by iMichka** [comment]
Hi. Yes, this is the exact same error. I had no time to work on this. Upstream may need to be contacted, because I have no clue how to fix this.

**Comment by nick-dimitrov** [comment]
I've manually installed an older version, 0.13.7
Here's the log file:
[libass_Release 0.13.7_log_install.txt](https://github.com/Linuxbrew/homebrew-core/files/1629857/libass_Release.0.13.7_log_install.txt)

===============

Then I tried to install libass again via brew:

nick@nick:~/Свалени/libass-0.13.7$ brew install libass
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
flac ✔

Warning: libass 0.14.0_1 is already installed, it's just not linked.
You can use `brew link libass` to link this version.
nick@nick:~/Свалени/libass-0.13.7$ brew link libass
Linking /home/linuxbrew/.linuxbrew/Cellar/libass/0.14.0_1... 7 symlinks created

**Comment by iMichka** [comment]
Fixed

**Pull request closed without merging**
