### PR TITLE
unison 2.48.4

### PR DESCRIPTION
**Pull request by odoublewen**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by odoublewen** [comment]
In addition to version upgrade, please note that the current formula for unison is broken due to change un the tar file URL.  This PR provides a more stable URL.

**Comment by rwhogg** [comment]
Hi @odoublewen. Thanks for the pull request!

`unison` has already been updated upstream; I apologize that this has not been merged yet. You can try installing directly from the upstream URL if you like: `brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/unison.rb`

Normally, we would request that you send new version PR's upstream, but that is unnecessary in this case since they have already updated.

However, I also noticed that you fixed some of the audit failures in this PR. If you can test your PR on a Mac, upstream would be happy to get a PR to fix those. (I'm not sure if they'll want to keep the test or not - they might want something more sophisticated.)

```bash
% brew audit --strict unison
unison:
  * A `test do` test block should be added
  * Description shouldn't include the formula name
  * Use `system "make", "./mkProjectInfo"` instead of `system "make ./mkProjectInfo"` 
  * Use `system "make", "UISTYLE=text"` instead of `system "make UISTYLE=text"` 
Error: 4 problems in 1 formula
```

You might also want to remove the formula name from the description as well.

Once again, thanks a bunch for contributing!

**Comment by sjackman** [comment]
Sorry for the delay in merging Mac Homebrew into Linuxbrew. I'm at a conference this week and will be tackling the merge once I'm back in about a week's time.

**Comment by odoublewen** [comment]
@rwhogg - thanks for the info and feedback.  I wondered how homebrew and linuxbrew try to keep in sync, and this answers it for me.   Note:  I think the audit you ran was not testing my PR -- you likely audited the current repo version.  My original PR fixes all of those things.

**Comment by rwhogg** [comment]
Homebrew has been merged into Linuxbrew, so `unison` 2.48.4 should now be available.

Thanks for being patient while Shaun was busy :smile:

**Pull request closed without merging**
