### PR TITLE
ghc 8.0.1: build ghc 8.0.1 from source using a binary release of ghc 8.0.1

### PR DESCRIPTION
**Pull request by CristianCantoro**
- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
-----

***WARNING: this pull request is not complete yet***

(splitting from #1366 for clarity)

Premise: `ghc`, the Glasgow Haskell Compiler, is written in Haskell so it needs a binary of itself to build from source.

the current stable release of `ghc` is `8.0.1` and in Linuxbrew building from source is currently using a binary release of `ghc v. 7.8.4` ([ghc.rb#L81](https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/ghc.rb#L81)).

Build with a binary release of `ghc 8.0.1` is known to cause the following problem ([ghc.rb#L79-L80](https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/ghc.rb#L79-L80)):
```
# Using 8.0.1 gives the error message:
# strip: Not enough room for program headers, try linking with -N
```
However, I am not able to reproduce the error on [docker-linuxbrew](https://github.com/sjackman/docker-linuxbrew) and besides an error in linking libraries which I am able to resolve with `brew patchelf ghc` (see [#851](https://github.com/Linuxbrew/homebrew-core/issues/851#issuecomment-266402224)), I am able to build it from source. See the full [logs](http://pastebin.com/raw/AK2yGciV).

I am opening this PR, but I consider it incomplete because on one hand I can not reproduce the existing issue and on the other it is not working completely. Help wanted.

### CODE REVIEW

**Comment by CristianCantoro** [comment]
From the CI logs it looks like that the error is present only in Travis-CI ([Travis-CI: builds/184188821#L1602](https://travis-ci.org/Linuxbrew/homebrew-core/builds/184188821#L1602)):
```
strip: /tmp/ghc-20161215-11576-1kfis3k/ghc-8.0.1/binary/lib/ghc-8.0.1/ghc-prim-0.5.0.0/stbGoOex: Not enough room for program headers, try linking with -N
strip:/tmp/ghc-20161215-11576-1kfis3k/ghc-8.0.1/binary/lib/ghc-8.0.1/ghc-prim-0.5.0.0/stbGoOex[.note.gnu.build-id]: Bad value
```

Instead circleci kills the build after 120 minutes ([build 2904](https://circleci.com/gh/Linuxbrew/homebrew-core/2904)):
```
command umask 022; PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"; brew install patchelf curl && brew tap homebrew/dupes && brew tap linuxbrew/xorg && brew test-bot --tap=homebrew/core --keep-old --verbose took more than 120 minutes to run
```

could it be for both cases a problem of resource (in one case memory in the other time) for both CI systems?

**Comment by sjackman** [comment]
It could be that the `strip` program from `binutils` on Travis is too old and buggy. Travis is running Ubuntu 12 and Circle is running Ubuntu 14. It's a theory anyway.

**Comment by CristianCantoro** [comment]
> It could be that the strip program from binutils on Travis is too old and buggy. Travis is running Ubuntu 12 and Circle is running Ubuntu 14. It's a theory anyway.

Would it be possible to change the settings for the CI? If anything raising the time limit on circleci would help, the build takes ~ 122 minutes (_sic et simpliciter_) on my machine (a quad core i5).

**Comment by rwhogg** [comment]
We've been running into timeouts with Circle CI left and right and I don't think it's possible to increase the time limit without moving to a paid plan.

We've been working around it for some very large and important formulae by building them manually on our own machines.

**Comment by staticfloat** [comment]
With regards to the `strip`/`patchelf` errors, I tried this out on a `precise` version of the `linuxbrew` docker files that @sjackman has so graciously provided.  My `sf/precise` branch has a test that runs into many of the same issues here, but allows one to swap in my own `patchelf` binary easily.  My `patchelf` doesn't completely solve the issues yet, but it's giving the same error messages as shown in [this comment](https://github.com/NixOS/patchelf/issues/10#issuecomment-271543898), so if I can solve it for that comment hopefully it will solve them for this PR as well.  Having the build process of `ghc` as a part of your test-develop cycle is cumbersome, so I'll see if I can't narrow things down with the `libxml` binaries given me in the other thread first

**Comment by sjackman** [comment]
Thanks, Elliot!

**Pull request closed without merging**
