### PR TITLE
makefile2graph: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
CircleCI fails with…
```
make test
make -Bnd | ./make2graph | dot
Error: fontconfig: Couldn't find font.
```
https://circleci.com/gh/Linuxbrew/homebrew-core/13312

**Comment by sjackman** [comment]
`apt-get install fonts-dejavu-core` resolves `Error: fontconfig: Couldn't find font.` I don't know that we have a brewed solution for this issue yet. I'm okay with ignoring this `brew test` failure on CircleCI.

**Comment by sjackman** [comment]
I rebased this PR to rebuild the bottle.

**Comment by iMichka** [comment]
So it looks for some fonts on the system when running `make test`. I would just comment `make test` out. I am worried that some other builds may pick up a wrong font path or do fancy stuff, so it is better not to install any fonts.

**Comment by sjackman** [comment]
I've disabled `make test` on CircleCI.

**Comment by iMichka** [comment]
```
==> Downloading https://linuxbrew.bintray.com/bottles/zlib-1.2.11.x86_64_linux.bottle.tar.gz
/usr/bin/curl --show-error --user-agent Linuxbrew/1.5.8-3-g42f6c7a (Linux; x86_64 4.4.0-109-generic) curl/7.47.0 --fail --silent --location --remote-time --continue-at - --output /home/linuxbrew/.cache/Homebrew/zlib-1.2.11.x86_64_linux.bottle.tar.gz.incomplete https://linuxbrew.bintray.com/bottles/zlib-1.2.11.x86_64_linux.bottle.tar.gz
Downloaded to: /home/linuxbrew/.cache/Homebrew/zlib-1.2.11.x86_64_linux.bottle.tar.gz
SHA256: 6f604280b9e056da163b81cef3076b2e39bbd2b8d3cc8c36d27c19c472c760a4
==> Verifying zlib-1.2.11.x86_64_linux.bottle.tar.gz checksum
==> FAILED
```

The bottle was built, but there was an error. Not sure what failed though ...

**Comment by sjackman** [comment]
```
$ brew fetch zlib
==> Downloading https://linuxbrew.bintray.com/bottles/zlib-1.2.11.x86_64_linux.b
######################################################################## 100.0%
Downloaded to: /gsc/btl/linuxbrew/var/cache/homebrew/zlib-1.2.11.x86_64_linux.bottle.tar.gz
SHA256: 6f604280b9e056da163b81cef3076b2e39bbd2b8d3cc8c36d27c19c472c760a4
```
worked for me just now. Perhaps it was a transient error.

**Comment by sjackman** [comment]
💚

**Comment by iMichka** [comment]
Merged :)

**Comment by sjackman** [comment]
Thanks, Michka!

**Pull request closed without merging**
