### PR TITLE
Merge 2017-08-17 deaf9bad

### PR DESCRIPTION
**Pull request by rwhogg**
* [x] fio
* [ ] libuv
* [x] rancher-cli

598ec35e49 fio: update 3.0 bottle for Linuxbrew.
128525eb4b rancher-cli: update 0.6.3 bottle for Linuxbrew.
775067a7c2 fits: update 1.2.0 bottle for Linuxbrew.
6a1e109b8d git-town: update 4.2.1 bottle for Linuxbrew.

### CODE REVIEW

**Comment by rwhogg** [comment]
`argp-standalone` failed: https://travis-ci.org/Linuxbrew/homebrew-core/builds/265569194#L4580

```
make[1]: Entering directory `/tmp/argp-standalone-20170817-11522-7kngqh/argp-standalone-1.3'
if gcc-4.8 -DHAVE_CONFIG_H -I. -I. -I.   -I.  -g -O2 -ggdb3 -Wall -W  -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes  -Waggregate-return  -Wpointer-arith -Wbad-function-cast -Wnested-externs -MT argp-ba.o -MD -MP -MF ".deps/argp-ba.Tpo" -c -o argp-ba.o argp-ba.c; \
	then mv -f ".deps/argp-ba.Tpo" ".deps/argp-ba.Po"; else rm -f ".deps/argp-ba.Tpo"; exit 1; fi
if gcc-4.8 -DHAVE_CONFIG_H -I. -I. -I.   -I.  -g -O2 -ggdb3 -Wall -W  -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes  -Waggregate-return  -Wpointer-arith -Wbad-function-cast -Wnested-externs -MT argp-eexst.o -MD -MP -MF ".deps/argp-eexst.Tpo" -c -o argp-eexst.o argp-eexst.c; \
	then mv -f ".deps/argp-eexst.Tpo" ".deps/argp-eexst.Po"; else rm -f ".deps/argp-eexst.Tpo"; exit 1; fi
if gcc-4.8 -DHAVE_CONFIG_H -I. -I. -I.   -I.  -g -O2 -ggdb3 -Wall -W  -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes  -Waggregate-return  -Wpointer-arith -Wbad-function-cast -Wnested-externs -MT argp-fmtstream.o -MD -MP -MF ".deps/argp-fmtstream.Tpo" -c -o argp-fmtstream.o argp-fmtstream.c; \
	then mv -f ".deps/argp-fmtstream.Tpo" ".deps/argp-fmtstream.Po"; else rm -f ".deps/argp-fmtstream.Tpo"; exit 1; fi
In file included from argp-eexst.c:27:0:
argp.h:568:1: error: expected ‘,’ or ‘;’ before ‘{’ token
 {
 ^
argp.h:574:1: error: expected ‘,’ or ‘;’ before ‘{’ token
 {
 ^
argp.h:586:1: error: expected ‘,’ or ‘;’ before ‘{’ token
 {
 ^
make[1]: *** [argp-eexst.o] Error 1
```

Considering it's a standalone version of a `glibc` function, I'm not sure if there's any need for this formula on Linux.

---

linkage failed for `fits`: https://travis-ci.org/Linuxbrew/homebrew-core/builds/265569194#L5245

```
brew linkage --test fits
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libgcc_s.so.1
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6
Missing libraries:
  libzen.so.0
No unwanted system libraries
```
`libzen.so.0` comes with `fits` (./libexec/tools/mediainfo/linux/libzen.so.0), but I'm not sure why it's bundling `media-info`.

---

`git-town`'s test failed, but it's the usual Git email address not configured problem.

**Comment by rwhogg** [comment]
`libuv` failed on Circle because of a lack of `python`:

```
==> brew install --build-bottle --verbose libuv
==> Downloading https://github.com/libuv/libuv/archive/v1.14.0.tar.gz
Already downloaded: /home/linuxbrew/.cache/Homebrew/libuv-1.14.0.tar.gz
==> Verifying libuv-1.14.0.tar.gz checksum
tar xzf /home/linuxbrew/.cache/Homebrew/libuv-1.14.0.tar.gz
==> make man
.
Last 150 lines from /home/linuxbrew/.cache/Homebrew/Logs/libuv/01.make:
2017-08-17 13:19:30 +0000

make
man

sphinx-build -b man -d build/doctrees   src build/man
/usr/bin/env: python: No such file or directory
make: *** [man] Error 127

==> Formula
Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libuv.rb
==> Configuration
HOMEBREW_VERSION: >1.2.0 (no git repository)
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: 46d9544a4c5f44184ec228d59969fab3d4d006f5
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/linuxbrew/homebrew-core
Core tap HEAD: f1393dc7446de118d3182cb9fd756039e0a9a4b3
Core tap last commit: 11 minutes ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: 36-core 64-bit haswell
Homebrew Ruby: 2.0.0-p384 => /usr/bin/ruby2.0
Clang: N/A
Git: 1.9.1 => /usr/bin/git
Perl: /usr/bin/perl
Python: N/A
Ruby: /usr/bin/ruby => /usr/bin/ruby2.0
Java: N/A
Kernel: Linux 4.4.0-83-generic x86_64 GNU/Linux
OS: Ubuntu 14.04.5 LTS (trusty)
Host glibc: 2.19
/usr/bin/gcc: 4.8.4
glibc: N/A
gcc: N/A
xorg: N/A
```

**Comment by sjackman** [comment]
Merged!

**Comment by sjackman** [comment]
`deaf9bad` is the best SHA1 that I've seen yet. It'd be a good name for a band.

**Pull request closed without merging**
