### PR TITLE
libxml2: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by sjackman** [comment]
Circle failed in `brew install libcroco`
```
==> brew install libcroco
intltool: Unsatisfied dependency: XML::Parser
Homebrew does not provide special Perl dependencies; install with:
  `cpan -i XML::Parser`
Error: An unsatisfied requirement failed this build.
==> FAILED
```
which is weird because `XML::Parser` is installed in the `postinstall` of `perl`.
```
==> /home/linuxbrew/.linuxbrew/Cellar/perl/5.24.0_3/bin/cpan -i XML::Parser
```
In any case, it can be ignored for now, but would be good to figure out what's going on here.

**Comment by maxim-belkin** [comment]
That's because bottle for `intltool` was not updated, so it uses system's perl which does not have XML::Parser.

**Comment by sjackman** [comment]
System `perl` should have `XML::Parser`. We install it with `sudo apt-get install libxml-parser-perl`.
https://github.com/Linuxbrew/homebrew-core/blob/master/circle.yml#L21

**Comment by maxim-belkin** [comment]
Blocked by #1614

**Comment by maxim-belkin** [comment]
#1614 has been merged

**Comment by sjackman** [comment]
I triggered a rebuild on CircleCI.

**Comment by maxim-belkin** [comment]
rebased and force-pushed.

**Comment by maxim-belkin** [comment]
now, that is interesting:
```
==> brew install librsvg
intltool: Unsatisfied dependency: XML::Parser
Homebrew does not provide special Perl dependencies; install with:
  `cpan -i XML::Parser`
Error: An unsatisfied requirement failed this build.
==> FAILED
```

**Comment by maxim-belkin** [comment]
I was able to reproduce Circle's problem locally. Will see if I can fix that

**Comment by maxim-belkin** [comment]
Looks like root of the problem is:
```log
Running make for T/TO/TODDR/XML-Parser-2.44.tar.gz
Warning: Prerequisite 'LWP::UserAgent => 0' for 'TODDR/XML-Parser-2.44.tar.gz' failed when processing 'OALDERS/libwww-perl-6.16.tar.gz' with 'make_test => NO 2 dependencies      missing (HTML::Entities,HTML::HeadParser)'. Continuing, but chances to succeed are limited.
```
This is from the post-installation step in perl.

**Comment by maxim-belkin** [comment]
builds times out because of llvm.

**Pull request closed without merging**
