### PR TITLE
mongodb: error: pcap.h: No such file or directory

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
/home/linuxbrew/.linuxbrew/bin/g++-5 -std=c++11 -o build/opt/mongo/base/global_initializer.o -c -Wnon-virtual-dtor -Woverloaded-virtual -std=c++11 -I/home/linuxbrew/.linuxbrew/opt/openssl/include -fno-omit-frame-pointer -fPIC -fno-strict-aliasing -ggdb -pthread -Wall -Wsign-compare -Wno-unknown-pragmas -Winvalid-pch -Werror -O2 -Wno-unused-local-typedefs -Wno-unused-function -Wno-deprecated-declarations -Wno-unused-but-set-variable -Wno-missing-braces -fno-builtin-memcmp -DPCRE_STATIC -DNDEBUG -DBOOST_THREAD_VERSION=4 -DBOOST_THREAD_DONT_PROVIDE_VARIADIC_THREAD -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_THREAD_DONT_PROVIDE_INTERRUPTIONS -DBOOST_THREAD_HAS_NO_EINTR_BUG -Isrc/third_party/asio-asio-1-11-0/asio/include -Isrc/third_party/s2 -Isrc/third_party/pcre-8.37 -Isrc/third_party/boost-1.56.0 -Ibuild/opt -Isrc src/mongo/base/global_initializer.cpp
src/mongo/base/global_initializer.cpp:44:14: error: 'mongo::{anonymous}::_theGlobalInitializer' defined but not used [-Werror=unused-variable]
 Initializer* _theGlobalInitializer = &getGlobalInitializer();
              ^
cc1plus: all warnings being treated as errors
scons: *** [build/opt/mongo/base/global_initializer.o] Error 1
scons: building terminated because of errors.
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/128998030#L1978

**Comment by sjackman** [comment]
```
Building mongoreplay...
# github.com/google/gopacket/pcap
vendor/src/github.com/google/gopacket/pcap/pcap.go:19:18: fatal error: pcap.h: No such file or directory
compilation terminated.
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/191150506#L1867

**Comment by sjackman** [comment]
Oddly, depending on `libpcap` did not resolve the error on Circle.
It timed out on Travis. https://travis-ci.org/Linuxbrew/homebrew-core/builds/191160001#L1908

**Comment by sjackman** [comment]
Here are the instructions for building Mongodb from source. https://github.com/mongodb/mongo/wiki/Build-Mongodb-From-Source
I don't unfortunately see options to specify the location of `pcap.h`

**Comment by sjackman** [comment]
I've opened an issue upstream at https://github.com/mongodb/mongo-tools/issues/86

**Comment by timotheecour** [comment]
Here https://github.com/Linuxbrew/homebrew-core/issues/1568#issuecomment-272034351 you said:

> mongodb should work on Linuxbrew. I'm attempting to reproduce in #235

Does that mean it works for you? I've reproduced this bug on several ubuntu boxes, including a fresh phusion/baseimage:latest docker image.

**Comment by sjackman** [comment]
>> mongodb should work on Linuxbrew.

> I'm attempting to reproduce in #235
Does that mean it works for you? I've reproduced this bug on several ubuntu boxes, including a fresh phusion/baseimage:latest docker image.

`mongodb` has worked for me previously. I suspect that installing `libpcap-dev` using `apt-get` would work around this issue (untested). It currently does not work using brewed `libpcap`.

**Comment by sjackman** [comment]
Superseded by #1578

**Pull request closed without merging**
