### PR TITLE
sdl2: enable X for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by sjackman** [comment]
```
/home/linuxbrew/.linuxbrew/include/X11/XKBlib.h:31:35: fatal error: X11/extensions/XKBstr.h: No such file or directory
compilation terminated.
Makefile:569: recipe for target 'build/SDL_x11dyn.lo' failed
```
https://circleci.com/gh/Linuxbrew/homebrew-core/15466
https://circleci.com/api/v1.1/project/github/Linuxbrew/homebrew-core/15466/output/111/0?file=true

**Comment by Char-Aznable** [comment]
`XKBstr.h` should be provided in `Cellar/kbproto/1.0.7/include/X11/extensions/` -- might be add dependency to ```linuxbrew/xorg/kbproto```?

**Comment by Char-Aznable** [comment]
Another one: In file included from /tmp/sdl2-20180428-10403-1r895p2/SDL2-2.0.8/src/video/x11/SDL_x11dyn.h:47:0,
                 from /tmp/sdl2-20180428-10403-1r895p2/SDL2-2.0.8/src/video/x11/SDL_x11dyn.c:27:
/home/linuxbrew/.linuxbrew/include/X11/extensions/XShm.h:33:32: fatal error: X11/extensions/shm.h: No such file or directory

Should add dependency on `linuxbrew/xorg/xextproto`

**Comment by Char-Aznable** [comment]
Here are a list of xorg's libraries listed on sdl's website:
`libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev libxxf86vm-dev libxss-dev libgl1-mesa-dev libesd0-dev`
I'm not sure if all of these should be installed in order to get this configuration working

**Comment by iMichka** [comment]
Merged. I randomly enabled a bunch of flags without knowing exactly which ones are needed, so I hope this was enough :)

**Comment by Char-Aznable** [comment]
I can confirm that the current bottled version gives functional ffplay now.

**Pull request closed without merging**
