### PR TITLE
pango: Build a bottle for Linuxbrew: Fails with --env=super

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by sjackman** [comment]
```
Package xcb-shm was not found in the pkg-config search path.
Perhaps you should add the directory containing `xcb-shm.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xcb-shm', required by 'cairo', not found
/tmp/pango-20170410-28258-106o4r3/pango-1.40.5/pango/tmp-introspectptU3uA/Pango-1.0.c:2:18: fatal error: glib.h: No such file or directory
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/220435203#L5703

**Comment by maxim-belkin** [comment]
see the same error here: https://github.com/Linuxbrew/homebrew-xorg/pull/294#issuecomment-293389792

it is blocked by either Linuxbrew/homebrew-core#2302 or Linuxbrew/brew#337

**Comment by sjackman** [comment]
A fix like PR https://github.com/Linuxbrew/brew/pull/337 allows us to use Homebrew formula unmodified, so that's my preferred solution.

**Comment by maxim-belkin** [comment]
It works so nicely for Homebrew because there it add just one dependency only. For Linuxbrew, however, it brings quite a few dependencies from Linuxbrew/xorg which, in turn, depend on things in Linuxbrew/core: https://gist.github.com/maxim-belkin/c621dcb11288399b314d227fa44e734c

**Comment by sjackman** [comment]
The user has to install the dependencies of `:x11` only once, then it's done. It may be only one dependency on Mac, but it's one monolithic dependency.

**Comment by maxim-belkin** [comment]
Closing to play around with deps (as I can't commit/rebase this branch)

Superseded by #2384

**Pull request closed without merging**
