### PR TITLE
efl: Add missing dependencies for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
> configure: error: OpenGL XLib dependencies not found

**Comment by sjackman** [comment]
What's the `systemd` dependency need for? Just curious. `libudev`?

**Comment by iMichka** [comment]
No clue. The build error was:
```
checking for sched_getcpu... yes
configure: error: systemd support wanted, but systemd was not found.
```

**Comment by iMichka** [comment]
```
gcc-5: error: 10000: No such file or directory
gcc-5: error: 100000000: No such file or directory
gcc-5: error: 10000: No such file or directory
gcc-5: error: 100000000: No such file or directory
gcc-5: error: 10000: No such file or directory
gcc-5: error: 100000000: No such file or directory
gcc-5: error: unrecognized command line option '-pagezero_size'
gcc-5: error: unrecognized command line option '-image_base'
Makefile:26813: recipe for target 'bin/evas/evas_cserve2' failed
make[3]: *** [bin/evas/evas_cserve2] Error 1
make[3]: *** Waiting for unfinished jobs....
gcc-5: error: unrecognized command line option '-pagezero_size'
gcc-5: error: unrecognized command line option '-image_base'
gcc-5: error: unrecognized command line option '-pagezero_size'
gcc-5: error: unrecognized command line option '-image_base'
Makefile:26640: recipe for target 'bin/elua/elua' failed
make[3]: *** [bin/elua/elua] Error 1
Makefile:51882: recipe for target 'install-recursive' failed
make[2]: *** [install-recursive] Error 1
Makefile:52568: recipe for target 'install' failed
make[1]: *** [install] Error 2
Makefile:2971: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

==> Formula
Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/efl.rb
```

**Comment by iMichka** [comment]
That error is quite uncommon. I bet that we are hitting the 4Gb memory limit.

**Comment by iMichka** [comment]
`-j1` worked, but:

```
==> git clean -ffdx --exclude=Library/Taps
brew untap linuxbrew/extra
Untapping linuxbrew/extra... (36 files, 126KB)
Untapped 5 formulae
git checkout -f master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
git reset --hard origin/master
HEAD is now at 09208fb CircleCI: Store artifacts [Linux]
git clean -ffdx --exclude=Library/Taps --exclude=Library/Homebrew/vendor
git checkout -f master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
git reset --hard origin/master
HEAD is now at 2bc64b1 .travis.yml: Sync with core (#328)
git checkout -f master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
git reset --hard origin/master
HEAD is now at 736a7f8 picard-tools 2.12.0 (#6295)
Error: Kernel.exit
Exited with code 1
```

**Pull request closed without merging**
