### PR TITLE
qt: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
g++ -Wl,--no-undefined -Wl,--version-script,QtXcbQpa.version -Wl,-O1 -fuse-ld=gold -Wl,--enable-new-dtags -Wl,-z,origin -Wl,-rpath,\$ORIGIN -Wl,-rpath,/home/linuxbrew/.linuxbrew/Cellar/qt/5.11.2_1/lib -shared -Wl,-Bsymbolic-functions -Wl,-soname,libQt5XcbQpa.so.5 -o libQt5XcbQpa.so.5.11.2 .obj/qxcbclipboard.o .obj/qxcbconnection.o .obj/qxcbintegration.o .obj/qxcbkeyboard.o .obj/qxcbmime.o .obj/qxcbscreen.o .obj/qxcbwindow.o .obj/qxcbbackingstore.o .obj/qxcbwmsupport.o .obj/qxcbnativeinterface.o .obj/qxcbcursor.o .obj/qxcbimage.o .obj/qxcbxsettings.o .obj/qxcbsystemtraytracker.o .obj/qxcbdrag.o .obj/qxcbconnection_xi2.o .obj/qxcbsessionmanager.o .obj/qxcbglintegrationfactory.o .obj/qxcbglintegration.o .obj/qxcbnativeinterfacehandler.o .obj/moc_qxcbconnection.o .obj/moc_qxcbmime.o .obj/moc_qxcbnativeinterface.o .obj/moc_qxcbsystemtraytracker.o .obj/moc_qxcbglintegrationplugin.o  -L/tmp/qt-20181126-7838-19nhxrx/qt-everywhere-src-5.11.2/qtbase/lib -lQt5ServiceSupport -L/home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/lib -lQt5ThemeSupport -lQt5EventDispatcherSupport -L/home/linuxbrew/.linuxbrew/Cellar/glib/2.58.1/lib -lgthread-2.0 -lglib-2.0 -lQt5FontDatabaseSupport -lGL -lqtfreetype -lqtlibpng -lz -lQt5Gui -lQt5EdidSupport -lQt5DBus -lQt5Core -lpthread -L/home/linuxbrew/.linuxbrew/Cellar/libxcb/1.13/lib -L/home/linuxbrew/.linuxbrew/Cellar/libx11/1.6.6/lib -lX11-xcb -lX11 -L/home/linuxbrew/.linuxbrew/Cellar/libxi/1.7.9/lib -lXi -L/home/linuxbrew/.linuxbrew/Cellar/libice/1.0.9/lib -L/home/linuxbrew/.linuxbrew/Cellar/libsm/1.2.2/lib -lSM -lICE -lxcb-static -lxcb -L/home/linuxbrew/.linuxbrew/Cellar/libxkbcommon/0.8.2_1/lib -lxkbcommon-x11 -lxkbcommon -ldl -L/home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/lib -lGL 
.obj/qxcbbackingstore.o:qxcbbackingstore.cpp:function QXcbBackingStoreImage::createShmSegment(unsigned long): error: undefined reference to 'xcb_shm_create_segment'
.obj/qxcbbackingstore.o:qxcbbackingstore.cpp:function QXcbBackingStoreImage::createShmSegment(unsigned long): error: undefined reference to 'xcb_shm_create_segment_reply'
.obj/qxcbbackingstore.o:qxcbbackingstore.cpp:function QXcbBackingStoreImage::createShmSegment(unsigned long): error: undefined reference to 'xcb_shm_create_segment_reply_fds'
collect2: error: ld returned 1 exit status
Makefile.xcb_qpa_lib:334: recipe for target '../../../../lib/libQt5XcbQpa.so.5.11.2' failed
make[6]: *** [../../../../lib/libQt5XcbQpa.so.5.11.2] Error 1
make[6]: Leaving directory '/tmp/qt-20181126-7838-19nhxrx/qt-everywhere-src-5.11.2/qtbase/src/plugins/platforms/xcb'
Makefile:88: recipe for target 'sub-xcb_qpa_lib-pro-make_first-ordered' failed
make[5]: *** [sub-xcb_qpa_lib-pro-make_first-ordered] Error 2
make[5]: Leaving directory '/tmp/qt-20181126-7838-19nhxrx/qt-everywhere-src-5.11.2/qtbase/src/plugins/platforms/xcb'
Makefile:100: recipe for target 'sub-xcb-make_first' failed
make[4]: *** [sub-xcb-make_first] Error 2
make[4]: Leaving directory '/tmp/qt-20181126-7838-19nhxrx/qt-everywhere-src-5.11.2/qtbase/src/plugins/platforms'
Makefile:102: recipe for target 'sub-platforms-make_first' failed
make[3]: *** [sub-platforms-make_first] Error 2
make[3]: Leaving directory '/tmp/qt-20181126-7838-19nhxrx/qt-everywhere-src-5.11.2/qtbase/src/plugins'
Makefile:775: recipe for target 'sub-plugins-make_first' failed
make[2]: *** [sub-plugins-make_first] Error 2
make[2]: Leaving directory '/tmp/qt-20181126-7838-19nhxrx/qt-everywhere-src-5.11.2/qtbase/src'
Makefile:48: recipe for target 'sub-src-make_first' failed
make[1]: *** [sub-src-make_first] Error 2
make[1]: Leaving directory '/tmp/qt-20181126-7838-19nhxrx/qt-everywhere-src-5.11.2/qtbase'
Makefile:83: recipe for target 'module-qtbase-make_first' failed
make: *** [module-qtbase-make_first] Error 2
```

**Comment by thoughton** [comment]
(Not sure this is actually stale...?)

**Comment by iMichka** [comment]
The bot adds the label after some time. It means that nobody is actively working on this.

I already tried to debug this but had no luck with it until now. I'll give it a second try.

**Comment by iMichka** [comment]
This looks ok:
```
strings /home/linuxbrew/.linuxbrew/Cellar/libxcb/1.13/lib/libxcb-shm.so | grep xcb_shm_create
xcb_shm_create_pixmap
xcb_shm_create_segment_reply
xcb_shm_create_segment
xcb_shm_create_segment_unchecked
xcb_shm_create_segment_reply_fds
xcb_shm_create_pixmap_checked
xcb_shm_create_pixmap_checked
xcb_shm_create_pixmap
xcb_shm_create_segment
xcb_shm_create_segment_unchecked
xcb_shm_create_segment_reply
xcb_shm_create_segment_reply_fds
```

I tried to add `-lxcb-shm` to the failing step and it worked. So it looks like this flag is missing from the build.

**Comment by iMichka** [comment]
I found a workaround. Not really elegant but it works. It looks like that part of the code is quite fragile anyway in qt.

**Pull request closed without merging**
