### PR TITLE
nvc: Depends on bison flex tcl

### PR DESCRIPTION
**Pull request by jck**

### CODE REVIEW

**Comment by sjackman** [comment]
```
configure: error: GNU Flex not found
```

Depends on `flex` and probably `bison` too.

**Comment by sjackman** [comment]
```
checking tcl.h usability... no
checking tcl.h presence... no
checking for tcl.h... no
checking tcl/tcl.h usability... yes
checking tcl/tcl.h presence... yes
checking for tcl/tcl.h... yes
checking for library containing Tcl_CreateInterp... no
configure: error: TCL library not found
```

Depends on `tcl`

**Comment by sjackman** [comment]
@jck Woud you like to add the dependencies to this PR?

**Comment by jck** [comment]
Sorry, I missed this notification. I have added the dependencies.

**Comment by sjackman** [comment]
```
Error: No available formula with the name "tcl"
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/172173692#L440

Try instead
```ruby
depends_on "homebrew/dupes/tcl-tk" unless OS.mac?
```

**Pull request closed without merging**
