### PR TITLE
octave: Depends on curl for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**
Fix the error: Missing libraries: libcurl.so.4

### CODE REVIEW

**Comment by sjackman** [comment]
Blocked by `graphicsmagick` https://github.com/Linuxbrew/homebrew-core/pull/4072

**Comment by iMichka** [comment]
There was an octave bump in the last core merge, so you will have to rebase after that:
https://github.com/Linuxbrew/homebrew-core/pull/4079

**Comment by sjackman** [comment]
Only failure is the unrelated `swrcfit`.
```
==> brew install swrcfit
==> Installing swrcfit from homebrew/science
Error: homebrew/science/swrcfit contains conflicting version recursive dependencies:
  openssl, openssl@1.1
View these with `brew deps --tree homebrew/science/swrcfit`.
==> FAILED
```

Merge PR #4079 produced no bottles, so I'm merging this PR. I'll then open a merge PR to replace #4079.

**Comment by iMichka** [comment]
Ok. I'm fine with that. We really need to do something for `swrcfit` in science. I think I have an old PR open for that. If it is too broken we should just remove it or write a patch for it ourselves ...

**Comment by sjackman** [comment]
Never mind. I forgot that this PR wasn't intended to produce a bottle, because it's already bottled.

**Comment by sjackman** [comment]
Merged without updating the bottle.

**Pull request merged**
