### PR TITLE
openssl@1.1: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
Test Summary Report
-------------------
../test/recipes/90-test_shlibload.t      (Wstat: 1024 Tests: 4 Failed: 4)
  Failed tests:  1-4
  Non-zero exit status: 4
```

@sjackman We have one failing test for openssl@1.1

**Comment by sjackman** [comment]
I can reproduce this test failure in the `linuxbrew/linuxbrew` Docker image.

**Comment by iMichka** [comment]
@sjackman I am almost in vacation, and will have no internet access. So I will not be able to follow up on this in the next 2 weeks. Can you take this over?

**Comment by iMichka** [comment]
Considering this as a build error, as the test suite is part of the build process for `openssl`.

**Comment by sjackman** [comment]
I can look into it. My plan is to test building this version of OpenSSL outside of Linuxbrew to attempt to replicate the build failure. If I'm able to replicate that issue, I'll open an issue upstream with the developers of `openssl`.

**Comment by iMichka** [comment]
openssl@1.1 1.1.1 has been released and merged. Still the same error.

**Comment by iMichka** [comment]
The error is the following:

```
linuxbrew@3e40aaea99f5:/tmp/openssl@1.1-20180919-2688-y1lxx6/openssl-1.1.1$ test/shlibloadtest -crypto_first libcrypto.so libssl.so
test/shlibloadtest: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by iMichka** [comment]
```
linuxbrew@3e40aaea99f5:/tmp/openssl@1.1-20180919-2688-y1lxx6/openssl-1.1.1$ ls -l | grep .so
lrwxrwxrwx  1 linuxbrew linuxbrew      16 Sep 19 21:34 libcrypto.so -> libcrypto.so.1.1
-rwxr-xr-x  1 linuxbrew linuxbrew 3207912 Sep 19 21:34 libcrypto.so.1.1
lrwxrwxrwx  1 linuxbrew linuxbrew      13 Sep 19 21:34 libssl.so -> libssl.so.1.1
-rwxr-xr-x  1 linuxbrew linuxbrew  671520 Sep 19 21:34 libssl.so.1.1
```

**Comment by sjackman** [comment]
```
test/shlibloadtest: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```
I bet it's because it's keg-only and the executables don't know where to find their libraries. The `RPATH` is set to the installation `lib` directory, but the libraries are not yet installed. Try running `make install` before `make test`.

Hopefully that works. If not, you could try setting `LD_LIBRARY_PATH` to wherever the libraries exist before installation.

**Comment by sjackman** [comment]
Tests were disabled with…
```ruby
system "make", "test" if build.with?("test") && OS.mac?
```
I'm fine with that. Were you able to test either of my suggested work arounds above, either running `make install` before `make test`, or setting `LD_LIBRARY_PATH` during `make test`?

**Comment by iMichka** [comment]
I added the tests after the install step, see lines below. The tests ran and worked. I think this is fine like it is.

**Pull request closed without merging**
