### PR TITLE
glib: Build a bottle for Linuxbrew: Depends on XML::Parser

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
Circle
```
checking for XML::Parser... configure: error: XML::Parser perl module is required for intltool
```

**Comment by sjackman** [comment]
Debian package `libxml-parser-perl` is already installed.
```
==> Installing gtk-doc dependency: perl
```

gtk-doc
```
  depends_on :perl => "5.18" if MacOS.version <= :mavericks
```

When `gtk-doc` is installed from a bottle it pulls in `perl` which doesn't yet have any packages installed.

The `postinstall` of `perl` should install the core necessary Perl packages.

**Comment by maxim-belkin** [comment]
`XML::parser` is required for `shared-mime-info`

**Comment by rwhogg** [comment]
Closed in favour of #1216

**Pull request closed without merging**
