### PR TITLE
hiredis: fix for Linuxbrew

### PR DESCRIPTION
**Pull request by xu-cheng**
- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by sjackman** [comment]
Thanks again, @xu-cheng!

**Comment by sjackman** [comment]
Because `libjson-rpc-cpp` already has a bottle for `x86_64_linux`, updating it in this PR causes the whole job to fail, and prevents the bottle for `hiredis` from being updated (due to `test-bot --keep-old` and limitations of our CI infrastructure). Please split this PR into two PRs. Sorry for the hassle.

**Comment by xu-cheng** [comment]
See #9120 for `hiredis`. I will create PR for `libjson-rpc-cpp` after it is merged.

**Comment by xu-cheng** [comment]
`libjson-rpc-cpp` is in #9123

**Pull request closed without merging**
