### PR TITLE
exa: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
git2/common.h: No such file or directory
compilation terminated.
make[3]: *** [CMakeFiles/git2.dir/src/diff_generate.c.o] Error 1
make[3]: *** [CMakeFiles/git2.dir/src/attr.c.o] Error 1
In file included from /home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/src/checkout.c:10:0:
/home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/src/checkout.h:10:27: fatal error: git2/checkout.h: No such file or directory
```

**Comment by iMichka** [comment]
Needs #10284 first.

**Comment by iMichka** [comment]
```
In file included from /home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/src/hash.h:28:0,
                 from /home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/src/filebuf.h:11,
                 from /home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/src/index.h:11,
                 from /home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/src/diff.c:13:
/home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/src/hash/hash_generic.h:11:18: fatal error: hash.h: No such file or directory
compilation terminated.
make[3]: *** [CMakeFiles/git2.dir/src/config_file.c.o] Error 1
make[3]: *** [CMakeFiles/git2.dir/src/diff.c.o] Error 1
In file included from /home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/src/hash.h:28:0,
                 from /home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/src/filebuf.h:11,
                 from /home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/src/index.h:11,
                 from /home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/src/diff_generate.c:16:
/home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/src/hash/hash_generic.h:11:18: fatal error: hash.h: No such file or directory
compilation terminated.
make[3]: *** [CMakeFiles/git2.dir/src/diff_generate.c.o] Error 1
In file included from /home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/src/hash.h:28:0,
                 from /home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/src/filebuf.h:11,
                 from /home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/src/fetchhead.c:15:
/home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/src/hash/hash_generic.h:11:18: fatal error: hash.h: No such file or directory
compilation terminated.
make[3]: *** [CMakeFiles/git2.dir/src/fetchhead.c.o] Error 1
make[2]: *** [CMakeFiles/git2.dir/all] Error 2
make[1]: *** [all] Error 2
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2
```

**Comment by falzm** [comment]
Maybe we can open an issue at the [exa Github project](https://github.com/ogham/exa) to ask for some help?

**Comment by iMichka** [comment]
```
gcc-5 called with: -DGIT_ARCH_64 -DGIT_THREADS -DGIT_USE_NSEC -DGIT_USE_STAT_MTIM -DHAVE_FUTIMENS -DHAVE_QSORT_R -D_FILE_OFFSET_BITS=64 -I/home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/src -I/home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/include -I/home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/deps/http-parser -I/home/linuxbrew/.linuxbrew/include -D_GNU_SOURCE -ffunction-sections -fdata-sections -fPIC -m64 -Wall -Wextra -Wdocumentation -Wno-missing-field-initializers -Wstrict-aliasing=2 -Wstrict-prototypes -Wdeclaration-after-statement -Wno-unused-const-variable -Wno-unused-function -O3 -DNDEBUG -o CMakeFiles/git2.dir/src/attr.c.o -c /home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/src/attr.c
superenv removed:  -I/home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/src -I/home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/include -I/home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/deps/http-parser -I/home/linuxbrew/.linuxbrew/include -m64 -Wall -Wextra -Wdocumentation -Wstrict-aliasing=2 -Wstrict-prototypes -Wdeclaration-after-statement -O3
superenv added:    -pipe -w -O2 -march=native -isystem/home/linuxbrew/.linuxbrew/include
superenv executed: gcc-5 -pipe -w -O2 -march=native -DGIT_ARCH_64 -DGIT_THREADS -DGIT_USE_NSEC -DGIT_USE_STAT_MTIM -DHAVE_FUTIMENS -DHAVE_QSORT_R -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -ffunction-sections -fdata-sections -fPIC -Wno-missing-field-initializers -Wno-unused-const-variable -Wno-unused-function -DNDEBUG -o CMakeFiles/git2.dir/src/attr.c.o -c /home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/src/attr.c -isystem/home/linuxbrew/.linuxbrew/include
```

**Comment by iMichka** [comment]
@sjackman superenv removes:
> -I/home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/src -I/home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/include -I/home/linuxbrew/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.14/libgit2/deps/http-parser

**Comment by sjackman** [comment]
I created a fix but I haven't tested it yet, so I haven't opened a PR yet. Here's the untested commit. https://github.com/sjackman/homebrew/commit/037f2b60f290aaf8599019b991da8bbb3fb98214

**Comment by sjackman** [comment]
I've opened PR https://github.com/Homebrew/brew/pull/5393 to fix this issue.

**Comment by sjackman** [comment]
PR https://github.com/Homebrew/brew/pull/5393 has been merged. Hopefully this PR will work now.

**Comment by iMichka** [comment]
Almost there. The bottling now fails.

**Comment by sjackman** [comment]
> Almost there. The bottling now fails.

That's most likely because it depends on `rust`. These problems should hopefully go away once we're caught up.

**Comment by iMichka** [comment]
What do you  mean about `rust`? `rust` is a build time dependency. The `rust` bottle is now built and uploaded, and a rebase here did not change anything.

**Comment by sjackman** [comment]
Previously before my patches to Homebrew/brew, anything built with `rust` would come up as being non-relocatable. After my patches, they are `cellar :any`. The macOS bottle was likely built before my patches, so came up as non-relocatable. The Linux bottle being built after, is coming up as `cellar :any`.

**Comment by iMichka** [comment]
Ok, got it. I ran the bottle step on mac (with a from-source build of exa), and got a bottle with `cellar :any_skip_relocation`. So I can use `cellar :any_skip_relocation` here, as the linux build proposes to add it too.

**Comment by iMichka** [comment]
Here we got, bottle is built and uploaded.

**Pull request closed without merging**
