### PR TITLE
tcsh: Depends on ncurses for Linuxbrew

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by rwhogg** [comment]
From https://travis-ci.org/Linuxbrew/homebrew-core/builds/127860678#L636-L640

```
==> /home/linuxbrew/.linuxbrew/Cellar/tcsh/6.19.00/bin/tcsh ./test.csh
/home/linuxbrew/.linuxbrew/Cellar/tcsh/6.19.00/bin/tcsh: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
Error: tcsh: failed
<0> expected but was
<127>.
```

This looks like a missing `ncurses` dependency (for historical reasons, `libtinfo` is provided by `ncurses` on Ubuntu).

**Comment by rwhogg** [comment]
@sjackman: while Travis was green for this PR, it's been going red since the merge (on this formula only).

Thinking I should revert this.

**Comment by sjackman** [comment]
This patch is good, but the bottle is bad. It's linked against `libtinfo.so.5`, which our `ncurses` package doesn't provide. I'll remove `libtinfo-dev` from the LinuxbrewTestBot to prevent this from happening. Rebuilding the bottle should fix it.

**Comment by sjackman** [comment]
```
$ patchelf --print-needed ~/.linuxbrew/bin/tcsh
libtinfo.so.5
libcrypt.so.1
libc.so.6
```

**Comment by sjackman** [comment]
This PR is related: https://github.com/Homebrew/homebrew-dupes/pull/517

**Comment by sjackman** [comment]
I'm trying a rebuild of the bottle over here: https://github.com/Linuxbrew/homebrew-core/pull/212

**Comment by sjackman** [comment]
Much better:
```
$ patchelf --print-needed ~/.linuxbrew/bin/tcsh
libncursesw.so.6
libcrypt.so.1
libc.so.6
```

**Pull request closed without merging**
