### PR TITLE
atkmm: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Circle
```
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/atkmm/test.01.g++-4.8:
2017-04-28 16:54:43 +0000

/usr/bin/g++-4.8
-std=c++11
test.cpp
-o
test
-I/home/linuxbrew/.linuxbrew/opt/atk/include/atk-1.0
-I/home/linuxbrew/.linuxbrew/opt/gettext/include
-I/home/linuxbrew/.linuxbrew/opt/glib/include/glib-2.0
-I/home/linuxbrew/.linuxbrew/opt/glib/lib/glib-2.0/include
-I/home/linuxbrew/.linuxbrew/opt/glibmm/include/glibmm-2.4
-I/home/linuxbrew/.linuxbrew/opt/glibmm/lib/glibmm-2.4/include
-I/home/linuxbrew/.linuxbrew/Cellar/atkmm/2.24.2/include/atkmm-1.6
-I/home/linuxbrew/.linuxbrew/opt/libsigc++/include/sigc++-2.0
-I/home/linuxbrew/.linuxbrew/opt/libsigc++/lib/sigc++-2.0/include
-L/home/linuxbrew/.linuxbrew/opt/atk/lib
-L/home/linuxbrew/.linuxbrew/opt/gettext/lib
-L/home/linuxbrew/.linuxbrew/opt/glib/lib
-L/home/linuxbrew/.linuxbrew/opt/glibmm/lib
-L/home/linuxbrew/.linuxbrew/opt/libsigc++/lib
-L/home/linuxbrew/.linuxbrew/Cellar/atkmm/2.24.2/lib
-latk-1.0
-latkmm-1.6
-lglib-2.0
-lglibmm-2.4
-lgobject-2.0
-lintl
-lsigc-2.0

/usr/bin/ld: cannot find -lintl
collect2: error: ld returned 1 exit status
Error: atkmm: failed
```

**Comment by sjackman** [comment]
```ruby
*("-lintl" if OS.mac?)
```

**Comment by maxim-belkin** [comment]
Linuxbrew/brew#360

**Comment by maxim-belkin** [comment]
I don't think this syntax works inside of `%W[]`

**Comment by maxim-belkin** [comment]
Oh! the test is in standard env...

**Comment by sjackman** [comment]
> Oh! the test is in standard env...

Yeah, that's by design. The reasoning being that `brew test` should be in an environment similar to that of the user, to ensure the package works in their environment.

**Comment by maxim-belkin** [comment]
Travis:
```
undefined reference to `get_defs[abi:cxx11](unsigned long, bool (*)(unsigned long))
```
Similar error [here](https://mail.gnome.org/archives/gtkmm-list/2016-March/msg00013.html):

> A way to know that is to type:
$ cd /usr/lib
$ for each in *.so; do i686-pc-linux-gnu-gcc-nm -D ${each} | grep get_defs && echo ${each}; done
[...]
00003620 T _Z8get_defsmPFbmE
libglibmm_generate_extra_defs-2.4.so
[...]
> 
> So, I need to rebuild glibmm-2.38.2.
```

**Comment by maxim-belkin** [comment]
In a docker container based on `linuxbrew/linuxbrew` image:
```
$ brew install glibmm
==> Downloading https://linuxbrew.bintray.com/bottles/glibmm-2.50.1.x86_64_linux.bottle.tar.gz
Already downloaded: /home/linuxbrew/.cache/Homebrew/glibmm-2.50.1.x86_64_linux.bottle.tar.gz
==> Pouring glibmm-2.50.1.x86_64_linux.bottle.tar.gz
Warning: glibmm dependency libsigc++ was built with a different C++ standard
library (libstdc++ from gcc-5). This may cause problems at runtime.
🍺  /home/linuxbrew/.linuxbrew/Cellar/glibmm/2.50.1: 1,669 files, 61.1MB
```

**Comment by sjackman** [comment]
`Warning: glibmm dependency libsigc++ was built with a different C++ standard`

If it's coming up on CircleCI it's a false positive that ought to be fixed.
If it's coming up on TravisCI and the build fails, then it's working!

**Pull request closed without merging**
