### PR TITLE
Fix -liconv in formulas for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
```
gcc-4.8 -o unzip -liconv -Lbzip2 unzip.o crc32.o  crypt.o envargs.o explode.o extract.o fileio.o globals.o inflate.o list.o match.o process.o ttyio.o ubz2err.o unreduce.o unshrink.o zipinfo.o unix.o -lbz2 
gcc-4.8 -o funzip -liconv funzip.o crc32.o  cryptf.o globalsf.o inflatef.o ttyiof.o 
/usr/bin/ld: cannot find -liconv
unix.o: In function `set_symlnk_attribs':
unix.c:(.text+0x1840): warning: lchmod is not implemented and will always fail
collect2: error: ld returned 1 exit status
make[1]: *** [unzip] Error 1
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot find -liconv
collect2: error: ld returned 1 exit status
make[1]: *** [funzip] Error 1
make[1]: Leaving directory `/tmp/unzip-20170429-38645-11o2ud7/unzip60'
make: *** [macosx] Error 2
```

**Comment by sjackman** [comment]
It turns out that `ENV.refurbish_args` is *not* enabled by default. It's only enabled selectively in`audio go@1.4 nethack4 py2cairo saldl tbox vice`

**Comment by sjackman** [comment]
For that reason I suggest closing this PR without merging. Thanks for the effort anyway, Maxim.

**Comment by maxim-belkin** [comment]
> For that reason I suggest closing this PR without merging. Thanks for the effort anyway, Maxim.

No problem.

> It turns out that `ENV.refurbish_args` is *not* enabled by default. It's only enabled selectively in`audio go@1.4 nethack4 py2cairo saldl tbox vice`

Can you explain a bit more?

**Comment by sjackman** [comment]
Unless the formula calls `ENV.refurbish_args`, the function `refurbished_args` is not called. I only just learned this. I'm surprised that it's not the default.
See https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/shims/linux/super/cc#L89-L93

**Pull request closed without merging**
