### PR TITLE
perl: Depends on gdbm with libgdbm-compat for Linuxbrew

### PR DESCRIPTION
**Pull request by rwhogg**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by rwhogg** [comment]
See also #134 and https://github.com/linuxbrew/linuxbrew/pull/186

**Comment by rwhogg** [comment]
From https://travis-ci.org/Linuxbrew/homebrew-core/builds/127290665#L1499-L1503

```
/home/linuxbrew/.linuxbrew/Cellar/perl/5.22.1_1/bin/perl
test.pl
/home/linuxbrew/.linuxbrew/Cellar/perl/5.22.1_1/bin/perl: error while loading shared libraries: libperl.so: cannot open shared object file: No such file or directory
Error: perl: failed
```

Seriously? Ugh...

**Comment by sjackman** [comment]
Perl installs `libperl.so` in `…/Cellar/perl/5.22.1_1/lib/5.22.1/x86_64-linux-thread-multi/CORE/libperl.so`. It must be setting its `RPATH` to this location. When installing a bottle, Linuxbrew uses `patchelf` to wipe out the existing `RPATH` and replace it with `$HOMEBREW_PREFIX/lib`, which is overly simplistic. The fix is pretty straight forward. The `RPATH` in the bottle needs to fixed up to relocate `@@HOMEBREW_PREFIX@@` to `$HOMEBREW_PREFIX` and then add `$HOMEBREW_PREFIX/lib` if it's missing, probably to the end of the list.

**Comment by sjackman** [comment]
Blocked by https://github.com/Linuxbrew/brew/issues/8

**Comment by DoomHammer** [comment]
Funny, `./Configure` works fine here even though no `gdbm` in sight... (`make` fails, though)

**Comment by DoomHammer** [comment]
While on the other system it indeed complains about lacking `gdbm`. `perl` is a strange beast (but so is `python`).

**Comment by sjackman** [comment]
Building `perl` also requires `berkeley-db` on my CentOS 6 system.

```
==> ./Configure -des -Dprefix=/home/sjackman/.linuxbrew/Cellar/perl/5.22.1_1 -Dm
Last 15 lines from /home/sjackman/.cache/Homebrew/Logs/perl/01.Configure:
#include <stdio.h>
int main() { printf("Ok\n"); return(0); }

I used the command:

	cc -o try -O2 -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -fstack-protector-strong -L/usr/local/lib try.c -lpthread -lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc -lgdbm_compat
	 ./try

and I got the following output:

/home/sjackman/.linuxbrew/bin/ld: cannot find -ldb
collect2: error: ld returned 1 exit status
I can't compile the test program.
You have a BIG problem.  Shall I abort Configure [y]  
Ok.  Stopping Configure.
```

**Pull request closed without merging**
