### PR TITLE
ppsspp: Reduce CircleCI memory usage for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
-j24 > took more than 120 minutes to run
...

**Comment by sjackman** [comment]
Sigh. You could try between 25 and 31 threads to try to find a value that works, or you can close this PR without merging.

**Comment by iMichka** [comment]
28 and 30 timed out. Last try with 31.

**Comment by sjackman** [comment]
🤞

**Comment by iMichka** [comment]
> took more than 120 minutes to run

Ok so 31 is also not working. Abandoning.

**Pull request closed without merging**
