### PR TITLE
zookeeper: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
==> Verifying zookeeper-3.4.12.tar.gz checksum
tar xzf /home/linuxbrew/.cache/Homebrew/zookeeper-3.4.12.tar.gz
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:204:in `dump': singleton class can't be dumped (TypeError)
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:204:in `rescue in <main>'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:193:in `<main>'
Error: Forked child process failed: pid 2768 exit 1
==> FAILED
```

**Comment by iMichka** [comment]
@sjackman This looks like a weird bug. I have never seen that before.

**Comment by sjackman** [comment]
I have also never seen this error before. The line that's failing is inside an exception handling block, so the real error that's causing the exception in the first place is probably something different.

**Comment by sjackman** [comment]
```
$ brew irb <<<'Hardware::CPU.universal_archs'
NameError: uninitialized constant #<Class:Hardware::CPU>::ArchitectureListExtension
```
🐞

**Comment by sjackman** [comment]
I've opened issue https://github.com/Linuxbrew/brew/issues/699

**Pull request closed without merging**
