### PR TITLE
docker-machine: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by sjackman** [comment]
```
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/lib --set-interpreter /home/linuxbrew/.linuxbrew/lib/ld.so /home/linuxbrew/.linuxbrew/Cellar/go/1.8.1/libexec/src/debug/elf/testdata/gcc-amd64-linux-exec
Error: Failure while executing: ["ldd", "/home/linuxbrew/.linuxbrew/Cellar/go/1.8.1/libexec/src/debug/elf/testdata/gcc-386-freebsd-exec"] 
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/226834708#L1652

I believe this issue should be resolved. Can you try rebasing this PR onto master?

**Comment by maxim-belkin** [comment]
yes, this should be resolved. I'll do that once I finish up my exercise with the three PRs :)

**Comment by maxim-belkin** [comment]
rebased and force-pushed

**Comment by sjackman** [comment]
Failed while building `git`. https://travis-ci.org/Linuxbrew/homebrew-core/builds/231651778#L1275
Superseded by https://github.com/Linuxbrew/homebrew-core/pull/2828

**Pull request closed without merging**
