### PR TITLE
rpm: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
/bin/bash ./libtool  --tag=CC   --mode=link gcc-5 -fPIC -DPIC -D_REENTRANT -Wall -Wpointer-arith -Wmissing-prototypes -Wstrict-prototypes  -fno-strict-aliasing -fstack-protector -Wempty-body -g -O2   -o rpmspec rpmspec-rpmspec.o libcliutils.la build/librpmbuild.la lib/librpm.la rpmio/librpmio.la -lpopt -lcrypto -lcrypto -lcrypto -ldl -lpthread 
/tmp/rpm-20181114-10320-1m2xl0b/rpm-4.14.1/rpmio/.libs/librpmio.so: undefined reference to `EVP_md2'
collect2: error: ld returned 1 exit status
Makefile:962: recipe for target 'rpm2cpio' failed
```
https://circleci.com/gh/Linuxbrew/homebrew-core/22272

Same error as observed by @ranavikas007 in #10306.

I'm not planning to work on this issue myself.
@ranavikas007 A PR would be most welcome if you're able to find a fix for this issue.

**Comment by iMichka** [comment]
I think I found it: http://lists.rpm.org/pipermail/rpm-maint/2017-December/007031.html

`openssl` needs to be compiled with the `enable-md2` flag. Or there may be a way to disable the `md2` part in `rpm`, but I saw no flag that could help for that.

**Comment by sjackman** [comment]
There's not really any harm in adding `enable-md2` to `openssl`. I'd be okay with that, but I don't feel strongly either way. It's probably the only way to get `rpm` to build, other than to vendor `openssl` into `rpm`, which feels like overkill. Disabling `md2` in `rpm` would be better if that's possible. If MD2 is part of the `rpm` package format, it may not be possible.

**Comment by iMichka** [comment]
I rebuilt openssl with md2 and rebased this pull request on master.

**Comment by sjackman** [comment]
It (nearly) worked!

```
failed: brew install ./rpm--4.14.1_1.x86_64_linux.bottle.tar.gz
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall rpm`
==> An exception occurred within a child process:
  Utils::InreplaceError: inreplace failed
/home/linuxbrew/.linuxbrew/Cellar/rpm/4.14.1_1/lib/rpm/macros:
  expected replacement of "/usr/bin/gpg2" with #<Pathname:/home/linuxbrew/.linuxbrew/bin/gpg>
```
https://circleci.com/gh/Linuxbrew/homebrew-core/23145

```diff
  def post_install
    (var/"lib/rpm").mkpath

    # Attempt to fix expected location of GPG to a sane default.
-    inreplace lib/"rpm/macros", "/usr/bin/gpg2", HOMEBREW_PREFIX/"bin/gpg"
+    inreplace lib/"rpm/macros", "/usr/bin/gpg2", HOMEBREW_PREFIX/"bin/gpg" if OS.mac?
  end
```

**Pull request closed without merging**
