### PR TITLE
ocaml: Use xorg dep instead of X11 for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by maelvalais** [comment]
Hi,
Right after this commit, my linux [Travis CI setup broke](https://travis-ci.org/touist/homebrew-touist/jobs/337677011). During `brew test-bot` for a formula (`touist`) that requires `ocaml`, it fails at some point saying:
```
Error: No available formula with the name "linuxbrew/xorg/xorg" 
Please tap it and then try again: brew tap linuxbrew/xorg
```
It happens right after `brew uses --recursive touist/touist/touist` is done.

I have no idea on how to fix that :(

**Comment by maelvalais** [comment]
I just stumbled upon a two-years-old commit (https://github.com/Linuxbrew/homebrew-core/commit/912f80e770de75eac722350fd9e8d197e8b79622) from @sjackman that says

> .travis.yml: Tap linuxbrew/xorg for Linuxbrew
>
> Work around
> Error: No available formula with the name "linuxbrew/xorg/xorg"

I guess I also need to add `brew tap linuxbrew/xorg`. But why was it working fine util now?

Btw, isn't it weird that `xorg` is mandatory although `x11` is optional? 🙄 Maybe it should read:
```ruby
    depends_on "linuxbrew/xorg/xorg" if build.with?("x11") && !OS.mac?
```

**Comment by iMichka** [comment]
Hi. You are right, I made a mistake here. It is optional, so it should stay optional on Linux too. Would you like to submit a pull request with that change?

**Comment by maelvalais** [comment]
Sure! 😀 Here is the PR: https://github.com/Linuxbrew/homebrew-core/pull/5967

**Pull request closed without merging**
