### PR TITLE
agda: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
```
checking version of ghc... 7.8.4
configure: error: GHC version 7.10 or later is required to compile GHC.
```

**Comment by sjackman** [comment]
`ghc` is at version 8.2.1. Is the host `ghc` being picked up?

**Comment by maxim-belkin** [comment]
No, ghc formula has to be updated:
```
==> Verifying ghc--gmp-6.1.2.tar.xz checksum
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/ghc/8.2.1/libexec/integer-gmp --with-pic --disable-shared
.
==> make
..
==> make check
..
==> make install
.
==> Downloading https://downloads.haskell.org/~ghc/7.8.4/ghc-7.8.4-x86_64-unknown-linux-deb7.tar.xz
Already downloaded: /home/ubuntu/.cache/Homebrew/ghc--binary-7.tar.xz
```

**Comment by sjackman** [comment]
Ah, in the `ghc` formula we're trying to bootstrap ghc 8.2.1 using a binary distribution of ghc 7.8.4, which isn't working. So the `ghc` formula is broken.

**Comment by sjackman** [comment]
I've opened PR https://github.com/Linuxbrew/homebrew-core/pull/3738 to try to fix `ghc`.
Blocked by `ghc` #3738.

**Comment by sjackman** [comment]
I've bottled `ghc`. Can you please rebase this onto `master`?

**Comment by iMichka** [comment]
Rebased

**Comment by iMichka** [comment]
```
==> brew install --build-bottle --verbose agda
==> Cloning https://github.com/agda/agda.git
Updating /home/linuxbrew/.cache/Homebrew/agda--git
git config remote.origin.url https://github.com/agda/agda.git
git config remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
==> Checking out revision e3f598313ceac6de8903f9e5693efb30435691fc
git checkout -f e3f598313ceac6de8903f9e5693efb30435691fc --
HEAD is now at e3f598313... [ user manual ] move record update (fixes #2665)
git reset --hard e3f598313ceac6de8903f9e5693efb30435691fc
HEAD is now at e3f598313 [ user manual ] move record update (fixes #2665)
git submodule foreach --recursive git submodule sync
Entering 'std-lib'
git submodule update --init --recursive
==> cabal sandbox init
.
==> cabal update
.
==> cabal install --jobs=36 --max-backjumps=100000 alex
.
==> cabal install --jobs=36 --max-backjumps=100000 happy
.
==> cabal install --jobs=36 --max-backjumps=100000 cpphs
..
==> cabal install --jobs=36 --max-backjumps=100000 --only-dependencies
...
==> cabal install --jobs=36 --max-backjumps=100000 --prefix=/home/linuxbrew/.linuxbrew/Cellar/agda/2.5.3-alpha1
.==> git checkout pull/3733 -f
Already on 'pull/3733'
Too long with no output (exceeded 10m0s)
```

**Comment by iMichka** [comment]
There will be a `agda` update in the next core merge, so maybe this PR will not be needed (#4128)

**Comment by iMichka** [comment]
Rebased

**Pull request closed without merging**
