### PR TITLE
htmlcleaner: build fails with JDK < 8

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by rwhogg** [comment]
From 

> [ERROR] javadoc: error - invalid flag: -Xdoclint:none

I had this problem too. It depends on Java 8+.

**Comment by rwhogg** [comment]
The upstream says it supports Java 1.5+, so it seems silly to ask for a Java 1.8 dependency just because of a screwy JavaDoc flag.

I think I'll file a bug upstream with this to see what they think about it.

**Comment by rwhogg** [comment]
Issue filed; it's https://sourceforge.net/p/htmlcleaner/bugs/174/

**Comment by rwhogg** [comment]
I added the JDK 8 dependency to Mac Homebrew, which has since been merged into Linuxbrew. Going to try this again.

**Comment by rwhogg** [comment]
It still fails. Unassigning myself.

**Comment by maxim-belkin** [comment]
#2362

**Pull request closed without merging**
