### PR TITLE
nginx: Adding --with-stream option

### PR DESCRIPTION
**Pull request by nitinbansal1989**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by rwhogg** [comment]
Hey @nitinbansal1989, thanks for contributing :smile: 

Is the `--with-stream` option supported on macOS? If so, can you send this PR upstream to Homebrew?

Thanks a bunch!

**Comment by nitinbansal1989** [comment]
@rwhogg "--with-stream" is also supported in mac.

**Comment by rwhogg** [comment]
> @rwhogg "--with-stream" is also supported in mac.

Cool! Can you send this PR upstream then? If you need help, we're happy to assist with that process.

**Comment by nitinbansal1989** [comment]
Sry but i am a little noob at git. Can you send me a link on how to file any upstream request. Thanks

**Comment by rwhogg** [comment]
You may wish to read https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md , but that doesn't assume that you've already forked Linuxbrew. So here's what I'd recommend:

```bash
$ cd <your homebrew-core directory>
$ git remote add mac https://github.com/homebrew/homebrew-core
$ git fetch mac
$ git checkout mac/master -b mac-master
$ git checkout -b nginx-add-with-stream
$ git cherry-pick 615d546abfdb3986492a552bdc355c10f02c40d0 # this is the commit you already made for this pull request
$ git push origin nginx-add-with-stream
```

From there, you can make a PR against homebrew/homebrew-core instead of against linuxbrew/homebrew-core.

Feel free to ping me again if you need any more guidance!

**Comment by rwhogg** [comment]
The provided option is already available in `homebrew/nginx/nginx-full`. While that's not a supported tap of Linuxbrew, you are certainly welcome to use that formula.

My apologies that it took me until now to realize this.

**Comment by nitinbansal1989** [comment]
No issue, thanks.

**Pull request closed without merging**
