### PR TITLE
texlive: fix SHA256

### PR DESCRIPTION
**Pull request by maxim-belkin**
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?

-----
before the fix:
```
$ brew install texlive
==> Downloading http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
==> Downloading from http://ctan.sharelatex.com/tex-archive/systems/texlive/tlnet/install-tl-unx.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 65e94212bf3fa63639ea929e6368ee248bf8904ea53d04566431e33ce4f173f6
Actual: 216829f4e5346694654b27d4607fcd7591831ff642d94753916e87ecb18a2885
```
after the fix installation proceeds just fine

### CODE REVIEW

**Comment by maxim-belkin** [comment]
I should've posted it to Homebrew instead. Closing this one

**Comment by rwhogg** [comment]
@maxim-belkin this is Linuxbrew-only, I think here is the appropriate place

**Comment by maxim-belkin** [comment]
ok, thanks! :)

**Comment by rwhogg** [comment]
@maxim-belkin, any idea why the SHA is wrong on this one?

**Comment by maxim-belkin** [comment]
from [here](http://ctan.sharelatex.com/tex-archive/systems/texlive/tlnet/): installation script (`install-tl-unx.tar.gz`) was updated yesterday (12-Sep-2016 01:17)

**Comment by rwhogg** [comment]
Travis failure is an audit problem:

```
texlive:
  * Non-executables were installed to "/home/linuxbrew/.linuxbrew/Cellar/texlive/20160605/bin"
    The offending files are:
      /home/linuxbrew/.linuxbrew/Cellar/texlive/20160605/bin/x86_64-linux
```

Circle CI failed for no reason, so I've restarted the build there.

IMO, we should think about mirroring the `texlive` URL if we can't either find one that's constant across versions.

**Comment by sjackman** [comment]
> IMO, we should think about mirroring the texlive URL if we can't find one that doesn't change when a new version is released.

:+1:

**Pull request closed without merging**
