### PR TITLE
consul: Build a bottle for Linuxbrew: test failed

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by rwhogg** [comment]
Circle failed:

```
==> Summary
/home/linuxbrew/.linuxbrew/Cellar/consul/0.8.0: 4 files, 34.4MB
==> brew linkage consul
==> brew linkage --test consul
No broken dylib links
==> brew test consul --verbose
Testing consul
==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
==> Starting Consul agent...
==> Error starting agent: Failed to get advertise address: Multiple private IPs found. Please configure one.
==> /home/linuxbrew/.linuxbrew/Cellar/consul/0.8.0/bin/consul info
.
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/consul/test.01.consul:
2017-04-10 04:10:18 +0000

/home/linuxbrew/.linuxbrew/Cellar/consul/0.8.0/bin/consul
info

Error querying agent: Get http://127.0.0.1:8500/v1/agent/self: dial tcp 127.0.0.1:8500: getsockopt: connection refused
Error: consul: failed
Failed executing: /home/linuxbrew/.linuxbrew/Cellar/consul/0.8.0/bin/consul info
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1836:in `block in system'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1774:in `open'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1774:in `system'
/home/linuxbrew/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/consul.rb:93:in `block in <class:Consul>'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1673:in `block (2 levels) in run_test'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:884:in `with_logging'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1672:in `block in run_test'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1666:in `run_test'
/home/linuxbrew/.linuxbrew/Library/Homebrew/test.rb:33:in `block in <main>'
/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/home/linuxbrew/.linuxbrew/Library/Homebrew/test.rb:32:in `<main>'
```

**Comment by sjackman** [comment]
`Error starting agent: Failed to get advertise address: Multiple private IPs found. Please configure one.`
It passed on TravisCI. Looks like the test needs to be fixed up for CircleCI.

**Comment by DoomHammer** [comment]
Maybe specifying an arbitrary interface (like loopback) might be a good solution here?

**Comment by sjackman** [comment]
Works for me.

**Pull request closed without merging**
