### PR TITLE
postgresql: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
failed: brew install --verbose --build-bottle postgresql

        ==> Downloading https://ftp.postgresql.org/pub/source/v10.5/postgresql-10.5.tar.bz2
Already downloaded: /home/linuxbrew/.cache/Homebrew/downloads/6be9a18f8e978b9f30f3595ffb8d54f13fb2a328495066c8a2bc53641d68ed02--postgresql-10.5.tar.bz2
==> Verifying 6be9a18f8e978b9f30f3595ffb8d54f13fb2a328495066c8a2bc53641d68ed02--postgresql-10.5.tar.bz2 checksum
tar xf /home/linuxbrew/.cache/Homebrew/downloads/6be9a18f8e978b9f30f3595ffb8d54f13fb2a328495066c8a2bc53641d68ed02--postgresql-10.5.tar.bz2 -C /tmp/d20181205-34066-1x75dh4
cp -pR /tmp/d20181205-34066-1x75dh4/postgresql-10.5/. /tmp/postgresql-20181205-34066-1i4scez/postgresql-10.5
chmod -Rf +w /tmp/d20181205-34066-1x75dh4
Error: An exception occurred within a child process:
  NameError: uninitialized constant OS::Mac::CLT
```

```
failed: brew style postgresql

        == /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/postgresql.rb ==
C: 56:  5: Style/MultilineIfModifier: Favor a normal if-statement over a modifier clause in a multiline statement.

1 file inspected, 1 offense detected
```

**Comment by iMichka** [comment]
```
==> brew style postgresql
== /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/postgresql.rb ==
C: 72:  5: Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.
C: 73:  7: Layout/IndentationWidth: Use 2 (not -2) spaces for indentation.
C: 74:  9: Layout/IndentationConsistency: Inconsistent indentation detected.
W: 77:  7: Layout/EndAlignment: end at 77, 6 is not aligned with if MacOS.version >= :mavericks || MacOS::CLT.installed? at 72, 8.
```

**Comment by black-snow** [comment]
@iMichka I'm getting this now:

> Error: An exception occurred within a child process:
  NoMethodError: undefined method `sdk_path' for OS::Mac:Module

for v10.6/postgresql-10.6.tar.bz2

**Comment by iMichka** [comment]
@black-snow fixed!

**Comment by black-snow** [comment]
Awesome! Have all my thumbs

**Comment by JuPlutonic** [comment]
@iMichka I found out, what actually postgresql@10 can't be installed.
```
Error: An exception occurred within a child process:
NoMethodError: undefined method `sdk_path' for OS::Mac:Module
```
https://gist.github.com/JuPlutonic/276003eb125a46527dad70624534dade
===
Mention last merge: https://github.com/Linuxbrew/homebrew-core/pull/10726/commits/8cb61a78ab386e74eb54c0a54bcd5620605dcb30
===
After upgrade to postgresql 11. I need to run `brew postgresql-upgrade-database`
what actually installs postgresql"10

**Pull request closed without merging**
