### PR TITLE
ghc: Error: undefined method `>=' for nil:NilClass

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
==> brew install ./ghc-7.10.3b.x86_64_linux.bottle.2.tar.gz
==> Pouring ghc-7.10.3b.x86_64_linux.bottle.2.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/ghc/7.10.3b/bin/ghc-pkg recache
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/ghc/01.ghc-pkg:
2016-05-11 19:15:25 +0000

/home/linuxbrew/.linuxbrew/Cellar/ghc/7.10.3b/bin/ghc-pkg
recache

/home/linuxbrew/.linuxbrew/Cellar/ghc/7.10.3b/lib/ghc-7.10.3/bin/ghc-pkg: error while loading shared libraries: libncursesw.so.6: cannot open shared object file: No such file or directory
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall ghc`
==> Summary
/home/linuxbrew/.linuxbrew/Cellar/ghc/7.10.3b: 5,444 files, 945.6M
==> FAILED
```

```
==> brew test ghc --verbose
Testing ghc
==> /home/linuxbrew/.linuxbrew/Cellar/ghc/7.10.3b/bin/runghc /tmp/ghc-test-20160511-66051-7k9a0c/hello.hs
.
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/ghc/01.runghc:
2016-05-11 19:15:27 +0000

/home/linuxbrew/.linuxbrew/Cellar/ghc/7.10.3b/bin/runghc
/tmp/ghc-test-20160511-66051-7k9a0c/hello.hs

/home/linuxbrew/.linuxbrew/Cellar/ghc/7.10.3b/lib/ghc-7.10.3/bin/runghc: error while loading shared libraries: libHSprocess-1.2.3.0-52AgREEfSrnJLlkGV9YZZJ-ghc7.10.3.so: cannot open shared object file: No such file or directory
Error: ghc: failed
Failed executing: /home/linuxbrew/.linuxbrew/Cellar/ghc/7.10.3b/bin/runghc /tmp/ghc-test-20160511-66051-7k9a0c/hello.hs
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1495:in `block in system'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1432:in `open'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1432:in `system'
/home/linuxbrew/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/ghc.rb:166:in `block in <class:Ghc>'
```

**Comment by sjackman** [comment]
```
ghc-pkg: error while loading shared libraries: libncursesw.so.6
```

```
  depends_on "homebrew/dupes/ncurses" => :build if OS.linux?
```

`ncurses` is a run-time dependency as well.

**Comment by sjackman** [comment]
```
runghc: error while loading shared libraries: libHSprocess-1.2.3.0-52AgREEfSrnJLlkGV9YZZJ-ghc7.10.3.so
```

Should have been fixed by Linuxbrew/brew#35.

**Comment by sjackman** [comment]
GHC uses `$ORIGIN` in its `RPATH`, which gets removed by `change_rpath`.
```
patchelf --print-rpath /home/sjackman/.linuxbrew/Cellar/ghc/7.10.3b/lib/ghc-7.10.3/bin/runghc
/home/sjackman/.linuxbrew/lib:$ORIGIN/../proce_52AgREEfSrnJLlkGV9YZZJ:$ORIGIN/../direc_0hFG6ZxK1nk4zsyOqbNHfm:$ORIGIN/../unix_KZL8h98IqDM57kQSPo1mKx:$ORIGIN/../time_FTheb6LSxyX1UABIbBXRfn:$ORIGIN/../filep_Ey7a1in9roBAE8bUFJ5R9m:$ORIGIN/../bytes_6VWy06pWzJq9evDvK2d4w6:$ORIGIN/../deeps_6vMKxt5sPFR0XsbRWvvq59:$ORIGIN/../array_67iodizgJQIIxYVTp4emlA:$ORIGIN/../base_HQfYBxpPvuw8OunzQu6JGM:$ORIGIN/../integ_2aU3IZNMF9a7mQ0OzsZ0dS:$ORIGIN/../ghcpr_8TmvWUcS1U1IKHT0levwg3:$ORIGIN/../rts
```

**Comment by sjackman** [comment]
Fixed the above errors with an upcoming fix to `change_rpath`.

**Comment by sjackman** [comment]
```
$ brew test ghc
Testing ghc
==> /home/sjackman/.linuxbrew/Cellar/ghc/7.10.3b/bin/runghc /var/tmp/sjackman/g
Last 15 lines from /home/sjackman/.cache/Homebrew/Logs/ghc/01.runghc:
2016-05-11 15:22:14 -0700

/home/sjackman/.linuxbrew/Cellar/ghc/7.10.3b/bin/runghc
/var/tmp/sjackman/ghc-test-20160511-10444-z0jn1l/hello.hs

ghc: /home/sjackman/.linuxbrew/Cellar/ghc/7.10.3b/libexec/integer-gmp/lib/libgmp.a: unhandled ELF relocation(RelA) type 42

ghc: unable to load package `integer-gmp-1.0.0.0'
Error: ghc: failed
Failed executing: /home/sjackman/.linuxbrew/Cellar/ghc/7.10.3b/bin/runghc /var/tmp/sjackman/ghc-test-20160511-10444-z0jn1l/hello.hs
```

**Comment by sjackman** [comment]
This error has been seen over here:
https://github.com/DanielG/ghc-mod/issues/762#issuecomment-213743585

**Comment by DanielG** [comment]
This is a bug in GHCi's dynamic loader you should report it with GHC HQ if you can reproduce it reliably on your system.

**Comment by sjackman** [comment]
`Your build has exceeded the memory limit of 4G`

**Pull request closed without merging**
