### PR TITLE
hub: test fails

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by sjackman** [comment]
The relevant error is actually this `patchelf` error: `cannot find section`. It looks like `patchelf` fails on `go` executables.

**Comment by DoomHammer** [comment]
Same as #149 . #352 will hopefully fix this.

**Comment by rwhogg** [comment]
From https://travis-ci.org/Linuxbrew/homebrew-core/builds/159768428#L1648-L1656

```
*** Please tell me who you are.
Run
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
```

This is the exact same failure from #908 (and #777 before it). Once `git` is bottled, I'll rebuild this and fix the test the exact same way if necessary.

**Comment by sjackman** [comment]
`git` is bottled. I triggered a rebuild on Travis.

**Comment by rwhogg** [comment]
Thanks! I've actually been thinking we should fix this in `brew` though, and indeed I have a branch on my local machine that reverts that change to the Git test.

It already has code to set up a dummy Git identity before running `brew tests` (Martin showed me some of it). I've been thinking we should do the same for `brew test`. I held off at least in part because there was a PR open at the time upstream that refactored some of that code - which one it is, I don't remember at the moment.

**Comment by sjackman** [comment]
The test for `hub` needs to be fixed I think. It shouldn't assume that the user has configured git `user.name` and `user.email`. There's no reason to expect that they should have.

Why doesn't this test fail on Mac? I deleted `user.name` and `user.email` from my `.gitconfig`, ran `brew test hub`, and it worked!? 😖

**Comment by rwhogg** [comment]
> Why doesn't this test fail on Mac? I deleted user.name and user.email from my .gitconfig, ran brew test hub, and it worked!? 😖

Git attempts to automatically configure a name and email based on various information from the system if you haven't configured it yourself. For example, running on https://github.com/rwhogg/homebrew-travis-debug gives `fatal: empty ident name (for <linuxbrew@f0e886a59b85.(none)>) not allowed` since `hostname` gives `f0e886a59b85` and doesn't provide a TLD.

So whether this is reproducible depends not on operating system, but on per-system configuration.

I'd argue that this is a bug in Git; there's no reason email addresses have to have a TLD in them.

**Comment by sjackman** [comment]
The simplest workaround is to set `user.name` and `user.email` in `test do`, so that it doesn't depend on the system configuration.

**Comment by rwhogg** [comment]
> The simplest workaround is to set user.name and user.email in test do, so that it doesn't depend on the system configuration.

Agreed, but IMO I should also submit a bug upstream to Git and link it in the PR. (I would have submitted it already, but [Gmane's web ui being down](https://github.com/git/git-scm.com/issues/859) slowed me down.)

**Comment by sjackman** [comment]
I can see an argument for both sides. If I were making a commit and had forgotten to configure my e-mail address, and `git` had guessed that my email address were `sjackman@f0e886a59b85`, I'd probably prefer getting an error message over that non-FQDN e-mail address ending up in the git commit log.

**Comment by rwhogg** [comment]
> I'd probably prefer getting an error message over that non-FQDN e-mail address ending up in the git commit log.

Good point.

I think that for now, I'll just fix the test and get on with my life. Once Gmane's web UI starts working again or I figure out a different way to submit bugs, I'll try to do that, but it's not the end of the world if the bug URL doesn't show up in a comment. By contrast, the sooner the bottle, the better.

**Pull request closed without merging**
