### PR TITLE
pango: Add missing Xorg dependencies

### PR DESCRIPTION
**Pull request by dholm**

### CODE REVIEW

**Comment by sjackman** [comment]
`depends_on :x11` should pull in all of those dependencies, which should not be necessary.
@maxim-belkin ?

**Comment by dholm** [comment]
It fails for me without this change.

https://gist.github.com/dholm/4d10cece726816846a988c6d29199b92

**Comment by sjackman** [comment]
```
libtool: link: ( cd ".libs" && rm -f "libpangoft2-1.0.la" && ln -s "../libpangoft2-1.0.la" "libpangoft2-1.0.la" )
Package xproto was not found in the pkg-config search path.
Perhaps you should add the directory containing `xproto.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xproto', required by 'xau', not found
pango-engine.h:300: Warning: Pango: symbol='script_engine_list': Unknown namespace for symbol 'script_engine_list'
pango-engine.h:313: Warning: Pango: symbol='script_engine_init': Unknown namespace for symbol 'script_engine_init'
pango-engine.h:324: Warning: Pango: symbol='script_engine_exit': Unknown namespace for symbol 'script_engine_exit'
pango-engine.h:335: Warning: Pango: symbol='script_engine_create': Unknown namespace for symbol 'script_engine_create'
Package xproto was not found in the pkg-config search path.
Perhaps you should add the directory containing `xproto.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xproto', required by 'xau', not found
/tmp/pango-20170516-591362-aq82om/pango-1.40.5/pango/tmp-introspect1_Kk8d/Pango-1.0.c:2:18: fatal error: glib.h: No such file or directory
 #include <glib.h>
```
https://gist.githubusercontent.com/dholm/4d10cece726816846a988c6d29199b92/raw/b514149b91a0667c1505d3d6a1af25f759eec9eb/02.make

**Comment by dholm** [comment]
Hmm, ok, looks like they messed the OS installation on our hosts. They have installed dev packages for xau but not with its dependencies (like xproto). :(

**Comment by sjackman** [comment]
Linuxbrew `:x11` shouldn't depend on the host libraries, but perhaps that's confusing this issue.

**Pull request closed without merging**
