### PR TITLE
aurora-cli: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
```
gcc-4.8 -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c src/kerberos.c -o build/temp.linux-x86_64-2.7/src/kerberos.o

stderr:
In file included from src/kerberos.c:19:0:
src/kerberosbasic.h:17:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
error: command 'gcc-4.8' failed with exit status 1
```

**Comment by sjackman** [comment]
`gssapi/gssapi.h` is provided by `krb5`.

**Comment by maxim-belkin** [comment]
> `gssapi/gssapi.h` is provided by `krb5`.

hence the PR.

I will rebase this on top of the latest brew to see if changes to `gcc` fix the problem.

**Comment by maxim-belkin** [comment]
```
tderr:
_posixsubprocess.c:3:20: fatal error: Python.h: No such file or directory
 #include "Python.h"
                    ^
compilation terminated.
error: command 'gcc-4.8' failed with exit status 1
```
depends on Python for Linuxbrew? :)

**Comment by maxim-belkin** [comment]
from a local test:
```
stderr:
c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
compilation terminated.
error: command 'gcc-5' failed with exit status 1
```

**Comment by maxim-belkin** [comment]
so, might need `libffi` as well

**Comment by sjackman** [comment]
> hence the PR.

Sorry. 🤗 I missed that you had already addressed it in the Pr.

**Pull request closed without merging**
