### PR TITLE
pango: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
/tmp/pango-20180316-30196-v2ntx4/pango-1.42.0/pango/tmp-introspectNEiANs/Pango-1.0.c:2:18: fatal error: glib.h: No such file or directory
compilation terminated.
```

**Comment by sjackman** [comment]
```
brew list glib | grep glib.h
/home/sjackman/.linuxbrew/Cellar/glib/2.54.3/include/glib-2.0/glib.h
```
Perhaps `pango` is not looking inside that `glib-2.0` subfolder.

**Comment by sjackman** [comment]
```
libtool: link: ranlib .libs/libpangoft2-1.0.a
/tmp/pango-20180322-23403-1y1awev/pango-1.42.0/pango/tmp-introspectvpCVP6/Pango-1.0.c:2:18: fatal error: glib.h: No such file or directory
compilation terminated.
```
That command is a linker command, and the following error is a compiler error, so these lines are out of order, which makes it tricky to troubleshoot. `ENV.deparallelize` would make the log easier to interpret and troubleshoot.

**Comment by iMichka** [comment]
```
libtool: link:  gcc-5 -shared  -fPIC -DPIC  .libs/pangofc-font.o .libs/pangofc-fontmap.o .libs/pangofc-decoder.o .libs/pangofc-shape.o .libs/pangoft2.o .libs/pangoft2-fontmap.o .libs/pangoft2-render.o .libs/pango-ot-buffer.o .libs/pango-ot-info.o .libs/pango-ot-ruleset.o .libs/pango-ot-tag.o   -Wl,-rpath -Wl,/tmp/pango-20180323-23394-1s8mhtf/pango-1.42.0/pango/.libs -Wl,-rpath -Wl,/home/linuxbrew/.linuxbrew/Cellar/pango/1.42.0_1/lib ./.libs/libpango-1.0.so -L/home/linuxbrew/.linuxbrew/Cellar/glib/2.56.0/lib -L/home/linuxbrew/.linuxbrew/Cellar/fribidi/1.0.1/lib -lfribidi -lgobject-2.0 -lgthread-2.0 -lglib-2.0 -L/home/linuxbrew/.linuxbrew/Cellar/harfbuzz/1.7.6/lib -lharfbuzz -L/home/linuxbrew/.linuxbrew/opt/freetype/lib -L/home/linuxbrew/.linuxbrew/Cellar/fontconfig/2.12.6/lib -lfontconfig -lfreetype -lm  -g -O2 -Wl,-Bsymbolic-functions -pthread   -pthread -Wl,-soname -Wl,libpangoft2-1.0.so.0 -Wl,-version-script -Wl,.libs/libpangoft2-1.0.ver -o .libs/libpangoft2-1.0.so.0.4200.0
libtool: link: (cd ".libs" && rm -f "libpangoft2-1.0.so.0" && ln -s "libpangoft2-1.0.so.0.4200.0" "libpangoft2-1.0.so.0")
libtool: link: (cd ".libs" && rm -f "libpangoft2-1.0.so" && ln -s "libpangoft2-1.0.so.0.4200.0" "libpangoft2-1.0.so")
libtool: link: ar cru .libs/libpangoft2-1.0.a  pangofc-font.o pangofc-fontmap.o pangofc-decoder.o pangofc-shape.o pangoft2.o pangoft2-fontmap.o pangoft2-render.o pango-ot-buffer.o pango-ot-info.o pango-ot-ruleset.o pango-ot-tag.o
ar: `u' modifier ignored since `D' is the default (see `U')
libtool: link: ranlib .libs/libpangoft2-1.0.a
libtool: link: ( cd ".libs" && rm -f "libpangoft2-1.0.la" && ln -s "../libpangoft2-1.0.la" "libpangoft2-1.0.la" )
CPPFLAGS="" CFLAGS="-g -O2 -Wall" LDFLAGS="" CC="gcc-5" PKG_CONFIG="/home/linuxbrew/.linuxbrew/opt/pkg-config/bin/pkg-config" GI_HOST_OS="" DLLTOOL="dlltool" CC="gcc-5" /home/linuxbrew/.linuxbrew/Cellar/gobject-introspection/1.56.0/bin/g-ir-scanner  --warn-all --add-include-path=. --add-include-path=. --namespace=Pango --nsversion=1.0 --libtool="/bin/bash ../libtool" --pkg=gobject-2.0 --pkg=cairo --pkg=glib-2.0 --include=GObject-2.0 --include=cairo-1.0 --pkg-export=pango   --library=libpango-1.0.la --c-include "pango/pango.h" --cflags-begin -I.. -I.. -DG_LOG_DOMAIN=\"Pango\" -DPANGO_COMPILATION -DPANGO_ENABLE_BACKEND -DPANGO_ENABLE_ENGINE -DSYSCONFDIR=\"/home/linuxbrew/.linuxbrew/Cellar/pango/1.42.0_1/etc\" -DLIBDIR=\"/home/linuxbrew/.linuxbrew/Cellar/pango/1.42.0_1/lib\" -I.. -I.. -DG_DISABLE_CAST_CHECKS -pthread -I/home/linuxbrew/.linuxbrew/Cellar/pcre/8.42/include -I/home/linuxbrew/.linuxbrew/Cellar/glib/2.56.0/include/glib-2.0 -I/home/linuxbrew/.linuxbrew/Cellar/glib/2.56.0/lib/glib-2.0/include   -I/home/linuxbrew/.linuxbrew/Cellar/pcre/8.42/include -I/home/linuxbrew/.linuxbrew/Cellar/glib/2.56.0/include/glib-2.0 -I/home/linuxbrew/.linuxbrew/Cellar/glib/2.56.0/lib/glib-2.0/include -I/home/linuxbrew/.linuxbrew/Cellar/graphite2/1.3.10/include -I/home/linuxbrew/.linuxbrew/Cellar/harfbuzz/1.7.6/include/harfbuzz -I/home/linuxbrew/.linuxbrew/opt/freetype/include/freetype2 -I/home/linuxbrew/.linuxbrew/opt/freetype/include/freetype2 -I/home/linuxbrew/.linuxbrew/Cellar/expat/2.2.5/include -I/home/linuxbrew/.linuxbrew/Cellar/fontconfig/2.12.6/include -I/home/linuxbrew/.linuxbrew/Cellar/expat/2.2.4/include -I/home/linuxbrew/.linuxbrew/opt/freetype/include/freetype2 -I/home/linuxbrew/.linuxbrew/Cellar/fribidi/1.0.1/include/fribidi   -fvisibility=hidden --cflags-end  break.c ellipsize.c fonts.c glyphstring.c modules.c pango-attributes.c pango-bidi-type.c pango-color.c pango-context.c pango-coverage.c pango-emoji.c pango-emoji-table.h pango-engine.c pango-fontmap.c pango-fontset.c pango-glyph-item.c pango-gravity.c pango-impl-utils.h pango-item.c pango-language.c pango-language-sample-table.h pango-layout.c pango-markup.c pango-matrix.c pango-renderer.c pango-script.c pango-script-lang-table.h pango-tabs.c pango-utils.c pango-utils-internal.h reorder-items.c shape.c pango-enum-types.c pango.h pango-attributes.h pango-bidi-type.h pango-break.h pango-context.h pango-coverage.h pango-engine.h pango-font.h pango-fontmap.h pango-fontset.h pango-glyph.h pango-glyph-item.h pango-gravity.h pango-item.h pango-language.h pango-layout.h pango-matrix.h pango-modules.h pango-renderer.h pango-script.h pango-tabs.h pango-types.h pango-utils.h pango-version-macros.h pango-enum-types.h libpango-1.0.la --output Pango-1.0.gir
Package renderproto was not found in the pkg-config search path.
Perhaps you should add the directory containing `renderproto.pc'
to the PKG_CONFIG_PATH environment variable
Package 'renderproto', required by 'xrender', not found
pango-engine.h:300: Warning: Pango: symbol='script_engine_list': Unknown namespace for symbol 'script_engine_list'
pango-engine.h:313: Warning: Pango: symbol='script_engine_init': Unknown namespace for symbol 'script_engine_init'
pango-engine.h:324: Warning: Pango: symbol='script_engine_exit': Unknown namespace for symbol 'script_engine_exit'
pango-engine.h:335: Warning: Pango: symbol='script_engine_create': Unknown namespace for symbol 'script_engine_create'
pango-version-macros.h:287: Warning: Pango: Unknown namespace for identifier 'Interval'
Package renderproto was not found in the pkg-config search path.
Perhaps you should add the directory containing `renderproto.pc'
to the PKG_CONFIG_PATH environment variable
Package 'renderproto', required by 'xrender', not found
/tmp/pango-20180323-23394-1s8mhtf/pango-1.42.0/pango/tmp-introspectCcLxUC/Pango-1.0.c:2:18: fatal error: glib.h: No such file or directory
```

**Comment by sjackman** [comment]
```
-I/home/linuxbrew/.linuxbrew/Cellar/glib/2.56.0/include/glib-2.0
```
```
$ wc /home/linuxbrew/.linuxbrew/Cellar/glib/2.56.0/include/glib-2.0/glib.h
 115  354 3361 /home/linuxbrew/.linuxbrew/Cellar/glib/2.56.0/include/glib-2.0/glib.h
```
Mysterious…

**Comment by iMichka** [comment]
```
pkg-config --cflags glib-2.0
-I/home/linuxbrew/.linuxbrew/Cellar/glib/2.56.0/include/glib-2.0 -I/home/linuxbrew/.linuxbrew/Cellar/glib/2.56.0/lib/glib-2.0/include -I/home/linuxbrew/.linuxbrew/Cellar/pcre/8.42/include
```

This looks OK

**Comment by iMichka** [comment]
Building pango 1.40 fails with the same error. This was working before and we had a bottle.

So there is probably a bug somewhere in brew?

**Comment by sjackman** [comment]
I'll need to troubleshoot it interactively.

**Comment by iMichka** [comment]
Fixed! The `glib.h` error was a red herring. Actually some packages were missing, and the script was telling it (by telling us that the `.pc` files were missing). Once I added everything it was fine.

Their error handling is quite bad ...

**Comment by sjackman** [comment]
Woohoo! Glad to hear it! Thanks, Michka! 💯

**Pull request closed without merging**
