### PR TITLE
node: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by rwhogg** [comment]
@iMichka, @maxim-belkin any idea what happened to 8a9ec61? The link above 404's, and locally the Node formula lacks a Linux bottle, but Bintray says that the Node 8.1.4 bottle was published yesterday.

**Comment by maxim-belkin** [comment]
that's weird

**Comment by maxim-belkin** [comment]
Here is the log in my docker container:
```
b4703bbb5f (HEAD -> master, origin/master, origin/HEAD, maxim-belkin/master) node@6: update 6.11.1 bottle for Linuxbrew. (34 hours ago) <Maxim Belkin>
8a9ec61831 node: update 8.1.4 bottle for Linuxbrew. (34 hours ago) <Maxim Belkin>
01c164f070 CONTRIBUTING: make more Linuxbrew-specific. (34 hours ago) <Mike McQuaid>
33b2b38171 ISSUE_TEMPLATE: tweak Homebrew instructions. (34 hours ago) <Mike McQuaid>
34148c8597 README: remove Homebrew-specific things. (34 hours ago) <Mike McQuaid>
00ef67227d mpg123: update 1.25.2 bottle for Linuxbrew. (2 days ago) <Michka Popoff>
5f36b47673 node@4: update 4.8.4 bottle for Linuxbrew. (2 days ago) <Michka Popoff>
564f27c998 Merge branch homebrew/master into linuxbrew/master (2 days ago) <Michka Popoff>
```

**Comment by maxim-belkin** [comment]
Somehow, they no longer show up in the [commit history](https://github.com/Linuxbrew/homebrew-core/commits/master). I can move them to a different branch and cherry-pick them after updating master

**Comment by maxim-belkin** [comment]
There was a forced update but that's not a problem:
```
$ git fetch origin master
remote: Counting objects: 362, done.
remote: Compressing objects: 100% (104/104), done.
remote: Total 362 (delta 275), reused 345 (delta 258), pack-reused 0
Receiving objects: 100% (362/362), 43.92 KiB | 0 bytes/s, done.
Resolving deltas: 100% (275/275), completed with 81 local objects.
From https://github.com/Linuxbrew/homebrew-core
 * branch                  master     -> FETCH_HEAD
 + b4703bbb5f...95013336ba master     -> origin/master  (forced update)
```

**Comment by maxim-belkin** [comment]
done

**Pull request closed without merging**
