### PR TITLE
stella: Fix build for Linux

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by rwhogg** [comment]
Stella's home page says it's multi-platform and runs on Linux, so while the build process would probably be extremely different I'm not sure if it's appropriate to mark this as `depends_on :macos`.

@sjackman thoughts on this?

**Comment by sjackman** [comment]
Yes, I agree with Bob. It looks like to build it on Linux you'd run `make` instead. If someone has the time and inclination to submit a PR to fix it, that'd be great. Otherwise I'd suggest adding a comment to this PR saying that `stella` could build on Linux were this formula modified, and then merge this PR.

**Comment by iMichka** [comment]
I'll give it a try, it's on my todo list :)

**Comment by iMichka** [comment]
Okay got it to build. But the test fails. Here is the output:

> Testing stella
==> /home/linuxbrew/.linuxbrew/Cellar/stella/5.0.1/bin/stella -help
Error: stella: failed
Expected /Stella version 5.0.1/ to match "ERROR: Couldn't load settings file\nERROR: Couldn't initialize SDL: No available video device\n\nERROR: Couldn't create OSystem\nERROR: Couldn't save settings file".

@sjackman any idea what the problem could be?

**Comment by sjackman** [comment]
`ERROR: Couldn't initialize SDL: No available video device`
That one may bet a bit tricky to fix, if CircleCI and TravisCI are headless. You'd need a fake X server, or some similar hack. It's possible but probably not worth the effort. I'd disable the test on CircleCI and TravisCI, and add a comment explaining why.

**Comment by iMichka** [comment]
I had the same error locally on my Ubuntu. I also thought it was a headless problem, but it seems not. I would just disable the test for Linux, add a comment, and if somebody wants to use that formula, they need to fix it. Is that fine for you?

**Comment by sjackman** [comment]
Yep, that works for me.

**Comment by iMichka** [comment]
> stella:
>  * File should end with a newline
>  * "#{prefix}/bin" should be "#{bin}"

**Pull request closed without merging**
