### PR TITLE
Merge 2017-09-06 d13188176b

### PR DESCRIPTION
**Pull request by iMichka**
+ [ ] libxml2

### CODE REVIEW

**Comment by iMichka** [comment]
`libxml2` will need to be built manually in a docker container.

**Comment by sjackman** [comment]
This PR built a bottle for libxml2 https://circleci.com/gh/Linuxbrew/homebrew-core/8820#artifacts/containers/0
There seems to be a bug with the CircleCI API.
https://circleci.com/api/v1.1/project/github/Linuxbrew/homebrew-core/latest/artifacts?branch=pull/4145
returns `{ "message" : "Build not found" }`
but https://circleci.com/api/v1.1/project/github/Linuxbrew/homebrew-core/8820/artifacts
returns the expected bottles (though with every bottle appearing twice, which seems to be a separate bug).

**Comment by sjackman** [comment]
I downloaded the two `libxml2` bottle files (.json and .tar.gz) from the web interface and then ran…
```sh
CIRCLE_PR_NUMBER=4145 linuxbrew test-bot --ci-upload
linuxbrew pull --bottle --clean 4145
```

**Comment by sjackman** [comment]
> Your build ran 745 tests with 23 failures

https://circleci.com/gh/Linuxbrew/homebrew-core/8820#tests/containers/0

😬

**Comment by sjackman** [comment]
I believe the revision of `gtkmm libxml++ libxml++3` need to be bumped for `gcc-5`

**Comment by iMichka** [comment]
```
==> brew test --verbose git-flow-avh
Testing git-flow-avh
==> git init
.
==> /home/linuxbrew/.linuxbrew/Cellar/git-flow-avh/1.11.0_1/bin/git-flow init -d
.
Last 150 lines from /home/linuxbrew/.cache/Homebrew/Logs/git-flow-avh/test.02.git-flow:
2017-09-06 21:46:03 +0000

/home/linuxbrew/.linuxbrew/Cellar/git-flow-avh/1.11.0_1/bin/git-flow
init
-d

Using default branch names.
No branches exist yet. Base branches must be created now.
Branch name for production releases: [master] 
Branch name for "next release" development: [develop] 

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <linuxbrew@414857ad0cb9.(none)>) not allowed
fatal: Not a valid object name: 'master'.
error: pathspec 'develop' did not match any file(s) known to git.
Fatal: Could not check out branch 'develop'.
Error: git-flow-avh: failed
Failed executing: /home/linuxbrew/.linuxbrew/Cellar/git-flow-avh/1.11.0_1/bin/git-flow init -d
```

```
-lxml2

/home/linuxbrew/.linuxbrew/Cellar/libxml++3/3.0.1/lib/libxml++-3.0.so: undefined reference to `Glib::ustring::rbegin()'
/home/linuxbrew/.linuxbrew/Cellar/libxml++3/3.0.1/lib/libxml++-3.0.so: undefined reference to `Glib::get_unichar_from_std_iterator(__gnu_cxx::__normal_iterator<char const*, std::string>)'
/home/linuxbrew/.linuxbrew/Cellar/libxml++3/3.0.1/lib/libxml++-3.0.so: undefined reference to `Glib::ustring::ustring(std::string const&)'
collect2: error: ld returned 1 exit status
Error: libxml++3: failed
```

```
The ICU library support cannot be enabled.
 Turn on verbose messaging (-v) to /tmp/phantomjs-20170906-19664-tmivxt/src/qt/qtbase/configure to see the final report.
 If you believe this message is in error you may use the continue
 switch (-continue) to /tmp/phantomjs-20170906-19664-tmivxt/src/qt/qtbase/configure to continue.

ERROR: Failed to build PhantomJS! Configuration of Qt Base failed.
Executing in /tmp/phantomjs-20170906-19664-tmivxt: git submodule init
Executing in /tmp/phantomjs-20170906-19664-tmivxt: git submodule update --init
configuring Qt Base, please wait...
Executing in /tmp/phantomjs-20170906-19664-tmivxt/src/qt/qtbase: /tmp/phantomjs-20170906-19664-tmivxt/src/qt/qtbase/configure -static -opensource -confirm-license -prefix /tmp/phantomjs-20170906-19664-tmivxt/src/qt/qtbase -qt-zlib -qt-libpng -qt-libjpeg -qt-pcre -nomake examples -nomake tools -nomake tests -no-qml-debug -no-dbus -no-opengl -no-audio-backend -D QT_NO_GRAPHICSVIEW -D QT_NO_GRAPHICSEFFECT -D QT_NO_STYLESHEET -D QT_NO_STYLE_CDE -D QT_NO_STYLE_CLEANLOOKS -D QT_NO_STYLE_MOTIF -D QT_NO_STYLE_PLASTIQUE -D QT_NO_PRINTPREVIEWDIALOG -qpa phantom -openssl -openssl-linked -no-openvg -no-eglfs -no-egl -no-glib -no-gtkstyle -no-cups -no-sm -no-xinerama -no-xkb -no-xcb -no-kms -no-linuxfb -no-directfb -no-mtdev -no-libudev -no-evdev -no-pulseaudio -no-alsa -no-feature-PRINTPREVIEWWIDGET -fontconfig -icu -release

==> Formula
Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/phantomjs.rb
```

```
In file included from /home/linuxbrew/.linuxbrew/Cellar/libxml++/2.40.1/include/libxml++-2.6/libxml++/libxml++.h:75:0,
                 from test.cpp:1:
/home/linuxbrew/.linuxbrew/Cellar/libxml++/2.40.1/include/libxml++-2.6/libxml++/validators/xsdvalidator.h:149:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<Impl> pimpl_;
        ^
In file included from /home/linuxbrew/.linuxbrew/Cellar/gcc/5.3.0/include/c++/5.3.0/memory:81:0,
                 from /home/linuxbrew/.linuxbrew/Cellar/libxml++/2.40.1/include/libxml++-2.6/libxml++/parsers/saxparser.h:14,
                 from /home/linuxbrew/.linuxbrew/Cellar/libxml++/2.40.1/include/libxml++-2.6/libxml++/libxml++.h:53,
                 from test.cpp:1:
/home/linuxbrew/.linuxbrew/Cellar/gcc/5.3.0/include/c++/5.3.0/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
/home/linuxbrew/.linuxbrew/Cellar/libxml++/2.40.1/lib/libxml++-2.6.so: undefined reference to `Glib::ustring::rbegin()'
/home/linuxbrew/.linuxbrew/Cellar/libxml++/2.40.1/lib/libxml++-2.6.so: undefined reference to `Glib::get_unichar_from_std_iterator(__gnu_cxx::__normal_iterator<char const*, std::string>)'
collect2: error: ld returned 1 exit status
Error: libxml++: failed
```

```
==> brew test --verbose libgit2-glib
Testing libgit2-glib
==> git init
.
==> /home/linuxbrew/.linuxbrew/Cellar/libgit2-glib/0.26.0/libexec/general /tmp/libgit2-glib-test-20170906-73821-swmca8/horatio
.
Last 150 lines from /home/linuxbrew/.cache/Homebrew/Logs/libgit2-glib/test.02.general:
2017-09-06 23:00:24 +0000

/home/linuxbrew/.linuxbrew/Cellar/libgit2-glib/0.26.0/libexec/general
/tmp/libgit2-glib-test-20170906-73821-swmca8/horatio

/home/linuxbrew/.linuxbrew/Cellar/libgit2-glib/0.26.0/libexec/general: line 202: cd: /tmp/libgit2-glib-20170802-37847-wxvcei/libgit2-glib-0.26.0/examples: No such file or directory
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/gcc-4.8:33:in `escape': no implicit conversion of nil into String (TypeError)
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/gcc-4.8:33:in `initialize'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/gcc-4.8:359:in `new'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/gcc-4.8:359:in `<main>'
Error: libgit2-glib: failed
Failed executing: /home/linuxbrew/.linuxbrew/Cellar/libgit2-glib/0.26.0/libexec/general /tmp/
```

```
==> brew test --verbose docbook2x
Testing docbook2x
==> /home/linuxbrew/.linuxbrew/Cellar/docbook2x/0.8.8_1/bin/docbook2man /tmp/docbook2x-test-20170906-77806-19wtckk/brew.1.xml
.
Last 150 lines from /home/linuxbrew/.cache/Homebrew/Logs/docbook2x/test.01.docbook2man:
2017-09-06 23:02:46 +0000

/home/linuxbrew/.linuxbrew/Cellar/docbook2x/0.8.8_1/bin/docbook2man
/tmp/docbook2x-test-20170906-77806-19wtckk/brew.1.xml

Can't locate XML/SAX/ParserFactory.pm in @INC (you may need to install the XML::SAX::ParserFactory module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /home/linuxbrew/.linuxbrew/Cellar/docbook2x/0.8.8_1/bin/db2x_manxml line 2413.
BEGIN failed--compilation aborted at /home/linuxbrew/.linuxbrew/Cellar/docbook2x/0.8.8_1/bin/db2x_manxml line 2413.
Error: docbook2x: failed
```

```
==> brew test --verbose pdf2htmlex
Testing pdf2htmlex
==> /home/linuxbrew/.linuxbrew/Cellar/pdf2htmlex/0.14.6_18/bin/pdf2htmlEX /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test/support/fixtures/test.pdf
.
Last 150 lines from /home/linuxbrew/.cache/Homebrew/Logs/pdf2htmlex/test.01.pdf2htmlEX:
2017-09-06 23:04:25 +0000

/home/linuxbrew/.linuxbrew/Cellar/pdf2htmlex/0.14.6_18/bin/pdf2htmlEX
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test/support/fixtures/test.pdf

/home/linuxbrew/.linuxbrew/Cellar/pdf2htmlex/0.14.6_18/bin/pdf2htmlEX: error while loading shared libraries: libpoppler.so.68: cannot open shared object file: No such file or directory
Error: pdf2htmlex: failed
```

```
==> brew test --verbose dwarf
Testing dwarf
==> /home/linuxbrew/.linuxbrew/bin/gcc-5 test.c -o test

==> /home/linuxbrew/.linuxbrew/Cellar/dwarf/0.3.2/bin/dwarf -c 'print $mac' test
Error: dwarf: failed
<"magic: 0xfeedfacf (-17958193)"> expected but was
<"unknown section.">.
==> FAILED
```

```
-lsigc-2.0

/home/linuxbrew/.linuxbrew/Cellar/gtkmm/2.24.5/lib/libgdkmm-2.4.so: undefined reference to `Glib::ustring::ustring(std::string&&)'
/home/linuxbrew/.linuxbrew/Cellar/gtkmm/2.24.5/lib/libgtkmm-2.4.so: undefined reference to `Glib::ustring::ustring(std::string const&)'
collect2: error: ld returned 1 exit status
Error: gtkmm: failed
```

```
==> brew test --verbose ldc
Testing ldc
==> /home/linuxbrew/.linuxbrew/Cellar/ldc/1.3.0/bin/ldc2 -flto=full test.d
.
Last 150 lines from /home/linuxbrew/.cache/Homebrew/Logs/ldc/test.01.ldc2:
2017-09-06 23:15:58 +0000

/home/linuxbrew/.linuxbrew/Cellar/ldc/1.3.0/bin/ldc2
-flto=full
test.d

Error: The LLVMgold.so plugin (needed for LTO) was not found. You can specify its path with -flto-binary=<file>.
Error: ldc: failed
```

```
==> Installing swrcfit from homebrew/science
Error: homebrew/science/swrcfit contains conflicting version recursive dependencies:
  openssl, openssl@1.1
View these with `brew deps --tree homebrew/science/swrcfit`.
==> FAILED
```

```
==> brew test --verbose littler
Testing homebrew/science/littler
==> /home/linuxbrew/.linuxbrew/Cellar/littler/0.2.3_14/bin/littler -e 'print(pi)'
.
Last 150 lines from /home/linuxbrew/.cache/Homebrew/Logs/littler/test.01.littler:
2017-09-06 23:46:38 +0000

/home/linuxbrew/.linuxbrew/Cellar/littler/0.2.3_14/bin/littler
-e
'print(pi)'

cannot find system Renviron
Fatal error: unable to open the base package

Error: homebrew/science/littler: failed
```

```
==> brew linkage --test shogun
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libdl.so.2
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /lib64/ld-linux-x86-64.so.2
Missing libraries:
  libhdf5.so.100
No unwanted system libraries
Warning: homebrew/science/shogun dependency snappy was built with a different C++ standard
library (libstdc++ from gcc-5). This may cause problems at runtime.
```

```
==> brew test --verbose opencascade
Testing homebrew/science/opencascade
this isn't a Tk application
Error: homebrew/science/opencascade: failed
test returned false
```

```
==> brew linkage --test openni2
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libdl.so.2
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /lib/x86_64-linux-gnu/librt.so.1
  /lib64/ld-linux-x86-64.so.2
Missing libraries:
  libOpenNI2.so
No unwanted system libraries
Warning: homebrew/science/openni2 dependency pcre was built with a different C++ standard
library (libstdc++ from gcc-4.8). This may cause problems at runtime.
```

```
./.libs/libfolia.so: undefined reference to `TiCC::bz2Compress(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
./.libs/libfolia.so: undefined reference to `TiCC::uppercase(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
./.libs/libfolia.so: undefined reference to `TiCC::gzCompress(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
./.libs/libfolia.so: undefined reference to `TiCC::bz2ReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
Makefile:676: recipe for target 'folialint' failed
make[1]: *** [folialint] Error 1
make[1]: Leaving directory '/tmp/libfolia-20170907-120888-10egeq8/libfolia-1.9/src'
Makefile:471: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

==> Formula
Tap: homebrew/science
Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-science/libfolia.rb
```


```
==> brew linkage --test mlpack
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /lib/x86_64-linux-gnu/librt.so.1
Missing libraries:
  libarmadillo.so.7
  libboost_program_options-mt.so.1.63.0
  libboost_serialization-mt.so.1.63.0
  libboost_unit_test_framework-mt.so.1.63.0
No unwanted system libraries
Warning: homebrew/science/mlpack dependency hdf5 was built with a different C++ standard
library (libstdc++ from gcc-5). This may cause problems at runtime.
==> FAILED
```

**Pull request merged**
