### PR TITLE
vpcs: Fix for Linuxbrew

### PR DESCRIPTION
**Pull request by rwhogg**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

### Description
`vpcs` was using a Mac-specific Make target.

### CODE REVIEW

**Comment by rwhogg** [comment]
Travis [failed](https://travis-ci.org/Linuxbrew/homebrew-core/builds/126526059#L467) installing the bottle:

> cannot find section .interp

**Comment by sjackman** [comment]
That's the error message that `patchelf` gives when it attempts to relocate a static executable. This bug definitely needs to be fixed. It could be fixed in `patchelf` to make this a warning rather than an error. That's probably the simpler fix. The alternative is that Linuxbrew could check whether the ELF is dynamic or static, and skip `patchelf` for static executables. The problem here is that I haven't found an easy way to distinguish dynamic from dynamic. The easiest way would be to call out to `file`.

**Comment by sjackman** [comment]
Blocked by https://github.com/Linuxbrew/brew/issues/4

**Comment by rwhogg** [comment]
Merging without adding the bottle.

**Comment by sjackman** [comment]
> Merging without adding the bottle.

This `patchelf` bug is fixed now, yes?

**Comment by rwhogg** [comment]
Yes, it is. Merged without adding the bottle because this PR in particular cannot seem to get both Travis and Circle to to show up on the PR, presumably because it's so old.

**Pull request closed without merging**
