### PR TITLE
texinfo: re-build linux bottle

### PR DESCRIPTION
**Pull request by lordqwerty**
- [X] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by rwhogg** [comment]
My apologies; what is the issue with the existing Linux bottle?

**Comment by lordqwerty** [comment]
If you remove `texinfo` and install again, I don't get the bottle it builds from source on my machine. Looking at the commit history there is not one from LinuxbrewBot. So I thought it wasn't resolving and favouring a build from source?

**Comment by rwhogg** [comment]
Weird. Can you do a `brew config` and paste the output here please? Also please paste the output of `brew reinstall texinfo` in a gist.

If I delete the cached bottle on my system and try reinstalling, the bottle downloads and installs fine for me. Is there a texinfo-6.3.x86_64_linux.bottle.tar.gz or similar file in `brew --cache`?

As for there not being a commit from Linuxbrewtestbot, that's not necessarily an indication that there's no bottle available. We frequently squash commits in our workflow, eliminating the test-bot from the commit history.

**Comment by sjackman** [comment]
The `texinfo` bottle is not relocatable (not `cellar :any`). The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by sjackman** [comment]
You can assign non-project-members to issues now. That's interesting.

**Pull request closed without merging**
