### PR TITLE
mlt: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
`brew install libdv` fails
```
checking for gcc... gcc-4.8
checking for C compiler default output file name... configure: error: C compiler cannot create executables
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/246278237#L2520
Blocked by #3042

**Comment by sjackman** [comment]
```
gcc-4.8 -I../.. -DARCH_X86_64 -Wall -DPIC   -O2 -pipe -fno-tree-dominator-opts -fno-tree-pre -ffast-math -DUSE_MMX -DUSE_SSE -DUSE_SSE2 -g -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC -pthread -D_GNU_SOURCE=1 -D_REENTRANT -I/home/linuxbrew/.linuxbrew/include/SDL   -c -o consumer_sdl_audio.o consumer_sdl_audio.c
consumer_sdl.c: In function ‘consumer_get_dimensions’:
consumer_sdl.c:919:10: error: ‘SDL_SysWMinfo’ has no member named ‘subsystem’
   if ( wm.subsystem == SDL_SYSWM_X11 ) 
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/246309620#L2869

This seems like an upstream issue to me.

**Comment by iMichka** [comment]
@sjackman this could be rebased; just to see what happens with gcc5

**Comment by sjackman** [comment]
Rebased.

**Comment by iMichka** [comment]
```
consumer_sdl_still.c:623:17: error: request for member ‘width’ in something not a structure or union
    *width = attr.width;
                 ^
consumer_sdl_still.c:624:18: error: request for member ‘height’ in something not a structure or union
    *height = attr.height;
                  ^
<builtin>: recipe for target 'consumer_sdl_still.o' failed
make[2]: *** [consumer_sdl_still.o] Error 1
make[2]: Leaving directory '/tmp/mlt-20170913-10317-1o2a08b/mlt-6.4.1/src/modules/sdl'
Makefile:5: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/tmp/mlt-20170913-10317-1o2a08b/mlt-6.4.1/src/modules'
Makefile:9: recipe for target 'all' failed
make: *** [all] Error 1

==> Formula
Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mlt.rb
```

**Comment by iMichka** [comment]
Seems to be that bug:
https://github.com/mltframework/mlt/issues/239#issuecomment-310176554

**Comment by sjackman** [comment]
Closing without merging. Feel free to pick up this PR if you're so inclined.

**Pull request closed without merging**
