### PR TITLE
flow: Depends on elfutils for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by rwhogg** [comment]
From https://travis-ci.org/Linuxbrew/homebrew-core/builds/130173448#L670-L671

```
/bin/sh: 1: ocamlbuild: not found
make: *** [build-flow-native-deps] Error 127
```

**Comment by sjackman** [comment]
This issue likely affects Homebrew on Mac as well.

**Comment by sjackman** [comment]
```
ocamlopt   -ccopt -DNO_LZ4 -c hack/heap/hh_shared.c
+ ocamlopt   -ccopt -DNO_LZ4 -c hack/heap/hh_shared.c
hack/heap/hh_shared.c:172:17: warning: 'MAGIC_CONSTANT' defined but not used [-Wunused-variable]
 static uint64_t MAGIC_CONSTANT = 0xfacefacefaceb000ll;
                 ^
mv hh_shared.o hack/heap/hh_shared.o
ocamlopt   -ccopt -DNO_LZ4 -c hack/hhi/hhi_elf.c
+ ocamlopt   -ccopt -DNO_LZ4 -c hack/hhi/hhi_elf.c
hack/hhi/hhi_elf.c:26:18: fatal error: gelf.h: No such file or directory
compilation terminated.
Command exited with code 2.
make: *** [build-flow-native-deps] Error 10
```
Looks like it depends on `elfutils` or `libelf`, I forget which is which, for `gelf.h`.
https://travis-ci.org/Linuxbrew/homebrew-core/builds/130280022#L1329

**Comment by rwhogg** [comment]
If this affects upstream Homebrew, we'll probably want to depend on `libelf` rather than `elfutils` since the latter is Linux-only. See https://github.com/Linuxbrew/homebrew-core/issues/233

**Comment by rwhogg** [comment]
```
hack/hhi/hhi_elf.c:26:18: fatal error: gelf.h: No such file or directory
 #include <gelf.h>
```

As it turns out, `gelf.h` isn't symlinked directly into `$HOMEBREW_PREFIX/include`. It's under `$HOMEBREW_PREFIX/include/libelf`.

Maybe an addition to CFLAGS would help?

**Comment by sjackman** [comment]
Debian also puts `gelf` in `include/libelf`. I'll just use `elfutils` for Linuxbrew. I'm guessing that this dependency isn't needed at all on Mac. See https://packages.debian.org/search?searchon=contents&keywords=gelf.h&mode=path&suite=stable&arch=any

**Comment by sjackman** [comment]
```
+ ocamlopt   -ccopt -DNO_LZ4 -c hack/utils/get_build_id.gen.c
hack/utils/get_build_id.gen.c:1:101: error: 'hg' undeclared here (not in a function)
 const char* const BuildInfo_kRevision = ""; const unsigned long BuildInfo_kRevisionCommitTimeUnix = hg log 
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/130462963#L1463

**Comment by sjackman** [comment]
I'm not at all familiar with ocaml, so I'm passing on this issue.

**Comment by rwhogg** [comment]
The `ocamlbuild => :build` dependency was added upstream, so it's no longer needed.

I'm not predicting that we'll be able to bottle this, but if nothing else I can add the `elfutils` dependency.

**Comment by rwhogg** [comment]
Replaced by #914

**Pull request closed without merging**
