### PR TITLE
libpst: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
/usr/bin/ld: cannot find -l-lpthread
collect2: error: ld returned 1 exit status
Makefile:320: recipe for target '_libpst.la' failed
make[2]: *** [_libpst.la] Error 1
make[2]: Leaving directory '/tmp/libpst-20181012-16939-110x7x1/libpst-0.6.72/python'
Makefile:401: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/libpst-20181012-16939-110x7x1/libpst-0.6.72'
Makefile:286: recipe for target 'all' failed
make: *** [all] Error 2

�[34m==>�[0m �[1mFormula�[0m
Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libpst.rb
```

**Comment by iMichka** [comment]
```
libtool: link: g++-5 -shared -nostdlib /home/linuxbrew/.linuxbrew/opt/glibc/lib/crti.o /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/crtbeginS.o  .libs/python-libpst.o  -Wl,--whole-archive ../src/.libs/libpst.a -Wl,--no-whole-archive  -l -lpthread -L/home/linuxbrew/.linuxbrew/lib -L/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0 -lstdc++ -lm -lc -lgcc_s /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/crtendS.o /home/linuxbrew/.linuxbrew/opt/glibc/lib/crtn.o    -Wl,-soname -Wl,_libpst.so -o .libs/_libpst.so
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -l-lpthread
```

**Comment by iMichka** [comment]
```
g++-5 called with: -shared -nostdlib /home/linuxbrew/.linuxbrew/opt/glibc/lib/crti.o /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/crtbeginS.o .libs/python-libpst.o -Wl,--whole-archive ../src/.libs/libpst.a -Wl,--no-whole-archive -l -lpthread -L/home/linuxbrew/.linuxbrew/lib -L/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0 -lstdc++ -lm -lc -lgcc_s /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/crtendS.o /home/linuxbrew/.linuxbrew/opt/glibc/lib/crtn.o -Wl,-soname -Wl,_libpst.so -o .libs/_libpst.so
superenv removed:  -L/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0
superenv added:    -pipe -w -O2 -march=native -isystem/home/linuxbrew/.linuxbrew/include -B/home/linuxbrew/.linuxbrew/opt/glibc/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/Cellar/libpst/0.6.72_1/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/bzip2/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/zlib/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/boost/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/gdbm/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/openssl/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/ncurses/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/readline/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/sqlite/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/python@2/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/boost-python/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/gettext/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/libffi/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/pcre/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/util-linux/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/glib/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/libxml2/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/libgsf/lib -Wl,--dynamic-linker=/home/linuxbrew/.linuxbrew/lib/ld.so
superenv executed: g++-5 -pipe -w -O2 -march=native -shared -nostdlib /home/linuxbrew/.linuxbrew/opt/glibc/lib/crti.o /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/crtbeginS.o .libs/python-libpst.o -Wl,--whole-archive ../src/.libs/libpst.a -Wl,--no-whole-archive -l -lpthread -lstdc++ -lm -lc -lgcc_s /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/crtendS.o /home/linuxbrew/.linuxbrew/opt/glibc/lib/crtn.o -Wl,-soname -Wl,_libpst.so -o .libs/_libpst.so -isystem/home/linuxbrew/.linuxbrew/include -L/home/linuxbrew/.linuxbrew/lib -B/home/linuxbrew/.linuxbrew/opt/glibc/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/Cellar/libpst/0.6.72_1/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/bzip2/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/zlib/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/boost/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/gdbm/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/openssl/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/ncurses/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/readline/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/sqlite/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/python@2/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/boost-python/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/gettext/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/libffi/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/pcre/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/util-linux/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/glib/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/libxml2/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/libgsf/lib -Wl,--dynamic-linker=/home/linuxbrew/.linuxbrew/lib/ld.so
```

**Comment by iMichka** [comment]
I thought at first it was a superenv bug, but actually it really passes a lone `-l` as parameter. @sjackman do you know if this makes any sense?

**Comment by sjackman** [comment]
Looks like a bug in the `Makefile` to me. The bare `-l` is probably something like `-l$something` and `$something` is undefined.

**Pull request closed without merging**
