### PR TITLE
gspell: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
checking for DocBook XML DTD V4.3 in XML catalog... not found
configure: error: could not find DocBook XML DTD V4.3 in XML catalog
```

**Comment by iMichka** [comment]
Meanwhile a bottle was built. Abandoning this.

**Comment by sjackman** [comment]
> checking for DocBook XML DTD V4.3 in XML catalog... not found
configure: error: could not find DocBook XML DTD V4.3 in XML catalog

I'm seeing this error when building `gtk-doc` locally. Any tips on how to fix it?

**Comment by sjackman** [comment]
PRs https://github.com/Linuxbrew/homebrew-core/pull/5165 and https://github.com/Linuxbrew/homebrew-core/pull/5167 are related. I ran `brew postinstall docbook && brew postinstall docbook-xsl` but it didn't help.

**Comment by sjackman** [comment]
This line is present in `$HOMEBREW_PREFIX/etc/xml/catalog` and the specified file exists.
```xml
  <nextCatalog catalog="file:///gsc/btl/linuxbrew/Cellar/docbook/5.0/docbook/xml/4.3/catalog.xml"/>
```

**Comment by sjackman** [comment]
Here's the contents of my `etc/xml/catalog` file.
```xml
<?xml version="1.0"?>
<!DOCTYPE catalog PUBLIC "-//OASIS//DTD Entity Resolution XML Catalog V1.0//EN" "http://www.oasis-open.org/committees/entity/release/1.0/catalog.dtd">
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
  <delegatePublic publicIdStartString="-//OASIS//ENTITIES DocBook XML" catalog="file:///usr/share/sgml/docbook/xmlcatalog"/>
  <delegatePublic publicIdStartString="-//OASIS//DTD DocBook XML" catalog="file:///usr/share/sgml/docbook/xmlcatalog"/>
  <delegatePublic publicIdStartString="ISO 8879:1986" catalog="file:///usr/share/sgml/docbook/xmlcatalog"/>
  <delegateSystem systemIdStartString="http://www.oasis-open.org/docbook/" catalog="file:///usr/share/sgml/docbook/xmlcatalog"/>
  <delegateURI uriStartString="http://www.oasis-open.org/docbook/" catalog="file:///usr/share/sgml/docbook/xmlcatalog"/>
  <rewriteSystem systemIdStartString="http://scrollkeeper.sourceforge.net/dtds/scrollkeeper-omf-1.0/scrollkeeper-omf.dtd" rewritePrefix="/usr/share/xml/scrollkeeper/dtds/scrollkeeper-omf.dtd"/>
  <rewriteURI uriStartString="http://scrollkeeper.sourceforge.net/dtds/scrollkeeper-omf-1.0/scrollkeeper-omf.dtd" rewritePrefix="/usr/share/xml/scrollkeeper/dtds/scrollkeeper-omf.dtd"/>
  <nextCatalog catalog="file:///gsc/btl/linuxbrew/Cellar/docbook-xsl/1.78.1_1/docbook-xsl/catalog.xml"/>
  <nextCatalog catalog="file:///gsc/btl/linuxbrew/Cellar/docbook-xsl/1.78.1_1/docbook-xsl-ns/catalog.xml"/>
  <nextCatalog catalog="file:///gsc/btl/linuxbrew/Cellar/docbook-xsl/1.79.1/docbook-xsl/catalog.xml"/>
  <nextCatalog catalog="file:///gsc/btl/linuxbrew/Cellar/docbook-xsl/1.79.1/docbook-xsl-ns/catalog.xml"/>
  <nextCatalog catalog="file:///gsc/btl/linuxbrew/Cellar/docbook/5.0/docbook/xml/4.2/catalog.xml"/>
  <nextCatalog catalog="file:///gsc/btl/linuxbrew/Cellar/docbook/5.0/docbook/xml/4.1.2/catalog.xml"/>
  <nextCatalog catalog="file:///gsc/btl/linuxbrew/Cellar/docbook/5.0/docbook/xml/4.3/catalog.xml"/>
  <nextCatalog catalog="file:///gsc/btl/linuxbrew/Cellar/docbook/5.0/docbook/xml/4.4/catalog.xml"/>
  <nextCatalog catalog="file:///gsc/btl/linuxbrew/Cellar/docbook/5.0/docbook/xml/4.5/catalog.xml"/>
  <nextCatalog catalog="file:///gsc/btl/linuxbrew/Cellar/docbook/5.0/docbook/xml/5.0/catalog.xml"/>
  <nextCatalog catalog="file:///gsc/btl/linuxbrew/Cellar/docbook-xsl/1.79.1_1/docbook-xsl/catalog.xml"/>
  <nextCatalog catalog="file:///gsc/btl/linuxbrew/Cellar/docbook-xsl/1.79.1_1/docbook-xsl-ns/catalog.xml"/>
</catalog>
```
There's a bunch of references to `/usr/share/sgml/docbook/xmlcatalog`. I delete those lines, and it works!
Here's the new contents of the file.
```xml
<?xml version="1.0"?>
<!DOCTYPE catalog PUBLIC "-//OASIS//DTD Entity Resolution XML Catalog V1.0//EN" "http://www.oasis-open.org/committees/entity/release/1.0/catalog.dtd">
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
  <nextCatalog catalog="file:///gsc/btl/linuxbrew/Cellar/docbook/5.0/docbook/xml/4.2/catalog.xml"/>
  <nextCatalog catalog="file:///gsc/btl/linuxbrew/Cellar/docbook/5.0/docbook/xml/4.1.2/catalog.xml"/>
  <nextCatalog catalog="file:///gsc/btl/linuxbrew/Cellar/docbook/5.0/docbook/xml/4.3/catalog.xml"/>
  <nextCatalog catalog="file:///gsc/btl/linuxbrew/Cellar/docbook/5.0/docbook/xml/4.4/catalog.xml"/>
  <nextCatalog catalog="file:///gsc/btl/linuxbrew/Cellar/docbook/5.0/docbook/xml/4.5/catalog.xml"/>
  <nextCatalog catalog="file:///gsc/btl/linuxbrew/Cellar/docbook/5.0/docbook/xml/5.0/catalog.xml"/>
  <nextCatalog catalog="file:///gsc/btl/linuxbrew/Cellar/docbook-xsl/1.79.1_1/docbook-xsl/catalog.xml"/>
  <nextCatalog catalog="file:///gsc/btl/linuxbrew/Cellar/docbook-xsl/1.79.1_1/docbook-xsl-ns/catalog.xml"/>
</catalog>
```
The fix to this problem is…
```sh
xmlcatalog --noout $(brew --prefix)/etc/xml/catalog "-//OASIS//DTD DocBook XML V4.3//EN"
rm -f $(brew --prefix)/etc/xml/catalog
brew postinstall docbook
brew postinstall docbook-xsl
xmlcatalog --noout $(brew --prefix)/etc/xml/catalog "-//OASIS//DTD DocBook XML V4.3//EN"
```

**Comment by iMichka** [comment]
Does this mean that another formula is messing up the xml file? sgml ?

**Comment by sjackman** [comment]
Perhaps. Something is auto-detect these host files in `/usr`, `/usr/share/sgml/docbook/xmlcatalog`, which we'd rather it not do.

**Pull request closed without merging**
