### PR TITLE
cryptopp: fix building for linuxbrew

### PR DESCRIPTION
**Pull request by xu-cheng**
- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Applying upstream patch https://github.com/weidai11/cryptopp/pull/575

### CODE REVIEW

**Comment by iMichka** [comment]
Hi. Thanks for this contribution.

Was this patch submitted to upstream? We would prefer that upstream creates a new release with the patch included. If their release cycle is longer than a few weeks/months, we can add this patch here, but then it needs to be safeguarded with an `unless OS.mac?` after the `end`, and add a comment that it needs to be removed for the next release.

**Comment by xu-cheng** [comment]
Yes, this patch is submit to the upstream and has been merged. It is unlikely for them to create a new release as the average release cycle for cryptopp is several years. So I have made the necessary changes as you requested.

**Comment by xu-cheng** [comment]
Hi, any chance to merge this? Thanks.

**Comment by iMichka** [comment]
Thanks for your contribution!

**Pull request closed without merging**
