### PR TITLE
akamai: test fails on Travis

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
Test fails on Travis:
```
Error: akamai: failed
<0> expected but was
<2>.
```

**Comment by sjackman** [comment]
Move Travis to "allowed failures" and merge?

**Comment by iMichka** [comment]
Yes, this is what is going to happen. Once the bottles are built, I'll merge this.

**Comment by iMichka** [comment]
@sjackman could you look at why the bottle upload did not work? Bottle seems to be quite small.

**Comment by sjackman** [comment]
> Error: akamai-0.3.2.x86_64_linux.bottle.tar.gz is already published. Please remove it manually from
https://bintray.com/linuxbrew/bottles/akamai/view#files

**Comment by iMichka** [comment]
I deleted the bottle, and rebased. Let's rebuild this.

**Pull request closed without merging**
