### PR TITLE
jasper: Needs full texlive to build

### PR DESCRIPTION
**Pull request by dholm**

### CODE REVIEW

**Comment by dholm** [comment]
Build will fail unless tabularx is installed https://gist.github.com/dholm/5b1037ef58532677a5d0f7d3beee33c8.

**Comment by sjackman** [comment]
Please copy the relevant errors from the gist and link to the specific line, if you can.
```
! LaTeX Error: File `tabu.sty' not found.
```
https://gist.github.com/dholm/5b1037ef58532677a5d0f7d3beee33c8#file-02-make-L816

```
l.14 \RequirePackage
                    {tabularx}^^M
```
https://gist.github.com/dholm/5b1037ef58532677a5d0f7d3beee33c8#file-02-make-L825-L826
```

**Comment by sjackman** [comment]
`texlive --with-small` includes `tabularx.sty` but appears to be missing `tabu.sty`
```
$ tar tf ~/.cache/Homebrew/texlive-20170414.x86_64_linux.bottle.tar.gz | egrep '(tabu|tabularx).sty'
texlive/20170414/texmf-dist/tex/latex/tools/tabularx.sty
```

Is there a list of which Texlive installation schemes include which packages? Does `--with-medium` include `tabu.sty`?

**Comment by dholm** [comment]
@sjackman I tested it with "small", "medium" and finally "full" was the only one that worked for me.  I'll try it again and check exactly what it fails on with each one.

**Comment by dholm** [comment]
When `texlive` is installed `--with-small`:

```
! LaTeX Error: File `tabu.sty' not found.                    
                                                       
Type X to quit or <RETURN> to proceed,                    
or enter new name. (Default extension: sty)           
                                                         
Enter file name:                                                                                
! Emergency stop.                                                                           
<read *>
                                
l.14 \RequirePackage                                                                    
                    {tabularx}^^M
```

**Comment by dholm** [comment]
Another option would be to pass JAS_ENABLE_DOC=False to cmake so that the texlive dependency can be removed completely.

**Comment by sjackman** [comment]
An alternative would be to add a `TabuRequirement` that checks whether `tabu.sty` is installed, and if it's not suggests that the user run `tlmgr install tabu`.

**Comment by sjackman** [comment]
The small `texlive` bottle is already 260 MB, so I'm hesitant to make it larger. https://bintray.com/linuxbrew/bottles/texlive#files

**Comment by sjackman** [comment]
```
 depends_on "texlive" => ["with-full", :build]
```
Depending on an option like this is deprecated, because it forces the user to install `texlive` from source without using the bottle (which is `--with-small`).

**Comment by sjackman** [comment]
If you're sufficiently motivated to address this issue, you could add a `:tex` requirement to Linuxbrew/brew.
```ruby
depends_on "tabu" => :tex
```

**Comment by sjackman** [comment]
I'd be curious to know whether a default installation of LaTeX on Ubuntu/Debian includes `tabu.sty`.

**Comment by sjackman** [comment]
We could also contact the upstream authors and suggest that they, if possible, avoid using tabu.sty in favour of a more common tables package.

**Comment by sjackman** [comment]
I'd accept a PR to `texlive` to add `tabu.sty` to the default bottle.

**Pull request closed without merging**
