### PR TITLE
appscale-tools: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by sjackman** [comment]
```
cc -pthread -shared -L/home/linuxbrew/.linuxbrew/lib build/temp.linux-x86_64-2.7/c/_cffi_backend.o -L/home/linuxbrew/.linuxbrew/lib -L/home/linuxbrew/.linuxbrew/opt/openssl/lib -L/home/linuxbrew/.linuxbrew/opt/sqlite/lib -L/home/linuxbrew/.linuxbrew/Cellar/python/2.7.13/lib -lffi -lpython2.7 -o build/lib.linux-x86_64-2.7/_cffi_backend.so
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -lffi
collect2: error: ld returned 1 exit status
error: command 'cc' failed with exit status 1
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/221877712#L2931

Missing dependency of `libffi`?

**Comment by maxim-belkin** [comment]
Travis failed with:
```
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -lffi
```

**Comment by sjackman** [comment]
Jinx!

**Comment by maxim-belkin** [comment]
Now it fails in the `test` block
```
==> brew test appscale-tools --verbose
Testing appscale-tools
==> /home/linuxbrew/.linuxbrew/Cellar/appscale-tools/3.2.1/bin/appscale help
.
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/appscale-tools/test.01.appscale:
2017-04-13 21:07:28 +0000

/home/linuxbrew/.linuxbrew/Cellar/appscale-tools/3.2.1/bin/appscale
help

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/appscale-tools/3.2.1/libexec/bin/appscale", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/linuxbrew/.linuxbrew/Cellar/appscale-tools/3.2.1/libexec/vendor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/home/linuxbrew/.linuxbrew/Cellar/appscale-tools/3.2.1/libexec/vendor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/appscale-tools/3.2.1/libexec/vendor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/linuxbrew/.linuxbrew/Cellar/appscale-tools/3.2.1/libexec/vendor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/home/linuxbrew/.linuxbrew/Cellar/appscale-tools/3.2.1/libexec/vendor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/linuxbrew/.linuxbrew/Cellar/appscale-tools/3.2.1/libexec/vendor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'secretstorage' distribution was not found and is required by keyring
Error: appscale-tools: failed
Failed executing: /home/linuxbrew/.linuxbrew/Cellar/appscale-tools/3.2.1/bin/appscale help
```

**Comment by sjackman** [comment]
Maybe it depends on https://pypi.python.org/pypi/SecretStorage/ ?

**Comment by maxim-belkin** [comment]
```
depends_on "secretstorage" => :python
```
?

**Comment by sjackman** [comment]
Try…
```ruby
  resource "httplib2" do
    url "https://pypi.python.org/packages/a5/a5/0830cfe34a4cfd0d1c3c8b614ede1edb2aaf999091ac8548dd19cb352e79/SecretStorage-2.3.1.tar.gz"
    sha256 "3af65c87765323e6f64c83575b05393f9e003431959c9395d1791d51497f29b6"
  end unless OS.mac?
```

**Comment by maxim-belkin** [comment]
I started working on a bottle but I'll try a resource

**Comment by maxim-belkin** [comment]
now we need `pyparsing`

**Comment by sjackman** [comment]
Nice work, Maxim!

**Pull request closed without merging**
