### PR TITLE
py2cairo: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by rwhogg** [comment]
I tried fighting with this one both locally and on the Linuxbrew Docker image. Works fine locally; the problem on the Docker image is that `pkg-config` (triggered by `waf`) really doesn't like `cairo` for who knows what reason.

```
$ pkg-config --modversion cairo
1.14.6
$ pkg-config --atleast-version=1.10.0 cairo; echo $?
1
```

Which is crazy, since `pkg-config` is perfectly happy with `zlib`, `expat`, and `ncurses`. 

I also tried all sorts of variants of different version arguments to make sure it wasn't just a parsing error on "1.10.0". I also went Google searching and there's all sorts of issues building `py2cairo` on the Mac, but this *feels* like a bug in `pkg-config` to me. It *might* also be related to https://github.com/Linuxbrew/legacy-linuxbrew/issues/47 , but that seems dubious since there's only one .pc file for `cairo` and it seems to be finding it.

**Comment by sjackman** [comment]
My only thought would be to check the `pkg-config` search path for older versions of `cairo`, but yet, it looks like a bug to me. I'd send a bug report upstream to `pkg-config`.

**Comment by rwhogg** [comment]
I decided to take another look at this and found something very interesting:

```bash
% pkg-config --atleast-version=1.14.6 --print-errors cairo; echo $?
Package xcb-shm was not found in the pkg-config search path.
Perhaps you should add the directory containing `xcb-shm.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xcb-shm', required by 'cairo', not found
1
```

Upon further inspection, installing `cairo` as a dependency did not trigger installing X11. However, installing `cairo` manually did. After installing manually, `pkg-config` does recognize `cairo` as expected. 

While the bizarre `pkg-config` behaviour now makes much more sense (it's clearly not a bug in `pkg-config`, just a quirk) clearly the X11 dependency logic is not quite right.

Maybe I just have  bug in the X.Org requirement?

**Comment by rwhogg** [comment]
I've gotten closer to the reason this is failing. `linuxbrew/xorg/xorg` is recognized as a dependency, but it gets pruned out in the following code (https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/formula_installer.rb#L426-L427):

```ruby
if (dep.optional? || dep.recommended?) && build.without?(dep)
  Dependency.prune
```

The `dep.recommended?` makes sense; that's how `cairo` is set up. The `build.without?` makes no sense as I passed no argument of the kind.

So, either there's a bug in `without?` or we've somehow picked up an inappropriate `without-x11` or something like somewhere along the line. Not sure what gives.

**Comment by rwhogg** [comment]
I've found it! And it's a nasty one.

`build.with?` (the negation of `build.without?) does the following check for whether or not a specific option has passed:

```
      if option_defined? "with-#{name}"
        include? "with-#{name}"
      elsif option_defined? "without-#{name}"
        !include? "without-#{name}"
      else
        false
      end
```

`name` as passed into that function is "linuxbrew/xorg/xorg". There's two problems with that:

1. The "linuxbrew/xorg" is still attached
2. The formula itself is named "xorg", not "x11"

If the value of "name" was just "x11", the problem would go away since `cairo` has a `--without-x11` option, which would trigger case number 2 above. Then it would see that we didn't pass `--without-x11` at the command line and everything would just be fine. Currently, it triggers case number 3, returns a hardcoded `false` and then gets pruned out by the code I pointed out earlier.

X11 on Mac presumably doesn't trip over this case since, while its cask is `xquartz` and it has no default formula, presumably the value passed in to `build.without?` above derives from the "name" field in x11_requirement.rb ("x11"). (That's all speculation though.)

CC @maxim-belkin. Fixing this is going to be a headache and a half.

**Comment by maxim-belkin** [comment]
Superseded by #2385.

**Pull request closed without merging**
