### PR TITLE
qwt: -spec, audit fixed.

### PR DESCRIPTION
**Pull request by JuPlutonic**
- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
[brew_test_qwt.txt](https://github.com/Linuxbrew/homebrew-core/files/2825465/brew_test_qwt.txt)
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----
[Discource: Troubles with test in formula. Formula is audited and compiled successfully](https://discourse.brew.sh/t/troubles-with-test-in-formula-formula-is-audited-and-compiled-successfully/4106)

### CODE REVIEW

**Comment by iMichka** [comment]
Hi. We are almost there. Just one comment, please do not open new pull requests, you can force push to your remote branch to update the code in here.

Please add the `cellar :any_skip_relocation` line to the bottle block so that the bottle gets correctly built.

Thanks for working on this!

**Comment by JuPlutonic** [comment]
@iMichka CircleCI stalled with ```fatal: --unshallow on a complete repository does not make sense
Exited with code 128```

**Comment by iMichka** [comment]
Hi. Can you rebase this on master? It should fix it.

**Comment by JuPlutonic** [comment]
@iMichka  ```Able to merge. These branches can be automatically merged``` I smth. wrong I will try it again.

**Pull request closed without merging**
