### PR TITLE
bazel: Build a bottle for Linuxbrew: exceeded the memory limit of 4G

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
TravisCI `brew test bazel` failed
```
==> brew test bazel --verbose
Testing bazel
==> /home/linuxbrew/.linuxbrew/Cellar/bazel/0.4.5/bin/bazel build //:bazel-test
.
Last 150 lines from /home/linuxbrew/.cache/Homebrew/Logs/bazel/test.01.bazel:
2017-06-03 20:58:43 +0000
/home/linuxbrew/.linuxbrew/Cellar/bazel/0.4.5/bin/bazel
build
//:bazel-test
Failed to extract install_base_key: local file header signature for file A-server.jar not found
Error: bazel: failed
Failed executing: /home/linuxbrew/.linuxbrew/Cellar/bazel/0.4.5/bin/bazel build //:bazel-test
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/239161496#L1391

**Comment by sjackman** [comment]
CircleCI executed 38 `cc1plus` processes and exceeded 4 GB of RAM.
https://circleci.com/gh/Linuxbrew/homebrew-core/5983
https://5983-56942570-gh.circle-artifacts.com/0/tmp/memory-usage.txt

**Comment by sjackman** [comment]
```
The build tool has reset ENV; --env=std required.
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/239097566#L1300

**Comment by sjackman** [comment]
@steren Hi, Steren. I'm attempting to a build a binary bottle of `bazel` for Linuxbrew. I've run into two issues.
1. All environment variables are being reset, including some needed by `brew`. Is it possible to prevent that?
2. `./compile.sh` is using 38 `c++` processes, which exceeds the 4 GB memory limit of CircleCI. Is it possible to configure it to use fewer processes?

Thanks,
Shaun

**Comment by steren** [comment]
Hi @sjackman,

Let me loop @damienmg who will be able to help you better.

For 2: the [--local_resources](https://bazel.build/versions/master/docs/bazel-user-manual.html#flag--local_resources) flag might be helpful.

**Comment by sjackman** [comment]
Thanks, Steren.

**Comment by sjackman** [comment]
Here's a related issue open issue on the number of parallel processes used to build `bazel`. https://github.com/bazelbuild/bazel/issues/2048

**Comment by sjackman** [comment]
I had no luck reducing the number of processes by setting `BAZEL_EXTRA_ARGS=--jobs=8`. It used 36 `c++` processes.
See https://5996-56942570-gh.circle-artifacts.com/0/tmp/memory-usage.txt

**Comment by steren** [comment]
I suggest to post your question on StackOverflow, the Bazel team watches the `bazel` tag and you should get an answer in a few days.

**Comment by sjackman** [comment]
| Jobs | Status |
| 32 | ❌ |
| 16 | ❌ |
| 8 | |

**Comment by sjackman** [comment]
| Jobs | Status |
| 32 | ❌ |
| 16 | ❌ |
| 8 | |

**Comment by sjackman** [comment]
Bazel seems to fire up 4 workers if I ask for fewer than `--jobs=4`. The option [--local_resources](https://bazel.build/versions/master/docs/bazel-user-manual.html#flag--local_resources) suggested by @steren is the next place to look.

**Comment by damienmg** [comment]
Try `--worker_max_instances=2`?

For 1. you want to use `--action_env` flag to white list environment variables to get shipped to the action.

**Comment by damienmg** [comment]
(sorry for the late answer but I am on holidays, just working a few days remotely)

**Comment by sjackman** [comment]
Thanks for the tip, Damien. I'm trying now…
```ruby
    ENV["BAZEL_EXTRA_ARGS"] = "--jobs=#{ENV["HOMEBREW_MAKE_JOBS"]} --worker_max_instances=#{ENV["HOMEBREW_MAKE_JOBS"]}"
```

**Comment by sjackman** [comment]
@damienmg I'm still seeing four `javabootstrap_deploy.jar --persistent_worker` processes with `BAZEL_EXTRA_ARGS="--jobs=1 --worker_max_instances=1"`
See https://6259-56942570-gh.circle-artifacts.com/0/tmp/memory-usage.txt

**Pull request closed without merging**
