### PR TITLE
Merge 2017-08-26 1db46900a2

### PR DESCRIPTION
**Pull request by iMichka**
+ [ ] grpc
+ [ ] protobuf-swift
+ [ ] protobuf

### CODE REVIEW

**Comment by iMichka** [comment]
Bottle upload failed. I'll open separate PR's.

**Comment by sjackman** [comment]
No bottles were built by CircleCI.
https://circleci.com/gh/Linuxbrew/homebrew-core/8423#artifacts/containers/0
```
Uploading /home/linuxbrew/bottles to s3://circle-production-customer-artifacts/picard/…build/artifacts/home/linuxbrew/bottles
  No artifact files found at /home/linuxbrew/bottles
```

**Comment by iMichka** [comment]
Weird? There were definitively a list of bottles in the artefacts tab. They are gone now. Not sure what happened.

**Comment by sjackman** [comment]
My fault. I was looking at the `master` build, which checks only formulae syntax. Here's the correct one:
https://circleci.com/gh/Linuxbrew/homebrew-core/8421#artifacts/containers/0

**Comment by sjackman** [comment]
`bot.linuxbrew.sh` timed out after five minutes with no apparent reason why. When the transfer fails, you can either retrigger the bot:
```
http://bot.linuxbrew.sh/ci-upload/github.com/Linuxbrew/homebrew-core/pull/4001?keep-old=1
```
Or publish the bottles using your local machine, which gives you progress and error messages:
```
brew pull-circle --ci-upload https://github.com/Linuxbrew/homebrew-core/pull/4001
```

**Pull request merged**
