### PR TITLE
postgresql: error: libperl library is required for Perl

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by rwhogg** [comment]
From https://travis-ci.org/Linuxbrew/homebrew-core/builds/130173150#L1943-L1945

```
checking for perl.h... yes
checking for libperl... no
configure: error: libperl library is required for Perl
```

See also the discussion from https://github.com/Linuxbrew/linuxbrew/pull/1019

**Comment by sjackman** [comment]
This formula builds successfully on LinuxbrewTestBot on Ubuntu 14 which does not exclude `/usr/lib` for the library search path, unlike Travis on Ubuntu 12 which uses `glibc` and does exclude `/usr/lib`. I'm not sure whether it should `depends_on "perl" unless OS.mac?` on Linuxbew. I guess it has to, otherwise it won't pick up `libperl.so`.

**Comment by rwhogg** [comment]
> This formula builds successfully on LinuxbrewTestBot on Ubuntu 14 which does not exclude /usr/lib for the library search path

I think we ought to change that if possible. It already punished us before on #193.

**Comment by sjackman** [comment]
Here's the question. On Linuxbrew systems that do not have `glibc` installed, `/usr/lib` is not excluded from the library search path, because that exclusion is handled by `glibc` at run time (and handled by `gcc` at link time). I want the LinuxbrewTestBot to represent a user's normal Linuxbrew system running on Ubuntu 14. That system does not have `glibc` installed, because Ubuntu 14 has `glibc` 2.19, and so does not exclude `/usr/lib`. So the question is, are we talking about just hacking up the LinuxbrewTestBot and making it different than normal installations (for example by installing `glibc`), or changing the default behaviour of Linuxbrew?

**Comment by rwhogg** [comment]
I was proposing a change just to LinuxbrewTestBot. IMO, it'd be better if TestBot-created bottles only dynamically link to .so files known to be available on Linuxbrew, or on the explicit list of dependencies.

Arguably, if it would take a lot of work and/or risk breaking things, then it's probably not worth it. `ncurses` vs. `tinfo` is, in a sense, due to historical reasons, and there probably aren't all that many similar ones.

**Comment by sjackman** [comment]
A simple solution is to remove all the `lib*-dev` packages except `libc6-dev` from the LinuxbrewTestBot. I've already removed `sudo apt-get remove libncurses5-dev libtinfo-dev` from LinuxbrewTestBot. We can continue doing this on a case-by-case basis, or do it wholesale.

**Comment by DoomHammer** [comment]
Personally I would make `glibc` an essential dependency. Figuring out system dependencies is really hard and the combinations are countless. I understand, though, this point of view may not be universal :)

**Comment by sjackman** [comment]
I can definitely understand that viewpoint, and Linuxbrew does ignore nearly all host libraries, but I decided to draw the line at `glibc` and `gcc` and use the host's where possible. On a system with sufficiently new `glibc`, it's nice to build executables and libraries that can be intermixed.

**Pull request closed without merging**
