### PR TITLE
Update kubernetes cli

### PR DESCRIPTION
**Pull request by franciscocpg**
- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by sjackman** [comment]
See https://github.com/Linuxbrew/brew/blob/master/CONTRIBUTING.md#contributing-to-linuxbrew

> Linuxbrew is a fork of Homebrew. Homebrew is merged into Linuxbrew roughly once per week. To contribute a new formula or a new version of an existing formula, please submit your pull request to Homebrew rather than to Linuxbrew.

**Comment by franciscocpg** [comment]
Sorry about that @sjackman 
But this version kubernetes-cli.rb 1.4.6 was merged into homebrew 18 days ago (https://github.com/Homebrew/homebrew-core/commit/987010d81b337016440ca57fab4622336f84d2cc)
It's been two weeks since then so I'd thought I should open this PR.
Do you know why still is not available at Linuxbrew/homebrew-core?

**Comment by sjackman** [comment]
@rwhogg and I have both unfortunately been busier than usual and have gotten to a merge of Homebrew/core on the usual schedule. One of us will try to get to it in the next few days. Sorry for the delay.

**Comment by franciscocpg** [comment]
Thank you @sjackman

**Pull request closed without merging**
