### PR TITLE
ntl: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
Test fails:
> /home/linuxbrew/.linuxbrew/Cellar/ntl/10.4.0/lib/libntl.a(lip.o): In function `redc':
/tmp/ntl-20170709-39012-9xndg8/ntl-10.4.0/src/lip.cpp:5012: undefined reference to `__gmpn_addmul_1'
/tmp/ntl-20170709-39012-9xndg8/ntl-10.4.0/src/lip.cpp:5024: undefined reference to `__gmpn_sub_n'

**Comment by sjackman** [comment]
My best guess is that
```
      -lgmp
      -lntl
```
should be
```
      -lntl
      -lgmp
```

**Comment by iMichka** [comment]
Let me try that. If it works I guess best would be to submit that patch upstream.

**Comment by iMichka** [comment]
I opened a PR upstream to keep both versions in sync: https://github.com/Homebrew/homebrew-core/pull/15496

**Pull request closed without merging**
