### PR TITLE
cloc: Build a bottle for Linuxbrew (blocked by perl-modules)

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by rwhogg** [comment]
From https://travis-ci.org/Linuxbrew/homebrew-core/builds/127482186#L533-L533

```
Can't locate Regexp/Common.pm in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at cloc line 59.
BEGIN failed--compilation aborted at cloc line 59.
make: *** [test-perl] Error 2
```

Probably just a missing CPAN dependency, but maybe something more than that.

**Comment by rwhogg** [comment]
Marking as blocked by https://github.com/Linuxbrew/homebrew-core/pull/139

**Comment by rwhogg** [comment]
Now blocked by https://github.com/Linuxbrew/brew/issues/6#issuecomment-217925845

**Comment by rwhogg** [comment]
From https://travis-ci.org/Linuxbrew/homebrew-core/builds/184569081#L490-L503

```
Last 150 lines from /home/linuxbrew/.cache/Homebrew/Logs/cloc/01.perl:
2016-12-16 15:51:39 +0000
perl
Makefile.PL
INSTALL_BASE=/home/linuxbrew/.linuxbrew/Cellar/cloc/1.70/libexec
WARNING: TEST_REQUIRES is not a known parameter.
Checking if your kit is complete...
Looks good
'TEST_REQUIRES' is not a known MakeMaker parameter name.
ExtUtils::MakeMaker::YAML does not support circular references at /usr/share/perl/5.14/ExtUtils/MakeMaker/YAML.pm line 499.
Writing Makefile for Regexp::Common
Writing MYMETA.yml
```

It builds fine on Travis if you use a brewed Perl. Ubuntu (my 16.04 machine) shows no dependencies other than Perl and the 2 vendored dependencies, so I'm not sure what gives. I'm currently trying installing libcpan-meta-perl and hoping that fixes everything, but if I can't figure this out it might be better just to make this depend on brewed Perl.

**Comment by maxim-belkin** [comment]
closing to re-do again under superenv

**Comment by maxim-belkin** [comment]
#2361

**Pull request closed without merging**
