### PR TITLE
git-flow: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by sjackman** [comment]
TravisCI
```
1.00s==> brew test git-flow --verbose
Testing git-flow
==> git flow init -d
.
==> git rev-parse --abbrev-ref HEAD
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Error: git-flow: failed
<0> expected but was
<128>.
==> FAILED
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/222379905#L2170

**Comment by maxim-belkin** [comment]
same fix for Travis...?

**Comment by maxim-belkin** [comment]
no, it wouldn't help

**Comment by maxim-belkin** [comment]
To troubleshoot, I added a `raise` to the test block
```
$ git diff
diff --git a/Formula/git-flow.rb b/Formula/git-flow.rb
index 156e19230c..b30e4c998e 100644
--- a/Formula/git-flow.rb
+++ b/Formula/git-flow.rb
@@ -45,6 +45,7 @@ class GitFlow < Formula
   end
 
   test do
+    raise
     system "git", "flow", "init", "-d"
     assert_equal "develop", shell_output("git rev-parse --abbrev-ref HEAD").strip
   end
```
and then did the following
```
brew test -d git-flow
```
then chose "5. shell"
then
```
git config --list
```
which yielded an empty list...


Now, what fixes the problem is:
```
$ git diff
diff --git a/Formula/git-flow.rb b/Formula/git-flow.rb
index 156e19230c..9c436de75f 100644
--- a/Formula/git-flow.rb
+++ b/Formula/git-flow.rb
@@ -45,6 +45,8 @@ class GitFlow < Formula
   end
 
   test do
+    system "git", "config", "--global", "user.name", "test test"
+    system "git", "config", "--global", "user.email", "test@email.com"
     system "git", "flow", "init", "-d"
     assert_equal "develop", shell_output("git rev-parse --abbrev-ref HEAD").strip
   end
```

**Comment by maxim-belkin** [comment]
@sjackman Another fix:
```
$ git diff
diff --git a/Library/Homebrew/test.rb b/Library/Homebrew/test.rb
index a4923802be..46a41a49de 100644
--- a/Library/Homebrew/test.rb
+++ b/Library/Homebrew/test.rb
@@ -17,7 +17,8 @@ begin
   ENV.extend(Stdenv)
   formula = ARGV.formulae.first
   if OS.linux?
-    ENV.setup_build_environment(formula)
+    ENV.setup_build_environment
   else
     ENV.setup_build_environment
   end
```

**Comment by sjackman** [comment]
Why doesn't adding the configuration to `.travis.yml` fix this issue?

**Comment by maxim-belkin** [comment]
#2370

**Comment by maxim-belkin** [comment]
rebased on top of #2370

**Comment by maxim-belkin** [comment]
So, still fails. interestingly enough, `brew test git-flow` fails in my tests as well. So, setting global user's name and email had nothing to do with it. See the troubleshooting steps [above](https://github.com/Linuxbrew/homebrew-core/pull/2369#issuecomment-294306033)

**Pull request closed without merging**
