### PR TITLE
Merge 2017-04-20

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
```
=> brew linkage --test geant4
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
No broken dylib links
Unwanted system libraries:
  libGL.so.1
==> FAILED
```

**Comment by maxim-belkin** [comment]
```
==> brew test --verbose libdap
Testing libdap
Error: libdap: failed
libdap cannot be built with any available compilers.
Install Clang or brew install gcc
```

**Comment by maxim-belkin** [comment]
Apparently, `geant4` needs `linuxbrew/xorg/mesa`

**Comment by sjackman** [comment]
We ought to remove `libgl1-mesa-dev` in `circle.yml` and `.travis.yml`.

**Pull request closed without merging**
