### PR TITLE
boost-python: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
Rebased

**Comment by sjackman** [comment]
```
==> brew linkage --test pykep
Missing libraries:
  libboost_date_time-mt.so.1.63.0
  libboost_python-mt.so.1.63.0
  libboost_serialization-mt.so.1.63.0
```
Need to rebuild `pykep`.

**Comment by sjackman** [comment]
Failed to build on CircleCI, but built on TravisCI, oddly.

**Comment by iMichka** [comment]
I have a PR for pykep open, I'll rebase: https://github.com/Homebrew/homebrew-science/pull/6256

**Comment by iMichka** [comment]
Will need to be rebased once boost 1.65.1 is merged

**Comment by iMichka** [comment]
This is building just fine for me locally in the docker container. Trying to reduce the memory usage.

**Pull request closed without merging**
