### PR TITLE
Merge 2017-03-21

### PR DESCRIPTION
**Pull request by maxim-belkin**
- [ ] git
 - [ ] glib-networking
 - [ ] mercurial
 - [ ] translate-shell
 - [ ] vim
 - [ ] yarn

### CODE REVIEW

**Comment by sjackman** [comment]
@maxim-belkin To avoid a period in `master` without a bottle for `git`, which is a core dep of Linuxbrew, would you like to try building a merge PR just for that one formula?
```sh
git checkout -b merge-git
git merge a34bd21
hub pull-request -m "Merge git"
linuxbrew pull --bottle …
```
Since it's only a single formula `linuxbrew pull --bottle` will work and doesn't need `--keep-going`.

**Comment by maxim-belkin** [comment]
https://github.com/Linuxbrew/homebrew-core/pull/2152

**Comment by maxim-belkin** [comment]
I guess I should remove the conflicting commits from this PR

**Comment by maxim-belkin** [comment]
In the light of pushed bottles, closing this PR :)

**Comment by sjackman** [comment]
You'll want to `build-bottle-pr` its conflicts before submitting a new merge PR if you merge someone else's merge PR. Sorry for messing up your merge.

**Comment by sjackman** [comment]
Note there's one more bottle build pending on the previous merge PR, #2148.

**Pull request closed without merging**
