### PR TITLE
Merge 2017-08-26 1713a4e98c

### PR DESCRIPTION
**Pull request by iMichka**
+ [ ] dmd
+ [ ] the_silver_searcher

### CODE REVIEW

**Comment by iMichka** [comment]
```
Checking for basic utility set
Setting up configuration options ... done
Joining in ./make.rc ... ./make-config.sh: 68: ././___tmp18105: Syntax error: EOF in backquote substitution
make: *** [config] Error 1

==> Formula
Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/s-nail.rb
```

```
Installing mitmproxy dependency: perl
==> /home/linuxbrew/.linuxbrew/Cellar/perl/5.26.0_1/bin/cpan -i XML::Parser
... lot of failures
```

```
make
libuv.dylib
SO_LDFLAGS=-Wl,-install_name,/home/linuxbrew/.linuxbrew/Cellar/upscaledb/2.2.0_6/libexec/libuv/lib/libuv.dylib

make: *** No rule to make target `libuv.dylib'.  Stop.

==> Formula
Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/upscaledb.rb
==> Configuration
```

**Comment by sjackman** [comment]
`make libuv.dylib` should be `make libuv.so`

**Comment by sjackman** [comment]
```
/home/linuxbrew/.linuxbrew/Cellar/perl/5.26.0_1/bin/cpan -i XML::Parser
```
I'm thinking that we should remove this from `postinstall` and instead vendor this dependency into any formula that needs it.

**Comment by sjackman** [comment]
```
Joining in ./make.rc ... ./make-config.sh: 68: ././___tmp18105: Syntax error: EOF in backquote substitution
```
`sh` errors are sometimes caused by the default shell on Ubuntu being `dash` rather than `bash`.

**Pull request merged**
