### PR TITLE
glib: Depends on util-linux for libmount.so

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
checking for LIBMOUNT... no
checking libmount/libmount.h usability... no
checking libmount/libmount.h presence... no
checking for libmount/libmount.h... no
configure: error: *** Could not find libmount
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/165137970#L2011

**Comment by rwhogg** [comment]
The `pdf2htmlex` test failed (https://travis-ci.org/Linuxbrew/homebrew-core/builds/165145933#L2851-L2852)

```
/home/linuxbrew/.linuxbrew/Cellar/pdf2htmlex/0.14.6_6/bin/pdf2htmlEX: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
Error: pdf2htmlex: failed
```

This is probably just a missing dependency on `readline` by `pdf2htmlex`, so I'll probably just merge this anyways.

**Comment by rwhogg** [comment]
Nope, I was wrong:

```
linuxbrew@9b51be76cec0:~/.linuxbrew/lib$ grep -ir libreadline.so.6 .
Binary file ./python2.7/lib-dynload/readline.so matches
```

The problem is actually that `python` needs to be rebuilt against the new version of `readline`. Once that's bottled, we have to make a new revision for `pdf2htmlex` so it can be rebuilt from source against Python.

None of this has anything to do with `glib`, so merging.

**Comment by sjackman** [comment]
> Once that's bottled, we have to make a new revision for `pdf2htmlex` so it can be rebuilt from source against Python.

After updating `python`, check `brew linkage pdf2htmlex`. It may not be necessary to rebuild `pdf2htmlex`.

**Comment by sjackman** [comment]
```
$ patchelf --print-needed /gsc/btl/linuxbrew/Cellar/pdf2htmlex/0.14.6_6/bin/pdf2htmlEX
libpoppler.so.63
libcairo.so.2
libfreetype.so.6
libfontforge.so.2
libstdc++.so.6
libm.so.6
libgcc_s.so.1
libc.so.6
```
`pdf2htmlEX` has no direct `readline` dependency. 

Currently `brew linkage` uses `ldd` and reports all recursive dependencies. By default we ought to limit it to only the direct dependencies with an option to recurse.

**Pull request closed without merging**
