### PR TITLE
texlive: new sha256

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
```
=> brew linkage texlive
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libdl.so.2
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /lib/x86_64-linux-gnu/librt.so.1
  /lib64/ld-linux-x86-64.so.2
  /usr/lib/x86_64-linux-gnu/libICE.so.6
  /usr/lib/x86_64-linux-gnu/libSM.so.6
  /usr/lib/x86_64-linux-gnu/libX11.so.6
  /usr/lib/x86_64-linux-gnu/libXaw.so.7
  /usr/lib/x86_64-linux-gnu/libXext.so.6
  /usr/lib/x86_64-linux-gnu/libXmu.so.6
  /usr/lib/x86_64-linux-gnu/libXpm.so.4
  /usr/lib/x86_64-linux-gnu/libXt.so.6
  /usr/lib/x86_64-linux-gnu/libfontconfig.so.1
```

**Comment by maxim-belkin** [comment]
```
==> brew audit texlive --online
Error: 1 problem in 1 formula
texlive:
  * Non-executables were installed to "/home/linuxbrew/.linuxbrew/opt/texlive/bin"
    The offending files are:
      /home/linuxbrew/.linuxbrew/opt/texlive/bin/x86_64-linux
==> FAILED
```

**Comment by sjackman** [comment]
I doubt many people use the X11 features of `texlive`, so I'd rather not make this dependency mandatory. I'd rather just ignore the linkage failure and leave the formula as is.

**Comment by maxim-belkin** [comment]
what about `fontconfig`?

**Comment by sjackman** [comment]
My guess is that `fontconfig` is probably a useful dependency. You could check `brew linkage --reverse texlive` to find out which executable depends on `fontconfig`.

**Comment by maxim-belkin** [comment]
```
$ brew linkage --reverse texlive
/lib64/libc.so.6
  bin/x86_64-linux/afm2pl
  bin/x86_64-linux/afm2tfm
  bin/x86_64-linux/aleph
  bin/x86_64-linux/asy
  bin/x86_64-linux/autosp
  bin/x86_64-linux/bbox
  bin/x86_64-linux/bg5conv
  bin/x86_64-linux/biber
  bin/x86_64-linux/bibtex
  bin/x86_64-linux/bibtex8
  bin/x86_64-linux/bibtexu
  bin/x86_64-linux/cef5conv
  bin/x86_64-linux/cefconv
  bin/x86_64-linux/cefsconv
  bin/x86_64-linux/cfftot1
  bin/x86_64-linux/chktex
  bin/x86_64-linux/ctangle
  bin/x86_64-linux/ctie
  bin/x86_64-linux/cweave
  bin/x86_64-linux/detex
  bin/x86_64-linux/devnag
  bin/x86_64-linux/disdvi
  bin/x86_64-linux/dt2dv
  bin/x86_64-linux/dv2dt
  bin/x86_64-linux/dvi2tty
  bin/x86_64-linux/dvibook
  bin/x86_64-linux/dviconcat
  bin/x86_64-linux/dvicopy
  bin/x86_64-linux/dvidvi
  bin/x86_64-linux/dvilj
  bin/x86_64-linux/dvilj2p
  bin/x86_64-linux/dvilj4
  bin/x86_64-linux/dvilj4l
  bin/x86_64-linux/dvipng
  bin/x86_64-linux/dvipos
  bin/x86_64-linux/dvips
  bin/x86_64-linux/dviselect
  bin/x86_64-linux/dvisvgm
  bin/x86_64-linux/dvitodvi
  bin/x86_64-linux/dvitype
  bin/x86_64-linux/epsffit
  bin/x86_64-linux/eptex
  bin/x86_64-linux/euptex
  bin/x86_64-linux/extconv
  bin/x86_64-linux/gftodvi
  bin/x86_64-linux/gftopk
  bin/x86_64-linux/gftype
  bin/x86_64-linux/gregorio
  bin/x86_64-linux/gsftopk
  bin/x86_64-linux/hbf2gf
  bin/x86_64-linux/kpseaccess
  bin/x86_64-linux/kpsereadlink
  bin/x86_64-linux/kpsestat
  bin/x86_64-linux/kpsewhich
  bin/x86_64-linux/lacheck
  bin/x86_64-linux/luajittex
  bin/x86_64-linux/luatex
  bin/x86_64-linux/mag
  bin/x86_64-linux/makeindex
  bin/x86_64-linux/makejvf
  bin/x86_64-linux/mendex
  bin/x86_64-linux/mf
  bin/x86_64-linux/mf-nowin
  bin/x86_64-linux/mflua
  bin/x86_64-linux/mfluajit
  bin/x86_64-linux/mft
  bin/x86_64-linux/mmafm
  bin/x86_64-linux/mmpfb
  bin/x86_64-linux/mpost
  bin/x86_64-linux/msxlint
  bin/x86_64-linux/odvicopy
  bin/x86_64-linux/odvitype
  bin/x86_64-linux/omfonts
  bin/x86_64-linux/otangle
  bin/x86_64-linux/otfinfo
  bin/x86_64-linux/otftotfm
  bin/x86_64-linux/otp2ocp
  bin/x86_64-linux/outocp
  bin/x86_64-linux/patgen
  bin/x86_64-linux/pbibtex
  bin/x86_64-linux/pdfclose
  bin/x86_64-linux/pdfopen
  bin/x86_64-linux/pdftex
  bin/x86_64-linux/pdftosrc
  bin/x86_64-linux/pdvitype
  bin/x86_64-linux/pfb2pfa
  bin/x86_64-linux/pk2bm
  bin/x86_64-linux/pktogf
  bin/x86_64-linux/pktype
  bin/x86_64-linux/pltotf
  bin/x86_64-linux/pmpost
  bin/x86_64-linux/pmxab
  bin/x86_64-linux/pooltype
  bin/x86_64-linux/ppltotf
  bin/x86_64-linux/prepmx
  bin/x86_64-linux/ps2pk
  bin/x86_64-linux/psbook
  bin/x86_64-linux/psnup
  bin/x86_64-linux/psresize
  bin/x86_64-linux/psselect
  bin/x86_64-linux/pstops
  bin/x86_64-linux/ptex
  bin/x86_64-linux/ptftopl
  bin/x86_64-linux/scor2prt
  bin/x86_64-linux/sjisconv
  bin/x86_64-linux/synctex
  bin/x86_64-linux/t1ascii
  bin/x86_64-linux/t1asm
  bin/x86_64-linux/t1binary
  bin/x86_64-linux/t1disasm
  bin/x86_64-linux/t1dotlessj
  bin/x86_64-linux/t1lint
  bin/x86_64-linux/t1mac
  bin/x86_64-linux/t1rawafm
  bin/x86_64-linux/t1reencode
  bin/x86_64-linux/t1testpage
  bin/x86_64-linux/t1unmac
  bin/x86_64-linux/t4ht
  bin/x86_64-linux/tangle
  bin/x86_64-linux/teckit_compile
  bin/x86_64-linux/tex
  bin/x86_64-linux/tex2xindy
  bin/x86_64-linux/tex4ht
  bin/x86_64-linux/tftopl
  bin/x86_64-linux/tie
  bin/x86_64-linux/ttf2afm
  bin/x86_64-linux/ttf2pk
  bin/x86_64-linux/ttf2tfm
  bin/x86_64-linux/ttfdump
  bin/x86_64-linux/ttftotype42
  bin/x86_64-linux/upbibtex
  bin/x86_64-linux/updvitype
  bin/x86_64-linux/upmendex
  bin/x86_64-linux/upmpost
  bin/x86_64-linux/uppltotf
  bin/x86_64-linux/uptex
  bin/x86_64-linux/uptftopl
  bin/x86_64-linux/vftovp
  bin/x86_64-linux/vlna
  bin/x86_64-linux/vptovf
  bin/x86_64-linux/weave
  bin/x86_64-linux/wofm2opl
  bin/x86_64-linux/wopl2ofm
  bin/x86_64-linux/wovf2ovp
  bin/x86_64-linux/wovp2ovf
  bin/x86_64-linux/xdvi-xaw
  bin/x86_64-linux/xdvipdfmx
  bin/x86_64-linux/xetex
  bin/x86_64-linux/xindy.run
  tlpkg/installer/xz/xz.x86_64-linux
  tlpkg/installer/xz/xzdec.x86_64-linux

/lib64/libcrypt.so.1
  bin/x86_64-linux/xindy.run

/lib64/libdl.so.2
  bin/x86_64-linux/dvisvgm
  bin/x86_64-linux/luajittex
  bin/x86_64-linux/luatex
  bin/x86_64-linux/mflua
  bin/x86_64-linux/mfluajit
  bin/x86_64-linux/xindy.run

/lib64/libgcc_s.so.1
  bin/x86_64-linux/asy
  bin/x86_64-linux/mfluajit

/lib64/libm.so.6
  bin/x86_64-linux/afm2pl
  bin/x86_64-linux/afm2tfm
  bin/x86_64-linux/aleph
  bin/x86_64-linux/asy
  bin/x86_64-linux/bibtex
  bin/x86_64-linux/bibtex8
  bin/x86_64-linux/bibtexu
  bin/x86_64-linux/cfftot1
  bin/x86_64-linux/ctangle
  bin/x86_64-linux/ctie
  bin/x86_64-linux/cweave
  bin/x86_64-linux/dvicopy
  bin/x86_64-linux/dvipng
  bin/x86_64-linux/dvipos
  bin/x86_64-linux/dvips
  bin/x86_64-linux/dvisvgm
  bin/x86_64-linux/dvitype
  bin/x86_64-linux/eptex
  bin/x86_64-linux/euptex
  bin/x86_64-linux/gftodvi
  bin/x86_64-linux/gftopk
  bin/x86_64-linux/gftype
  bin/x86_64-linux/luajittex
  bin/x86_64-linux/luatex
  bin/x86_64-linux/mag
  bin/x86_64-linux/mf
  bin/x86_64-linux/mf-nowin
  bin/x86_64-linux/mflua
  bin/x86_64-linux/mfluajit
  bin/x86_64-linux/mft
  bin/x86_64-linux/mmafm
  bin/x86_64-linux/mmpfb
  bin/x86_64-linux/mpost
  bin/x86_64-linux/odvicopy
  bin/x86_64-linux/odvitype
  bin/x86_64-linux/omfonts
  bin/x86_64-linux/otangle
  bin/x86_64-linux/otfinfo
  bin/x86_64-linux/otftotfm
  bin/x86_64-linux/otp2ocp
  bin/x86_64-linux/outocp
  bin/x86_64-linux/patgen
  bin/x86_64-linux/pbibtex
  bin/x86_64-linux/pdftex
  bin/x86_64-linux/pdftosrc
  bin/x86_64-linux/pdvitype
  bin/x86_64-linux/pfb2pfa
  bin/x86_64-linux/pk2bm
  bin/x86_64-linux/pktogf
  bin/x86_64-linux/pktype
  bin/x86_64-linux/pltotf
  bin/x86_64-linux/pmpost
  bin/x86_64-linux/pmxab
  bin/x86_64-linux/pooltype
  bin/x86_64-linux/ppltotf
  bin/x86_64-linux/ps2pk
  bin/x86_64-linux/ptex
  bin/x86_64-linux/ptftopl
  bin/x86_64-linux/scor2prt
  bin/x86_64-linux/synctex
  bin/x86_64-linux/t1dotlessj
  bin/x86_64-linux/t1lint
  bin/x86_64-linux/t1rawafm
  bin/x86_64-linux/t1reencode
  bin/x86_64-linux/t1testpage
  bin/x86_64-linux/tangle
  bin/x86_64-linux/teckit_compile
  bin/x86_64-linux/tex
  bin/x86_64-linux/tftopl
  bin/x86_64-linux/tie
  bin/x86_64-linux/ttf2afm
  bin/x86_64-linux/ttf2pk
  bin/x86_64-linux/ttf2tfm
  bin/x86_64-linux/ttftotype42
  bin/x86_64-linux/upbibtex
  bin/x86_64-linux/updvitype
  bin/x86_64-linux/upmendex
  bin/x86_64-linux/upmpost
  bin/x86_64-linux/uppltotf
  bin/x86_64-linux/uptex
  bin/x86_64-linux/uptftopl
  bin/x86_64-linux/vftovp
  bin/x86_64-linux/vptovf
  bin/x86_64-linux/weave
  bin/x86_64-linux/wofm2opl
  bin/x86_64-linux/wopl2ofm
  bin/x86_64-linux/wovf2ovp
  bin/x86_64-linux/wovp2ovf
  bin/x86_64-linux/xdvi-xaw
  bin/x86_64-linux/xdvipdfmx
  bin/x86_64-linux/xetex
  bin/x86_64-linux/xindy.run

/lib64/libncurses.so.5
  bin/x86_64-linux/asy
  bin/x86_64-linux/xindy.run

/lib64/libpthread.so.0
  bin/x86_64-linux/asy
  bin/x86_64-linux/xetex
  tlpkg/installer/xz/xz.x86_64-linux
  tlpkg/installer/xz/xzdec.x86_64-linux

/lib64/libreadline.so.5
  bin/x86_64-linux/asy

/lib64/librt.so.1
  bin/x86_64-linux/asy
  tlpkg/installer/xz/xz.x86_64-linux
  tlpkg/installer/xz/xzdec.x86_64-linux

/lib64/libz.so.1
  bin/x86_64-linux/asy

/usr/lib64/libGL.so.1
  bin/x86_64-linux/asy

/usr/lib64/libGLU.so.1
  bin/x86_64-linux/asy

/usr/lib64/libICE.so.6
  bin/x86_64-linux/mf
  bin/x86_64-linux/mflua
  bin/x86_64-linux/mfluajit
  bin/x86_64-linux/xdvi-xaw

/usr/lib64/libSM.so.6
  bin/x86_64-linux/mf
  bin/x86_64-linux/mflua
  bin/x86_64-linux/mfluajit
  bin/x86_64-linux/xdvi-xaw

/usr/lib64/libX11.so.6
  bin/x86_64-linux/mf
  bin/x86_64-linux/mflua
  bin/x86_64-linux/mfluajit
  bin/x86_64-linux/pdfclose
  bin/x86_64-linux/pdfopen
  bin/x86_64-linux/xdvi-xaw

/usr/lib64/libXaw.so.7
  bin/x86_64-linux/xdvi-xaw

/usr/lib64/libXext.so.6
  bin/x86_64-linux/mf
  bin/x86_64-linux/mflua
  bin/x86_64-linux/mfluajit
  bin/x86_64-linux/xdvi-xaw

/usr/lib64/libXmu.so.6
  bin/x86_64-linux/pdfclose
  bin/x86_64-linux/pdfopen
  bin/x86_64-linux/xdvi-xaw

/usr/lib64/libXpm.so.4
  bin/x86_64-linux/xdvi-xaw

/usr/lib64/libXt.so.6
  bin/x86_64-linux/xdvi-xaw

/usr/lib64/libfontconfig.so.1
  bin/x86_64-linux/xetex

/usr/lib64/libstdc++.so.6
  bin/x86_64-linux/asy

libglut.so.3
  bin/x86_64-linux/asy
```

**Comment by sjackman** [comment]
X11 depended on by `mf mflua mfluajit pdfclose pdfopen xdvi-xaw`
GL depended on by `asy`
`fontconfig` depended on by `xetex`
So, yes, it should depend on `fontconfig`, and I don't think it needs to depend on X11.

**Comment by sjackman** [comment]
Looks good to me. :shipit: once CI is 💚

**Pull request closed without merging**
