### PR TITLE
open-mpi 2.1.1 [merge]

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
==> brew test --verbose cerulean
ImportError: No module named matplotlib.pyplot
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/231663176#L3528

**Comment by sjackman** [comment]
```
==> brew fetch --retry gmsh
Download failed: https://linuxbrew.bintray.com/bottles-science/gmsh-2.16.0_1.x86_64_linux.bottle.tar.gz
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/231663176#L4251

**Comment by sjackman** [comment]
```
==> brew test --verbose dl_poly_classic
==> Downloading https://ccpforge.cse.rl.ac.uk/gf/download/frsrelease/145/1314/TEST1.tar.gz
/usr/bin/curl --remote-time --location --user-agent Linuxbrew/1.X.Y (Linux; x86_64 Ubuntu 14.04.5 LTS) curl/7.35.0 --fail --silent https://ccpforge.cse.rl.ac.uk/gf/download/frsrelease/145/1314/TEST1.tar.gz -C 0 -o /home/linuxbrew/.cache/Homebrew/dl_poly_classic--test1-1.tar.gz.incomplete
==> Verifying dl_poly_classic--test1-1.tar.gz checksum
Error: homebrew/science/dl_poly_classic: failed
SHA256 mismatch
Expected: 307e8b17e9709b6df4ed6e8da6d8c383da396e1cedec44e6f36305e0875e0472
Actual: f2176cd29b8116aa27b5c4ce6c1de2f05e58b2c402f26ad43bb3552581e26f92
Archive: /home/linuxbrew/.cache/Homebrew/dl_poly_classic--test1-1.tar.gz
```

**Comment by sjackman** [comment]
```
==> brew test --verbose alpscore
Testing homebrew/science/alpscore
==> mpicxx test.cpp -lalps-accumulators -lalps-hdf5 -lalps-utilities -lalps-params -lboost_filesystem-mt -lboost_system-mt -lboost_program_options-mt -o test
test.cpp:(.text+0x436): undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)'
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/231663176#L4823

**Comment by sjackman** [comment]
These above errors are unrelated to this PR. I'll ignore and merge this PR once PR #2640 is merged.

**Comment by sjackman** [comment]
@tmozgach Could you please look into the download failures of `freec`, `gmsh`, and `dl_poly_classic`?

**Comment by maxim-belkin** [comment]
`dl_poly_classic` is easy:
```
File Download Error
Invalid parameters supplied
```

**Pull request merged**
