### PR TITLE
ffmpeg: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
/usr/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/aom/1.0.0/lib/libaom.a(aom_config.c.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/home/linuxbrew/.linuxbrew/Cellar/aom/1.0.0/lib/libaom.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
ffbuild/library.mak:102: recipe for target 'libavcodec/libavcodec.so.58' failed
make: *** [libavcodec/libavcodec.so.58] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by iMichka** [comment]
Trying to build `aom` with shared libraries here: #11569

**Comment by aswger** [comment]
the latest formula was built just fine in my machine. :smile:
need to reinstall aom etc. before though

`$ brew update`

`$ brew reinstall aom`
```
==> Reinstalling aom                                                                                                                                                                             
==> Downloading https://linuxbrew.bintray.com/bottles/aom-1.0.0.x86_64_linux.bottle.tar.gz                                                                                                       
######################################################################## 100.0%                                                                                                                  
==> Pouring aom-1.0.0.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/aom/1.0.0: 20 files, 5.7MB
```

`brew reinstall vamp-plugins-sdk`
```
==> Reinstalling vamp-plugin-sdk 
==> Downloading https://linuxbrew.bintray.com/bottles/vamp-plugin-sdk-2.7.1.x86_64_linux.bottle.
######################################################################## 100.0%
==> Pouring vamp-plugin-sdk-2.7.1.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/vamp-plugin-sdk/2.7.1: 42 files, 2MB
```

`brew reinstall rubberband`
```
==> Reinstalling rubberband 
==> Downloading https://linuxbrew.bintray.com/bottles/rubberband-1.8.2_1.x86_64_linux.bottle.tar
Already downloaded: /home/agus/.cache/Homebrew/downloads/5e4147686b409d0fd1578bf70e93a9c11a32489dacbd334c370f88d0a536a173--rubberband-1.8.2_1.x86_64_linux.bottle.tar.gz
==> Pouring rubberband-1.8.2_1.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/rubberband/1.8.2_1: 19 files, 1.9MB
```

`brew reinstall ffmpeg`
```
==> Reinstalling ffmpeg 
==> Downloading https://ffmpeg.org/releases/ffmpeg-4.1.1.tar.xz
Already downloaded: /home/agus/.cache/Homebrew/downloads/399f9086b56b6ae907cc16a59daaccda1e96dae3978b21905cbc48e9e11546b5--ffmpeg-4.1.1.tar.xz
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/ffmpeg/4.1.1 --enable-shared --enable
==> make install
==> make alltools
🍺  /home/linuxbrew/.linuxbrew/Cellar/ffmpeg/4.1.1: 282 files, 62.1MB, built in 22 minutes 12 seconds
```

**Comment by aswger** [comment]
also the dynamic linking to libaom was done well. All using latest formula in master

`$ ldd /home/linuxbrew/.linuxbrew/bin/ffmpeg`
```
	linux-vdso.so.1 (0x00007ffda775a000)
	libavdevice.so.58 => /home/linuxbrew/.linuxbrew/lib/libavdevice.so.58 (0x00007fd830bfd000)
	libavfilter.so.7 => /home/linuxbrew/.linuxbrew/lib/libavfilter.so.7 (0x00007fd83073d000)
	libavformat.so.58 => /home/linuxbrew/.linuxbrew/lib/libavformat.so.58 (0x00007fd830320000)
	libavcodec.so.58 => /home/linuxbrew/.linuxbrew/lib/libavcodec.so.58 (0x00007fd82ed76000)
	libavresample.so.4 => /home/linuxbrew/.linuxbrew/lib/libavresample.so.4 (0x00007fd82eb56000)
	libpostproc.so.55 => /home/linuxbrew/.linuxbrew/lib/libpostproc.so.55 (0x00007fd82e93d000)
	libswresample.so.3 => /home/linuxbrew/.linuxbrew/lib/libswresample.so.3 (0x00007fd82e71f000)
	libswscale.so.5 => /home/linuxbrew/.linuxbrew/lib/libswscale.so.5 (0x00007fd82e496000)
	libavutil.so.56 => /home/linuxbrew/.linuxbrew/lib/libavutil.so.56 (0x00007fd82e230000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd82de92000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd82dc73000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd82d882000)
	libxcb.so.1 => /home/linuxbrew/.linuxbrew/lib/libxcb.so.1 (0x00007fd82d654000)
	libxcb-shm.so.0 => /home/linuxbrew/.linuxbrew/lib/libxcb-shm.so.0 (0x00007fd82d44f000)
	libxcb-shape.so.0 => /home/linuxbrew/.linuxbrew/lib/libxcb-shape.so.0 (0x00007fd82d24a000)
	libxcb-xfixes.so.0 => /home/linuxbrew/.linuxbrew/lib/libxcb-xfixes.so.0 (0x00007fd82d040000)
	libasound.so.2 => /usr/lib/x86_64-linux-gnu/libasound.so.2 (0x00007fd82cd39000)
	libSDL2-2.0.so.0 => /home/linuxbrew/.linuxbrew/lib/libSDL2-2.0.so.0 (0x00007fd82ca1c000)
	libXv.so.1 => /home/linuxbrew/.linuxbrew/lib/libXv.so.1 (0x00007fd82c816000)
	libX11.so.6 => /home/linuxbrew/.linuxbrew/lib/libX11.so.6 (0x00007fd82c4fc000)
	libXext.so.6 => /home/linuxbrew/.linuxbrew/lib/libXext.so.6 (0x00007fd82c2eb000)
	librubberband.so.2 => /home/linuxbrew/.linuxbrew/lib/librubberband.so.2 (0x00007fd82c0af000)
	libtesseract.so.4 => /home/linuxbrew/.linuxbrew/lib/libtesseract.so.4 (0x00007fd82b887000)
	libass.so.9 => /home/linuxbrew/.linuxbrew/lib/libass.so.9 (0x00007fd82b651000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd82b44d000)
	libfontconfig.so.1 => /home/linuxbrew/.linuxbrew/lib/libfontconfig.so.1 (0x00007fd82b206000)
	libfreetype.so.6 => /home/linuxbrew/.linuxbrew/lib/libfreetype.so.6 (0x00007fd82af5c000)
	libbz2.so.1.0 => /home/linuxbrew/.linuxbrew/lib/libbz2.so.1.0 (0x00007fd82ad4b000)
	libbluray.so.2 => /home/linuxbrew/.linuxbrew/lib/libbluray.so.2 (0x00007fd82ab02000)
	libz.so.1 => /home/linuxbrew/.linuxbrew/lib/libz.so.1 (0x00007fd82a8ed000)
	libgnutls.so.30 => /home/linuxbrew/.linuxbrew/lib/libgnutls.so.30 (0x00007fd82a539000)
	librtmp.so.1 => /home/linuxbrew/.linuxbrew/lib/librtmp.so.1 (0x00007fd82a31b000)
	liblzma.so.5 => /home/linuxbrew/.linuxbrew/lib/liblzma.so.5 (0x00007fd82a0f4000)
	libopencore-amrwb.so.0 => /home/linuxbrew/.linuxbrew/lib/libopencore-amrwb.so.0 (0x00007fd829edf000)
	libsnappy.so.1 => /home/linuxbrew/.linuxbrew/lib/libsnappy.so.1 (0x00007fd829cc4000)
	libaom.so.0 => /home/linuxbrew/.linuxbrew/lib/libaom.so.0 (0x00007fd8295b2000)
	libmp3lame.so.0 => /home/linuxbrew/.linuxbrew/lib/libmp3lame.so.0 (0x00007fd82931d000)
	libopencore-amrnb.so.0 => /home/linuxbrew/.linuxbrew/lib/libopencore-amrnb.so.0 (0x00007fd8290f2000)
	libopenjp2.so.7 => /home/linuxbrew/.linuxbrew/lib/libopenjp2.so.7 (0x00007fd828e9d000)
	libopus.so.0 => /home/linuxbrew/.linuxbrew/lib/libopus.so.0 (0x00007fd828c44000)
	libspeex.so.1 => /home/linuxbrew/.linuxbrew/lib/libspeex.so.1 (0x00007fd828a2e000)
	libtheoraenc.so.1 => /home/linuxbrew/.linuxbrew/lib/libtheoraenc.so.1 (0x00007fd8287e9000)
	libtheoradec.so.1 => /home/linuxbrew/.linuxbrew/lib/libtheoradec.so.1 (0x00007fd8285cc000)
	libvorbis.so.0 => /home/linuxbrew/.linuxbrew/lib/libvorbis.so.0 (0x00007fd828392000)
	libvorbisenc.so.2 => /home/linuxbrew/.linuxbrew/lib/libvorbisenc.so.2 (0x00007fd8280e4000)
	libx264.so.155 => /home/linuxbrew/.linuxbrew/lib/libx264.so.155 (0x00007fd827c1f000)
	libx265.so.169 => /home/linuxbrew/.linuxbrew/lib/libx265.so.169 (0x00007fd826a9a000)
	libxvidcore.so.4 => /home/linuxbrew/.linuxbrew/lib/libxvidcore.so.4 (0x00007fd8267ae000)
	libsoxr.so.0 => /home/linuxbrew/.linuxbrew/lib/libsoxr.so.0 (0x00007fd826501000)
	/home/linuxbrew/.linuxbrew/lib/ld.so => /lib64/ld-linux-x86-64.so.2 (0x00007fd831055000)
	libXau.so.6 => /home/linuxbrew/.linuxbrew/lib/libXau.so.6 (0x00007fd8262fd000)
	libXdmcp.so.6 => /home/linuxbrew/.linuxbrew/lib/libXdmcp.so.6 (0x00007fd8260f6000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fd825eee000)
	libXcursor.so.1 => /home/linuxbrew/.linuxbrew/lib/libXcursor.so.1 (0x00007fd825ce2000)
	libXinerama.so.1 => /home/linuxbrew/.linuxbrew/lib/libXinerama.so.1 (0x00007fd825ade000)
	libXi.so.6 => /home/linuxbrew/.linuxbrew/lib/libXi.so.6 (0x00007fd8258cf000)
	libXrandr.so.2 => /home/linuxbrew/.linuxbrew/lib/libXrandr.so.2 (0x00007fd8256c4000)
	libXss.so.1 => /home/linuxbrew/.linuxbrew/lib/libXss.so.1 (0x00007fd8254bf000)
	libXxf86vm.so.1 => /home/linuxbrew/.linuxbrew/lib/libXxf86vm.so.1 (0x00007fd8252b9000)
	libsamplerate.so.0 => /home/linuxbrew/.linuxbrew/lib/libsamplerate.so.0 (0x00007fd824f4c000)
	libfftw3.so.3 => /home/linuxbrew/.linuxbrew/lib/libfftw3.so.3 (0x00007fd824bc1000)
	libstdc++.so.6 => /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6 (0x00007fd824804000)
	libgcc_s.so.1 => /home/linuxbrew/.linuxbrew/lib/libgcc_s.so.1 (0x00007fd8245ed000)
	liblept.so.5 => /home/linuxbrew/.linuxbrew/lib/liblept.so.5 (0x00007fd824154000)
	libgomp.so.1 => /home/linuxbrew/.linuxbrew/lib/libgomp.so.1 (0x00007fd823f31000)
	libfribidi.so.0 => /home/linuxbrew/.linuxbrew/lib/libfribidi.so.0 (0x00007fd823d14000)
	libharfbuzz.so.0 => /home/linuxbrew/.linuxbrew/lib/libharfbuzz.so.0 (0x00007fd823a01000)
	libexpat.so.1 => /home/linuxbrew/.linuxbrew/lib/libexpat.so.1 (0x00007fd8237d6000)
	libuuid.so.1 => /home/linuxbrew/.linuxbrew/lib/libuuid.so.1 (0x00007fd8235ce000)
	libpng16.so.16 => /home/linuxbrew/.linuxbrew/lib/libpng16.so.16 (0x00007fd823399000)
	libxml2.so.2 => /home/linuxbrew/.linuxbrew/lib/libxml2.so.2 (0x00007fd82302b000)
	libp11-kit.so.0 => /home/linuxbrew/.linuxbrew/lib/libp11-kit.so.0 (0x00007fd822cf9000)
	libunistring.so.2 => /home/linuxbrew/.linuxbrew/lib/libunistring.so.2 (0x00007fd822974000)
	libtasn1.so.6 => /home/linuxbrew/.linuxbrew/lib/libtasn1.so.6 (0x00007fd822760000)
	libnettle.so.6 => /home/linuxbrew/.linuxbrew/lib/libnettle.so.6 (0x00007fd822525000)
	libhogweed.so.4 => /home/linuxbrew/.linuxbrew/lib/libhogweed.so.4 (0x00007fd8222eb000)
	libgmp.so.10 => /home/linuxbrew/.linuxbrew/lib/libgmp.so.10 (0x00007fd822070000)
	libssl.so.1.0.0 => /home/linuxbrew/.linuxbrew/lib/libssl.so.1.0.0 (0x00007fd821dfe000)
	libcrypto.so.1.0.0 => /home/linuxbrew/.linuxbrew/lib/libcrypto.so.1.0.0 (0x00007fd8219ab000)
	libogg.so.0 => /home/linuxbrew/.linuxbrew/lib/libogg.so.0 (0x00007fd8217a3000)
	libXrender.so.1 => /home/linuxbrew/.linuxbrew/lib/libXrender.so.1 (0x00007fd821599000)
	libXfixes.so.3 => /home/linuxbrew/.linuxbrew/lib/libXfixes.so.3 (0x00007fd821392000)
	libjpeg.so.9 => /home/linuxbrew/.linuxbrew/lib/libjpeg.so.9 (0x00007fd821155000)
	libgif.so.7 => /home/linuxbrew/.linuxbrew/lib/libgif.so.7 (0x00007fd820f4a000)
	libtiff.so.5 => /home/linuxbrew/.linuxbrew/lib/libtiff.so.5 (0x00007fd820cd1000)
	libwebp.so.7 => /home/linuxbrew/.linuxbrew/lib/libwebp.so.7 (0x00007fd820a61000)
	libglib-2.0.so.0 => /home/linuxbrew/.linuxbrew/lib/libglib-2.0.so.0 (0x00007fd820739000)
	libgraphite2.so.3 => /home/linuxbrew/.linuxbrew/lib/libgraphite2.so.3 (0x00007fd820514000)
	libbsd.so.0 => /home/linuxbrew/.linuxbrew/lib/libbsd.so.0 (0x00007fd820301000)
	libffi.so.6 => /home/linuxbrew/.linuxbrew/lib/libffi.so.6 (0x00007fd8200f8000)
	libpcre.so.1 => /home/linuxbrew/.linuxbrew/lib/libpcre.so.1 (0x00007fd81fe86000)
```

**Comment by retokromer** [comment]
>the latest formula was built just fine in my machine. 😄

No problems here either (Debian 9.5, Ubuntu 18.04.1 LTS and Slackware 14.2).

**Comment by iMichka** [comment]
Bottles uploaded!

Yes, you may need to rebuild `vamp-plugins-sdk`, `aom` and `rubberband` to get this working.

Thanks to all for your patience and help.

**Pull request closed without merging**
