### PR TITLE
Merge 2017-08-16 ebd609e714

### PR DESCRIPTION
**Pull request by sjackman**
+ [ ] advancecomp
+ [ ] babl
+ [ ] dmd
+ [ ] dub
+ [ ] fig2dev
+ [ ] inetutils
+ [ ] netpbm
+ [ ] zimg

### CODE REVIEW

**Comment by iMichka** [comment]
dmd:

```
make -C src -f posix.mak
make[1]: Entering directory `/tmp/dmd-20170816-18619-r3zwsh/dmd-2.075.1/src'
c++ -Wno-deprecated -Wstrict-aliasing -fno-exceptions -fno-rtti -D__pascal= -DMARS=1 -DTARGET_LINUX=1 -DDM_TARGET_CPU_X86=1 -m64 -std=gnu++98 -O2 -Iddmd/tk ddmd/backend/optabgen.c -o ../generated/linux/release/64/optabgen
  (CC)  ROOT_OBJS  ddmd/root/newdelete.c
c++ -c -o../generated/linux/release/64/newdelete.o -Wno-deprecated -Wstrict-aliasing -fno-exceptions -fno-rtti -D__pascal= -DMARS=1 -DTARGET_LINUX=1 -DDM_TARGET_CPU_X86=1 -m64 -std=gnu++98 -O2 -Iddmd/root -MMD -MF ../generated/linux/release/64/newdelete.deps ddmd/root/newdelete.c
mkdir -p /tmp/.host_dmd-2.072.2
TMPFILE=$(mktemp deleteme.XXXXXXXX) &&	curl -fsSL http://downloads.dlang.org/releases/2.x/2.072.2/dmd.2.072.2.linux.zip > ${TMPFILE}.zip && \
		unzip -qd /tmp/.host_dmd-2.072.2 ${TMPFILE}.zip && rm ${TMPFILE}.zip;
[ -f ../generated/linux/release/64/dmd.conf ] || echo "$DEFAULT_DMD_CONF" > ../generated/linux/release/64/dmd.conf
../generated/linux/release/64/optabgen
OPTABGEN... generating files
mv debtab.c optab.c cdxxx.c elxxx.c fltables.c tytab.c ../generated/linux/release/64
/bin/sh: 2: unzip: not found
make[1]: *** [/tmp/.host_dmd-2.072.2/dmd2/linux/bin64/dmd] Error 127
```

`dub` needs `dmd`

**Comment by sjackman** [comment]
`dmd` depends on `unzip`.

**Comment by iMichka** [comment]
Yes: https://github.com/Linuxbrew/homebrew-core/pull/3848

**Comment by iMichka** [comment]
And dub: #3849

**Pull request merged**
