### PR TITLE
mfx-dispatch 1.23 (new formula)

### PR DESCRIPTION
**Pull request by half2me**
- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
Hi. We do not accept new formulae here as this repository will be closed end of the month. 

You can either submit this to homebrew core or host it in your own tap.

**Comment by half2me** [comment]
@iMichka it will be closed? Why?

**Comment by iMichka** [comment]
There is some discussion here: https://github.com/Homebrew/homebrew-science/issues/6365

Mostly because lack of resources and energy to keep high quality formulae in this repository.

**Comment by half2me** [comment]
@iMichka I understand. Since we make use of certain applications at my workplace, I would be glad to help out with those formulas. (Bumping versions, or fixing any reported bugs) I'll start out with my own tap at first, and maybe add PRs for existing formulae that I have modified.

**Pull request closed without merging**
