### PR TITLE
rust: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by xu-cheng** [comment]
You probably need

```diff
diff --git a/Formula/rust.rb b/Formula/rust.rb
index dc13fc3e5d..8bbde1771f 100644
--- a/Formula/rust.rb
+++ b/Formula/rust.rb
@@ -44,7 +44,7 @@ class Rust < Formula
   unless OS.mac?
     depends_on "binutils"
     depends_on "curl"
-    depends_on "python"
+    depends_on "python@2"
     depends_on "zlib"
   end
```

**Comment by iMichka** [comment]
Would python3 not work?

I will need anyway to build the bottle locally, because circle is not powerful enough to build this.

**Comment by xu-cheng** [comment]
I am afraid that python 2 is require. 

Ref: https://github.com/rust-lang/rust#building-from-source

**Comment by iMichka** [comment]
Okay, too bad. But actually not my problem, they have until 2020 to fix it. I'll make the change to python 2 then.

**Pull request closed without merging**
