### PR TITLE
Merge 2017-06-12

### PR DESCRIPTION
**Pull request by maxim-belkin**
Conflicts:
 - [ ]	Formula/armor.rb
 - [ ]	Formula/autojump.rb
 - [ ]	Formula/conan.rb
 - [ ]	Formula/dialog.rb
 - [ ]	Formula/dovecot.rb
 - [ ]	Formula/freetds.rb
 - [ ]	Formula/imagemagick.rb
 - [ ]	Formula/kops.rb

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Travis:
monit
```
configure: error: PAM enabled but headers or library not found, install the PAM development support or run configure --without-pam
```

**Comment by maxim-belkin** [comment]
```
Could not symlink bin/annotate
Target /home/linuxbrew/.linuxbrew/bin/annotate
is a symlink belonging to mummer. You can unlink it:
  brew unlink mummer

To force the link and overwrite all conflicting files:
  brew link --overwrite gd

To list all files that would be deleted:
  brew link --overwrite --dry-run gd
```

**Comment by maxim-belkin** [comment]
I don't understand this failure:
```
==> Installing homebrew/science/mir-prefer 
==> Downloading https://linuxbrew.bintray.com/bottles-science/mir-prefer-0.24_1.x86_64_linux.bottle.tar.gz
Already downloaded: /home/ubuntu/.cache/Homebrew/mir-prefer-0.24_1.x86_64_linux.bottle.tar.gz
==> Verifying mir-prefer-0.24_1.x86_64_linux.bottle.tar.gz checksum
==> Pouring mir-prefer-0.24_1.x86_64_linux.bottle.tar.gz
tar xzf /home/ubuntu/.cache/Homebrew/mir-prefer-0.24_1.x86_64_linux.bottle.tar.gz
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/lib --set-interpreter /home/linuxbrew/.linuxbrew/lib/ld.so /home/linuxbrew/.linuxbrew/Cellar/mir-prefer/0.24_1/dependency/Linux/x32/RNALfold
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/lib --set-interpreter /home/linuxbrew/.linuxbrew/lib/ld.so /home/linuxbrew/.linuxbrew/Cellar/mir-prefer/0.24_1/dependency/Linux/x64/RNALfold
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew:/home/linuxbrew/.linuxbrew/opt/ncurses/lib:/home/linuxbrew/.linuxbrew/opt/zlib/lib:/home/linuxbrew/.linuxbrew/lib --set-interpreter /home/linuxbrew/.linuxbrew/lib/ld.so /home/linuxbrew/.linuxbrew/Cellar/mir-prefer/0.24_1/dependency/Linux/x64/samtools
==> Finishing up
ln -s ../Cellar/mir-prefer/0.24_1/bin/miR_PREFeR miR_PREFeR
ln -s ../Cellar/mir-prefer/0.24_1/bin/miR_PREFeR.py miR_PREFeR.py
==> Summary
/home/linuxbrew/.linuxbrew/Cellar/mir-prefer/0.24_1: 23 files, 14.1MB
==> FAILED
```

**Comment by maxim-belkin** [comment]
Did someone forget HDF5 dep?
```
==> brew test --verbose shogun
Testing homebrew/science/shogun
==> /home/linuxbrew/.linuxbrew/bin/g++-5 -std=c++11 -I/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/include test.cpp -o test -L/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib -lshogun
.
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/shogun/test.01.g++-5:
2017-06-13 21:17:06 +0000

/home/linuxbrew/.linuxbrew/bin/g++-5
-std=c++11
-I/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/include
test.cpp
-o
test
-L/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib
-lshogun

/home/linuxbrew/.linuxbrew/bin/ld: warning: libhdf5.so.100, needed by /home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so, not found (try using -rpath or -rpath-link)
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5T_NATIVE_INT16_g'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Sselect_elements'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Dread'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Sget_simple_extent_ndims'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5T_NATIVE_SCHAR_g'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5T_NATIVE_INT64_g'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Eset_auto2'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Screate_simple'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Aget_type'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Fcreate'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5T_NATIVE_UCHAR_g'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Screate'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Tget_size'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Tcreate'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5T_NATIVE_UINT16_g'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Dwrite'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5T_STD_REF_OBJ_g'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Tvlen_create'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Awrite'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Fclose'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5T_NATIVE_LDOUBLE_g'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Aexists'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Tinsert'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Tequal'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Gclose'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5check_version'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Aopen'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Dget_space'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Tget_class'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5T_C_S1_g'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Sget_simple_extent_npoints'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Gcreate2'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5T_NATIVE_UINT64_g'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Aget_space'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Tcopy'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Sselect_none'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Tclose'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5T_NATIVE_UINT8_g'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5T_NATIVE_ULLONG_g'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Rcreate'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5T_NATIVE_UINT32_g'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5T_NATIVE_LLONG_g'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Sclose'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Dopen2'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Dget_type'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5T_NATIVE_DOUBLE_g'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Aread'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Dclose'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5open'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5T_NATIVE_FLOAT_g'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5T_NATIVE_HBOOL_g'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Sget_simple_extent_dims'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Gopen2'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Dcreate2'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5T_NATIVE_INT8_g'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Fopen'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5T_NATIVE_INT32_g'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Sget_simple_extent_type'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Aclose'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Tset_size'
/home/linuxbrew/.linuxbrew/Cellar/shogun/6.0.0/lib/libshogun.so: undefined reference to `H5Acreate2'
```

**Comment by maxim-belkin** [comment]
oopsie
```
==> Installing swrcfit from homebrew/science
Error: homebrew/science/swrcfit contains conflicting version recursive dependencies:
  openssl, openssl@1.1
View these with `brew deps --tree homebrew/science/swrcfit`.
==> FAILED
```

**Comment by maxim-belkin** [comment]
libgit2
```
==> Summary
/home/linuxbrew/.linuxbrew/Cellar/libgit2-glib/0.25.0: 150 files, 2.9MB
==> brew linkage --test libgit2-glib
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
No broken dylib links
No unwanted system libraries
==> brew test --verbose libgit2-glib
Testing libgit2-glib
==> git init
.
==> /home/linuxbrew/.linuxbrew/Cellar/libgit2-glib/0.25.0/libexec/general /tmp/libgit2-glib-test-20170613-65453-1udngyj/horatio
.
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/libgit2-glib/test.02.general:
2017-06-13 22:00:46 +0000

/home/linuxbrew/.linuxbrew/Cellar/libgit2-glib/0.25.0/libexec/general
/tmp/libgit2-glib-test-20170613-65453-1udngyj/horatio

/home/linuxbrew/.linuxbrew/Cellar/libgit2-glib/0.25.0/libexec/general: line 202: cd: /tmp/libgit2-glib-20170524-89601-jpp0w9/libgit2-glib-0.25.0/examples: No such file or directory
gcc-4.8: error: general.o: No such file or directory
gcc-4.8: error: ../libgit2-glib/.libs/libgit2-glib-1.0.so: No such file or directory
Error: libgit2-glib: failed
```

**Comment by maxim-belkin** [comment]
no bottles have been built 😢

**Comment by sjackman** [comment]
> `Could not symlink bin/annotate`

@tmozgach resolved this issue in the merged PR https://github.com/Homebrew/homebrew-science/pull/5795

**Pull request closed without merging**
