### PR TITLE
guile: Depends on gperf

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
gperf -m 10 ./iconv_open-hpux.gperf > ./iconv_open-hpux.h-t
  GEN      configmake.h
/bin/bash: gperf: command not found
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/127086871#L2062

**Comment by sjackman** [comment]
Timed out
```
==> brew install --build-bottle --verbose guile
==> Downloading http://ftpmirror.gnu.org/guile/guile-2.0.11.tar.xz
Already downloaded: /home/ubuntu/.cache/Homebrew/guile-2.0.11.tar.xz
==> Verifying guile-2.0.11.tar.xz checksum
==> ./configure --disable-dependency-tracking --prefix=/home/linuxbrew/.linuxbrew/Cellar/guile/2.0.11_2 --with-libreadline-prefix=/home/linuxbrew/.linuxbrew/opt/readline --with-libgmp-prefix=/home/linuxbrew/.linuxbrew/opt/gmp
.
==> make install
..
command umask 022; PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"; brew install patchelf && brew test-bot --keep-old --verbose took more than 10 minutes since last output
```

**Comment by maxim-belkin** [comment]
I'll investigate this one...

**Comment by maxim-belkin** [comment]
I was able to build `guile --devel` locally. It took 65 minutes

**Comment by sjackman** [comment]
Thanks, Maxim.

**Pull request closed without merging**
