### PR TITLE
Merge 2018-01-24 1202fc7892

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
HEAD is now at 6c7fdbf xcb-proto: update 1.12_1 bottle for Linuxbrew.
Error: undefined method `default_formula?' for #<OsxfuseRequirement: "osxfuse" []>
```

**Comment by sjackman** [comment]
I think we need to merge `Homebrew/test-bot` into `Linuxbrew/test-bot`. I think that the method `Requirement::default_formula?` no longer exists.

**Comment by iMichka** [comment]
Okay merge is done, here is the first error:
```
Error: undefined method `git' for #<Homebrew::Test:0x00000003286358>
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-test-bot/cmd/brew-test-bot.rb:399:in `merge_commit?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-test-bot/cmd/brew-test-bot.rb:454:in `download'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-test-bot/cmd/brew-test-bot.rb:1141:in `run'
```

**Comment by sjackman** [comment]
Replace
```ruby
git(…)
```
with
```ruby
Utils.popen_read("git", …)
```
in each of its three occurrences.

**Comment by iMichka** [comment]
https://github.com/Linuxbrew/homebrew-test-bot/pull/63

**Comment by iMichka** [comment]
```
==> brew uses --recursive cryfs
..
==> SKIPPING: cryfs
libfuse is required to install this formula.
Run "brew install libfuse" to install it.
```

That's because cryfs depends_on :osxfuse, so this is fine.

**Comment by sjackman** [comment]
There are 33 occurrences of `depends_on :osxfuse` in core. I can fix up Linuxbrew/brew so that `depends_on :osxfuse` installs `libfuse` on Linux.

**Comment by iMichka** [comment]
Yes, I think this will be needed, if it is not too complicated.

I bet upstream will be dropping that requirement too one day, but I'll let them do the change first :)

**Pull request merged**
