### PR TITLE
gsettings-desktop-schemas: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
This one will probably need `atk`

**Comment by sjackman** [comment]
`atk` is bottled.

**Comment by maxim-belkin** [comment]
I mean adding `atk` as a dependency

**Comment by sjackman** [comment]
Ah, gotcha. Why is `atk` needed as a dep on Linux but not on Mac?

**Comment by maxim-belkin** [comment]
dunno. Perhaps, upstream didn't catch it because they've got it (somehow).

**Comment by rwhogg** [comment]
> dunno. Perhaps, upstream didn't catch it because they've got it (somehow).

GTK+3 does depend on `atk` upstream, but `gsettings-desktop-schemas` doesn't. `brew linkage gsettings-desktop-schemas` doesn't report anything on a Mac, presumably because this formula has no binaries or libraries.

**Pull request closed without merging**
