### PR TITLE
lua: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
make
install
INSTALL_TOP=/home/linuxbrew/.linuxbrew/Cellar/lua/5.3.5
INSTALL_INC=/home/linuxbrew/.linuxbrew/Cellar/lua/5.3.5/include/lua
INSTALL_MAN=/home/linuxbrew/.linuxbrew/Cellar/lua/5.3.5/share/man/man1
TO_LIB=liblua.a liblua.so liblua.so.5.3 liblua.so.5.3.5

cd src && mkdir -p /home/linuxbrew/.linuxbrew/Cellar/lua/5.3.5/bin /home/linuxbrew/.linuxbrew/Cellar/lua/5.3.5/include/lua /home/linuxbrew/.linuxbrew/Cellar/lua/5.3.5/lib /home/linuxbrew/.linuxbrew/Cellar/lua/5.3.5/share/man/man1 /home/linuxbrew/.linuxbrew/Cellar/lua/5.3.5/share/lua/5.3 /home/linuxbrew/.linuxbrew/Cellar/lua/5.3.5/lib/lua/5.3
cd src && install -p -m 0755 lua luac /home/linuxbrew/.linuxbrew/Cellar/lua/5.3.5/bin
cd src && install -p -m 0644 lua.h luaconf.h lualib.h lauxlib.h lua.hpp /home/linuxbrew/.linuxbrew/Cellar/lua/5.3.5/include/lua
cd src && install -p -m 0644 liblua.a liblua.so liblua.so.5.3 liblua.so.5.3.5 /home/linuxbrew/.linuxbrew/Cellar/lua/5.3.5/lib
install: cannot stat 'liblua.so.5.3.5': No such file or directory
Makefile:61: recipe for target 'install' failed
make: *** [install] Error 1

==> Formula
Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/lua.rb
```

**Comment by iMichka** [comment]
Maybe this:
```
==> Verifying lua--patch-b9bba9d10ed5d34335c831972a02ec48471ca1dbf95230edc13fe5f575d5542c.patch checksum
==> Patching
==> Applying lua.patch
patch -g 0 -f -p1 -i /tmp/lua--patch-20180711-6515-qxbhy/lua.patch
patching file Makefile
patching file src/Makefile
patch unexpectedly ends in middle of line
```

**Comment by jbadomics** [comment]
I'm getting the same error

<details>
<summary>install error</summary>

```
brew install lua
==> Downloading https://www.lua.org/ftp/lua-5.3.5.tar.gz
Already downloaded: /panfs/roc/groups/1/bonddr/jbadalam/.cache/Homebrew/lua-5.3.5.tar.gz
==> Downloading https://gist.githubusercontent.com/iMichka/baa7e609848d8eb9fc063c3bf664b5bf/raw/56a4b4993b30c533585b706b2465ff86a71995e7/lua.patch
Already downloaded: /panfs/roc/groups/1/bonddr/jbadalam/.cache/Homebrew/lua--patch-b9bba9d10ed5d34335c831972a02ec48471ca1dbf95230edc13fe5f575d5542c.patch
==> Patching
==> Applying lua.patch
patching file Makefile
patching file src/Makefile
patch unexpectedly ends in middle of line
==> make linux INSTALL_TOP=/panfs/roc/groups/1/bonddr/jbadalam/.linuxbrew/Cellar/lua/5.3.5 INSTALL_INC=/panfs/roc/groups/1/bonddr/jbadalam/.linuxbrew/Cellar/lua
==> make install INSTALL_TOP=/panfs/roc/groups/1/bonddr/jbadalam/.linuxbrew/Cellar/lua/5.3.5 INSTALL_INC=/panfs/roc/groups/1/bonddr/jbadalam/.linuxbrew/Cellar/l
Last 15 lines from /panfs/roc/groups/1/bonddr/jbadalam/.cache/Homebrew/Logs/lua/02.make:
2018-07-31 13:35:48 -0500

make
install
INSTALL_TOP=/panfs/roc/groups/1/bonddr/jbadalam/.linuxbrew/Cellar/lua/5.3.5
INSTALL_INC=/panfs/roc/groups/1/bonddr/jbadalam/.linuxbrew/Cellar/lua/5.3.5/include/lua
INSTALL_MAN=/panfs/roc/groups/1/bonddr/jbadalam/.linuxbrew/Cellar/lua/5.3.5/share/man/man1
TO_LIB=liblua.a liblua.so liblua.so.5.3 liblua.so.5.3.5

cd src && mkdir -p /panfs/roc/groups/1/bonddr/jbadalam/.linuxbrew/Cellar/lua/5.3.5/bin /panfs/roc/groups/1/bonddr/jbadalam/.linuxbrew/Cellar/lua/5.3.5/include/lua /panfs/roc/groups/1/bonddr/jbadalam/.linuxbrew/Cellar/lua/5.3.5/lib /panfs/roc/groups/1/bonddr/jbadalam/.linuxbrew/Cellar/lua/5.3.5/share/man/man1 /panfs/roc/groups/1/bonddr/jbadalam/.linuxbrew/Cellar/lua/5.3.5/share/lua/5.3 /panfs/roc/groups/1/bonddr/jbadalam/.linuxbrew/Cellar/lua/5.3.5/lib/lua/5.3
cd src && install -p -m 0755 lua luac /panfs/roc/groups/1/bonddr/jbadalam/.linuxbrew/Cellar/lua/5.3.5/bin
cd src && install -p -m 0644 lua.h luaconf.h lualib.h lauxlib.h lua.hpp /panfs/roc/groups/1/bonddr/jbadalam/.linuxbrew/Cellar/lua/5.3.5/include/lua
cd src && install -p -m 0644 liblua.a liblua.so liblua.so.5.3 liblua.so.5.3.5 /panfs/roc/groups/1/bonddr/jbadalam/.linuxbrew/Cellar/lua/5.3.5/lib
install: cannot stat `liblua.so.5.3.5': No such file or directory
make: *** [Makefile:64: install] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
lua: Build a bottle for Linuxbrew https://github.com/Linuxbrew/homebrew-core/pull/8396
```

</details>

<details>
<summary>brew config</summary>

```
HOMEBREW_VERSION: 1.7.1-1-gc46aef1
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: c46aef12fef6a29746df86640628ea2e61f6afe1
Last commit: 24 hours ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 4f0bc9e8a6d6ac3d010f5d6ea6cc755d7966835b
Core tap last commit: 6 minutes ago
HOMEBREW_PREFIX: /panfs/roc/groups/1/bonddr/jbadalam/.linuxbrew
HOMEBREW_REPOSITORY: /panfs/roc/groups/1/bonddr/jbadalam/.linuxbrew
HOMEBREW_CELLAR: /panfs/roc/groups/1/bonddr/jbadalam/.linuxbrew/Cellar
HOMEBREW_CACHE: /panfs/roc/groups/1/bonddr/jbadalam/.cache/Homebrew
HOMEBREW_BOTTLE_DEFAULT_DOMAIN_LINUX: https://linuxbrew.bintray.com
HOMEBREW_BOTTLE_DEFAULT_DOMAIN_MACOS: https://homebrew.bintray.com
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_LOGS: /panfs/roc/groups/1/bonddr/jbadalam/.cache/Homebrew/Logs
CPU: 24-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /panfs/roc/groups/1/bonddr/jbadalam/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: N/A
Git: 2.18.0 => /panfs/roc/groups/1/bonddr/jbadalam/.linuxbrew/bin/git
Curl: 7.19.7 => /usr/bin/curl
Java: N/A
Kernel: Linux 2.6.32-696.30.1.el6.x86_64 x86_64 GNU/Linux
OS: CentOS release 6.9 (Final) (Final)
Host glibc: 2.12
/usr/bin/gcc: 4.4.7
glibc: 2.23
gcc: 5.5.0_4
xorg: 20170115_1
```

</details>

**Comment by VincentZhou98** [comment]
I pass the building by the instruction and patch from the following link [lua-5.3.5](http://www.linuxfromscratch.org/blfs/view/svn/general/lua.html). @iMichka You could try it.

**Comment by iMichka** [comment]
Hey, cool. Thanks. Last time I checked there was no patch for lua 5.3.5. Looks like somebody had some free time to get a new patch out. I obviously had not time.

I will test the patch and update lua as soon as possible.

This patching of lua each version is a real mess ... everybody relies on shared libraries to be there, but upstream does not want to support them ...

**Comment by iMichka** [comment]
```
# Lua version and release.
V= 5.3
R= $V.4
```

Looks like they forgot to bump the version number in the makefile ...

**Comment by iMichka** [comment]
I patched the makefile even more to change the version number.
Linuxfromscratch recommends to use 5.3.4, but I think this is inconsistent (http://www.linuxfromscratch.org/blfs/view/svn/general/lua.html).

I am not able to subscribe to the lua mailing list to report this (my email address is not accepted, I do not know why). I'll just go with 5.3.5 and hope this is what was expected, and there was no specific reason to keep the .so filename at 5.3.4 ...

**Comment by iMichka** [comment]
Done. Until it breaks at the next release. Thanks for your patience.

**Comment by VincentZhou98** [comment]
Nice work!

**Pull request closed without merging**
