### PR TITLE
mkvtoolnix: Depends on libxslt and needs C++14

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
TravisCI
```
checking for DocBook XSL root directory... using supplied /home/linuxbrew/.linuxbrew/opt/docbook-xsl/docbook-xsl
checking for xsltproc... no
configure: error: xsltproc wasn't found
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/208479459

**Comment by sjackman** [comment]
TravisCI timed out while building `depends_on "boost"  => "c++11"`
https://travis-ci.org/Linuxbrew/homebrew-core/builds/208696362#L2637

**Comment by sjackman** [comment]
CircleCI
```
The following features of the C++11/C++14 standards are not supported by /usr/bin/g++-4.8 -std=c++11:
  * std::make_unique function (C++14)
  * digit separators (C++14)
  * binary literals (C++14)
  * generic lambdas (C++14)
If you are using the GNU C compiler collection (gcc) then you need
at least v4.9.x.
configure: error: support for required C++11/C++14 features incomplete
```
https://circleci.com/gh/Linuxbrew/homebrew-core/4254

**Comment by rwhogg** [comment]
Maybe we should merge this without updating the bottle to resolve #2338?

`needs :cxx14` should be available now too, if we want to add that.

**Pull request closed without merging**
