### PR TITLE
open-mpi: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Error <blah>#</blah>1
```
==> brew linkage --test abyss
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libdl.so.2
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
No broken dylib links
Unwanted system libraries:
  libsqlite3.so.0
==> FAILED
```

**Comment by maxim-belkin** [comment]
Error <blah>#</blah>2
```
==> brew test --verbose cerulean
Testing homebrew/science/cerulean
==> python /home/linuxbrew/.linuxbrew/Cellar/cerulean/0.1/libexec/Cerulean.py -h
.
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/cerulean/test.01.python:
2017-05-05 03:50:05 +0000

python
/home/linuxbrew/.linuxbrew/Cellar/cerulean/0.1/libexec/Cerulean.py
-h

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/cerulean/0.1/libexec/Cerulean.py", line 43, in <module>
    from long_contig_graph import LongContigGraph
  File "/home/linuxbrew/.linuxbrew/Cellar/cerulean/0.1/libexec/long_contig_graph.py", line 43, in <module>
    from illumina_graph import Graph
  File "/home/linuxbrew/.linuxbrew/Cellar/cerulean/0.1/libexec/illumina_graph.py", line 50, in <module>
    import matplotlib.pyplot as plt
ImportError: No module named matplotlib.pyplot
Error: homebrew/science/cerulean: failed
Failed executing: python /home/linuxbrew/.linuxbrew/Cellar/cerulean/0.1/libexec/Cerulean.py -h
```

**Comment by maxim-belkin** [comment]
Error <blah>#</blah>3:
```
==> brew test --verbose dl_poly_classic
Testing homebrew/science/dl_poly_classic
==> Downloading https://ccpforge.cse.rl.ac.uk/gf/download/frsrelease/145/1314/TEST1.tar.gz
/usr/bin/curl --remote-time --location --user-agent Linuxbrew/1.1.11-280-gb3d07003e (Linux; x86_64 Ubuntu 14.04.4 LTS) curl/7.35.0 --fail --silent https://ccpforge.cse.rl.ac.uk/gf/download/frsrelease/145/1314/TEST1.tar.gz -C 0 -o /home/ubuntu/.cache/Homebrew/dl_poly_classic--test1-1.tar.gz.incomplete
==> Verifying dl_poly_classic--test1-1.tar.gz checksum
Error: homebrew/science/dl_poly_classic: failed
SHA256 mismatch
Expected: 307e8b17e9709b6df4ed6e8da6d8c383da396e1cedec44e6f36305e0875e0472
Actual: f2176cd29b8116aa27b5c4ce6c1de2f05e58b2c402f26ad43bb3552581e26f92
```

**Comment by maxim-belkin** [comment]
Error <blah>#</blah>4:
```
==> brew linkage --test gmsh
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libdl.so.2
  /lib/x86_64-linux-gnu/libm.so.6
  /usr/lib/libblas.so.3
  /usr/lib/liblapack.so.3
No broken dylib links
Unwanted system libraries:
  libblas.so.3
  liblapack.so.3
==> FAILED
```

**Comment by sjackman** [comment]
None of these errors are caused by bumping `open-mpi`, so merging.

**Pull request closed without merging**
