### PR TITLE
gcc@6: Enable gcc-6 for Linux

### PR DESCRIPTION
**Pull request by kygx-legend**

### CODE REVIEW

**Comment by kygx-legend** [comment]
```
==> ../configure --build=x86_64-apple-darwin3.10.0-327.28.3.el7.x86_64 --prefix=/data/spadm/brew/Cellar/
Last 15 lines from /home/spadm/.cache/Homebrew/Logs/gcc@6/01.configure:
--with-isl=/data/spadm/brew/opt/isl
--with-system-zlib
--enable-stage1-checking
--enable-checking=release
--enable-lto
--with-build-config=bootstrap-debug
--disable-werror
--with-pkgversion=Homebrew GCC 6.4.0
--with-bugurl=https://github.com/Homebrew/homebrew-core/issues
--with-dwarf2
--disable-nls
--enable-multilib

checking build system type... Invalid configuration `x86_64-apple-darwin3.10.0-327.28.3.el7.x86_64': machine `x86_64-apple-darwin3.10.0-327.28.3.el7.x86_64' not recognized
configure: error: /bin/sh ../config.sub x86_64-apple-darwin3.10.0-327.28.3.el7.x86_64 failed
```

**Comment by iMichka** [comment]
Hi. I had a look, the changes look good.
The current failure is: `make[3]: *** [s-attrtab] Killed`.

This probably means the build has hit the 4Gb memory limit. You can add these lines at the begging of the install block:
```
# Reduce memory usage below 4 GB for Circle CI.
ENV["MAKEFLAGS"] = "-j16" if ENV["CIRCLECI"]
```

This will reduce the number of cores from 32 to 16. If it does not work we can try with `-j8`.

**Comment by kygx-legend** [comment]
@iMichka, thanks! It works after using `-j16`. Another error is also fixed by adding some codes of `gcc.rb`. Please review again!

**Comment by iMichka** [comment]
Cool. Looks great. I’ll have a look when I’m back from work this evening.

**Comment by iMichka** [comment]
Nice. @kygx-legend Thank you for your contribution! We have now a gcc 6 bottle thanks to you.

**Pull request closed without merging**
