### PR TITLE
w3m: Depends on ncurses for Linuxbrew

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by rwhogg** [comment]
From

```
terms.o: In function `setlinescols':
terms.c:(.text+0x2bf): undefined reference to `tgetnum'
```

Guessing this is a missing dependency on `homebrew/dupes/ncurses`, since it links to that on my machine and builds fine there.

**Comment by rwhogg** [comment]
From https://travis-ci.org/Linuxbrew/homebrew-core/builds/160493062#L1504

```
  * Dir["istream.[ch]"] is unnecessary; just use "istream.[ch]"
```

Well, that's an audit failure, but it was already there. The formula itself builds now.

Will merge assuming that Circle doesn't blow up.

@maxim-belkin, I fixed this because it says in the homebrew-xorg README that this formula currently doesn't build and we're not using it for building documentation as a result. Once I've got this merged, what (if anything) do you think we should do about that?

**Comment by maxim-belkin** [comment]
It is needed for some of the X.Org Libraries -- don't remember which ones but it is pretty easy to figure out.

**Comment by rwhogg** [comment]
Circle failure is the same audit failure we see on Travis. Merging soon.

**Pull request closed without merging**
