### PR TITLE
libexif: Fix test for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
==> brew test libexif --verbose
Testing libexif
==> /usr/bin/gcc-4.8 test.c -o test -I/home/linuxbrew/.linuxbrew/Cellar/libexif/0.6.21/include -L/home/linuxbrew/.linuxbrew/Cellar/libexif/0.6.21/lib -lexif
==> ./test /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test/support/fixtures/test.jpg
Error: libexif: failed
<0> expected but was
<12>.
==> FAILED
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/261386632#L1552

**Comment by sjackman** [comment]
I'm unable to reproduce this test failure locally.

**Comment by rwhogg** [comment]
I can reproduce it if I explicitly run `brew test --cc=gcc-4.8`.

**Comment by sjackman** [comment]
I was unable to reproduce the failure with `gcc-5`, but I am also able to reproduce the failure in the `linuxbrew/linuxbrew` Docker image with `gcc-4.8`.

**Pull request closed without merging**
