### PR TITLE
fix mongo-c-driver

### PR DESCRIPTION
**Pull request by timotheecour**
- [ x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [ x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
fixes https://github.com/Linuxbrew/homebrew-core/issues/1567 and https://github.com/Linuxbrew/homebrew-core/issues/1414 (same issue)

### CODE REVIEW

**Comment by timotheecour** [comment]
getting same on OSX:
```
Testing mongo-c-driver
==> Using the sandbox
==> /usr/bin/clang -o test /Users/timothee/homebrew/Cellar/mongo-c-driver/1.5.1/share/mongo-c-driver/libbson/examples/json-to-bson.c -I/Users/timothee/homebrew/Cellar/mongo-c-driver/1.5.1/include/libbson-1.0 -L/Users/timothee/homebrew/Cellar/mongo-c-driver/1.5.1/lib -lbson-1.0
==> ./test test.json
==> /usr/bin/clang -o test /Users/timothee/homebrew/Cellar/mongo-c-driver/1.5.1/share/mongo-c-driver/mongoc/examples/mongoc-ping.c -I/Users/timothee/homebrew/Cellar/mongo-c-driver/1.5.1/include/libmongoc-1.0 -I/Users/timothee/homebrew/Cellar/mongo-c-driver/1.5.1/include/libbson-1.0 -L/Users/timothee/homebrew/Cel
==> ./test mongodb://0.0.0.0 2>&1
Error: mongo-c-driver: failed
<3> expected but was
<0>.
```

so could be a broken test. how about merging anyway and opening a separate issue for that?

**Comment by timotheecour** [comment]
@sjackman I sent out https://github.com/Homebrew/homebrew-core/pull/8928 upstream to fix broken test. Could you please merge this (so we don't have to wait till next merge with upstream and then waiting more for this to be merged in)? Thanks!

**Comment by sjackman** [comment]
I'll merge this PR without updating the bottle.
I'll update the bottle once the test succeeds (see https://github.com/Homebrew/homebrew-core/pull/8928).

**Comment by sjackman** [comment]
For future PRs the preferred commit message is
`mongo-c-driver: Fix for Linuxbrew`

**Comment by sjackman** [comment]
> @sjackman : should this be moved to linuxbrew-core? Current situation is bad: in Linuxbrew#1576 (comment) you said this is blocking updating the linuxbrew bottle:

> It's not dependent on CI but whether there's a MongoDB already running on the system.

@timotheecour If the problem is that there's a `mongodb` server running on CircleCI, then I think the solution is to kill that server in the `circle.yml`.

**Pull request closed without merging**
