### PR TITLE
git 2.9.0

### PR DESCRIPTION
**Pull request by gdraynz**

### CODE REVIEW

**Comment by rwhogg** [comment]
Hi @gdraynz : normally, we request that pull requests for new versions of existing formulae go to upstream Homebrew rather than here. However, Homebrew has already upgraded to version 2.9 of Git: https://github.com/Homebrew/homebrew-core/blob/master/Formula/git.rb .

You can cherry-pick the relevant Git commit into your personal Linuxbrew branch if you'd like to upgrade to the new Git version now.

My apologies and thank you very much for contributing!

**Comment by gdraynz** [comment]
Ha! ok thanks for the heads-up :)

**Comment by netroby** [comment]
Long days goes. why linuxbrew does not upgrade to git 2.9.2. even upstream upgrade to 2.9.2

**Comment by sjackman** [comment]
I've been out of town for the last two weeks. The upgrade will happen in the next few days.

**Pull request closed without merging**
