### PR TITLE
get-flash-videos: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
> Can't locate Module/Find.pm in @INC (you may need to install the Module::Find module)

**Comment by iMichka** [comment]
> Can't locate Try/Tiny.pm in @INC (you may need to install the Try::Tiny module)

**Comment by iMichka** [comment]
This builds now, but the test is failing with:
```
Using method 'bbc' plugin version 0.01 for http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm
Downloading http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm
Error: Can't use string ("<?xml version="1.0" encoding="UT"...) as a SCALAR ref while "strict refs" in use at /home/linuxbrew/.linuxbrew/Cellar/get-flash-videos/1.25.93/lib/perl5/FlashVideo/Site/Bbc.pm line 88.

Couldn't extract Flash movie URL. This site may need specific support adding,
or fixing.

Please confirm that the URL is valid and that you are running the latest
version of get-flash-videos.

If the latest version does not support this site please create a bug
report at https://github.com/monsieurvideo/get-flash-videos making
sure you include the output with --debug enabled. Alternatively,
fix it yourself and send us a pull request.
Couldn't download any videos.
```

**Comment by sjackman** [comment]
Does the test work on macOS?

**Comment by iMichka** [comment]
Yes ...

**Comment by sjackman** [comment]
Both a local Linux machine and on macOS? Fails on CI though?

**Comment by iMichka** [comment]
Ok retested; this fails on locally too on Linux. I'll test this more in detail tomorrow.

**Comment by iMichka** [comment]
I opened an issue upstream: https://github.com/monsieurvideo/get-flash-videos/issues/215

**Comment by iMichka** [comment]
@sjackman Here is a case where the bottle didn't get uploaded.

**Comment by sjackman** [comment]
I've pinged `http://bot.linuxbrew.sh/ci-upload/github.com/Linuxbrew/homebrew-core/pull/3467?keep-old=1`

**Comment by sjackman** [comment]
```
Error: get-flash-videos-1.25.93.x86_64_linux.bottle.tar.gz is already published. Please remove it manually from
https://bintray.com/linuxbrew/bottles/get-flash-videos/view#files
```
Sorry these logs aren't available. It'd be great to figure out how to get that information out of AWS to us.

**Comment by iMichka** [comment]
Ok I'll remove the bottle. Maybe I already try to upload it at one point.
Logs would be great, but it does not happen so often so it is fine. Thanks for the help.

**Pull request closed without merging**
