### PR TITLE
Merge 2016-12-04

### PR DESCRIPTION
**Pull request by rwhogg**
- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Merging homebrew/homebrew-core into linuxbrew/homebrew-core

### CODE REVIEW

**Comment by rwhogg** [comment]
CC @Linuxbrew/core if they want to review this.

In particular, @maxim-belkin if you have the chance to double-check `llvm` that would be greatly appreciated 😄

**Comment by rwhogg** [comment]
Problems so far:

* `readline` fails to upgrade if you have a brewed `gawk`, because `gawk` links to `libreadline.so.7`, which temporarily goes away during the upgrade
* Mono fails during the F# stage with message "/tmp/mono--fsharp-20161204-5373-1pe93pv/packages/FSharp.Compiler.Tools.4.0.1.3/tools/Microsoft.FSharp.Targets: error : Tool exited with code: 137. Output: F# Compiler for F# 4.1". No idea what that means.

**Comment by sjackman** [comment]
> readline fails to upgrade if you have a brewed gawk, because gawk links to libreadline.so.7, which temporarily goes away during the upgrade

This issue is longstanding and affects a number of packages. The workaround is something like…
```sh
LD_LIBRARY_PATH=`brew --prefix readline`/lib brew upgrade readline
```

We could make `brew` do this automatically. The problem is that it moves the previous `lib` directory to the front of the library search path, whereas we'd probably want it at the end of the library search path. Setting `LD_LIBRARY_PATH` to `$(brew --prefix)/lib:$(brew --prefix readline)/lib)` during `brew upgrade` would accomplish that. I'm not convinced it's bullet proof, but it's probably better than what we have now. I think we ought to try patching `brew upgrade` to do this. Another common example of failure is upgrading the dependencies of `gcc`.

An alternative fix, arguably better, is to have the RPATH of each executable include each `lib` directory of each of its dependencies, rather than just `$(brew --prefix)/lib`. This behaviour would be more similar to macOS, where the absolute path to each dependent library is stored in each executable.

**Comment by sjackman** [comment]
> CMake fails

We'll have to resolve that before this merge.

**Comment by sjackman** [comment]
> Mono fails

We can probably ignore that failure for now.

**Comment by rwhogg** [comment]
One other problem I've since discovered: `qt5` needs a revision bump because `icu4c` changed its soname. 

I'd include that in this PR, but `qt5` is also failing to build (and hiding the reason), so I think it's best to deal with it later.

**Comment by rwhogg** [comment]
`cmake` actually does build correctly on my machine. The problem was with `qt5` - once I removed that, `cmake` installed fine.

My guess is that `cmake` tried to build the GUI since it detected Qt was available. Since `qt5` isn't on the dependency list, this won't be a problem for building the bottle.

**Comment by maxim-belkin** [comment]
@rwhogg I'm fine with the changes to llvm introduced here. I'm still working on fixes for Linux.

**Pull request merged**
