### PR TITLE
Merge expat 14d36114e4

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
libtool: compile:  gcc-4.8 -std=gnu99 -I./lib -I. -g -O2 -Wall -Wmissing-prototypes -Wstrict-prototypes -fexceptions -fno-strict-aliasing -DHAVE_EXPAT_CONFIG_H -c lib/xmltok.c  -fPIC -DPIC -o lib/.libs/xmltok.o
lib/xmlparse.c:56:3: error: #error You do not have support for any sources of high quality entropy enabled. For end user security, that is probably not what you want. Your options include: * Linux + glibc >=2.25 (getrandom): HAVE_GETRANDOM, * Linux + glibc <2.25 (syscall SYS_getrandom): HAVE_SYSCALL_GETRANDOM, * BSD / macOS (arc4random_buf): HAVE_ARC4RANDOM_BUF, * libbsd (arc4random_buf): HAVE_ARC4RANDOM_BUF + HAVE_LIBBSD, * Windows (RtlGenRandom): _WIN32. If insist on not using any of these, bypass this error by defining XML_POOR_ENTROPY; you have been warned. For CMake, one way to pass the define is: cmake -DCMAKE_C_FLAGS="-pipe -O2 -DHAVE_SYSCALL_GETRANDOM" . If you have reasons to patch this detection code away or need changes to the build system, please open a bug. Thank you!
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/255089067#L1624

**Comment by sjackman** [comment]
Perhaps this will work? I'd like to know why it's not autodetected.
```sh
cmake -DCMAKE_C_FLAGS="-pipe -O2 -DHAVE_SYSCALL_GETRANDOM"
```

**Comment by sjackman** [comment]
Except that we build `expat` using `./configure && make`. Does `expat` provide two separate build systems?

**Comment by sjackman** [comment]
Trying…
```ruby
ENV.append_to_cflags "-DHAVE_SYSCALL_GETRANDOM" unless OS.mac?
```

**Comment by sjackman** [comment]
The issue may be related to these two commits:
https://github.com/libexpat/libexpat/commit/602e6c78ca750c082b72f8cdf4a38839b312959f
https://github.com/Homebrew/homebrew-core/commit/9996b79349bc92db60b0bd6a2697703dbdc7d162#diff-02439230aca53b5e91bfc8a7a8de6498L20

**Comment by sjackman** [comment]
```
lib/xmlparse.c: In function ‘writeRandomBytes_getrandom’:
lib/xmlparse.c:760:17: error: ‘SYS_getrandom’ undeclared (first use in this function)
         syscall(SYS_getrandom, currentTarget, bytesToWrite, getrandomFlags);
```
The plot thickens.
https://travis-ci.org/Linuxbrew/homebrew-core/builds/255142857#L1612

**Comment by sjackman** [comment]
I've opened an issue with the upstream `libexpat` developers at https://github.com/libexpat/libexpat/issues/88

**Comment by rwhogg** [comment]
Thanks a bunch @maxim-belkin and @sjackman!

**Pull request merged**
