### PR TITLE
gnupg: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
`brew test` fails on Travis CI
```
301.00s==> brew test gnupg --verbose
Testing gnupg
==> /home/linuxbrew/.linuxbrew/Cellar/gnupg/1.4.21/bin/gpg1 --batch --gen-key batchgpg
.Error: gnupg: failed
execution expired
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/211160624#L2083

**Comment by maxim-belkin** [comment]
rebased on top of the latest brew/homebrew-core

**Comment by sjackman** [comment]
Bob's Docker image of Travis CI may be helpful in troubleshooting this `brew test` failure.
https://github.com/Linuxbrew/docker/blob/master/travis/Dockerfile

**Comment by iMichka** [comment]
@sjackman Please rebase, #3747 brings in a new gnupg

**Pull request closed without merging**
