### PR TITLE
Merge 2017-12-26 8ba4d9cf37

### PR DESCRIPTION
**Pull request by iMichka**
+ [ ] llvm

### CODE REVIEW

**Comment by ilovezfs** [comment]
This is not complete.
https://github.com/Homebrew/homebrew-core/commit/8f84c9238a9a5f8d85a08755c20eff9c8040a6b1
https://github.com/Homebrew/homebrew-core/commit/c2fccf2572c24d0ecf91a478926c7c7a15cadcf9

**Comment by iMichka** [comment]
It is. These commits come later in the git history, so they will be merged during the next merge step.

I'm going to merge this pull request as-is, without building a bottle. I'll open a new merge commit that will contain the latest changes, and build the llvm bottle in a second step.

**Comment by ilovezfs** [comment]
:+1:

**Comment by iMichka** [comment]
See #5300

**Pull request merged**
