### PR TITLE
cloc: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
should we add 
```
depends_on :perl => :build unless OS.mac?
```
?

**Comment by sjackman** [comment]
```
perl
Makefile.PL
INSTALL_BASE=/home/linuxbrew/.linuxbrew/Cellar/cloc/1.72/libexec
WARNING: TEST_REQUIRES is not a known parameter.
Checking if your kit is complete...
Looks good
'TEST_REQUIRES' is not a known MakeMaker parameter name.
ExtUtils::MakeMaker::YAML does not support circular references at /usr/share/perl/5.14/ExtUtils/MakeMaker/YAML.pm line 499.
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/222008827#L1548
Looks like this perl module is too old on TravisCI? Since CircleCI completed successfully, I'm inclined to ignore the error and merge it as is.

**Comment by maxim-belkin** [comment]
I wonder if we should add something like 
```
depends_on :perl => "5.20" unless OS.mac?
```
?

**Comment by maxim-belkin** [comment]
I mean, this would help those who have old perl and decide to build the formula from source.

**Comment by sjackman** [comment]
Is it the version of Perl that's outdated, or the version of that particular module `ExtUtils/MakeMaker`? Does that module ship with Perl?

**Comment by sjackman** [comment]
The way the Homebrew Requirements system works, I believe adding
```ruby
depends_on :perl => "5.20" unless OS.mac?
```
makes `perl` a hard dependency for anyone installing this formula from a bottle. That's by design, and I think it's a bit odd.

**Comment by maxim-belkin** [comment]
even if it's satisfied by system's perl?

**Comment by sjackman** [comment]
Yes. When installing a bottle, all `default-formula` of requirements become mandatory.

**Comment by maxim-belkin** [comment]
merged
see https://github.com/Linuxbrew/homebrew-core/pull/2361#issuecomment-294278122

**Pull request closed without merging**
