### PR TITLE
boost-python3: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
> /bin/sh: 2: -O3: not found

**Comment by akaitake** [comment]
I can not build boost-python3 with error "/bin/sh: 2: -O3: not found"
Do you have any suggestions?

**Comment by iMichka** [comment]
For the moment, no. I have no clue why this is broken. I just know that before, when boost-python was only one formula, it was building fine with python 3.

There is one difference though, which is the addition of numpy support. You may try to remove that from the formula and see if it helps.

I do not know when I will find time to work on this, so any help debugging this would be appreciated.

**Comment by akaitake** [comment]
Thank you for your advice. I finally succeeded to compile with numpy support.
I changed two lines.
Line 52: py_prefix = `python3 -c "import sys; print(sys.prefix)"`.strip
Line 63: using gcc : : g++ ;
Thank you.

**Comment by iMichka** [comment]
Hi. Cool it worked for you. Would you like to submit a pull request with the changes?

**Comment by iMichka** [comment]
Superseded by #6095

**Pull request closed without merging**
