### PR TITLE
tectonic: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by sjackman** [comment]
```
Error: --keep-old was passed but there are changes in:
cellar: old: "/home/linuxbrew/.linuxbrew/Cellar", new: :any_skip_relocation
```
https://circleci.com/gh/Linuxbrew/homebrew-core/22765

**Comment by iMichka** [comment]
> rustlib/x86_64-apple-darwin

Where is that coming from :(

**Comment by sjackman** [comment]
>> rustlib/x86_64-apple-darwin

> Where is that coming from :(

That was the macOS bottle! No need for concern. =)

**Comment by iMichka** [comment]
Cool, thanks.

**Pull request closed without merging**
