### PR TITLE
libpq: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
configure: error: zlib library not found
If you have zlib already installed, see config.log for details on the
failure.  It is possible the compiler isn't looking in the proper directory.
Use --without-zlib to disable zlib support.
```

**Comment by iMichka** [comment]
The test error is:
`./libpqtest: error while loading shared libraries: libpq.so.5: cannot open shared object file: No such file or directory`

I have seen this for multiple formulae.

A fix (proposed here) is to prepend library path, but I think this is not the right thing to do.
@sjackman I think I am missing some  `rpath` magic here?

**Comment by sjackman** [comment]
`brew test` is run in stdenv (not superenv). stdenv does set `LD_LIBRARY_PATH` but only if the `formula` argument is passed to `ENV.setup_build_environment`, and that argument is not passed.
See https://github.com/Linuxbrew/brew/blob/b67917c837f1fb9c5bf2494cfd89b4eee6802802/Library/Homebrew/test.rb#L19

We used to have a Linuxbrew-specific patch that did pass that `formula` argument, but it was removed. It was originally added to select GCC 5 when that formula did not work with the host's GCC 4.8. When we switched the host GCC to GCC 5, I was hoping that it was no longer necessary. It seems that I was wrong.

@iMichka Should we add it back in?

**Comment by sjackman** [comment]
On second thought, I think `LD_RUN_PATH` should be set by stdenv to `$HOMEBREW_PREFIX/lib`, which does not require calling `ENV.setup_build_environment` with a `formula` argument.

**Comment by sjackman** [comment]
I've confirmed that `RPATH` is correctly set to `$HOMEBREW_PREFIX/lib`, but `libpq` is `keg_only` because it conflicts with `postgres`, so the library `libpq.so.5` is not symlinked. Your suggested fix is good. `Formula["libpq"].lib` can be simply `lib`
```ruby
    ENV.prepend_path "LD_LIBRARY_PATH", lib unless OS.mac?
```
The other option would be to add `-Wl,-rpath=#{lib}` to the compiler options.

**Comment by iMichka** [comment]
Ok, got it, it is due to the fact that it is keg only.
I am OK with the ´ENV.prepend_path "LD_LIBRARY_PATH", lib unless OS.mac?´ solution.

One last question: why is this working on mac? Are the paths to the libs backed in the executable by default (something like ´-Wl,-rpath=#{lib}´, but by default).

**Comment by sjackman** [comment]
Yes, the complete path to each library is encoded in the executable by default on macOS.

**Comment by iMichka** [comment]
Cool, good to know. Thanks for the help.

**Pull request closed without merging**
