### PR TITLE
kubernetes-cli: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
kubernetes-cli:
  * C: 22: col 10: Don't use OS.linux?; Homebrew/core only supports macOS
```

```
Makefile:92: recipe for target 'all' failed
make: *** [all] Error 1
make: Leaving directory '/tmp/kubernetes-cli-20171016-4033-yeubjf/src/k8s.io/kubernetes'
!!! Error in hack/generate-docs.sh:37
  Error in hack/generate-docs.sh:37. 'make -C "${KUBE_ROOT}" WHAT="${BINS[*]}"' exited with status 2
Call stack:
  1: hack/generate-docs.sh:37 main(...)
Exiting with status 1

==> Formula
```

**Comment by iMichka** [comment]
Seems to be the following error: https://github.com/kubernetes/kubernetes/issues/49519

**Comment by iMichka** [comment]
Rebased, 1.8.2 is out

**Comment by iMichka** [comment]
```
go build k8s.io/kubernetes/federation/cmd/genfeddocs: /home/linuxbrew/.linuxbrew/Cellar/go/1.9.1/libexec/pkg/tool/linux_amd64/link: signal: killed
go build k8s.io/kubernetes/cmd/genman: /home/linuxbrew/.linuxbrew/Cellar/go/1.9.1/libexec/pkg/tool/linux_amd64/link: signal: killed
# k8s.io/kubernetes/cmd/genkubedocs
/home/linuxbrew/.linuxbrew/Cellar/go/1.9.1/libexec/pkg/tool/linux_amd64/link: running gcc-5 failed: exit status 1
/usr/bin/ld: final link failed: No space left on device
```

**Comment by tivvit** [comment]
Hi @iMichka I looked at the issue and it is not merged in master. 
Do I get it right that the problem is that the build (CI) needs more then 4GB RAM (I have encountered that too on small machines) - https://circleci.com/docs/1.0/oom/
Does your change with make flags help? Is there an option to make the build machine bigger (i do not think so)?
I am willing to help but not sure where should i start

**Pull request closed without merging**
