### PR TITLE
qt5: Many missing dependencies

### PR DESCRIPTION
**Pull request by rwhogg**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

Replacing #681

### CODE REVIEW

**Comment by rwhogg** [comment]
```
xcb.cpp:38:27: fatal error: xcb/xcb_icccm.h: No such file or directory
```

Uh huh. That header file doesn't actually come from `libxcb`, but rather from `xcb-util-wm`.

**Comment by rwhogg** [comment]
Various errors from Travis:

```
pulseaudio.cpp:35:33: fatal error: pulse/glib-mainloop.h: No such file or directory
libinput.cpp:34:22: fatal error: libinput.h: No such file or directory
opengles2.cpp:37:25: fatal error: GLES2/gl2.h: No such file or directory
tslib.cpp:34:19: fatal error: tslib.h: No such file or directory
xkbcommon.cpp:34:33: fatal error: xkbcommon/xkbcommon.h: No such file or directory
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -lfontconfig
```

**Comment by rwhogg** [comment]
Yet more fatal errors:
```
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -licui18n
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -licuuc
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -licudata
libproxy.cpp:36:19: fatal error: proxy.h: No such file or directory
xcb.cpp:42:27: fatal error: xcb/xcb_image.h: No such file or directory
```

Still haven't resolved some of the earlier ones either.

**Comment by rwhogg** [comment]
It's now blocked by `libproxy`

**Comment by donbright** [comment]
it is possible to workaround some of the more obscure libxcb dependencies by passing -qt-xcb to qt5's configure script

http://doc.qt.io/qt-5/linux-requirements.html

**Comment by rwhogg** [comment]
Travis timed out. Circle would have succeeded, it just had a trivial audit failure. If the bottle uploads to Bintray cleanly, I'll merge this and just fix the audit failure before pushing.

**Comment by rwhogg** [comment]
QT 5 is merged!

This is a huge milestone for Linuxbrew and a lot of people helped get us here. I'd like to thank in particular @donbright for his alternate PR #1062, @sjackman for general Linuxbrew awesomeness, @maxim-belkin for originally packaging up X11, and @DoomHammer for reviewing #797.

:raised_hands:

**Comment by sjackman** [comment]
👏 Nice work, Bob! That's fantastic. Want to post to an announcement to Linuxbrew Updates? I've locked that issue to contributors.

**Pull request closed without merging**
