### PR TITLE
Remove x11 superenv hacks

### PR DESCRIPTION
**Pull request by rwhogg**
- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Remove various superenv related hacks put in place until https://github.com/linuxbrew/brew/pull/337 was merged.

### CODE REVIEW

**Comment by rwhogg** [comment]
I might be able to remove an ages-old `poppler` hack I put in on #697 too.

**Comment by maxim-belkin** [comment]
just a heads-up: I'm currently merging the core in #2424

**Comment by maxim-belkin** [comment]
building llvm bottle locally to help this PR

**Comment by maxim-belkin** [comment]
safe to proceed with this PR

**Comment by rwhogg** [comment]
Thanks a bunch for rebottling `llvm`! Rebased.

**Comment by maxim-belkin** [comment]
@rwhogg llvm bottle has been merged! please try rebasing this PR once again

**Comment by rwhogg** [comment]
CI was successful, just timeout on Travis and webhook failure on Circle.

@sjackman, @maxim-belkin okay with me merging without updating the bottle?

**Comment by sjackman** [comment]
:shipit: Yep!

**Pull request merged**
