### PR TITLE
gperftools: Use llvm to provide libunwind

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
@tseemann Does this fix it for you?

@sjackman I propose to remove the `libunwind` formula from linuxbrew, and redirect it to llvm.

**Comment by xu-cheng** [comment]
Wouldn't `llvm` a little heavy to be used for this purpose? IMHO, it would be better to make `libunwind` keg-only or as a vendored resource in `gperftools`.

**Comment by iMichka** [comment]
PR's are welcome. I fixed the initial issue, and I am totally aware that using llvm for this is totally overkill. But I have no time to investigate more.

Also, this dependency is there only for linux. I see a comment in the formula:
> Fix error: No frame pointers and no libunwind. The compilation will fail

Not sure this is even needed anymore. Some testing may be needed.

**Comment by xu-cheng** [comment]
> Would you like to submit a PR?

Sure. But I am currently travelling abroad for a research conference, so it will be a while before I can submit it.

**Comment by xu-cheng** [comment]
#7265

**Pull request closed without merging**
