### PR TITLE
clang-format: fix build for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
> g++-5: internal compiler error: Killed (program cc1plus)

**Comment by iMichka** [comment]
```
==> ninja clang-format
.
Last 150 lines from /home/linuxbrew/Library/Logs/Homebrew/clang-format/02.ninja:
 extern int fgetc (FILE *__stream);
                   ^
/usr/include/stdio.h:531:25: error: ‘__stream’ was not declared in this scope
 extern int fgetc (FILE *__stream);
                         ^
/usr/include/stdio.h:532:18: error: ‘FILE’ was not declared in this scope
 extern int getc (FILE *__stream);
                  ^
/usr/include/stdio.h:532:24: error: ‘__stream’ was not declared in this scope
 extern int getc (FILE *__stream);
                        ^
/usr/include/stdio.h:573:28: error: ‘FILE’ has not been declared
 extern int fputc (int __c, FILE *__stream);
                            ^
/usr/include/stdio.h:574:27: error: ‘FILE’ has not been declared
 extern int putc (int __c, FILE *__stream);
                           ^
/usr/include/stdio.h:622:52: error: ‘FILE’ has not been declared
 extern char *fgets (char *__restrict __s, int __n, FILE *__restrict __stream)
                                                    ^
/usr/include/stdio.h:689:47: error: ‘FILE’ has not been declared
 extern int fputs (const char *__restrict __s, FILE *__restrict __stream);
                                               ^
/usr/include/stdio.h:702:29: error: ‘FILE’ has not been declared
 extern int ungetc (int __c, FILE *__stream);
                             ^
/usr/include/stdio.h:710:20: error: ‘FILE’ has not been declared
        size_t __n, FILE *__restrict __stream) __wur;
                    ^
/usr/include/stdio.h:716:21: error: ‘FILE’ has not been declared
         size_t __n, FILE *__restrict __s);
                     ^
/usr/include/stdio.h:749:19: error: ‘FILE’ was not declared in this scope
 extern int fseek (FILE *__stream, long int __off, int __whence);
                   ^
/usr/include/stdio.h:749:25: error: ‘__stream’ was not declared in this scope
 extern int fseek (FILE *__stream, long int __off, int __whence);
                         ^
/usr/include/stdio.h:749:35: error: expected primary-expression before ‘long’
 extern int fseek (FILE *__stream, long int __off, int __whence);
                                   ^
/usr/include/stdio.h:749:51: error: expected primary-expression before ‘int’
 extern int fseek (FILE *__stream, long int __off, int __whence);
                                                   ^
/usr/include/stdio.h:749:63: error: expression list treated as compound expression in initializer [-fpermissive]
 extern int fseek (FILE *__stream, long int __off, int __whence);
                                                               ^
/usr/include/stdio.h:754:24: error: ‘FILE’ was not declared in this scope
 extern long int ftell (FILE *__stream) __wur;
                        ^
/usr/include/stdio.h:754:30: error: ‘__stream’ was not declared in this scope
 extern long int ftell (FILE *__stream) __wur;
                              ^
/usr/include/stdio.h:759:21: error: variable or field ‘rewind’ declared void
 extern void rewind (FILE *__stream);
                     ^
/usr/include/stdio.h:759:21: error: ‘FILE’ was not declared in this scope
/usr/include/stdio.h:759:27: error: ‘__stream’ was not declared in this scope
 extern void rewind (FILE *__stream);
                           ^
/usr/include/stdio.h:798:21: error: ‘FILE’ was not declared in this scope
 extern int fgetpos (FILE *__restrict __stream, fpos_t *__restrict __pos);
                     ^
/usr/include/stdio.h:798:27: error: expected primary-expression before ‘__restrict’
 extern int fgetpos (FILE *__restrict __stream, fpos_t *__restrict __pos);
                           ^
/usr/include/stdio.h:798:48: error: ‘fpos_t’ was not declared in this scope
 extern int fgetpos (FILE *__restrict __stream, fpos_t *__restrict __pos);
                                                ^
/usr/include/stdio.h:798:56: error: expected primary-expression before ‘__restrict’
 extern int fgetpos (FILE *__restrict __stream, fpos_t *__restrict __pos);
                                                        ^
/usr/include/stdio.h:798:72: error: expression list treated as compound expression in initializer [-fpermissive]
 extern int fgetpos (FILE *__restrict __stream, fpos_t *__restrict __pos);
                                                                        ^
/usr/include/stdio.h:803:21: error: ‘FILE’ was not declared in this scope
 extern int fsetpos (FILE *__stream, const fpos_t *__pos);
                     ^
/usr/include/stdio.h:803:27: error: ‘__stream’ was not declared in this scope
 extern int fsetpos (FILE *__stream, const fpos_t *__pos);
                           ^
/usr/include/stdio.h:803:37: error: expected primary-expression before ‘const’
 extern int fsetpos (FILE *__stream, const fpos_t *__pos);
                                     ^
/usr/include/stdio.h:803:56: error: expression list treated as compound expression in initializer [-fpermissive]
 extern int fsetpos (FILE *__stream, const fpos_t *__pos);
                                                        ^
/usr/include/stdio.h:826:23: error: variable or field ‘clearerr’ declared void
 extern void clearerr (FILE *__stream) __THROW;
                       ^
/usr/include/stdio.h:826:23: error: ‘FILE’ was not declared in this scope
/usr/include/stdio.h:826:29: error: ‘__stream’ was not declared in this scope
 extern void clearerr (FILE *__stream) __THROW;
                             ^
/usr/include/stdio.h:828:18: error: ‘FILE’ was not declared in this scope
 extern int feof (FILE *__stream) __THROW __wur;
                  ^
/usr/include/stdio.h:828:24: error: ‘__stream’ was not declared in this scope
 extern int feof (FILE *__stream) __THROW __wur;
                        ^
/usr/include/stdio.h:830:20: error: ‘FILE’ was not declared in this scope
 extern int ferror (FILE *__stream) __THROW __wur;
                    ^
/usr/include/stdio.h:830:26: error: ‘__stream’ was not declared in this scope
 extern int ferror (FILE *__stream) __THROW __wur;
                          ^
In file included from /usr/include/libio.h:56:0,
                 from /usr/include/stdio.h:74,
                 from /usr/include/c++/5/cstdio:42,
                 from /usr/include/c++/5/ext/string_conversions.h:43,
                 from /usr/include/c++/5/bits/basic_string.h:5249,
                 from /usr/include/c++/5/string:52,
                 from /usr/include/c++/5/bits/locale_classes.h:40,
                 from /usr/include/c++/5/bits/ios_base.h:41,
                 from /usr/include/c++/5/ios:42,
                 from /usr/include/c++/5/ostream:38,
                 from /usr/include/c++/5/iterator:64,
                 from ../include/llvm/ADT/iterator_range.h:22,
                 from ../include/llvm/ADT/iterator.h:13,
                 from ../include/llvm/ADT/FoldingSet.h:20,
                 from ../lib/Support/FoldingSet.cpp:15:
/usr/include/stdio.h:942:1: error: expected declaration before ‘}’ token
 __END_DECLS
 ^
```

**Comment by thedrow** [comment]
So standard C structs like FILE are missing? :open_mouth:

**Comment by iMichka** [comment]
The CI ran out memory, which sometimes give weird errors. I built this locally and uploaded the bottle.

**Pull request closed without merging**
