### PR TITLE
pulseaudio: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by sjackman** [comment]
Any progress on this issue?
cc @suujia

**Comment by iMichka** [comment]
I think this is due to the broken perl install we are currently having. We should try to fix perl first.

**Comment by sjackman** [comment]
Is there a relevant issue or PR for the Perl problem?

**Comment by iMichka** [comment]
https://github.com/Linuxbrew/homebrew-core/issues/8597
https://github.com/Linuxbrew/homebrew-core/pull/8709
https://github.com/brewsci/homebrew-bio/pull/342

Maybe some new supermen problem, or due to the make shim changes? Or something completely new? Building perl has worked before. The problem is not only for centos 6, but for all Linux versions.

**Comment by sjackman** [comment]
`brew install perl` and `brew postinstall perl` work in the `linuxbrew/linuxbrew` Docker image. How do I reproduce this issue?

**Comment by tseemann** [comment]
I am a bit confused.  `perl` provides `XML::Parser` but `pulseaudio` is installing it too?

```
  unless OS.mac?
    depends_on "m4" => :build
    depends_on "libcap"
    depends_on "expat"

    # Depends on XML::Parser
    # Using the host's Perl interpreter to install XML::Parser fails when using brew's glibc.
    # Use brew's Perl interpreter instead.
    # See Linuxbrew/homebrew-core#8148
    depends_on "perl" => :build
    resource "XML::Parser" do
      url "https://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-2.44.tar.gz"
      sha256 "1ae9d07ee9c35326b3d9aad56eae71a6730a73a116b9fe9e8a4758b7cc033216"
    end
  end

  def install
    unless OS.mac?
      ENV.prepend_create_path "PERL5LIB", libexec/"lib/perl5"
      resources.each do |res|
        res.stage do
          system "perl", "Makefile.PL", "INSTALL_BASE=#{libexec}"
          system "make", "PERL5LIB=#{ENV["PERL5LIB"]}", *("CC=#{ENV.cc}" unless OS.mac?)
          system "make", "install"
        end
      end
    end
```

**Comment by iMichka** [comment]
We had a super long discussion here about all this: https://github.com/Linuxbrew/homebrew-core/pull/8148

Not sure it helps.  There is also: #4499
Improvements are welcome!

**Pull request closed without merging**
