### PR TITLE
Merge Homebrew #21ad2fe3b5 into Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**
Conflicts:
 - [x]	Formula/cmark-gfm.rb
 - [x]	Formula/flow.rb
 - [x]	Formula/mariadb.rb

### CODE REVIEW

**Comment by maxim-belkin** [comment]
`sourcekitten` is a mac-only thing

**Comment by maxim-belkin** [comment]
`mycli` failed with the same sympomps as `buku`:
```
    gcc-4.8 -fno-strict-aliasing -g -O2 -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/home/linuxbrew/.linuxbrew/bin/../Cellar/python/2.7.13/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
```

**Comment by sjackman** [comment]
I've addressed `sourcekitten` with PR https://github.com/Linuxbrew/homebrew-core/pull/3297

**Comment by sjackman** [comment]
I've addressed `mycli` with PR #3298

**Comment by sjackman** [comment]
Merged. Thanks, Maxim!

**Pull request merged**
