### PR TITLE
icu4c: Reduce memory usage below 4 GB for Circle CI

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
`-j8` failed.

**Comment by iMichka** [comment]
`-j4` failed.

**Comment by rwhogg** [comment]
Ran out of memory even with "-j1". We probably have to disable this one on CI 🙁

**Comment by sjackman** [comment]
Sad face indeed. `icu4c` is a pretty critical dependency. We can build a bottle manually in the mean time. Good grief though. I wonder if other GCC versions have better memory performance, or `clang` for that matter.

**Comment by sjackman** [comment]
Ah. Their build system is ignoring our configuration and using 32 compiler processes.
```
curl https://7903-56942570-gh.circle-artifacts.com/0/tmp/memory-usage.txt | grep -c cc1plus
32
```

**Comment by sjackman** [comment]
Weird though, because it looks like a typical invocation of `make`.

**Comment by sjackman** [comment]
I've opened a duplicate PR to do some interactive troubleshooting myself at https://github.com/Linuxbrew/homebrew-core/pull/3822

**Comment by iMichka** [comment]
#3822 fixed it with `-j24`. We do not know how that worked there an not here, but at least it works. Closing here.

**Comment by sjackman** [comment]
Superseded by https://github.com/Linuxbrew/homebrew-core/pull/3822

**Pull request closed without merging**
