### PR TITLE
fzf: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by sjackman** [comment]
TravisCI `brew install go`
```
Error: Failure while executing: ["ldd", "/home/linuxbrew/.linuxbrew/Cellar/go/1.8.1/libexec/src/debug/elf/testdata/gcc-386-freebsd-exec"]
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/227724930#L1704

**Comment by maxim-belkin** [comment]
rebase?

**Comment by sjackman** [comment]
No. I think it's a different problem. `file` reports that the executable is `dynamically linked`, but `ldd` reports `not a dynamic executable`

**Comment by maxim-belkin** [comment]
Those are different files, no?

```
$ brew install go
==> Downloading https://linuxbrew.bintray.com/bottles/go-1.8.1.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring go-1.8.1.x86_64_linux.bottle.tar.gz
Error: Failure while executing: ["ldd", "/home/linuxbrew/.linuxbrew/Cellar/go/1.8.1/libexec/src/debug/elf/testdata/gcc-386-freebsd-exec"] 
```

**Comment by sjackman** [comment]
> Those are different files, no?

Woops. Fixed above. Same result.

**Comment by maxim-belkin** [comment]
could it be `https://unix.stackexchange.com/a/75121/222638` ?

**Comment by maxim-belkin** [comment]
or http://stackoverflow.com/a/26516273/7410631

**Comment by maxim-belkin** [comment]
Oh! I think this is it:
```
ELF 32-bit LSB executable
```

**Comment by sjackman** [comment]
That could do it. Or also maybe the wrong dynamic linker:
```
$ patchelf --print-interpreter ~/.linuxbrew/Cellar/go/1.8.1/libexec/src/debug/elf/testdata/gcc-386-freebsd-exec
/libexec/ld-elf.so.1
```
That was built from source though, not poured from a bottle. Poured shouldn't have that problem.

**Comment by maxim-belkin** [comment]
> Poured shouldn't have that problem 

Can't pour, see https://github.com/Linuxbrew/homebrew-core/pull/2584#issuecomment-298700453

**Comment by maxim-belkin** [comment]
http://stackoverflow.com/a/28970871/7410631 ?

**Comment by sjackman** [comment]
I think that you're right then. It is the 32-bit problem. I guess before calling `ldd` we have to check that the architecture matches. Ugh. Or more of a hack ignore the error `not a dynamic executable`, though I'm less comfortable with that.

**Comment by sjackman** [comment]
`ELF.arch` returns the architecture of the ELF file, either `:i386` or `:x86_64`.

**Comment by maxim-belkin** [comment]
rebased and force-pushed

**Pull request closed without merging**
