### PR TITLE
hello: test ci

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
AWS upload log:
```
==> Fetching patch 
Patch: https://github.com/Homebrew/homebrew-core/pull/5718.patch
/usr/bin/curl --show-error --user-agent Linuxbrew/1.X.Y (Linux; x86_64 4.9.77-31.58.amzn1.x86_64) curl/7.51.0 --fail --silent --location --remote-time --continue-at - --output /tmp/test-bot/.cache/Homebrew/5718.patch https://github.com/Homebrew/homebrew-core/pull/5718.patch
git fetch --quiet origin pull/5718/head
==> Applying patch
git am --whitespace=nowarn -3 /tmp/test-bot/.cache/Homebrew/5718.patch
Applying: rcssserver: migrate to boneyard
Repository lacks necessary blobs to fall back on 3-way merge.
Cannot fall back to three-way merge.
Patch failed at 0001 rcssserver: migrate to boneyard
The copy of the patch that failed is found in:
/tmp/brew/Library/Taps/homebrew/homebrew-core/.git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
Already on 'master'
fatal: sha1 information is lacking or useless (Formula/rcssserver.rb).
Error: Patch failed to apply: aborted.
Error: Kernel.exit
Error: Failure while executing: brew pull --clean https://github.com/Homebrew/homebrew-core/pull/5718
```

**Comment by sjackman** [comment]
```sh
brew pull --clean https://github.com/Homebrew/homebrew-core/pull/5718
```
It's pulling from `Homebrew/homebrew-core` rather than `Linuxbrew/homebrew-core`.

**Comment by sjackman** [comment]
This commit is at fault:
https://github.com/Linuxbrew/homebrew-test-bot/commit/f86084d3b7baef89fe5cd71a892451ab8b015d34

**Comment by sjackman** [comment]
Hopefully PR https://github.com/Linuxbrew/homebrew-test-bot/pull/64 resolves this issue.

**Comment by iMichka** [comment]
```
==> Fetching patch 
Patch: https://github.com/Linuxbrew/homebrew-core/pull/5718.patch
/usr/bin/curl --show-error --user-agent Linuxbrew/1.X.Y (Linux; x86_64 4.9.77-31.58.amzn1.x86_64) curl/7.51.0 --fail --silent --location --remote-time --continue-at - --output /tmp/test-bot/.cache/Homebrew/5718.patch https://github.com/Linuxbrew/homebrew-core/pull/5718.patch
git fetch --quiet origin pull/5718/head
==> Applying patch
git am --whitespace=nowarn -3 /tmp/test-bot/.cache/Homebrew/5718.patch
Applying: hello: test ci
Using index info to reconstruct a base tree...
M	.circleci/config.yml
M	Formula/hello.rb
Falling back to patching base and 3-way merge...
Auto-merging Formula/hello.rb
CONFLICT (content): Merge conflict in Formula/hello.rb
Patch failed at 0001 hello: test ci
The copy of the patch that failed is found in:
/tmp/brew/Library/Taps/homebrew/homebrew-core/.git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
Already on 'master'
Could not create directory '/home/sbx_user1059/.ssh'.
Failed to add the host to the list of known hosts (/home/sbx_user1059/.ssh/known_hosts).
remote: warning: Deleting a non-existent ref. 
To git@github.com:LinuxbrewTestBot/homebrew-core.git
+ ada5e3e...db422ce master -> master (forced update)
- [deleted] pr-5718
Failed to merge in the changes.
Error: Patch failed to apply: aborted.
Error: Kernel.exit
Error: Failure while executing: brew pull --clean --tap=homebrew/core https://github.com/Linuxbrew/homebrew-core/pull/5718
```

Making progress, thanks @sjackman . The url is correct now. Still some error somewhere, I'll continue to work on this today.

**Comment by iMichka** [comment]
I did a first cleanup by removing some duplicated code: https://github.com/Linuxbrew/homebrew-test-bot/pull/66

**Comment by iMichka** [comment]
This worked. Bottles have been uploaded.

Still getting a curl error that may be interesting to investigate:
```
git tag --force pr-5718
git push --force git@github.com:LinuxbrewTestBot/homebrew-core.git master:master refs/tags/pr-5718
Already on 'master'
Could not create directory '/home/sbx_user1059/.ssh'.
Failed to add the host to the list of known hosts (/home/sbx_user1059/.ssh/known_hosts).
remote: warning: Deleting a non-existent ref. 
To git@github.com:LinuxbrewTestBot/homebrew-core.git
+ 830b169...4255a72 master -> master (forced update)
- [deleted] pr-5718
curl: (22) The requested URL returned error: 404 Not Found
Could not create directory '/home/sbx_user1059/.ssh'.
Failed to add the host to the list of known hosts (/home/sbx_user1059/.ssh/known_hosts).
To git@github.com:LinuxbrewTestBot/homebrew-core.git
* [new tag] pr-5718 -> pr-5718
```

**Comment by iMichka** [comment]
I do not need that PR anymore. Closing.

**Pull request closed without merging**
