### PR TITLE
Update Formula/texlive.rb

### PR DESCRIPTION
**Pull request by whiter462**
http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
was updated on 22 Oct 2017

### CODE REVIEW

**Comment by iMichka** [comment]
Hi. Thanks for opening a pull request.
Here is what the bot is saying:
```
        Error: SHA256 mismatch
Expected: 925bceeb4100ff7248dd499f732901d135f4747598bb64c93a1bc51928f65a2b
Actual: dc0ebd50327ea95cc2ecf167f283d2157dc083d5aea0bc53a6787ed8beac2569
```

Seems you got the wrong sha256 for the source file.

**Comment by whiter462** [comment]
Thanks for your comment, iMichka.
I've checked some mirrors, and got multiple sha256 like,

f91af0dc3ab940b6c15a9ee1abe222fea84cca82e9738efc93cd9e8ac20271c8
on http://ctan.math.utah.edu/, ftp://anorien.csc.warwick.ac.uk/, http://ctan.cs.uu.nl/, http://ftp.jaist.ac.jp, 

925bceeb4100ff7248dd499f732901d135f4747598bb64c93a1bc51928f65a2b
on  http://babyname.tips/, ftp://ftp.u-aizu.ac.jp/

but, I didn't get sha256 said by the bot.
(checked by: $ openssl dgst -sha256 install-tl-unx.tar.gz )

It might got something wrong in rsync-ing beyond some mirrors.

Should I wait to become single sha256 in most mirrors?
And, how could I get the bot saying?

**Comment by iMichka** [comment]
You can click on the circle-ci icon on this page, which will open the circle.ci test page. You can look at the log file and see the bot complaining about the sha256.

It is weird that different mirrors are reporting different sha256 sums ...

I use `shasum -a 256` to compute shasums, and that has always worked. Never tried with openssl.

**Comment by whiter462** [comment]
Thanks for comment.
I got the complaint of the bot, and downloaded from the same mirror as the bot did.
But still get sha256 from "http://mirrors.ibiblio.org/CTAN/" as 
`925bceeb4100ff7248dd499f732901d135f4747598bb64c93a1bc51928f65a2b`

I used both `shasum -a 256` and `openssl dgst -sha256`, and got the same sha256 sum as above in my environment.

It was so weird ...

Also, I found a size difference between 
a file with 4,027,**_178_** bytes has sha256:  `f91af0dc3ab940b6c15a9ee1abe222fea84cca82e9738efc93cd9e8ac20271c8`
and 
a file with 4,027,**_211_** bytes has sha256: `925bceeb4100ff7248dd499f732901d135f4747598bb64c93a1bc51928f65a2b` .

In this situation, I recommend sha256 for 20171022 version is 
`f91af0dc3ab940b6c15a9ee1abe222fea84cca82e9738efc93cd9e8ac20271c8` , 
which is the majority.

but, it needs single sha256 in whole or most mirrors...

**Comment by iMichka** [comment]
```
Automated TeX Live installation using profile: /dev/null
./install-tl: Initialization failed (in setup_unix_one):
./install-tl: could not find a usable wget.
./install-tl: Please install wget and try again.
./install-tl: Goodbye.
```

You should add a `depends_on "wget" => :build" line to the dependencies.

```
failed: brew style texlive
== /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/texlive.rb ==
C: 12:  1: Trailing whitespace detected.
```

You have a trailing whitespace that needs to be removed.

**Comment by whiter462** [comment]
I've updated code, but still exist missing libs

~~~
==> brew linkage texlive
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libdl.so.2
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /lib/x86_64-linux-gnu/librt.so.1
  /lib64/ld-linux-x86-64.so.2
  /usr/lib/x86_64-linux-gnu/libX11.so.6
  /usr/lib/x86_64-linux-gnu/libXext.so.6
Homebrew libraries:
  /home/linuxbrew/.linuxbrew/lib/libfontconfig.so.1 (fontconfig)
Missing libraries:
  libICE.so.6
  libSM.so.6
  libXaw.so.7
  libXmu.so.6
  libXpm.so.4
  libXt.so.6
~~~

What should I do next?

**Comment by whiter462** [comment]
I added "xorg" dependency.
(ref: https://github.com/Linuxbrew/legacy-linuxbrew/pull/892)

bot said, `Undeclared dependencies with linkage`
~~~
Undeclared dependencies with linkage:
  linuxbrew/xorg/libice
  linuxbrew/xorg/libsm
  linuxbrew/xorg/libx11
  linuxbrew/xorg/libxaw
  linuxbrew/xorg/libxext
  linuxbrew/xorg/libxmu
  linuxbrew/xorg/libxpm
  linuxbrew/xorg/libxt
Dependencies with no linkage:
  xorg
~~~

This message may be by design.
https://github.com/Linuxbrew/brew/issues/438

Should I care this problem?

**Comment by iMichka** [comment]
I think we can leave this like this for the linkage.

circle.ci is red not because of that, but of the following error:
```
texlive:
  * Non-executables were installed to "/home/linuxbrew/.linuxbrew/opt/texlive/bin"
    The offending files are:
      /home/linuxbrew/.linuxbrew/opt/texlive/bin/x86_64-linux
==> FAILED
```

What is that file? We may ignore that audit for the time being.

One last thing you should do is to safeguard the two new dependencies in an `unless OS.mac? ... end` block, so that we know these dependencies are only for Linux. Once this is done I'll merge this PR.

**Comment by iMichka** [comment]
If you have any questions or need help, please feel free to ask.

There is still a syntax error: `Error: undefined method `/' for "bin/x86_64-linux":String`

I see you are trying to fix the audit error related to this.
I think the problem is that `bin.install_symlink Dir[binarch/"*"]` installs `bin/x86_64-linux/*`, and keeps the folder structure. This is why the `x86_64-linux` folder is copied. Maybe `bin.install` would be enough?

By the way, you can use `git commit --amend` instead of `git commit`. We want only one single commit at the end. If you feel confident to squash them all to a single commit, you can do it, but if you do not know how to do it, I'll do it for you when merging.

**Comment by whiter462** [comment]
Thanks @iMichka 

I added some modifications.
and source file was changed on 20171026 with 4,027,112 bytes and new maybe single SHA256
`929965f57591bad3544bd0fc9f4e8ad2a69ad33a444d9c1ca4030dfa4bb118c9`

still got error, you mentioned
~~~
Warning: Non-executables were installed to "/home/linuxbrew/.linuxbrew/opt/texlive/bin"
The offending files are:
  /home/linuxbrew/.linuxbrew/opt/texlive/bin/x86_64-linux
~~~

I'll try only `bin.install`.

Sorry for many commits, but I edited on webpage.

**Comment by whiter462** [comment]
finally, I got passed.

Please check this commit, @iMichka .

**Comment by whiter462** [comment]
Thank you for your advices, @iMichka

**Comment by iMichka** [comment]
@whiter462 Thanks for your contribution!

**Pull request closed without merging**
