### PR TITLE
harfbuzz: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by sjackman** [comment]
Hmm. `libxml2` seems broken. Seven failures that all look like:
```
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -lxml2
Missing libraries: libxml2.so.2
undefined reference to `xmlDocSetRootElement@LIBXML2_2.4.30'
error while loading shared libraries: libxml2.so.2: cannot open shared object file: No such file or directory
```

**Comment by iMichka** [comment]
`libxml2` is being rebuilt here #3983

**Comment by iMichka** [comment]
@maxim-belkin, that one can be rebased, libxml2 bottles have been uploaded

**Comment by maxim-belkin** [comment]
I think the failure is unrelated:
```
failed: brew test --verbose corebird
```

**Comment by sjackman** [comment]
Merged!

**Pull request closed without merging**
