### PR TITLE
inspectrum: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by iMichka** [comment]
You should rebase this, it timed out due to the qt build, I pushed that bottle few hours ago.

**Comment by sjackman** [comment]
Rebased

**Comment by iMichka** [comment]
```
failed: brew test inspectrum --verbose

        Testing inspectrum
==> /home/linuxbrew/.linuxbrew/Cellar/inspectrum/0.2.1/bin/inspectrum -h
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-linuxbrew'
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.
Error: inspectrum: failed
<0> expected but was
<1>.
```

**Comment by iMichka** [comment]
You could disable that test for Linux.

**Comment by sjackman** [comment]
I've disabled the test for CircleCI. We could consider running a dummy headless (VNC) X11 server on CircleCI. It's not a priority.

**Comment by sjackman** [comment]
Thanks for merging, Michka.

**Pull request closed without merging**
