### PR TITLE
Merge 2017-05-09

### PR DESCRIPTION
**Pull request by maxim-belkin**
```
Conflicts:
	Formula/awscli.rb
	Formula/cairo.rb
	Formula/cdparanoia.rb
	Formula/docker-compose.rb
	Formula/docker.rb
	Formula/flex.rb
	Formula/freetds.rb
	Formula/git-extras.rb
	Formula/git.rb
	Formula/gmime.rb
	Formula/gupnp.rb
	Formula/kubernetes-helm.rb
	Formula/libglade.rb
	Formula/libmemcached.rb
	Formula/libsoup.rb
	Formula/libusb-compat.rb
	Formula/libvorbis.rb
	Formula/make.rb
	Formula/mariadb.rb
	Formula/mediaconch.rb
	Formula/nano.rb
	Formula/screenresolution.rb
	Formula/subversion.rb
	Formula/tcl-tk.rb
	Formula/tig.rb
	Formula/whois.rb
	Formula/zstd.rb
```

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Failure:
```
==> Verifying git-2.12.2.tar.xz checksum
==> make install prefix=/home/linuxbrew/.linuxbrew/Cellar/git/2.12.2 sysconfdir=/home/linuxbrew/.linuxbrew/etc CC=gcc-4.8 CFLAGS= LDFLAGS= NO_TCLTK=1 NO_OPENSSL=1 APPLE_COMMON_CRYPTO=1
.
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/git/01.make:
2017-05-09 14:07:11 +0000

make
install
prefix=/home/linuxbrew/.linuxbrew/Cellar/git/2.12.2
sysconfdir=/home/linuxbrew/.linuxbrew/etc
CC=gcc-4.8
CFLAGS=
LDFLAGS=
NO_TCLTK=1
NO_OPENSSL=1
APPLE_COMMON_CRYPTO=1

GIT_VERSION = 2.12.2
    * new build flags
gcc-4.8 -o base85.o -c -MF ./.depend/base85.o.d -MQ base85.o -MMD -MP   -I. -DHAVE_ALLOCA_H -DNO_OPENSSL -DNO_GETTEXT -DSHA1_MAX_BLOCK_SIZE="1024L*1024L*1024L"  -DHAVE_PATHS_H -DHAVE_DEV_TTY -DHAVE_CLOCK_GETTIME -DHAVE_CLOCK_MONOTONIC -DHAVE_GETDELIM -DSHA1_HEADER='"block-sha1/sha1.h"'  -DNO_STRLCPY -DSHELL_PATH='"/bin/sh"' -DPAGER_ENV='"LESS=FRX LV=-c"'  base85.c
    * new link flags
    * new prefix flags
gcc-4.8 -o bisect.o -c -MF ./.depend/bisect.o.d -MQ bisect.o -MMD -MP   -I. -DHAVE_ALLOCA_H -DNO_OPENSSL -DNO_GETTEXT -DSHA1_MAX_BLOCK_SIZE="1024L*1024L*1024L"  -DHAVE_PATHS_H -DHAVE_DEV_TTY -DHAVE_CLOCK_GETTIME -DHAVE_CLOCK_MONOTONIC -DHAVE_GETDELIM -DSHA1_HEADER='"block-sha1/sha1.h"'  -DNO_STRLCPY -DSHELL_PATH='"/bin/sh"' -DPAGER_ENV='"LESS=FRX LV=-c"'  bisect.c
gcc-4.8 -o blob.o -c -MF ./.depend/blob.o.d -MQ blob.o -MMD -MP   -I. -DHAVE_ALLOCA_H -DNO_OPENSSL -DNO_GETTEXT -DSHA1_MAX_BLOCK_SIZE="1024L*1024L*1024L"  -DHAVE_PATHS_H -DHAVE_DEV_TTY -DHAVE_CLOCK_GETTIME -DHAVE_CLOCK_MONOTONIC -DHAVE_GETDELIM -DSHA1_HEADER='"block-sha1/sha1.h"'  -DNO_STRLCPY -DSHELL_PATH='"/bin/sh"' -DPAGER_ENV='"LESS=FRX LV=-c"'  blob.c
gcc-4.8 -o branch.o -c -MF ./.depend/branch.o.d -MQ branch.o -MMD -MP   -I. -DHAVE_ALLOCA_H -DNO_OPENSSL -DNO_GETTEXT -DSHA1_MAX_BLOCK_SIZE="1024L*1024L*1024L"  -DHAVE_PATHS_H -DHAVE_DEV_TTY -DHAVE_CLOCK_GETTIME -DHAVE_CLOCK_MONOTONIC -DHAVE_GETDELIM -DSHA1_HEADER='"block-sha1/sha1.h"'  -DNO_STRLCPY -DSHELL_PATH='"/bin/sh"' -DPAGER_ENV='"LESS=FRX LV=-c"'  branch.c
gcc-4.8 -o bulk-checkin.o -c -MF ./.depend/bulk-checkin.o.d -MQ bulk-checkin.o -MMD -MP   -I. -DHAVE_ALLOCA_H -DNO_OPENSSL -DNO_GETTEXT -DSHA1_MAX_BLOCK_SIZE="1024L*1024L*1024L"  -DHAVE_PATHS_H -DHAVE_DEV_TTY -DHAVE_CLOCK_GETTIME -DHAVE_CLOCK_MONOTONIC -DHAVE_GETDELIM -DSHA1_HEADER='"block-sha1/sha1.h"'  -DNO_STRLCPY -DSHELL_PATH='"/bin/sh"' -DPAGER_ENV='"LESS=FRX LV=-c"'  bulk-checkin.c
gcc-4.8 -o bundle.o -c -MF ./.depend/bundle.o.d -MQ bundle.o -MMD -MP   -I. -DHAVE_ALLOCA_H -DNO_OPENSSL -DNO_GETTEXT -DSHA1_MAX_BLOCK_SIZE="1024L*1024L*1024L"  -DHAVE_PATHS_H -DHAVE_DEV_TTY -DHAVE_CLOCK_GETTIME -DHAVE_CLOCK_MONOTONIC -DHAVE_GETDELIM -DSHA1_HEADER='"block-sha1/sha1.h"'  -DNO_STRLCPY -DSHELL_PATH='"/bin/sh"' -DPAGER_ENV='"LESS=FRX LV=-c"'  bundle.c
gcc-4.8 -o cache-tree.o -c -MF ./.depend/cache-tree.o.d -MQ cache-tree.o -MMD -MP   -I. -DHAVE_ALLOCA_H -DNO_OPENSSL -DNO_GETTEXT -DSHA1_MAX_BLOCK_SIZE="1024L*1024L*1024L"  -DHAVE_PATHS_H -DHAVE_DEV_TTY -DHAVE_CLOCK_GETTIME -DHAVE_CLOCK_MONOTONIC -DHAVE_GETDELIM -DSHA1_HEADER='"block-sha1/sha1.h"'  -DNO_STRLCPY -DSHELL_PATH='"/bin/sh"' -DPAGER_ENV='"LESS=FRX LV=-c"'  cache-tree.c
gcc-4.8 -o color.o -c -MF ./.depend/color.o.d -MQ color.o -MMD -MP   -I. -DHAVE_ALLOCA_H -DNO_OPENSSL -DNO_GETTEXT -DSHA1_MAX_BLOCK_SIZE="1024L*1024L*1024L"  -DHAVE_PATHS_H -DHAVE_DEV_TTY -DHAVE_CLOCK_GETTIME -DHAVE_CLOCK_MONOTONIC -DHAVE_GETDELIM -DSHA1_HEADER='"block-sha1/sha1.h"'  -DNO_STRLCPY -DSHELL_PATH='"/bin/sh"' -DPAGER_ENV='"LESS=FRX LV=-c"'  color.c
In file included from blob.c:1:0:
cache.h:40:18: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
```
Since this is a failure with `git`, I suggest adding `depends_on "zlib" => :build` to git in this PR

**Comment by maxim-belkin** [comment]
Another instance of `-lintl`:
```
==> brew test --verbose gdk-pixbuf
Testing gdk-pixbuf
==> /usr/bin/gcc-4.8 test.c -o test -Os -w -pipe -march=native -isystem/home/linuxbrew/.linuxbrew/include -L/home/linuxbrew/.linuxbrew/lib -Wl,--dynamic-linker=/home/linuxbrew/.linuxbrew/lib/ld.so -Wl,-rpath,/home/linuxbrew/.linuxbrew/lib -I/home/linuxbrew/.linuxbrew/opt/gettext/include -I/home/linuxbrew/.linuxbrew/opt/glib/include/glib-2.0 -I/home/linuxbrew/.linuxbrew/opt/glib/lib/glib-2.0/include -I/home/linuxbrew/.linuxbrew/Cellar/gdk-pixbuf/2.36.6/include/gdk-pixbuf-2.0 -I/home/linuxbrew/.linuxbrew/opt/libpng/include/libpng16 -I/home/linuxbrew/.linuxbrew/opt/pcre/include -D_REENTRANT -L/home/linuxbrew/.linuxbrew/opt/gettext/lib -L/home/linuxbrew/.linuxbrew/opt/glib/lib -L/home/linuxbrew/.linuxbrew/Cellar/gdk-pixbuf/2.36.6/lib -lgdk_pixbuf-2.0 -lglib-2.0 -lgobject-2.0 -lintl
.
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/gdk-pixbuf/test.01.gcc-4.8:
2017-05-09 14:14:00 +0000

/usr/bin/gcc-4.8
test.c
-o
test
-Os
-w
-pipe
-march=native
-isystem/home/linuxbrew/.linuxbrew/include
-L/home/linuxbrew/.linuxbrew/lib
-Wl,--dynamic-linker=/home/linuxbrew/.linuxbrew/lib/ld.so
-Wl,-rpath,/home/linuxbrew/.linuxbrew/lib
-I/home/linuxbrew/.linuxbrew/opt/gettext/include
-I/home/linuxbrew/.linuxbrew/opt/glib/include/glib-2.0
-I/home/linuxbrew/.linuxbrew/opt/glib/lib/glib-2.0/include
-I/home/linuxbrew/.linuxbrew/Cellar/gdk-pixbuf/2.36.6/include/gdk-pixbuf-2.0
-I/home/linuxbrew/.linuxbrew/opt/libpng/include/libpng16
-I/home/linuxbrew/.linuxbrew/opt/pcre/include
-D_REENTRANT
-L/home/linuxbrew/.linuxbrew/opt/gettext/lib
-L/home/linuxbrew/.linuxbrew/opt/glib/lib
-L/home/linuxbrew/.linuxbrew/Cellar/gdk-pixbuf/2.36.6/lib
-lgdk_pixbuf-2.0
-lglib-2.0
-lgobject-2.0
-lintl

/usr/bin/ld: cannot find -lintl
collect2: error: ld returned 1 exit status
Error: gdk-pixbuf: failed
```

**Comment by maxim-belkin** [comment]
```
==> brew linkage --test gtk+3
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /lib/x86_64-linux-gnu/librt.so.1
  /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0
No broken dylib links
Unwanted system libraries:
  libatk-bridge-2.0.so.0
==> FAILED
```

**Comment by maxim-belkin** [comment]
```
==> Finishing up
ln -s ../Cellar/gnudatalanguage/0.9.7_1/bin/gdl gdl
rm /home/linuxbrew/.linuxbrew/bin/gdl
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /home/linuxbrew/.linuxbrew
Could not symlink bin/pltek
Target /home/linuxbrew/.linuxbrew/bin/pltek
is a symlink belonging to plplot. You can unlink it:
  brew unlink plplot

To force the link and overwrite all conflicting files:
  brew link --overwrite gnudatalanguage

To list all files that would be deleted:
  brew link --overwrite --dry-run gnudatalanguage

Possible conflicting files are:
/home/linuxbrew/.linuxbrew/bin/pltek -> /home/linuxbrew/.linuxbrew/Cellar/plplot/5.12.0/bin/pltek
/home/linuxbrew/.linuxbrew/include/plplot/disptab.h
/home/linuxbrew/.linuxbrew/include/plplot/drivers.h
/home/linuxbrew/.linuxbrew/include/plplot/pdf.h
/home/linuxbrew/.linuxbrew/include/plplot/plConfig.h
```

gnudatalanguage conflicts with plplot ?

**Comment by sjackman** [comment]
> Since this is a failure with git, I suggest adding depends_on "zlib" => :build to git in this PR

The CI treats merge PRs specially only if the last commit is a merge commit. So you'll have to `git commit --amend` the merge commit rather than putting that in its own commit (which I'd generally prefer).

Another way to do it would be to break this merge PR into three separate merge PRs
1. everything up to `git`
2. only `git`
3. everything after `git`

**Comment by maxim-belkin** [comment]
Ok, let me break everything into 3 separate PRs. They will have names `... part x/3`

**Comment by sjackman** [comment]
I have previously used 2017-05-09-1,  2017-05-09-2,  2017-05-09-3, etc. Whatever works for you.

**Comment by maxim-belkin** [comment]
I was talking about PR titles :)

**Comment by sjackman** [comment]
Ah, yep. Sounds good.

**Comment by sjackman** [comment]
Superseded by #2627 #2628 #2629

**Pull request closed without merging**
