### PR TITLE
jdk: Remove bottle :unneeded

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
So many audit errors! The installation directory should probably be changed from `prefix` to `libexec` (or similar).

```
1.00s==> brew audit jdk --online
Error: 4 problems in 1 formula
jdk:
  * A top-level "man" directory was found
    Homebrew requires that man pages live under share.
    This can often be fixed by passing "--mandir=#{man}" to configure.
  * JARs were installed to "/home/linuxbrew/.linuxbrew/Cellar/jdk/1.8.0-112/lib"
    Installing JARs to "lib" can cause conflicts between packages.
    For Java software, it is typically better for the formula to
    install to "libexec" and then symlink or wrap binaries into "bin".
    See "activemq", "jruby", etc. for examples.
    The offending files are:
      /home/linuxbrew/.linuxbrew/Cellar/jdk/1.8.0-112/lib/sa-jdi.jar
      /home/linuxbrew/.linuxbrew/Cellar/jdk/1.8.0-112/lib/ant-javafx.jar
      /home/linuxbrew/.linuxbrew/Cellar/jdk/1.8.0-112/lib/javafx-mx.jar
      /home/linuxbrew/.linuxbrew/Cellar/jdk/1.8.0-112/lib/jconsole.jar
      /home/linuxbrew/.linuxbrew/Cellar/jdk/1.8.0-112/lib/dt.jar
      /home/linuxbrew/.linuxbrew/Cellar/jdk/1.8.0-112/lib/tools.jar
      /home/linuxbrew/.linuxbrew/Cellar/jdk/1.8.0-112/lib/packager.jar
  * Non-libraries were installed to "/home/linuxbrew/.linuxbrew/Cellar/jdk/1.8.0-112/lib"
    Installing non-libraries to "lib" is discouraged.
    The offending files are:
      /home/linuxbrew/.linuxbrew/Cellar/jdk/1.8.0-112/lib/orb.idl
      /home/linuxbrew/.linuxbrew/Cellar/jdk/1.8.0-112/lib/ir.idl
      /home/linuxbrew/.linuxbrew/Cellar/jdk/1.8.0-112/lib/jexec
      /home/linuxbrew/.linuxbrew/Cellar/jdk/1.8.0-112/lib/ct.sym
  * Non-executables were installed to "/home/linuxbrew/.linuxbrew/Cellar/jdk/1.8.0-112/bin"
    The offending files are:
      /home/linuxbrew/.linuxbrew/Cellar/jdk/1.8.0-112/bin/jmc.ini
==> FAILED
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/190851081#L822

**Comment by sjackman** [comment]
I've got an inclination to just ignore these audit errors. They should only affect this formula, as nothing should depend on `jdk` directly.

**Comment by sjackman** [comment]
Circle
```
==> brew bottle --merge --write --no-commit ./jdk-1.8.0-112.x86_64_linux.bottle.json --keep-old
Error: --keep-old was passed but there was no existing bottle block!
==> jdk
==> FAILED
```
@Linuxbrew/core I thought this bug of `--keep-old` with a new bottle was fixed in `test-bot`?

**Comment by maxim-belkin** [comment]
> @Linuxbrew/core I thought this bug of --keep-old with a new bottle was fixed in test-bot?

https://github.com/Homebrew/brew/pull/1401

**Comment by sjackman** [comment]
Ah, thanks for the reference, Maxim.

**Comment by maxim-belkin** [comment]
"DO NOT MERGE" -- are you testing whether it solves the problem?

**Comment by sjackman** [comment]
Assuming it builds successfully, I'll revert the change to `circle.yml` before I push this PR to `master`.

**Pull request closed without merging**
