### PR TITLE
llvm: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
/usr/bin/ranlib ../libLLVMMC.a
make[2]: Leaving directory `/tmp/llvm-20160721-53029-uzhyt7'
make[2]: Leaving directory `/tmp/llvm-20160721-53029-uzhyt7'
[ 17%] Built target obj.llvm-tblgen
[ 17%] Built target LLVMMC
make[1]: Leaving directory `/tmp/llvm-20160721-53029-uzhyt7'
make: *** [all] Error 2
```

**Comment by sjackman** [comment]
```
CMakeFiles/cxx.dir/__/src/typeinfo.cpp.o:(.data.rel.ro._ZTISt10bad_typeid[_ZTISt10bad_typeid]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libc++.so.1.0] Error 1
make[2]: Leaving directory `/tmp/llvm-20160721-58120-uzik3b'
```

**Comment by sjackman** [comment]
@maxim-belkin Any thoughts on the above error message?

**Comment by maxim-belkin** [comment]
not at the moment. Seems like deparallelization helps but no idea why

**Comment by sjackman** [comment]
@maxim-belkin Does it make sense to disable libc++ for Linux as below?

```diff
--- a/Formula/llvm.rb
+++ b/Formula/llvm.rb
@@ -132,7 +132,11 @@ class Llvm < Formula
 
   option :universal
   option "without-compiler-rt", "Do not build Clang runtime support libraries for code sanitizers, builtins, and profiling"
-  option "without-libcxx", "Do not build libc++ standard library"
+  if OS.mac?
+    option "without-libcxx", "Do not build libc++ standard library"
+  else
+    option "with-libcxx", "Build libc++ standard library"
+  end
   option "with-libcxxabi", "Build libc++abi standard library"
   option "with-toolchain", "Build with Toolchain to facilitate overriding system compiler"
   # From TODO.TXT file in libcxxabi: CMake always link to /usr/lib/libc++abi.dylib on OS X.
```

**Comment by sjackman** [comment]
With the above patch to disable `libc++`, it finally built! `brew test` failed however.

```
==> brew test llvm --verbose
Testing llvm
==> /home/linuxbrew/.linuxbrew/Cellar/llvm/3.8.1/bin/llvm-config --prefix
==> /home/linuxbrew/.linuxbrew/Cellar/llvm/3.8.1/bin/clang -L/home/linuxbrew/.linuxbrew/Cellar/llvm/3.8.1/lib -fopenmp -nobuiltininc -I/home/linuxbrew/.linuxbrew/Cellar/llvm/3.8.1/lib/clang/3.8.1/include omptest.c -o omptest

==> ./omptest
==> /home/linuxbrew/.linuxbrew/Cellar/llvm/3.8.1/bin/clang++ -v -nostdinc -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/include -I/usr/include test.cpp -o testCLT++
.
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/llvm/02.clang++:
2016-07-22 01:59:07 +0000

/home/linuxbrew/.linuxbrew/Cellar/llvm/3.8.1/bin/clang++
-v
-nostdinc
-I/Library/Developer/CommandLineTools/usr/include/c++/v1
-I/include
-I/usr/include
test.cpp
-o
testCLT++

clang version 3.8.1 (tags/RELEASE_381/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/linuxbrew/.linuxbrew/Cellar/llvm/3.8.1/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/home/linuxbrew/.linuxbrew/Cellar/llvm/3.8.1/bin/clang-3.8" -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name test.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -v -dwarf-column-info -debugger-tuning=gdb -nostdsysteminc -nobuiltininc -resource-dir /home/linuxbrew/.linuxbrew/Cellar/llvm/3.8.1/bin/../lib/clang/3.8.1 -I /Library/Developer/CommandLineTools/usr/include/c++/v1 -I /include -I /usr/include -I/home/linuxbrew/.linuxbrew/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/x86_64-linux-gnu/c++/4.8 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/x86_64-linux-gnu/c++/4.8 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/backward -fdeprecated-macro -fdebug-compilation-dir /tmp/llvm-test-20160722-100993-s7fzpm -ferror-limit 19 -fmessage-length 0 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -o /tmp/test-5f2229.o -x c++ test.cpp
clang -cc1 version 3.8.1 based upon LLVM 3.8.1 default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/Library/Developer/CommandLineTools/usr/include/c++/v1"
ignoring nonexistent directory "/include"
ignoring duplicate directory "/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/x86_64-linux-gnu/c++/4.8"
#include "..." search starts here:
#include <...> search starts here:
 /usr/include
 /home/linuxbrew/.linuxbrew/include
 /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8
 /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/x86_64-linux-gnu/c++/4.8
 /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/backward
End of search list.
In file included from test.cpp:1:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/iostream:38:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/x86_64-linux-gnu/c++/4.8/bits/c++config.h:426:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/x86_64-linux-gnu/c++/4.8/bits/os_defines.h:39:
/usr/include/features.h:374:12: fatal error: 'sys/cdefs.h' file not found
#  include <sys/cdefs.h>
           ^
1 error generated.
Error: llvm: failed
Failed executing: /home/linuxbrew/.linuxbrew/Cellar/llvm/3.8.1/bin/clang++ -v -nostdinc -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/include -I/usr/include test.cpp -o testCLT++
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1508:in `block in system'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1445:in `open'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1445:in `system'
/home/linuxbrew/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb:378:in `block in <class:Llvm>'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1350:in `block in run_test'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:75:in `block in run'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:75:in `chdir'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:75:in `run'
/home/linuxbrew/.linuxbrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:1344:in `run_test'
/home/linuxbrew/.linuxbrew/Library/Homebrew/test.rb:33:in `block in <main>'
/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/home/linuxbrew/.linuxbrew/Library/Homebrew/test.rb:32:in `<main>'
==> FAILED
```

@maxim-belkin Any thoughts? Does `brew test llvm` work for you?

**Comment by sjackman** [comment]
`llvm` conflicts with `gcc`, which is lame.
```
/gsc/btl/linuxbrew/lib/libgomp.so -> /gsc/btl/linuxbrew/Cellar/gcc/5.3.0/lib/libgomp.so
/gsc/btl/linuxbrew/lib/libunwind.so -> /gsc/btl/linuxbrew/Cellar/libunwind/1.1/lib/libunwind.so
```

Can `llvm` instead depend on `gcc` and `libunwind` and remove these two conflicting files?

Turns out `libgomp.so` is a symlink to `libomp.so`, so I think we can just remove the `libgomp.so` symlink.

`llvm`'s `libunwind.so` is a symlink to `libunwind.so.1.0`
whereas `libunwind`'s `libunwind.so` is a symlink to `libunwind.so.8.0.1`

Still the answer is probably to remove the `libunwind.so` symlink from `llvm`.

**Comment by sjackman** [comment]
`brew test llvm` fails on my system:
```
❯❯❯ brew test llvm
Testing llvm
==> /gsc/btl/linuxbrew/Cellar/llvm/3.8.1/bin/llvm-config --prefix
==> /gsc/btl/linuxbrew/Cellar/llvm/3.8.1/bin/clang -L/gsc/btl/linuxbrew/Cellar/l
==> ./omptest
Error: llvm: failed
<0> expected but was
<nil>.
```

**Comment by sjackman** [comment]
`--gcc-toolchain=$(brew --prefix)/lib` is useful for specifying the location of `crtbegin.o`, `-lgcc` and `-lgcc_s`
http://llvm.org/docs/GettingStarted.html#getting-a-modern-host-c-toolchain

**Pull request closed without merging**
