### PR TITLE
Merge 2017-08-23 b9cf978515

### PR DESCRIPTION
**Pull request by iMichka**
+ [ ] boost-bcp
+ [ ] boost-python
+ [ ] boost
+ [ ] osmium-tool

### CODE REVIEW

**Comment by sjackman** [comment]
That's fewer conflicts than I expected.

**Comment by iMichka** [comment]
I think we had just the 4 main bottles. Maybe be will get some more; sometimes some tools build automatically.

And you know what I just discovered ... you can `brew install wesnoth`!

**Comment by sjackman** [comment]
The build timed out after five hours. Because of that, it looks like no bottles were transferred.
No `Uploading artifacts` step is run in CircleCI.
Instead the last lines are
```
==> git checkout pull/3971 -f
Already on 'pull/3971'
==> brew cleanup --prune=7
Build timedout
Build was timedout after 5h0m0s
```

**Comment by sjackman** [comment]
These formulae had linkage failures

### Homebrew/core
apache-arrow.rb
apngasm.rb
bastet.rb
libphonenumber.rb
nghttp2.rb
pdns.rb
pdnsrec.rb

### Homebrew/science
alpscore
augustus
bless
ome-common
ome-files
ome-xml
rapsearch2
shark

**Comment by sjackman** [comment]
I'm going to build a bottle for `boost` 1.65.0 manually in Docker.

**Comment by sjackman** [comment]
Done!

**Pull request merged**
