### PR TITLE
docbook-utils (new formula)

### PR DESCRIPTION
**Pull request by rwhogg**
- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by rwhogg** [comment]
https://travis-ci.org/Linuxbrew/homebrew-core/builds/173777390#L1827

```
/tmp/opensp-20161107-23088-x60dxk/OpenSP-1.5.2/docsrc/osgmlnorm.xml:3: warning: failed to load external entity "/usr/share/sgml/docbook/xml-dtd-4.1.2/docbookx.dtd"
```

We should probably add `export XML_CATALOG_FILES="/home/linuxbrew/.linuxbrew/etc/xml/catalog"` to the Travis file. Although I am remarkably confused, since this seems to get exported on [line 1224](https://travis-ci.org/Linuxbrew/homebrew-core/builds/173777390#L1224).

**Comment by sjackman** [comment]
If you mean
```
==> Caveats
To use the DocBook package in your XML toolchain,
you need to add the following to your ~/.bashrc:
export XML_CATALOG_FILES="/home/linuxbrew/.linuxbrew/etc/xml/catalog"
```
that's just an informational message to the user. It's not executed.

**Comment by maxim-belkin** [comment]
ping) linuxbrew/extra?

**Comment by rwhogg** [comment]
> ping) linuxbrew/extra?

I no longer remember the reason I started working on this formula in the first place... That might be a good home for these though.

**Comment by sjackman** [comment]
Something depended on it. I believe for an executable named `docbook2html` or `docbook2pdf` or something.

**Comment by maxim-belkin** [comment]
Let's move this to `linuxbrew/extra`

**Comment by maxim-belkin** [comment]
### OpenSP

* opensp:
  \* C: 24: col 20: Missing space after #.

```
==> brew test opensp --verbose
Testing opensp
==> false
```

### openjade & docbook-utils
```
compilation terminated.
ELObj.cxx:7:33: fatal error: InterpreterMessages.h: No such file or directory
 #include "InterpreterMessages.h"
```

**Comment by maxim-belkin** [comment]
@rwhogg will you move it to `linuxbrew/extra` or do you want me to do it?

**Comment by sjackman** [comment]
As I recall, `docbook-utils` is a dependency of formulae in `Linuxbrew/core`, in which case it should stay in `core`.

**Comment by rwhogg** [comment]
I don't think I'm likely to ever get around to finishing this, so I'm just going to close it.

**Pull request closed without merging**
