### PR TITLE
rrdtool: Build a bottle for Linuxbrew: error: unrecognized command line option '-Wshorten-64-to-32'

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
/home/linuxbrew/.linuxbrew/bin/gcc-5 -c  -I/tmp/rrdtool-20170106-10918-v4roqk/rrdtool-1.6.0/src -I/tmp/rrdtool-20170106-10918-v4roqk/rrdtool-1.6.0/src -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g   -DVERSION=\"1.5001\" -DXS_VERSION=\"1.5001\" -fPIC "-I/usr/lib/perl/5.14/CORE"  -DPERLPATCHLEVEL=14 RRDs.c
checking for rrd_create() in -lrrd... no
creating Makefile
make[3]: Entering directory `/tmp/rrdtool-20170106-10918-v4roqk/rrdtool-1.6.0/bindings/ruby'
compiling main.c
gcc-5: error: unrecognized command line option '-Wshorten-64-to-32'
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/189556977#L5273

**Comment by maxim-belkin** [comment]
Apple's extension to gcc that never made it to the upstream

**Comment by emanresusername** [comment]
is [this](https://github.com/Linuxbrew/brew/pull/446/files) related? (also breaking `ntopng` install)

**Comment by sjackman** [comment]
I'm afraid that I don't have a solution to this issue. A PR would be most welcome if you're able to sort it out yourself. Superenv could be used to remove `-Wshorten-64-to-32` from the command line. I'm unsure why that macOS-specific option is being added to the command line though. I don't see anything in the `rrdtool` formula.

**Pull request closed without merging**
