### PR TITLE
gobject-introspection: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
==> brew test --verbose easyrpg-player
Testing easyrpg-player
==> /home/linuxbrew/.linuxbrew/Cellar/easyrpg-player/0.5.1_1/bin/easyrpg-player -v
/home/linuxbrew/.linuxbrew/Cellar/easyrpg-player/0.5.1_1/bin/easyrpg-player: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/linuxbrew/.linuxbrew/lib/liblcf.so.0)
/home/linuxbrew/.linuxbrew/Cellar/easyrpg-player/0.5.1_1/bin/easyrpg-player: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/linuxbrew/.linuxbrew/lib/liblcf.so.0)
/home/linuxbrew/.linuxbrew/Cellar/easyrpg-player/0.5.1_1/bin/easyrpg-player: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/linuxbrew/.linuxbrew/lib/liblcf.so.0)
Error: easyrpg-player: failed
<0> expected but was
<1>.
==> FAILED
```
https://circleci.com/api/v1.1/project/github/Linuxbrew/homebrew-core/6990/output/31/0?file=true

**Comment by sjackman** [comment]
Error while building `gkt+3`
```
checking for GDK_DEP... no
configure: error: Package requirements (pango pangocairo gdk-pixbuf-2.0 >= 2.30.0 cairo >= 1.14.0 cairo-gobject >= 1.14.0 gio-unix-2.0 >= 2.49.4 fontconfig x11 xext xinerama xi xrandr xcursor xfixes xcomposite xdamage    cairo-xlib epoxy >= 1.0) were not met:

No package 'epoxy' found
```

**Comment by sjackman** [comment]
Error while building `pygobject`
```
checking for headers required to compile python extensions... not found
configure: error: Python headers not found
```

**Comment by sjackman** [comment]
`brew test --verbose libgit2-glib` failed
```
Failed executing: /home/linuxbrew/.linuxbrew/Cellar/libgit2-glib/0.25.0_1/libexec/general /tmp/libgit2-glib-test-20170729-9344-19oftz1/horatio
```

**Comment by sjackman** [comment]
`brew test libnice` failed
```
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -lintl
```

**Comment by sjackman** [comment]
`brew link gnudatalanguage` failed
```
Error: The `brew link` step did not complete successfully
==> Finishing up
ln -s ../Cellar/gnudatalanguage/0.9.7_3/bin/gdl gdl
rm /home/linuxbrew/.linuxbrew/bin/gdl
The formula built, but is not symlinked into /home/linuxbrew/.linuxbrew
Could not symlink bin/pltek
Target /home/linuxbrew/.linuxbrew/bin/pltek
is a symlink belonging to plplot. You can unlink it:
  brew unlink plplot

To force the link and overwrite all conflicting files:
  brew link --overwrite gnudatalanguage

To list all files that would be deleted:
  brew link --overwrite --dry-run gnudatalanguage
```

**Comment by sjackman** [comment]
Merging despite these failures.

**Comment by rwhogg** [comment]
> Error while building gkt+3

That's a problem with superenv. `pkg-config` under superenv doesn't pick up stuff under `lib/"x86_64-linux-gnu/pkgconfig"`, which is where `libepoxy` puts `epoxy.pc`.

I've opened a WIP PR to fix this at https://github.com/Linuxbrew/brew/pull/442

**Pull request closed without merging**
