### PR TITLE
mono: build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by rwhogg** [comment]
From https://travis-ci.org/Linuxbrew/homebrew-core/builds/127491563#L5366-L5371

```
Testing mono
==> /home/linuxbrew/.linuxbrew/Cellar/mono/4.2.3.4/bin/mcs hello.cs
libgcc_s.so.1 must be installed for pthread_cancel to work
Error: mono: failed
<0> expected but was
<nil>.
```

**Comment by rwhogg** [comment]
Huh, that had no effect.

This one's going to require deeper digging.

**Comment by DoomHammer** [comment]
`strace` to see where this `libgcc_s.so.1` is being searched in?

**Comment by rwhogg** [comment]
See #705

**Comment by rwhogg** [comment]
Wow, it actually worked!

Since it's been so long since I submitted this, I'd like to remove the GCC dependency and see if it still builds. If it does, I'll merge it like that; otherwise, I'll merge it like this.

**Comment by rwhogg** [comment]
It failed, but only because of an audit failure that second commit introduced.

**Pull request closed without merging**
