### PR TITLE
Merge 2017-03-20

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
10 bottles have been built!

**Comment by sjackman** [comment]
Wow, that's great!

**Comment by maxim-belkin** [comment]
but I'm not sure how to pull them :(

**Comment by sjackman** [comment]
It'll be tricky to pull them now, after the PR is merged. Next time around try:
```sh
brew pull --bottle --keep-going https://github.com/Linuxbrew/homebrew-core/pull/2118
```
`--keep-going` says to ignore the errors about bottles missing for some of the modified formula. This script could be improved to expect bottles only for those formula that have had their bottle `sha256` updated for Linuxbrew by the PR.

**Comment by sjackman** [comment]
It should also check that `brew test` passes for each of the bottles on CircleCI. Right now you'd have to manually browse through the log to confirm that, which is a tad tedious.

**Comment by sjackman** [comment]
Rather than opening a separate `Build bottles for merge 2017-xx-xx` issue, I've been putting the bottle checklist in the merge PR. That step could be automated by `brew merge-homebrew --core`.

**Comment by maxim-belkin** [comment]
`brew pull` will also pull changes introduced by the PR (I tried that). Hence the question.

**Comment by sjackman** [comment]
That's intended, right?
```sh
git checkout master
git reset --hard origin/master
brew pull --bottle --keep-going https://github.com/Linuxbrew/homebrew-core/pull/2118
```

**Comment by maxim-belkin** [comment]
doesn't `pull --bottle` squash something once it's done ?

**Comment by sjackman** [comment]
It can, but only if the `diff` contains the string `: Build a bottle for Linuxbrew`
https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/dev-cmd/pull.rb#L238

**Comment by maxim-belkin** [comment]
got it! thanks! I knew I was doing something wrong :)

**Comment by sjackman** [comment]
No worries. This process could use some documentation for Linuxbrew maintainers.

**Comment by sjackman** [comment]
I forgot that the `bot.linuxbrew.sh/ci-upload` doesn't yet work with merge PRs, until it gets a fix (adding `--keep-going` to it). You can do it manually using `brew pull-circle --keep-going --ci-upload`.

**Comment by sjackman** [comment]
A low-tech solution is to run `brew build-bottle-pr` after the merge for both the conflicting formula as well as the ones with bottles built successfully by the merge PR.

**Pull request merged**
