### PR TITLE
jpeg: Fixes for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
```
Error: 2 problems in 1 formula
jpeg:
  * Formula has other versions so create a versioned alias:
      cd /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases
      ln -s ../Formula/jpeg.rb jpeg@9b
  * Formula has invalid versioned aliases:
      jpeg@9
```

**Comment by maxim-belkin** [comment]
`dcraw` has to be rebuilt
```
==> brew linkage --test dcraw
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /usr/lib/x86_64-linux-gnu/libjpeg.so.8
No broken dylib links
Unwanted system libraries:
  libjpeg.so.8
==> FAILED
```

**Comment by maxim-belkin** [comment]
`fltk` has to be rebuild:
```
==> brew linkage --test fltk
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libdl.so.2
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /usr/lib/x86_64-linux-gnu/libjpeg.so.8
No broken dylib links
Unwanted system libraries:
  libjpeg.so.8
Warning: fltk dependency pcre was built with a different C++ standard
library (libstdc++ from gcc-4.8). This may cause problems at runtime.
==> FAILED
```

**Comment by maxim-belkin** [comment]
same for `gd`:

```
==> brew linkage --test gd
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /usr/lib/x86_64-linux-gnu/libjpeg.so.8
No broken dylib links
Unwanted system libraries:
  libjpeg.so.8
==> FAILED
```

**Comment by maxim-belkin** [comment]
same for `gdk-pixbuf`:

```
==> brew linkage --test gdk-pixbuf
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /usr/lib/x86_64-linux-gnu/libjpeg.so.8
No broken dylib links
Unwanted system libraries:
  libjpeg.so.8
==> FAILED
```

**Comment by maxim-belkin** [comment]
`gmic`:

```
==> brew linkage --test gmic
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /usr/lib/x86_64-linux-gnu/libjpeg.so.8
No broken dylib links
Unwanted system libraries:
  libjpeg.so.8
==> FAILED
```

**Comment by maxim-belkin** [comment]
```
==> brew linkage --test graphicsmagick
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /usr/lib/x86_64-linux-gnu/libjpeg.so.8
No broken dylib links
Unwanted system libraries:
  libjpeg.so.8
Warning: graphicsmagick dependency libtiff was built with a different C++ standard
library (libstdc++ from gcc-4.8). This may cause problems at runtime.
==> FAILED
```

**Comment by maxim-belkin** [comment]
```
==> brew linkage --test gst-plugins-good
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /usr/lib/x86_64-linux-gnu/libjpeg.so.8
No broken dylib links
Unwanted system libraries:
  libjpeg.so.8
==> FAILED
```

**Comment by maxim-belkin** [comment]
```
==> brew linkage --test imagemagick
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /usr/lib/x86_64-linux-gnu/libjpeg.so.8
No broken dylib links
Unwanted system libraries:
  libjpeg.so.8
Warning: imagemagick dependency libtiff was built with a different C++ standard
library (libstdc++ from gcc-4.8). This may cause problems at runtime.
==> FAILED
```

**Comment by maxim-belkin** [comment]
```
==> brew linkage --test imagemagick@6
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /usr/lib/x86_64-linux-gnu/libjpeg.so.8
No broken dylib links
Unwanted system libraries:
  libjpeg.so.8
Warning: imagemagick@6 dependency libtiff was built with a different C++ standard
library (libstdc++ from gcc-4.8). This may cause problems at runtime.
==> FAILED
```

**Comment by maxim-belkin** [comment]
```
==> brew linkage --test imageworsener
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /usr/lib/x86_64-linux-gnu/libjpeg.so.8
No broken dylib links
Unwanted system libraries:
  libjpeg.so.8
==> FAILED
```

**Comment by maxim-belkin** [comment]
```
==> brew linkage --test imlib2
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libdl.so.2
  /lib/x86_64-linux-gnu/libm.so.6
  /usr/lib/x86_64-linux-gnu/libjpeg.so.8
No broken dylib links
Unwanted system libraries:
  libjpeg.so.8
==> FAILED
```

**Comment by maxim-belkin** [comment]
```
==> brew linkage --test jasper
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /usr/lib/x86_64-linux-gnu/libjpeg.so.8
No broken dylib links
Unwanted system libraries:
  libjpeg.so.8
==> FAILED
```

**Comment by maxim-belkin** [comment]
```
==> brew linkage --test leptonica
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /usr/lib/x86_64-linux-gnu/libjpeg.so.8
No broken dylib links
Unwanted system libraries:
  libjpeg.so.8
==> FAILED
```

**Comment by maxim-belkin** [comment]
Fall failed commands:
```
==> brew audit jpeg --online
==> brew linkage --test dcraw
==> brew linkage --test fltk
==> brew linkage --test gd
==> brew install gdal
==> brew linkage --test gdk-pixbuf
==> brew linkage --test gmic
==> brew linkage --test graphicsmagick
==> brew linkage --test gst-plugins-good
==> brew linkage --test imagemagick
==> brew linkage --test imagemagick@6
==> brew linkage --test imageworsener
==> brew linkage --test imlib2
==> brew linkage --test jasper
==> brew linkage --test leptonica
==> brew linkage --test libgphoto2
==> brew linkage --test libtiff
==> brew linkage --test little-cms2
==> brew install mapserver
==> brew linkage --test netpbm
==> brew test --verbose ocamlsdl
==> brew linkage --test pike
==> brew linkage --test poppler
==> brew linkage --test r
==> brew linkage --test sane-backends
==> brew linkage --test sdl2_image
==> brew linkage --test sdl_image
==> brew linkage --test ufraw
==> brew linkage --test vips
==> brew linkage --test volatility
==> brew test --verbose volatility
==> brew linkage --test webp
==> brew linkage --test wxmac
```

**Comment by sjackman** [comment]
Superseded by https://github.com/Linuxbrew/homebrew-core/pull/3670

**Pull request closed without merging**
