### PR TITLE
pike: Depends on jpeg for Linuxbrew

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by rwhogg** [comment]
So, apparently `pike` is linking against the system `libjpeg`:

```
==> brew linkage --test pike
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libcrypt.so.1
  /lib/x86_64-linux-gnu/libdl.so.2
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libnsl.so.1
  /lib/x86_64-linux-gnu/libpthread.so.0
  /lib/x86_64-linux-gnu/librt.so.1
  /usr/lib/x86_64-linux-gnu/libjpeg.so.8
No broken dylib links
Unwanted system libraries:
  libjpeg.so.8
==> FAILED
```

**Comment by sjackman** [comment]
Remove `libjpeg62-dev` in the CI configs, and `depends_on "jpeg" unless OS.mac?`

**Comment by rwhogg** [comment]
The library in question seems to come from `libjpeg-turbo8` (the dev package is not installed), but I don't really want to remove non-dev packages from Circle.

It might make more sense just to retry this after #3816 is merged.

**Comment by sjackman** [comment]
I'm hoping to merge #3816 soon, today or tomorrow.

**Comment by rwhogg** [comment]
Succeeds on Circle 2.0!

Travis is still having the same issue; hoping removing `libjpeg8-dev` will fix that.

**Comment by rwhogg** [comment]
Yeah, it worked!

**Comment by sjackman** [comment]
I'm so glad to be rid of all those `lib…-dev` packages on CircleCI.

**Pull request closed without merging**
