### PR TITLE
clang: Alias for llvm [Linux]

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
I wonder whether upstream would consider renaming `llvm` to `clang` now that the `clang` executable is built by default.

**Comment by iMichka** [comment]
That would mean changing all the `depends_on "llvm"` to `depends_on "clang"` I guess. Not sure this is going to happen.

**Comment by sjackman** [comment]
There's only 11 formulae that depend on `llvm`. That's not so bad.

**Comment by iMichka** [comment]
Maybe @ilovezfs has an opinion on that, before we submit a pull request in homebrew-core.

- Could we rename `llvm` to `clang`?
- or does an alias make more sense?

**Comment by ilovezfs** [comment]
Probably neither because aliases for versioned formulae are awkward (i.e. Will we support an alias clang@3.9, etc.? Would we add an audit to make sure those always get created for new versioned formulae?), and the formula is used almost exclusively for the llvm part, not the clang part, in Homebrew.

**Comment by jonchang** [comment]
They might support an addition to `missing_formula.rb` so when you try to `brew install clang` it'll tell you that it comes with the Xcode CLT but you can also get a brewed copy through `llvm`.

**Comment by ilovezfs** [comment]
That seems like an abuse of missing formula to me.

**Comment by ilovezfs** [comment]
Basically an alias is the right answer but someone would have to write the audit code to make sure a new alias gets created for each new versioned llvm and another audit to make sure the versioned alias for the unversioned llvm formula gets updated every time llvm gets upgraded, and we'd have to be willing to maintain that symlink farm.

**Comment by iMichka** [comment]
I am not sure that you can say that one specific clang version is related to a specific llvm version. It is like this in homebrew because they are built from the same formula, but I think both projects are decoupled. What would be the version scheme for clang?

Also; apple clang is a patched `clang`, so you never really know what version you are using. So you are not really installing the same `clang` than the one provided by Apple.

The discussion here is due to the fact that I was working on the `chakra` formula for Linux, and it needs `clang`, not `llvm`. So I was wondering where I would get `clang` from on Linux, and did not directly realise that the `llvm` formula provided `clang`. I looked at the caveats but there was no hint of that. Maybe just adding a line that it is also install `clang` would have helped. Not sure we want to maintain aliases and stuff.

**Comment by ilovezfs** [comment]
```
iMac-TMP:~ joe$ /usr/local/Cellar/llvm/4.0.1/bin/clang-4.0 --version
clang version 4.0.1 (tags/RELEASE_401/final)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /usr/local/Cellar/llvm/4.0.1/bin
iMac-TMP:~ joe$ 
```
There's a fairly clear relationship between the llvm version and the clang version ;)

**Comment by iMichka** [comment]
This is because we choose to do that. But I think that you can check out the clang and llvm repos locally, and build mismatched versions (you can choose 2 different commits in each tree). They may report the same version, but the commits may be different from what upstream tagged as valid releases (not sure they tag anything, they use SVN and different branches for each release).

And of course Apple is even more complicated, for example:
```
clang-700.0.72 => LLVM 3.7.0
clang-700.1.76 => LLVM 3.7.0
clang-700.1.81 => LLVM 3.7.0
clang-703.0.29 => LLVM 3.8.0
clang-703.0.31 => LLVM 3.8.0
```

**Comment by ilovezfs** [comment]
It's an upstream version not "because we choose to do that": http://blog.llvm.org/2016/12/llvms-new-versioning-scheme.html

Not sure how the versioning of Apple's toolchain is relevant here.

**Comment by iMichka** [comment]
Thanks for that link, I wasn't aware of it.

We did choose to have a formula which produces `llvm 4.0.1` and `clang 4.0.1`. We could have chosen to produce `llvm 4.0.0` and `clang 4.0.1`. It would probably not make any sense to use it like that though.

Back to the initial question/problem. Do we want to do anything about the naming / aliasing, or should we choose the status-quo and leave it like it is?

**Comment by iMichka** [comment]
Let's close this. I think the status-quo is the best solution here. We are not going to change the naming of `llvm` or add aliases for different versions, that is too much work for not so much benefit.

**Pull request closed without merging**
