### PR TITLE
pandoc-crossref: Build a bottle for Linuxbrew (blocked by #1940)

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by rwhogg** [comment]
From Circle:

```
Configuring zlib-0.6.1.2...
Setup: Missing dependency on a foreign library:
* Missing (or bad) header file: zlib.h
* Missing C library: z
This problem can usually be solved by installing the system package that
provides this library (you may need the "-dev" version). If the library is
already installed but in a non-standard location then you can use the flags
--extra-include-dirs= and --extra-lib-dirs= to specify where it is.
If the header file does exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.

Error during cabal-install bootstrap:
Configuring the zlib package failed.
```

**Comment by sjackman** [comment]
I've merge the `zlib` PR. Strange error that is.

**Comment by sjackman** [comment]
Perhaps `depends_on "zlib" unless OS.mac?" would resolve this issue.

**Comment by rwhogg** [comment]
Marking as blocked by #1940

**Pull request closed without merging**
