### PR TITLE
glibc: Help gcc find crti.o

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by sjackman** [comment]
I don't know of any distributions that use `/usr/lib32`. Can you give an example? I'd be inclined to remove it.

What's the error message that this PR address, and do we have steps to reproduce it? Do we have a user-reported issue that this PR addresses?

**Comment by iMichka** [comment]
The error is described in #7695: `ld: cannot find crti.o: No such file or directory`

I used the more general solution proposed by @xu-cheng for gcc :)

**Comment by sjackman** [comment]
Looks good to me. Do we know why this fix is needed on some systems but not others?

**Comment by xu-cheng** [comment]
> Do we know why this fix is needed on some systems but not others?

I am not entirely sure, as I don't know how to reproduce this bug. I assume this bug only happens when using brewed gcc + system glibc? If so, this may be caused by my following codes:

https://github.com/Linuxbrew/homebrew-core/blob/f0b470d752d9704f6a0d796868a510c525ad8c8a/Formula/gcc.rb#L116-L118

As a result, it may search the wrong the library. However, these codes are required to make different brewed gcc coexist. 

If it were the case, a better solution maybe change
https://github.com/Linuxbrew/homebrew-core/blob/f0b470d752d9704f6a0d796868a510c525ad8c8a/Formula/gcc.rb#L283-L284
to
```ruby
if glibc_installed
  crtdir = glibc.opt_lib
else
  crtdir = Pathname.new(Utils.popen_read("/usr/bin/cc", "-print-file-name=crti.o")).parent
end
ln_sf Dir[crtdir/"*crt?.o"], libgcc
```

**Please note that the above comments are all speculations.**

**Comment by iMichka** [comment]
Maybe this would be a good solution, which also does not imply hacking around in the glibc formula.
I will update this PR accordingly, and use ENV.cc instead of `/usr/bin/cc`.

Even if ENV.cc changes; the path to the system's glibc should not change.
People on centos will the be able to build gcc, and then rebuild gcc with brewed glibc. For people with newer systems and a newer glibc, the right file will be symlinked.

The only danger would be a glib update, but I am not sure this happens really often (at least in LTS versions).

**Comment by iMichka** [comment]
@Gwang-Jin can you test if this works for you?
You should just pull the change for gcc and run `brew postinstall gcc`. This should create a symlink for crti.o in the Cellar, and you should then be able to build glibc.

**Comment by xu-cheng** [comment]
> use ENV.cc instead of /usr/bin/cc.

Actually, I think we may want to use `/usr/bin/cc` in this case, at least for `gcc.rb`. The reason is that I am not sure what would happen if `ENV.cc` points to the current gcc formula. If it points back to itself, it may not be able to find glibc in the first place.

Though I am not entirely sure, so you may need to do some testing.

**Comment by iMichka** [comment]
@xu-cheng I think this works because:

**On systems with older `glibc` where we need to build from source (centos-6 for example)**
`brew install gcc --without-glibc` -> at this point, brewed `glibc` is not installed, ENV.cc points to whatever compiler is on the system, the symlink points to the system's `glibc`.
`brew install glibc`
`brew install gcc`  -> at this point, brewed `glibc` is installed, so we symlink that one.

**On systems with older `glibc` where we pour bottles**
We pour the `glibc` formula first, and then the `gcc` bottle. The symlink will then point to the brewed `glibc` (same situation as the last step above).

**On systems with newer `glibc`**, we do not allow to install brewed `glibc`, so the symlink will always point to the system's `glibc`.

I hope my explanation was clear :)

**Comment by xu-cheng** [comment]
@iMichka Thanks for the explanation. What I have in mind is a rather edge case. What would happen for the following situation?

* User's system has sufficient new glibc. 
* User runs `brew install gcc`. 
* During the `post_install`, the `ENV.cc` may point to the just installed brew gcc itself. 
* Then `ENV.cc -print-file-name=crti.o` may return an empty path, since brew gcc is unable to find system glibc in the first place. 
* As a result, `ln_sf Dir[crtdir/"*crt?.o"], libgcc` will have no effect.

**Comment by sjackman** [comment]
> During the post_install, the ENV.cc may point to the just installed brew gcc itself.

This may be the case when the user runs `brew postinstall gcc` (unconfirmed).

**Comment by iMichka** [comment]
Right. I will test this as soon as possible.

**Comment by iMichka** [comment]
When running `brew postinstall gcc` on ubuntu 18.04, I get:
> ==> undefined method `cc' for #<Object:0x00000001e511d0>

Looks like ENV.cc is not set during post-install.

We could go for "cc" though, and take whatever is in the path. In this case I get `/usr/lib/x86_64-linux-gnu/` as path for the crt files.

**Comment by iMichka** [comment]
Yes, this gives me `/home/linuxbrew/.linuxbrew/bin/cc`. We could use `homebrew_bin/"cc"`.

The returned path for the `crt` files is then:
`/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/`, which contains `*crt` symlinks to `/usr/lib/x86_64-linux-gnu/`.

There may be one drawback: you pour the bottle and you do not have `/usr/lib/x86_64-linux-gnu/`, but something else. Not sure what happens then.

**Comment by iMichka** [comment]
Right, I tried to be too clever here :) Let's got for `/usr/lib/cc`. I added the fix for `gcc@4.9` too.

**Pull request closed without merging**
