### PR TITLE
texlive 20181029

### PR DESCRIPTION
**Pull request by sjackman**
Fix broken symlinks in bin.

### CODE REVIEW

**Comment by sjackman** [comment]
I've retriggered this PR three times with `git commit --amend && git push --force`, and CircleCI won't trigger.

**Comment by iMichka** [comment]
The only way is to open/close the PR. I am still in contact with circleci regarding that matter.

**Comment by sjackman** [comment]
Thanks, Michka!

**Comment by iMichka** [comment]
Thanks @sjackman !

**Pull request closed without merging**
