### PR TITLE
Merge 2017-07-20 85cb865aef

### PR DESCRIPTION
**Pull request by maxim-belkin**
- [ ] hdf5

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Expecting this to fail because of `zlib` :)

**Comment by maxim-belkin** [comment]
Failures:
1. hdf5
```
==> brew audit hdf5 --online --new-formula
...
Error: 1 problem in 1 formula
hdf5:
  * New formulae should not use `deprecated_option`.
==> FAILED
```
2. NetCDF
```
99% tests passed, 2 tests failed out of 175

Total Test time (real) =  86.61 sec

The following tests FAILED:
	 44 - ncdump_tst_nccopy4 (Failed)
	137 - tst_h_vars (Failed)
Errors while running CTest
make: *** [test] Error 8
```
3. alpscore

```
/tmp/ccoKz8vf.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > alps::params_ns::detail::validate_cast<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
test.cpp:(.text+0x436): undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)'
/tmp/ccoKz8vf.o: In function `bool alps::params_ns::detail::validate_cast<bool>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
test.cpp:(.text+0x575): undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool*, int)'
/tmp/ccoKz8vf.o: In function `boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)':
test.cpp:(.text._ZN5boost15program_options16validation_errorC2ENS1_6kind_tERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_i[_ZN5boost15program_options16validation_errorC5ENS1_6kind_tERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_i]+0x2e): undefined reference to `boost::program_options::validation_error::get_template[abi:cxx11](boost::program_options::validation_error::kind_t)'
test.cpp:(.text._ZN5boost15program_options16validation_errorC2ENS1_6kind_tERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_i[_ZN5boost15program_options16validation_errorC5ENS1_6kind_tERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_i]+0x4c): undefined reference to `boost::program_options::error_with_option_name::error_with_option_name(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
/tmp/ccoKz8vf.o:(.rodata._ZTVN5boost15program_options20invalid_option_valueE[_ZTVN5boost15program_options20invalid_option_valueE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/tmp/ccoKz8vf.o:(.rodata._ZTVN5boost15program_options16validation_errorE[_ZTVN5boost15program_options16validation_errorE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/tmp/ccoKz8vf.o: In function `void boost::program_options::validate<double, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, double*, long)':
test.cpp:(.text._ZN5boost15program_options8validateIdcEEvRNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIT0_St11char_traitsIS7_ESaIS7_EEESaISB_EEPT_l[_ZN5boost15program_options8validateIdcEEvRNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIT0_St11char_traitsIS7_ESaIS7_EEESaISB_EEPT_l]+0x11b): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/ccoKz8vf.o: In function `void boost::program_options::validate<unsigned long, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, unsigned long*, long)':
test.cpp:(.text._ZN5boost15program_options8validateImcEEvRNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIT0_St11char_traitsIS7_ESaIS7_EEESaISB_EEPT_l[_ZN5boost15program_options8validateImcEEvRNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIT0_St11char_traitsIS7_ESaIS7_EEESaISB_EEPT_l]+0x116): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/ccoKz8vf.o: In function `void boost::program_options::validate<long, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, long*, long)':
test.cpp:(.text._ZN5boost15program_options8validateIlcEEvRNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIT0_St11char_traitsIS7_ESaIS7_EEESaISB_EEPT_l[_ZN5boost15program_options8validateIlcEEvRNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIT0_St11char_traitsIS7_ESaIS7_EEESaISB_EEPT_l]+0x116): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/ccoKz8vf.o: In function `void boost::program_options::validate<unsigned int, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, unsigned int*, long)':
test.cpp:(.text._ZN5boost15program_options8validateIjcEEvRNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIT0_St11char_traitsIS7_ESaIS7_EEESaISB_EEPT_l[_ZN5boost15program_options8validateIjcEEvRNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIT0_St11char_traitsIS7_ESaIS7_EEESaISB_EEPT_l]+0x115): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/ccoKz8vf.o: In function `void boost::program_options::validate<int, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, int*, long)':
test.cpp:(.text._ZN5boost15program_options8validateIicEEvRNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIT0_St11char_traitsIS7_ESaIS7_EEESaISB_EEPT_l[_ZN5boost15program_options8validateIicEEvRNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIT0_St11char_traitsIS7_ESaIS7_EEESaISB_EEPT_l]+0x115): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/ccoKz8vf.o:(.rodata._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE[_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE]+0x38): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/tmp/ccoKz8vf.o:(.rodata._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/tmp/ccoKz8vf.o:(.rodata._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE[_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE]+0x38): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/tmp/ccoKz8vf.o:(.rodata._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/home/linuxbrew/.linuxbrew/lib/libalps-params.so: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/home/linuxbrew/.linuxbrew/lib/libalps-params.so: undefined reference to `boost::program_options::detail::cmdline::cmdline(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
/home/linuxbrew/.linuxbrew/lib/libalps-params.so: undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
/home/linuxbrew/.linuxbrew/lib/libalps-params.so: undefined reference to `boost::program_options::arg[abi:cxx11]'
/home/linuxbrew/.linuxbrew/lib/libalps-params.so: undefined reference to `boost::program_options::to_internal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
Error: homebrew/science/alpscore: failed
Failed executing: mpicxx test.cpp -lalps-accumulators -lalps-hdf5 -lalps-utilities -lalps-params -lboost_filesystem-mt -lboost_system-mt -lboost_program_options-mt -o test
```

4. blasr:
```
=> brew linkage --test blasr
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /lib/x86_64-linux-gnu/librt.so.1
Missing libraries:
  libhdf5.so.10
  libhdf5_cpp.so.11
No unwanted system libraries
==> FAILED
```

5. dextractor
```
==> brew test --verbose dextractor
Testing homebrew/science/dextractor
==> /home/linuxbrew/.linuxbrew/Cellar/dextractor/1.0_4/bin/dextract 2>&1
Error: homebrew/science/dextractor: failed
Expected /Usage/ to match "(null): zlib library is not present, check build/installation\n".
==> FAILED
```

6. flann
```
=> brew linkage --test flann
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
Missing libraries:
  libhdf5.so.100
No unwanted system libraries
==> FAILED
```

7. insighttoolkit
```
==> brew linkage --test insighttoolkit
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libdl.so.2
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libnsl.so.1
  /lib/x86_64-linux-gnu/libpthread.so.0
  /lib/x86_64-linux-gnu/libthread_db.so.1
  /usr/lib/x86_64-linux-gnu/libasound.so.2
  /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
Missing libraries:
  libhdf5_cpp.so.101
  libjawt.so
  libjvm.so
  libmawt.so
  libodbc.so
  libodbcinst.so
  libvtkCommonColor-7.1.so.1
  libvtkCommonComputationalGeometry-7.1.so.1
  libvtkCommonCore-7.1.so.1
  libvtkCommonDataModel-7.1.so.1
  libvtkCommonExecutionModel-7.1.so.1
  libvtkCommonMath-7.1.so.1
  libvtkCommonMisc-7.1.so.1
  libvtkCommonSystem-7.1.so.1
  libvtkCommonTransforms-7.1.so.1
  libvtkDICOMParser-7.1.so.1
  libvtkFiltersCore-7.1.so.1
  libvtkFiltersExtraction-7.1.so.1
  libvtkFiltersGeneral-7.1.so.1
  libvtkFiltersGeometry-7.1.so.1
  libvtkFiltersSources-7.1.so.1
  libvtkFiltersStatistics-7.1.so.1
  libvtkIOImage-7.1.so.1
  libvtkImagingCore-7.1.so.1
  libvtkImagingFourier-7.1.so.1
  libvtkImagingSources-7.1.so.1
  libvtkInteractionStyle-7.1.so.1
  libvtkRenderingCore-7.1.so.1
  libvtkRenderingFreeType-7.1.so.1
  libvtkRenderingOpenGL2-7.1.so.1
  libvtkalglib-7.1.so.1
  libvtkfreetype-7.1.so.1
  libvtkglew-7.1.so.1
  libvtkmetaio-7.1.so.1
  libvtksys-7.1.so.1
Unwanted system libraries:
  libGL.so.1
  libasound.so.2
  libthread_db.so.1
```

8. libbi
```
==> brew test --verbose libbi
Testing homebrew/science/libbi
==> /home/linuxbrew/.linuxbrew/Cellar/libbi/1.3.0_4/bin/libbi sample @test.conf
.
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/libbi/test.01.libbi:
2017-07-20 13:56:00 +0000

/home/linuxbrew/.linuxbrew/Cellar/libbi/1.3.0_4/bin/libbi
sample
@test.conf

Stash.c: loadable library and perl binaries are mismatched (got handshake key 0xdb80080, needed 0xde00080)
Error: homebrew/science/libbi: failed
Failed executing: /home/linuxbrew/.linuxbrew/Cellar/libbi/1.3.0_4/bin/libbi sample @test.conf
```

9. boost

**Comment by maxim-belkin** [comment]
I'm not so sure about zlib. hdf5 built successfully without it

**Comment by rwhogg** [comment]
> I'm not so sure about zlib. hdf5 built successfully without it

From release_docs/INSTALL:

> 3. HDF5 dependencies
3.1. Zlib
        The HDF5 Library includes a predefined compression filter that 
        uses the "deflate" method for chunked datasets. If zlib-1.1.2 or
        later is found, HDF5 will use it.  Otherwise, HDF5's predefined
        compression method will degenerate to a no-op; the compression
        filter will succeed but the data will not be compressed.

Based on that, I'd say it's a good idea to include it either way, even if it's not strictly necessary. `zlib`'s a core dependency of lots of other stuff anyways, and given that the immediate next dependency on that list is labeled "optional" and `zlib` isn't, I'm personally in favor of including it.

**Comment by rwhogg** [comment]
New failure: `moose`

```
==> brew linkage --test moose
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
Missing libraries:
  libgsl.so.19
No unwanted system libraries
Warning: homebrew/science/moose dependency hdf5 was built with a different C++ standard
library (libstdc++ from gcc-4.8). This may cause problems at runtime.
==> FAILED
==> brew test --verbose moose
Testing homebrew/science/moose
==> python -c import moose
.
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/moose/test.01.python:
2017-07-21 02:15:51 +0000

python
-c
import moose

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.13/lib/python2.7/site-packages/moose/__init__.py", line 25, in <module>
    from .moose import *
  File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.13/lib/python2.7/site-packages/moose/moose.py", line 17, in <module>
    from . import _moose
ImportError: libgsl.so.19: cannot open shared object file: No such file or directory
Error: homebrew/science/moose: failed
Failed executing: python -c import\ moose
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1804:in `block in system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1742:in `open'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1742:in `system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-science/moose.rb:69:in `block in <class:Moose>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1639:in `block (2 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:832:in `with_logging'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1638:in `block in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1632:in `run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:33:in `block in <main>'
/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:32:in `<main>'
==> FAILED
```

nixio:

```
==> brew test --verbose nixio
Testing homebrew/science/nixio
==> Downloading https://raw.githubusercontent.com/G-Node/nix-demo/master/data/spike_features.h5
/home/linuxbrew/.linuxbrew/opt/curl/bin/curl --remote-time --location --user-agent Linuxbrew/1.2.4-2-g59a338502 (Linux; x86_64 Ubuntu 14.04.4 LTS) curl/7.54.1 --fail --silent https://raw.githubusercontent.com/G-Node/nix-demo/master/data/spike_features.h5 -C 0 -o /home/ubuntu/.cache/Homebrew/nixio--demofile-features.h5.incomplete
==> Verifying nixio--demofile-features.h5 checksum
==> /home/linuxbrew/.linuxbrew/Cellar/nixio/1.4.0/bin/nix-tool dump spike_features.h5
.
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/nixio/test.01.nix-tool:
2017-07-21 02:17:00 +0000

/home/linuxbrew/.linuxbrew/Cellar/nixio/1.4.0/bin/nix-tool
dump
spike_features.h5

/home/linuxbrew/.linuxbrew/Cellar/nixio/1.4.0/bin/nix-tool: symbol lookup error: /home/linuxbrew/.linuxbrew/Cellar/nixio/1.4.0/bin/nix-tool: undefined symbol: _ZN5boost15program_options3argE
Error: homebrew/science/nixio: failed
Failed executing: /home/linuxbrew/.linuxbrew/Cellar/nixio/1.4.0/bin/nix-tool dump spike_features.h5
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1804:in `block in system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1742:in `open'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1742:in `system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-science/nixio.rb:44:in `block (2 levels) in <class:Nixio>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:97:in `block in unpack'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:93:in `unpack'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:85:in `stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-science/nixio.rb:43:in `block in <class:Nixio>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1639:in `block (2 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:832:in `with_logging'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1638:in `block in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1632:in `run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:33:in `block in <main>'
/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:32:in `<main>'
==> FAILED
```

radx:

```
==> brew linkage --test radx
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
Missing libraries:
  libhdf5_cpp.so.100
No unwanted system libraries
Warning: homebrew/science/radx dependency hdf5 was built with a different C++ standard
library (libstdc++ from gcc-4.8). This may cause problems at runtime.
==> FAILED
==> brew test --verbose radx
Testing homebrew/science/radx
==> /home/linuxbrew/.linuxbrew/Cellar/radx/20160809_5/bin/RadxPrint -h
.
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/radx/test.01.RadxPrint:
2017-07-21 02:40:44 +0000

/home/linuxbrew/.linuxbrew/Cellar/radx/20160809_5/bin/RadxPrint
-h

/home/linuxbrew/.linuxbrew/Cellar/radx/20160809_5/bin/RadxPrint: error while loading shared libraries: libhdf5_cpp.so.100: cannot open shared object file: No such file or directory
Error: homebrew/science/radx: failed
Failed executing: /home/linuxbrew/.linuxbrew/Cellar/radx/20160809_5/bin/RadxPrint -h
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1804:in `block in system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1742:in `open'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1742:in `system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-science/radx.rb:35:in `block in <class:Radx>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1639:in `block (2 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:832:in `with_logging'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1638:in `block in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1632:in `run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:33:in `block in <main>'
/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:32:in `<main>'
==> FAILED
```

shogun (because r was migrated)

```
==> brew install shogun
==> Installing shogun from homebrew/science
Error: No available formula with the name "r" (dependency of homebrew/science/shogun)
It was migrated from homebrew/science to homebrew/core.
==> FAILED
```


statismo

```
==> brew test --verbose statismo
Testing homebrew/science/statismo
==> /home/linuxbrew/.linuxbrew/Cellar/statismo/0.11.0_12/bin/statismo-build-shape-model --help
.
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/statismo/test.01.statismo-build-shape-model:
2017-07-21 02:42:26 +0000

/home/linuxbrew/.linuxbrew/Cellar/statismo/0.11.0_12/bin/statismo-build-shape-model
--help

/home/linuxbrew/.linuxbrew/Cellar/statismo/0.11.0_12/bin/statismo-build-shape-model: error while loading shared libraries: libhdf5_cpp.so.100: cannot open shared object file: No such file or directory
Error: homebrew/science/statismo: failed
Failed executing: /home/linuxbrew/.linuxbrew/Cellar/statismo/0.11.0_12/bin/statismo-build-shape-model --help
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1804:in `block in system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1742:in `open'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1742:in `system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-science/statismo.rb:43:in `block in <class:Statismo>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1639:in `block (2 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:832:in `with_logging'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1638:in `block in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1632:in `run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:33:in `block in <main>'
/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:32:in `<main>'
==> FAILED
```

swrcfit

```
==> Installing swrcfit from homebrew/science
Error: homebrew/science/swrcfit contains conflicting version recursive dependencies:
  openssl, openssl@1.1
View these with `brew deps --tree homebrew/science/swrcfit`.
==> FAILED
```

**Comment by rwhogg** [comment]
@maxim-belkin are you okay with me merging with the `zlib` dependency or would you rather if I took it back out?

**Comment by rwhogg** [comment]
Well, this is just great. Like `python` used to do, `hdf5` apparently embeds a specific GCC version into `h5cc`, making the compiler fail if run on a system without that version available. (It's 4.8 in this case).

The old homebrew-science bottle apparently had the same problem, so I'll let this slide, but FYI @jonchang and @sjackman in case you weren't aware.

**Pull request closed without merging**
