### PR TITLE
pypy: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
⏳

**Comment by iMichka** [comment]
Lol. I’m sitting in the train right now. I’ll start the compilation when I am back home :)

**Comment by maxim-belkin** [comment]
🚂

**Comment by iMichka** [comment]
```
==> Bottling pypy-6.0.0.x86_64_linux.bottle.1.tar.gz...
Error: Failure while executing: /home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --print-rpath '/home/linuxbrew/.linuxbrew/Cellar/pypy/6.0.0/libexec/bin/libpypy-c.so.debug' 2>&1
strange: no string table 
==> FAILED
```

**Comment by maxim-belkin** [comment]
🤔  I'm trying it now in my Linuxbrew container.

**Comment by maxim-belkin** [comment]
```
$ file /home/linuxbrew/.linuxbrew/Cellar/pypy/6.0.0/libexec/bin/libpypy-c.so.debug 
/home/linuxbrew/.linuxbrew/Cellar/pypy/6.0.0/libexec/bin/libpypy-c.so.debug: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped

$ ldd /home/linuxbrew/.linuxbrew/Cellar/pypy/6.0.0/libexec/bin/libpypy-c.so.debug 
ldd: warning: you do not have execution permission for `/home/linuxbrew/.linuxbrew/Cellar/pypy/6.0.0/libexec/bin/libpypy-c.so.debug'
	statically linked
```

**Comment by maxim-belkin** [comment]
Same problem as in https://github.com/spack/spack/issues/6677 with a fix in https://github.com/spack/spack/pull/6679
We need to safeguard the call to `patchelf`

**Comment by maxim-belkin** [comment]
@sjackman, here is the (zipped) file, in case you'd want to work with it and don't want to spend an hour compiling it :)

[libpypy-c.so.debug.zip](https://github.com/Linuxbrew/homebrew-core/files/2143706/libpypy-c.so.debug.zip)

**Comment by sjackman** [comment]
The fix will go here if you'd like to take a stab at fixing it yourself:
https://github.com/Linuxbrew/brew/blob/3ba4c2ed9b0587040949a4a9a95b576f520bae84/Library/Homebrew/extend/os/linux/keg_relocate.rb#L25
Otherwise give a reminder, and I'll fix it.

**Comment by maxim-belkin** [comment]
> if you'd like to take a stab
🔪 😱 

will do

**Comment by sjackman** [comment]
I've merged Linuxbrew/brew#740.

**Comment by maxim-belkin** [comment]
Just an FYI:
```
=> Detecting if pypy-6.0.0.x86_64_linux.bottle.2.tar.gz is relocatable...
Warning: String '/home/linuxbrew/.linuxbrew' still exists in these files:
/home/linuxbrew/.linuxbrew/Cellar/pypy/6.0.0/libexec/bin/pypy.debug
 --> match '/home/linuxbrew/.linuxbrew/Cellar/gcc/5.3.0/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include' at offset 0x86f
Warning: String '/home/linuxbrew/.linuxbrew/Cellar' still exists in these files:
/home/linuxbrew/.linuxbrew/Cellar/pypy/6.0.0/libexec/bin/pypy.debug
 --> match '/home/linuxbrew/.linuxbrew/Cellar/gcc/5.3.0/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include' at offset 0x86f
```

```sh
$ file /home/linuxbrew/.linuxbrew/Cellar/pypy/6.0.0/libexec/bin/pypy.debug
/home/linuxbrew/.linuxbrew/Cellar/pypy/6.0.0/libexec/bin/pypy.debug: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter *empty*, for GNU/Linux 2.6.32, not stripped
```

**Comment by sjackman** [comment]
Thanks for the heads up. We can safely ignore those warnings.

**Comment by iMichka** [comment]
I'll try a new bottling tomorrow :) Thanks!

**Comment by maxim-belkin** [comment]
🎉

**Comment by sjackman** [comment]
Woohoo! 🎉
I've opened a PR for `pypy3`. https://github.com/Linuxbrew/homebrew-core/pull/8372

**Pull request closed without merging**
