### PR TITLE
go: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by DoomHammer**

### CODE REVIEW

**Comment by DoomHammer** [comment]
Patchelf has problems with `go` binaries. Reported in https://github.com/NixOS/patchelf/pull/95

**Comment by sjackman** [comment]
Fixed by https://github.com/Linuxbrew/homebrew-core/pull/352

**Comment by DoomHammer** [comment]
I believe we haven't seen that yet. Am I right @sjackman ?

```
cannot find section .dynamic
Error: undefined method `write' for nil:NilClass
```

**Comment by sjackman** [comment]
`cannot find section .dynamic` is not yet fixed. The proposal is to use `file` to skip non-dynamic ELF files.

**Comment by rwhogg** [comment]
@DoomHammer, can we close this now? It looks like a `go` bottle was already pushed by the test bot.

**Comment by DoomHammer** [comment]
Pushed the changes yesterday, thought they should close this as well.

**Pull request closed without merging**
