### PR TITLE
glibmm: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by sjackman** [comment]
`brew test libxml++ libxml++3` failed on TravisCI.
```
/home/linuxbrew/.linuxbrew/Cellar/libxml++/2.40.1/lib/libxml++-2.6.so: undefined reference to `Glib::ustring::rbegin()'
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/219735975#L3492

**Comment by rwhogg** [comment]
> I don't see this error on my local machine.

C++11 ABI issue due to Travis' old compiler?

**Comment by sjackman** [comment]
When I pour bottles for `libsigc++ glibmm libxml++` then `brew test libsigc++ glibmm libxml++` works fine. If you rebuild `glibmm` from source using Linuxbrew GCC 5.3 then `brew test libsigc++ glibmm` succeeds, but `brew test libxml++` fails. All three of these formulae `needs :cxx11`.

**Comment by sjackman** [comment]
Here's what I gather from that (needs verification).
`b` depends on `a`, both compiled with `-std=c++11`

| `a` | `b` | Status |
|---|---|---|
| 4.8 | 4.8 | ✅ |
| 4.8 | 5.3 | ✅ |
| 5.3 | 4.8 | ❌ |
| 5.3 | 5.3 | ✅ |

**Comment by sjackman** [comment]
Based on this, I believe we can ignore this CI failure on Travis. It would be helpful to detect this situation, and skip the test. Or perhaps even better, drop GCC 4.8 all together and move forward with a more recent version of GCC, possibly GCC 6.

**Comment by sjackman** [comment]
The funny thing is that `brew` has logic to detect this situation, though it's evidently not working in this case.
```
  # If either package doesn't use C++, all is well
  # libstdc++ and libc++ aren't ever intercompatible
  # libstdc++ is compatible across Apple compilers, but
  # not between Apple and GNU compilers, or between GNU compiler versions
  def compatible_with?(other)
```
https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/cxxstdlib.rb#L46

**Comment by sjackman** [comment]
Linuxbrew doesn't implement `detect_cxx_stdlibs`
https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/extend/os/mac/keg_relocate.rb#L47

**Comment by sjackman** [comment]
This issue has been affecting Homebrew/science recently. I'll take a stab at implementing `detect_cxx_stdlibs`.

**Comment by maxim-belkin** [comment]
> This issue has been affecting Homebrew/science recently. I'll take a stab at implementing `detect_cxx_stdlibs`.

Soooo.... should I rerun the build?

**Comment by sjackman** [comment]
I think you can merge this bottle even though TravisCI failed. We know why it failed. A better solution than simply ignoring the TravisCI failure would be good ultimately.

**Pull request closed without merging**
