### PR TITLE
Add formula for ladspa-swh (audio plugin)

### PR DESCRIPTION
**Pull request by binarykitchen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

---

See https://github.com/Linuxbrew/homebrew-core/issues/1037 for more info. Not sure if all is correct as this is my first time ...

### CODE REVIEW

**Comment by maxim-belkin** [comment]
failure on CI is due to `--keep-old` option and does not indicate a problem with the formula.

**Comment by maxim-belkin** [comment]
@binarykitchen looks like you don't need `ladspa-header` here, right?

**Comment by sjackman** [comment]
This formula should go in a new tap I think.

**Comment by maxim-belkin** [comment]
kinda agree. `homebrew-audio` ? :)

**Comment by sjackman** [comment]
If this formula builds on Mac OS, it should go there. You could try `Homebrew/core`.
If it does not build on Mac OS, I'd suggest a personal tap `binarykitchen/homebrew-audio` for now.
If that tap becomes popular enough, it can be migrated to `Linuxbrew/homebrew-audio`.
Closing, but feel free to continue this discussion.

**Comment by binarykitchen** [comment]
guys, i dont understand? what's wrong with this? i really need this so that i can install ffmpeg with rubberband on linux, see https://github.com/Linuxbrew/homebrew-core/issues/1037#issue-181913324

or can someone else, who is more experienced with linuxbrew, do it? @sjackman ?

**Comment by maxim-belkin** [comment]
@binarykitchen, here are the instructions:
1. create a new (empty) repository on github and call it `ladspa-audio` or `homebrew-audio`
2. clone it to your local machine
3. Add the file from this PR (`git add`, `git commit`)
4*. Add the ladspa-header file form the other PR following the same procedure
5. `git push`
6. `brew tap binarykitchen/ladspa-audio`
7.  `brew install ladspa-swh`

* you can also add ladspa header as a resource to the formula in this PR. There is no real advantage to either approach as some people later down the road might need `ladspa-header` and then they'll use your repo.
You can also add `README.md` to the project to describe what is contained in it

**Comment by sjackman** [comment]
The only new formula accepted into Linuxbrew/core are those that are dependencies of other formula already in Linuxbrew/core that are required dependencies for Linuxbrew but not for Mac OS. Other new formula should either go in Homebrew/core if they build on Mac, or in a new tap if they do not build on Mac.

**Pull request closed without merging**
