### PR TITLE
httpflow: depend on libpcap

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
g++-4.8 -lz -lpcap -lpcre http_flow.o http_parser.o custom_parser.o util.o data_link.o -o httpflow
...
custom_parser.o: In function `custom_parser::filter_url(real_pcre const*, pcre_extra const*, std::string const&)':
custom_parser.cpp:(.text+0x749): undefined reference to `pcre_exec'
util.o: In function `gzip_decompress(std::string&, std::string&)':
util.cpp:(.text+0x164): undefined reference to `inflateInit2_'
util.cpp:(.text+0x1b7): undefined reference to `inflate'
util.cpp:(.text+0x1e5): undefined reference to `inflateEnd'
collect2: error: ld returned 1 exit status
```

**Comment by sjackman** [comment]
```
g++-4.8 -lz -lpcap -lpcre http_flow.o http_parser.o custom_parser.o util.o data_link.o -o httpflow
```
should be
```
g++-4.8 http_flow.o http_parser.o custom_parser.o util.o data_link.o -o httpflow -lpcap -lpcre -lz
```
You could patch the Makefile. Or try rebasing and cross your fingers. If that doesn't work, it may work to `depends_on "binutils" => :build`. I think a newer `ld` is smarter about `-l` options.

**Comment by iMichka** [comment]
Let's try with a rebase first

**Comment by iMichka** [comment]
```
g++-5 -lz -lpcap -lpcre http_flow.o http_parser.o custom_parser.o util.o data_link.o -o httpflow
http_flow.o: In function `print_usage()':
http_flow.cpp:(.text+0xd2): undefined reference to `pcap_lib_version'
http_flow.o: In function `init_capture_config(int, char**, capture_config*, char*)':
http_flow.cpp:(.text+0x452): undefined reference to `pcre_compile'
http_flow.cpp:(.text+0x46e): undefined reference to `pcre_study'
http_flow.cpp:(.text+0x51a): undefined reference to `pcap_lookupdev'
http_flow.o: In function `main':
http_flow.cpp:(.text.startup+0x9f): undefined reference to `pcap_lookupnet'
http_flow.cpp:(.text.startup+0xbc): undefined reference to `pcap_open_live'
http_flow.cpp:(.text.startup+0xd0): undefined reference to `pcap_datalink'
http_flow.cpp:(.text.startup+0xe8): undefined reference to `pcap_compile'
http_flow.cpp:(.text.startup+0xfe): undefined reference to `pcap_setfilter'
http_flow.cpp:(.text.startup+0x111): undefined reference to `pcap_freecode'
http_flow.cpp:(.text.startup+0x119): undefined reference to `pcap_datalink'
http_flow.cpp:(.text.startup+0x1df): undefined reference to `pcap_loop'
http_flow.cpp:(.text.startup+0x22e): undefined reference to `pcap_close'
http_flow.cpp:(.text.startup+0x23a): undefined reference to `pcap_geterr'
http_flow.cpp:(.text.startup+0x26e): undefined reference to `pcap_close'
http_flow.cpp:(.text.startup+0x2ba): undefined reference to `pcap_open_offline'
http_flow.cpp:(.text.startup+0x2e4): undefined reference to `pcap_geterr'
http_flow.cpp:(.text.startup+0x34a): undefined reference to `pcap_geterr'
custom_parser.o: In function `custom_parser::filter_url(real_pcre const*, pcre_extra const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
custom_parser.cpp:(.text+0x9cf): undefined reference to `pcre_exec'
util.o: In function `gzip_decompress(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
util.cpp:(.text+0x216): undefined reference to `inflateInit2_'
util.cpp:(.text+0x268): undefined reference to `inflate'
util.cpp:(.text+0x29f): undefined reference to `inflateEnd'
collect2: error: ld returned 1 exit status
Makefile:30: recipe for target 'all' failed
make: *** [all] Error 1
```

**Pull request closed without merging**
