### PR TITLE
Create paraview.rb

### PR DESCRIPTION
**Pull request by Gwang-Jin**
Based on @sjackman 's comment [https://github.com/brewsci/homebrew-science/issues/177#issuecomment-393684229](https://github.com/brewsci/homebrew-science/issues/177#issuecomment-393684229), I have submitted my RB.

I fix the original paraview.rb (Mac OS version) to install in Linuxbrew. And
1. version up to 5.4.1
2. add option "osmesa"
3. add option "mpich"

Thank you.

- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<Formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by Gwang-Jin** [comment]
Oh, `ci/circleci` says
```
Warning: Found Ruby file outside homebrew/core tap formula directory
(/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula):
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/paraview.rb
```

I would like to migrate `brewsci/science/paraview.rb` to this tap.
How should I do?
Thank you.

**Comment by iMichka** [comment]
I would prefer to not add this to the core repository because I am not sure I want to work on maintaining this. The formula is not there on Mac. Why not add it to the science repo: https://github.com/brewsci/ ?

**Comment by Gwang-Jin** [comment]
I tried to submit `brewsci/homebrew-science` but it is rejected [https://github.com/brewsci/homebrew-science/pull/191#issuecomment-408967433](https://github.com/brewsci/homebrew-science/pull/191#issuecomment-408967433). And making new tap only for `paraview` would be abnormal(?). If your comment means reject, there is no tap to submit my RB.
Thank you.

**Comment by iMichka** [comment]
You should submit it to: https://github.com/brewsci/homebrew-base

The homebrew-science repo is just there for the history, and is legacy.

**Comment by iMichka** [comment]
But maybe @sjackman would like to have it in this repo?

**Pull request closed without merging**
