### PR TITLE
io: bump revision for libxml

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by sjackman** [comment]
```
    depends_on "ossp-uuid"
```
`libuuid` is provided by `util-linux` on Linux rather than `ossp-uuid`, and the two conflict.
I suggest…
```ruby
if OS.mac?
  depends_on "ossp-uuid"
else
  depends_on "util-linux" # for libuuid
end
```

**Comment by iMichka** [comment]
```
failed: brew linkage --test io

        Missing libraries:
  libIoOgg.so
  libIoRange.so
```

**Comment by sjackman** [comment]
```
❯❯❯ brew list io | egrep 'libIoOgg.so|libIoRange.so'
/home/linuxbrew/.linuxbrew/Cellar/io/2017.09.06/lib/io/addons/Ogg/_build/dll/libIoOgg.so
/home/linuxbrew/.linuxbrew/Cellar/io/2017.09.06/lib/io/addons/Range/_build/dll/libIoRange.so
```
It's unusual for the library to be in directory named `_build`. I thought that may be a packaging bug, but looking at the formula, it looks intentional.

```
$ ldd /home/linuxbrew/.linuxbrew/Cellar/io/2017.09.06/lib/io/addons/Vorbis/_build/dll/libIoVorbis.so | grep 'not found'
	libIoOgg.so => not found
```
It looks like `io` finds and loads these shared libraries at run-time, using its own search path. So the audit failure is a false positive, but I'm not sure that we have a mechanism to override it.

**Comment by maxim-belkin** [comment]
How about `patchelf` in `postinstall`?

**Comment by sjackman** [comment]
> How about patchelf in postinstall?

Yep, that's possible. Or even better in the `def install` itself. My best guess though is that fixing up the `RPATH` isn't actually needed for the correct functioning of the software. We're only doing it to silence `brew audit`, which isn't ideal in my opinion.

**Comment by maxim-belkin** [comment]
if only we could `linkage.skip_test ["libOgg.so", "libBlah.so"]`... but then, again, this case is suspicious.

**Comment by iMichka** [comment]
On mac:
```
[michkapopoff:~] brew list io | egrep 'libIoOgg.dylib|libIoRange.dylib'
/usr/local/Cellar/io/2017.09.06/lib/io/addons/Ogg/_build/dll/libIoOgg.dylib
/usr/local/Cellar/io/2017.09.06/lib/io/addons/Range/_build/dll/libIoRange.dylib
[michkapopoff:~] brew linkage --test io
No broken library linkage
```

**Comment by maxim-belkin** [comment]
```
$ otool -L /usr/local/Cellar/io/2017.09.06/lib/io/addons/Vorbis/_build/dll/libIoVorbis.dylib 
/usr/local/Cellar/io/2017.09.06/lib/io/addons/Vorbis/_build/dll/libIoVorbis.dylib:
	/usr/local/opt/io/lib/io/addons/Vorbis/_build/dll/libIoVorbis.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/libvorbis/lib/libvorbis.0.dylib (compatibility version 5.0.0, current version 5.8.0)
	@rpath/libIoOgg.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libiovmall.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libcoroutine.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libgarbagecollector.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libbasekit.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
	/usr/local/opt/libogg/lib/libogg.0.dylib (compatibility version 9.0.0, current version 9.3.0)
```

**Comment by sjackman** [comment]
On macOS, the default behaviour is to embed the pull path to each dependent shared library.

**Comment by iMichka** [comment]
Merged as-is. I have too many PR's open and will probably not have time to fix this now.

**Pull request closed without merging**
