### PR TITLE
Mapnik: fixes

### PR DESCRIPTION
**Pull request by maxim-belkin**
Supersedes #1210

### CODE REVIEW

**Comment by maxim-belkin** [comment]
2 interesting failures on Circle:

<span>#</span>1:
```
==> brew audit mapnik --online
Error: 1 problem in 1 formula
mapnik:
  * Formula has other versions so create an alias:
      cd /home/linuxbrew/.linuxbrew/Library/Taps/homebrew/homebrew-core/Aliases
      ln -s ../Formula/mapnik.rb mapnik@3
==> FAILED
```
<span>#</span>2:
```
==> brew linkage mapnik
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libdl.so.2
  /lib/x86_64-linux-gnu/libgcc_s.so.1
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /usr/lib/x86_64-linux-gnu/libpq.so.5
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6
Homebrew libraries:
  /home/linuxbrew/.linuxbrew/lib/libboost_filesystem.so.1.63.0 (boost)
  /home/linuxbrew/.linuxbrew/lib/libboost_program_options.so.1.63.0 (boost)
  /home/linuxbrew/.linuxbrew/lib/libboost_regex.so.1.63.0 (boost)
  /home/linuxbrew/.linuxbrew/lib/libboost_system.so.1.63.0 (boost)
  /home/linuxbrew/.linuxbrew/lib/libfreetype.so.6 (freetype)
  /home/linuxbrew/.linuxbrew/lib/libharfbuzz.so.0 (harfbuzz)
  /home/linuxbrew/.linuxbrew/lib/libicuuc.so.58 (icu4c)
  /home/linuxbrew/.linuxbrew/lib/libjpeg.so.8 (jpeg)
  /home/linuxbrew/.linuxbrew/lib/libpng16.so.16 (libpng)
  /home/linuxbrew/.linuxbrew/lib/libtiff.so.5 (libtiff)
  /home/linuxbrew/.linuxbrew/lib/libmapnik.so.3.0 (mapnik)
  /home/linuxbrew/.linuxbrew/lib/libproj.so.12 (proj)
  /home/linuxbrew/.linuxbrew/lib/libsqlite3.so.0 (sqlite)
  /home/linuxbrew/.linuxbrew/lib/libwebp.so.7 (webp)
==> brew linkage --test mapnik
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libdl.so.2
  /lib/x86_64-linux-gnu/libgcc_s.so.1
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /usr/lib/x86_64-linux-gnu/libpq.so.5
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No broken dylib links
==> FAILED
```

**Comment by maxim-belkin** [comment]
Not sure about the first failure, but the second one implies we need
```
depends_on "postgresql" unless OS.mac?
```

**Comment by maxim-belkin** [comment]
```
Error: mapnik contains conflicting version recursive dependencies:
  berkeley-db@4, berkeley-db
View these with `brew deps --tree mapnik`.
==> FAILED

==> brew audit mapnik --online
Error: 1 problem in 1 formula
mapnik:
  * Formula has other versions so create an alias:
      cd /home/linuxbrew/.linuxbrew/Library/Taps/homebrew/homebrew-core/Aliases
      ln -s ../Formula/mapnik.rb mapnik@3
```

**Comment by maxim-belkin** [comment]
`postgresql` depends on `perl` which depends on `berkeley-db` which conflicts with `berkeley-db@4` which is a dependency of mapnik

**Comment by maxim-belkin** [comment]
so, we can't use `postgresql` as a dependency of `mapnik` to provide `libpq.so`. Perhaps, we should use `postgresql` resource within `mapnik` to build just that `libpq.so`

**Comment by sjackman** [comment]
Try removing the package `libpq-dev` in `circle.yml` and `.travis.yml`.

**Comment by maxim-belkin** [comment]
ok, will try that. will have to rebase on top of the latest update because upstream added mapnik@3 alias

**Pull request closed without merging**
