### PR TITLE
avoid gmp failed on 32bit linux

### PR DESCRIPTION
**Pull request by wangpeiwen**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
assembly will failed on 32bit linux

### CODE REVIEW

**Comment by sjackman** [comment]
Please include a `brew gist-logs binutils` for any report of a build failure.
This looks like an upstream bug to me. Please report it upstream to `gmp`.

**Comment by wangpeiwen** [comment]
[here](https://gist.github.com/5b6ea502abc5a390fa23eb9978366947) is my gist-logs
the main reason of failed is CFLAGS was set by brew and ABI was mistaked by gmp's configure
as error message
> configure: error: Oops, mp_limb_t is 32 bits, but the assembler code
> in this configuration expects 64 bits.
> You appear to have set $CFLAGS, perhaps you also need to tell GMP the
> intended ABI, see "ABI and ISA" in the manual.
we just remove CFLAGS, configure will auto detect ABI
and everything is ok

**Comment by sjackman** [comment]
Travis: https://gist.github.com/anonymous/5b6ea502abc5a390fa23eb9978366947#file-01-configure-L262
`configure: error: Oops, mp_limb_t is 32 bits`

There's an upstream discussion on this topic.
See https://gmplib.org/list-archives/gmp-discuss/2011-July/004663.html
and http://lists.linuxfromscratch.org/pipermail/lfs-dev/2008-November/062156.html

Can you try
```ruby
args << "ABI=32" if Hardware::CPU.is_32_bit? && !OS.mac?
```

**Comment by sjackman** [comment]
What sort of machine is this, a VM, tablet or a phone?
https://gist.github.com/anonymous/5b6ea502abc5a390fa23eb9978366947#file-00-config-out-L12
`CPU: octa-core 32-bit sandybridge`

**Comment by sjackman** [comment]
GitHub isn't letting me reopen this pull request. If the above `ABI=32` fix works, can you e-mail upstream and ask them what's going on, and also open a new PR with the fix?

**Comment by sjackman** [comment]
Related `legacy-homebrew` issue: https://github.com/Homebrew/legacy-homebrew/issues/20693

**Pull request closed without merging**
