### PR TITLE
valgrind: test fails: Blocked by glibc #1042

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by rwhogg** [comment]
Test fails per https://github.com/Linuxbrew/homebrew-core/issues/917

**Comment by rwhogg** [comment]
Marking as help wanted as I believe this will be fixed by #1005.

**Comment by maxim-belkin** [comment]
restarted Travis

**Comment by sjackman** [comment]
Blocked by `glibc` #1042
#1042 was merged, but the bottle has not yet been updated.

**Comment by maxim-belkin** [comment]
What is the plan with regard to bottling `glibc`?

**Comment by maxim-belkin** [comment]
I can build linux-pam manually and build-from-source glibc & valgrind

**Comment by sjackman** [comment]
We've never updated `glibc`. We need to check that `brew upgrade glibc` works and doesn't break everything when the previous keg gets unlinked.

**Comment by sjackman** [comment]
Should we consider merging this PR without first updating the glibc bottle?

**Comment by rwhogg** [comment]
Closing this so @maxim-belkin can open a new PR for `valgrind`.

**Pull request closed without merging**
