### PR TITLE
libproxy: Depends on perl for Linuxbrew

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by rwhogg** [comment]
```
CMake Error at bindings/perl/lib/cmake_install.cmake:44 (file):
  file cannot create directory: /usr/local/lib/perl/5.14.2/Net.  Maybe need
  administrative privileges.
```

Sandbox violation :frowning:

**Comment by rwhogg** [comment]
If you `brew install perl`, first, it doesn't give the sandbox violation. However, the formula also just outright disables Python for the same reason Perl blows up here.

This one's going to take some thought.

**Comment by rwhogg** [comment]
Marking as blocked by #797

**Comment by rwhogg** [comment]
Marking as no longer blocked by 797. Onwards to Qt 5 again!

**Comment by rwhogg** [comment]
And now it's blocked by cmake/sphinx-doc. :frowning:

**Comment by sjackman** [comment]
Unblocked by `cmake`

**Comment by rwhogg** [comment]
From https://travis-ci.org/Linuxbrew/homebrew-core/builds/165977150#L1722-L1724

```
CMake Error at bindings/perl/lib/cmake_install.cmake:44 (file):
  file cannot create directory: /usr/local/lib/perl/5.14.2/Net.  Maybe need
  administrative privileges.
```

**Pull request closed without merging**
