### PR TITLE
mysql: exceeding memory limit while building a bottle on CircleCI

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
Error: Failure while executing: /usr/bin/curl -fLA Linuxbrew/0.9.9\ (Linux;\ x86_64\ Ubuntu\ 14.04.4\ LTS)\ curl/7.35.0 --silent --fail -T mysql-5.7.12.x86_64_linux.bottle.tar.gz https://api.bintray.com/content/linuxbrew/bottles/mysql/5.7.12/mysql-5.7.12.x86_64_linux.bottle.tar.gz?override=1
```
Failure while uploading to Bintray. No useful error message, but perhaps the bottle is too large.

**Comment by sjackman** [comment]
On Travis: `The job exceeded the maximum time limit for jobs, and has been terminated.`

**Comment by maxim-belkin** [comment]
@sjackman: I restarted this build and now it gives an error that seems to be fixable.

Strange thing:
```
==> brew uninstall --force bzip2 cmake curl libidn makedepend perl pkg-config sphinx-doc
Uninstalling bzip2... (29 files, 1.5M)
Uninstalling cmake... (2,027 files, 23.8M)
Uninstalling curl... (366 files, 2.8M)
Uninstalling libidn... (93 files, 1.7M)
==> PASSED
```

**Comment by sjackman** [comment]
Blocked by `cmake` https://github.com/Linuxbrew/homebrew-core/pull/889 and  `sphinx-doc` #1026

**Comment by sjackman** [comment]
Unblocked by `cmake`

**Comment by sjackman** [comment]
Circle: `Your build has exceeded the memory limit of 4G on 1 container.`

**Comment by sjackman** [comment]
6 threads used too much memory, and so did 5 threads. Trying 4 threads.

**Comment by sjackman** [comment]
4 threads failed: 1255440 + 1121304 + 835012 + 745440 = 3957196 MB RAM

**Comment by sjackman** [comment]
3 threads succeeded!

**Pull request closed without merging**
