### PR TITLE
hidapi: depend on systemd

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
> ==> make install
.
Error: No such file or directory - hidtest/.libs/hidtest

**Comment by iMichka** [comment]
That is due to this line:
> bin.install "hidtest/.libs/hidtest"

Maybe it needs to be an absolute path / prefixed?

**Comment by iMichka** [comment]
@sjackman I replaced `bin.install "hidtest/.libs/hidtest"` with `bin.install Dir["hidtest/.libs/hidtest"]` and this should work now. What is the difference here. My ruby foo is not good enough :) I guess the fix could pushed to upstream too?

**Comment by iMichka** [comment]
> hidapi:
 > * Dir["hidtest/.libs/hidtest"] is unnecessary; just use "hidtest/.libs/hidtest"

That's what the audit tells me. But if I do that, it does not work and throws:
> Error: No such file or directory - hidtest/.libs/hidtest

**Comment by sjackman** [comment]
`Dir["hidtest/.libs/hidtest"]` is equivalent to `[]` if `hidtest/.libs/hidtest` does not exist. I suspect that file does not exist.

**Comment by iMichka** [comment]
```
/usr/bin/gcc-4.8
-o
test
test.c
-I/home/linuxbrew/.linuxbrew/Cellar/hidapi/0.8.0-rc1/include/hidapi
-L/home/linuxbrew/.linuxbrew/Cellar/hidapi/0.8.0-rc1/lib
-lhidapi
-Os
-w
-pipe
-march=native

/usr/bin/ld: cannot find -lhidapi
```

**Comment by iMichka** [comment]
```
linuxbrew@f6f26030ab63:~$ ls -l /home/linuxbrew/.linuxbrew/Cellar/hidapi/0.8.0-rc1/lib/ 
total 260
-r--r--r-- 1 linuxbrew linuxbrew 53946 Sep  2 15:41 libhidapi-hidraw.a
lrwxrwxrwx 1 linuxbrew linuxbrew    25 Sep  2 15:41 libhidapi-hidraw.so -> libhidapi-hidraw.so.0.0.0
lrwxrwxrwx 1 linuxbrew linuxbrew    25 Sep  2 15:41 libhidapi-hidraw.so.0 -> libhidapi-hidraw.so.0.0.0
-r-xr-xr-x 1 linuxbrew linuxbrew 45008 Sep  2 15:41 libhidapi-hidraw.so.0.0.0
-r--r--r-- 1 linuxbrew linuxbrew 84278 Sep  2 15:41 libhidapi-libusb.a
lrwxrwxrwx 1 linuxbrew linuxbrew    25 Sep  2 15:41 libhidapi-libusb.so -> libhidapi-libusb.so.0.0.0
lrwxrwxrwx 1 linuxbrew linuxbrew    25 Sep  2 15:41 libhidapi-libusb.so.0 -> libhidapi-libusb.so.0.0.0
-r-xr-xr-x 1 linuxbrew linuxbrew 70096 Sep  2 15:41 libhidapi-libusb.so.0.0.0
drwxr-xr-x 2 linuxbrew linuxbrew  4096 Sep  2 15:41 pkgconfig
```

That's ... not funny. The names of the libs are different on Linux. `-lhidapi-hidraw` should do it.

**Pull request closed without merging**
