### PR TITLE
automake: Set environment variable PERL

### PR DESCRIPTION
**Pull request by Char-Aznable**
This sets the shebang line of the installed script to brewed perl

### CODE REVIEW

**Comment by sjackman** [comment]
Please report the error message that you experience `brew gist-logs automake` without this PR applied.

**Comment by Char-Aznable** [comment]
It was some other tool using automake during installation that gives the error:
```
Can't load '/home/aznb/perl5/lib/perl5/x86_64-linux-thread-multi/auto/threads/threads.so' for module threads: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/aznb/perl5/lib/perl5/x86_64-linux-thread-multi/auto/threads/threads.so) at /usr/lib64/perl5/XSLoader.pm line 70.
 at /home/aznb/perl5/lib/perl5/x86_64-linux-thread-multi/threads.pm line 32
Compilation failed in require at /home/linuxbrew/.linuxbrew/bin/automake line 52.
BEGIN failed--compilation aborted at /home/linuxbrew/.linuxbrew/bin/automake line 57
``` 
I can't go back now to provide the gist-logs for the tool which gives this error

**Comment by sjackman** [comment]
Commented at https://github.com/Linuxbrew/homebrew-core/pull/6518#issuecomment-372434551

**Comment by iMichka** [comment]
Will need to be rebased. I pushed a fix for a different problem with auomake right now.

**Comment by Char-Aznable** [comment]
Is there plan to incorporate this or should I ditch it? @iMichka

**Comment by sjackman** [comment]
I'm disinclined to set a hard dependency of `autoconf` on `perl`, since most systems have `/usr/bin/perl` available. I'd prefer to sort out why your `/usr/bin/perl` isn't working with the brewed `automake`. Thanks all the same, Char.

**Pull request closed without merging**
