### PR TITLE
libsndfile: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by sjackman** [comment]
Looks like you'll have to remove the `libjack` library in `circle.yml` as you had done before. Add that commit to this PR, and see if it resolves the issue.

**Comment by maxim-belkin** [comment]
circle only? I can try remove `libjack0`, `libjack-jackd2-0` or both. any preference?

**Comment by sjackman** [comment]
Do both Circle and Travis, to keep them in sync. Try removing only `libjack0`first. If that doesn't work, try both.

**Comment by maxim-belkin** [comment]
still `checking existing, conflicting JACK installs... yes`

**Comment by maxim-belkin** [comment]
For future reference: it is necessary to remote `libjack-jack2-0` in order to avoid
```
checking existing, conflicting JACK installs... yes
```

**Pull request closed without merging**
