### PR TITLE
Merge 2017-04-21/22

### PR DESCRIPTION
**Pull request by maxim-belkin**
**Conflicts:**
- [ ] awscli
- [ ] bind
- [ ] crystal-lang
- [ ] git-lfs
- [ ] libsoup
- [ ] unzip
- [ ] **boost**
- [ ] emacs
- [ ] osh
- [ ] vim

### CODE REVIEW

**Comment by maxim-belkin** [comment]
```
==> brew linkage --test libprelude
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libgcc_s.so.1
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6
Missing libraries:
  libpython3.6m.so.1.0
```

**Comment by maxim-belkin** [comment]
```
$ brew linkage libprelude
Homebrew libraries:
  /data/server4/mbelkin/.linuxbrew/lib/libgcc_s.so.1 (gcc)
  /data/server4/mbelkin/.linuxbrew/lib/libstdc++.so.6 (gcc)
  /data/server4/mbelkin/.linuxbrew/lib/libc.so.6 (glibc)
  /data/server4/mbelkin/.linuxbrew/lib/libdl.so.2 (glibc)
  /data/server4/mbelkin/.linuxbrew/lib/libm.so.6 (glibc)
  /data/server4/mbelkin/.linuxbrew/lib/libpthread.so.0 (glibc)
  /data/server4/mbelkin/.linuxbrew/lib/libgnutls.so.30 (gnutls)
  /data/server4/mbelkin/.linuxbrew/lib/libgcrypt.so.20 (libgcrypt)
  /data/server4/mbelkin/.linuxbrew/lib/libgpg-error.so.0 (libgpg-error)
  /data/server4/mbelkin/.linuxbrew/lib/libprelude.so.23 (libprelude)
  /data/server4/mbelkin/.linuxbrew/lib/libpreludecpp.so.8 (libprelude)
  /data/server4/mbelkin/.linuxbrew/lib/libltdl.so.7 (libtool)
  /data/server4/mbelkin/.linuxbrew/lib/libpython3.6m.so.1.0 (python3)
Possible undeclared dependencies:
  libgpg-error
  libtool
  python3
```

**Comment by maxim-belkin** [comment]
```
=> brew install --build-bottle --verbose docker-machine-driver-xhyve
[snip]
make
build

make: xcrun: Command not found
make: xcrun: Command not found
```

**Comment by maxim-belkin** [comment]
`docker-machine-driver-xhyve` has `depends_on :macos => :yosemite`

**Comment by ilovezfs** [comment]
Let's try to get https://github.com/Homebrew/homebrew-core/pull/12740 in as well for the sake of fixing https://github.com/Homebrew/homebrew-core/issues/12662.

**Comment by maxim-belkin** [comment]
> Let's try to get https://github.com/Homebrew/homebrew-core/pull/12740 in as well for the sake of fixing https://github.com/Homebrew/homebrew-core/issues/12662.

ok

**Comment by ilovezfs** [comment]
thanks!

**Comment by maxim-belkin** [comment]
```
=> Verifying nnn-1.0.tar.gz checksum
==> brew install --build-bottle --verbose nnn
==> Downloading https://github.com/jarun/nnn/archive/v1.0.tar.gz
Already downloaded: /home/ubuntu/.cache/Homebrew/nnn-1.0.tar.gz
==> Verifying nnn-1.0.tar.gz checksum
tar xzf /home/ubuntu/.cache/Homebrew/nnn-1.0.tar.gz
==> make install PREFIX=/home/linuxbrew/.linuxbrew/Cellar/nnn/1.0
.
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/nnn/01.make:
2017-04-21 19:36:15 +0000

make
install
PREFIX=/home/linuxbrew/.linuxbrew/Cellar/nnn/1.0

cp config.def.h config.h
gcc-4.8 -O3 -march=native -Wall -Wextra -Wno-unused-parameter  -o nnn nnn.c  -lcurses
nnn.c:8:20: fatal error: curses.h: No such file or directory
 #include <curses.h>
                    ^
compilation terminated.
make: *** [nnn] Error 1
```
I don't see where `nnn` is located so merging for now with the goal to figure this out later :)

**Comment by ilovezfs** [comment]
Maybe `depends_on "ncurses" unless OS.mac?`?

**Comment by ilovezfs** [comment]
It's a new formula: https://github.com/Homebrew/homebrew-core/pull/12446

**Comment by maxim-belkin** [comment]
of course... I was preparing to pull in the merge commit I did `reset --hard origin/master` so I didn't see it.

**Comment by maxim-belkin** [comment]
```
../configure
--prefix=/home/linuxbrew/.linuxbrew/Cellar/wine/2.0.1
CPPFLAGS=-I/home/linuxbrew/.linuxbrew/Cellar/wine/2.0.1/libexec/include
LDFLAGS=-L/home/linuxbrew/.linuxbrew/Cellar/wine/2.0.1/libexec/lib

checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking whether make sets $(MAKE)... yes
checking for gcc... gcc-4.8
checking whether the C compiler works... no
configure: error: in `/tmp/wine-20170422-119321-jeabni/wine-2.0.1/wine-32-build':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

**Pull request closed without merging**
