### PR TITLE
libosmium: Depend on expat for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
> brew cleanup --prune=7
Too long with no output (exceeded 10m0s)

Interesting. I'm rebuilding again to see if that was transient.

**Comment by iMichka** [comment]
Different errors now:

```
note: #pragma message: Disabling regex functionality. See source code for info.
 #  pragma message("Disabling regex functionality. See source code for info.")                                                                         ^
g++-4.8: internal compiler error: Killed (program cc1plus)

/tmp/libosmium-20170818-6313-oze8d2/libosmium-2.13.0/examples/osmium_filter_discussions.cpp:91:1: fatal error: error writing to /tmp/ccoR8ETC.s: Cannot allocate memory
 }
 ^
compilation terminated.
```

Rebuilding again without cache

**Comment by iMichka** [comment]
I think the most interesting part is:
```
fatal error: error writing to /tmp/ccgsavvj.s: Cannot allocate memory
 #    pragma GCC diagnostic pop
```

Let's try to reduce the memory usage.

**Comment by iMichka** [comment]
```
/tmp/ccQv18Z9.o: In function `osmium::io::detail::XMLParser::ExpatXMLParser<osmium::io::detail::XMLParser>::ExpatXMLParser(osmium::io::detail::XMLParser*)':
test.cpp:(.text._ZN6osmium2io6detail9XMLParser14ExpatXMLParserIS2_EC2EPS2_[_ZN6osmium2io6detail9XMLParser14ExpatXMLParserIS2_EC5EPS2_]+0x19): undefined reference to `XML_ParserCreate'
test.cpp:(.text._ZN6osmium2io6detail9XMLParser14ExpatXMLParserIS2_EC2EPS2_[_ZN6osmium2io6detail9XMLParser14ExpatXMLParserIS2_EC5EPS2_]+0x6e): undefined reference to `XML_SetUserData'
test.cpp:(.text._ZN6osmium2io6detail9XMLParser14ExpatXMLParserIS2_EC2EPS2_[_ZN6osmium2io6detail9XMLParser14ExpatXMLParserIS2_EC5EPS2_]+0x87): undefined reference to `XML_SetElementHandler'
test.cpp:(.text._ZN6osmium2io6detail9XMLParser14ExpatXMLParserIS2_EC2EPS2_[_ZN6osmium2io6detail9XMLParser14ExpatXMLParserIS2_EC5EPS2_]+0x9b): undefined reference to `XML_SetCharacterDataHandler'
test.cpp:(.text._ZN6osmium2io6detail9XMLParser14ExpatXMLParserIS2_EC2EPS2_[_ZN6osmium2io6detail9XMLParser14ExpatXMLParserIS2_EC5EPS2_]+0xaf): undefined reference to `XML_SetEntityDeclHandler'
/tmp/ccQv18Z9.o: In function `osmium::io::detail::XMLParser::ExpatXMLParser<osmium::io::detail::XMLParser>::~ExpatXMLParser()':
test.cpp:(.text._ZN6osmium2io6detail9XMLParser14ExpatXMLParserIS2_ED2Ev[_ZN6osmium2io6detail9XMLParser14ExpatXMLParserIS2_ED5Ev]+0x17): undefined reference to `XML_ParserFree'
/tmp/ccQv18Z9.o: In function `osmium::io::detail::XMLParser::ExpatXMLParser<osmium::io::detail::XMLParser>::operator()(std::string const&, bool)':
test.cpp:(.text._ZN6osmium2io6detail9XMLParser14ExpatXMLParserIS2_EclERKSsb[_ZN6osmium2io6detail9XMLParser14ExpatXMLParserIS2_EclERKSsb]+0x52): undefined reference to `XML_Parse'
```

Almost good. Test is failing now.

**Comment by sjackman** [comment]
Change
```diff
-    system ENV.cxx, "-std=c++11", "-stdlib=libc++", "-lexpat", "-o", "libosmium_read", "test.cpp"
+    system ENV.cxx, "-std=c++11", *("-stdlib=libc++" if OS.mac?), "-o", "libosmium_read", "test.cpp", "-lexpat"
```

**Comment by iMichka** [comment]
Thanks that worked !

**Pull request closed without merging**
