### PR TITLE
Compile glibc with -O2

### LINKED ISSUE #1005: glibc: Compiling with -Os breaks valgrind
When I run valgrind I see the following error.
```
==11869== Memcheck, a memory error detector
==11869== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==11869== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==11869== Command: ./read
==11869== 
 
valgrind:  Fatal error at startup: a function redirection
valgrind:  which is mandatory for this platform-tool combination
valgrind:  cannot be set up.  Details of the redirection are:
valgrind:  
valgrind:  A must-be-redirected function
valgrind:  whose name matches the pattern:      strlen
valgrind:  in an object with soname matching:   ld-linux-x86-64.so.2
valgrind:  was not found whilst processing
valgrind:  symbols from the object with soname: ld-linux-x86-64.so.2
valgrind:  
valgrind:  Possible fixes: (1, short term): install glibc's debuginfo
valgrind:  package on this machine.  (2, longer term): ask the packagers
valgrind:  for your Linux distribution to please in future ship a non-
valgrind:  stripped ld.so (or whatever the dynamic linker .so is called)
valgrind:  that exports the above-named function using the standard
valgrind:  calling conventions for this platform.  The package you need
valgrind:  to install for fix (1) is called
valgrind:  
valgrind:    On Debian, Ubuntu:                 libc6-dbg
valgrind:    On SuSE, openSuSE, Fedora, RHEL:   glibc-debuginfo
valgrind:  
valgrind:  Cannot continue -- exiting now.  Sorry.
```

I believe this is because binutils is built w/ --disable-debug.

Is there any reason --disable-debug is used in the default binutils formula? Can we make it an optional flag? Otherwise is there a way to require optional flags for dependencies?

### PR DESCRIPTION
**Pull request by carlorosati**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

-----

Closes #1005

### CODE REVIEW

**Comment by carlorosati** [comment]
This is a fix for issue #1005

**Comment by carlorosati** [comment]
Why is the circleci details page 404ing?

**Comment by sjackman** [comment]
> Why is the circleci details page 404ing?

We're unfortunately not able to expose the Circle results to the public due to credentials (tokens) in the build logs. =/ I wish I could.

**Comment by sjackman** [comment]
The Circle build succeeded except for an error that the bottle wasn't updated because there's already a bottle for `glibc` 2.19.
```
==> brew bottle --merge --write --no-commit ./glibc-2.19.x86_64_linux.bottle.json --keep-old
Error: --keep-old was passed but there are changes in:
sha256 => x86_64_linux
==> glibc
==> FAILED
```

**Comment by sjackman** [comment]
Merged without updating the bottle. Thanks for your contribution, @carlorosati!

**Pull request closed without merging**
