### PR TITLE
gdb: Build a bottle for Linuxbrew: Depends on python

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
1.00s==> brew test gdb --verbose
Testing gdb
==> /home/linuxbrew/.linuxbrew/Cellar/gdb/7.12.1/bin/gdb /home/linuxbrew/.linuxbrew/Cellar/gdb/7.12.1/bin/gdb -configuration
.
Last 150 lines from /home/linuxbrew/.cache/Homebrew/Logs/gdb/test.01.gdb:
2017-01-30 21:50:43 +0000
/home/linuxbrew/.linuxbrew/Cellar/gdb/7.12.1/bin/gdb
/home/linuxbrew/.linuxbrew/Cellar/gdb/7.12.1/bin/gdb
-configuration
/home/linuxbrew/.linuxbrew/Cellar/gdb/7.12.1/bin/gdb: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
Error: gdb: failed
Failed executing: /home/linuxbrew/.linuxbrew/Cellar/gdb/7.12.1/bin/gdb /home/linuxbrew/.linuxbrew/Cellar/gdb/7.12.1/bin/gdb -configuration
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/196723697#L2183

**Comment by maxim-belkin** [comment]
rebased

**Comment by maxim-belkin** [comment]
```
==> brew linkage --test gdb
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libdl.so.2
  /lib/x86_64-linux-gnu/libexpat.so.1
  /lib/x86_64-linux-gnu/liblzma.so.5
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /lib64/ld-linux-x86-64.so.2
  /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
No broken dylib links
==> FAILED
```

@sjackman, @rwhogg: how about
```
depends_on "python" unless OS.mac?
```

**Comment by sjackman** [comment]
```
  /lib/x86_64-linux-gnu/libexpat.so.1
  /lib/x86_64-linux-gnu/liblzma.so.5
  /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
```

> `depends_on "python" unless OS.mac?`

:+1: and looks like it may also need `expat` and `xz`.

**Comment by sjackman** [comment]
:shipit: Thanks, Maxim!

**Pull request closed without merging**
