### PR TITLE
octave: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
> configure: error: A BLAS library was detected but found incompatible with your Fortran 77 compiler settings.

**Comment by iMichka** [comment]
@dpo Any idea what the problem could be?

**Comment by dpo** [comment]
Better ask @schoeps

**Comment by iMichka** [comment]
Superseded by #5564

**Comment by iMichka** [comment]
The good news is that it built correctly in #5564. Maybe the removal of the :fortran requirement helped :)

**Comment by schoeps** [comment]
Glad that it worked. It's a maybe not 100% clean as Octave contains some Fortran code.

**Pull request closed without merging**
