### PR TITLE
gdb: fix add --without-python parameter on linux platform as needed

### PR DESCRIPTION
**Pull request by lday0321**
add --without-python parameter on linux platform as needed

### CODE REVIEW

**Comment by sjackman** [comment]
Circle failed with…
```
checking whether to use python... /home/linuxbrew/.linuxbrew
checking for python2.7... no
checking for python2.6... no
checking for python2.5... no
checking for python2.4... no
configure: error: no usable python found at /home/linuxbrew/.linuxbrew
```
https://circleci.com/gh/Linuxbrew/homebrew-core/10424

**Comment by sjackman** [comment]
@iMichka I'm good with this patch as is. It fixes bug the @lday0321 and I troubleshot in https://github.com/Linuxbrew/brew/issues/518

@lday0321 If you have the time and inclination, it'd be great to get this PR succeeding on CircleCI and build a binary bottle for Linux. I'm not sure what's wrong with it though. The first thing that comes to mind is perhaps
```ruby
args << "--with-python=#{HOMEBREW_PREFIX}"
```
should be
```ruby
args << "--with-python=#{Formula["python"].prefix}"
```
but somehow I don't think that's causing the build failure.

**Comment by iMichka** [comment]
I merged this as-is. Building a bottle is a different topic. I have not much time but a PR from @lday0321  or somebody else for that would be welcome.

**Comment by iMichka** [comment]
BTW thanks for your contribution! :)

**Comment by lday0321** [comment]
@sjackman I'm just a novice using linuxbrew and I'm not quite sure how to build bottle, maybe someone others can help.

**Comment by sjackman** [comment]
Submit a PR to fix the `--with-python=…` issue, and our CI system will automatically build a bottle. Welcome to Linuxbrew, and thanks for your contribution!

**Pull request closed without merging**
