### PR TITLE
pango: Package 'xcb-shm', required by 'cairo', not found

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
Error: cairo 1.14.6 did not build
```
Blocked by #45

**Comment by sjackman** [comment]
```
Package xcb-shm was not found in the pkg-config search path.
Perhaps you should add the directory containing `xcb-shm.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xcb-shm', required by 'cairo', not found
/tmp/pango-20160605-87167-tp3vfg/pango-1.38.1/pango/tmp-introspectzAQytx/Pango-1.0.c:2:18: fatal error: glib.h: No such file or directory
 #include <glib.h>
                  ^
compilation terminated.
Caught exception: <class 'distutils.errors.CompileError'> CompileError(DistutilsExecError("command '/usr/bin/gcc-4.8' failed with exit status 1",),)
> /home/linuxbrew/.linuxbrew/Cellar/python/2.7.11/lib/python2.7/distutils/unixccompiler.py(124)_compile()
-> raise CompileError, msg
(Pdb) 
make[4]: *** [Pango-1.0.gir] Error 1
make[4]: Leaving directory `/tmp/pango-20160605-87167-tp3vfg/pango-1.38.1/pango'
```

**Comment by sjackman** [comment]
> `Package 'xcb-shm', required by 'cairo', not found`

Should be provided by `xorg`, which is a dependency of `cairo`.

> `error: glib.h: No such file or directory`

`glib` is already a dependency of `pango.`

**Comment by sjackman** [comment]
@rwhogg Care to look into the above errors?

**Comment by rwhogg** [comment]
`configure: WARNING: unrecognized options: --enable-man`

Should probably fix that upstream.

**Comment by rwhogg** [comment]
```
==> Installing dependencies for pango: patchelf, pkg-config, homebrew/dupes/ncurses, readline, sqlite, gdbm, zlib, openssl, bzip2, gpatch, python, xz, libxml2, gettext, libffi, glib, libpng, freetype, expat, fontconfig, pixman, cairo, homebrew/dupes/m4, bison, flex, gobject-introspection, icu4c, harfbuzz
```

Weird that `linuxbrew/xorg/xorg` isn't on that list, but it is on the list of `brew deps`.

---------

Worth noting that the behaviour of `brew deps` varies depending on what is tapped. Starting from scratch on the `linuxbrew/linuxbrew` Docker image:

```bash
$ brew deps pango
Error: No available formula with the name "homebrew/dupes/ncurses" 
Please tap it and then try again: brew tap homebrew/dupes
$ brew tap homebrew/dupes
...
$ brew deps pango
bison
bzip2
cairo
expat
flex
fontconfig
freetype
gdbm
gettext
glib
gobject-introspection
harfbuzz
homebrew/dupes/m4
homebrew/dupes/ncurses
icu4c
libffi
libpng
libxml2
linuxbrew/xorg/xorg
openssl
pixman
pkg-config
python
readline
sqlite
zlib
```

Odd that I had to tap `dupes` but not `xorg`.

**Comment by rwhogg** [comment]
Installing `cairo` manually triggers the X11 dependency, but installing it as a dependency of `pango` does not. If you install `cairo` manually, it doesn't freeze with the problem described above.

The weird thing is that it correctly recognizes in both cases that X.Org is not installed.

We could probably work around this by forcing the `with-x11` option on Cairo, and given that it's complaining about `xcb-shm`, that might be the right thing to do. But this might hint at a bigger dependency-management bug, so I think this deserves more investigation first.

**Comment by sjackman** [comment]
Cairo does already force `--with-x11` on Linux. Very strange. See https://github.com/Linuxbrew/linuxbrew/pull/986
```ruby
  depends_on :x11 => OS.mac? ? :optional : :recommended if MacOS.version > :leopard || !OS.mac?
```
https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/cairo.rb#L26

**Comment by rwhogg** [comment]
It doesn't have anything to do with X11 per se. It has to do with the fact that `cairo` has a `:recommended` dependency on a requirement. If you make `cairo` depend on `:x11` absolutely, it gets installed as a dependency when installing `pango`. Likewise if you make it depend on "linuxbrew/xorg/xorg => :recommended" instead of indirectly going through the `:x11

Depending on `:java => :recommended` will have the same problem.

**Comment by sjackman** [comment]
Yes, I suspect it's a bug in the dependency resolver as well. As a hack in the mean time, we could change the recommended dependency to a required dependency by changing `:recommended` to `[]`.

**Comment by sjackman** [comment]
@xu-cheng Depending on a recommended requirement `depends_on :x11 => :recommended` when the `default_formula` is a cross-tap dependency like `linuxbrew/xorg/xorg` isn't working as expected. The `default_formula` is not installed.

**Comment by rwhogg** [comment]
> Is there a use case to use cairo without :x11 on Linux? Perhaps for non-interactive rendering using cairo?

Arguably, yes. `gnuplot` uses `cairo` to generate PDF's and PNG's (see http://www.gnuplot.info/announce.4.4.0). GNU R can use it as well.

Neither of these are high-priority use cases for me personally, but I could very plausibly see some sort of college printing house using this in a publishing pipeline.

> Depending on a recommended requirement depends_on :x11 => :recommended when the default_formula is a cross-tap dependency like linuxbrew/xorg/xorg isn't working as expected.

I'm not certain, but I don't think the fact that it's cross-tap matters in this case. `jdk` is part of `homebrew-core` on Linux yet `depends_on :java => :recommended` has the same problem that X11 does.

**Comment by sjackman** [comment]
> `jdk` is part of homebrew-core on Linux yet `depends_on :java => :recommended` has the same problem that X11 does.

Has this `:java` issue come up? `lcm` and `upscaledb` are the only two formula in `homebrew/core` that `depends_on :java => :recommended`.

**Comment by rwhogg** [comment]
> Has this :java issue come up? lcm and upscaledb are the only two formula in homebrew/core that depends_on :java => :recommended.

It hasn't come up. All I meant was that the problem is not unique to cross-tap default formulae. (I tested by changing the X11 dependency in `cairo` to a Java dependency). Since nothing depends on either `lcm` or `upscaledb`, this situation will never come up in the real world unless someone creates a formula that depends on one of those.

> Does it affect Mac OS?

I no longer have access to a Mac, unfortunately. I'd guess that the bug does exist there, but because of the nature of how XQuartz is installed versus how X.Org is installed, it's probably latent as far as upstream is concerned.

**Comment by sjackman** [comment]
```
Package xcb-shm was not found in the pkg-config search path.
Perhaps you should add the directory containing `xcb-shm.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xcb-shm', required by 'cairo', not found
/tmp/pango-20160725-78208-jc8c36/pango-1.40.1/pango/tmp-introspect8CXlJC/Pango-1.0.c:2:18: fatal error: glib.h: No such file or directory
```

**Comment by rwhogg** [comment]
Closing in favour of #665

**Pull request closed without merging**
