### PR TITLE
ibex: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
> /usr/bin/env: ‘python’: No such file or directory

**Comment by iMichka** [comment]
Same issue as for #10374

**Comment by iMichka** [comment]
> g++-5: internal compiler error: Killed (program cc1plus)

**Comment by sjackman** [comment]
I've opened PR https://github.com/Homebrew/brew/pull/5403 to address
```
An exception occurred within a child process:
  NoMethodError: undefined method `non_apple_gcc_version' for #<Object:0x0000000001ac1100>
/projects/btl_scratch/sjackman/brew/Homebrew/Library/Homebrew/extend/ENV/shared.rb:323:in `compiler_with_cxx11_support?'
```

**Comment by iMichka** [comment]
```
==> ./lab1
.
Last 150 lines from /home/linuxbrew/Library/Logs/Homebrew/ibex/test.02.lab1:
2018-12-13 19:59:10 +0000

./lab1

./lab1: error while loading shared libraries: libibex.so: cannot open shared object file: No such file or directory
```

**Comment by sjackman** [comment]
`./lab1: error while loading shared libraries: libibex.so: cannot open shared object file: No such file or directory`

Three ways to solve this problem…

1. Set LD_RUN_PATH during `brew test`
2. Set LD_LIBRARY_PATH during `brew test`
3. Modify the formula

That's my order of preference. What's your thoughts?

**Comment by sjackman** [comment]
This issue only arises when using the host compiler. When using the brewed `gcc` we patch the `specs` file to add `HOMEBREW_PREFIX/lib` to the `RPATH`.

**Pull request closed without merging**
