### PR TITLE
watchman: unable to execute '/usr/bin/gcc-4.8': No such file or directory

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
/usr/bin/gcc-4.8 -pthread -shared -L/home/linuxbrew/.linuxbrew/lib -Wl,--dynamic-linker=/home/linuxbrew/.linuxbrew/lib/ld.so -Wl,-rpath,/home/linuxbrew/.linuxbrew/lib -L/home/linuxbrew/.linuxbrew/lib -Wl,--dynamic-linker=/home/linuxbrew/.linuxbrew/lib/ld.so -Wl,-rpath,/home/linuxbrew/.linuxbrew/lib -Os -w -pipe -march=core2 -isystem/home/linuxbrew/.linuxbrew/include build/temp.linux-x86_64-2.7/pywatchman/bser.o -L/home/linuxbrew/.linuxbrew/lib -L/home/linuxbrew/.linuxbrew/opt/openssl/lib -L/home/linuxbrew/.linuxbrew/opt/sqlite/lib -L/home/linuxbrew/.linuxbrew/Cellar/python/2.7.11/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/pywatchman/bser.so
unable to execute '/usr/bin/gcc-4.8': No such file or directory
error: command '/usr/bin/gcc-4.8' failed with exit status 1
```
Ergh. Apparently the compiler path is hard coded somewhere in the `python` bottle.

**Comment by rwhogg** [comment]
> Ergh. Apparently the compiler path is hard coded somewhere in the python bottle.

Yes it is. This is the same problem affecting #159 and #172

**Comment by sjackman** [comment]
Blocked by #314

**Comment by rwhogg** [comment]
Superseded by #833

**Pull request closed without merging**
