### PR TITLE
gtk+3: Depends on egl for Linuxbrew: Blocked by egl

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
checking for EGL... no
configure: error: Package requirements (egl) were not met:
No package 'egl' found
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/147487182#L5170

**Comment by sjackman** [comment]
Depends on `egl` for Linuxbrew.
Blocked by `egl`

**Comment by maxim-belkin** [comment]
We need to add `depends_on "mesa"` to `libepoxy`.

**Comment by sjackman** [comment]
Is the `linuxbrew/xorg/mesa` formula working!?

**Comment by maxim-belkin** [comment]
superseded by #1444

**Pull request closed without merging**
