### PR TITLE
fontconfig: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by rwhogg** [comment]
That's weird. From Circle

```
==> brew test --verbose epstool
Testing epstool
Error: epstool: failed
epstool cannot be built with any available compilers.
Install Clang or brew install gcc
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/compilers.rb:127:in `compiler'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/compilers.rb:109:in `select_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/ENV/shared.rb:176:in `compiler'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/ENV/std.rb:73:in `setup_build_environment'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:20:in `<main>'
==> FAILED
```

**Comment by rwhogg** [comment]
```
==> Fetching kat from homebrew/science
==> Downloading https://linuxbrew.bintray.com/bottles-science/kat-2.3.4.x86_64_linux.bottle.tar.gz
/home/linuxbrew/.linuxbrew/opt/curl/bin/curl --remote-time --location --user-agent Linuxbrew/1.2.0-94-g2e121544f (Linux; x86_64 Ubuntu 14.04.4 LTS) curl/7.54.0 --fail --silent https://linuxbrew.bintray.com/bottles-science/kat-2.3.4.x86_64_linux.bottle.tar.gz -C 0 -o /home/ubuntu/.cache/Homebrew/kat-2.3.4.x86_64_linux.bottle.tar.gz.incomplete
Downloaded to: /home/ubuntu/.cache/Homebrew/kat-2.3.4.x86_64_linux.bottle.tar.gz
SHA256: 50f16a555329882595778c5a54efbd2c8ce65f3d6f57498a25785c6c466975e4
==> Verifying kat-2.3.4.x86_64_linux.bottle.tar.gz checksum
==> brew install kat
==> Installing kat from homebrew/science
kat: Unsatisfied dependency: matplotlib
Homebrew does not provide special Python dependencies; install with:
  `pip install matplotlib`
kat: Unsatisfied dependency: numpy
Homebrew does not provide special Python dependencies; install with:
  `pip install numpy`
kat: Unsatisfied dependency: scipy
Homebrew does not provide special Python dependencies; install with:
  `pip install scipy`
Error: Unsatisfied requirements failed this build.
==> FAILED
```

Should `kat` be updated to use the `scipy`, `numpy`, and `matplotlib` formulae?

**Comment by rwhogg** [comment]
Travis timed out, but otherwise passed. Circle found a number of weird failures, but none related to the recent changes.

**Comment by rwhogg** [comment]
Apparently test-bot didn't build a bottle for this one. That's frustrating.

Will rebase and try again.

**Comment by rwhogg** [comment]
Travis timed out but was otherwise successful. Circle was also fine, except that test-bot apparently didn't build a bottle again :(

@maxim-belkin, do you have time to look at this? I'll try to deal with it tomorrow if you don't.

**Comment by maxim-belkin** [comment]
Hmm.. I see LinuxbrewTestBot made a release for this PR: https://github.com/LinuxbrewTestBot/homebrew-core/releases

Let me try pulling it

**Comment by sjackman** [comment]
`epstool cannot be built with any available compilers.`

That is weird. It `fails_with :gcc => "4.8"` which for installing from source should cause it to install the `gcc` formula on CircleCI. It should still pour a bottle and test just fine without `gcc` installed. Requires more troubleshooting.

**Comment by sjackman** [comment]
> Should kat be updated to use the scipy, numpy, and matplotlib formulae?

Yes, I think so.

**Comment by sjackman** [comment]
> Apparently test-bot didn't build a bottle for this one. That's frustrating.

I've reimaged and redeployed `bot.linuxbrew.sh`. Hopefully that helps.

**Pull request closed without merging**
