### PR TITLE
Merge 2018-11-19 17cb513803

### PR DESCRIPTION
**Pull request by iMichka**
+ [ ] tinyxml2

### CODE REVIEW

**Comment by sjackman** [comment]
```
==> /usr/bin/gcc test.cpp -L/home/linuxbrew/.linuxbrew/Cellar/tinyxml2/7.0.1/lib -ltinyxml2 -o test
test.cpp:1:22: fatal error: tinyxml2.h: No such file or directory
```
Looks like the test needs to be modified to add `-I#{include}`

**Comment by iMichka** [comment]
Bottle upload failed:
```
error: cannot create pipe: Too many open files in system
fatal: fetch-pack: unable to fork off sideband demultiplexer
error: cannot create pipe: Too many open files in system
fatal: fetch-pack: unable to fork off sideband demultiplexer
From https://github.com/Linuxbrew/homebrew-core
c7e37d5..e876f75 master -> origin/master
error: Ref refs/remotes/origin/master is at e876f75d5390fcf94ff036808ec5c3dd46f15f64 but expected c7e37d57f0655d422f9a6eb2d225836bca3d7cfa
error: Cannot lock ref 'refs/remotes/origin/master': 
From https://github.com/Linuxbrew/homebrew-core
```

**Comment by iMichka** [comment]
Weird because the GitHub GUI also shows a rebase/conflicts problem, but I think there is none ...

**Comment by iMichka** [comment]
Merged without pulling the bottle.

I will try to fix the test here: #10374
I'll also upload the bottle from that new build.

**Comment by sjackman** [comment]
I don't see this test failure when using the `linuxbrew/linuxbrew` Docker image, so it looks as though this behaviour is new with Homebrew/brew.

**Comment by iMichka** [comment]
OK, I'll hold of fixing any tests like this for the time being. I think this could be fixed in std env for the test env.

**Pull request merged**
