### PR TITLE
libhttpseverywhere: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
checking for XML::Parser... configure: error: XML::Parser perl module is required for intltool

==> Formula
Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libsoup.rb
```

**Comment by iMichka** [comment]
@sjackman I found a solution to build libsoup, without vendoring the xml parser again.

- Add the following line to the install block: ENV.prepend_path "PERL5LIB", "#{Formula["intltool"].libexec}/lib/perl5"
- Bump the revision of `inttool` to 1. you didn't want to do that back then (#1443), but it is necessary so we get a bottle containing the vendored xml::parser (the current bottle doesn't contain it).

Any thoughts? I will then update the 78 formulae using that strategy. I think it makes sense to use the xml::parser vendored by `intltool` at `intltool's runtime.

**Comment by sjackman** [comment]
Nice find! Not every formula that depends on `intltool` should require this fix. This fix should only be required if the tool explicitly checks that the Perl module `XML::Parser` is installed. If the formula uses the `intltool` executables, that should be fine.

**Comment by iMichka** [comment]
```
== /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libhttpseverywhere.rb ==
C: 83:  1: Align the elements of an array literal if they span more than one line.
C: 85:  1: Align the elements of an array literal if they span more than one line.
C: 88:  1: Align the elements of an array literal if they span more than one line.
```

```
-lgobject-2.0
<<<<<<<
HEAD
-lhttpseverywhere-0.4
=======
-lhttpseverywhere-0.6
-lintl
>>>>>>>
432bd996f1
-ljson-glib-1.0
-lsoup-2.4
-lxml2

gcc-5: error: <<<<<<<: No such file or directory
gcc-5: error: HEAD: No such file or directory
gcc-5: error: =======: No such file or directory
gcc-5: error: >>>>>>>: No such file or directory
gcc-5: error: 432bd996f1: No such file or directory
Error: libhttpseverywhere: failed
Failed executing: /usr/bin/gcc-5 test.c -o
```

**Pull request closed without merging**
