### PR TITLE
pulseaudio: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
x86_64-linux-gnu-gcc -c   -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g   -DVERSION=\"2.44\" -DXS_VERSION=\"2.44\" -fPIC "-I/usr/lib/x86_64-linux-gnu/perl/5.22/CORE"   Expat.c
Expat.xs:12:19: fatal error: expat.h: No such file or directory
compilation terminated.
Makefile:320: recipe for target 'Expat.o' failed
make[1]: *** [Expat.o] Error 1
make[1]: Leaving directory '/tmp/pulseaudio--XML::Parser-20170906-8046-wlj7gj/XML-Parser-2.44/Expat'
Makefile:594: recipe for target 'subdirs' failed
make: *** [subdirs] Error 2

==> Formula
Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pulseaudio.rb
```

**Comment by sjackman** [comment]
The compiler executable that it's calling `x86_64-linux-gnu-gcc` is not caught by Superenv/cc. The workaround is…
```ruby
system "make", "PERL5LIB=#{ENV["PERL5LIB"]}", "CC=#{ENV.cc}"
```
See https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/systemd.rb#L46

I've opened PR https://github.com/Linuxbrew/brew/pull/481 to hopefully address the root cause, which adds the symlink `shims/linux/super/x86_64-linux-gnu-gcc`.

**Comment by iMichka** [comment]
@sjackman Thanks! It is weird that I was able to build this on the 1st of August and now it fails, but that may come through brew 1.3.1.

I was already thinking that the includes were filtered out, and wanted to investigate that part. I'll try your workaround, so that we can build a bottle.

**Comment by sjackman** [comment]
If you're able to reproduce this failure locally, could you please test my PR https://github.com/Linuxbrew/brew/pull/481? If it resolves the issue, I'll merge it.

**Comment by iMichka** [comment]
On my ubuntu 17.04 it builds from source nicely without any workaround. Travis was green here too.

The workaround works, but we are hitting another error now.

> Can't locate XML/Parser.pm in @INC (you may need to install the XML::Parser module)

Not sure if this is related to the fact that `PERL5LIB=` is empty.

**Comment by sjackman** [comment]
Looks to me like this line is missing:
```ruby
ENV.prepend_create_path "PERL5LIB", libexec/"lib/perl5
```
e.g. https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/systemd.rb#L40

**Comment by iMichka** [comment]
I knew I had forgotten something. Let's try again.

**Pull request closed without merging**
