### PR TITLE
qt: Depends on X11 for Linuxbrew

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by rwhogg** [comment]
```
Error: No available formula with the name "linuxbrew/xorg/xorg" 
```

Blocked by the same problem we're facing on #340

**Comment by sjackman** [comment]
Does one of the dependencies of `qt` depend on `:x11 => :optional`? Changing the `:x11 => optional` dependency to `:recommended`, which may make sense for Linuxbrew, should resolve this.

**Comment by rwhogg** [comment]
No, none of the dependencies (there's only 2 other than X11 at the moment, `zlib` and `openssl`) have any kind of X11 dependency.

**Comment by sjackman** [comment]
I can't reproduce this tapping issue outside of the LinuxbrewTestBot. You?
```
$ brew install qt
==> Tapping linuxbrew/xorg
Initialized empty Git repository in /home/sjackman/.linuxbrew/Library/Taps/linuxbrew/homebrew-xorg/.git/
remote: Counting objects: 178, done.
remote: Compressing objects: 100% (170/170), done.
remote: Total 178 (delta 132), reused 21 (delta 8), pack-reused 0
Receiving objects: 100% (178/178), 61.02 KiB, done.
Resolving deltas: 100% (132/132), done.
Tapped 168 formulae (198 files, 296.7K)
```
Oddly for me it's freezing right there. Not sure what's up with that.

**Comment by rwhogg** [comment]
No, I've never been able to reproduce this outside the test-bot either.

> Oddly for me it's freezing right there. Not sure what's up with that.
It takes a really long time for me, but I've never seen it freeze. I think it's just that Linuxbrew takes a really long time to recursively process the dependencies for all the tiny X.Org libraries.

**Comment by sjackman** [comment]
Okay, I probably got impatient. Thanks for the info. We can hack around this bug on LinuxbrewTestBot by preemptively tapping `linuxbrew/xorg`.

**Comment by rwhogg** [comment]
Travis timed out and the bottle upload appeared to fail on Circle even though it was created successfully. I think I may have to build and upload this bottle manually.

**Comment by sjackman** [comment]
I believe there is a 200 MB bottle limit currently on Bintray that I can disable. This issue affects a couple other packages as well, like `mysql`. Can you build the bottle locally and report its size? GCC 4.8 produces ridiculously large C++ executables when debugging information is included. Upstream Homebrew used to strip debugging information but changed that a few months ago. I'm wondering whether we should continue stripping executables.

**Comment by sjackman** [comment]
Kind of unrelated, but I have not confirmed the C++ ABI compatibility of GCC 4.8, GCC 5.3 and GCC 6.1. Can bottles compiled with GCC 4.8 be run on older systems like Ubuntu 12 that have GCC 5.3 or GCC 6.1 installed by Linuxbrew? I feel like now, before bottling `qt`, is a good time to answer that question. I'm wondering whether we should be building bottles with GCC 4.8 on Ubuntu 14 or a newer GCC, either provided by the host on Ubuntu 16 (GCC 5.3.1) or installed by Linuxbrew. If C++ bottles compiled by GCC 4.8 can be run with `libstdc++.so.6` provided by GCC 5 and 6, then I'm happy with the status quo.

**Comment by rwhogg** [comment]
Huh, it appears to only be 104.5 MB. Guess it's not hitting the limit after all.

As for the ABI: not sure, will investigate when I can.

**Comment by sjackman** [comment]
Looks like the limit is 250 MB:
> Files can only be uploaded to a version and only by the owner of the package to which the version belongs. Empty files cannot be uploaded to Bintray. File size is limited to 250 MB. Size limitation is not applicable for Professional users if uploading via REST APIs.

https://bintray.com/docs/usermanual/uploads/uploads_manuallyuploadingfilestoaversion.html

**Comment by rwhogg** [comment]
From https://gcc.gnu.org/onlinedocs/gcc/Compatibility.html:

> Starting with GCC 3.2, GCC binary conventions for C++ are based on a written, vendor-neutral C++ ABI that was designed to be specific to 64-bit Itanium but also includes generic specifications that apply to any platform. We have tried hard to provide a stable ABI that will be compatible with future GCC releases, but it is possible that we will encounter problems that make this difficult.

I think we're fine as regards GCC 4.x versus 5.x. They both appear to use a variant of `libstdc++.so.6`, which is marked as forward-compatible [here](https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html). Indeed, it looks like forward compatibility hasn't been broken since GCC 3.x, so I don't think we have any problems there.

That same page does say that the libraries are *not* backward compatible though. So, assuming we build everything with GCC 4.8, that means any distribution using bottled C++ software must have 4.8 or higher available at runtime. Presumably, this was already the case for `libgcc_s.so` anyways, but if the dependency manager doesn't currently handle this, it will have to for systems whose native compiler is 4.7 or lower.

**Comment by sjackman** [comment]
That's good news, and what I expected given that we haven't yet run into any trouble. Any idea whether GCC 6.x is ABI compatible with GCC 4.8? I know that `The default mode for C++ is now -std=gnu++14 instead of -std=gnu++98`. See https://gcc.gnu.org/gcc-6/changes.html. I've definitely run into trouble even with GCC 5 with libraries that are compiled with `-std=c++11` are not compatible with libraries that are compiled with the default `-std=gnu++98`, e.g. Boost.

**Comment by rwhogg** [comment]
From https://fedoramagazine.org/gcc-5-in-fedora-whats-an-abi-and-what-happens-when-we-change-it/

> GCC 5 implements such an ABI change when the compiler is built with default options from the upstream community sources. It does this order to implement the new C++11 language standard. That provides new features to developers at the cost of binary compatibility – the C++11 requirements on certain C++ core classes requires an ABI change.

Assuming gnu++14 on GCC 6 requires at least as many ABI changes as c++11 or gnu++11 do, that might be a problem.

This might affect #447 . I apologize for the lack of progress here; I've been swamped with schoolwork recently.

**Comment by sjackman** [comment]
No worries, Bob. I've been swamped at work preparing for a conference in a few short weeks, which is why I haven't merged Homebrew into Linuxbrew in a month, which is not great. I'm going to try to make a merge a priority so that we have a few weeks to deal with issues before the conference. I am a bit worried that every bottle that uses C++ will have to be rebuilt, but so it goes I guess.

**Comment by sjackman** [comment]
I had three bottles in Homebrew-Science fail to upload to Bintray:
https://github.com/Linuxbrew/homebrew-science/pull/19
https://github.com/Linuxbrew/homebrew-science/pull/68
https://github.com/Linuxbrew/homebrew-science/pull/99

**Comment by rwhogg** [comment]
The dependency on X11 is obviously correct. So even though the bottle is not ready, I'm going to merge this anyways.

A lot of its dependencies may need to be rebottled soon because of the upstream merge anyways. I'll try to bottle it again once the merge is done.

**Comment by sjackman** [comment]
We've decided to delay the upgrade to `gcc6` because of a likely ABI change, which will require rebuilding all C++ bottles.

**Pull request closed without merging**
