### PR TITLE
man-db 2.7.6.1

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by rwhogg** [comment]
Should we move `man-db` to homebrew-extra?

**Comment by sjackman** [comment]
Yep, sounds good to me.

**Comment by sjackman** [comment]
```
checking for libpipeline... no
configure: error: Package requirements (libpipeline >= 1.4.0) were not met:
Requested 'libpipeline >= 1.4.0' but version of libpipeline is 1.3.1
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/199063012#L2148

**Comment by sjackman** [comment]
`libpipeline.rb` should move to `linuxbrew/extra` as well.

**Comment by rwhogg** [comment]
I've opened https://github.com/Linuxbrew/homebrew-extra/pull/6 to handle the new versions of `libpipeline` and `man-db` and previously migrated them in https://github.com/Linuxbrew/homebrew-extra/pull/4

**Pull request closed without merging**
