### PR TITLE
octave: updates for linuxbrew

### PR DESCRIPTION
**Pull request by dpo**
- [X] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Depends on #3457 and #3452 and probably others.

### CODE REVIEW

**Comment by sjackman** [comment]
```
Your build has exceeded the memory limit of 4G on 1 container.
```
https://circleci.com/gh/Linuxbrew/homebrew-core/7287
https://7287-56942570-gh.circle-artifacts.com/0/tmp/memory-usage.txt

**Comment by sjackman** [comment]
| Jobs | Status |
|---|---|
| 32 | ❌ |
| 24 | |

**Comment by rwhogg** [comment]
Looks like Circle didn't run out of memory this time, but we've now got a C++ 11 ABI issue:

```
libinterp/.libs/liboctinterp.so: undefined reference to `Magick::Image::ping(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libinterp/.libs/liboctinterp.so: undefined reference to `Magick::Image::attribute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
libinterp/.libs/liboctinterp.so: undefined reference to `Magick::CoderInfo::description[abi:cxx11]() const'
libinterp/.libs/liboctinterp.so: undefined reference to `Magick::Image::comment[abi:cxx11]() const'
libinterp/.libs/liboctinterp.so: undefined reference to `Magick::Image::magick[abi:cxx11]() const'
libinterp/.libs/liboctinterp.so: undefined reference to `Magick::CoderInfo::CoderInfo(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/octave-cli] Error 1
```

**Comment by sjackman** [comment]
The usual work around to that is to add
```ruby
# Work around the C++11 ABI issue.
fails_with :gcc => "5" if OS.linux?
```
Migrating to Ubuntu 16 Xenial should resolve this issue.

**Comment by dpo** [comment]
Thanks. I've been trying to reproduce locally but ran into other problems related to `systemd`, which I have to build from source... and it doesn't build. I'll try your suggestion.

**Comment by dpo** [comment]
It worked! Thanks!

**Pull request closed without merging**
