### PR TITLE
moc: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
```
./configure
--prefix=/home/linuxbrew/.linuxbrew/Cellar/jack/0.125.0_1

checking existing, conflicting JACK installs... yes

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
You appear to have at least one existing installation of JACK.

Complete or partial JACK installs exist in: /usr/lib

Installing this version will leave at least one of these
existing installations installed and this will probably break
JACK on your machine. 

Before building, you should first remove the existing JACK
installation(s). 

Alternatively use ./configure --enable-force-install to force
overwriting the existing install.

WARNING: ON ANY DEBIAN-DERIVED DISTRIBUTION (Debian, Ubuntu etc)
CHANGING THE INSTALLATION PREFIX WILL NOT PRODUCE A WORKING JACK
INSTALL. Please contact the distribution packager for JACK and
ask them to fix their packaging.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by maxim-belkin** [comment]
@sjackman do you know which packages should be deleted in circle-ci to avoid the above error?

**Comment by sjackman** [comment]
My guess would be `libjack-jackd2-0` and/or `libjack0`.

**Comment by maxim-belkin** [comment]
thanks!

**Comment by maxim-belkin** [comment]
```
==> brew linkage moc
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /usr/lib/x86_64-linux-gnu/libmagic.so.1
Homebrew libraries:
  /home/linuxbrew/.linuxbrew/lib/libdb-6.2.so (berkeley-db)
  /home/linuxbrew/.linuxbrew/lib/libavcodec.so.57 (ffmpeg)
  /home/linuxbrew/.linuxbrew/lib/libavformat.so.57 (ffmpeg)
  /home/linuxbrew/.linuxbrew/lib/libavutil.so.55 (ffmpeg)
  /home/linuxbrew/.linuxbrew/lib/libFLAC.so.8 (flac)
  /home/linuxbrew/.linuxbrew/lib/libsamplerate.so.0 (libsamplerate)
  /home/linuxbrew/.linuxbrew/lib/libsndfile.so.1 (libsndfile)
  /home/linuxbrew/.linuxbrew/lib/libltdl.so.7 (libtool)
  /home/linuxbrew/.linuxbrew/lib/libvorbisfile.so.3 (libvorbis)
  /home/linuxbrew/.linuxbrew/lib/libncursesw.so.6 (ncurses)
Possible undeclared dependencies:
  flac
  libsamplerate
  libsndfile
  libvorbis
  ncurses
==> brew linkage --test moc
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
  /usr/lib/x86_64-linux-gnu/libmagic.so.1
No broken dylib links
Unwanted system libraries:
  libmagic.so.1
==> FAILED
```

**Comment by maxim-belkin** [comment]
@sjackman what would be a better syntax to say that `libmagic` is optional on mac but required on Linux? I've added
```
  if OS.mac?
    depends_on "libmagic" => :optional
  else
    depends_on "libmagic"
  end
```
but I'm not sure this is the best approach

**Comment by maxim-belkin** [comment]
@sjackman should we delete libjack-jackd2-0 and libjack0 permanently from both Travis and Circle?

**Comment by sjackman** [comment]
Yes

**Pull request closed without merging**
