### PR TITLE
Merge 2017-04-24

### PR DESCRIPTION
**Pull request by maxim-belkin**
Conflicts:
 - [ ] gcc
 - [ ] harfbuzz
 - [ ] libgeotiff
 - [ ] parallel
 - [ ] vim

### CODE REVIEW

**Comment by maxim-belkin** [comment]
@sjackman please review the `gcc` formula.

**Comment by aktau** [comment]
Is there any reason for the GCC version to diverge so between Linuxbrew and Homebrew? This diff looks as follows:

```
    stable do
-     url "http://ftpmirror.gnu.org/gcc/gcc-5.3.0/gcc-5.3.0.tar.bz2"
-     mirror "https://ftp.gnu.org/gnu/gcc/gcc-5.3.0/gcc-5.3.0.tar.bz2"
-     sha256 "b84f5592e9218b73dbae612b5253035a7b34a9a1f7688d2e1bfaaf7267d5c4db"
 -    url "https://ftp.gnu.org/gnu/gcc/gcc-6.3.0/gcc-6.3.0.tar.bz2"
 -    mirror "https://ftpmirror.gnu.org/gcc/gcc-6.3.0/gcc-6.3.0.tar.bz2"
 -    sha256 "f06ae7f3f790fbf0f018f6d40e844451e6bc3b7bc96e128e63b09825c1f8b29f"
++    unless OS.mac?
++      url "http://ftpmirror.gnu.org/gcc/gcc-5.3.0/gcc-5.3.0.tar.bz2"
++      mirror "https://ftp.gnu.org/gnu/gcc/gcc-5.3.0/gcc-5.3.0.tar.bz2"
++      sha256 "b84f5592e9218b73dbae612b5253035a7b34a9a1f7688d2e1bfaaf7267d5c4db"
++    else
++      url "https://ftp.gnu.org/gnu/gcc/gcc-6.3.0/gcc-6.3.0.tar.bz2"
++      mirror "https://ftpmirror.gnu.org/gcc/gcc-6.3.0/gcc-6.3.0.tar.bz2"
++      sha256 "f06ae7f3f790fbf0f018f6d40e844451e6bc3b7bc96e128e63b09825c1f8b29f"
++    end
```

Which appears to tell me that an old "random version" policy was replaced with (older for linux)/(newer for mac).

I'm asking because I can't build `fontconfig --without-docs` anymore because of an illegal instruction error that GCC 5.3.0 is throwing me. I'd wish to try this with a properly maintained GCC version.

**Comment by aktau** [comment]
Apologies, I just tried to edit the formula to get a recent GCC and got this:

These open issues may also help:
gcc stuck at 5 https://github.com/Linuxbrew/homebrew-core/issues/4158
gcc-7: command not found [Fedora 26] https://github.com/Linuxbrew/homebrew-core/issues/3865
Failed to build glibc with gcc 4.4 https://github.com/Linuxbrew/homebrew-core/issues/4077
gcc 5.4.0 and isl 0.18 https://github.com/Linuxbrew/homebrew-core/pull/664

Guess I'll read up on those

**Comment by sjackman** [comment]
Updating GCC was blocked on updating our bottling infrastructure from Ubuntu 14 Trusty using GCC 4.8 to Ubuntu 16 Xenial using GCC 5.3. GCC 4 and 5 are not ABI compatible. We've completed that update. It's no possible, in principle, to update the default `gcc` formula to 7.2.0. We have to first confirm that GCC 5 and GCC 7 are ABI compatible (including C++). As far as I know, they are.

**Pull request closed without merging**
