### PR TITLE
gdal: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by epifanio** [comment]
Not sure this is the right issue where to report build failures. I just tried to install `gdal --head` as the package available is too old for my case of study (1.x)

this the brew log on a linux centos:

```
==> Installing gdal --HEAD --with-complete --with-opencl --with-armadillo --with-libkml --with-postgresql --with-python
==> Cloning https://svn.osgeo.org/gdal/trunk/gdal
==> Downloading https://gist.githubusercontent.com/dakcarto/7abad108aa31a1e53fb4/raw/b56887208fd91d0434d5a901dae3806fb1bd32f8/gdal-armadillo.patch
############################################################################################################################################# 100.0%
==> Patching
==> Applying gdal-armadillo.patch
patching file configure
Hunk #1 FAILED at 29089.
Hunk #2 FAILED at 29114.
2 out of 2 hunks FAILED -- saving rejects to file configure.rej
Error: Failure while executing: patch -g 0 -f -p1 -i /tmp/gdal--patch-20180319-20793-196olzt/gdal-armadillo.patch
```
Then trying to install `without armadillo` i got the following error:

```
[epifanio@jupyter ~]$ brew install gdal --with-complete --with-opencl --with-python --with-libkml --with-postgresql --HEAD
==> Cloning https://svn.osgeo.org/gdal/trunk/gdal
Updating /home/epifanio/.cache/Homebrew/gdal--svn-HEAD
Error: inreplace failed
frmts/jpeg2000/jpeg2000_vsil_io.cpp:
  expected replacement of "s
```

**Comment by iMichka** [comment]
Hi. Your error is unrelated. We do not really support `head` builds. You would get the same error on mac, so this "bug" would need to be reported here: https://github.com/Homebrew/homebrew-core (and fixed there). Ideally the `gdal` developers would make a new release, and we would update the formula.

**Comment by iMichka** [comment]
Blocked by #6393

**Comment by epifanio** [comment]
I see thanks for your reply. The gdal library version 2.2.3 was released 4 months ago. The one available on brew is `GDAL 1.11.5, released 2016/07/01` just a bit out of date. I'll try to have a look at the formula to see if it can be adapted to build  `2.2.3` instead of `head`.

**Comment by iMichka** [comment]
Cool. These changes will need to be submitted here: https://github.com/Homebrew/homebrew-core
You will probably have to change some things in the formula.

Once it is merged there, it will be merged to linuxbrew.

**Comment by epifanio** [comment]
Does it mean I have to test it on OSX first, have it merged there and the see if it works on Linux?

**Comment by iMichka** [comment]
You could work on the Linux version if you have no mac, port the changes to the mac repo. They have an automated CI which will tell you if there are any errors. Tell them you do not own a mac (if it is the case). Normally they prefer that people do not use the CI for testing but in that case they will probably make an exception.

**Comment by iMichka** [comment]
```
libtool: compile:  g++-5 -std=gnu++11 -I/tmp/gdal-20180326-9291-1qd1qjf/gdal-2.2.4/port -I/tmp/gdal-20180326-9291-1qd1qjf/gdal-2.2.4/gcore -I/tmp/gdal-20180326-9291-1qd1qjf/gdal-2.2.4/alg -I/tmp/gdal-20180326-9291-1qd1qjf/gdal-2.2.4/ogr -I/tmp/gdal-20180326-9291-1qd1qjf/gdal-2.2.4/ogr/ogrsf_frmts -I/tmp/gdal-20180326-9291-1qd1qjf/gdal-2.2.4/gnm -I/tmp/gdal-20180326-9291-1qd1qjf/gdal-2.2.4/apps -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2 -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wlogical-op -Wshadow -Werror=vla -Wdate-time -Wfloat-conversion -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wsuggest-override -I../frmts/gtiff -I../frmts/mem -I../frmts/vrt -I../ogr -I../ogr/ogrsf_frmts/generic -I../gnm/ -I../gnm/gnm_frmts/ -I/home/linuxbrew/.linuxbrew/opt/json-c/include/json-c -I../ogr/ogrsf_frmts/geojson -DGNM_ENABLED -I/home/linuxbrew/.linuxbrew/Cellar/gdal/2.2.4/include -I/tmp/gdal-20180326-9291-1qd1qjf/gdal-2.2.4/port -I/home/linuxbrew/.linuxbrew/opt/giflib -I/home/linuxbrew/.linuxbrew/opt/giflib/include -I/home/linuxbrew/.linuxbrew/opt/jpeg -I/home/linuxbrew/.linuxbrew/opt/jpeg/include -I/home/linuxbrew/.linuxbrew/opt/libgeotiff/include -I/home/linuxbrew/.linuxbrew/opt/libtiff/include -I/home/linuxbrew/.linuxbrew/opt/libpng -I/home/linuxbrew/.linuxbrew/opt/libpng/include -I/home/linuxbrew/.linuxbrew/opt/zlib -I/home/linuxbrew/.linuxbrew/opt/zlib/include -DGDAL_COMPILATION -DPAM_ENABLED -c rasterio_ssse3.cpp  -fPIC -DPIC -o .libs/rasterio_ssse3.o
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:37:0,
                 from /tmp/gdal-20180326-9291-1qd1qjf/gdal-2.2.4/port/cpl_port.h:762,
                 from rasterio_ssse3.cpp:29:
/usr/lib/gcc/x86_64-linux-gnu/5/include/tmmintrin.h: In function ‘void GDALUnrolledCopy_GByte_3_1_SSSE3(GByte*, const GByte*, int)’:
/usr/lib/gcc/x86_64-linux-gnu/5/include/tmmintrin.h:136:1: error: inlining failed in call to always_inline ‘__m128i _mm_shuffle_epi8(__m128i, __m128i)’: target specific option mismatch
 _mm_shuffle_epi8 (__m128i __X, __m128i __Y)
 ^
rasterio_ssse3.cpp:77:52: error: called from here
         xmm2 = _mm_shuffle_epi8(xmm2, xmm_shuffle2);
                                                    ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:37:0,
                 from /tmp/gdal-20180326-9291-1qd1qjf/gdal-2.2.4/port/cpl_port.h:762,
                 from rasterio_ssse3.cpp:29:
/usr/lib/gcc/x86_64-linux-gnu/5/include/tmmintrin.h:136:1: error: inlining failed in call to always_inline ‘__m128i _mm_shuffle_epi8(__m128i, __m128i)’: target specific option mismatch
 _mm_shuffle_epi8 (__m128i __X, __m128i __Y)
 ^
rasterio_ssse3.cpp:75:52: error: called from here
         xmm1 = _mm_shuffle_epi8(xmm1, xmm_shuffle1);
                                                    ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:37:0,
                 from /tmp/gdal-20180326-9291-1qd1qjf/gdal-2.2.4/port/cpl_port.h:762,
                 from rasterio_ssse3.cpp:29:
/usr/lib/gcc/x86_64-linux-gnu/5/include/tmmintrin.h:136:1: error: inlining failed in call to always_inline ‘__m128i _mm_shuffle_epi8(__m128i, __m128i)’: target specific option mismatch
 _mm_shuffle_epi8 (__m128i __X, __m128i __Y)
 ^
rasterio_ssse3.cpp:73:52: error: called from here
         xmm0 = _mm_shuffle_epi8(xmm0, xmm_shuffle0);
                                                    ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:37:0,
                 from /tmp/gdal-20180326-9291-1qd1qjf/gdal-2.2.4/port/cpl_port.h:762,
                 from rasterio_ssse3.cpp:29:
/usr/lib/gcc/x86_64-linux-gnu/5/include/tmmintrin.h:136:1: error: inlining failed in call to always_inline ‘__m128i _mm_shuffle_epi8(__m128i, __m128i)’: target specific option mismatch
 _mm_shuffle_epi8 (__m128i __X, __m128i __Y)
 ^
rasterio_ssse3.cpp:77:52: error: called from here
         xmm2 = _mm_shuffle_epi8(xmm2, xmm_shuffle2);
                                                    ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:37:0,
                 from /tmp/gdal-20180326-9291-1qd1qjf/gdal-2.2.4/port/cpl_port.h:762,
                 from rasterio_ssse3.cpp:29:
/usr/lib/gcc/x86_64-linux-gnu/5/include/tmmintrin.h:136:1: error: inlining failed in call to always_inline ‘__m128i _mm_shuffle_epi8(__m128i, __m128i)’: target specific option mismatch
 _mm_shuffle_epi8 (__m128i __X, __m128i __Y)
 ^
rasterio_ssse3.cpp:75:52: error: called from here
         xmm1 = _mm_shuffle_epi8(xmm1, xmm_shuffle1);
                                                    ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:37:0,
                 from /tmp/gdal-20180326-9291-1qd1qjf/gdal-2.2.4/port/cpl_port.h:762,
                 from rasterio_ssse3.cpp:29:
/usr/lib/gcc/x86_64-linux-gnu/5/include/tmmintrin.h:136:1: error: inlining failed in call to always_inline ‘__m128i _mm_shuffle_epi8(__m128i, __m128i)’: target specific option mismatch
 _mm_shuffle_epi8 (__m128i __X, __m128i __Y)
 ^
rasterio_ssse3.cpp:73:52: error: called from here
         xmm0 = _mm_shuffle_epi8(xmm0, xmm_shuffle0);
                                                    ^
GNUmakefile:42: recipe for target 'rasterio_ssse3.lo' failed
make[1]: *** [rasterio_ssse3.lo] Error 1
make[1]: Leaving directory '/tmp/gdal-20180326-9291-1qd1qjf/gdal-2.2.4/gcore'
GNUmakefile:83: recipe for target 'core-target' failed
make: *** [core-target] Error 2
```

**Comment by maxim-belkin** [comment]
I don't like the path to the file:
```
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:37:0,
```
...

**Comment by maxim-belkin** [comment]
Try adding `-msse4.1` to `CMAKE_CXX_FLAGS` ...?

**Comment by tseemann** [comment]
I thought Brew only supported up to SSE2 by default?
By forced compiler settings maybe?

**Comment by iMichka** [comment]
Fixed!

**Pull request closed without merging**
