### PR TITLE
infer: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
> configure: error: python2.7 not found.

**Comment by iMichka** [comment]
```
[ 11%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/Watchdog.cpp.o
[ 11%] Linking CXX static library ../../libLLVMDebugInfoCodeView.a
make[3]: Leaving directory '/tmp/clang-setup.zHzawO/build'
[ 11%] Built target LLVMDebugInfoCodeView
[ 11%] Linking CXX static library ../../libLLVMDebugInfoPDB.a
make[3]: Leaving directory '/tmp/clang-setup.zHzawO/build'
[ 11%] Built target LLVMDebugInfoPDB
[ 11%] Linking CXX static library ../libLLVMSupport.a
make[3]: Leaving directory '/tmp/clang-setup.zHzawO/build'
[ 11%] Built target LLVMSupport
[ 11%] Linking CXX static library ../libLLVMMC.a
make[3]: Leaving directory '/tmp/clang-setup.zHzawO/build'
[ 11%] Built target LLVMMC
make[2]: Leaving directory '/tmp/clang-setup.zHzawO/build'
Makefile:151: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/tmp/clang-setup.zHzawO/build'
Makefile:254: recipe for target 'clang_setup' failed
make: *** [clang_setup] Error 2

  compilation failure; you can try running

    make clean
    ./build-infer.sh all --yes


==> Formula
Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/infer.rb
```

**Comment by thedrow** [comment]
It's failing to build on my machine as well with 16GB of memory and 8GB of swap.
Anyone knows how to build this correctly?

**Comment by iMichka** [comment]
Did you add the python2 change? I need to see the exact error message, because the log I put here is truncated.

You are talking about 16Gb of Ram. Did it fail due to lack of memory?

**Comment by thedrow** [comment]
I didn't add the python2 change.
I can try though.

I think it did since the linker was killed with SIGKILL.

**Comment by iMichka** [comment]
I tried this on my computer with 16 Gb of RAM. The computer froze and I needed to do a hard reboot.

If somebody is willing to pay me for 32 Gb of RAM so I can test again? ...

More seriously, not sure throwing more hardware at this is a good long term solution. Maybe there are some flags or build hints to be passed to reduce the compile time and memory usage?

**Comment by iMichka** [comment]
I need to test this again, I added more swap to my swap partition, this may help.

**Comment by thedrow** [comment]
Any luck?

**Comment by iMichka** [comment]
It's still on my todo list, but now my summer holidays are coming and I have a lot of other stuff to handle, so I do not guarantee that I will be able to look at this before September.

**Pull request closed without merging**
