### PR TITLE
assimp: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
```
==> brew linkage --test assimp
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libgcc_s.so.1
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libz.so.1
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No broken dylib links
Unwanted system libraries:
  libz.so.1
==> FAILED
```

**Comment by sjackman** [comment]
```
Unwanted system libraries:
  libz.so.1
```
It's a mystery to me how it still manages to link against `zlib` without `zlib1g-dev` installed.

**Comment by maxim-belkin** [comment]
the power of will!

**Comment by maxim-belkin** [comment]
from Circle log:
<pre>
DEBIAN_FRONTEND=noninteractive sudo apt-get autoremove -y --purge libblas-dev libbz2-dev libfreetype6-dev libgdbm-dev libicu-dev libidn11-dev libjasper-dev libjbig-dev libkrb5-dev liblzma-dev libncurses5-dev libpcre3-dev libtinfo-dev libwebp-dev libwmf-dev libx11-dev libxml2-dev llvm-3.4 mysql-common zlib1g-dev
Reading package lists... Done

[snip]
Package 'libwebp-dev' is not installed, so not removed
The following extra packages will be installed:
  <b>libxslt1.1</b>
The following packages will be REMOVED:
[snip]
  libxfixes-dev* libxml2-dev* libxrender-dev* <b>libxslt1-dev*</b> libxt-dev*
[snip]
  tsconf* uuid-dev* x11proto-render-dev* <b>zlib1g-dev*</b>
The following packages will be upgraded:
  <b>libxslt1.1</b>
</pre>

**Comment by sjackman** [comment]
So it looks like `zlib1g-dev` is being removed as intended. Here's a possibility. `zlib` is a dependency of a `:build` dependency, so it's present at build time, and then gets removed before `brew linkage` because it's not annotated as being a run-time dependency, then you see this error. That actually seems reasonably likely to me.

**Comment by maxim-belkin** [comment]
I don't understand. System's `zlib` is removed before any Linuxbrew's step. So, how can Linuxbrew link to non-existing `libz.so.1`?

**Comment by sjackman** [comment]
I think it's linking to the brewed `zlib`, which is marked as a recursive build dependency, but is not marked as a run-time dependency. I have not confirmed this hypothesis.

**Pull request closed without merging**
