### PR TITLE
opencoarrays: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
/tmp/opencoarrays-20180811-11543-16cfxv9/OpenCoarrays-2.2.0/src/tests/regression/reported/issue-552-send_by_ref-singleton.f90:23:12:

    allocate(co % c, co % d, co % e, mold=co % b)
            1
Error: Array specification required in ALLOCATE statement at (1)
/tmp/opencoarrays-20180811-11543-16cfxv9/OpenCoarrays-2.2.0/src/tests/regression/reported/issue-552-send_by_ref-singleton.f90:23:20:

    allocate(co % c, co % d, co % e, mold=co % b)
                    1
Error: Array specification required in ALLOCATE statement at (1)
/tmp/opencoarrays-20180811-11543-16cfxv9/OpenCoarrays-2.2.0/src/tests/regression/reported/issue-552-send_by_ref-singleton.f90:23:28:

    allocate(co % c, co % d, co % e, mold=co % b)
                            1
Error: Array specification required in ALLOCATE statement at (1)
Error: comand:
   `/home/linuxbrew/.linuxbrew/bin/gfortran -I/tmp/opencoarrays-20180811-11543-16cfxv9/OpenCoarrays-2.2.0/build/include/OpenCoarrays-2.2.0_GNU-5.5.0 -fcoarray=lib -pthread -Wl,-rpath -Wl,/home/linuxbrew/.linuxbrew/opt/libevent/lib -Wl,-rpath -Wl,/home/linuxbrew/.linuxbrew/Cellar/open-mpi/3.1.1/lib -Wl,--enable-new-dtags -L/home/linuxbrew/.linuxbrew/Cellar/libevent/2.1.8/lib -L/home/linuxbrew/.linuxbrew/Cellar/open-mpi/3.1.1/lib -pthread -I /home/linuxbrew/.linuxbrew/Cellar/open-mpi/3.1.1/include -I /home/linuxbrew/.linuxbrew/Cellar/open-mpi/3.1.1/lib -I /home/linuxbrew/.linuxbrew/include -DPREFIX_NAME=_gfortran_caf_ -DHAVE_MPI -DMPI_WORKING_MODULE -O3 -DNDEBUG -O3 -o /tmp/opencoarrays-20180811-11543-16cfxv9/OpenCoarrays-2.2.0/build/bin/OpenCoarrays-2.2.0-tests/issue-552-send_by_ref-singleton /tmp/opencoarrays-20180811-11543-16cfxv9/OpenCoarrays-2.2.0/src/tests/regression/reported/issue-552-send_by_ref-singleton.f90 /tmp/opencoarrays-20180811-11543-16cfxv9/OpenCoarrays-2.2.0/build/lib/libcaf_mpi.a /home/linuxbrew/.linuxbrew/lib/libmpi_usempif08.so /home/linuxbrew/.linuxbrew/lib/libmpi_usempi_ignore_tkr.so /home/linuxbrew/.linuxbrew/lib/libmpi_mpifh.so /home/linuxbrew/.linuxbrew/lib/libmpi.so`
failed to compile.
```

**Comment by maxim-belkin** [comment]
And that means we'd need to build open-mpi with gcc@7

**Comment by iMichka** [comment]
I am fine with that.

It means rebuilding some bottles though, but there are not so many so this should be good:
```
brew uses --recursive open-mpi
abyss
bsponmpi
dynare
hypre
lammps
opencoarrays
petsc-complex
sundials
boost-mpi
cp2k
gmsh
konoha
octave
petsc
scalapack
```

@sjackman thoughts?

**Comment by sjackman** [comment]
`open-mpi` is C, so I suspect that it's not necessary to rebuild `open-mpi` with GCC 7. I would want to see evidence that it is necessary before going down that path.

**Comment by maxim-belkin** [comment]
If I remember correctly, this is a Homebrew-related problem: one can not use gcc and fcc@7 in one "project":
opencoarrays depend on gcc@7 (normal dep) and open-mpi (normal dep), so open-mpi can not depend on gcc because of conflict with gcc@7.

**Comment by sjackman** [comment]
It may complain about having a versioned and non-versioned dep in the dep tree. Does it?

**Comment by maxim-belkin** [comment]
> It may complain about having a versioned and non-versioned dep in the dep tree. Does it?

I believe this is exactly what is happening here.

**Comment by sjackman** [comment]
Can you please quote the exact error message that you see regarding dep conflicts, ideally in a CircleCI build?

Can we confirm that OpenCoarrays does in fact require GCC 7? I'm not able to find it in their documentation. https://github.com/sourceryinstitute/OpenCoarrays

I'm not able to find this error in their issue tracker
````
Error: Array specification required in ALLOCATE statement
```
https://github.com/sourceryinstitute/OpenCoarrays/issues?q=Error%3A+Array+specification+required+in+ALLOCATE+statement

**Pull request closed without merging**
