### PR TITLE
rust: Build a bottle for Linuxbrew: took more than 120 minutes to run

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by DoomHammer** [comment]
This beast is huuuge!

**Comment by rwhogg** [comment]
I was hoping that `-j12` would work since it worked for you last time, but no such luck. Trying 14 now.

**Comment by rwhogg** [comment]
12 timed out, 14 ran out of memory. Well, this is fun.

**Comment by sjackman** [comment]
Are all its dependencies bottled?

**Comment by DoomHammer** [comment]
@rwhogg, been there, done that. Good old bisection was the only way to find a golden number. But it didn't last long.

**Comment by rwhogg** [comment]
> Are all its dependencies bottled?

Yeah, they are. I think DoomHammer's suggestion is probably the best way forward at this point.

**Pull request closed without merging**
