### PR TITLE
llvm: Update libcxxabi for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
I'm building the bottle locally

**Comment by iMichka** [comment]
@sjackman I guess here too I need to build without --keep-old.

```
Warning: --keep-old is passed but there are changes in: cellar
./llvm-5.0.0_1.x86_64_linux.bottle.tar.gz
  bottle do
    cellar :any
    sha256 "8dfcde31c2251ead3583ab22799cf79f377d0197ef54b762c9c488539a02f7e3" => :x86_64_linux
  end
==> brew bottle --merge --write --no-commit ./llvm-5.0.0_1.x86_64_linux.bottle.json --keep-old
Error: --keep-old was passed but there are changes in:
sha256 => x86_64_linux
==> llvm
==> FAILED
```

**Comment by sjackman** [comment]
> I guess here too I need to build without `--keep-old`.

I didn't think so, because you're bumping the `revision`. It seems I'm wrong about that though. Removing `--keep-old` would likely work. You can also try deleting the `sha256 … => x86_64_linux`.

**Comment by iMichka** [comment]
I removed the sha256, that will work.

**Comment by JuPlutonic** [comment]
removed sha256 … => x86_64_linux line from the recipe
run brew install llvm --with-libcxx => two times got errors connected to coping
(-15Gb HDD free space(/ with /tmp) -8Gb RAM -19Gb Swap partition)
[with-libcxx.zip](https://github.com/Linuxbrew/homebrew-core/files/1460303/with-libcxx.zip)
[with-libcxx2.zip](https://github.com/Linuxbrew/homebrew-core/files/1460304/with-libcxx2.zip)

**Pull request closed without merging**
