### PR TITLE
grafana: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
Reported to core: https://github.com/Homebrew/homebrew-core/pull/15423

**Comment by sjackman** [comment]
```
==> Downloading from https://codeload.github.com/grafana/grafana/tar.gz/v4.4.1
/usr/bin/curl --remote-time --location --user-agent Linuxbrew/1.2.4 (Linux; x86_64 Ubuntu 14.04.5 LTS) curl/7.35.0 --fail --silent https://codeload.github.com/grafana/grafana/tar.gz/v4.4.1 -C 0 -o /home/linuxbrew/.cache/Homebrew/grafana-4.4.1.tar.gz.incomplete
Warning: Formula reports different SHA256: 8579fbed20e745b7dd3e352c5828a6d867524e1069f03a161c2b8e7b9e510cf8
Downloaded to: /home/linuxbrew/.cache/Homebrew/grafana-4.4.1.tar.gz
SHA256: 36c644cd1e630668814235316b76f68758ec5c7f5119e424a73e1bf85a4b969e
==> Verifying grafana-4.4.1.tar.gz checksum
==> FAILED
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/251500849#L1290
Most likely an upstream Homebrew issue.

**Comment by iMichka** [comment]
It is. See my comments above.

**Comment by sjackman** [comment]
Ah, thanks! I think I was looking at a stale page.

**Comment by iMichka** [comment]
I guess that I can close this PR, and wait that the update comes with the regular core merge in the next days?

**Comment by sjackman** [comment]
If you leave this PR open, it prevents `linuxbrew build-botlte-pr` from opening a duplicate PR. Likely not a big deal in this case though, so you can close it.

**Pull request closed without merging**
