### PR TITLE
pypy3: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
Failed to build on CircleCI, but no obvious error message. Will have to try locally to get the complete build log.
https://circleci.com/gh/Linuxbrew/homebrew-core/18034

**Comment by sjackman** [comment]
@maxim-belkin Would you like to look into getting `pypy3` working?

**Comment by maxim-belkin** [comment]
will do!

**Comment by iMichka** [comment]
Superseded by #8402

**Pull request closed without merging**
