### PR TITLE
ghc: Fix build on Linux

### PR DESCRIPTION
**Pull request by dholm**

### CODE REVIEW

**Comment by sjackman** [comment]
Both TravisCI and CircleCI timed out.

**Comment by sjackman** [comment]
Please include a `brew gist-logs` showing the error message that your PR is attempting to resolve. This formula already has a bottle for Linuxbrew, so it looks as though CircleCI did not encounter this error on the previous CI run.

**Comment by dholm** [comment]
https://gist.github.com/dholm/54666fcf95c7dc5c4f0e887c680edf00

**Comment by sjackman** [comment]
Are both `libgmp.so.3` and  `libgmp.so.10` required, or only the latter?

**Comment by dholm** [comment]
@sjackman Only libgmp.so.10, fixed!

**Comment by sjackman** [comment]
Merged. Thanks for your contribution to Linuxbrew, David!

For future PRs, the preferred commit log message is
> ghc: Fix for Linuxbrew

**Pull request merged**
