### PR TITLE
Merge curl 3a4fe74aae

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by iMichka** [comment]
@sjackman A small comment on this.
If you leave `if OS.mac?` in the bottle block; it will fail to build on circle.ci. 
Removing it allows to build a bottle, like you did.

But then you need to add `if OS.mac?` for the relocation, see af46f8a17e035628d540ed27888f12ce738ccf7a

Because if you don't add it back, it will break curl for some of our users.

**Comment by iMichka** [comment]
I added the 'if OS.mac?' back with 15d75a2f13cc96b85a107bfda54d924ed6093e89

**Comment by sjackman** [comment]
Thanks for merging, Michka.

Preventing using the bottle on non-`~linuxbrew/.linuxbrew` installations is handled by `pour_bottle?` now I believe, so `cellar :any` should be fine.
```ruby
  pour_bottle? do
    default_prefix = BottleSpecification::DEFAULT_PREFIX
    reason "The bottle needs to be installed into #{default_prefix} when built with OpenSSL."
    satisfy { OS.mac? || HOMEBREW_PREFIX.to_s == default_prefix }
  end
```
https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/curl.rb#L19

**Comment by iMichka** [comment]
@sjackman See https://github.com/Linuxbrew/homebrew-core/issues/4444

This was the error we got and why I added it back.

**Comment by sjackman** [comment]
```
curl: (77) error setting certificate verify locations:
  CAfile: /home/rcmm/.linuxbrew/etc/openssl/cert.pem
```
I can't say why the `cert.pem` file is missing. It should be installed by `brew postinstall openssl`. The `CAfile` path is correct though. If `curl` had incorrectly been installed by bottle rather than source, the incorrect path would be `CAfile: /home/linuxbrew/.linuxbrew/etc/openssl/cert.pem`.

**Comment by iMichka** [comment]
In #4444, I link to your initial discovery: https://github.com/Linuxbrew/homebrew-core/issues/236

And this commit: https://github.com/Linuxbrew/homebrew-core/commit/c22d002f6d0b8921e6a4f2dcf861312f6568768e

**Comment by sjackman** [comment]
The `pour_bottle?` solution should make `cellar :any if OS.mac?` unnecessary.

```
export CURL_CA_BUNDLE=$(brew --prefix)/etc/openssl/cert.pem
git config --global http.sslCAInfo $(brew --prefix)/etc/openssl/cert.pem
```
https://github.com/Linuxbrew/homebrew-core/issues/236#issuecomment-218055065

I had forgotten about this workaround. We could make a shell script wrapper for `curl` that set the `CURL_CA_BUNDLE` environment variable (if unset). I wonder if that would work for `git` as well.

**Pull request merged**
