### PR TITLE
libunwind: update 1.12 bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by sjackman** [comment]
It's a native Linuxbrew package, so you have to disable `--keep-old`. At the moment that's manual. It could be automated by adding a `--no-keep-old` option to build-bottle-pr.

To do it manually, add a commit that removes `--keep-old ` and `?keep-old=1` from `circle.yml`. When you merge the PR, be remove that commit before pushing `master`.

**Comment by maxim-belkin** [comment]
Can't pull this bottle either

**Comment by sjackman** [comment]
See my above comment about `keep-old`.

**Comment by maxim-belkin** [comment]
done!

**Comment by sjackman** [comment]
Great. After merging, remember to use `git rebase -i` to remove that commit before pushing to `master`.

**Comment by maxim-belkin** [comment]
Closed in 2fd7a2b

**Pull request closed without merging**
