### PR TITLE
gdal: Build a bottle for Linuxbrew: libgdal.so: undefined reference to `curl_multi_info_read'

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
Both CircleCI and TravisCI
```
libtool: link: /home/linuxbrew/.linuxbrew/bin/g++-5 -Wl,--dynamic-linker=/home/linuxbrew/.linuxbrew/lib/ld.so -Wl,-rpath -Wl,/home/linuxbrew/.linuxbrew/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/zlib/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/libpng/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/jpeg/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/giflib/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/libtiff/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/lzlib/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/proj/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/libgeotiff/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/geos/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/json-c/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/libxml2/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/bzip2/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/pcre/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/ncurses/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/readline/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/sqlite/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/freexl/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/liblwgeom/lib -Wl,-rpath=/home/linuxbrew/.linuxbrew/opt/libspatialite/lib .libs/gdalinfo.o .libs/commonutils.o -o .libs/gdalinfo  -L/home/linuxbrew/.linuxbrew/opt/liblwgeom/lib -L/home/linuxbrew/.linuxbrew/lib -L/home/linuxbrew/.linuxbrew/opt/sqlite/lib /tmp/gdal-20170307-5318-1l2nbzy/gdal-1.11.5/.libs/libgdal.so -L/home/linuxbrew/.linuxbrew/opt/json-c/lib -L/home/linuxbrew/.linuxbrew/Cellar/geos/3.6.1/lib -L/home/linuxbrew/.linuxbrew -L/home/linuxbrew/.linuxbrew/opt/libpng -L/home/linuxbrew/.linuxbrew/opt/libpng/lib -L/usr -L/usr/lib -L/home/linuxbrew/.linuxbrew/Cellar/gdal/1.11.5_1/lib -L/home/linuxbrew/.linuxbrew/Cellar/libxml2/2.9.4_2/lib /home/linuxbrew/.linuxbrew/Cellar/proj/4.9.3/lib/libproj.so -lm -ljson-c -lfreexl -lgeos_c -lexpat -lgif -ljpeg -lgeotiff -ltiff -lpng -lpthread -lrt -lspatialite -lsqlite3 -lpcre -lxml2 -lz -ldl  -Wl,-rpath -Wl,/home/linuxbrew/.linuxbrew/Cellar/gdal/1.11.5_1/lib -Wl,-rpath -Wl,/home/linuxbrew/.linuxbrew/Cellar/proj/4.9.3/lib
/tmp/gdal-20170307-5318-1l2nbzy/gdal-1.11.5/.libs/libgdal.so: undefined reference to `curl_multi_info_read'
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/208479404#L3146

**Comment by iMichka** [comment]
@sjackman this is the error:
> ./configure: line 25044: /usr/bin/curl-config: No such file or directory

I could fix this by changing the curl entry to:
> "--with-curl=#{Formula["curl"].opt_bin}/curl-config",

and a `depends_on "curl"`

This should allow us to build bottles for this :)

**Comment by sjackman** [comment]
Thanks for the tip, Michka!

**Comment by sjackman** [comment]
Blocked by `git` https://github.com/Linuxbrew/homebrew-core/pull/2647

**Pull request closed without merging**
