### PR TITLE
nss: fix heinous os specific install logic

### PR DESCRIPTION
**Pull request by carlorosati**
- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Audit complains about .chk files being installed to /lib.

```
% brew audit --strict nss
nss:
  * Non-libraries were installed to "brew/opt/nss/lib"
    Installing non-libraries to "lib" is discouraged.
    The offending files are:
      brew/opt/nss/lib/libfreebl3.chk
      brew/opt/nss/lib/libnssdbm3.chk
      brew/opt/nss/lib/libfreeblpriv3.chk
      brew/opt/nss/lib/libsoftokn3.chk
Error: 1 problem in 1 formula
```
Debian has the following setup. What should Linuxbrew do?

```
/usr/lib/x86_64-linux-gnu/libnss3.so
/usr/lib/x86_64-linux-gnu/libnssutil3.so
/usr/lib/x86_64-linux-gnu/libsmime3.so
/usr/lib/x86_64-linux-gnu/libssl3.so
/usr/lib/x86_64-linux-gnu/nss/libfreebl3.chk
/usr/lib/x86_64-linux-gnu/nss/libfreebl3.so
/usr/lib/x86_64-linux-gnu/nss/libnssckbi.so
/usr/lib/x86_64-linux-gnu/nss/libnssdbm3.chk
/usr/lib/x86_64-linux-gnu/nss/libnssdbm3.so
/usr/lib/x86_64-linux-gnu/nss/libsoftokn3.chk
/usr/lib/x86_64-linux-gnu/nss/libsoftokn3.so
/usr/share/doc/libnss3/changelog.Debian.gz
/usr/share/doc/libnss3/copyright
/usr/share/lintian/overrides/libnss3
```

Adressese issue #1620

### CODE REVIEW

**Comment by sjackman** [comment]
On Mac Homebrew, `nss` installs three `chk` files in `libexec`.
```
/usr/local/Cellar/nss/3.28.1/libexec/libfreebl3.chk
/usr/local/Cellar/nss/3.28.1/libexec/libnssdbm3.chk
/usr/local/Cellar/nss/3.28.1/libexec/libsoftokn3.chk
```
See https://homebrew.bintray.com/bottles/nss-3.28.1.el_capitan.bottle.tar.gz
```sh
curl -L https://homebrew.bintray.com/bottles/nss-3.28.1.el_capitan.bottle.tar.gz | tar t
```

If this patch works on both Mac and Linux, please submit this PR upstream to Homebrew/core. Do you have access to a Mac?

**Comment by sjackman** [comment]
#1619 reports that `nss` depends on `sqlite` for Linuxbrew. Did you experience that?

**Comment by carlorosati** [comment]
Yes. I was planning on closing out both issues with this pull request.

**Comment by carlorosati** [comment]
@sjackman [That](https://github.com/Homebrew/homebrew-core/pull/9935#issuecomment-279511419) was a no-go.

**Comment by sjackman** [comment]
Building a bottle for the dependency `nspr` at https://github.com/Linuxbrew/homebrew-core/pull/1801

**Comment by sjackman** [comment]
```
==> brew audit nss --online
Error: 1 problem in 1 formula
nss:
  * Non-libraries were installed to "/home/linuxbrew/.linuxbrew/opt/nss/lib"
    Installing non-libraries to "lib" is discouraged.
    The offending files are:
      /home/linuxbrew/.linuxbrew/opt/nss/lib/libsoftokn3.chk
      /home/linuxbrew/.linuxbrew/opt/nss/lib/libfreebl3.chk
      /home/linuxbrew/.linuxbrew/opt/nss/lib/libfreeblpriv3.chk
      /home/linuxbrew/.linuxbrew/opt/nss/lib/libnssdbm3.chk
==> FAILED
```
Can you move these `chk` files to `libexec`?

**Comment by carlorosati** [comment]
@sjackman Sure thing.

**Comment by sjackman** [comment]
```
ssl3con.c:38:18: fatal error: zlib.h: No such file or directory
```
https://circleci.com/gh/Linuxbrew/homebrew-core/3754?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Looks like it needs `depends_on "zlib" unless OS.mac?`

**Comment by sjackman** [comment]
Merged with changes. See d50b4d0e62e65b3c6839cd118a3b2371f4b40b9e
Thanks for your contribution to Linuxbrew!

**Pull request closed without merging**
