### PR TITLE
automake 1.16 - replace Perl 'none'

### PR DESCRIPTION
**Pull request by tseemann**
*Resolves https://github.com/Linuxbrew/homebrew-core/issues/6275*

- [ ] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by sjackman** [comment]
Thanks for the patch, Torsten.
@iMichka The issue that this patch is addressing is that current versions of `automake` don't work with old versions of Perl which include an old version of `List::Util` which don't include the function `none`. Three possible solutions are…
1. this PR, which seems pretty straight forward
2. vendor in a recent version of `List::Util`
3. depend on brewed `perl`

Thoughts?

**Comment by tseemann** [comment]
Might be fixed upstream soon enough... but unclear how long to wait. 

```
Date: Sat, 3 Mar 2018 23:50:10 +0100
Subject: [PATCH] automake: Don't rely on List::Util to provide 'none'

This change fixes automake bug#30631.

This removes the use of List::Util which is not supported by Perl 5.6,
by reimplementing the 'none' subroutine.

* lib/Automake/General.pm (none): New subroutine.
* bin/automake.in (handle_single_transform): Use it.
* t/pm/General.pl: New test.
* t/list-of-tests.mk (perl_TESTS): Add it.
---
 bin/automake.in         |  3 +--
 lib/Automake/General.pm | 20 +++++++++++++++++++-
 t/list-of-tests.mk      |  1 +
 t/pm/General.pl         | 27 +++++++++++++++++++++++++++
 4 files changed, 48 insertions(+), 3 deletions(-)
 create mode 100644 t/pm/General.pl

diff --git a/bin/automake.in b/bin/automake.in
index 16fb45182..a52a48951 100644
--- a/bin/automake.in
+++ b/bin/automake.in
@@ -73,7 +73,6 @@ use Automake::Wrap 'makefile_wrap';
 use Automake::Language;
 use File::Basename;
 use File::Spec;
-use List::Util 'none';
 use Carp;
 
 ## ----------------------- ##
@@ -1793,7 +1792,7 @@ sub handle_single_transform
                 my $dname = $derived;
                 if ($directory ne ''
                     && option 'subdir-objects'
-                    && none { $dname =~ /$_$/ } @dup_shortnames)
+                    && none { $dname =~ /$_[0]$/ } @dup_shortnames)
                   {
                     # At this point, we don't clear information about what
                     # parts of $derived are truly file name components.  We can
diff --git a/lib/Automake/General.pm b/lib/Automake/General.pm
index 32f5c8db7..aa2de38b8 100644
--- a/lib/Automake/General.pm
+++ b/lib/Automake/General.pm
@@ -23,7 +23,7 @@ use File::Basename;
 use vars qw (@ISA @EXPORT);
 
 @ISA = qw (Exporter);
-@EXPORT = qw (&uniq $me);
+@EXPORT = qw (&uniq &none $me);
 
 # Variable we share with the main package.  Be sure to have a single
 # copy of them: using 'my' together with multiple inclusion of this
@@ -66,5 +66,23 @@ sub uniq (@)
    return wantarray ? @res : "@res";
 }
 
+# $RES
+# none (&PRED, @LIST)
+# ------------
+# Return 1 when no element in LIST satisfies predicate PRED otherwise 0.
+sub none (&@)
+{
+  my ($pred, @list) = @_;
+  my $res = 1;
+  foreach my $item (@list)
+    {
+      if ($pred->($item))
+        {
+          $res = 0;
+          last;
+        }
+    }
+  return $res;
+}
 
 1; # for require
diff --git a/t/list-of-tests.mk b/t/list-of-tests.mk
index 271bfb573..84dd29af0 100644
--- a/t/list-of-tests.mk
+++ b/t/list-of-tests.mk
@@ -54,6 +54,7 @@ t/pm/DisjCon2.pl \
 t/pm/DisjCon3.pl \
 t/pm/DisjConditions.pl \
 t/pm/DisjConditions-t.pl \
+t/pm/General.pl \
 t/pm/Version.pl \
 t/pm/Version2.pl \
 t/pm/Version3.pl \
diff --git a/t/pm/General.pl b/t/pm/General.pl
new file mode 100644
index 000000000..0caefe7cf
--- /dev/null
+++ b/t/pm/General.pl
@@ -0,0 +1,27 @@
+# Copyright (C) 2018 Free Software Foundation, Inc.
+#
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2, or (at your option)
+# any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <https://www.gnu.org/licenses/>.
+
+use Automake::General;
+
+my $failed = 0;
+
+# Check 'none'.
+my $none_positive = none { $_[0] < 0 } (1, 7, 3, 8, 9);
+$failed = 1 if ($none_positive == 0);
+
+my $none_gt_8 = none { $_[0] >= 8 } (1, 7, 3, 8, 9);
+$failed = 1 if ($none_gt_8 == 1);
+
+exit $failed;
-- 
2.16.2

```

**Comment by sjackman** [comment]
Nice find, Torsten! My preferred fix then is to `patch do` this upstream patch. What's the URL of the patch, Torsten? Can you modify this PR to use the upstream patch?

**Comment by tseemann** [comment]
I can't find a URL for their patch - it was emailed to be.  The GNU github seems to not be public. I am very confused about it.

**Comment by sjackman** [comment]
Where did you find this patch? Can you provide a link to it?

**Comment by sbfnk** [comment]
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=30631

**Comment by sjackman** [comment]
Here's the patch in plain text format.
https://debbugs.gnu.org/cgi/bugreport.cgi?msg=11;att=1;bug=30631;filename=0001-automake-Don-t-rely-on-List-Util-to-provide-none.patch
We can use this in Linuxbrew in a `patch do` block. This patch was posted on 2018-03-03.

**Comment by sjackman** [comment]
@tseemann Please use a `patch do` block with the above `.patch` URL rather than `patch :DATA`.

**Comment by iMichka** [comment]
We may need to use brewed perl though: #6434

Thoughts?

**Comment by sjackman** [comment]
Commented at https://github.com/Linuxbrew/homebrew-core/pull/6434#issuecomment-372176826

**Comment by tundratim** [comment]
@iMichka Do we have an ETA for when this will become part of the release linuxbrew?  I pulled this morning and am still seeing this:

Running automake...
"none" is not exported by the List::Util module
Can't continue after import errors at /opt/TundraWare/tools/opt/automake/bin/automake line 76.
BEGIN failed--compilation aborted at /opt/TundraWare/tools/opt/automake/bin/automake line 76.

**Comment by iMichka** [comment]
Merged. Thanks @tseemann !

**Pull request closed without merging**
