### PR TITLE
gdbm: add GNU_SOURCE flag

### PR DESCRIPTION
**Pull request by gmcbretas**
Like the Spack Package:
https://github.com/citibeth/spack/blob/121306d9bbbeb1c69969a9ef039a622193c70534/var/spack/repos/builtin/packages/gdbm/package.py

- [X] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
This was also reported here (see full discussion and proposed patch): https://github.com/Linuxbrew/homebrew-core/pull/6242#issuecomment-399577553

I would be willing to accept a PR like proposed in my comment. You can rebase this and adapt the patch accordingly. Also, please do not modify the `enable-libgdbm-compat` part.

**Comment by maxim-belkin** [comment]
@iMichka, this PR was submitted from the `master` branch, so...
I'll try cherry-picking it

**Comment by maxim-belkin** [comment]
todo: add `unless OS.mac? || build.bottle?`

**Comment by maxim-belkin** [comment]
Done! Enjoy, guys!

**Comment by iMichka** [comment]
Merged. Thanks @gmcbretas and @okhowang for your help and contributions!

**Comment by gmcbretas** [comment]
I'm happy that all went good! I was trying to recreate my environment of
the PR to give the rigth answers about used versions.

Em qua, 27 de jun de 2018 às 19:06, Michka Popoff <notifications@github.com>
escreveu:

**Pull request closed without merging**
