### PR TITLE
gtk+3: Fix dependencies and test

### PR DESCRIPTION
**Pull request by rwhogg**
- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by maxim-belkin** [comment]
blocked by cairo

**Comment by sjackman** [comment]
`cairo` has a bottle. How is it blocked?

**Comment by maxim-belkin** [comment]
can't push to this branch, so closing this one to open a new one

**Comment by maxim-belkin** [comment]
#2368

**Pull request closed without merging**
