### PR TITLE
git-now: test fails

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by rwhogg** [comment]
```
/home/linuxbrew/.linuxbrew/Cellar/git-now/0.1.1.0/libexec/bin/git-now: 17: /home/linuxbrew/.linuxbrew/Cellar/git-now/0.1.1.0/libexec/bin/git-now-add: Syntax error: "(" unexpected (expecting "fi")
Error: git-now: failed
```

**Comment by sjackman** [comment]
Without looking into this further, it may be cause by the default shell `/bin/sh` being `dash` on Debian distros rather than `bash`.

**Comment by rwhogg** [comment]
You're right, that's exactly the problem.

This is really interesting. `~/.linuxbrew/opt/git-now/libexec/bin/git-now` is a shell script with shebang "#!/bin/sh". `checkbashisms` doesn't complain about it, so that's fine. However, it executes `git-now-add` like this:

```bash
# run command
  . "$GITNOW_DIR/git-now-$SUBCOMMAND"
```

`git-now-add` doesn't have a shebang line, but it contains bashisms:

```bash
checkbashisms /home/bob/.linuxbrew/Cellar/git-now/0.1.1.0/libexec/bin/git-now-add
script /home/bob/.linuxbrew/Cellar/git-now/0.1.1.0/libexec/bin/git-now-add does not appear to have a #! interpreter line;
you may get strange results
possible bashism in /home/bob/.linuxbrew/Cellar/git-now/0.1.1.0/libexec/bin/git-now-add line 29 (bash arrays, ${name[0|*|@]}):
        n=${#args[@]}
possible bashism in /home/bob/.linuxbrew/Cellar/git-now/0.1.1.0/libexec/bin/git-now-add line 35 (bash arrays, ${name[0|*|@]}):
      git add ${args[@]}
```

Which means that if the shell used to run `git-now` isn't `bash`, which it won't be because `/bin/sh` is actually `dash`, then the execution will blow up.

I really wish Debian/Ubuntu had never made the `bash`-to-`dash` change, but oh well.

**Comment by rwhogg** [comment]
The current HEAD of `git-now` has a `#!/bin/bash` shebang. This was fixed [here](https://github.com/iwata/git-now/issues/2).

The last release was made in 2011, but he might be willing to make another one. I think I'll open an issue later today and then submit a PR to Homebrew once the new version is released.

Failing that, we can patch for Linuxbrew, but I'd prefer not to.

**Comment by rwhogg** [comment]
Issue submitted, it's https://github.com/iwata/git-now/issues/12

**Comment by rwhogg** [comment]
@sjackman, would you be okay with patching this? I don't expect this formula to be updated upstream any time soon, and if it is, it will probably result in this issue getting fixed anyways.

**Comment by sjackman** [comment]
Sure, yeah. A patch is fine. I have no problem at all with
```ruby
inreplace bin/"git-now", "#!/bin/sh", "#!/bin/bash"
```

**Pull request closed without merging**
