### PR TITLE
bash-snippets 1.17.2

### PR DESCRIPTION
**Pull request by alexanderepstein**
Updating the formula to include options and match the current homebrew formula

- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alexanderepstein** [comment]
Not sure why but both of the tests failed after the uninstall with a Kernel Error, although the uninstall itself was successful.

**Comment by jonchang** [comment]
A `bash-snippets` update is included in https://github.com/Linuxbrew/homebrew-core/pull/3516. Since Homebrew/core doesn't already have `bash-snippets` 1.17.2 I suggest you open a pull request there for this change. Separately updating formula causes problems when we eventually try to bring down new changes from Homebrew/core, so we don't do it unless it's absolutely critical.

The build failed due to:

```
bash-snippets:
  * A top-level "man" directory was found
    Homebrew requires that man pages live under share.
    This can often be fixed by passing "--mandir=#{man}" to configure.
```

**Comment by alexanderepstein** [comment]
Ah thank you II can fix this change and make an update to homebrew-core, would you be able to add this update over 1.16.0 in #3516?

**Comment by jonchang** [comment]
It will eventually get merged since we're currently about a week or two behind Homebrew/core. As I previously stated:

> Separately updating formula causes problems when we eventually try to bring down new changes from Homebrew/core, so we don't do it unless it's absolutely critical.

**Comment by alexanderepstein** [comment]
Gotcha wasn't sure about the process. Would changing the installation path for the manpage to ```$prefix/share/man/man1``` versus ```$prefix/man/man1``` solve this issue?

**Comment by jonchang** [comment]
Yes.

**Comment by alexanderepstein** [comment]
Awesome, thanks for your help

**Pull request closed without merging**
