### PR TITLE
ghc: Build a bottle for Linuxbrew: Timed out

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
"/tmp/ghc-20170105-11591-4w2foy/ghc-8.0.1/binary/lib/ghc-7.8.4/bin/ghc-pkg" --force --global-package-db "/tmp/ghc-20170105-11591-4w2foy/ghc-8.0.1/binary/lib/ghc-7.8.4/package.conf.d" update rts/dist/package.conf.install
/tmp/ghc-20170105-11591-4w2foy/ghc-8.0.1/binary/lib/ghc-7.8.4/bin/ghc-pkg: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/189227874#L1606

**Comment by sjackman** [comment]
Circle took more than 120 minutes to run

**Comment by maxim-belkin** [comment]
from a local build using `test-bot-docker`:
```
make -C utils/haddock/doc html SPHINX_BUILD=/home/linuxbrew/.linuxbrew/opt/sphinx-doc/bin/sphinx-build
/home/linuxbrew/.linuxbrew/opt/sphinx-doc/bin/sphinx-build -b html . .build-html
/home/linuxbrew/.linuxbrew/opt/sphinx-doc/bin/sphinx-build: /home/linuxbrew/.linuxbrew/Cellar/sphinx-doc/1.5.1/libexec/bin/sphinx-build: /usr/bin/python: bad interpreter: No such file or directory
/home/linuxbrew/.linuxbrew/opt/sphinx-doc/bin/sphinx-build: line 2: /home/linuxbrew/.linuxbrew/Cellar/sphinx-doc/1.5.1/libexec/bin/sphinx-build: Success
make[2]: *** [html] Error 126
make[1]: *** [html_utils/haddock/doc] Error 2
make: *** [all] Error 2
```

**Comment by sjackman** [comment]
The work around is to `sudo apt-get install python-setuptools`, but not ideal clearly.

**Comment by rwhogg** [comment]
A newer version of `ghc` is bottled, so closing.

**Pull request closed without merging**
