### PR TITLE
guile: Build a bottle for Linuxbrew: patchelf: cannot find section .dynstr

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
```
==> brew bottle --verbose --json guile --keep-old
==> Bottling guile-2.2.0.x86_64_linux.bottle.tar.gz...
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath @@HOMEBREW_PREFIX@@/lib:@@HOMEBREW_PREFIX@@/opt/libtool/lib:@@HOMEBREW_PREFIX@@/opt/libffi/lib:@@HOMEBREW_PREFIX@@/opt/libunistring/lib:@@HOMEBREW_PREFIX@@/opt/bdw-gc/lib:@@HOMEBREW_PREFIX@@/opt/gmp/lib:@@HOMEBREW_PREFIX@@/opt/ncurses/lib:@@HOMEBREW_PREFIX@@/opt/readline/lib:@@HOMEBREW_PREFIX@@/Cellar/guile/2.2.0/lib --set-interpreter /lib64/ld-linux-x86-64.so.2 /home/linuxbrew/.linuxbrew/Cellar/guile/2.2.0/bin/guile
cannot find section .dynstr
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/lib:/home/linuxbrew/.linuxbrew/opt/libtool/lib:/home/linuxbrew/.linuxbrew/opt/libffi/lib:/home/linuxbrew/.linuxbrew/opt/libunistring/lib:/home/linuxbrew/.linuxbrew/opt/bdw-gc/lib:/home/linuxbrew/.linuxbrew/opt/gmp/lib:/home/linuxbrew/.linuxbrew/opt/ncurses/lib:/home/linuxbrew/.linuxbrew/opt/readline/lib:/home/linuxbrew/.linuxbrew/Cellar/guile/2.2.0/lib --set-interpreter /home/linuxbrew/.linuxbrew/lib/ld.so /home/linuxbrew/.linuxbrew/Cellar/guile/2.2.0/bin/guile
cannot find section .dynstr
Error: Failure while executing: /home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/lib 
==> FAILED
```

**Comment by maxim-belkin** [comment]
retrying in the superenv

**Comment by sjackman** [comment]
I've opened PR https://github.com/Linuxbrew/brew/pull/365 to address this issue.

**Comment by sjackman** [comment]
Merged #365 and retriggered CI builds of this PR.

**Comment by sjackman** [comment]
Getting there. I've opened PR https://github.com/Linuxbrew/brew/pull/367 to address this issue.

**Comment by sjackman** [comment]
Merged!

**Comment by maxim-belkin** [comment]
Thanks!

**Pull request closed without merging**
