### PR TITLE
gdal: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
building 'osgeo._gdal' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/extensions
gcc-5 -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -msse4.1 -fPIC -I/home/linuxbrew/.linuxbrew/include -I/home/linuxbrew/.linuxbrew/opt/openssl/include -I/home/linuxbrew/.linuxbrew/opt/sqlite/include -I/home/linuxbrew/.linuxbrew/opt/python/include/python3.6m -I/home/linuxbrew/.linuxbrew/opt/python/lib/python3.6/site-packages/numpy/core/include -I/tmp/gdal-20180515-22822-xaw1cc/gdal-2.2.4/include -c extensions/gdal_wrap.cpp -o build/temp.linux-x86_64-3.6/extensions/gdal_wrap.o
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
extensions/gdal_wrap.cpp:3168:22: fatal error: cpl_port.h: No such file or directory
compilation terminated.
error: command 'gcc-5' failed with exit status 1

==> Formula
Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gdal.rb
```

**Comment by Gwang-Jin** [comment]
I failed to install `gdal` with

````
g++-5 -pthread -shared -L/home/skpark/.linuxbrew/lib build/temp.linux-x86_64-3.6/extensions/gdal_wrap.o -L/home/skpark/.linuxbrew/lib -L/home/skpark/.linuxbrew/opt/openssl/lib -L/home/skpark/.linuxbrew/opt/sqlite/lib -L/home/skpark/.linuxbrew/Cellar/python/3.6.5/lib -L/home/skpark/tmp/gdal-20180531-15212-vli4wd/gdal-2.3.0/lib -lpython3.6m -lgdal -o build/lib.linux-x86_64-3.6/osgeo/_gdal.cpython-36m-x86_64-linux-gnu.so
/home/skpark/.linuxbrew/bin/ld: cannot find -lgdal
collect2: error: ld returned 1 exit status
error: command 'g++-5' failed with exit status 1
````

[https://gist.github.com/ec258e0318ffca8fd1d799d9c7492784](https://gist.github.com/ec258e0318ffca8fd1d799d9c7492784)

**Comment by iMichka** [comment]
Here is a full build log: https://gist.github.com/iMichka/cdb0705ccada9c007f2f662599696b6b

**Comment by iMichka** [comment]
> configure: WARNING: unrecognized options: --without-ruby, --without-dwgdirect
(probably unrelated)

**Comment by iMichka** [comment]
> /bin/bash: pkg-config: command not found

**Comment by iMichka** [comment]
Also, this path is passed to the linker: `-L/tmp/gdal-20180714-2693-1926ho4/gdal-2.3.1/lib`, though it does not exist when ld is called. Let's try to disable the parallel build.

**Comment by iMichka** [comment]
Hush bot, I want to work on this at one point :)

**Comment by iMichka** [comment]
```
linuxbrew@3e40aaea99f5:/tmp/gdal-20180811-37368-5m3gqy/gdal-2.3.1$ find . -name "*.so"
./.libs/libgdal.so
```

WTF

**Comment by iMichka** [comment]
Making progress, I was able to solve this by hijacking the LDFLAGS.

Next error is:
```
building 'osgeo._gnm' extension
gcc-5 -DNDEBUG -g -O3 -Wall -msse4.1 -fPIC -I/home/linuxbrew/.linuxbrew/include -I/home/linuxbrew/.linuxbrew/opt/openssl/include -I/home/linuxbrew/.linuxbrew/opt/sqlite/include -I/home/linuxbrew/.linuxbrew/opt/python/include/python3.7m -I/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/numpy/core/include -I/tmp/gdal-20180818-16807-12hhkdm/gdal-2.3.1/include -c extensions/gnm_wrap.cpp -o build/temp.linux-x86_64-3.7/extensions/gnm_wrap.o -std=c++11 -I/tmp/gdal-20180818-16807-12hhkdm/gdal-2.3.1/port -I/tmp/gdal-20180818-16807-12hhkdm/gdal-2.3.1/gcore -I/tmp/gdal-20180818-16807-12hhkdm/gdal-2.3.1/alg -I/tmp/gdal-20180818-16807-12hhkdm/gdal-2.3.1/ogr -I/tmp/gdal-20180818-16807-12hhkdm/gdal-2.3.1/ogr/ogrsf_frmts -I/tmp/gdal-20180818-16807-12hhkdm/gdal-2.3.1/frmts/vrt -I/tmp/gdal-20180818-16807-12hhkdm/gdal-2.3.1/apps
extensions/gnm_wrap.cpp:3144:21: fatal error: gnm_api.h: No such file or directory
```

**Comment by iMichka** [comment]
Fixed! There is a small failure in util-linux, but that is unrelated.

**Pull request closed without merging**
