### PR TITLE
open-mpi: Fix libopen-pal.so: undefined reference to __atomic_compare_exchange_16

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by iMichka** [comment]
```
libtool: link: ( cd ".libs" && rm -f "mca_shmem_sysv.la" && ln -s "../mca_shmem_sysv.la" "mca_shmem_sysv.la" )
make[2]: Leaving directory '/tmp/open-mpi-20180620-5502-1vfrjo3/openmpi-3.1.0/opal/mca/shmem/sysv'
Making all in tools/wrappers
make[2]: Entering directory '/tmp/open-mpi-20180620-5502-1vfrjo3/openmpi-3.1.0/opal/tools/wrappers'
  CC       opal_wrapper.o
  GENERATE opal_wrapper.1
  CCLD     opal_wrapper
../../../opal/.libs/libopen-pal.so: undefined reference to `__atomic_compare_exchange_16'
collect2: error: ld returned 1 exit status
Makefile:1875: recipe for target 'opal_wrapper' failed
make[2]: *** [opal_wrapper] Error 1
make[2]: Leaving directory '/tmp/open-mpi-20180620-5502-1vfrjo3/openmpi-3.1.0/opal/tools/wrappers'
Makefile:2375: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/open-mpi-20180620-5502-1vfrjo3/openmpi-3.1.0/opal'
Makefile:1897: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by sjackman** [comment]
Trying…
```ruby

**Comment by sjackman** [comment]
If this doesn't work, one option is to build a bottle locally on Docker and upload that.

**Comment by iMichka** [comment]
We can do that. I already do that for llvm, qt and rust. It may be a problem if there are more to come.

**Comment by sjackman** [comment]
I'm seeing the same error with `ENV.deparallelize`
```
Making all in tools/wrappers
make[2]: Entering directory '/tmp/open-mpi-20180620-5528-1elo57z/openmpi-3.1.0/opal/tools/wrappers'
  CC       opal_wrapper.o
  CCLD     opal_wrapper
../../../opal/.libs/libopen-pal.so: undefined reference to `__atomic_compare_exchange_16'
collect2: error: ld returned 1 exit status
Makefile:1875: recipe for target 'opal_wrapper' failed
make[2]: *** [opal_wrapper] Error 1
```
https://circleci.com/gh/Linuxbrew/homebrew-core/17486

It's quite curious that the error is not reproducible in a `linuxbrew/linuxbrew` container. It must be either the CPU or the Linux kernel version, I suppose.

Are you able to build a bottle locally, Michka, or shall I?

**Comment by iMichka** [comment]
Can you build and upload it? Because I need to rebuilt and upload qt and llvm5 this weekend. I’ll do the merge/publish once you are done.

**Comment by sjackman** [comment]
Sure. Running `brew test-bot-docker open-mpi` now.

**Comment by sjackman** [comment]
Ahhh. It looks like `brew install open-mpi` succeeds but `brew install --build-bottle open-mpi` fails. So it looks like `-march=core2` is to blame.

**Comment by sjackman** [comment]
We may be able to hack around this by setting the environment variable `HOMEBREW_ARCHFLAGS` to something that works, once we know what that something is.

**Comment by tseemann** [comment]
This works for on RHEL7 now - thank you!

**Comment by sjackman** [comment]
```
Making all in tools/wrappers
make[2]: Entering directory '/tmp/open-mpi-20180626-5474-13dg0ag/openmpi-3.1.0/opal/tools/wrappers'
  CC       opal_wrapper.o
  GENERATE opal_wrapper.1
  CCLD     opal_wrapper
../../../opal/.libs/libopen-pal.so: undefined reference to `__atomic_compare_exchange_16'
collect2: error: ld returned 1 exit status
Makefile:1875: recipe for target 'opal_wrapper' failed
```
https://circleci.com/gh/Linuxbrew/homebrew-core/17678

How curious. `-march=ivybridge` also fails. I wonder how that differs from setting no option…

**Comment by sjackman** [comment]
@iMichka Please merge this PR after https://github.com/Linuxbrew/homebrew-core/pull/8202

**Comment by iMichka** [comment]
Ok no problem. We can go this way. I think when you set nothing it probably tries to determine the best settings based on the current processor. `open-mpi` is probably best recompiled manually if you want to get the most out of it, but I have no experience in that.

**Comment by sjackman** [comment]
Thanks for merging, Michka!

**Pull request closed without merging**
