### PR TITLE
unzip: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
testbot does not create releases for #2430 and #2427

**Comment by maxim-belkin** [comment]
There is a hard-coded `/usr/bin/unzip` in [here](https://github.com/Linuxbrew/homebrew-core/pull/2430/files#diff-d87991cd34d8588a99f1641bcaabd6c3R66). That zip might not exist on some Linux platforms... should we make it depend on something that provides `zip` for Linuxbrew (@sjackman)?

**Comment by sjackman** [comment]
I poked
`http://bot.linuxbrew.sh/ci-upload/github.com/Linuxbrew/homebrew-core/pull/2430?keep-old=1`
```
Error: unzip-6.0_3.x86_64_linux.bottle.tar.gz is already published. Please remove it manually from
```
https://bintray.com/linuxbrew/bottles/unzip/view#files

**Comment by sjackman** [comment]
I've deleted the bottle from Bintray and repoked `bot.linuxbrew.sh`

**Comment by sjackman** [comment]
`bind` PR #2427 had the same problem.

**Comment by sjackman** [comment]
> There is a hard-coded `/usr/bin/unzip` in here. That zip might not exist on some Linux platforms... should we make it depend on something that provides zip for Linuxbrew (@sjackman)?

I'd change it to `OS.mac? ? "/usr/bin/unzip" : "unzip"` but I wouldn't add a new dependency just for `test`.

**Pull request closed without merging**
