### PR TITLE
pypy: Depends on zlib

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
error: zlib.h: No such file or directory
```
https://circleci.com/gh/Linuxbrew/homebrew-core/17010

**Comment by sjackman** [comment]
```
error: openssl/comp.h: No such file or directory
```
See https://github.com/Linuxbrew/homebrew-core/pull/7523
and https://github.com/Homebrew/homebrew-core/pull/27108
The upstream issue has been closed, so I hoped this issue had been resolved, but it seems not. How is `pypy` building successfully on macOS?

**Comment by iMichka** [comment]
It does not build anymore. The bottle was built with an older version of the openssl formula.

**Comment by iMichka** [comment]
https://github.com/Homebrew/homebrew-core/pull/29129

comp is back, you can rebase this.

**Comment by maxim-belkin** [comment]
```
Add more commits by pushing to the bottle-pypy branch on sjackman/homebrew-core.
```
You can rebase this too!

**Comment by sjackman** [comment]
Yeah! Thanks for the heads up, Michka. Rebased.

**Comment by sjackman** [comment]
Failed on CircleCI, but built successfully on TravisCI !?
```
==> /tmp/pypy-20180618-5131-1y96u6e/pypy2-v6.0.0-src/bootstrap/bin/pypy /tmp/pypy-20180618-5131-1y96u6e/pypy2-v6.0.0-src/rpython/bin/rpython -Ojit --shared --cc gcc-5 --verbose --make-jobs 32 targetpypystandalone.py
.................................
Last 150 lines from /home/linuxbrew/.cache/Homebrew/Logs/pypy/01.pypy:
[flowgraph] (rpython.jit.metainterp.pyjitpl:3162)MetaInterp.direct_assembler_call
[flowgraph] (rpython.jit.metainterp.warmstate:683)get_assembler_token
[flowgraph] (rpython.jit.metainterp.warmstate:683)get_assembler_token
…
[flowgraph] (rpython.jit.metainterp.warmstate:683)get_assembler_token
[flowgraph] (rpython.jit.metainterp.warmstate:683)get_assembler_token
[flowgraph] (rpython.jit.metainterp.compile:1125)compile_tmp_callback
[flowgraph] (rpython.rlib.rjitlog.rjitlog:327)tmp_callback
[flowgraph] (rpython.jit.metainterp.pyjitpl:1532)MIFrame.handle_possible_overflow_error
…
```
https://circleci.com/gh/Linuxbrew/homebrew-core/17411

I see that it's using `--make-jobs 32`. I wonder whether it's exceeding available memory.

**Comment by sjackman** [comment]
Looks like the same error with `--make-jobs 4`. I'll try 1.
https://circleci.com/gh/Linuxbrew/homebrew-core/17419

**Comment by sjackman** [comment]
Looks like the same with `--make-jobs 1`. I don't see an actual error message here though, at least in the last 150 lines. I'll try it in Docker.
```
==> /tmp/pypy-20180618-5155-9v0ip9/pypy2-v6.0.0-src/bootstrap/bin/pypy /tmp/pypy-20180618-5155-9v0ip9/pypy2-v6.0.0-src/rpython/bin/rpython -Ojit --shared --cc gcc-5 --verbose --make-jobs 1 targetpypystandalone.py
............................................
Last 150 lines from /home/linuxbrew/.cache/Homebrew/Logs/pypy/01.pypy:
[flowgraph] (rpython.rtyper.lltypesystem.rordereddict:1012)ll_dict_lookup
[flowgraph] (?:2)ll_dict_lookup_trampoline
[flowgraph] (rpython.rtyper.lltypesystem.rordereddict:1012)ll_dict_lookup
…
[flowgraph] (?:1)memo__sizeof_none_0
[flowgraph] (rpython.rtyper.rlist:562)ll_copy
[flowgraph] (rpython.rtyper.rlist:709)ll_getitem
```
https://circleci.com/gh/Linuxbrew/homebrew-core/17421

**Comment by sjackman** [comment]
I haven't sadly been able to get this to compile successfully on CircleCI. =/

@iMichka Could you please squash-merge this PR anyway after PR https://github.com/Linuxbrew/homebrew-core/pull/8133 ?

**Comment by sjackman** [comment]
I got somewhat further on a local build.

`02.pypy`
```
2018-06-21 17:21:36 -0700

/var/tmp/sjackman/pypy-20180621-125208-1y8zgff/pypy2-v6.0.0-src/bootstrap/bin/pypy
package.py
--archive-name
pypy
--targetdir
.

/var/tmp/sjackman/pypy-20180621-125208-1y8zgff/pypy2-v6.0.0-src/bootstrap/bin/pypy: /gsc/btl/linuxbrew/opt/openssl/lib/libssl.so.1.0.0: no version information available (required by /var/tmp/sjackman/pypy-20180621-125208-1y8zgff/pypy2-v6.0.0-src/bootstrap/bin/libpypy-c.so)
/var/tmp/sjackman/pypy-20180621-125208-1y8zgff/pypy2-v6.0.0-src/bootstrap/bin/pypy: /gsc/btl/linuxbrew/opt/openssl/lib/libcrypto.so.1.0.0: no version information available (required by /var/tmp/sjackman/pypy-20180621-125208-1y8zgff/pypy2-v6.0.0-src/bootstrap/bin/libpypy-c.so)
/var/tmp/sjackman/pypy-20180621-125208-1y8zgff/pypy2-v6.0.0-src/bootstrap/bin/pypy: /gsc/btl/linuxbrew/opt/openssl/lib/libssl.so.1.0.0: no version information available (required by /var/tmp/sjackman/pypy-20180621-125208-1y8zgff/pypy2-v6.0.0-src/bootstrap/bin/libpypy-c.so)
/var/tmp/sjackman/pypy-20180621-125208-1y8zgff/pypy2-v6.0.0-src/bootstrap/bin/pypy: /gsc/btl/linuxbrew/opt/openssl/lib/libcrypto.so.1.0.0: no version information available (required by /var/tmp/sjackman/pypy-20180621-125208-1y8zgff/pypy2-v6.0.0-src/bootstrap/bin/libpypy-c.so)
* _audioop_build.py
* _curses_build.py
* _gdbm_build.py
* _pwdgrp_build.py
* _resource_build.py
* _sqlite3_build.py
* _syslog_build.py
* _tkinter/tklib_build.py
 *** TCL libraries not found!  Falling back...
/gsc/btl/linuxbrew/bin/ld: cannot find -ltcl
/gsc/btl/linuxbrew/bin/ld: cannot find -ltk
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "_tkinter/tklib_build.py", line 66, in <module>
    library_dirs = libdirs
  File "/var/tmp/sjackman/pypy-20180621-125208-1y8zgff/pypy2-v6.0.0-src/lib_pypy/cffi/api.py", line 451, in verify
    lib = self.verifier.load_library()
  File "/var/tmp/sjackman/pypy-20180621-125208-1y8zgff/pypy2-v6.0.0-src/lib_pypy/cffi/verifier.py", line 104, in load_library
    self._compile_module()
  File "/var/tmp/sjackman/pypy-20180621-125208-1y8zgff/pypy2-v6.0.0-src/lib_pypy/cffi/verifier.py", line 201, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "/var/tmp/sjackman/pypy-20180621-125208-1y8zgff/pypy2-v6.0.0-src/lib_pypy/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/var/tmp/sjackman/pypy-20180621-125208-1y8zgff/pypy2-v6.0.0-src/lib_pypy/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
VerificationError: LinkError: command 'cc' failed with exit status 1

!!!!!!!!!!
Building tk bindings failed.
                You can either install development headers package,
                add the --without-tk option to skip packaging this
                binary CFFI extension, or say --without-cffi.

HOMEBREW_VERSION: 1.6.9
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: 3ba4c2ed9b0587040949a4a9a95b576f520bae84
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: e29d97e5968de087e927e960326e3952e1cbf9e7
Core tap last commit: 80 minutes ago
HOMEBREW_PREFIX: /gsc/btl/linuxbrew
HOMEBREW_REPOSITORY: /gsc/btl/linuxbrew/Homebrew
HOMEBREW_CELLAR: /gsc/btl/linuxbrew/Cellar
HOMEBREW_CACHE: /gsc/btl/linuxbrew/var/cache/homebrew
CPU: 128-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /gsc/btl/linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby
Clang: N/A
Git: 2.16.2 => /gsc/btl/linuxbrew/bin/git
Curl: 7.29.0 => /usr/bin/curl
Java: N/A
Kernel: Linux 3.10.0-229.14.1.el7.x86_64 x86_64 GNU/Linux
OS: CentOS Linux release 7.1.1503 (Core)  (Core)
Host glibc: 2.17
/usr/bin/gcc: 4.8.3
glibc: 2.23
gcc: 5.5.0_4
xorg: 20170115_1

HOMEBREW_CC: gcc-5
HOMEBREW_CXX: g++-5
MAKEFLAGS: -j128
CMAKE_PREFIX_PATH: /gsc/btl/linuxbrew
PKG_CONFIG_PATH: /gsc/btl/linuxbrew/opt/ncurses/lib/pkgconfig:/gsc/btl/linuxbrew/opt/sqlite/lib/pkgconfig:/gsc/btl/linuxbrew/opt/openssl/lib/pkgconfig:/gsc/btl/linuxbrew/opt/libbsd/lib/pkgconfig:/gsc/btl/linuxbrew/opt/expat/lib/pkgconfig:/gsc/btl/linuxbrew/opt/libffi/lib/pkgconfig:/gsc/btl/linuxbrew/opt/zlib/lib/pkgconfig
ACLOCAL_PATH: /gsc/btl/linuxbrew/share/aclocal
PATH: /gsc/btl/linuxbrew/Homebrew/Library/Homebrew/shims/linux/super:/gsc/btl/linuxbrew/opt/pkg-config/bin:/gsc/btl/linuxbrew/opt/gdbm/bin:/gsc/btl/linuxbrew/opt/ncurses/bin:/gsc/btl/linuxbrew/opt/sqlite/bin:/gsc/btl/linuxbrew/opt/openssl/bin:/gsc/btl/linuxbrew/opt/bzip2/bin:/gsc/btl/linuxbrew/opt/expat/bin:/gsc/btl/linuxbrew/opt/binutils/bin:/gsc/btl/linuxbrew/opt/make/bin:/usr/bin:/bin:/usr/sbin:/sbin:/gsc/btl/linuxbrew/opt/gcc/bin
LD_LIBRARY_PATH: /gsc/btl/linuxbrew/opt/openssl/lib:/gsc/btl/linuxbrew/opt/bzip2/lib
```

**Comment by maxim-belkin** [comment]
`brew install tcl-tk`?

**Comment by sjackman** [comment]
Now however it's failing with…
```
[translation:ERROR] ValueError: running 'pkg-config libffi --cflags-only-I' failed:
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
and the default ['/usr/include/libffi'] is not a valid directory
```
even though it depends on `pkg-config` and `libffi`. Sigh. This formula is cursed.

**Comment by sjackman** [comment]
Yeah, I tried adding `tcl-tk` to the dependencies. Now it's failing with this wacky `pkg-config` and `libffi` error above, which is pretty weird. I don't believe that error is related to adding `tcl-tk` though.

**Comment by maxim-belkin** [comment]
Yeah, my comment was related to:
> *** TCL libraries not found!  Falling back...
/gsc/btl/linuxbrew/bin/ld: cannot find -ltcl
/gsc/btl/linuxbrew/bin/ld: cannot find -ltk

**Comment by maxim-belkin** [comment]
https://pypy.readthedocs.io/en/latest/build.html

`pip install cffi` ? :)

**Comment by sjackman** [comment]
I think I have to give up on this PR. Here's my work in progress.

```diff
commit 78311b4c630972f83ac134d4e1f1a0a967fc8a2c
Author: Shaun Jackman <sjackman@gmail.com>
Date:   Wed May 30 10:37:13 2018 -0700

    pypy: Depends on zlib [Linux]
    
    Fix error: zlib.h: No such file or directory

diff --git a/Formula/pypy.rb b/Formula/pypy.rb
index 87c9b35b17..43dd8668a8 100644
--- a/Formula/pypy.rb
+++ b/Formula/pypy.rb
@@ -23,8 +23,11 @@ class Pypy < Formula
   depends_on "sqlite" => :recommended
   depends_on "openssl"
   unless OS.mac?
+    depends_on "bzip2"
     depends_on "expat"
     depends_on "libffi"
+    depends_on "tcl-tk"
+    depends_on "zlib"
   end
 
   resource "bootstrap" do
@@ -51,6 +54,11 @@ class Pypy < Formula
   fails_with :gcc
 
   def install
+    # Fix pypy: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
+    ENV["LD_LIBRARY_PATH"] = Formula["bzip2"].lib
+    # Fix error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
+    ENV.prepend_path "LD_LIBRARY_PATH", Formula["openssl"].lib
+
     # Having PYTHONPATH set can cause the build to fail if another
     # Python is present, e.g. a Homebrew-provided Python 2.x
     # See https://github.com/Homebrew/homebrew/issues/24364
```
78311b4c630972f83ac134d4e1f1a0a967fc8a2c

**Comment by maxim-belkin** [comment]
Time permitting, I'll play around with it.

**Comment by sjackman** [comment]
That'd be great. Thanks, Maxim. I've found `pypy3` to be about twice as fast as `python3`.

**Comment by maxim-belkin** [comment]
attempt 1: https://gist.github.com/af912436e1fae523deba9042fde29742

**Comment by maxim-belkin** [comment]
what works:
```
        incdirs = ['/home/linuxbrew/.linuxbrew/opt/tcl-tk/include' + _ver]
        linklibs = ['tcl8.6' + _ver, 'tk8.6' + _ver]
```

**Comment by maxim-belkin** [comment]
getting closer. There was a mistake in extracting instructions: `tar -xzf ... pypy....tar.bz2`
On macOS, `-z` is ignored, on Linux - results in an error.

**Comment by iMichka** [comment]
Cool. Happy you are having a closer look. BTW you may want to update, with #8190 the bootstrapping got updated.

**Comment by maxim-belkin** [comment]
> BTW you may want to update, with #8190 the bootstrapping got updated.

no kidding?

**Comment by iMichka** [comment]
Lol I did not see that it was you. I do not always look at who makes changes when merging :)

The -z option is gone too with the last merge.

**Comment by maxim-belkin** [comment]
> The -z option is gone too with the last merge.

RIP 😢

**Comment by maxim-belkin** [comment]
success: https://gist.github.com/2cf403871a60280f2fad5a249a11c60c
```
$ brew test pypy
Testing pypy
==> /home/linuxbrew/.linuxbrew/Cellar/pypy/6.0.0/bin/pypy -c print('Hello, world!')
Hello, world!
==> /home/linuxbrew/.linuxbrew/Cellar/pypy/6.0.0/bin/pypy -c import time; time.clock()
==> /home/linuxbrew/.linuxbrew/share/pypy/pip list
Package    Version
---------- -------
cffi       1.11.5 
greenlet   0.4.13 
pip        10.0.1 
readline   6.2.4.1
setuptools 39.2.0 
```

**Comment by sjackman** [comment]
Woohoo!

**Pull request closed without merging**
