### PR TITLE
qwt: qmake: Option -spec requires a parameter

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
Blocked by qt5 #1144

**Comment by sjackman** [comment]
Circle
```
==> /home/linuxbrew/.linuxbrew/Cellar/qt5/5.7.0/bin/qmake -config release -spec
.
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/qwt/01.qmake:
2016-10-29 16:51:38 +0000

/home/linuxbrew/.linuxbrew/Cellar/qt5/5.7.0/bin/qmake
-config
release
-spec

***Option -spec requires a parameter
```

**Comment by sjackman** [comment]
Travis `The job exceeded the maximum time limit for jobs, and has been terminated.`

**Comment by JuPlutonic** [comment]
I only replaced -spec:
```
Warning: qwt dependency gettext was built with a different C++ standard
library (libstdc++ from gcc-5). This may cause problems at runtime.
🍺  /home/linuxbrew/.linuxbrew/Cellar/qwt/6.1.3_4: 1,670 files, 19MB, built in 4 minutes 7 seconds
```

**Pull request closed without merging**
