### PR TITLE
netcdf: move libraries from lib64/ to lib/ on linux

### PR DESCRIPTION
**Pull request by sbfnk**
- [X] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by sbfnk** [comment]
Thanks @iMichka. I've updated and re-pushed the commit.

My understanding is that the separation is for systems that support multiple binary formats (e.g., 32-bit and 64-bit) - macOS doesn't so for homebrew it make sense to assume everything is in lib/. I imagine that's why brew only links lib/ while ignoring lib64/.

**Comment by iMichka** [comment]
Yes but then we should put the path to lib64 for all the formulae, instead of treating each formula manually one by one?

**Comment by sjackman** [comment]
On Linuxbrew we do not support multiarch. All libraries are install in `lib`. Some packages try to get fancy and detect a multiarch system and change the library directory from the one specified (with `--libdir` or `$prefix/lib`) to some other place. The biggest problem with this behaviour is that there's often not an easy way to override it. Thankfully this behaviour is pretty rare. Individual fixups like this one are fine by me. `configure --libdir=#{lib}` would be preferable if it worked. In other packages I've found that it doesn't. The packages replaces the last directory component specified with `lib64`.

**Comment by sbfnk** [comment]
Latest update uses `cmake`'s `-DCMAKE_INSTALL_LIBDIR` to achieve this, instead of moving files around.

**Comment by sjackman** [comment]
The only error is…
```
==> brew bottle --merge --write --no-commit ./netcdf-4.5.0_1.x86_64_linux.bottle.json --keep-old
Error: --keep-old was passed but there are changes in:
sha256 => x86_64_linux
```
which you can ignore. Looks good to me.

**Comment by sjackman** [comment]
I transfered the bottles to Bintray omitting `--keep-old`:
```
http://bot.linuxbrew.sh/ci-upload/github.com/Linuxbrew/homebrew-core/pull/4958
```

**Comment by sjackman** [comment]
Thanks for your contribution to Linuxbrew, Sebastian.

**Comment by sjackman** [comment]
Merged!

**Pull request closed without merging**
