### PR TITLE
openssl: fix issues with build

### PR DESCRIPTION
**Pull request by kyungminlee**
1. `makedepend` does not correctly find header files in `/usr/include/ARCH`. Use compiler instead.
2. SELinux and Bash on Windows disallows executable stack for `libcrypto.so`. Pass `--noexecstack` to assembler.

### CODE REVIEW

**Comment by sjackman** [comment]
> `makedepend` does not correctly find header files in `/usr/include/ARCH`. Use compiler instead.

Could you submit this patch upstream to the `openssl` developers?

**Comment by sjackman** [comment]
> SELinux and Bash on Windows disallows executable stack for libcrypto.so. Pass --noexecstack to assembler.

Should `-Wa,--noexecstack` be added to the default `CFLAGS` for Linuxbrew? Is there any downside to doing so?

**Comment by sjackman** [comment]
Here's a related post: https://github.com/Microsoft/BashOnWindows/issues/471#issuecomment-271080328

**Comment by kyungminlee** [comment]
Regarding the `makedepend` issue https://github.com/Linuxbrew/homebrew-core/pull/1510/commits/2159d2cabd4eb8ab6362d16bc27cc4841b0cba12, there is an open pull request on `openssl` related to this: https://github.com/openssl/openssl/pull/1524.

**Comment by sjackman** [comment]
Here's the related Debian bug for the openssl executable stack:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=321721
The workaround is
```sh
sudo execstack -c libssl.so.0.9.7
```
The fix adopted by Debian is the same as yours, to add `-Wa,--noexecstack` to `CFLAGS`.

**Comment by sjackman** [comment]
Does https://github.com/openssl/openssl/pull/1524 resolve your issue? If so, I suggest using
```ruby
patch do
    url "https://github.com/openssl/openssl/pull/1524.patch"
    sha256 "853a15755d3bc2b561d64c4f5d58a7ff4885e5cdbacbf429ce93b477e0d3d68e"
end
```

I agree with the following change, but please add a comment above
```
# openssl does not in fact require an executable stack.
ENV.append_to_cflags "-Wa,--noexecstack" if OS.linux?
```

**Comment by sjackman** [comment]
Merged. Thanks for your contribution to Linuxbrew, @kyungminlee! Note that I have not updated the binary bottles. The fix to `noexecstack` does required updating the bottles. That update will happen with the next release of `openssl` (or upstream Homebrew change to `openssl`). If this issue causes significant trouble to Windows users, we may consider bumping the bottle version ahead of upstream (but we try to avoid that if possible).

**Comment by sjackman** [comment]
Test on Travis CI failed. I haven't seen this failure before, but doesn't seem related to this PR. Odd.
```
==> brew test openssl --verbose
Testing openssl
Error: openssl: failed
OpenSSL requires the .cnf file for some functionality
==> FAILED
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/190705869#L1648

**Comment by kyungminlee** [comment]
The current bottle doesn't seem to contain `.bottle` directory, which is supposed to include files in `etc/openssl`.

**Comment by sjackman** [comment]
Curious. I wonder why that would be.
@Linuxbrew/core Any thoughts on the above CI failure, and whether we should disable this failed `brew test` until the next upstream rebuild of `openssl`, or bump `revision` and rebuild it now?

**Comment by kyungminlee** [comment]
Don't know why `.bottle` is missing. All the previous versions seem to contain it. Perhaps `HOMEBREW_PREFIX/etc/openssl` was not properly removed before buidling the bottle? I am +1 for rebuilding the bottle.

**Comment by sjackman** [comment]
That could be. For some reason `circle.yml` was `brew` installing `curl` rather than using the host's curl. Coincidentally, I reverted that in 4dade4a26a just today.

Other than this `brew test openssl` failure, how does the lack of config files affect the user?

**Comment by kyungminlee** [comment]
openssl doesn't work without `openssl.cnf`:

```
$ mv ~/.brew/etc/openssl ~/.brew/etc/openssl.old
$ openssl req -new
WARNING: can't open config file: /home/kyungminlee/.brew/etc/openssl/openssl.cnf
Unable to load config info from /home/kyungminlee/.brew/etc/openssl/openssl.cnf
```

**Comment by sjackman** [comment]
I've opened https://github.com/Linuxbrew/homebrew-core/pull/1559 to rebuild the bottle for `openssl`

**Pull request closed without merging**
