### PR TITLE
python: Enable select.poll for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
This issue has been moved to https://github.com/Linuxbrew/homebrew-core/issues/674

**Comment by bjwatson** [comment]
Thanks, Shaun. Looks much better now:

```
$ python ~/.linuxbrew/Cellar/python/2.7.12_1/lib/python2.7/test/test_poll.py
test_poll1 (__main__.PollTests) ... ok
test_poll2 (__main__.PollTests) ... ok
test_poll3 (__main__.PollTests) ... ok
test_poll_c_limits (__main__.PollTests) ... ok
test_threaded_poll (__main__.PollTests) ... ok

----------------------------------------------------------------------
Ran 5 tests in 10.526s

OK
brianwatson@brianwatson0:~/.linuxbrew/Library/Taps/homebrew/homebrew-core$ brew info python
python: stable 2.7.12, HEAD
Interpreted, interactive, object-oriented programming language
https://www.python.org
~/.linuxbrew/Cellar/python/2.7.12_1 (5,431 files, 105.0M) *
  Built from source on 2016-07-26 at 17:50:56
From: https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/python.rb
==> Dependencies
Build: xz ✔, pkg-config ✔, gpatch ✔
Required: openssl ✔, bzip2 ✔
Recommended: readline ✔, sqlite ✔, gdbm ✔
Optional: homebrew/dupes/tcl-tk ✘, berkeley-db4 ✘
==> Options
--universal
	Build a universal binary
--with-berkeley-db4
	Build with berkeley-db4 support
--with-quicktest
	Run `make quicktest` after the build (for devs; may fail)
--with-tcl-tk
	Use Homebrew's Tk instead of OS X Tk (has optional Cocoa and threads support)
--with-unicode-ucs4
	Build unicode support with UCS4
--without-gdbm
	Build without gdbm support
--without-poll
	Disable select.poll
--without-readline
	Build without readline support
--without-sqlite
	Build without sqlite support
--HEAD
	Install HEAD version
==> Caveats
Pip and setuptools have been installed. To update them
  pip install --upgrade pip setuptools

You can install Python packages with
  pip install <package>

They will install into the site-package directory
  ~/.linuxbrew/lib/python2.7/site-packages

See: https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Homebrew-and-Python.md

```

**Comment by sjackman** [comment]
Glad to hear it. Merged!

**Comment by bjwatson** [comment]
Thanks!

**Pull request closed without merging**
