### PR TITLE
docbook-utils 0.6.14 (new formula) [WIP; do not merge]

### PR DESCRIPTION
**Pull request by sjackman**
+ docbook-utils 0.6.14 (new formula)
  Convert DocBook files to other formats (HTML, RTF, PS, man, PDF)
+ openjade 1.3.2 (new formula)
  Implementation of the DSSSL language
+ opensp 1.5.2 (new formula)
  OpenJade group's SGML parsing tools

### CODE REVIEW

**Comment by sjackman** [comment]
Circle
```
warning: failed to load external entity "/usr/share/sgml/docbook/xml-dtd-4.1.2/docbookx.dtd"
validity error : Could not load the external subset "/usr/share/sgml/docbook/xml-dtd-4.1.2/docbookx.dtd"
Document /tmp/opensp-20161101-112444-1u90v5g/OpenSP-1.5.2/docsrc/osgmlnorm.xml does not validate
xmlto: /tmp/opensp-20161101-112444-1u90v5g/OpenSP-1.5.2/docsrc/osx.xml does not validate (status 3)
xmlto: Fix document syntax or use --skip-validation option
make[2]: *** [osgmlnorm.1] Error 13
```

**Comment by maxim-belkin** [comment]
quick and dirty fix: `--disable-doc-build`

**Comment by maxim-belkin** [comment]
good ref: [here](http://www.linuxfromscratch.org/blfs/view/svn/pst/opensp.html)

**Comment by sjackman** [comment]
> --disable-doc-build: This switch prevents the configure script checking if you have xmlto installed. If you have xmlto, you can remove this option.


We do have `xmlto` installed, but I take it that it's not working.

**Comment by rwhogg** [comment]
I got the following trying to install `opensp`:

```
/home/linuxbrew/.linuxbrew/bin/xmlto man osgmlnorm.xml
xmlto: Can't continue, xsltproc tool not found or not executable.
```

Looks like `xmlto` needs an (at least `:recommended`) dependency on `libxslt` on Linux. Not necessary on macOS because `xsltproc` is included in /usr/bin there.

**Comment by rwhogg** [comment]
Also worth noting after I installed `opensp`:

```
Warning: A top-level "man" directory was found
Homebrew requires that man pages live under share.
This can often be fixed by passing "--mandir=#{man}" to configure.
```

**Comment by sjackman** [comment]
Feel free to take over this PR, if you want it, Bob!

**Comment by rwhogg** [comment]
Superceded by #1185

**Pull request closed without merging**
