### PR TITLE
gtk+3: Depends on egl: Blocked by libepoxy #276

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by rwhogg** [comment]
I've been having trouble with GTK+3 for two months or so now. I'm fairly certain it's blocked by OpenGL support.

@maxim-belkin, could you provide some guidance on this? Do you know what formulae need to be installed on Linux for OpenGL to work?

**Comment by sjackman** [comment]
The dependency `cairo` fails to build.
```
checking whether cairo's Xlib surface backend feature could be enabled... no (requires X development libraries)
configure: error:  Xlib surface backend feature could not be enabled
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/146879905#L3129

**Comment by sjackman** [comment]
```
checking for EGL... no
configure: error: Package requirements (egl) were not met:
No package 'egl' found
Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
Alternatively, you may set the environment variables EGL_CFLAGS
and EGL_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/147108322#L3776

**Comment by sjackman** [comment]
Blocked by libepoxy #276

**Comment by sjackman** [comment]
Merged without updating the bottle.

**Pull request closed without merging**
