### PR TITLE
aamath: Depends on flex and readline

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by rwhogg** [comment]
From https://travis-ci.org/Linuxbrew/homebrew-core/builds/216995706#L2052

```
aamath.cc:19:31: fatal error: readline/readline.h: No such file or directory
```

`depends_on "readline"`?

**Comment by sjackman** [comment]
```
g++ -g parser.o lexer.o expr.o canvas.o aamath.o  -o aamath -lreadline -ltermcap
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -ltermcap
collect2: error: ld returned 1 exit status
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/217024877#L2087

**Comment by sjackman** [comment]
On Debian, `libtermcap.so` is provided by binary package `libtinfo-dev` and by source package `ncurses`.
On Linuxbrew, `libtermcap.so` should probably be a symlink to `libncursesw.so`.

**Comment by sjackman** [comment]
`ln -s libncursesw.so libtermcap.so` does in fact resolve the build failure.

**Comment by sjackman** [comment]
Blocked by https://github.com/Linuxbrew/homebrew-core/pull/2239

**Comment by rwhogg** [comment]
Closing in favour of #2340

**Pull request closed without merging**
