### PR TITLE
mitmproxy: fix depends_on "libffi" unless OS.mac?

### PR DESCRIPTION
**Pull request by emanresusername**
- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by emanresusername** [comment]
not familiar with whats going on with the `--build-bottle` task, any pointers on that?

**Comment by iMichka** [comment]
Hi. The actual error is:
> distutils.errors.CompileError: command 'gcc-5' failed with exit status 1
> SystemExit: error: command 'gcc-5' failed with exit status 1

Is this compiling for you locally? The log is truncated, but I bet we are hitting the 4 Gb memory limit of the circle. Not sure how to tell the install script to use less cores during the build.

Often we write something like this at the top of the install block:
```
    # Reduce memory usage below 4 GB for Circle CI.
    ENV["MAKEFLAGS"] = "-j16" if ENV["CIRCLECI"]
```

**Comment by emanresusername** [comment]
yeah it works locally, i'll give the makeflags a try...

**Comment by emanresusername** [comment]
no luck with the makeflags :cry:

**Comment by iMichka** [comment]
Please try with -j1 to be sure. But I am not sure the python setup uses make internally. The source code needs to be double-checked for that.

**Comment by emanresusername** [comment]
no luck with `-j1` either :sob:

**Comment by emanresusername** [comment]
@iMichka un-stale-ify?

**Comment by iMichka** [comment]
We could try also to use ‘-j4 -l2.5’. The l flag tells make to reduce the load. No guarantee it will work.

**Comment by emanresusername** [comment]
>     c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory

looks like the test machines might need to have `libffi-dev` installed?

https://github.com/Nexmo/nexmo-python/issues/16#issuecomment-260355631
https://github.com/josenavas/QiiTa/blob/master/INSTALL.md#c_cffi_backendc1517-fatal-error-ffih-no-such-file-or-directory
https://code.djangoproject.com/ticket/26952
http://eavesdrop.openstack.org/irclogs/%23openstack-infra/%23openstack-infra.2017-10-04.log.html#t2017-10-04T09:26:16

**Comment by iMichka** [comment]
Add these lines:

```
# pkg-config helps setuptools find libffi
depends_on "pkg-config" => :build
```

**Comment by emanresusername** [comment]
Looks like that did it!! 
Lmk if/which of the intermediate iterations should be reverted/squashed etc

**Comment by iMichka** [comment]
Good. Can you regroup the two new dependencies in a single `unless OS.mac?` block?

And then squash everything to a single commit? Feel confident using `git rebase -i`? If not, I can do the squashing myself before merging.

**Comment by emanresusername** [comment]
done and done :+1:

**Comment by iMichka** [comment]
@emanresusername Thanks for your contribution!

**Pull request closed without merging**
