### PR TITLE
libmaa: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by rwhogg** [comment]
From https://travis-ci.org/Linuxbrew/homebrew-core/builds/152208070#L1223

```
/home/linuxbrew/.linuxbrew/bin/glibtool: line 10548: /usr/bin/gcc-4.8: No such file or directory
```

```bash
% strings ~/.linuxbrew/bin/glibtool | grep gcc-4.8
LTCC="/usr/bin/gcc-4.8"
CC="/usr/bin/gcc-4.8"
```

@sjackman, it looks like the `libtool` bottle has the same problem the Python bottles did: they hardcode a compiler reference.

**Comment by sjackman** [comment]
Eep. Good to know. I wish packages wouldn't do that. I'll look into it.

**Comment by sjackman** [comment]
I'm super confused by this. The command line specifies to use `gcc-5` to link, and then `libtool` ignores that and uses `gcc-4.8` instead. I don't think it's supposed to do that.

```
glibtool --tag=CC --mode=link /home/linuxbrew/.linuxbrew/bin/gcc-5 -o libmaa.la strlcpy.lo obstack.lo xmalloc.lo hash.lo set.lo stack.lo list.lo error.lo memory.lo string.lo debug.lo flags.lo maa.lo prime.lo bit.lo timer.lo arg.lo pr.lo sl.lo base64.lo base26.lo source.lo parse-concrete.lo text.lo log.lo \
	   -L/home/linuxbrew/.linuxbrew/lib -Wl,--dynamic-linker=/home/linuxbrew/.linuxbrew/lib/ld.so -Wl,-rpath,/home/linuxbrew/.linuxbrew/lib -lm \
	   -rpath "/home/linuxbrew/.linuxbrew/Cellar/libmaa/1.3.2/lib" -export-symbols ./export.sym \
	   -version-info 3:0
glibtool: link: echo "{ global:" > .libs/libmaa.ver
glibtool: link:  cat ./export.sym | sed -e "s/\(.*\)/\1;/" >> .libs/libmaa.ver
glibtool: link:  echo "local: *; };" >> .libs/libmaa.ver
glibtool: link:  /usr/bin/gcc-4.8 -shared  -fPIC -DPIC  .libs/strlcpy.o .libs/obstack.o .libs/xmalloc.o .libs/hash.o .libs/set.o .libs/stack.o .libs/list.o .libs/error.o .libs/memory.o .libs/string.o .libs/debug.o .libs/flags.o .libs/maa.o .libs/prime.o .libs/bit.o .libs/timer.o .libs/arg.o .libs/pr.o .libs/sl.o .libs/base64.o .libs/base26.o .libs/source.o .libs/parse-concrete.o .libs/text.o .libs/log.o   -L/home/linuxbrew/.linuxbrew/lib -lm  -Wl,--dynamic-linker=/home/linuxbrew/.linuxbrew/lib/ld.so -Wl,-rpath -Wl,/home/linuxbrew/.linuxbrew/lib   -Wl,-soname -Wl,libmaa.so.3 -Wl,-version-script -Wl,.libs/libmaa.ver -o .libs/libmaa.so.3.0.0
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/152208070#L1223

**Comment by sjackman** [comment]
I don't think `libtool` is broken for every formula (I hope), but it certainly seems to be broken for this one.

**Comment by sjackman** [comment]
This test works for me on a system that does not have `/usr/bin/gcc-4.8` installed.
```
printf '#include <stdio.h>\nint main() { puts("Hello, world!"); return 0; }' >hello.c
libtool --mode=compile --tag=CC gcc -c hello.c -o hello.o
libtool --mode=link --tag=CC gcc hello.o -o hello
```

**Comment by rwhogg** [comment]
Blocked by #376

**Pull request closed without merging**
