### PR TITLE
llvm@4: rebuild bottle with -02 for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**
The last time the bottle was built was on 2017-09-09

I would like to rebuild this with `-02` to reduce the bottle size, and to make `llvm@4` compile stuff faster.

As there will probably be no more updates to llvm 4, there is not point to wait for a new release. This is why I bumped the revision.

### CODE REVIEW

**Comment by xu-cheng** [comment]
FYI, I never have found the time to port #7565 to other `llvm@*` formulae. In which, it fixed the issue that old llvm formula bypasses superenv. Therefore, the `-O2` rebuild may not work as intended.

The related code is: https://github.com/Linuxbrew/homebrew-core/blob/6b6506fc57bf5800ffe98b7a0b9cbb39a22a4caf/Formula/llvm%404.rb#L255-L256

**Comment by iMichka** [comment]
Okay, looks like I'll need to work on backporting the changes to llvm@4 then :)

**Comment by iMichka** [comment]
@xu-cheng I made a first attempt to backport the changes from `llvm` to `llvm@4`. The only thing I did not do here is to backport your patch.

The lib/Driver/ToolChains/Gnu.cpp and lib/Driver/ToolChains/Linux.cpp files do not exist in `llvm@4`.
I guess that the code is somewhere hidden in the more generic `Toolchain.cpp`. As you seem to have more experience with that part, would you like to backport your patch? Just to avoid that I need to spend too much time digging through the clang code :)

**Comment by sjackman** [comment]
It's also an option to say that `llvm@4` is not supported on Linux. The only formula that uses it is `ispc`.

**Comment by xu-cheng** [comment]
@iMichka 

As requested, https://github.com/xu-cheng/clang/commit/2813f6d3c65d2b45a32ff9e124f9e40a0f9363cd

Noted that I did not test it.

**Pull request closed without merging**
