### PR TITLE
alsa-lib: bottles are not added if keep-old is passed and there's no existing bottle block

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by rwhogg** [comment]
Circle failure is the same old keep-old nonsense. Merging.

**Comment by rwhogg** [comment]
On `brew pull --bottle`:

```
==> Verifying bottles published on Bintray
Warning: No bottle defined in formula alsa-lib
```

Uh-huh. Clearly there's a problem when using `--keep-old` but no existing bottle block exists.

**Comment by sjackman** [comment]
The bottle is published on Bintray. You could just manually commit a bottle block:
```
  bottle do
    sha256 "1adadace25e90c1dd8ae1253477868e85ba6f11668ed1c4624dcbc91f18ac499" => :x86_64_linux
  end
```

**Comment by rwhogg** [comment]
Thanks for the tip Shaun! Merged.

**Pull request closed without merging**
