### PR TITLE
terminal-notifier: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by sjackman** [comment]
```
❯❯❯ brew desc terminal-notifier
terminal-notifier: Send macOS User Notifications from the command-line
```
From the description, good chance this will need
```ruby
depends_on :macos
```

**Comment by iMichka** [comment]
In fact it already has a `depends_on :macos`. It was opened automatically when I ran:
> linuxbrew build-bottle-pr doxygen heroku irssi mikutter ntl remarshal tippecanoe vim you-get ponyc

**Comment by sjackman** [comment]
That's a bug in `brew build-bottle-pr` then. It already ignores `bottle :disabled` and `:unneeded`. Care to submit a fix PR?
See https://github.com/Linuxbrew/homebrew-developer/blob/master/cmd/brew-build-bottle-pr.rb#L101-L104

**Comment by iMichka** [comment]
Let me try this :)

**Pull request closed without merging**
